### ISSUE TITLE
gst-plugins-base fails to install with options enabled

### ISSUE THREAD

**Issue by purebordem** [Homebrew/homebrew-core#10074]
Attempting to install gst-plugins-base --with-opus, ogg, vorbis, etc. Using any "--with-" from available options causes install to fail. Python quits unexpectedly. If I install without any options, install succeeds.

https://gist.github.com/anonymous/cc79a9753e4296da7e61592f5f357599

```
HOMEBREW_VERSION: 1.1.10
ORIGIN: https://github.com/Homebrew/brew
HEAD: 69d1cedd12d37d6a9535fbba17d2129b165c08f8
Last commit: 2 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 8174f1e1fb5f3d1b277a3969466e13dbdbc1ce7e
Core tap last commit: 84 minutes ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_REPOSITORY: /usr/local/Homebrew
HOMEBREW_CELLAR: /usr/local/Cellar
HOMEBREW_BOTTLE_DOMAIN: https://homebrew.bintray.com
CPU: quad-core 64-bit broadwell
Homebrew Ruby: 2.0.0-p648
Clang: 8.0 build 800
Git: 2.10.1 => /Library/Developer/CommandLineTools/usr/bin/git
Perl: /usr/bin/perl
Python: /usr/local/bin/python => /usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/bin/python2.7
Ruby: /usr/bin/ruby => /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin/ruby
Java: N/A
macOS: 10.12.2-x86_64
Xcode: N/A
CLT: 8.2.0.0.1.1480973914
X11: N/A
```

```
Warning: Unbrewed dylibs were found in /usr/local/lib.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected dylibs:
  /usr/local/lib/libmp3lame.0.0.0.dylib
  /usr/local/lib/libmp3lame.0.dylib

Warning: Unbrewed header files were found in /usr/local/include.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected header files:
  /usr/local/include/lame/lame.h

Warning: Unbrewed static libraries were found in /usr/local/lib.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected static libraries:
  /usr/local/lib/libmp3lame.a

Warning: You have unlinked kegs in your Cellar
Leaving kegs unlinked can lead to build-trouble and cause brews that depend on
those kegs to fail to run properly once built. Run `brew link` on these:
  lame
```

```
File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/unixccompiler.py", line 111, in preprocess
    raise CompileError, msg
distutils.errors.CompileError: command 'clang' terminated by signal 10
make[5]: *** [GstVideo-1.0.gir] Error 1
make[4]: *** [all] Error 2
make[3]: *** [video] Error 2
make[2]: *** [all-recursive] Error 1
make[1]: *** [all-recursive] Error 1
make: *** [all] Error 2
```

**Comment by purebordem** [comment]
Install was successful. Not sure what happened on the original install.

**Comment by ilovezfs** [comment]
>Install was successful. Not sure what happened on the original install.

It's possibly something problematic lurking in your site-packages directory.

**Comment by ProfFan** [comment]
I've got a similar problem. Attaching important logs below:
```
  GEN      GstTag-1.0.gir
Traceback (most recent call last):
  File "/usr/local/Cellar/gobject-introspection/1.52.1/bin/g-ir-scanner", line 66, in <module>
    sys.exit(scanner_main(sys.argv))
  File "/usr/local/Cellar/gobject-introspection/1.52.1/lib/gobject-introspection/giscanner/scannermain.py", line 538, in scanner_main
    ss = create_source_scanner(options, args)
  File "/usr/local/Cellar/gobject-introspection/1.52.1/lib/gobject-introspection/giscanner/scannermain.py", line 446, in create_source_scanner
    ss.parse_files(filenames)
  File "/usr/local/Cellar/gobject-introspection/1.52.1/lib/gobject-introspection/giscanner/sourcescanner.py", line 262, in parse_files
    self._parse(headers)
  File "/usr/local/Cellar/gobject-introspection/1.52.1/lib/gobject-introspection/giscanner/sourcescanner.py", line 305, in _parse
    self._cpp_options)
  File "/usr/local/Cellar/gobject-introspection/1.52.1/lib/gobject-introspection/giscanner/ccompiler.py", line 200, in preprocess
    extra_postargs=extra_postargs)
  File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/unixccompiler.py", line 113, in preprocess
    raise CompileError, msg
distutils.errors.CompileError: command ['clang', '-E', u'-D_REENTRANT', u'-U__BLOCKS__', '-I.', u'-I/private/tmp/gst-plugins-base-20170707-34266-1vc2avz/gst-plugins-base-1.12.1/gst-libs', u'-I/usr/local/Cellar/pcre/8.40/include', u'-I/usr/local/Cellar/glib/2.52.3/include/glib-2.0', u'-I/usr/local/Cellar/glib/2.52.3/lib/glib-2.0/include', u'-I/usr/local/Cellar/gettext/0.19.8.1/include', u'-I/usr/local/Cellar/gstreamer/1.12.1/include/gstreamer-1.0', '-o', u'g-ir-cpp-A6IhRX.i', '-C', u'/tmp/g-ir-cpp-A6IhRX.c'] terminated by signal 10
```

No idea what **['clang', '-E', u'-D_REENTRANT', u'-U__BLOCKS__', '-I.', u'-I/private/tmp/gst-plugins-base-20170707-34266-1vc2avz/gst-plugins-base-1.12.1/gst-libs', u'-I/usr/local/Cellar/pcre/8.40/include', u'-I/usr/local/Cellar/glib/2.52.3/include/glib-2.0', u'-I/usr/local/Cellar/glib/2.52.3/lib/glib-2.0/include', u'-I/usr/local/Cellar/gettext/0.19.8.1/include', u'-I/usr/local/Cellar/gstreamer/1.12.1/include/gstreamer-1.0', '-o', u'g-ir-cpp-A6IhRX.i', '-C', u'/tmp/g-ir-cpp-A6IhRX.c'] terminated by signal 10** means. It seems to be when the gir file is being generated.

**Comment by ProfFan** [comment]
After careful investigation, it is actually `Python` that is crashing with SIGBUS. The `distutils` module falsely reported the error.

Stacktrace:
```
System Integrity Protection: enabled

Crashed Thread:        0  Dispatch queue: com.apple.main-thread

Exception Type:        EXC_BAD_ACCESS (SIGBUS)
Exception Codes:       KERN_PROTECTION_FAILURE at 0x000000010689b6d2
Exception Note:        EXC_CORPSE_NOTIFY

VM Regions Near 0x10689b6d2:
    VM_ALLOCATE            0000000106506000-00000001065c6000 [  768K] rw-/rwx SM=COW  
--> MALLOC_LARGE           00000001065c6000-0000000106ac8000 [ 5128K] rw-/rwx SM=COW  
    MALLOC_TINY            00007ff2c8400000-00007ff2c8800000 [ 4096K] rw-/rwx SM=COW  

Application Specific Information:
crashed on child side of fork pre-exec

Thread 0 Crashed:: Dispatch queue: com.apple.main-thread
0   libsystem_kernel.dylib        	0x00007fff95051d42 __pthread_kill + 10
1   libsystem_pthread.dylib       	0x00007fff9513f457 pthread_kill + 90
2   libsystem_c.dylib             	0x00007fff94f68497 raise + 26
3   libsystem_platform.dylib      	0x00007fff95132b3a _sigtramp + 26
4   org.python.python             	0x0000000105835cd1 frame_dealloc + 19
5   libsystem_c.dylib             	0x00007fff94f69437 fork + 47
6   org.python.python             	0x00000001058c8aba posix_fork + 16
7   org.python.python             	0x0000000105893bd8 PyEval_EvalFrameEx + 11282
8   org.python.python             	0x0000000105890de5 PyEval_EvalCodeEx + 1579
9   org.python.python             	0x0000000105899be2 fast_function + 290
...
```
Looks like that the problem is with Python. I tried the the reported clang command and it runs smoothly in my shell.

@ilovezfs Can we reopen this issue?

**Comment by ilovezfs** [comment]
@ProfFan did you attempt the steps here: https://github.com/Homebrew/homebrew-core/issues/10074#issuecomment-280724938

**Comment by ProfFan** [comment]
@ilovezfs Looks like this is doing a completely new install of homebrew :(

Anyway I will try it. THX!

**Comment by ProfFan** [comment]
@ilovezfs It worked! Just still a little bit curious about the root cause. Thank you very much!

**Comment by ilovezfs** [comment]
@ProfFan me tool. I don't think we can consider this truly resolved until it stops happening, but would prefer a PR fixing it over just leaving this issue sitting here open. I'm glad the not-so-great workaround worked for you.
