### ISSUE TITLE
python-debug: UnicodeDecodeError: 'ascii' codec can't decode byte

### ISSUE THREAD

**Issue by todd-dsm** [Homebrew/homebrew-core#10158]
# Troubleshooting steps:
- [x ] Ran `brew update` and retried your prior step? yes
- [x ] Ran `brew doctor`, fixed as many issues as possible and retried your prior step? only common warnings
- [ ] Confirmed this is problem with specific formulae and not Homebrew/brew? no

### Bug report:
Hey guys, I realize this probably isn't a homebrew formula issue but I'm going to start the conversation here:
* I can't duplicate this issue on Fedora; it works without error. 
* On Debian there is some flakey behavior but a different error message though; not sure if it's related. But, here's what I'm seeing:

```bash
pip3 install python-debug
Collecting python-debug
  Using cached python-debug-0.1.3.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/pip-build-s_jbjzh2/python-debug/setup.py", line 19, in <module>
        long_description = open('README.markdown').read(),
      File "/usr/local/Cellar/python3/3.6.0/Frameworks/Python.framework/Versions/3.6/lib/python3.6/encodings/ascii.py", line 26, in decode
        return codecs.ascii_decode(input, self.errors)[0]
    UnicodeDecodeError: 'ascii' codec can't decode byte 0xd0 in position 926: ordinal not in range(128)
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/pip-build-s_jbjzh2/python-debug/
```

I'm a bit lost when it comes to platform-specific Unicode issues.

Fedora install:

```bash
$ sudo pip3 install --upgrade pip
Collecting pip
  Downloading pip-9.0.1-py2.py3-none-any.whl (1.3MB)
    100% |████████████████████████████████| 1.3MB 935kB/s 
Installing collected packages: pip
  Found existing installation: pip 8.1.2
    Uninstalling pip-8.1.2:
      Successfully uninstalled pip-8.1.2
Successfully installed pip-9.0.1
$ sudo pip3 install python-debug
Collecting python-debug
  Downloading python-debug-0.1.3.tar.gz
Installing collected packages: python-debug
  Running setup.py install for python-debug ... done
Successfully installed python-debug-0.1.3
```

Debian install:
```bash
$ sudo apt-get upgrade python3-pip
...

$ sudo pip3 install --upgrade python-debug
Downloading/unpacking python-debug
  Downloading python-debug-0.1.3.tar.gz
  Running setup.py (path:/tmp/pip-build-n747ibor/python-debug/setup.py) egg_info for package python-debug

Installing collected packages: python-debug
  Running setup.py install for python-debug
      File "/usr/local/lib/python3.4/dist-packages/pydebug/__init__.py", line 26
        print xmlformat(text, encoding)
                      ^
    SyntaxError: invalid syntax
    
    
Successfully installed python-debug
Cleaning up...
```

I understand that the distro-provided packages should be used for installing additional python packages but this is the only way to draw-out some equivalent behavior.

**Comment by MikeMcQuaid** [comment]
> Hey guys, I realize this probably isn't a homebrew formula issue but I'm going to start the conversation here:

You're right, sorry.
