### ISSUE TITLE
Installing a Python module in user + editable mode doesn't work

### ISSUE THREAD

**Issue by ubitux** [Homebrew/homebrew-core#101987]
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

```shell
$ brew config
HOMEBREW_VERSION: 3.4.11
ORIGIN: https://github.com/Homebrew/brew
HEAD: 30e3d8883cde265cbc16ff94b49a3ac14137590e
Last commit: 10 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 43c907a2a3c8c42a4d9fa691bba49f45f3cf047e
Core tap last commit: 2 hours ago
Core tap branch: master
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CASK_OPTS: []
HOMEBREW_CORE_GIT_REMOTE: https://github.com/Homebrew/homebrew-core
HOMEBREW_MAKE_JOBS: 8
Homebrew Ruby: 2.6.8 => /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.8/bin/ruby
CPU: octa-core 64-bit haswell
Clang: 13.1.6 build 1316
Git: 2.32.1 => /Applications/Xcode.app/Contents/Developer/usr/bin/git
Curl: 7.79.1 => /usr/bin/curl
macOS: 12.4-x86_64
CLT: 13.4.0.0.1.1651278267
Xcode: 13.4
```

```shell
$ brew doctor
Your system is ready to brew.
```

### Verification

- [X] I ran `brew update` and am still able to reproduce my issue.
- [x] I have resolved all warnings from `brew doctor` and that did not fix my problem.

### What were you trying to do (and why)?

Any Python module installed with `pip install --user --editable <module>` will not work properly. `--user` only works, `--editable` only works, but not both. This is not reproducible on Linux with matching versions of pip and setuptools.

Here is a sample Python module for testing:
```
% find simplemodule
simplemodule
simplemodule/simplemodule
simplemodule/simplemodule/__init__.py
simplemodule/simplemodule/cli.py
simplemodule/setup.py
```

`__init__.py`: empty
`cli.py`:
```python
def main():
    print("I am a simple Python module")
```
`setup.py`:
```python
from setuptools import setup

setup(
    name="simplemodule",
    version="0.1",
    description="A simple module",
    packages=["simplemodule"],
    entry_points={
        "console_scripts": [
            "simplemodule-cli=simplemodule.cli:main",
        ],
    },
)
```

### What happened (include all command output)?

```
% pip -v install --user -e simplemodule
Using pip 22.1 from /usr/local/lib/python3.9/site-packages/pip (python 3.9)
Obtaining file:///Users/ux/test-python/simplemodule
  Running command python setup.py egg_info
  running egg_info
  creating /private/var/folders/7j/xklxvnfd7l5gzbz4c8x03rbw0000gn/T/pip-pip-egg-info-4npfauj5/simplemodule.egg-info
  writing /private/var/folders/7j/xklxvnfd7l5gzbz4c8x03rbw0000gn/T/pip-pip-egg-info-4npfauj5/simplemodule.egg-info/PKG-INFO
  writing dependency_links to /private/var/folders/7j/xklxvnfd7l5gzbz4c8x03rbw0000gn/T/pip-pip-egg-info-4npfauj5/simplemodule.egg-info/dependency_links.txt
  writing entry points to /private/var/folders/7j/xklxvnfd7l5gzbz4c8x03rbw0000gn/T/pip-pip-egg-info-4npfauj5/simplemodule.egg-info/entry_points.txt
  writing top-level names to /private/var/folders/7j/xklxvnfd7l5gzbz4c8x03rbw0000gn/T/pip-pip-egg-info-4npfauj5/simplemodule.egg-info/top_level.txt
  writing manifest file '/private/var/folders/7j/xklxvnfd7l5gzbz4c8x03rbw0000gn/T/pip-pip-egg-info-4npfauj5/simplemodule.egg-info/SOURCES.txt'
  reading manifest file '/private/var/folders/7j/xklxvnfd7l5gzbz4c8x03rbw0000gn/T/pip-pip-egg-info-4npfauj5/simplemodule.egg-info/SOURCES.txt'
  writing manifest file '/private/var/folders/7j/xklxvnfd7l5gzbz4c8x03rbw0000gn/T/pip-pip-egg-info-4npfauj5/simplemodule.egg-info/SOURCES.txt'
  Preparing metadata (setup.py) ... done
Installing collected packages: simplemodule
  Running setup.py develop for simplemodule
    Running command python setup.py develop
    running develop
    /usr/local/lib/python3.9/site-packages/setuptools/command/easy_install.py:144: EasyInstallDeprecationWarning: easy_install command is deprecated. Use build and pip and other standards-based tools.
      warnings.warn(
    /usr/local/lib/python3.9/site-packages/setuptools/command/install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
      warnings.warn(
    Checking .pth file support in /Users/ux/Library/Python/3.9/lib/python3.9/site-packages
    /usr/local/opt/python@3.9/bin/python3.9 -E -c pass
    TEST FAILED: /Users/ux/Library/Python/3.9/lib/python3.9/site-packages does NOT support .pth files
    bad install directory or PYTHONPATH

    You are attempting to install a package to a directory that is not
    on PYTHONPATH and which Python does not read ".pth" files from.  The
    installation directory you specified (via --install-dir, --prefix, or
    the distutils default setting) was:

        /Users/ux/Library/Python/3.9/lib/python3.9/site-packages

    and your PYTHONPATH environment variable currently contains:

        ''

    Here are some of your options for correcting the problem:

    * You can choose a different installation directory, i.e., one that is
      on PYTHONPATH or supports .pth files

    * You can add the installation directory to the PYTHONPATH environment
      variable.  (It must then also be on PYTHONPATH whenever you run
      Python and want to use the package(s) you are installing.)

    * You can set up the installation directory to support ".pth" files by
      using one of the approaches described here:

      https://setuptools.pypa.io/en/latest/deprecated/easy_install.html#custom-installation-locations


    Please make the appropriate changes for your system and try again.
    running egg_info
    creating simplemodule.egg-info
    writing simplemodule.egg-info/PKG-INFO
    writing dependency_links to simplemodule.egg-info/dependency_links.txt
    writing entry points to simplemodule.egg-info/entry_points.txt
    writing top-level names to simplemodule.egg-info/top_level.txt
    writing manifest file 'simplemodule.egg-info/SOURCES.txt'
    reading manifest file 'simplemodule.egg-info/SOURCES.txt'
    writing manifest file 'simplemodule.egg-info/SOURCES.txt'
    running build_ext
    Creating /Users/ux/Library/Python/3.9/lib/python3.9/site-packages/simplemodule.egg-link (link to .)
    Installing simplemodule-cli script to /Users/ux/Library/Python/3.9/bin

    Installed /Users/ux/test-python/simplemodule
Successfully installed simplemodule
```

```
% simplemodule-cli
Traceback (most recent call last):
  File "/Users/ux/Library/Python/3.9/bin/simplemodule-cli", line 33, in <module>
    sys.exit(load_entry_point('simplemodule', 'console_scripts', 'simplemodule-cli')())
  File "/Users/ux/Library/Python/3.9/bin/simplemodule-cli", line 22, in importlib_load_entry_point
    for entry_point in distribution(dist_name).entry_points
  File "/usr/local/Cellar/python@3.9/3.9.12_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/importlib/metadata.py", line 542, in distribution
    return Distribution.from_name(distribution_name)
  File "/usr/local/Cellar/python@3.9/3.9.12_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/importlib/metadata.py", line 196, in from_name
    raise PackageNotFoundError(name)
importlib.metadata.PackageNotFoundError: simplemodule
```

### What did you expect to happen?

To have `simplemodule-cli` print "I am a simple Python module" on execution.

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
brew install python
pip install --user -e simplemodule
simplemodule-cli
```
```

**Comment by SMillerDev** [comment]
Is it reproducible with Homebrew on Linux?

**Comment by ubitux** [comment]
> Is it reproducible with Homebrew on Linux?

Mmh, installing homebrew on linux is going to be way too intrusive for me to try. I can do do and provide whatever information you need on the mac though.

**Comment by gromgit** [comment]
> Is it reproducible with Homebrew on Linux?

Not on my main Ubuntu 20.04 desktop:
```bash
$ brew config
HOMEBREW_VERSION: 3.4.11-72-g5d4353f
ORIGIN: https://github.com/Homebrew/brew
HEAD: 5d4353f617fa2aa684582aa868c2e5016d8987b5
Last commit: 2 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 3893c59ef84f94168c95f94c7012584527cec905
Core tap last commit: 22 hours ago
Core tap branch: master
HOMEBREW_PREFIX: /home/linuxbrew/.linuxbrew
HOMEBREW_BOOTSNAP: set
HOMEBREW_CASK_OPTS: []
HOMEBREW_CORE_GIT_REMOTE: https://github.com/Homebrew/homebrew-core
HOMEBREW_DISPLAY: :0.0
HOMEBREW_DISPLAY_INSTALL_TIMES: set
HOMEBREW_EDITOR: vim
HOMEBREW_MAKE_JOBS: 6
HOMEBREW_NO_AUTO_UPDATE: set
HOMEBREW_TEMP: /home/linuxbrew/.linuxbrew/tmp
Homebrew Ruby: 2.6.8 => /home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.8/bin/ruby
CPU: hexa-core 64-bit skylake
Clang: 13.0.1
Git: 2.36.1 => /home/linuxbrew/.linuxbrew/bin/git
Curl: 7.68.0 => /bin/curl
Kernel: Linux 5.4.0-110-generic x86_64 GNU/Linux
OS: Ubuntu 20.04.4 LTS (focal)
Host glibc: 2.31
/usr/bin/gcc: 9.4.0
/usr/bin/ruby: 2.7.0
glibc: N/A
gcc@5: N/A
xorg: N/A

$ brew info python
python@3.9: stable 3.9.12 (bottled)
Interpreted, interactive, object-oriented programming language
https://www.python.org/
/home/linuxbrew/.linuxbrew/Cellar/python@3.9/3.9.12_1 (2,663 files, 78.4MB) *
  Poured from bottle on 2022-05-14 at 23:04:15
[...]

$ which pip3
/home/linuxbrew/.linuxbrew/bin/pip3

$ pip3 --version
pip 22.0.4 from /home/linuxbrew/.linuxbrew/opt/python@3.9/lib/python3.9/site-packages/pip (python 3.9)

$ pip3 -v install --user -e simplemodule
Using pip 22.0.4 from /home/linuxbrew/.linuxbrew/opt/python@3.9/lib/python3.9/site-packages/pip (python 3.9)
Obtaining file:///home/aho/tmp/simplemodule
  Running command python setup.py egg_info
  running egg_info
  creating /tmp/pip-pip-egg-info-jnarwv0n/simplemodule.egg-info
  writing /tmp/pip-pip-egg-info-jnarwv0n/simplemodule.egg-info/PKG-INFO
  writing dependency_links to /tmp/pip-pip-egg-info-jnarwv0n/simplemodule.egg-info/dependency_links.txt
  writing entry points to /tmp/pip-pip-egg-info-jnarwv0n/simplemodule.egg-info/entry_points.txt
  writing top-level names to /tmp/pip-pip-egg-info-jnarwv0n/simplemodule.egg-info/top_level.txt
  writing manifest file '/tmp/pip-pip-egg-info-jnarwv0n/simplemodule.egg-info/SOURCES.txt'
  reading manifest file '/tmp/pip-pip-egg-info-jnarwv0n/simplemodule.egg-info/SOURCES.txt'
  writing manifest file '/tmp/pip-pip-egg-info-jnarwv0n/simplemodule.egg-info/SOURCES.txt'
  Preparing metadata (setup.py) ... done
Installing collected packages: simplemodule
  Running setup.py develop for simplemodule
    Running command python setup.py develop
    running develop
    /home/linuxbrew/.linuxbrew/opt/python@3.9/lib/python3.9/site-packages/setuptools/command/easy_install.py:144: EasyInstallDeprecationWarning: easy_install command is deprecated. Use build and pip and other standards-based tools.
      warnings.warn(
    /home/linuxbrew/.linuxbrew/opt/python@3.9/lib/python3.9/site-packages/setuptools/command/install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
      warnings.warn(
    running egg_info
    writing simplemodule.egg-info/PKG-INFO
    writing dependency_links to simplemodule.egg-info/dependency_links.txt
    writing entry points to simplemodule.egg-info/entry_points.txt
    writing top-level names to simplemodule.egg-info/top_level.txt
    reading manifest file 'simplemodule.egg-info/SOURCES.txt'
    writing manifest file 'simplemodule.egg-info/SOURCES.txt'
    running build_ext
    Creating /home/aho/.local/lib/python3.9/site-packages/simplemodule.egg-link (link to .)
    Adding simplemodule 0.1 to easy-install.pth file
    Installing simplemodule-cli script to /home/aho/.local/bin

    Installed /home/aho/tmp/simplemodule
Successfully installed simplemodule-0.1
WARNING: You are using pip version 22.0.4; however, version 22.1 is available.
You should consider upgrading via the '/home/linuxbrew/.linuxbrew/opt/python@3.9/bin/python3.9 -m pip install --upgrade pip' command.

$ simplemodule-cli
I am a simple Python module
```
but I can confirm exactly the same errors as @ubitux on my own Monterey setup, even though I'm running stock Homebrew pip3 v22.0.4 (it looks like @ubitux upgraded to pip3 v22.1).

**Comment by ubitux** [comment]
> but I can confirm exactly the same errors as @ubitux on my own Monterey setup, even though I'm running stock Homebrew pip3 v22.0.4 (it looks like @ubitux upgraded to pip3 v22.1).

Yes I upgraded pip and setuptools as documented on https://docs.brew.sh/Homebrew-and-Python when I first had the issue.

Also note that `pip install --user` "works" but it puts the cli tool in `/usr/local/Cellar/python@3.9/3.9.12_1/Frameworks/Python.framework/Versions/3.9/bin/` which is not in the `$PATH`. The egg link OTOH lands in `/usr/local/lib/python3.9/site-packages/`. This makes the `--user` version half working (but at least it runs).

**Comment by cho-m** [comment]
Not sure if related, but one thing I noticed is that the lib path in logs show:
```
    TEST FAILED: /Users/ux/Library/Python/3.9/lib/python3.9/site-packages does NOT support .pth files
```

while `site` uses a different path:
```console
❯ /usr/local/opt/python@3.9/bin/python3.9 -c 'import site; print(site.USER_BASE); print(site.USER_SITE)'
/Users/cho-m/Library/Python/3.9
/Users/cho-m/Library/Python/3.9/lib/python/site-packages
```

It is possible that Python auto-adds `site.USER_SITE` to search path and if library was installed there then it may work out of box. Would need further triaging to check this.

I don't know why `site.USER_SITE == .../lib/python/site-packages` while `pip3 install ...` is using `.../lib/python3.9/site-packages`.

**Comment by cho-m** [comment]
After some additional debugging, this may be an upstream bug specific to Python installations using macOS Framework build.

I think the problem is that CPython `site.py` uses a different path than what `distutils` uses, e.g.
```console
❯ /opt/homebrew/bin/python3.9
Python 3.9.13 (main, May 19 2022, 13:48:47)
[Clang 13.1.6 (clang-1316.0.21.2)] on darwin
Type "help", "copyright", "credits" or "license" for more information.

>>> from distutils.dist import Distribution
>>> c = Distribution().get_command_obj('install')
/opt/homebrew/lib/python3.9/site-packages/setuptools/command/install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
  warnings.warn(
>>> c.user = True
>>> c.finalize_options()
>>> print(c.install_lib)
/Users/cho-m/Library/Python/3.9/lib/python3.9/site-packages/

>>> import site
>>> print(site.USER_SITE)
/Users/cho-m/Library/Python/3.9/lib/python/site-packages

>>> import sys
>>> from pprint import pprint
>>> pprint(sys.path)
['',
 '/opt/homebrew/Cellar/python@3.9/3.9.13/Frameworks/Python.framework/Versions/3.9/lib/python39.zip',
 '/opt/homebrew/Cellar/python@3.9/3.9.13/Frameworks/Python.framework/Versions/3.9/lib/python3.9',
 '/opt/homebrew/Cellar/python@3.9/3.9.13/Frameworks/Python.framework/Versions/3.9/lib/python3.9/lib-dynload',
 '/Users/cho-m/Library/Python/3.9/lib/python/site-packages',
 '/opt/homebrew/lib/python3.9/site-packages']
``` 

The following code appears to be reason for different path in `site.py` https://github.com/python/cpython/blob/v3.9.13/Lib/site.py#L272-L275
```python
    if sys.platform == 'darwin' and sys._framework:
        return f'{userbase}/lib/python/site-packages'

    return f'{userbase}/lib/python{version[0]}.{version[1]}/site-packages'
```

---

Not sure what is "correct" behavior. If `distutils` is correct, then a potential fix would be to remove the `if` condition in above CPython code.

**Comment by ubitux** [comment]
Note that you can use `python -m site [--user-base] [--user-site]` to ease introspection.

**Comment by ubitux** [comment]
> I think the problem is that CPython `site.py` uses a different path than what `distutils` uses, e.g.

Is there an upstream issue we can track? I'm not sure I can open it myself because I don't think I understand the problem enough.
