### ISSUE TITLE
Groovy: groovy CLI broken for JAVA_HOME set for 11 LTS

### ISSUE THREAD

**Issue by tmoschou** [Homebrew/homebrew-core#103364]
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

```shell
❯ brew gist-logs groovy
Error: No logs.

❯ brew config
HOMEBREW_VERSION: 3.5.1
ORIGIN: https://github.com/Homebrew/brew
HEAD: 2258ba5797c1ea8149a49673b5c080011c366237
Last commit: 3 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: c6001df23bacf2ee9c42896733d8ceb921043649
Core tap last commit: 2 hours ago
Core tap branch: master
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CASK_OPTS: []
HOMEBREW_CORE_GIT_REMOTE: https://github.com/Homebrew/homebrew-core
HOMEBREW_MAKE_JOBS: 16
Homebrew Ruby: 2.6.8 => /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.8_1/bin/ruby
CPU: 16-core 64-bit kabylake
Clang: 13.1.6 build 1316
Git: 2.32.1 => /Library/Developer/CommandLineTools/usr/bin/git
Curl: 7.79.1 => /usr/bin/curl
macOS: 12.4-x86_64
CLT: 13.4.0.0.1.1651278267
Xcode: N/A
```
```


### Verification

- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.

### What were you trying to do (and why)?

Run `/usr/local/opt/groovy/bin/groovy` or `/usr/local/opt/groovy/bin/groovysh` 

### What happened (include all command output)?

```
❯ readlink -f $JAVA_HOME
/Library/Java/JavaVirtualMachines/temurin-11.jdk/Contents/Home

❯ readlink -f $(which groovy)
/usr/local/Cellar/groovy/4.0.3/bin/groovy

❯ groovy
Error occurred during initialization of VM
java.lang.InternalError: Could not create SecurityManager: allow
	at sun.misc.Launcher.<init>(Launcher.java:106)
	at sun.misc.Launcher.<clinit>(Launcher.java:54)
	at java.lang.ClassLoader.initSystemClassLoader(ClassLoader.java:1444)
	at java.lang.ClassLoader.getSystemClassLoader(ClassLoader.java:1429)
```

### What did you expect to happen?

Not to crash.

This is crashing, because the wrapper script recently added `-Djava.security.manager=allow` in 3b2acd57eb90 (https://github.com/Homebrew/homebrew-core/pull/98612) and assumes `JAVA_HOME` is unset or not set to JDK 11 LTS.

```
❯ cat /usr/local/Cellar/groovy/4.0.3/bin/groovy
#!/bin/bash
JAVA_HOME="${JAVA_HOME:-/usr/local/opt/openjdk/libexec/openjdk.jdk/Contents/Home}" JAVA_OPTS="$JAVA_OPTS -Djava.security.manager=allow" exec "/usr/local/Cellar/groovy/4.0.3/libexec/bin/groovy"  "$@"
```

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
1. Install Java 11 LTS. https://adoptium.net/temurin/releases?version=11

2. `export JAVA_HOME=$(/usr/libexec/java_home -v 11)`

3. `brew install groovy`

4. run `groovy`

Workaround is to call `/usr/local/opt/libexec/bin/groovy` directly and avoid the wrapper script
```

**Comment by cho-m** [comment]
Originally `-Djava.security.manager=allow` needed to be set to get JDK18 to work, but it looks like 4.0.3 has a fix https://issues.apache.org/jira/browse/GROOVY-10610, so we can drop it. Created #103382 for this.

**Comment by cho-m** [comment]
Closing as PR is merged.
