### ISSUE TITLE
Glooctl - Couldn't find manifest matching bottle checksum

### ISSUE THREAD

**Issue by brandonhon** [Homebrew/homebrew-core#106486]
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

```shell
brew config:

`HOMEBREW_VERSION: 3.5.6
ORIGIN: https://github.com/Homebrew/brew
HEAD: 0b030b74e2ac518bd0bc4158f96c449198f9957f
Last commit: 3 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: b8ed9d4c8a57ad53906c6d18213b6c36652b3e66
Core tap last commit: 2 hours ago
Core tap branch: master
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CASK_OPTS: []
HOMEBREW_DISPLAY: /private/tmp/com.apple.launchd.y0ZZ61DTDB/org.xquartz:0
HOMEBREW_EDITOR: /usr/bin/vim
HOMEBREW_MAKE_JOBS: 12
Homebrew Ruby: 2.6.8 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: dodeca-core 64-bit kabylake
Clang: 13.1.6 build 1316
Git: 2.32.1 => /Library/Developer/CommandLineTools/usr/bin/git
Curl: 7.79.1 => /usr/bin/curl
macOS: 12.4-x86_64
CLT: 13.4.0.0.1.1651278267
Xcode: 13.4.1`
```

### Verification

- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.

### What were you trying to do (and why)?

Brew upgrade/install glooctl v1.11.24 (latest)

### What happened (include all command output)?

Error:

`==> Downloading https://ghcr.io/v2/homebrew/core/glooctl/manifests/1.11.24
######################################################################## 100.0%
==> Downloading https://ghcr.io/v2/homebrew/core/glooctl/manifests/1.11.24
######################################################################## 100.0%
Error: Couldn't find manifest matching bottle checksum.
/usr/local/Homebrew/Library/Homebrew/software_spec.rb:399:in `github_packages_manifest_resource_tab'
/usr/local/Homebrew/Library/Homebrew/software_spec.rb:352:in `fetch_tab'
/usr/local/Homebrew/Library/Homebrew/formula.rb:2379:in `fetch_bottle_tab'
/usr/local/Homebrew/Library/Homebrew/formula_installer.rb:1177:in `fetch'
/usr/local/Homebrew/Library/Homebrew/install.rb:305:in `block in install_formulae'
/usr/local/Homebrew/Library/Homebrew/install.rb:278:in `map'
/usr/local/Homebrew/Library/Homebrew/install.rb:278:in `install_formulae'
/usr/local/Homebrew/Library/Homebrew/cmd/install.rb:222:in `install'
/usr/local/Homebrew/Library/Homebrew/brew.rb:93:in `<main>'`

### What did you expect to happen?

Expected bottle to updated without issue 

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
brew install glooctl or brew upgrade glooctl (if already installed)
```

**Comment by brandonhon** [comment]
Gracias!
