### ISSUE TITLE
ddclient: 'expected replacement of "/usr/sbin/ddclient" with "/opt/homebrew/Cellar/ddclient/HEAD-.../ddclient"' & gits-log failure

### ISSUE THREAD

**Issue by ylluminate** [Homebrew/homebrew-core#106810]
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output
Attempted to grab `brew gist-logs ddclient`, but got a failure:
```
$ brew gist-logs -d ddclient
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::FormulaLoader): loading /opt/homebrew/Library/Taps/homebrew/homebrew-core/Formula/ddclient.rb
/opt/homebrew/Library/Homebrew/shims/shared/git --version
/opt/homebrew/Library/Homebrew/shims/shared/curl --version
/opt/homebrew/Library/Homebrew/shims/shared/curl --disable --cookie /dev/null --globoff --show-error --user-agent Homebrew/3.5.6\ \(Macintosh\;\ arm64\ Mac\ OS\ X\ 12.5\)\ curl/7.79.1 --header Accept-Language:\ en --retry 3 --location https://api.github.com/gists --header Accept:\ application/vnd.github.v3\+json --write-out '
'\%\{http_code\} --header Accept:\ application/vnd.github.antiope-preview\+json --header Authorization:\ token\ ****** --data @/private/tmp/github_api_post20220728-20514-so4yml --dump-header /private/tmp/github_api_headers20220728-20514-1btwdjp
Error: Not Found
/opt/homebrew/Library/Homebrew/utils/github/api.rb:301:in `raise_error'
/opt/homebrew/Library/Homebrew/utils/github/api.rb:234:in `open_rest'
/opt/homebrew/Library/Homebrew/utils/github.rb:40:in `create_gist'
/opt/homebrew/Library/Homebrew/cmd/gist-logs.rb:66:in `gistify_logs'
/opt/homebrew/Library/Homebrew/cmd/gist-logs.rb:120:in `gist_logs'
/opt/homebrew/Library/Homebrew/brew.rb:93:in `<main>'
```

`$ brew config`:
```
HOMEBREW_VERSION: 3.5.6
ORIGIN: https://github.com/Homebrew/brew
HEAD: 0b030b74e2ac518bd0bc4158f96c449198f9957f
Last commit: 8 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: bbe2deae0ab7bf20cafe1019094f3ae56e671f1f
Core tap last commit: 76 minutes ago
Core tap branch: master
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_EDITOR: nano
HOMEBREW_GITHUB_API_TOKEN: set
HOMEBREW_MAKE_JOBS: 10
Homebrew Ruby: 2.6.8 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: 10-core 64-bit dunno
Clang: 13.1.6 build 1316
Git: 2.32.1 => /Applications/Xcode_13.4.1.app/Contents/Developer/usr/bin/git
Curl: 7.79.1 => /usr/bin/curl
macOS: 12.5-arm64
CLT: 13.4.0.0.1.1651278267
Xcode: 13.4.1 => /Applications/Xcode_13.4.1.app/Contents/Developer
Rosetta 2: false
```

`$ brew doctor`:
```
Your system is ready to brew.
```

### Verification

- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.

### What were you trying to do (and why)?

Installing `--HEAD ddclient` since v3.9.1 will not work and newer pre-release candidates resolve CloudFlare trouble. (See: https://github.com/ddclient/ddclient/releases/tag/v3.10.0_1 supports CloudFlare API tokens.)

### What happened (include all command output)?

`$ brew install -d --HEAD ddclient`:
```
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::FormulaLoader): loading /opt/homebrew/Library/Taps/homebrew/homebrew-core/Formula/ddclient.rb
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::FormulaLoader): loading /opt/homebrew/Library/Taps/homebrew/homebrew-core/Formula/autoconf.rb
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::FormulaLoader): loading /opt/homebrew/Library/Taps/homebrew/homebrew-core/Formula/m4.rb
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::FormulaLoader): loading /opt/homebrew/Library/Taps/homebrew/homebrew-core/Formula/automake.rb
==> Cloning https://github.com/ddclient/ddclient.git
git --git-dir /Users/admin/Library/Caches/Homebrew/ddclient--git/.git status -s
Updating /Users/admin/Library/Caches/Homebrew/ddclient--git
git config remote.origin.url https://github.com/ddclient/ddclient.git
git config remote.origin.fetch \+refs/heads/develop:refs/remotes/origin/develop
git config remote.origin.tagOpt --no-tags
git config advice.detachedHead false
git fetch origin
==> Checking out branch develop
git checkout -f develop --
Already on 'develop'
Your branch is up to date with 'origin/develop'.
git reset --hard origin/develop --
HEAD is now at 5382a98 Fix typo
git --git-dir /Users/admin/Library/Caches/Homebrew/ddclient--git/.git rev-parse --short=7 HEAD
/opt/homebrew/Library/Homebrew/shims/shared/git --version
/opt/homebrew/Library/Homebrew/build.rb (Formulary::FormulaLoader): loading /opt/homebrew/Library/Taps/homebrew/homebrew-core/Formula/autoconf.rb
/opt/homebrew/Library/Homebrew/build.rb (Formulary::FormulaLoader): loading /opt/homebrew/Library/Taps/homebrew/homebrew-core/Formula/m4.rb
/opt/homebrew/Library/Homebrew/build.rb (Formulary::FormulaLoader): loading /opt/homebrew/Library/Taps/homebrew/homebrew-core/Formula/automake.rb
git --git-dir /Users/admin/Library/Caches/Homebrew/ddclient--git/.git rev-parse --short=7 HEAD
hdiutil imageinfo -format /Users/admin/Library/Caches/Homebrew/ddclient--git
cp -pR /Users/admin/Library/Caches/Homebrew/ddclient--git/sample-etc_ppp_ip-up.local /private/tmp/d20220728-23500-148pg93/sample-etc_ppp_ip-up.local
cp -pR /Users/admin/Library/Caches/Homebrew/ddclient--git/sample-get-ip-from-fritzbox /private/tmp/d20220728-23500-148pg93/sample-get-ip-from-fritzbox
cp -pR /Users/admin/Library/Caches/Homebrew/ddclient--git/.envrc /private/tmp/d20220728-23500-148pg93/.envrc
cp -pR /Users/admin/Library/Caches/Homebrew/ddclient--git/build-aux/. /private/tmp/d20220728-23500-148pg93/build-aux
cp -pR /Users/admin/Library/Caches/Homebrew/ddclient--git/configure.ac /private/tmp/d20220728-23500-148pg93/configure.ac
cp -pR /Users/admin/Library/Caches/Homebrew/ddclient--git/ChangeLog.md /private/tmp/d20220728-23500-148pg93/ChangeLog.md
cp -pR /Users/admin/Library/Caches/Homebrew/ddclient--git/sample-etc_systemd.service /private/tmp/d20220728-23500-148pg93/sample-etc_systemd.service
cp -pR /Users/admin/Library/Caches/Homebrew/ddclient--git/ddclient.in /private/tmp/d20220728-23500-148pg93/ddclient.in
cp -pR /Users/admin/Library/Caches/Homebrew/ddclient--git/sample-etc_rc.d_init.d_ddclient.ubuntu /private/tmp/d20220728-23500-148pg93/sample-etc_rc.d_init.d_ddclient.ubuntu
cp -pR /Users/admin/Library/Caches/Homebrew/ddclient--git/README.cisco /private/tmp/d20220728-23500-148pg93/README.cisco
cp -pR /Users/admin/Library/Caches/Homebrew/ddclient--git/shell.nix /private/tmp/d20220728-23500-148pg93/shell.nix
cp -pR /Users/admin/Library/Caches/Homebrew/ddclient--git/sample-etc_rc.d_init.d_ddclient /private/tmp/d20220728-23500-148pg93/sample-etc_rc.d_init.d_ddclient
cp -pR /Users/admin/Library/Caches/Homebrew/ddclient--git/sample-etc_rc.d_init.d_ddclient.lsb /private/tmp/d20220728-23500-148pg93/sample-etc_rc.d_init.d_ddclient.lsb
cp -pR /Users/admin/Library/Caches/Homebrew/ddclient--git/docs/. /private/tmp/d20220728-23500-148pg93/docs
cp -pR /Users/admin/Library/Caches/Homebrew/ddclient--git/sample-etc_rc.d_init.d_ddclient.redhat /private/tmp/d20220728-23500-148pg93/sample-etc_rc.d_init.d_ddclient.redhat
cp -pR /Users/admin/Library/Caches/Homebrew/ddclient--git/t/. /private/tmp/d20220728-23500-148pg93/t
cp -pR /Users/admin/Library/Caches/Homebrew/ddclient--git/Makefile.am /private/tmp/d20220728-23500-148pg93/Makefile.am
cp -pR /Users/admin/Library/Caches/Homebrew/ddclient--git/README.md /private/tmp/d20220728-23500-148pg93/README.md
cp -pR /Users/admin/Library/Caches/Homebrew/ddclient--git/COPYING /private/tmp/d20220728-23500-148pg93/COPYING
cp -pR /Users/admin/Library/Caches/Homebrew/ddclient--git/README.ssl /private/tmp/d20220728-23500-148pg93/README.ssl
cp -pR /Users/admin/Library/Caches/Homebrew/ddclient--git/.gitignore /private/tmp/d20220728-23500-148pg93/.gitignore
cp -pR /Users/admin/Library/Caches/Homebrew/ddclient--git/sample-ddclient-wrapper.sh /private/tmp/d20220728-23500-148pg93/sample-ddclient-wrapper.sh
cp -pR /Users/admin/Library/Caches/Homebrew/ddclient--git/CONTRIBUTING.md /private/tmp/d20220728-23500-148pg93/CONTRIBUTING.md
cp -pR /Users/admin/Library/Caches/Homebrew/ddclient--git/sample-etc_cron.d_ddclient /private/tmp/d20220728-23500-148pg93/sample-etc_cron.d_ddclient
cp -pR /Users/admin/Library/Caches/Homebrew/ddclient--git/sample-etc_rc.d_init.d_ddclient.alpine /private/tmp/d20220728-23500-148pg93/sample-etc_rc.d_init.d_ddclient.alpine
cp -pR /Users/admin/Library/Caches/Homebrew/ddclient--git/.github/. /private/tmp/d20220728-23500-148pg93/.github
cp -pR /Users/admin/Library/Caches/Homebrew/ddclient--git/sample-etc_dhcpc_dhcpcd-eth0.exe /private/tmp/d20220728-23500-148pg93/sample-etc_dhcpc_dhcpcd-eth0.exe
cp -pR /Users/admin/Library/Caches/Homebrew/ddclient--git/m4/. /private/tmp/d20220728-23500-148pg93/m4
cp -pR /Users/admin/Library/Caches/Homebrew/ddclient--git/COPYRIGHT /private/tmp/d20220728-23500-148pg93/COPYRIGHT
cp -pR /Users/admin/Library/Caches/Homebrew/ddclient--git/sample-etc_dhclient-exit-hooks /private/tmp/d20220728-23500-148pg93/sample-etc_dhclient-exit-hooks
cp -pR /Users/admin/Library/Caches/Homebrew/ddclient--git/ddclient.conf.in /private/tmp/d20220728-23500-148pg93/ddclient.conf.in
cp -pR /Users/admin/Library/Caches/Homebrew/ddclient--git/.git/. /private/tmp/d20220728-23500-148pg93/.git
cp -pR /Users/admin/Library/Caches/Homebrew/ddclient--git/autogen /private/tmp/d20220728-23500-148pg93/autogen
cp -pR /Users/admin/Library/Caches/Homebrew/ddclient--git/sample-etc_rc.d_ddclient.freebsd /private/tmp/d20220728-23500-148pg93/sample-etc_rc.d_ddclient.freebsd
cp -pR /private/tmp/d20220728-23500-148pg93/sample-etc_ppp_ip-up.local /private/tmp/ddclient-20220728-23500-ahpdp0/sample-etc_ppp_ip-up.local
cp -pR /private/tmp/d20220728-23500-148pg93/sample-get-ip-from-fritzbox /private/tmp/ddclient-20220728-23500-ahpdp0/sample-get-ip-from-fritzbox
cp -pR /private/tmp/d20220728-23500-148pg93/.envrc /private/tmp/ddclient-20220728-23500-ahpdp0/.envrc
cp -pR /private/tmp/d20220728-23500-148pg93/build-aux/. /private/tmp/ddclient-20220728-23500-ahpdp0/build-aux
cp -pR /private/tmp/d20220728-23500-148pg93/configure.ac /private/tmp/ddclient-20220728-23500-ahpdp0/configure.ac
cp -pR /private/tmp/d20220728-23500-148pg93/ChangeLog.md /private/tmp/ddclient-20220728-23500-ahpdp0/ChangeLog.md
cp -pR /private/tmp/d20220728-23500-148pg93/sample-etc_systemd.service /private/tmp/ddclient-20220728-23500-ahpdp0/sample-etc_systemd.service
cp -pR /private/tmp/d20220728-23500-148pg93/ddclient.in /private/tmp/ddclient-20220728-23500-ahpdp0/ddclient.in
cp -pR /private/tmp/d20220728-23500-148pg93/sample-etc_rc.d_init.d_ddclient.ubuntu /private/tmp/ddclient-20220728-23500-ahpdp0/sample-etc_rc.d_init.d_ddclient.ubuntu
cp -pR /private/tmp/d20220728-23500-148pg93/README.cisco /private/tmp/ddclient-20220728-23500-ahpdp0/README.cisco
cp -pR /private/tmp/d20220728-23500-148pg93/shell.nix /private/tmp/ddclient-20220728-23500-ahpdp0/shell.nix
cp -pR /private/tmp/d20220728-23500-148pg93/sample-etc_rc.d_init.d_ddclient /private/tmp/ddclient-20220728-23500-ahpdp0/sample-etc_rc.d_init.d_ddclient
cp -pR /private/tmp/d20220728-23500-148pg93/sample-etc_rc.d_init.d_ddclient.lsb /private/tmp/ddclient-20220728-23500-ahpdp0/sample-etc_rc.d_init.d_ddclient.lsb
cp -pR /private/tmp/d20220728-23500-148pg93/docs/. /private/tmp/ddclient-20220728-23500-ahpdp0/docs
cp -pR /private/tmp/d20220728-23500-148pg93/sample-etc_rc.d_init.d_ddclient.redhat /private/tmp/ddclient-20220728-23500-ahpdp0/sample-etc_rc.d_init.d_ddclient.redhat
cp -pR /private/tmp/d20220728-23500-148pg93/t/. /private/tmp/ddclient-20220728-23500-ahpdp0/t
cp -pR /private/tmp/d20220728-23500-148pg93/Makefile.am /private/tmp/ddclient-20220728-23500-ahpdp0/Makefile.am
cp -pR /private/tmp/d20220728-23500-148pg93/README.md /private/tmp/ddclient-20220728-23500-ahpdp0/README.md
cp -pR /private/tmp/d20220728-23500-148pg93/COPYING /private/tmp/ddclient-20220728-23500-ahpdp0/COPYING
cp -pR /private/tmp/d20220728-23500-148pg93/README.ssl /private/tmp/ddclient-20220728-23500-ahpdp0/README.ssl
cp -pR /private/tmp/d20220728-23500-148pg93/.gitignore /private/tmp/ddclient-20220728-23500-ahpdp0/.gitignore
cp -pR /private/tmp/d20220728-23500-148pg93/sample-ddclient-wrapper.sh /private/tmp/ddclient-20220728-23500-ahpdp0/sample-ddclient-wrapper.sh
cp -pR /private/tmp/d20220728-23500-148pg93/CONTRIBUTING.md /private/tmp/ddclient-20220728-23500-ahpdp0/CONTRIBUTING.md
cp -pR /private/tmp/d20220728-23500-148pg93/sample-etc_cron.d_ddclient /private/tmp/ddclient-20220728-23500-ahpdp0/sample-etc_cron.d_ddclient
cp -pR /private/tmp/d20220728-23500-148pg93/sample-etc_rc.d_init.d_ddclient.alpine /private/tmp/ddclient-20220728-23500-ahpdp0/sample-etc_rc.d_init.d_ddclient.alpine
cp -pR /private/tmp/d20220728-23500-148pg93/.github/. /private/tmp/ddclient-20220728-23500-ahpdp0/.github
cp -pR /private/tmp/d20220728-23500-148pg93/sample-etc_dhcpc_dhcpcd-eth0.exe /private/tmp/ddclient-20220728-23500-ahpdp0/sample-etc_dhcpc_dhcpcd-eth0.exe
cp -pR /private/tmp/d20220728-23500-148pg93/m4/. /private/tmp/ddclient-20220728-23500-ahpdp0/m4
cp -pR /private/tmp/d20220728-23500-148pg93/COPYRIGHT /private/tmp/ddclient-20220728-23500-ahpdp0/COPYRIGHT
cp -pR /private/tmp/d20220728-23500-148pg93/sample-etc_dhclient-exit-hooks /private/tmp/ddclient-20220728-23500-ahpdp0/sample-etc_dhclient-exit-hooks
cp -pR /private/tmp/d20220728-23500-148pg93/ddclient.conf.in /private/tmp/ddclient-20220728-23500-ahpdp0/ddclient.conf.in
cp -pR /private/tmp/d20220728-23500-148pg93/.git/. /private/tmp/ddclient-20220728-23500-ahpdp0/.git
cp -pR /private/tmp/d20220728-23500-148pg93/autogen /private/tmp/ddclient-20220728-23500-ahpdp0/autogen
cp -pR /private/tmp/d20220728-23500-148pg93/sample-etc_rc.d_ddclient.freebsd /private/tmp/ddclient-20220728-23500-ahpdp0/sample-etc_rc.d_ddclient.freebsd
git --git-dir /Users/admin/Library/Caches/Homebrew/ddclient--git/.git show -s --format=\%cD
==> ./autogen
==> ./configure --prefix=/opt/homebrew/Cellar/ddclient/HEAD-5382a98 --libdir=/opt/homebrew/Cellar/ddclient/HEAD-5382a98/lib
==> make install CURL=curl
/opt/homebrew/Library/Homebrew/ignorable.rb:29:in `block in raise'
Utils::Inreplace::Error: inreplace failed
sample-etc_cron.d_ddclient:
  expected replacement of "/usr/sbin/ddclient" with "/opt/homebrew/Cellar/ddclient/HEAD-5382a98/sbin/ddclient"
1. raise
2. ignore
3. backtrace
4. irb
5. shell
Choose an action: 1
==> Temporary files retained at:
/private/tmp/ddclient-20220728-23500-ahpdp0
git --git-dir /Users/admin/Library/Caches/Homebrew/ddclient--git/.git rev-parse --short=7 HEAD
Error: An exception occurred within a child process:
  Utils::Inreplace::Error: inreplace failed
sample-etc_cron.d_ddclient:
  expected replacement of "/usr/sbin/ddclient" with "/opt/homebrew/Cellar/ddclient/HEAD-5382a98/sbin/ddclient"

/opt/homebrew/Library/Homebrew/ignorable.rb:29:in `block in raise'
/opt/homebrew/Library/Homebrew/ignorable.rb:28:in `callcc'
/opt/homebrew/Library/Homebrew/ignorable.rb:28:in `raise'
/opt/homebrew/Library/Homebrew/utils/inreplace.rb:73:in `inreplace'
/opt/homebrew/Library/Taps/homebrew/homebrew-core/Formula/ddclient.rb:81:in `install'
/opt/homebrew/Library/Homebrew/debrew.rb:17:in `block in install'
/opt/homebrew/Library/Homebrew/debrew.rb:90:in `debrew'
/opt/homebrew/Library/Homebrew/debrew.rb:17:in `install'
/opt/homebrew/Library/Homebrew/build.rb:172:in `block (3 levels) in install'
/opt/homebrew/Library/Homebrew/utils.rb:601:in `with_env'
/opt/homebrew/Library/Homebrew/build.rb:134:in `block (2 levels) in install'
/opt/homebrew/Library/Homebrew/formula.rb:1286:in `block in brew'
/opt/homebrew/Library/Homebrew/formula.rb:2462:in `block (2 levels) in stage'
/opt/homebrew/Library/Homebrew/utils.rb:601:in `with_env'
/opt/homebrew/Library/Homebrew/formula.rb:2461:in `block in stage'
/opt/homebrew/Library/Homebrew/resource.rb:130:in `block (2 levels) in unpack'
/opt/homebrew/Library/Homebrew/download_strategy.rb:110:in `chdir'
/opt/homebrew/Library/Homebrew/download_strategy.rb:102:in `stage'
/opt/homebrew/Library/Homebrew/resource.rb:126:in `block in unpack'
/opt/homebrew/Library/Homebrew/mktemp.rb:63:in `block in run'
/opt/homebrew/Library/Homebrew/mktemp.rb:63:in `chdir'
/opt/homebrew/Library/Homebrew/mktemp.rb:63:in `run'
/opt/homebrew/Library/Homebrew/resource.rb:239:in `mktemp'
/opt/homebrew/Library/Homebrew/resource.rb:125:in `unpack'
/opt/homebrew/Library/Homebrew/resource.rb:99:in `stage'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/forwardable.rb:230:in `stage'
/opt/homebrew/Library/Homebrew/formula.rb:2441:in `stage'
/opt/homebrew/Library/Homebrew/formula.rb:1279:in `brew'
/opt/homebrew/Library/Homebrew/build.rb:129:in `block in install'
/opt/homebrew/Library/Homebrew/utils.rb:601:in `with_env'
/opt/homebrew/Library/Homebrew/build.rb:124:in `install'
/opt/homebrew/Library/Homebrew/build.rb:224:in `<main>'
```

### What did you expect to happen?

Successful installation, not:
```
Error: An exception occurred within a child process:
  Utils::Inreplace::Error: inreplace failed
sample-etc_cron.d_ddclient:
  expected replacement of "/usr/sbin/ddclient" with "/opt/homebrew/Cellar/ddclient/HEAD-5382a98/sbin/ddclient"
```

### Step-by-step reproduction instructions (by running `brew` commands)

See above inline in "What happened", eg, sans debug: `brew install --HEAD ddclient`

**Comment by carlocab** [comment]
Will be fixed in #106813.

Note that `--HEAD` installs are, by their definition, unstable, and could break at any point. This means that we don't provide support for them. (We also don't provide support for building from source because there is a myriad of reasons why they fail.)

If you have issues with `--HEAD` installs in the future, please make a pull request to fix it instead of filing an issue. Thanks!

**Comment by ylluminate** [comment]
Thanks, I would highly suggest removing `--HEAD` support for this then. Appreciate your input.

**Comment by carlocab** [comment]
See #106354 for discussion on removing `--HEAD`.

**Comment by ylluminate** [comment]
Thanks, I'm sorry: I was referring to the latter part of your remark wrt support and the desire to not support such options as `--HEAD`.  To me it seems that, if this is the policy, then the removal of concept of `--HEAD` here and otherwise should be considered seriously. If it's still left intact here, and elsewhere, then perhaps it is best to add some additional clauses within the formulae such as:
```
$ brew info ddclient
...
==> Options
* IMPORTANT, NB: Please do not report any problems you have with the following `--HEAD` build. We only accept pull requests to fix them and do not offer any assistance in resolution of any issues that may arise.
--HEAD (**NOTE ABOVE BEFORE TRYING**)
```

**Comment by carlocab** [comment]
We do have code that's meant to show you a message like that, but it seems to not be working here.

**Comment by DominusExult** [comment]
As it also failed for the SDL2 --head issue, the message might be generally broken.
As an OpenSource enthusiast who wants to do the *right* thing and takes time to report issues, it's very frustrating to run against a blunt "we do not care about this issue" and having it closed.
And with a slight OCD it's extremely disturbing as the mind screams "but it's still broken!!!"
I know my time is not more precious than yours but having that message show would have helped a lot!
(As for the SDL2 issue, I know it will pop up and quickly fixed when the next version gets released which is probably not that far away anyway)

**Comment by SMillerDev** [comment]
Does it show up when you run `brew install --head abduco`?

**Comment by ylluminate** [comment]
Yes:
```
...
install: mkdir /man1: Operation not permitted
make: *** [installdirs] Error 71
make: *** Waiting for unfinished jobs....

Do not report this issue to Homebrew/brew or Homebrew/core!

Please create pull requests instead of asking for help on Homebrew's GitHub,
Twitter or any other official channels.
```
