### ISSUE TITLE
[kubie] Error: Couldn't find manifest matching bottle checksum.

### ISSUE THREAD

**Issue by yermulnik** [Homebrew/homebrew-core#106855]
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

```shell
HOMEBREW_VERSION: 3.5.6-66-g43a3470
ORIGIN: https://github.com/Homebrew/brew
HEAD: 43a34706ede7ccc0dda81e6b8b0285600e5a4fbf
Last commit: 3 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 2d305da225a38872a43963e75e4c862b491ee77a
Core tap last commit: 3 minutes ago
Core tap branch: master
HOMEBREW_PREFIX: /home/linuxbrew/.linuxbrew
HOMEBREW_AUTO_UPDATE_SECS: 7200
HOMEBREW_BAT: set
HOMEBREW_BAT_CONFIG_PATH: /home/giermulnik/.config/bat/config
HOMEBREW_CASK_OPTS: []
HOMEBREW_DISPLAY: :0.0
HOMEBREW_EDITOR: /bin/vim
HOMEBREW_GITHUB_API_TOKEN: set
HOMEBREW_INSTALL_BADGE: ✔
HOMEBREW_MAKE_JOBS: 3
Homebrew Ruby: 2.6.8 => /home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.8_1/bin/ruby
CPU: octa-core 64-bit unknown_0x6_0xa5
Clang: 14.0.6
Git: 2.37.1 => /bin/git
Curl: 7.68.0 => /bin/curl
Kernel: Linux 5.18.14-051814-generic x86_64 GNU/Linux
OS: Ubuntu 20.04.4 LTS (focal)
Host glibc: 2.31
/usr/bin/gcc: 9.4.0
/usr/bin/ruby: 2.7.0
glibc: N/A
gcc@5: N/A
xorg: N/A
```

### Verification

- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.

### What were you trying to do (and why)?

`brew upgrade kubie`

### What happened (include all command output)?

```
> brew upgrade kubie
==> Upgrading 1 outdated package:
kubie 0.17.1 -> 0.17.2
==> Downloading https://ghcr.io/v2/homebrew/core/kubie/manifests/0.17.2
############################################################################################################# 100.0%
==> Downloading https://ghcr.io/v2/homebrew/core/kubie/manifests/0.17.2
############################################################################################################# 100.0%
Error: Couldn't find manifest matching bottle checksum.
Please report this issue:
  https://docs.brew.sh/Troubleshooting
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/software_spec.rb:412:in `github_packages_manifest_resource_tab'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/software_spec.rb:365:in `fetch_tab'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/formula.rb:2418:in `fetch_bottle_tab'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/formula_installer.rb:1177:in `fetch'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/upgrade.rb:71:in `block in upgrade_formulae'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/upgrade.rb:53:in `map'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/upgrade.rb:53:in `upgrade_formulae'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/cmd/upgrade.rb:179:in `upgrade_outdated_formulae'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/cmd/upgrade.rb:110:in `upgrade'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/brew.rb:93:in `<main>'
```

### What did you expect to happen?

`kubie` to be upgraded

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
`brew update && brew upgrade kubie`
```

**Comment by carlocab** [comment]
Thanks for the report. Will be fixed by #106856.

**Comment by yermulnik** [comment]
Thank you!

**Comment by carlocab** [comment]
Fixed now.

**Comment by yermulnik** [comment]
Can confirm `brew upgrade kubie` finished with success. Thanks a lot @carlocab 🥳
