### ISSUE TITLE
Hadoop is broken

### ISSUE THREAD

**Issue by Galaxy0419** [Homebrew/homebrew-core#107166]
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

```shell
[william@mbp-2020 logs]% brew config
HOMEBREW_VERSION: 3.5.7-2-g4baff3e
ORIGIN: https://mirrors.ustc.edu.cn/brew.git
HEAD: 4baff3eec111af70599c3fb517576d87ca74e9a2
Last commit: 30 hours ago
Core tap ORIGIN: https://mirrors.ustc.edu.cn/homebrew-core.git
Core tap HEAD: 4c1f447e39fe002aeb712f28925e22d51bea3605
Core tap last commit: 2 hours ago
Core tap branch: master
HOMEBREW_PREFIX: /usr/local
HOMEBREW_BOTTLE_DOMAIN: https://mirrors.ustc.edu.cn/homebrew-bottles
HOMEBREW_CASK_OPTS: []
HOMEBREW_CORE_GIT_REMOTE: https://mirrors.ustc.edu.cn/homebrew-core.git
HOMEBREW_MAKE_JOBS: 8
Homebrew Ruby: 2.6.8 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: octa-core 64-bit icelake
Clang: 13.1.6 build 1316
Git: 2.32.1 => /Applications/Xcode.app/Contents/Developer/usr/bin/git
Curl: 7.79.1 => /usr/bin/curl
macOS: 12.5-x86_64
CLT: N/A
Xcode: 13.4.1

[william@mbp-2020 homebrew-core](master)% brew doctor                                                                               
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: Suspicious https://github.com/Homebrew/brew git origin remote found.
The current git origin is:
  https://mirrors.ustc.edu.cn/brew.git

With a non-standard origin, Homebrew won't update properly.
You can solve this by setting the origin remote:
  git -C "/usr/local/Homebrew" remote set-url origin https://github.com/Homebrew/brew
```

### Verification

- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.

### What were you trying to do (and why)?

Start Hadoop HDFS cluster in "Pseudo-Distributed" mode using command ```start-all.sh```

### What happened (include all command output)?

Failed to start node manager and resource manager.
P.S. Logs are located under the ```/usr/local/Cellar/hadoop/3.3.3/libexec/logs```

**hadoop-xxx-nodemanager-xxx.log:**
```
2022-08-03 02:46:38,231 ERROR org.apache.hadoop.yarn.server.nodemanager.NodeManager: Error starting NodeManager
java.lang.ExceptionInInitializerError
	at com.google.inject.internal.cglib.reflect.$FastClassEmitter.<init>(FastClassEmitter.java:67)
	at com.google.inject.internal.cglib.reflect.$FastClass$Generator.generateClass(FastClass.java:72)
	at com.google.inject.internal.cglib.core.$DefaultGeneratorStrategy.generate(DefaultGeneratorStrategy.java:25)
	at com.google.inject.internal.cglib.core.$AbstractClassGenerator.create(AbstractClassGenerator.java:216)
	at com.google.inject.internal.cglib.reflect.$FastClass$Generator.create(FastClass.java:64)
	at com.google.inject.internal.BytecodeGen.newFastClass(BytecodeGen.java:204)
	at com.google.inject.internal.ProviderMethod$FastClassProviderMethod.<init>(ProviderMethod.java:256)
	at com.google.inject.internal.ProviderMethod.create(ProviderMethod.java:71)
	at com.google.inject.internal.ProviderMethodsModule.createProviderMethod(ProviderMethodsModule.java:275)
	at com.google.inject.internal.ProviderMethodsModule.getProviderMethods(ProviderMethodsModule.java:144)
	at com.google.inject.internal.ProviderMethodsModule.configure(ProviderMethodsModule.java:123)
	at com.google.inject.spi.Elements$RecordingBinder.install(Elements.java:340)
	at com.google.inject.spi.Elements$RecordingBinder.install(Elements.java:349)
	at com.google.inject.AbstractModule.install(AbstractModule.java:122)
	at com.google.inject.servlet.ServletModule.configure(ServletModule.java:52)
	at com.google.inject.AbstractModule.configure(AbstractModule.java:62)
	at com.google.inject.spi.Elements$RecordingBinder.install(Elements.java:340)
	at com.google.inject.spi.Elements.getElements(Elements.java:110)
	at com.google.inject.internal.InjectorShell$Builder.build(InjectorShell.java:138)
	at com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:104)
	at com.google.inject.Guice.createInjector(Guice.java:96)
	at com.google.inject.Guice.createInjector(Guice.java:73)
	at com.google.inject.Guice.createInjector(Guice.java:62)
	at org.apache.hadoop.yarn.webapp.WebApps$Builder.build(WebApps.java:417)
	at org.apache.hadoop.yarn.webapp.WebApps$Builder.start(WebApps.java:465)
	at org.apache.hadoop.yarn.webapp.WebApps$Builder.start(WebApps.java:461)
	at org.apache.hadoop.yarn.server.nodemanager.webapp.WebServer.serviceStart(WebServer.java:125)
	at org.apache.hadoop.service.AbstractService.start(AbstractService.java:194)
	at org.apache.hadoop.service.CompositeService.serviceStart(CompositeService.java:122)
	at org.apache.hadoop.service.AbstractService.start(AbstractService.java:194)
	at org.apache.hadoop.yarn.server.nodemanager.NodeManager.initAndStartNodeManager(NodeManager.java:963)
	at org.apache.hadoop.yarn.server.nodemanager.NodeManager.main(NodeManager.java:1042)
Caused by: java.lang.reflect.InaccessibleObjectException: Unable to make protected final java.lang.Class java.lang.ClassLoader.defineClass(java.lang.String,byte[],int,int,java.security.ProtectionDomain) throws java.lang.ClassFormatError accessible: module java.base does not "opens java.lang" to unnamed module @12efa456
	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:354)
	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:297)
	at java.base/java.lang.reflect.Method.checkCanSetAccessible(Method.java:200)
	at java.base/java.lang.reflect.Method.setAccessible(Method.java:194)
	at com.google.inject.internal.cglib.core.$ReflectUtils$2.run(ReflectUtils.java:56)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:318)
	at com.google.inject.internal.cglib.core.$ReflectUtils.<clinit>(ReflectUtils.java:46)
	... 32 more
```

**hadoop-xxx-resourcemanager-xxx.log:**
```
2022-08-03 02:46:35,642 ERROR org.apache.hadoop.yarn.server.resourcemanager.ResourceManager: Error starting ResourceManager
java.lang.ExceptionInInitializerError
	at com.google.inject.internal.cglib.reflect.$FastClassEmitter.<init>(FastClassEmitter.java:67)
	at com.google.inject.internal.cglib.reflect.$FastClass$Generator.generateClass(FastClass.java:72)
	at com.google.inject.internal.cglib.core.$DefaultGeneratorStrategy.generate(DefaultGeneratorStrategy.java:25)
	at com.google.inject.internal.cglib.core.$AbstractClassGenerator.create(AbstractClassGenerator.java:216)
	at com.google.inject.internal.cglib.reflect.$FastClass$Generator.create(FastClass.java:64)
	at com.google.inject.internal.BytecodeGen.newFastClass(BytecodeGen.java:204)
	at com.google.inject.internal.ProviderMethod$FastClassProviderMethod.<init>(ProviderMethod.java:256)
	at com.google.inject.internal.ProviderMethod.create(ProviderMethod.java:71)
	at com.google.inject.internal.ProviderMethodsModule.createProviderMethod(ProviderMethodsModule.java:275)
	at com.google.inject.internal.ProviderMethodsModule.getProviderMethods(ProviderMethodsModule.java:144)
	at com.google.inject.internal.ProviderMethodsModule.configure(ProviderMethodsModule.java:123)
	at com.google.inject.spi.Elements$RecordingBinder.install(Elements.java:340)
	at com.google.inject.spi.Elements$RecordingBinder.install(Elements.java:349)
	at com.google.inject.AbstractModule.install(AbstractModule.java:122)
	at com.google.inject.servlet.ServletModule.configure(ServletModule.java:52)
	at com.google.inject.AbstractModule.configure(AbstractModule.java:62)
	at com.google.inject.spi.Elements$RecordingBinder.install(Elements.java:340)
	at com.google.inject.spi.Elements.getElements(Elements.java:110)
	at com.google.inject.internal.InjectorShell$Builder.build(InjectorShell.java:138)
	at com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:104)
	at com.google.inject.Guice.createInjector(Guice.java:96)
	at com.google.inject.Guice.createInjector(Guice.java:73)
	at com.google.inject.Guice.createInjector(Guice.java:62)
	at org.apache.hadoop.yarn.webapp.WebApps$Builder.build(WebApps.java:417)
	at org.apache.hadoop.yarn.webapp.WebApps$Builder.start(WebApps.java:465)
	at org.apache.hadoop.yarn.server.resourcemanager.ResourceManager.startWepApp(ResourceManager.java:1389)
	at org.apache.hadoop.yarn.server.resourcemanager.ResourceManager.serviceStart(ResourceManager.java:1498)
	at org.apache.hadoop.service.AbstractService.start(AbstractService.java:194)
	at org.apache.hadoop.yarn.server.resourcemanager.ResourceManager.main(ResourceManager.java:1699)
Caused by: java.lang.reflect.InaccessibleObjectException: Unable to make protected final java.lang.Class java.lang.ClassLoader.defineClass(java.lang.String,byte[],int,int,java.security.ProtectionDomain) throws java.lang.ClassFormatError accessible: module java.base does not "opens java.lang" to unnamed module @12efa456
	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:354)
	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:297)
	at java.base/java.lang.reflect.Method.checkCanSetAccessible(Method.java:200)
	at java.base/java.lang.reflect.Method.setAccessible(Method.java:194)
	at com.google.inject.internal.cglib.core.$ReflectUtils$2.run(ReflectUtils.java:56)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:318)
	at com.google.inject.internal.cglib.core.$ReflectUtils.<clinit>(ReflectUtils.java:46)
	... 29 more
```

### What did you expect to happen?

Node manager and resource manager start successfully.

According to https://cwiki.apache.org/confluence/display/HADOOP/Hadoop+Java+Versions, Hadoop 3.3.x only have java 11 runtime support.  Depending on the latest openjdk is probably a mistake.  Meanwhile, the project should be compiled with openjdk version 8.

BTW, please also build the package with the native libraries, the following warning showed up every time:
```
2022-08-03 22:13:10,101 WARN util.NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
```

### Step-by-step reproduction instructions (by running `brew` commands)
- Install Hadoop
- Setup cluster in "Pseudo-Distributed" mode by following [this guide](https://hadoop.apache.org/docs/stable/hadoop-project-dist/hadoop-common/SingleCluster.html).
- run command ```start-all.sh```
- run command ``` jps```, and managers are not showing in the output

**Comment by cho-m** [comment]
Some detailed responses below, but beforehand, we are open to switching to `openjdk@11` but would need a PR with a valid test that can detect error with `openjdk`.

See previous attempt #98296 and corresponding reported issue #98294.

---

> However, event I changed the default openjdk to 11, the resource manager still failed to start.

How are you trying to change default? The linked scripts currently override `JAVA_HOME`, so you would probably need to use unlinked version, e.g.:
```console
❯ export JAVA_HOME="$HOMEBREW_PREFIX/opt/openjdk@11/libexec/openjdk.jdk/Contents/Home" 
❯ "$HOMEBREW_PREFIX/opt/hadoop/libexec/sbin/start-all.sh"
``` 

---

> Meanwhile, the project should be compiled with openjdk version 8.

Homebrew doesn't compile `hadoop`. The formula copies files from the official binary distribution. Since Java compiles to platform-independent bytecode, this meets our requirements.

Ref: https://docs.brew.sh/Acceptable-Formulae#we-dont-like-binary-formulae

---

> BTW, please also build the package with the native libraries, the following warning showed up every time:

Since we don't build from source, the only files we don't install are the native libraries as they don't meet our requirements.

Switching to `openjdk@8` has consequences of dropping `hadoop` and dependent formulae on M1 macs. Maybe we could build native libraries for Intel macs only, but would require someone to take a look into rewriting formula.

**Comment by Galaxy0419** [comment]
@cho-m Thanks for the reply, Hadoop is updated to 3.3.4 today and the issues still exist.

---
> we are open to switching to openjdk@11 but would need a PR with a valid test that can detect error with openjdk

Why can't we just change the depend property to ```openjdk@11```?  If we must include the test, where can I find the document?  I'm happy to contribute.

---
> You would probably need to use unlinked version

Yeah, I totally forgot the wrapper scripts override ```JAVA_HOME```, now the resource manager can start normally.  Edited the description.

**Comment by SMillerDev** [comment]
> Why can't we just change the depend property to openjdk@11? Do you mean we need to add a test that fails to start the node manager and resource manager?

We can, but without a test that fails someone will update it to depend on openjdk 18 again within weeks. That's why we need to add a test.

**Comment by Galaxy0419** [comment]
@SMillerDev How about a comment that reminds future developers that hadoop only supports java 11?

**Comment by carlocab** [comment]
Then you have someone who reads it and thinks "hmm... maybe it supports the newest Java now, since the test passes. Let's change it."

**Comment by SMillerDev** [comment]
Comments don't magically get resolved when Hadoop starts supporting JDK 17. A test will start passing when it does.

**Comment by Galaxy0419** [comment]
@carlocab @SMillerDev

How about something like "WARNING: Check https://cwiki.apache.org/confluence/display/HADOOP/Hadoop+Java+Versions before updating JDK".

I agree test is definitely the best solution for this.  However, fixing the package is also better than leaving a broken package in the repository.

**Comment by Galaxy0419** [comment]
@SMillerDev The only way I can think of is launching a new server process and check if it's alive after some time.  Does the solution sounds good enough to you?

**Comment by SMillerDev** [comment]
Sure, if possible it would also be good to ping the server.

**Comment by Galaxy0419** [comment]
Created https://github.com/Homebrew/homebrew-core/pull/107462, please review.
