### ISSUE TITLE
Python package still can be imported after `brew uninstall`

### ISSUE THREAD

**Issue by Oleksii-Svintsitskyi** [Homebrew/homebrew-core#108096]
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

```shell
https://gist.github.com/6aaf769281270e5eb5d134bdd34fcbef
```

### Verification

- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.

### What were you trying to do (and why)?

brew uninstall mapserver

### What happened (include all command output)?

`brew install mapserver`
`python3`
```
>>> import mapscript
>>> mapscript.MESSAGELENGTH
2048
```

`brew uninstall mapserver`
`python3`
```
>>> import mapscript
>>> mapscript.MESSAGELENGTH
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'mapscript' has no attribute 'MESSAGELENGTH'
```

### What did you expect to happen?

`brew install mapserver`
`python3`
```
>>> import mapscript
>>> mapscript.MESSAGELENGTH
2048
```

`brew uninstall mapserver`
`python3`
```
>>> import mapscript
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'mapscript'
```

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
Already described. Also, this happens not only to this package, but to any package installed with 
`system python, *Language::Python.setup_install_args(prefix, python)`
```

**Comment by SMillerDev** [comment]
What does `which python3` output?

**Comment by Oleksii-Svintsitskyi** [comment]
@SMillerDev `/usr/local/bin/python3`

**Comment by carlocab** [comment]
Yea, this happens because `brew` doesn't clean up all the empty directories left behind at
```
$(brew --prefix)/lib/python3.10/site-packages/mapserver
```
with `brew uninstall mapserver && brew cleanup`. It probably should.
