### ISSUE TITLE
awscli | exception | TypeError: deprecated() got an unexpected keyword argument 'name'

### ISSUE THREAD

**Issue by bender75** [Homebrew/homebrew-core#112500]
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

```shell
$ brew doctor                                                                                                                                                                                                 1 ↵
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: The filesystem on /System/Volumes/Data appears to be case-sensitive.
The default macOS filesystem is case-insensitive. Please report any apparent problems.
$ brew gist-logs awscli                                                                                                                                                                                       1 ↵
Error: No logs.
$ brew config                                                                                                                                                                                                 1 ↵
HOMEBREW_VERSION: 3.6.4-35-ge23d7b6
ORIGIN: https://github.com/Homebrew/brew
HEAD: e23d7b6360e24d64823382ad3d93a9e5e6b3b06f
Last commit: 27 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: bdb0b5d5a52817a88eb0c17332f9b0b6bf5dd49e
Core tap last commit: 33 minutes ago
Core tap branch: master
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CASK_OPTS: []
HOMEBREW_DISPLAY: /private/tmp/com.apple.launchd.o6L9tTtehE/org.xquartz:0
HOMEBREW_MAKE_JOBS: 6
Homebrew Ruby: 2.6.8 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: hexa-core 64-bit kabylake
Clang: 14.0.0 build 1400
Git: 2.38.0 => /usr/local/bin/git
Curl: 7.79.1 => /usr/bin/curl
macOS: 12.6-x86_64
CLT: 14.0.0.0.1.1661618636
Xcode: 14.0.1


$ brew info awscli
==> awscli: stable 2.7.31 (bottled), HEAD
Official Amazon AWS command-line interface
https://aws.amazon.com/cli/
/usr/local/Cellar/awscli/2.7.31 (12,785 files, 104.3MB) *
  Poured from bottle on 2022-10-06 at 17:37:19
From: https://github.com/Homebrew/homebrew-core/blob/HEAD/Formula/awscli.rb
License: Apache-2.0
==> Dependencies
Build: cmake ✔, rust ✘
Required: python@3.10 ✔, six ✔
==> Options
--HEAD
	Install HEAD version
==> Caveats
The "examples" directory has been installed to:
  /usr/local/share/awscli/examples

zsh completions and functions have been installed to:
  /usr/local/share/zsh/site-functions
==> Analytics
install: 169,550 (30 days), 673,187 (90 days), 2,612,240 (365 days)
install-on-request: 167,276 (30 days), 663,515 (90 days), 2,584,234 (365 days)
build-error: 63 (30 days)
```

### Verification

- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.

### What were you trying to do (and why)?

aws cli doesnt work expected.
on any command i'm facing an exception

### What happened (include all command output)?
```
$ aws --help
Traceback (most recent call last):
  File "/usr/local/bin/aws", line 19, in <module>
    import awscli.clidriver
  File "/usr/local/Cellar/awscli/2.7.31/libexec/lib/python3.10/site-packages/awscli/clidriver.py", line 20, in <module>
    import botocore.session
  File "/usr/local/Cellar/awscli/2.7.31/libexec/lib/python3.10/site-packages/awscli/botocore/session.py", line 27, in <module>
    import botocore.client
  File "/usr/local/Cellar/awscli/2.7.31/libexec/lib/python3.10/site-packages/awscli/botocore/client.py", line 16, in <module>
    from botocore import UNSIGNED, waiter, xform_name
  File "/usr/local/Cellar/awscli/2.7.31/libexec/lib/python3.10/site-packages/awscli/botocore/waiter.py", line 17, in <module>
    from botocore.docs.docstring import WaiterDocstring
  File "/usr/local/Cellar/awscli/2.7.31/libexec/lib/python3.10/site-packages/awscli/botocore/docs/__init__.py", line 15, in <module>
    from botocore.docs.service import ServiceDocumenter
  File "/usr/local/Cellar/awscli/2.7.31/libexec/lib/python3.10/site-packages/awscli/botocore/docs/service.py", line 14, in <module>
    from botocore.docs.client import ClientDocumenter, ClientExceptionsDocumenter
  File "/usr/local/Cellar/awscli/2.7.31/libexec/lib/python3.10/site-packages/awscli/botocore/docs/client.py", line 16, in <module>
    from botocore.docs.example import ResponseExampleDocumenter
  File "/usr/local/Cellar/awscli/2.7.31/libexec/lib/python3.10/site-packages/awscli/botocore/docs/example.py", line 13, in <module>
    from botocore.docs.shape import ShapeDocumenter
  File "/usr/local/Cellar/awscli/2.7.31/libexec/lib/python3.10/site-packages/awscli/botocore/docs/shape.py", line 19, in <module>
    from botocore.utils import is_json_value_header
  File "/usr/local/Cellar/awscli/2.7.31/libexec/lib/python3.10/site-packages/awscli/botocore/utils.py", line 32, in <module>
    import botocore.httpsession
  File "/usr/local/Cellar/awscli/2.7.31/libexec/lib/python3.10/site-packages/awscli/botocore/httpsession.py", line 41, in <module>
    from urllib3.contrib.pyopenssl import orig_util_SSLContext as SSLContext
  File "/usr/local/Cellar/awscli/2.7.31/libexec/lib/python3.10/site-packages/urllib3/contrib/pyopenssl.py", line 50, in <module>
    import OpenSSL.SSL
  File "/usr/local/lib/python3.10/site-packages/OpenSSL/__init__.py", line 8, in <module>
    from OpenSSL import SSL, crypto
  File "/usr/local/lib/python3.10/site-packages/OpenSSL/SSL.py", line 19, in <module>
    from OpenSSL.crypto import (
  File "/usr/local/lib/python3.10/site-packages/OpenSSL/crypto.py", line 3224, in <module>
    utils.deprecated(
TypeError: deprecated() got an unexpected keyword argument 'name'
```
### What did you expect to happen?

aws cli should work like expected

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
brew install awscli
aws --help
```

**Comment by carlocab** [comment]
Can't reproduce:
```
❯ brew install awscli
==> Downloading https://ghcr.io/v2/homebrew/core/awscli/manifests/2.7.31
######################################################################## 100.0%
==> Downloading https://ghcr.io/v2/homebrew/core/awscli/blobs/sha256:745497843b0ab4d0d8732b394febfa2960f2b1b9d6b7cdfdd51c15f2589f037f
==> Downloading from https://pkg-containers.githubusercontent.com/ghcr1/blobs/sha256:745497843b0ab4d0d8732b394febfa2960f2b1b9d6b7cdfdd51c15f2589f037f?
######################################################################## 100.0%
==> Pouring awscli--2.7.31.monterey.bottle.tar.gz
==> Caveats
The "examples" directory has been installed to:
  /usr/local/share/awscli/examples

zsh completions and functions have been installed to:
  /usr/local/share/zsh/site-functions
==> Summary
🍺  /usr/local/Cellar/awscli/2.7.31: 12,671 files, 103.4MB
==> Running `brew cleanup awscli`...
Disable this behaviour by setting HOMEBREW_NO_INSTALL_CLEANUP.
Hide these hints with HOMEBREW_NO_ENV_HINTS (see `man brew`).
❯ aws --help
usage: aws [-h] [--profile PROFILE] [--debug]

options:
  -h, --help         show this help message and exit
  --profile PROFILE
  --debug
```

**Comment by Bo98** [comment]
`pip uninstall pyOpenSSL` or upgrade `cryptography`.

**Comment by bender75** [comment]
Hi,
I'm very sorry that i reported my issue as a bug.
`pip3.10 uninstall pyOpenSSL` solved my issue.
Thank you very much and sorry about the circumstances.
