### ISSUE TITLE
libxt Intrinsic.h is broken

### ISSUE THREAD

**Issue by cheyao** [Homebrew/homebrew-core#114378]
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

```shell
brew config

HOMEBREW_VERSION: 3.6.7-44-gfa2649d
ORIGIN: https://github.com/Homebrew/brew
HEAD: fa2649dde786208da7d151a89bcafdd23a453f4d
Last commit: 3 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 691a699d73cb241ea2b090b20c74aa91e886cb38
Core tap last commit: 52 minutes ago
Core tap branch: master
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CASK_OPTS: []
HOMEBREW_MAKE_JOBS: 4
Homebrew Ruby: 2.6.8 => /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.8_1/bin/ruby
CPU: quad-core 64-bit haswell
Clang: 13.0.0 build 1300
Git: 2.32.0 => /Library/Developer/CommandLineTools/usr/bin/git
Curl: 7.64.1 => /usr/bin/curl
macOS: 11.6.1-x86_64
CLT: 13.2.0.0.1.1638488800
Xcode: N/A
```

brew doctor 
```
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: No Cask quarantine support available: there's no working version of `xattr` on this system.
Traceback (most recent call last):
  File "/usr/bin/xattr", line 8, in <module>
    from pkg_resources import load_entry_point
  File "/Users/ray/Library/Python/2.7/lib/python/site-packages/pkg_resources/__init__.py", line 3251, in <module>
    @_call_aside
  File "/Users/ray/Library/Python/2.7/lib/python/site-packages/pkg_resources/__init__.py", line 3235, in _call_aside
    f(*args, **kwargs)
  File "/Users/ray/Library/Python/2.7/lib/python/site-packages/pkg_resources/__init__.py", line 3264, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/Users/ray/Library/Python/2.7/lib/python/site-packages/pkg_resources/__init__.py", line 583, in _build_master
    ws.require(__requires__)
  File "/Users/ray/Library/Python/2.7/lib/python/site-packages/pkg_resources/__init__.py", line 900, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/Users/ray/Library/Python/2.7/lib/python/site-packages/pkg_resources/__init__.py", line 786, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'xattr==0.6.4' distribution was not found and is required by the application

Warning: Your Python installation is unable to find `xattr`
```
Don't mind the xattr I replaced it with a good one in /usr/local/bin but don't have permision to touch /usr/bin
```


### Verification

- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.

### What were you trying to do (and why)?

I was trying to generate a schematic for my cpu, so i needed qflow, and it depends on qrouter, so I downloaded it and compiled it. but to enable gui it needed libxt so i downloaded it, but it is giving a bunch of erros

### What happened (include all command output)?

cc -g -O2   -I/usr/local/Cellar/tcl-tk/8.6.12_1/include -I/sw/include -fno-common  -fPIC -DPACKAGE_NAME=\"\" -DPACKAGE_TARNAME=\"\" -DPACKAGE_VERSION=\"\" -DPACKAGE_STRING=\"\" -DPACKAGE_BUGREPORT=\"\" -DPACKAGE_URL=\"\" -DSTDC_HEADERS=1 -DHAVE_SETENV=1 -DHAVE_PUTENV=1 -DHAVE_VA_COPY=1 -DHAVE___VA_COPY=1 -DHAVE_LIBXT=1 -DHAVE_SYS_TYPES_H=1 -DHAVE_SYS_STAT_H=1 -DHAVE_STDLIB_H=1 -DHAVE_STRING_H=1 -DHAVE_MEMORY_H=1 -DHAVE_STRINGS_H=1 -DHAVE_INTTYPES_H=1 -DHAVE_STDINT_H=1 -DHAVE_UNISTD_H=1 -DHAVE_SYS_MMAN_H=1 -DTCL_QROUTER=1 -DVERSION=\"1.4\" -DREVISION=\"85\" -DUSE_TCL_STUBS -DUSE_TK_STUBS \
		-DQROUTER_PATH=\"/usr/local/share/qrouter\" -I/usr/local/Cellar/tcl-tk/8.6.12_1/include -c graphics.c -o graphics.o
In file included from graphics.c:10:
/usr/local/include/X11/Intrinsic.h:1181:3: error: expected function body after function declarator
) _X_SENTINEL(0);
  ^
/usr/local/include/X11/Intrinsic.h:1325:3: error: expected function body after function declarator
) _X_SENTINEL(0);
  ^
/usr/local/include/X11/Intrinsic.h:1392:3: error: expected function body after function declarator
) _X_SENTINEL(0);
  ^
/usr/local/include/X11/Intrinsic.h:1399:3: error: expected function body after function declarator
) _X_SENTINEL(0);
  ^
/usr/local/include/X11/Intrinsic.h:1423:3: error: expected function body after function declarator
) _X_SENTINEL(0);
  ^
/usr/local/include/X11/Intrinsic.h:1475:3: error: expected function body after function declarator
) _X_SENTINEL(0);
  ^
/usr/local/include/X11/Intrinsic.h:1498:3: error: expected function body after function declarator
) _X_SENTINEL(0);
  ^
/usr/local/include/X11/Intrinsic.h:1572:3: error: expected function body after function declarator
) _X_SENTINEL(0);
  ^
/usr/local/include/X11/Intrinsic.h:1593:3: error: expected function body after function declarator
) _X_SENTINEL(0);
  ^
/usr/local/include/X11/Intrinsic.h:1604:3: error: expected function body after function declarator
) _X_SENTINEL(0);
  ^
/usr/local/include/X11/Intrinsic.h:1615:3: error: expected function body after function declarator
) _X_SENTINEL(0);
  ^
/usr/local/include/X11/Intrinsic.h:1630:3: error: expected function body after function declarator
) _X_SENTINEL(0);
  ^
/usr/local/include/X11/Intrinsic.h:1645:3: error: expected function body after function declarator
) _X_SENTINEL(0);
  ^
/usr/local/include/X11/Intrinsic.h:1739:3: error: expected function body after function declarator
) _X_NORETURN;
  ^
/usr/local/include/X11/Intrinsic.h:1748:3: error: expected function body after function declarator
) _X_NORETURN;
  ^
/usr/local/include/X11/Intrinsic.h:1790:3: error: expected function body after function declarator
) _X_NORETURN;
  ^
/usr/local/include/X11/Intrinsic.h:1794:3: error: expected function body after function declarator
) _X_NORETURN;
  ^
/usr/local/include/X11/Intrinsic.h:1864:3: error: expected function body after function declarator
) _X_ATTRIBUTE_PRINTF(2,3);
  ^
graphics.c:78:5: error: implicit declaration of function 'XSetForeground' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
    XSetForeground(dpy, gc, yellowpix);
    ^
fatal error: too many errors emitted, stopping now [-ferror-limit=]
20 errors generated.
make: *** [graphics.o] Error 1

### What did you expect to happen?

just compile

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
brew install libxt

curl http://opencircuitdesign.com/qrouter/archive/qrouter-1.4.85.tgz >> qrouter

tar -xf qrouter

cd qrouter

./configure --with-tcl=/usr/local/Cellar/tcl-tk/8.6.12_1/lib --with-tk=/usr/local/Cellar/tcl-tk/8.6.12_1/lib

make
```

**Comment by SMillerDev** [comment]
There's nothing brew can do about your system missing essential system libraries.

**Comment by cheyao** [comment]
My system isn't missing essential system libraries, its that the libxt that brew installed isn't working

**Comment by SMillerDev** [comment]
> Warning: No Cask quarantine support available: there's no working version of `xattr` on this system.

This suggests otherwise
