### ISSUE TITLE
Latest gopass 1.14.10 from homebrew fails sporadically

### ISSUE THREAD

**Issue by davidolrik** [Homebrew/homebrew-core#115765]
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

```shell
$ brew config
HOMEBREW_VERSION: 3.6.11
ORIGIN: https://github.com/Homebrew/brew
HEAD: b7391069d48805c786b1e9fe88edf795960321dc
Last commit: 12 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: f75a93f870686e69b37ea4aa62d15dbdc4fe82c6
Core tap last commit: 59 minutes ago
Core tap branch: master
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CASK_OPTS: []
HOMEBREW_EDITOR: code_wait
HOMEBREW_MAKE_JOBS: 16
http_proxy: http://127.0.0.1:8118
https_proxy: http://127.0.0.1:8118
no_proxy: 127.0.0.1,192.0.2.0/24,198.51.100.0/24,203.0.113.0/24,localhost,docker
Homebrew Ruby: 2.6.10 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: 16-core 64-bit kabylake
Clang: 14.0.0 build 1400
Git: 2.38.1 => /usr/local/bin/git
Curl: 7.84.0 => /usr/bin/curl
macOS: 13.0.1-x86_64
CLT: 14.1.0.0.1.1666437224
Xcode: 14.1
```

```sh
$ brew doctor
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: "config" scripts exist outside your system or Homebrew directories.
`./configure` scripts often look for *-config scripts to determine if
software packages are installed, and which additional flags to use when
compiling and linking.

Having additional scripts in your path can confuse software installed via
Homebrew if the config script overrides a system or Homebrew-provided
script of the same name. We found the following "config" scripts:
  /Users/djo/.asdf/installs/python/3.11.0/bin/python-config
  /Users/djo/.asdf/installs/python/3.11.0/bin/python3-config
  /Users/djo/.asdf/installs/python/3.11.0/bin/ansible-config
  /Users/djo/.asdf/installs/python/3.11.0/bin/python3.11-config
  /Users/djo/.asdf/shims/python3.10-config
  /Users/djo/.asdf/shims/python3.9-config
  /Users/djo/.asdf/shims/python-config
  /Users/djo/.asdf/shims/python3-config
  /Users/djo/.asdf/shims/ansible-config
  /Users/djo/.asdf/shims/python3.8-config
  /Users/djo/.asdf/shims/python3.11-config
  /Users/djo/.asdf/shims/php-config

Warning: You have unlinked kegs in your Cellar.
Leaving kegs unlinked can lead to build-trouble and cause formulae that depend on
those kegs to fail to run properly once built. Run `brew link` on these:
  python-typing-extensions
  six
```

### Verification

- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.

### What were you trying to do (and why)?

Running `gopass show --password` fails sporadicly.

Running the command repeatedly will make it fail about 1 in 10 times.

### What happened (include all command output)?

```sh
$ /usr/local/Cellar/gopass/1.14.10/bin/gopass secret
runtime: nameOff 0x34312e31 base 0xa3b37b0 not in ranges:
	types 0xa3c6000 etypes 0xa54cce8
fatal error: runtime: name offset base pointer out of range

goroutine 10 [running]:
runtime.throw({0xa2d35a7?, 0xc000148da3?})
	runtime/panic.go:1047 +0x5d fp=0xc0001f8c28 sp=0xc0001f8bf8 pc=0x9cadcbd
runtime.resolveNameOff(0xc000148dc4?, 0x34312e31)
	runtime/type.go:221 +0x1d6 fp=0xc0001f8c80 sp=0xc0001f8c28 pc=0x9cd6936
runtime.(*_type).nameOff(...)
	runtime/type.go:227
runtime.(*_type).string(0xa3b37b0)
	runtime/type.go:55 +0x25 fp=0xc0001f8ca0 sp=0xc0001f8c80 pc=0x9cd65c5
runtime.(*TypeAssertionError).Error(0xc00050c030)
	runtime/error.go:39 +0x9e fp=0xc0001f8da8 sp=0xc0001f8ca0 pc=0x9c8017e
runtime.preprintpanics(0xc0000920a0?)
	runtime/panic.go:581 +0x7f fp=0xc0001f8e08 sp=0xc0001f8da8 pc=0x9cacb1f
panic({0xa451c20, 0xc00050c030})
	runtime/panic.go:985 +0x3ac fp=0xc0001f8ec8 sp=0xc0001f8e08 pc=0x9cad86c
runtime.panicdottypeE(0xa3b37b0, 0xa413e40, 0xa435100)
	runtime/iface.go:262 +0x6a fp=0xc0001f8ee8 sp=0xc0001f8ec8 pc=0x9c82b2a
context.(*cancelCtx).Done(0x7?)
	context/context.go:361 +0x1d4 fp=0xc0001f8f68 sp=0xc0001f8ee8 pc=0x9d0ac74
main.main.func2()
	/private/tmp/gopass-20221110-9511-1b72ciz/main.go:74 +0x3b fp=0xc0001f8fe0 sp=0xc0001f8f68 pc=0xa29201b
runtime.goexit()
	runtime/asm_amd64.s:1594 +0x1 fp=0xc0001f8fe8 sp=0xc0001f8fe0 pc=0x9cdfee1
created by main.main
	/private/tmp/gopass-20221110-9511-1b72ciz/main.go:70 +0x1db

goroutine 1 [runnable]:
syscall.syscall(0xc00078a000?, 0x32?, 0x9c9f705?, 0xc000475590?)
	runtime/sys_darwin.go:23 +0x7f fp=0xc000475550 sp=0xc0004754c0 pc=0x9cdc75f
syscall.Stat({0xc00078a000?, 0x32?}, 0xc00078c038)
	syscall/zsyscall_darwin_amd64.go:1942 +0x75 fp=0xc0004755a0 sp=0xc000475550 pc=0x9cf44b5
os.statNolog.func1(...)
	os/stat_unix.go:32
os.ignoringEINTR(...)
	os/file_posix.go:245
os.statNolog({0xc00078a000, 0x32})
	os/stat_unix.go:31 +0x4f fp=0xc0004755e0 sp=0xc0004755a0 pc=0x9d557cf
os.Stat({0xc00078a000, 0x32})
	os/stat.go:13 +0x34 fp=0xc000475600 sp=0xc0004755e0 pc=0x9d55314
github.com/gopasspw/gopass/pkg/fsutil.IsFile({0xc00078a000, 0x32})
	github.com/gopasspw/gopass/pkg/fsutil/fsutil.go:69 +0x27 fp=0xc000475658 sp=0xc000475600 pc=0x9de3147
github.com/gopasspw/gopass/internal/backend/storage/fs.(*Store).Exists(0xc000780000, {0x20?, 0xa510e80?}, {0xa29ca70, 0x7})
	github.com/gopasspw/gopass/internal/backend/storage/fs/store.go:142 +0x8b fp=0xc0004756d8 sp=0xc000475658 pc=0xa28284b
github.com/gopasspw/gopass/internal/backend/storage/gitfs.(*Git).Exists(0xac1f178?, {0xa50e7d0?, 0xc000202000?}, {0xa29ca70?, 0x0?})
	github.com/gopasspw/gopass/internal/backend/storage/gitfs/storage.go:27 +0x2b fp=0xc000475710 sp=0xc0004756d8 pc=0xa290d4b
github.com/gopasspw/gopass/internal/backend/crypto/gpg/cli.loader.Handles({}, {0xa50e7d0?, 0xc000202000?}, {0xa514158?, 0xc000782000?})
	github.com/gopasspw/gopass/internal/backend/crypto/gpg/cli/loader.go:36 +0x49 fp=0xc000475748 sp=0xc000475710 pc=0xa22b369
github.com/gopasspw/gopass/internal/backend/crypto/gpg/cli.(*loader).Handles(0xa510e80?, {0xa50e7d0?, 0xc000202000?}, {0xa514158?, 0xc000782000?})
	<autogenerated>:1 +0x47 fp=0xc000475778 sp=0xc000475748 pc=0xa22c5a7
github.com/gopasspw/gopass/internal/backend.DetectCrypto({0xa50e7d0, 0xc000202000}, {0xa514158?, 0xc000782000})
	github.com/gopasspw/gopass/internal/backend/crypto.go:81 +0x26b fp=0xc0004757e8 sp=0xc000475778 pc=0xa081c4b
github.com/gopasspw/gopass/internal/store/leaf.(*Store).initCryptoBackend(0xc0002c90c0, {0xa50e7d0?, 0xc000202000?})
	github.com/gopasspw/gopass/internal/store/leaf/crypto.go:16 +0x39 fp=0xc000475818 sp=0xc0004757e8 pc=0xa10b399
github.com/gopasspw/gopass/internal/store/leaf.New({0xa50e7d0, 0xc000202000}, {0x0, 0x0}, {0xc000032cf0, 0x2a})
	github.com/gopasspw/gopass/internal/store/leaf/store.go:67 +0x2e5 fp=0xc000475888 sp=0xc000475818 pc=0xa116d45
github.com/gopasspw/gopass/internal/store/root.(*Store).initialize(0xc00054e000, {0xa50e7d0, 0xc000202000})
	github.com/gopasspw/gopass/internal/store/root/init.go:81 +0x15d fp=0xc0004759f0 sp=0xc000475888 pc=0xa11b7dd
github.com/gopasspw/gopass/internal/store/root.(*Store).IsInitialized(0xc00054e000, {0xa50e7d0, 0xc000202000})
	github.com/gopasspw/gopass/internal/store/root/init.go:20 +0x6a fp=0xc000475a40 sp=0xc0004759f0 pc=0xa11aeaa
github.com/gopasspw/gopass/internal/action.(*Action).IsInitialized(0xc0001a6000, 0x1?)
	github.com/gopasspw/gopass/internal/action/init.go:32 +0x52 fp=0xc000475ac0 sp=0xc000475a40 pc=0xa2620d2
main.setupApp.func2(0xc0002c8200)
	/private/tmp/gopass-20221110-9511-1b72ciz/main.go:134 +0x31 fp=0xc000475b00 sp=0xc000475ac0 pc=0xa292571
github.com/urfave/cli/v2.(*Command).Run(0xc0002cf540, 0xc0002c8200, {0xc000022040, 0x2, 0x2})
	github.com/urfave/cli/v2@v2.23.5/command.go:271 +0xaab fp=0xc000475d90 sp=0xc000475b00 pc=0xa0238eb
github.com/urfave/cli/v2.(*App).RunContext(0xc0003d6000, {0xa50e7d0?, 0xc000202000}, {0xc000022040, 0x2, 0x2})
	github.com/urfave/cli/v2@v2.23.5/app.go:329 +0x665 fp=0xc000475e00 sp=0xc000475d90 pc=0xa020605
main.main()
	/private/tmp/gopass-20221110-9511-1b72ciz/main.go:89 +0x452 fp=0xc000475f80 sp=0xc000475e00 pc=0xa291f32
runtime.main()
	runtime/proc.go:250 +0x212 fp=0xc000475fe0 sp=0xc000475f80 pc=0x9cb04d2
runtime.goexit()
	runtime/asm_amd64.s:1594 +0x1 fp=0xc000475fe8 sp=0xc000475fe0 pc=0x9cdfee1

goroutine 2 [force gc (idle)]:
runtime.gopark(0x0?, 0x0?, 0x0?, 0x0?, 0x0?)
	runtime/proc.go:363 +0xd6 fp=0xc000070fb0 sp=0xc000070f90 pc=0x9cb0896
runtime.goparkunlock(...)
	runtime/proc.go:369
runtime.forcegchelper()
	runtime/proc.go:302 +0xad fp=0xc000070fe0 sp=0xc000070fb0 pc=0x9cb072d
runtime.goexit()
	runtime/asm_amd64.s:1594 +0x1 fp=0xc000070fe8 sp=0xc000070fe0 pc=0x9cdfee1
created by runtime.init.6
	runtime/proc.go:290 +0x25

goroutine 3 [GC sweep wait]:
runtime.gopark(0x1?, 0x0?, 0x0?, 0x0?, 0x0?)
	runtime/proc.go:363 +0xd6 fp=0xc000071790 sp=0xc000071770 pc=0x9cb0896
runtime.goparkunlock(...)
	runtime/proc.go:369
runtime.bgsweep(0x0?)
	runtime/mgcsweep.go:297 +0xd7 fp=0xc0000717c8 sp=0xc000071790 pc=0x9c9c7f7
runtime.gcenable.func1()
	runtime/mgc.go:178 +0x26 fp=0xc0000717e0 sp=0xc0000717c8 pc=0x9c91466
runtime.goexit()
	runtime/asm_amd64.s:1594 +0x1 fp=0xc0000717e8 sp=0xc0000717e0 pc=0x9cdfee1
created by runtime.gcenable
	runtime/mgc.go:178 +0x6b

goroutine 4 [GC scavenge wait]:
runtime.gopark(0xc0000380e0?, 0xa3b37c0?, 0x0?, 0x0?, 0x0?)
	runtime/proc.go:363 +0xd6 fp=0xc000071f70 sp=0xc000071f50 pc=0x9cb0896
runtime.goparkunlock(...)
	runtime/proc.go:369
runtime.(*scavengerState).park(0xa97c300)
	runtime/mgcscavenge.go:389 +0x53 fp=0xc000071fa0 sp=0xc000071f70 pc=0x9c9a853
runtime.bgscavenge(0x0?)
	runtime/mgcscavenge.go:622 +0x65 fp=0xc000071fc8 sp=0xc000071fa0 pc=0x9c9ae45
runtime.gcenable.func2()
	runtime/mgc.go:179 +0x26 fp=0xc000071fe0 sp=0xc000071fc8 pc=0x9c91406
runtime.goexit()
	runtime/asm_amd64.s:1594 +0x1 fp=0xc000071fe8 sp=0xc000071fe0 pc=0x9cdfee1
created by runtime.gcenable
	runtime/mgc.go:179 +0xaa

goroutine 5 [finalizer wait]:
runtime.gopark(0x9cb0c17?, 0x9cb0665?, 0x0?, 0x0?, 0xc000070770?)
	runtime/proc.go:363 +0xd6 fp=0xc000070628 sp=0xc000070608 pc=0x9cb0896
runtime.goparkunlock(...)
	runtime/proc.go:369
runtime.runfinq()
	runtime/mfinal.go:180 +0x10f fp=0xc0000707e0 sp=0xc000070628 pc=0x9c9056f
runtime.goexit()
	runtime/asm_amd64.s:1594 +0x1 fp=0xc0000707e8 sp=0xc0000707e0 pc=0x9cdfee1
created by runtime.createfing
	runtime/mfinal.go:157 +0x45

goroutine 6 [GC worker (idle)]:
runtime.gopark(0x0?, 0x0?, 0x0?, 0x0?, 0x0?)
	runtime/proc.go:363 +0xd6 fp=0xc000072750 sp=0xc000072730 pc=0x9cb0896
runtime.gcBgMarkWorker()
	runtime/mgc.go:1235 +0xf1 fp=0xc0000727e0 sp=0xc000072750 pc=0x9c935b1
runtime.goexit()
	runtime/asm_amd64.s:1594 +0x1 fp=0xc0000727e8 sp=0xc0000727e0 pc=0x9cdfee1
created by runtime.gcBgMarkStartWorkers
	runtime/mgc.go:1159 +0x25

goroutine 17 [GC worker (idle)]:
runtime.gopark(0x0?, 0x0?, 0x0?, 0x0?, 0x0?)
	runtime/proc.go:363 +0xd6 fp=0xc00006c750 sp=0xc00006c730 pc=0x9cb0896
runtime.gcBgMarkWorker()
	runtime/mgc.go:1235 +0xf1 fp=0xc00006c7e0 sp=0xc00006c750 pc=0x9c935b1
runtime.goexit()
	runtime/asm_amd64.s:1594 +0x1 fp=0xc00006c7e8 sp=0xc00006c7e0 pc=0x9cdfee1
created by runtime.gcBgMarkStartWorkers
	runtime/mgc.go:1159 +0x25

goroutine 33 [GC worker (idle)]:
runtime.gopark(0x0?, 0x0?, 0x0?, 0x0?, 0x0?)
	runtime/proc.go:363 +0xd6 fp=0xc0004b8750 sp=0xc0004b8730 pc=0x9cb0896
runtime.gcBgMarkWorker()
	runtime/mgc.go:1235 +0xf1 fp=0xc0004b87e0 sp=0xc0004b8750 pc=0x9c935b1
runtime.goexit()
	runtime/asm_amd64.s:1594 +0x1 fp=0xc0004b87e8 sp=0xc0004b87e0 pc=0x9cdfee1
created by runtime.gcBgMarkStartWorkers
	runtime/mgc.go:1159 +0x25

goroutine 7 [GC worker (idle)]:
runtime.gopark(0x0?, 0x0?, 0x0?, 0x0?, 0x0?)
	runtime/proc.go:363 +0xd6 fp=0xc000072f50 sp=0xc000072f30 pc=0x9cb0896
runtime.gcBgMarkWorker()
	runtime/mgc.go:1235 +0xf1 fp=0xc000072fe0 sp=0xc000072f50 pc=0x9c935b1
runtime.goexit()
	runtime/asm_amd64.s:1594 +0x1 fp=0xc000072fe8 sp=0xc000072fe0 pc=0x9cdfee1
created by runtime.gcBgMarkStartWorkers
	runtime/mgc.go:1159 +0x25

goroutine 18 [GC worker (idle)]:
runtime.gopark(0x0?, 0x0?, 0x0?, 0x0?, 0x0?)
	runtime/proc.go:363 +0xd6 fp=0xc00006cf50 sp=0xc00006cf30 pc=0x9cb0896
runtime.gcBgMarkWorker()
	runtime/mgc.go:1235 +0xf1 fp=0xc00006cfe0 sp=0xc00006cf50 pc=0x9c935b1
runtime.goexit()
	runtime/asm_amd64.s:1594 +0x1 fp=0xc00006cfe8 sp=0xc00006cfe0 pc=0x9cdfee1
created by runtime.gcBgMarkStartWorkers
	runtime/mgc.go:1159 +0x25

goroutine 34 [GC worker (idle)]:
runtime.gopark(0x0?, 0x0?, 0x0?, 0x0?, 0x0?)
	runtime/proc.go:363 +0xd6 fp=0xc0004b8f50 sp=0xc0004b8f30 pc=0x9cb0896
runtime.gcBgMarkWorker()
	runtime/mgc.go:1235 +0xf1 fp=0xc0004b8fe0 sp=0xc0004b8f50 pc=0x9c935b1
runtime.goexit()
	runtime/asm_amd64.s:1594 +0x1 fp=0xc0004b8fe8 sp=0xc0004b8fe0 pc=0x9cdfee1
created by runtime.gcBgMarkStartWorkers
	runtime/mgc.go:1159 +0x25

goroutine 35 [GC worker (idle)]:
runtime.gopark(0x0?, 0x0?, 0x0?, 0x0?, 0x0?)
	runtime/proc.go:363 +0xd6 fp=0xc0004b9750 sp=0xc0004b9730 pc=0x9cb0896
runtime.gcBgMarkWorker()
	runtime/mgc.go:1235 +0xf1 fp=0xc0004b97e0 sp=0xc0004b9750 pc=0x9c935b1
runtime.goexit()
	runtime/asm_amd64.s:1594 +0x1 fp=0xc0004b97e8 sp=0xc0004b97e0 pc=0x9cdfee1
created by runtime.gcBgMarkStartWorkers
	runtime/mgc.go:1159 +0x25

goroutine 19 [GC worker (idle)]:
runtime.gopark(0x0?, 0x0?, 0x0?, 0x0?, 0x0?)
	runtime/proc.go:363 +0xd6 fp=0xc00006d750 sp=0xc00006d730 pc=0x9cb0896
runtime.gcBgMarkWorker()
	runtime/mgc.go:1235 +0xf1 fp=0xc00006d7e0 sp=0xc00006d750 pc=0x9c935b1
runtime.goexit()
	runtime/asm_amd64.s:1594 +0x1 fp=0xc00006d7e8 sp=0xc00006d7e0 pc=0x9cdfee1
created by runtime.gcBgMarkStartWorkers
	runtime/mgc.go:1159 +0x25

goroutine 36 [GC worker (idle)]:
runtime.gopark(0x5807e52be10?, 0x0?, 0x0?, 0x0?, 0x0?)
	runtime/proc.go:363 +0xd6 fp=0xc0004b9f50 sp=0xc0004b9f30 pc=0x9cb0896
runtime.gcBgMarkWorker()
	runtime/mgc.go:1235 +0xf1 fp=0xc0004b9fe0 sp=0xc0004b9f50 pc=0x9c935b1
runtime.goexit()
	runtime/asm_amd64.s:1594 +0x1 fp=0xc0004b9fe8 sp=0xc0004b9fe0 pc=0x9cdfee1
created by runtime.gcBgMarkStartWorkers
	runtime/mgc.go:1159 +0x25

goroutine 37 [GC worker (idle)]:
runtime.gopark(0x5807e629571?, 0x1?, 0x6a?, 0x55?, 0x0?)
	runtime/proc.go:363 +0xd6 fp=0xc0004ba750 sp=0xc0004ba730 pc=0x9cb0896
runtime.gcBgMarkWorker()
	runtime/mgc.go:1235 +0xf1 fp=0xc0004ba7e0 sp=0xc0004ba750 pc=0x9c935b1
runtime.goexit()
	runtime/asm_amd64.s:1594 +0x1 fp=0xc0004ba7e8 sp=0xc0004ba7e0 pc=0x9cdfee1
created by runtime.gcBgMarkStartWorkers
	runtime/mgc.go:1159 +0x25

goroutine 20 [GC worker (idle)]:
runtime.gopark(0xa9ad720?, 0x1?, 0xbc?, 0x67?, 0x0?)
	runtime/proc.go:363 +0xd6 fp=0xc00006df50 sp=0xc00006df30 pc=0x9cb0896
runtime.gcBgMarkWorker()
	runtime/mgc.go:1235 +0xf1 fp=0xc00006dfe0 sp=0xc00006df50 pc=0x9c935b1
runtime.goexit()
	runtime/asm_amd64.s:1594 +0x1 fp=0xc00006dfe8 sp=0xc00006dfe0 pc=0x9cdfee1
created by runtime.gcBgMarkStartWorkers
	runtime/mgc.go:1159 +0x25

goroutine 21 [GC worker (idle)]:
runtime.gopark(0x5807e4fe86a?, 0x1?, 0xb4?, 0xd?, 0x0?)
	runtime/proc.go:363 +0xd6 fp=0xc00006e750 sp=0xc00006e730 pc=0x9cb0896
runtime.gcBgMarkWorker()
	runtime/mgc.go:1235 +0xf1 fp=0xc00006e7e0 sp=0xc00006e750 pc=0x9c935b1
runtime.goexit()
	runtime/asm_amd64.s:1594 +0x1 fp=0xc00006e7e8 sp=0xc00006e7e0 pc=0x9cdfee1
created by runtime.gcBgMarkStartWorkers
	runtime/mgc.go:1159 +0x25

goroutine 38 [GC worker (idle)]:
runtime.gopark(0xa9ad720?, 0x3?, 0x5f?, 0x74?, 0x0?)
	runtime/proc.go:363 +0xd6 fp=0xc0004baf50 sp=0xc0004baf30 pc=0x9cb0896
runtime.gcBgMarkWorker()
	runtime/mgc.go:1235 +0xf1 fp=0xc0004bafe0 sp=0xc0004baf50 pc=0x9c935b1
runtime.goexit()
	runtime/asm_amd64.s:1594 +0x1 fp=0xc0004bafe8 sp=0xc0004bafe0 pc=0x9cdfee1
created by runtime.gcBgMarkStartWorkers
	runtime/mgc.go:1159 +0x25

goroutine 22 [GC worker (idle)]:
runtime.gopark(0x5807e638fd0?, 0x1?, 0xfd?, 0xf8?, 0x0?)
	runtime/proc.go:363 +0xd6 fp=0xc00006ef50 sp=0xc00006ef30 pc=0x9cb0896
runtime.gcBgMarkWorker()
	runtime/mgc.go:1235 +0xf1 fp=0xc00006efe0 sp=0xc00006ef50 pc=0x9c935b1
runtime.goexit()
	runtime/asm_amd64.s:1594 +0x1 fp=0xc00006efe8 sp=0xc00006efe0 pc=0x9cdfee1
created by runtime.gcBgMarkStartWorkers
	runtime/mgc.go:1159 +0x25

goroutine 8 [GC worker (idle)]:
runtime.gopark(0xa9ad720?, 0x1?, 0xe?, 0xd4?, 0x0?)
	runtime/proc.go:363 +0xd6 fp=0xc000073750 sp=0xc000073730 pc=0x9cb0896
runtime.gcBgMarkWorker()
	runtime/mgc.go:1235 +0xf1 fp=0xc0000737e0 sp=0xc000073750 pc=0x9c935b1
runtime.goexit()
	runtime/asm_amd64.s:1594 +0x1 fp=0xc0000737e8 sp=0xc0000737e0 pc=0x9cdfee1
created by runtime.gcBgMarkStartWorkers
	runtime/mgc.go:1159 +0x25

goroutine 23 [GC worker (idle)]:
runtime.gopark(0xa9ad720?, 0x1?, 0x61?, 0x97?, 0x0?)
	runtime/proc.go:363 +0xd6 fp=0xc00006f750 sp=0xc00006f730 pc=0x9cb0896
runtime.gcBgMarkWorker()
	runtime/mgc.go:1235 +0xf1 fp=0xc00006f7e0 sp=0xc00006f750 pc=0x9c935b1
runtime.goexit()
	runtime/asm_amd64.s:1594 +0x1 fp=0xc00006f7e8 sp=0xc00006f7e0 pc=0x9cdfee1
created by runtime.gcBgMarkStartWorkers
	runtime/mgc.go:1159 +0x25

goroutine 49 [select, locked to thread]:
runtime.gopark(0xc0004b67a8?, 0x2?, 0x17?, 0xc?, 0xc0004b67a4?)
	runtime/proc.go:363 +0xd6 fp=0xc0004b6620 sp=0xc0004b6600 pc=0x9cb0896
runtime.selectgo(0xc0004b67a8, 0xc0004b67a0, 0x0?, 0x0, 0x0?, 0x1)
	runtime/select.go:328 +0x7bc fp=0xc0004b6760 sp=0xc0004b6620 pc=0x9cc04fc
runtime.ensureSigM.func1()
	runtime/signal_unix.go:991 +0x187 fp=0xc0004b67e0 sp=0xc0004b6760 pc=0x9cc4a27
runtime.goexit()
	runtime/asm_amd64.s:1594 +0x1 fp=0xc0004b67e8 sp=0xc0004b67e0 pc=0x9cdfee1
created by runtime.ensureSigM
	runtime/signal_unix.go:974 +0xbd

goroutine 9 [syscall]:
runtime.sigNoteSleep(0xc000148bb5)
	runtime/os_darwin.go:123 +0x1e fp=0xc00066e7a0 sp=0xc00066e768 pc=0x9caad3e
os/signal.signal_recv()
	runtime/sigqueue.go:149 +0x28 fp=0xc00066e7c0 sp=0xc00066e7a0 pc=0x9cdbf08
os/signal.loop()
	os/signal/signal_unix.go:23 +0x19 fp=0xc00066e7e0 sp=0xc00066e7c0 pc=0x9d69799
runtime.goexit()
	runtime/asm_amd64.s:1594 +0x1 fp=0xc00066e7e8 sp=0xc00066e7e0 pc=0x9cdfee1
created by os/signal.Notify.func1.1
	os/signal/signal.go:151 +0x2a

goroutine 11 [chan receive]:
runtime.gopark(0x7?, 0xc000149240?, 0x5?, 0x0?, 0xc000149245?)
	runtime/proc.go:363 +0xd6 fp=0xc00066f698 sp=0xc00066f678 pc=0x9cb0896
runtime.chanrecv(0xc000670060, 0xc00066f7a0, 0x1)
	runtime/chan.go:583 +0x49b fp=0xc00066f728 sp=0xc00066f698 pc=0x9c7e7fb
runtime.chanrecv2(0xc000149290?, 0x6?)
	runtime/chan.go:447 +0x18 fp=0xc00066f750 sp=0xc00066f728 pc=0x9c7e338
github.com/gopasspw/gopass/internal/queue.(*Queue).run(0xc000518320, {0xa50e728, 0xc0000a31c0})
	github.com/gopasspw/gopass/internal/queue/background.go:85 +0x70 fp=0xc00066f7b8 sp=0xc00066f750 pc=0xa0e9ff0
github.com/gopasspw/gopass/internal/queue.New.func1()
	github.com/gopasspw/gopass/internal/queue/background.go:79 +0x2e fp=0xc00066f7e0 sp=0xc00066f7b8 pc=0xa0e9f4e
runtime.goexit()
	runtime/asm_amd64.s:1594 +0x1 fp=0xc00066f7e8 sp=0xc00066f7e0 pc=0x9cdfee1
created by github.com/gopasspw/gopass/internal/queue.New
	github.com/gopasspw/gopass/internal/queue/background.go:79 +0x10d
```

### What did you expect to happen?

I expected my secret to be shown.

### Step-by-step reproduction instructions (by running `brew` commands)

See command output above - trying to show any secret will provoke the bug.

I've downloaded the pre-build binary of `gopass` from https://github.com/gopasspw/gopass/releases/download/v1.14.10/gopass-1.14.10-darwin-amd64.tar.gz and it works without fail.

**Comment by Bo98** [comment]
Seems like a race condition. Will see if I can reproduce.

**Comment by davidolrik** [comment]
Latest version 1.14.11 doesn't fail.
