### ISSUE TITLE
brew search gcc gives errors

### ISSUE THREAD

**Issue by SunnyRaj** [Homebrew/homebrew-core#1159]
- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?

In OS X EL Capitan 10.11.4

### Bug reports:

```
$ brew search gcc
Error: /usr/local/Library/Taps/jinmel/homebrew-gcc_cross_compilers/x64-elf-gdb.rb:14: syntax error, unexpected tSTRING_BEG, expecting keyword_do or '{' or '('
      system 'make'
              ^
Please report this bug:
    https://git.io/brew-troubleshooting
/usr/local/Library/Homebrew/formulary.rb:21:in `module_eval'
/usr/local/Library/Homebrew/formulary.rb:21:in `load_formula'
/usr/local/Library/Homebrew/formulary.rb:38:in `load_formula_from_path'
/usr/local/Library/Homebrew/formulary.rb:87:in `load_file'
/usr/local/Library/Homebrew/formulary.rb:78:in `klass'
/usr/local/Library/Homebrew/formulary.rb:74:in `get_formula'
/usr/local/Library/Homebrew/formulary.rb:171:in `get_formula'
/usr/local/Library/Homebrew/formulary.rb:211:in `factory'
/usr/local/Library/Homebrew/cmd/search.rb:164:in `block in search_formulae'
/usr/local/Library/Homebrew/cmd/search.rb:162:in `map'
/usr/local/Library/Homebrew/cmd/search.rb:162:in `search_formulae'
/usr/local/Library/Homebrew/cmd/search.rb:56:in `search'
/usr/local/Library/brew.rb:87:in `<main>'
```

**Comment by ilovezfs** [comment]
There's a bug in that formula in the tap. You can run
```
perl -p -i -e "s/--disable-werror',/--disable-werror'/" /usr/local/Library/Taps/jinmel/homebrew-gcc_cross_compilers/x64-elf-gdb.rb
```
to fix the bug and it will go away.

**Comment by SunnyRaj** [comment]
It does fix the issue. Thanks!

**Comment by ilovezfs** [comment]
you're welcome!
