### ISSUE TITLE
error when installing ```navi```

### ISSUE THREAD

**Issue by petersit00** [Homebrew/homebrew-core#116134]
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

```shell
Error: No logs.
```

```
HOMEBREW_VERSION: 3.6.11
ORIGIN: https://github.com/Homebrew/brew
HEAD: b7391069d48805c786b1e9fe88edf795960321dc
Last commit: 5 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 09fd806d21033a82881c23832690906c99a8ea2c
Core tap last commit: 7 minutes ago
Core tap branch: master
HOMEBREW_PREFIX: /home/linuxbrew/.linuxbrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_MAKE_JOBS: 16
Homebrew Ruby: 2.6.8 => /home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.8_1/bin/ruby
CPU: 16-core 64-bit unknown_0x6_0xa5
Clang: N/A
Git: 2.38.1 => /bin/git
Curl: 7.82.0 => /bin/curl
Kernel: Linux 5.15.0-53-generic x86_64 GNU/Linux
OS: Fedora release 36 (Thirty Six)
Host glibc: 2.35
/usr/bin/gcc: 12.0.1
/usr/bin/ruby: N/A
glibc: N/A
gcc@11: N/A
gcc: N/A
xorg: N/A
```

```
Your system is ready to brew.
```
```


### Verification

- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.

### What were you trying to do (and why)?

install navi

### What happened (include all command output)?

==> Installing navi
==> Pouring navi--2.20.1.x86_64_linux.bottle.tar.gz
Error: cannot normalize PT_NOTE segment: non-contiguous SHT_NOTE sections
Please report this issue:
  https://docs.brew.sh/Troubleshooting
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/patchelf-1.4.0/lib/patchelf/alt_saver.rb:682:in `normalize_note_segment'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/patchelf-1.4.0/lib/patchelf/alt_saver.rb:659:in `block in normalize_note_segments'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/patchelf-1.4.0/lib/patchelf/alt_saver.rb:955:in `block in phdrs_by_type'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/patchelf-1.4.0/lib/patchelf/alt_saver.rb:952:in `each'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/patchelf-1.4.0/lib/patchelf/alt_saver.rb:952:in `each_with_index'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/patchelf-1.4.0/lib/patchelf/alt_saver.rb:952:in `phdrs_by_type'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/patchelf-1.4.0/lib/patchelf/alt_saver.rb:653:in `normalize_note_segments'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/patchelf-1.4.0/lib/patchelf/alt_saver.rb:638:in `rewrite_sections_library'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/patchelf-1.4.0/lib/patchelf/alt_saver.rb:475:in `rewrite_sections'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/patchelf-1.4.0/lib/patchelf/alt_saver.rb:88:in `save!'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/patchelf-1.4.0/lib/patchelf/patcher.rb:191:in `save'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/os/linux/elf.rb:167:in `save_using_patchelf_rb'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/os/linux/elf.rb:112:in `patch!'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/extend/os/linux/keg_relocate.rb:53:in `change_rpath'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/extend/os/linux/keg_relocate.rb:15:in `block (2 levels) in relocate_dynamic_linkage'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/extend/pathname.rb:341:in `ensure_writable'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/extend/os/linux/keg_relocate.rb:14:in `block in relocate_dynamic_linkage'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/extend/os/linux/keg_relocate.rb:13:in `each'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/extend/os/linux/keg_relocate.rb:13:in `relocate_dynamic_linkage'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/keg_relocate.rb:132:in `replace_placeholders_with_locations'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/formula_installer.rb:1226:in `pour'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/formula_installer.rb:425:in `install'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/upgrade.rb:203:in `install_formula'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/install.rb:350:in `install_formula'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/install.rb:340:in `block in install_formulae'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/install.rb:339:in `each'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/install.rb:339:in `install_formulae'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/cmd/install.rb:233:in `install'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/brew.rb:95:in `<main>'

### What did you expect to happen?

install navi without error

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
brew install navi
```

**Comment by carlocab** [comment]
Same issue as https://github.com/Homebrew/homebrew-core/issues/115162.

**Comment by Bo98** [comment]
This will be fixed in a few hours.

**Comment by Bo98** [comment]
Fixed.
