### ISSUE TITLE
Error installing tor

### ISSUE THREAD

**Issue by AnastasiaSulyagina** [Homebrew/homebrew-core#11852]
When installing tor get an error: 
```
Error: Calling ENV.j1 is deprecated!
Use ENV.deparallelize instead.
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/libevent.rb:52:in `install'
Please report this to the homebrew/core tap!
```
MacOS : 10.12.3

Full stacktrace:
```
$ brew install tor
Updating Homebrew...
==> Auto-updated Homebrew!
Updated Homebrew from f8cf506 to 0882e9d.
Updated 2 taps (homebrew/science, homebrew/versions).
==> New Formulae
homebrew/science/oma                                                                   homebrew/science/tamarin-prover
==> Updated Formulae
homebrew/science/alembic           homebrew/science/fplll             homebrew/science/mantaflow         homebrew/science/pandaseq          homebrew/science/sollya
homebrew/science/armadillo         homebrew/science/freebayes         homebrew/science/nextflow          homebrew/science/phyx              homebrew/science/stringtie
homebrew/science/bbtools           homebrew/science/iqtree            homebrew/science/nexusformat       homebrew/science/rapsearch2        homebrew/science/swarm
homebrew/science/breseq            homebrew/science/libbigwig         homebrew/science/opencollada       homebrew/science/seqan             homebrew/science/vcfanno
==> Renamed Formulae
homebrew/science/hdf@4 -> homebrew/science/hdf4

==> Installing dependencies for tor: pkg-config, sphinx-doc, cmake, doxygen, makedepend, libevent
==> Installing tor dependency: pkg-config
==> Using the sandbox
==> Downloading https://pkgconfig.freedesktop.org/releases/pkg-config-0.29.1.tar.gz
######################################################################## 100,0%
==> ./configure --prefix=/usr/local/Cellar/pkg-config/0.29.1_1 --disable-host-tool --with-internal-glib --with-pc-path=/usr/local/lib/pkgconfig:/usr/local/share/pkgconfig:/u
==> make
==> make check
==> make install
🍺  /usr/local/Cellar/pkg-config/0.29.1_1: 11 files, 628.8KB, built in 13 minutes 58 seconds
==> Installing tor dependency: sphinx-doc
==> Downloading https://files.pythonhosted.org/packages/8b/78/eeea2b837f911cdc301f5f05163f9729a2381cad
######################################################################## 100,0%
==> Downloading https://pypi.python.org/packages/46/01/3539c406b47b0e44464a2b6c7b51871300d815b9d7b07c9
######################################################################## 100,0%
==> python -c import setuptools... --no-user-cfg install --prefix=/usr/local/Cellar/sphinx-doc/1.4.5/l
==> Downloading https://pypi.python.org/packages/6e/96/ba2a2462ed25ca0e651fb7b66e7080f5315f91425a07ea5
######################################################################## 100,0%
==> python -c import setuptools... --no-user-cfg install --prefix=/usr/local/Cellar/sphinx-doc/1.4.5/l
==> Downloading https://pypi.python.org/packages/source/d/docutils/docutils-0.12.tar.gz
######################################################################## 100,0%
==> python -c import setuptools... --no-user-cfg install --prefix=/usr/local/Cellar/sphinx-doc/1.4.5/l
==> Downloading https://pypi.python.org/packages/53/72/6c6f1e787d9cab2cc733cf042f125abec07209a58308831
######################################################################## 100,0%
==> python -c import setuptools... --no-user-cfg install --prefix=/usr/local/Cellar/sphinx-doc/1.4.5/l
==> Downloading https://pypi.python.org/packages/source/J/Jinja2/Jinja2-2.8.tar.gz
######################################################################## 100,0%
==> python -c import setuptools... --no-user-cfg install --prefix=/usr/local/Cellar/sphinx-doc/1.4.5/l
==> Downloading https://pypi.python.org/packages/source/M/MarkupSafe/MarkupSafe-0.23.tar.gz
######################################################################## 100,0%
==> python -c import setuptools... --no-user-cfg install --prefix=/usr/local/Cellar/sphinx-doc/1.4.5/l
==> Downloading https://pypi.python.org/packages/source/P/Pygments/Pygments-2.1.3.tar.gz
######################################################################## 100,0%
==> python -c import setuptools... --no-user-cfg install --prefix=/usr/local/Cellar/sphinx-doc/1.4.5/l
==> Downloading https://files.pythonhosted.org/packages/f7/c7/08e54702c74baf9d8f92d0bc331ecabf6d66a56f
######################################################################## 100,0%
==> python -c import setuptools... --no-user-cfg install --prefix=/usr/local/Cellar/sphinx-doc/1.4.5/l
==> Downloading https://pypi.python.org/packages/source/s/six/six-1.10.0.tar.gz
######################################################################## 100,0%
==> python -c import setuptools... --no-user-cfg install --prefix=/usr/local/Cellar/sphinx-doc/1.4.5/l
==> Downloading https://pypi.python.org/packages/source/s/snowballstemmer/snowballstemmer-1.2.1.tar.gz
######################################################################## 100,0%
==> python -c import setuptools... --no-user-cfg install --prefix=/usr/local/Cellar/sphinx-doc/1.4.5/l
==> python -c import setuptools... --no-user-cfg install --prefix=/usr/local/Cellar/sphinx-doc/1.4.5/l
==> Caveats
This formula is keg-only, which means it was not symlinked into /usr/local.

This formula is mainly used internally by other formulae.
Users are advised to use `pip` to install sphinx-doc.

If you need to have this software first in your PATH run:
  echo 'export PATH="/usr/local/opt/sphinx-doc/bin:$PATH"' >> ~/.bash_profile

==> Summary
🍺  /usr/local/Cellar/sphinx-doc/1.4.5: 2,758 files, 39.2MB, built in 49 seconds
==> Installing tor dependency: cmake
==> Downloading https://cmake.org/files/v3.6/cmake-3.6.1.tar.gz
######################################################################## 100,0%
==> ./bootstrap --prefix=/usr/local/Cellar/cmake/3.6.1 --no-system-libs --parallel=4 --datadir=/share/
==> make
==> make install
==> Caveats
Emacs Lisp files have been installed to:
  /usr/local/share/emacs/site-lisp/cmake
==> Summary
🍺  /usr/local/Cellar/cmake/3.6.1: 2,029 files, 27.7MB, built in 7 minutes 19 seconds
==> Installing tor dependency: doxygen
==> Downloading https://ftp.stack.nl/pub/users/dimitri/doxygen-1.8.11.src.tar.gz
######################################################################## 100,0%
==> cmake .. -DCMAKE_C_FLAGS_RELEASE=-DNDEBUG -DCMAKE_CXX_FLAGS_RELEASE=-DNDEBUG -DCMAKE_INSTALL_PREFI
==> make
🍺  /usr/local/Cellar/doxygen/1.8.11: 9 files, 13MB, built in 1 minute 38 seconds
==> Installing tor dependency: makedepend
==> Downloading https://xorg.freedesktop.org/releases/individual/util/makedepend-1.0.5.tar.bz2
######################################################################## 100,0%
==> Downloading https://xorg.freedesktop.org/releases/individual/proto/xproto-7.0.28.tar.gz
######################################################################## 100,0%
==> ./configure --disable-silent-rules --prefix=/private/tmp/makedepend-20170330-39872-1ml2udq/makedep
==> make install
==> Downloading https://xorg.freedesktop.org/releases/individual/util/util-macros-1.19.0.tar.bz2
######################################################################## 100,0%
==> ./configure --prefix=/private/tmp/makedepend-20170330-39872-1ml2udq/makedepend-1.0.5/xorg-macros
==> make install
==> ./configure --disable-silent-rules --prefix=/usr/local/Cellar/makedepend/1.0.5
==> make install
🍺  /usr/local/Cellar/makedepend/1.0.5: 8 files, 74.5KB, built in 49 seconds
==> Installing tor dependency: libevent
==> Downloading https://github.com/libevent/libevent/releases/download/release-2.0.22-stable/libevent-
==> Downloading from https://github-cloud.s3.amazonaws.com/releases/1856976/b8683cb6-0519-11e5-817f-05
######################################################################## 100,0%
==> Downloading https://github.com/libevent/libevent/commit/df6f99e5b51a3.patch
######################################################################## 100,0%
==> Patching
==> Applying df6f99e5b51a3.patch
patching file kqueue.c
Hunk #1 succeeded at 150 (offset -4 lines).
Error: Calling ENV.j1 is deprecated!
Use ENV.deparallelize instead.
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/libevent.rb:52:in `install'
Please report this to the homebrew/core tap!
```

**Comment by MikeMcQuaid** [comment]
@AnastasiaSulyagina 👋 Can we see your `brew config` and `brew doctor` output?

**Comment by AnastasiaSulyagina** [comment]
Actually have no idea about numpy, it works but there's always this error
```
$ brew doctor
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry and just ignore them. Thanks!

Warning: Suspicious homebrew/core git origin remote found.

With a non-standard origin, Homebrew won't pull updates from
the main repository. The current git origin is:
  https://github.com/AnastasiaSulyagina/homebrew-core.git

Unless you have compelling reasons, consider setting the
origin remote to point at the main repository by running:
  git -C "/usr/local/Homebrew/Library/Taps/homebrew/homebrew-core" remote add origin https://github.com/Homebrew/homebrew-core.git

Warning: Anaconda is known to frequently break Homebrew builds, including Vim and
MacVim, due to bundling many duplicates of system and Homebrew-available
tools.

If you encounter a build failure please temporarily remove Anaconda
from your $PATH and attempt the build again prior to reporting the
failure to us. Thanks!

Warning: python is symlinked to python3
This will confuse build scripts and in general lead to subtle breakage.

Warning: "config" scripts exist outside your system or Homebrew directories.
`./configure` scripts often look for *-config scripts to determine if
software packages are installed, and what additional flags to use when
compiling and linking.

Having additional scripts in your path can confuse software installed via
Homebrew if the config script overrides a system or Homebrew provided
script of the same name. We found the following "config" scripts:
  /Users/anastasia/Development/TOOLS/anaconda3/bin/curl-config
  /Users/anastasia/Development/TOOLS/anaconda3/bin/freetype-config
  /Users/anastasia/Development/TOOLS/anaconda3/bin/libdynd-config
  /Users/anastasia/Development/TOOLS/anaconda3/bin/libpng-config
  /Users/anastasia/Development/TOOLS/anaconda3/bin/libpng16-config
  /Users/anastasia/Development/TOOLS/anaconda3/bin/python3-config
  /Users/anastasia/Development/TOOLS/anaconda3/bin/python3.5-config
  /Users/anastasia/Development/TOOLS/anaconda3/bin/python3.5m-config
  /Users/anastasia/Development/TOOLS/anaconda3/bin/xml2-config
  /Users/anastasia/Development/TOOLS/anaconda3/bin/xslt-config

Warning: Python is installed at /Library/Frameworks/Python.framework

Homebrew only supports building against the System-provided Python or a
brewed Python. In particular, Pythons installed to /Library can interfere
with other software installs.

Warning: Unbrewed dylibs were found in /usr/local/lib.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected dylibs:
  /usr/local/lib/libopencv_calib3d.3.0.0.dylib
  /usr/local/lib/libopencv_core.3.0.0.dylib
  /usr/local/lib/libopencv_features2d.3.0.0.dylib
  /usr/local/lib/libopencv_flann.3.0.0.dylib
  /usr/local/lib/libopencv_highgui.3.0.0.dylib
  /usr/local/lib/libopencv_imgcodecs.3.0.0.dylib
  /usr/local/lib/libopencv_imgproc.3.0.0.dylib
  /usr/local/lib/libopencv_ml.3.0.0.dylib
  /usr/local/lib/libopencv_objdetect.3.0.0.dylib
  /usr/local/lib/libopencv_photo.3.0.0.dylib
  /usr/local/lib/libopencv_shape.3.0.0.dylib
  /usr/local/lib/libopencv_stitching.3.0.0.dylib
  /usr/local/lib/libopencv_superres.3.0.0.dylib
  /usr/local/lib/libopencv_video.3.0.0.dylib
  /usr/local/lib/libopencv_videoio.3.0.0.dylib
  /usr/local/lib/libopencv_videostab.3.0.0.dylib
  /usr/local/lib/libtcl8.6.dylib
  /usr/local/lib/libtk8.6.dylib

Warning: Unbrewed header files were found in /usr/local/include.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected header files:
  /usr/local/include/fakemysql.h
  /usr/local/include/fakepq.h
  /usr/local/include/fakesql.h
  /usr/local/include/itcl.h
  /usr/local/include/itcl2TclOO.h
  /usr/local/include/itclDecls.h
  /usr/local/include/itclInt.h
  /usr/local/include/itclIntDecls.h
  /usr/local/include/itclMigrate2TclCore.h
  /usr/local/include/itclTclIntStubsFcn.h
  /usr/local/include/mysqlStubs.h
  /usr/local/include/odbcStubs.h
  /usr/local/include/opencv2/calib3d/calib3d_c.h
  /usr/local/include/opencv2/core/cvdef.h
  /usr/local/include/opencv2/cvconfig.h
  /usr/local/include/opencv2/hal/defs.h
  /usr/local/include/opencv2/imgcodecs/imgcodecs_c.h
  /usr/local/include/opencv2/imgcodecs/ios.h
  /usr/local/include/opencv2/objdetect/objdetect_c.h
  /usr/local/include/opencv2/video/tracking_c.h
  /usr/local/include/opencv2/videoio/cap_ios.h
  /usr/local/include/opencv2/videoio/videoio_c.h
  /usr/local/include/pqStubs.h
  /usr/local/include/tcl.h
  /usr/local/include/tclDecls.h
  /usr/local/include/tclOO.h
  /usr/local/include/tclOODecls.h
  /usr/local/include/tclPlatDecls.h
  /usr/local/include/tclThread.h
  /usr/local/include/tclTomMath.h
  /usr/local/include/tclTomMathDecls.h
  /usr/local/include/tdbc.h
  /usr/local/include/tdbcDecls.h
  /usr/local/include/tdbcInt.h
  /usr/local/include/tk.h
  /usr/local/include/tkDecls.h
  /usr/local/include/tkPlatDecls.h

Warning: Unbrewed .pc files were found in /usr/local/lib/pkgconfig.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected .pc files:
  /usr/local/lib/pkgconfig/tcl.pc
  /usr/local/lib/pkgconfig/tk.pc

Warning: Unbrewed static libraries were found in /usr/local/lib.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected static libraries:
  /usr/local/lib/libopencv_calib3d.a
  /usr/local/lib/libopencv_core.a
  /usr/local/lib/libopencv_features2d.a
  /usr/local/lib/libopencv_flann.a
  /usr/local/lib/libopencv_hal.a
  /usr/local/lib/libopencv_highgui.a
  /usr/local/lib/libopencv_imgcodecs.a
  /usr/local/lib/libopencv_imgproc.a
  /usr/local/lib/libopencv_ml.a
  /usr/local/lib/libopencv_objdetect.a
  /usr/local/lib/libopencv_photo.a
  /usr/local/lib/libopencv_shape.a
  /usr/local/lib/libopencv_stitching.a
  /usr/local/lib/libopencv_superres.a
  /usr/local/lib/libopencv_video.a
  /usr/local/lib/libopencv_videoio.a
  /usr/local/lib/libopencv_videostab.a
  /usr/local/lib/libtclstub8.6.a
  /usr/local/lib/libtkstub8.6.a

Warning: You have unlinked kegs in your Cellar
Leaving kegs unlinked can lead to build-trouble and cause brews that depend on
those kegs to fail to run properly once built. Run `brew link` on these:
  numpy

Warning: Some directories in your path end in a slash.
Directories in your path should not end in a slash. This can break other
doctor checks. The following directories should be edited:
  /usr/local/bin/

Warning: Homebrew's sbin was not found in your PATH but you have installed
formulae that put executables in /usr/local/sbin.
Consider setting the PATH for example like so
  echo 'export PATH="/usr/local/sbin:$PATH"' >> ~/.bash_profile
Error: No available formula with the name "numpy" 
```

```
HOMEBREW_VERSION: 1.1.11-185-g0882e9d
ORIGIN: https://github.com/Homebrew/brew.git
HEAD: 0882e9ddbc2b4507038d87e21233ce29031b995b
Last commit: 4 hours ago
Core tap ORIGIN: https://github.com/AnastasiaSulyagina/homebrew-core.git
Core tap HEAD: cbc0c951c95455c0f1872a890b5196d50341a3a2
Core tap last commit: 7 months ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_REPOSITORY: /usr/local/Homebrew
HOMEBREW_CELLAR: /usr/local/Cellar
HOMEBREW_BOTTLE_DOMAIN: https://homebrew.bintray.com
CPU: quad-core 64-bit broadwell
Homebrew Ruby: 2.0.0-p648
Clang: 8.0 build 800
Git: 2.9.3 => /usr/local/bin/git
Perl: /usr/bin/perl
Python: /Users/anastasia/Development/TOOLS/anaconda3/bin/python => /Users/anastasia/Development/TOOLS/anaconda3/bin/python3.5
Ruby: /usr/local/bin/ruby => /usr/local/Cellar/ruby/2.3.0/bin/ruby
Java: 1.8.0_74, 1.8.0_45
macOS: 10.12.3-x86_64
Xcode: 8.2.1
CLT: N/A
X11: 2.7.9 => /opt/X11
```

**Comment by MikeMcQuaid** [comment]
> Warning: Suspicious homebrew/core git origin remote found.
> 
> With a non-standard origin, Homebrew won't pull updates from
> the main repository. The current git origin is:
>   https://github.com/AnastasiaSulyagina/homebrew-core.git
> 
> Unless you have compelling reasons, consider setting the
> origin remote to point at the main repository by running:
>   git -C "/usr/local/Homebrew/Library/Taps/homebrew/homebrew-core" remote add origin http

@AnastasiaSulyagina That's your issue!

**Comment by AnastasiaSulyagina** [comment]
Oh thanks! I did it with brew rep and forgot about core
