### ISSUE TITLE
git-remote-codecommit v1.16 installed using brew uses botocore v1.29.3 which doesn't recognize the new ~/.aws/config file formats created by AWS CLI v2.9.x

### ISSUE THREAD

**Issue by palaniswamy** [Homebrew/homebrew-core#118711]
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

```shell
==> git-remote-codecommit: stable 1.16 (bottled), HEAD
Git Remote Helper to interact with AWS CodeCommit
https://github.com/aws/git-remote-codecommit
/opt/homebrew/Cellar/git-remote-codecommit/1.16 (2,728 files, 89MB) *
  Poured from bottle on 2022-12-09 at 16:16:21
From: https://github.com/Homebrew/homebrew-core/blob/HEAD/Formula/git-remote-codecommit.rb
License: Apache-2.0
==> Dependencies
Required: python@3.11 ✔, six ✔
==> Options
--HEAD
	Install HEAD version
==> Analytics
install: 299 (30 days), 1,008 (90 days), 3,428 (365 days)
install-on-request: 299 (30 days), 1,008 (90 days), 3,430 (365 days)
build-error: 0 (30 days)
```

### Verification

- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.

### What were you trying to do (and why)?

I am trying to use AWS CLI v2.9.x to login to AWS SSO by using "aws configure sso" command which prepare the AWS Config file (~/.aws/config) in a certain format that supports AWS SSO session. 

### What happened (include all command output)?

The git-remote-codecommit comes with botocore v1.29.3 which doesn't support the new format of AWS Config file.

### What did you expect to happen?

The git-remote-codecommit is packaged with later version of botocore so that it works with new format of AWS Config file (~/.aws/config).

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
brew install git-remote-codecommit
brew install awscli
aws configure sso
# And provide answers to prompts from aws command to configure AWS Config file.
git clone codecommit://MyDemoRepo my-demo-repo


Errors:
Cloning into ''...
Traceback (most recent call last):
File "/opt/homebrew/bin/git-remote-codecommit", line 33, in 
sys.exit(load_entry_point('git-remote-codecommit==1.16', 'console_scripts', 'git-remote-codecommit')())
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/opt/homebrew/Cellar/git-remote-codecommit/1.16/libexec/lib/python3.11/site-packages/git_remote_codecommit/init.py", line 176, in main
context = Context.from_url(remote_url)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/opt/homebrew/Cellar/git-remote-codecommit/1.16/libexec/lib/python3.11/site-packages/git_remote_codecommit/init.py", line 148, in from_url
credentials = session.get_credentials()
^^^^^^^^^^^^^^^^^^^^^^^^^
File "/opt/homebrew/Cellar/git-remote-codecommit/1.16/libexec/lib/python3.11/site-packages/botocore/session.py", line 509, in get_credentials
).load_credentials()
^^^^^^^^^^^^^^^^^^
File "/opt/homebrew/Cellar/git-remote-codecommit/1.16/libexec/lib/python3.11/site-packages/botocore/credentials.py", line 2095, in load_credentials
creds = provider.load()
^^^^^^^^^^^^^^^
File "/opt/homebrew/Cellar/git-remote-codecommit/1.16/libexec/lib/python3.11/site-packages/botocore/credentials.py", line 2249, in load
sso_config = self._load_sso_config()
^^^^^^^^^^^^^^^^^^^^^^^
File "/opt/homebrew/Cellar/git-remote-codecommit/1.16/libexec/lib/python3.11/site-packages/botocore/credentials.py", line 2239, in _load_sso_config
raise InvalidConfigError(
botocore.exceptions.InvalidConfigError: The profile "" is configured to use SSO but is missing required configuration: sso_start_url, sso_region
```

**Comment by SMillerDev** [comment]
So.. we're waiting for a release that adds support for this to `git-remote-codecommit`then?

**Comment by bayandin** [comment]
> The git-remote-codecommit comes with botocore v1.29.3 which doesn't support the new format of AWS Config file.

Does `botocore` 1.29.36 support it? If so `brew update-python-resources git-remote-codecommit` and create a PR

**Comment by palaniswamy** [comment]
Yes the botocore v1.29.10 or later support it. Thanks for the tip about "brew update-python-resources". I have created the PR https://github.com/Homebrew/homebrew-core/pull/118815
