### ISSUE TITLE
brew test boost-python

### ISSUE THREAD

**Issue by parsibox** [Homebrew/homebrew-core#12147]
hi
`brew test boost-python`
say : 
```
/home/parsibox/.linuxbrew/bin/ld: /tmp/cccv3yGc.o: relocation R_X86_64_32 against `.rodata' can not be used when making a shared object; recompile with -fPIC
/home/parsibox/.linuxbrew/bin/ld: final link failed: Nonrepresentable section on output
collect2: error: ld returned 1 exit status
Error: boost-python: failed
```

```
[parsibox@localhost 46407a070844f764dec6f27bde385797]$ brew test boost-python
Testing boost-python
==> /home/parsibox/.linuxbrew/bin/g++-5 -shared hello.cpp -L/home/parsibox/.linuxbrew/Cellar/boost-python/1.63.0/lib -lboost_python -o hello.so -I/home/parsibox/.linuxbrew/Cellar/python/2.7.13/include/python2.7 -I/home/parsibox/.linuxbre
Last 15 lines from /home/parsibox/.cache/Homebrew/Logs/boost-python/test.01.g++-5:
-o
hello.so
-I/home/parsibox/.linuxbrew/Cellar/python/2.7.13/include/python2.7
-I/home/parsibox/.linuxbrew/Cellar/python/2.7.13/include/python2.7
-lpython2.7
-lpthread
-ldl
-lutil
-lm
-Xlinker
-export-dynamic

/home/parsibox/.linuxbrew/bin/ld: /tmp/cccv3yGc.o: relocation R_X86_64_32 against `.rodata' can not be used when making a shared object; recompile with -fPIC
/home/parsibox/.linuxbrew/bin/ld: final link failed: Nonrepresentable section on output
collect2: error: ld returned 1 exit status
Error: boost-python: failed
Failed executing: /home/parsibox/.linuxbrew/bin/g++-5 -shared hello.cpp -L/home/parsibox/.linuxbrew/Cellar/boost-python/1.63.0/lib -lboost_python -o hello.so -I/home/parsibox/.linuxbrew/Cellar/python/2.7.13/include/python2.7 -I/home/parsibox/.linuxbrew/Cellar/python/2.7.13/include/python2.7 -lpython2.7 -lpthread -ldl -lutil -lm -Xlinker -export-dynamic
/home/parsibox/.linuxbrew/Library/Homebrew/formula.rb:1836:in `block in system'
/home/parsibox/.linuxbrew/Library/Homebrew/formula.rb:1774:in `open'
/home/parsibox/.linuxbrew/Library/Homebrew/formula.rb:1774:in `system'
/home/parsibox/.linuxbrew/Library/Taps/homebrew/homebrew-core/Formula/boost-python.rb:93:in `block (2 levels) in <class:BoostPython>'
/home/parsibox/.linuxbrew/Library/Homebrew/language/python.rb:26:in `call'
/home/parsibox/.linuxbrew/Library/Homebrew/language/python.rb:26:in `block in each_python'
/home/parsibox/.linuxbrew/Library/Homebrew/language/python.rb:18:in `each'
/home/parsibox/.linuxbrew/Library/Homebrew/language/python.rb:18:in `each_python'
/home/parsibox/.linuxbrew/Library/Taps/homebrew/homebrew-core/Formula/boost-python.rb:90:in `block in <class:BoostPython>'
/home/parsibox/.linuxbrew/Library/Homebrew/formula.rb:1673:in `block (2 levels) in run_test'
/home/parsibox/.linuxbrew/Library/Homebrew/formula.rb:884:in `with_logging'
/home/parsibox/.linuxbrew/Library/Homebrew/formula.rb:1672:in `block in run_test'
/home/parsibox/.linuxbrew/Library/Homebrew/extend/fileutils.rb:14:in `block in mktemp'
/home/parsibox/.linuxbrew/Library/Homebrew/extend/fileutils.rb:74:in `block in run'
/home/parsibox/.linuxbrew/Library/Homebrew/extend/fileutils.rb:74:in `chdir'
/home/parsibox/.linuxbrew/Library/Homebrew/extend/fileutils.rb:74:in `run'
/home/parsibox/.linuxbrew/Library/Homebrew/extend/fileutils.rb:13:in `mktemp'
/home/parsibox/.linuxbrew/Library/Homebrew/formula.rb:1666:in `run_test'
/home/parsibox/.linuxbrew/Library/Homebrew/test.rb:33:in `block in <main>'
/home/parsibox/.linuxbrew/Library/Homebrew/vendor/portable-ruby/2.0.0-p648/lib/ruby/2.0.0/timeout.rb:66:in `timeout'
/home/parsibox/.linuxbrew/Library/Homebrew/test.rb:32:in `<main>'

```

**Comment by ilovezfs** [comment]
Please report Linuxbrew issues to https://github.com/Linuxbrew/homebrew-core/issues/new
