### ISSUE TITLE
SBT build from source error: undefined method `user' for nil:NilClass

### ISSUE THREAD

**Issue by erik-bershel** [Homebrew/homebrew-core#123415]
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

```shell
~ % brew doctor
==> Downloading https://formulae.brew.sh/api/formula.json
######################################################################## 100.0%
Your system is ready to brew.
```
-
```
~ % brew config
HOMEBREW_VERSION: 4.0.1
ORIGIN: https://github.com/Homebrew/brew
HEAD: 17c872fb5275d87922a56416587cb439a5064354
Last commit: 4 hours ago
Core tap origin: https://github.com/Homebrew/homebrew-core
Core tap HEAD: db25ff891d07186085be417e472cdde13881d2c7
Core tap last commit: 74 minutes ago
Core tap branch: master
Core tap JSON: 16 Feb 16:57 UTC
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_MAKE_JOBS: 8
Homebrew Ruby: 2.6.10 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: octa-core 64-bit arm_blizzard_avalanche
Clang: 14.0.0 build 1400
Git: 2.39.0 => /opt/homebrew/bin/git
Curl: 7.86.0 => /usr/bin/curl
macOS: 13.2-arm64
CLT: 14.2.0.0.1.1668646533
Xcode: N/A
Rosetta 2: false
```

### Verification

- [X] My "`brew doctor` output" says `Your system is ready to brew.` and am still able to reproduce my issue.
- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.

### What were you trying to do (and why)?

Trying to install sbt from scraps via brew with command: 
```
brew install --build-from-source sbt
```

### What happened (include all command output)?

```
==> Fetching sbt
######################################################################## 100.0%
==> Downloading https://github.com/sbt/sbt/releases/download/v1.8.2/sbt-1.8.2.tg
==> Downloading from https://objects.githubusercontent.com/github-production-rel
######################################################################## 100.0%
Error: undefined method `user' for nil:NilClass
Please report this issue:
  https://docs.brew.sh/Troubleshooting
/Users/ebershel/Library/Caches/Homebrew/Formula/sbt.rb:42:in `caveats'
/opt/homebrew/Library/Homebrew/caveats.rb:23:in `caveats'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/forwardable.rb:224:in `empty?'
/opt/homebrew/Library/Homebrew/formula_installer.rb:763:in `caveats'
/opt/homebrew/Library/Homebrew/formula_installer.rb:826:in `finish'
/opt/homebrew/Library/Homebrew/upgrade.rb:204:in `install_formula'
/opt/homebrew/Library/Homebrew/install.rb:350:in `install_formula'
/opt/homebrew/Library/Homebrew/install.rb:340:in `block in install_formulae'
/opt/homebrew/Library/Homebrew/install.rb:339:in `each'
/opt/homebrew/Library/Homebrew/install.rb:339:in `install_formulae'
/opt/homebrew/Library/Homebrew/cmd/install.rb:226:in `install'
/opt/homebrew/Library/Homebrew/brew.rb:93:in `<main>'
```

### What did you expect to happen?

sbt installed

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
brew install --build-from-source sbt
```

**Comment by carlocab** [comment]
You need to
```sh
export HOMEBREW_NO_INSTALL_FROM_API=1
```
in order to build from source.
