### ISSUE TITLE
GDAL formula no longer imports when used in Python venv, now shows "symbol not found in flat namespace (_CPLAddXMLChild)" error

### ISSUE THREAD

**Issue by migurski** [Homebrew/homebrew-core#124356]
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

```shell
HOMEBREW_VERSION: 4.0.4-12-g810c768
ORIGIN: https://github.com/Homebrew/brew
HEAD: 810c7681f9f59c33d2fd7e2b85fc6b28ec9deba7
Last commit: 2 hours ago
Core tap origin: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 2f66a74ab329e3f12d2978eb263dfad96b304140
Core tap last commit: 2 weeks ago
Core tap branch: master
Core tap JSON: 27 Feb 19:31 UTC
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_MAKE_JOBS: 8
Homebrew Ruby: 2.6.10 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: octa-core 64-bit arm_firestorm_icestorm
Clang: 14.0.0 build 1400
Git: 2.37.1 => /Library/Developer/CommandLineTools/usr/bin/git
Curl: 7.79.1 => /usr/bin/curl
macOS: 12.6.3-arm64
CLT: 14.2.0.0.1.1668646533
Xcode: N/A
Rosetta 2: false
```

### Verification

- [X] My "`brew doctor` output" says `Your system is ready to brew.` and am still able to reproduce my issue.
- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.

### What were you trying to do (and why)?

Install `gdal` along with Python bindings, then depend on GDAL as a Python package in a virtualenv.

Our team has been using this pattern with Homebrew successfully over the past year but today it no longer works.

### What happened (include all command output)?

* Install of `gdal` and Python 3 was successful
* Brew-level import works: ```/opt/homebrew/bin/python3 -c 'import osgeo.ogr'```
* Now, create a virtualenv and install GDAL:
    ```
    /opt/homebrew/bin/python3 -m venv .venv
    source .venv/bin/activate
    pip3 install -U pip
    pip3 install GDAL==3.6.2 --global-option=build_ext --global-option="-I/opt/homebrew/include" --global-option="-L/opt/homebrew/lib"
    python3 -c 'import osgeo.ogr'
    ```

#### Output of last two steps:

```
Collecting GDAL==3.6.2
  Using cached GDAL-3.6.2.tar.gz (757 kB)
  Preparing metadata (setup.py) ... done
Installing collected packages: GDAL
  Running setup.py install for GDAL ... done
Successfully installed GDAL-3.6.2
```

```
Traceback (most recent call last):
  File "/Users/migurski/Documents/felt/services/pipeline/.venv/lib/python3.11/site-packages/osgeo/__init__.py", line 30, in swig_import_helper
    return importlib.import_module(mname)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.2_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1206, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1149, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 676, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 573, in module_from_spec
  File "<frozen importlib._bootstrap_external>", line 1233, in create_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
ImportError: dlopen(/Users/migurski/Documents/felt/services/pipeline/.venv/lib/python3.11/site-packages/osgeo/_gdal.cpython-311-darwin.so, 0x0002): symbol not found in flat namespace (_CPLAddXMLChild)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/migurski/Documents/felt/services/pipeline/.venv/lib/python3.11/site-packages/osgeo/__init__.py", line 46, in <module>
    _gdal = swig_import_helper()
            ^^^^^^^^^^^^^^^^^^^^
  File "/Users/migurski/Documents/felt/services/pipeline/.venv/lib/python3.11/site-packages/osgeo/__init__.py", line 43, in swig_import_helper
    return importlib.import_module('_gdal')
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.2_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ModuleNotFoundError: No module named '_gdal'
```

### What did you expect to happen?

Importing the GDAL package with `import osgeo.ogr` should have worked.

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
brew install gdal
brew install python@3.11
```

Then, follow the commands above in "what happened".
```

**Comment by carlocab** [comment]
Does it work with a non-Homebrew Python 3.11?

**Comment by carlocab** [comment]
I think I know what the problem is. Can you provide the output of
```
pyext=/Users/migurski/Documents/felt/services/pipeline/.venv/lib/python3.11/site-packages/osgeo/_gdal.cpython-311-darwin.so
otool -L "$pyext"
otool -l "$pyext" | grep -A2 LC_RPATH
```
?
