### ISSUE TITLE
Can't install mdcat - Error: Missing 'annotations' section.

### ISSUE THREAD

**Issue by eshack94** [Homebrew/homebrew-core#124368]
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

**brew config output:**
```shell
eshackelford@MacBook-Pro eshack94 $ brew config
HOMEBREW_VERSION: 4.0.4
ORIGIN: https://github.com/Homebrew/brew
HEAD: 4d0154fa7926e8a7b06e9b074dd45957e820407c
Last commit: 11 hours ago
Core tap origin: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 662d1bc97c8dca79f995447cf26a0e510b5da5dc
Core tap last commit: 11 days ago
Core tap branch: master
Core tap JSON: 28 Feb 00:06 UTC
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_DISPLAY: /private/tmp/com.apple.launchd.PLo7Id8uRg/org.xquartz:0
HOMEBREW_EDITOR: vi
HOMEBREW_GITHUB_API_TOKEN: set
HOMEBREW_MAKE_JOBS: 10
Homebrew Ruby: 2.6.10 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: 10-core 64-bit arm_firestorm_icestorm
Clang: 14.0.0 build 1400
Git: 2.39.2 => /opt/homebrew/bin/git
Curl: 7.86.0 => /usr/bin/curl
macOS: 13.2.1-arm64
CLT: 14.2.0.0.1.1668646533
Xcode: 14.2
Rosetta 2: false
```

**brew doctor output (some warnings, but all these appear unrelated):**
```shell
eshackelford@MacBook-Pro eshack94 $ brew doctor
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: Some installed formulae are deprecated or disabled.
You should find replacements for the following formulae:
  ccextractor
  delta
  govendor
  ilmbase
  jsonschema
  kubernetes-cli@1.22
  kubernetes-service-catalog-client
  kubeval
  libglade
  lua@5.1
  perl@5.18

Warning: Unbrewed dylibs were found in /usr/local/lib.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected dylibs:
  /usr/local/lib/Spyder.dylib
  /usr/local/lib/Spyder3.dylib
  /usr/local/lib/Spyder5.dylib
  /usr/local/lib/dccmtr.dylib
  /usr/local/lib/dcxmtr.dylib
  /usr/local/lib/libCIEHandler.dylib
  /usr/local/lib/libCalibrationHandler.dylib
  /usr/local/lib/libDeviceManager.dylib
  /usr/local/lib/libErrorHandler.dylib
  /usr/local/lib/libICMManager.dylib
  /usr/local/lib/libMCCAppManager.dylib
  /usr/local/lib/libMCCEngineWrapper.dylib
  /usr/local/lib/libMonitorDDCCISDK.dylib
  /usr/local/lib/libProtocolEngine.dylib
  /usr/local/lib/libmkusb.dylib
  /usr/local/lib/libusb-1.0.0.dylib

Warning: Unbrewed header files were found in /usr/local/include.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected header files:
  /usr/local/include/python2.7/greenlet/greenlet.h

Warning: Unbrewed '.la' files were found in /usr/local/lib.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected '.la' files:
  /usr/local/lib/libclamav.la
  /usr/local/lib/libclammspack.la
  /usr/local/lib/libclamunrar.la
  /usr/local/lib/libclamunrar_iface.la
  /usr/local/lib/libfreshclam.la

Warning: You have unlinked kegs in your Cellar.
Leaving kegs unlinked can lead to build-trouble and cause formulae that depend on
those kegs to fail to run properly once built. Run `brew link` on these:
  coreutils
  docker
  html2text
  docker-completion
  handbrake
  remake
  md5sha1sum
  python@3.11
  wireshark
```

### Verification

- [X] My "`brew doctor` output" says `Your system is ready to brew.` and am still able to reproduce my issue.
- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.

### What were you trying to do (and why)?

Trying to update existing homebrew packages via the following command sequence:

```bash
brew update
brew upgrade
```

### What happened (include all command output)?

It appears that this `Error: Missing 'annotations' section.` issue with `mdcat` is causing subsequent upgrades to be aborted as well.

Output:

```bash
🚀 eshackelford@MacBook-Pro eshack94 $ brew update
Updated 1 tap (homebrew/cask-fonts).
==> Outdated Formulae
k6                     kubeconform            libass                 make                   mdcat                  mpv
==> Outdated Casks
utm

You have 6 outdated formulae and 1 outdated cask installed.
You can upgrade them with brew upgrade
or list them with brew outdated.
🚀 eshackelford@MacBook-Pro eshack94 $ brew upgrade
==> Upgrading 6 outdated packages:
mdcat 1.0.0 -> 1.1.0
make 4.4 -> 4.4.1
mpv 0.35.0 -> 0.35.1
k6 0.43.0 -> 0.43.1
kubeconform 0.6.0 -> 0.6.1
libass 0.17.0 -> 0.17.1
==> Fetching mdcat
==> Downloading https://ghcr.io/v2/homebrew/core/mdcat/manifests/1.1.0
Already downloaded: /Users/eshackelford/Library/Caches/Homebrew/downloads/17d722471fba1ea6d8ef0a0ffa8040ca97dccfccac354bcf33ff0dc27f13a00a--mdcat-1.1.0.bottle_manifest.json
==> Downloading https://ghcr.io/v2/homebrew/core/mdcat/manifests/1.1.0
######################################################################## 100.0%
Error: Missing 'annotations' section.
Please report this issue:
  https://docs.brew.sh/Troubleshooting
/opt/homebrew/Library/Homebrew/software_spec.rb:438:in `github_packages_manifest_resource_tab'
/opt/homebrew/Library/Homebrew/software_spec.rb:400:in `fetch_tab'
/opt/homebrew/Library/Homebrew/formula.rb:2621:in `fetch_bottle_tab'
/opt/homebrew/Library/Homebrew/formula_installer.rb:1183:in `fetch'
/opt/homebrew/Library/Homebrew/upgrade.rb:73:in `block in upgrade_formulae'
/opt/homebrew/Library/Homebrew/upgrade.rb:54:in `map'
/opt/homebrew/Library/Homebrew/upgrade.rb:54:in `upgrade_formulae'
/opt/homebrew/Library/Homebrew/cmd/upgrade.rb:194:in `upgrade_outdated_formulae'
/opt/homebrew/Library/Homebrew/cmd/upgrade.rb:116:in `upgrade'
/opt/homebrew/Library/Homebrew/brew.rb:93:in `<main>'
🚀 eshackelford@MacBook-Pro eshack94 $
```

### What did you expect to happen?

Expected `mdcat` package, and others to be upgraded.

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
1. Open Terminal.app or iTerm2.app. Must have an outdated installation of `mdcat`.
2. Run `brew update`.
3. Run `brew upgrade`.
```

**Comment by MicroBlueee** [comment]
same problem

**Comment by ZhongRuoyu** [comment]
Please try again now. I've rebuilt and reuploaded the bottles in https://github.com/Homebrew/homebrew-core/commit/20b79ac24a5dbedf63d4ed9416bbd423e5c2e55e.

**Comment by MicroBlueee** [comment]
verified, problem solved

**Comment by eshack94** [comment]
Thank you!
