### ISSUE TITLE
TypeError: no implicit conversion of false into String

### ISSUE THREAD

**Issue by derekPrivate** [Homebrew/homebrew-core#124434]
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

```shell
HOMEBREW_VERSION: 4.0.4
ORIGIN: https://github.com/Homebrew/brew
HEAD: 4d0154fa7926e8a7b06e9b074dd45957e820407c
Last commit: 26 hours ago
Core tap JSON: 28 Feb 15:05 UTC
HOMEBREW_PREFIX: /home/linuxbrew/.linuxbrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_MAKE_JOBS: 1
Homebrew Ruby: 2.6.8 => /home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.8_1/bin/ruby
CPU: single-core 64-bit haswell
Clang: N/A
Git: 2.38.3 => /usr/bin/git
Curl: 7.61.1 => /usr/bin/curl
Kernel: Linux 4.14.281-144.502.amzn1.x86_64 x86_64 GNU/Linux
OS: Unknown
Host glibc: 2.17
/usr/bin/gcc: 4.8.5
/usr/bin/ruby: 2.0.0
glibc: N/A
gcc@11: N/A
gcc: N/A
xorg: N/A

Your system is ready to brew.
```

### Verification

- [X] My "`brew doctor` output" says `Your system is ready to brew.` and am still able to reproduce my issue.
- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.

### What were you trying to do (and why)?

Using Amazon Linux 1 (quite an old version of Linux)
installed brew without problems, then wanted to
brew install gcc

reports error
TypeError: no implicit conversion of false into String

### What happened (include all command output)?

(switching on --verbose and --debug) shows this

==> Postinstalling gcc
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/brew.rb (Formulary::FromPathLoader): loading /home/linuxbrew/.linuxbrew/opt/gcc/.brew/gcc.rb
Warning: The post-install step did not complete successfully
You can try again using:
brew postinstall gcc
==> An exception occurred within a child process:
TypeError: no implicit conversion of false into String

/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/utils/popen.rb:47:in initialize' /home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/utils/popen.rb:47:in popen'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/utils/popen.rb:47:in popen' /home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/utils/popen.rb:9:in popen_read'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/utils/popen.rb:16:in safe_popen_read' /home/linuxbrew/.linuxbrew/opt/gcc/.brew/gcc.rb:151:in post_install'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/formula.rb:1160:in block (2 levels) in run_post_install' /home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/formula.rb:968:in with_logging'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/formula.rb:1159:in block in run_post_install' /home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/utils.rb:606:in with_env'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/formula.rb:1148:in run_post_install' /home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/postinstall.rb:24:in 

'

### What did you expect to happen?

gcc to be installed!

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
brew install gcc
```

**Comment by fxcoudert** [comment]
What does `brew info gcc` says? Your output says `gcc.rb:151:in post_install` but that line doesn't match what is currently in the formula.

**Comment by carlocab** [comment]
That'll probably be the formula generated from the API. I think API installs get tripped up by the `glibc` check in the `post_install` method.

**Comment by fxcoudert** [comment]
Does the API generate a different formula than the file in the repo? That's going to make backtraces hard to use 😢

**Comment by carlocab** [comment]
> Does the API generate a different formula than the file in the repo? That's going to make backtraces hard to use 😢 

Yes, unfortunately. Would be good to find a way to map lines to the original formula. Or maybe dump the generated one somehow. CC @Rylan12

**Comment by Bo98** [comment]
Should be the same except that the bottle block is missing.

**Comment by derekPrivate** [comment]
Following advice from Carlo, I now have a working gcc-12 (see below for what I did)

However, if this is vital, I can revert and try again?

As it stands at the moment (with a working gcc-12)  brew info gcc reports
==> Downloading https://formulae.brew.sh/api/formula.jws.json
######################################################################## 100.0%
==> gcc: stable 12.2.0 (bottled), HEAD
GNU compiler collection
https://gcc.gnu.org/
/home/linuxbrew/.linuxbrew/Cellar/gcc/12.2.0 (1,633 files, 306.6MB) *
  Poured from bottle on 2023-02-28 at 16:10:26
From: https://github.com/Homebrew/homebrew-core/blob/HEAD/Formula/gcc.rb
License: GPL-3.0-or-later with GCC-exception-3.1
==> Dependencies
Required: gmp ✔, isl ✔, libmpc ✔, mpfr ✔, zstd ✔, binutils ✔, zlib ✔, glibc ✔
==> Options
--HEAD
	Install HEAD version
==> Analytics
install: 59,279 (30 days), 200,202 (90 days), 1,357,096 (365 days)
install-on-request: 29,671 (30 days), 99,314 (90 days), 655,648 (365 days)
build-error: 127 (30 days)


This is what Carlo told me to do, and has resulted in a working install
export HOMEBREW_NO_INSTALL_FROM_API=1
brew tap homebrew/core
brew update
brew reinstall gcc

—
Derek Morris
***@***.***

**Comment by derekPrivate** [comment]
I am now getting a similar error when installing php on the same machine:

==> Installing php dependency: ncurses
==> Pouring ncurses--6.4.x86_64_linux.bottle.tar.gz
==> Downloading https://formulae.brew.sh/api/cask.jws.json
######################################################################## 100.0%
==> Downloading https://formulae.brew.sh/api/formula.jws.json
######################################################################## 100.0%
Error: no implicit conversion of false into String
Please report this issue:
  https://docs.brew.sh/Troubleshooting
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/utils/popen.rb:47:in `initialize'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/utils/popen.rb:47:in `popen'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/utils/popen.rb:47:in `popen'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/utils/popen.rb:9:in `popen_read'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/os/linux/elf.rb:134:in `initialize'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/os/linux/elf.rb:180:in `new'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/os/linux/elf.rb:180:in `metadata'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/os/linux/elf.rb:189:in `dynamically_linked_libraries'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/linkage_checker.rb:164:in `block in check_dylibs'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.8_1/lib/ruby/2.6.0/pathname.rb:565:in `block in find'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.8_1/lib/ruby/2.6.0/find.rb:49:in `block (2 levels) in find'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.8_1/lib/ruby/2.6.0/find.rb:48:in `catch'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.8_1/lib/ruby/2.6.0/find.rb:48:in `block in find'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.8_1/lib/ruby/2.6.0/find.rb:43:in `each'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.8_1/lib/ruby/2.6.0/find.rb:43:in `find'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.8_1/lib/ruby/2.6.0/pathname.rb:565:in `find'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.8_1/lib/ruby/2.6.0/forwardable.rb:230:in `find'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/linkage_checker.rb:157:in `check_dylibs'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/extend/os/linux/linkage_checker.rb:66:in `check_dylibs'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/linkage_checker.rb:37:in `initialize'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/formula.rb:2413:in `new'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/formula.rb:2413:in `block in undeclared_runtime_dependencies'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/cache_store.rb:26:in `use'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/formula.rb:2412:in `undeclared_runtime_dependencies'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/formula.rb:2021:in `runtime_dependencies'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/formula_installer.rb:805:in `finish'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/formula_installer.rb:738:in `install_dependency'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/formula_installer.rb:657:in `block in install_dependencies'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/formula_installer.rb:657:in `each'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/formula_installer.rb:657:in `install_dependencies'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/formula_installer.rb:403:in `install'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/upgrade.rb:203:in `install_formula'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/install.rb:350:in `install_formula'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/install.rb:340:in `block in install_formulae'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/install.rb:339:in `each'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/install.rb:339:in `install_formulae'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/cmd/install.rb:230:in `install'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/brew.rb:93:in `<main>'
—
Derek Morris
***@***.***

**Comment by fxcoudert** [comment]
This is a `brew` bug. I cannot transfer it there, for some reason…

**Comment by Bo98** [comment]
That error is really weird and I do not understand how it can happen. It's also at a very common callsite where installing anything would break with the same error, though we've not had any other reports of it happening.

The fact that API affects it is even more baffling.
