### ISSUE TITLE
Failed to install lapack

### ISSUE THREAD

**Issue by rmaack** [Homebrew/homebrew-core#12662]
I tried to install lapack, which fails with the error:

```
[rmaack@xirengcto01 ~]$ brew install lapack
==> Using Homebrew-provided fortran compiler.
This may be changed by setting the FC environment variable.
==> Downloading http://www.netlib.org/lapack/lapack-3.7.0.tgz
Already downloaded: /home/rmaack/.cache/Homebrew/lapack-3.7.0.tgz
==> cmake .. -DBUILD_SHARED_LIBS:BOOL=ON -DLAPACKE:BOOL=ON -DCMAKE_C_FLAGS_RELEASE=-DNDEBUG -DCMAKE_CXX_FLAGS_RELEASE=-DNDEBUG -DCMAKE_INSTALL_PREFIX=/home/rmaack/.linuxbrew_xirengcto01/Cellar/lapac
==> make install
Error: uninitialized constant Formulary::FormulaNamespace1f10e6644a7cc4e9130dc3e0c5c08883::Lapack::MachO
Please report this bug:
  https://github.com/Linuxbrew/brew/blob/master/docs/Troubleshooting.md#troubleshooting
/home/rmaack/.linuxbrew_xirengcto01/Library/Taps/homebrew/homebrew-core/Formula/lapack.rb:31:in `block (2 levels) in install'
/home/rmaack/.linuxbrew_xirengcto01/Library/Taps/homebrew/homebrew-core/Formula/lapack.rb:30:in `each'
/home/rmaack/.linuxbrew_xirengcto01/Library/Taps/homebrew/homebrew-core/Formula/lapack.rb:30:in `block in install'
/home/rmaack/.linuxbrew_xirengcto01/Library/Homebrew/extend/fileutils.rb:94:in `block in mkdir'
/home/rmaack/.linuxbrew_xirengcto01/Library/Homebrew/vendor/portable-ruby/2.0.0-p648/lib/ruby/2.0.0/fileutils.rb:125:in `chdir'
/home/rmaack/.linuxbrew_xirengcto01/Library/Homebrew/vendor/portable-ruby/2.0.0-p648/lib/ruby/2.0.0/fileutils.rb:125:in `cd'
/home/rmaack/.linuxbrew_xirengcto01/Library/Homebrew/extend/fileutils.rb:93:in `mkdir'
/home/rmaack/.linuxbrew_xirengcto01/Library/Taps/homebrew/homebrew-core/Formula/lapack.rb:22:in `install'
/home/rmaack/.linuxbrew_xirengcto01/Library/Homebrew/build.rb:149:in `block in install'
/home/rmaack/.linuxbrew_xirengcto01/Library/Homebrew/formula.rb:1137:in `block in brew'
/home/rmaack/.linuxbrew_xirengcto01/Library/Homebrew/formula.rb:1930:in `block in stage'
/home/rmaack/.linuxbrew_xirengcto01/Library/Homebrew/resource.rb:98:in `block in unpack'
/home/rmaack/.linuxbrew_xirengcto01/Library/Homebrew/extend/fileutils.rb:14:in `block in mktemp'
/home/rmaack/.linuxbrew_xirengcto01/Library/Homebrew/extend/fileutils.rb:74:in `block in run'
/home/rmaack/.linuxbrew_xirengcto01/Library/Homebrew/extend/fileutils.rb:74:in `chdir'
/home/rmaack/.linuxbrew_xirengcto01/Library/Homebrew/extend/fileutils.rb:74:in `run'
/home/rmaack/.linuxbrew_xirengcto01/Library/Homebrew/extend/fileutils.rb:13:in `mktemp'
/home/rmaack/.linuxbrew_xirengcto01/Library/Homebrew/resource.rb:94:in `unpack'
/home/rmaack/.linuxbrew_xirengcto01/Library/Homebrew/resource.rb:86:in `stage'
/home/rmaack/.linuxbrew_xirengcto01/Library/Homebrew/formula.rb:1917:in `stage'
/home/rmaack/.linuxbrew_xirengcto01/Library/Homebrew/formula.rb:1132:in `brew'
/home/rmaack/.linuxbrew_xirengcto01/Library/Homebrew/build.rb:124:in `install'
/home/rmaack/.linuxbrew_xirengcto01/Library/Homebrew/build.rb:201:in `<main>'
```

gist-logs: https://gist.github.com/58d4d5fd61c6ad75ae0f0649581b2e07

I run brew update before. Installing other packages seems to work also.

**Comment by bfontaine** [comment]
I edited your issue to replace the `lapack.txt` file link with its content.

**Comment by ilovezfs** [comment]
Your Homebrew is outdated.
```
HOMEBREW_VERSION: 1.1.11-10-ga4416e268
```
Please try `brew update --force` and then see what version is reported by `brew config`

**Comment by ilovezfs** [comment]
@rmaack I'm assuming that fixed it?

**Comment by rmaack** [comment]
No, unfortunately still the same error. After updating, my current version is 1.1.11.

**Comment by ilovezfs** [comment]
@rmaack in that case, please try `brew update-reset`

**Comment by rmaack** [comment]
Same result. Now on 1.1.11-12-g9d730186e.

**Comment by ilovezfs** [comment]
OK. Then
```
cd "$(brew --repo)"
git fetch --all --tags
brew update -f
```

**Comment by ilovezfs** [comment]
@rmaack fixed?

**Comment by rmaack** [comment]
No, that also didn't fix it :(

**Comment by ilovezfs** [comment]
```
cd "$(brew --repo)"
git status
git tag -l
```

**Comment by rmaack** [comment]
On branch stable
nothing to commit, working tree clean

1.0.0
1.0.1
1.0.2
1.0.3
1.0.4
1.0.5
1.0.6
1.0.7
1.0.8
1.0.9
1.1.0
1.1.0.1
1.1.1
1.1.10
1.1.11
1.1.2
1.1.2.1
1.1.3
1.1.4
1.1.5
1.1.6
1.1.7
1.1.8
1.1.9

**Comment by ilovezfs** [comment]
Ah, OK. I see this is linuxbrew! That would explain it. Please report this to https://github.com/Linuxbrew/homebrew-core/issues/ where they should be able to figure something out so this doesn't break on Linux.

**Comment by ilovezfs** [comment]
@rmaack this will be fixed by https://github.com/Homebrew/homebrew-core/pull/12740 once it makes its way over to Linuxbrew.

**Comment by sjackman** [comment]
There's a Core merge in progress at https://github.com/Linuxbrew/homebrew-core/pull/2424

**Comment by ilovezfs** [comment]
https://github.com/Homebrew/homebrew-core/pull/12740 has now shipped.
