### ISSUE TITLE
postinstall step fails for `helix` when installed at HEAD

### ISSUE THREAD

**Issue by nicholasjng** [Homebrew/homebrew-core#130672]
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

```shell
✗ brew config
HOMEBREW_VERSION: 4.0.17
ORIGIN: https://github.com/Homebrew/brew
HEAD: c0f8068573bbf886fdc78d3f9daca54d53e7e49e
Last commit: 2 days ago
Core tap JSON: 10 May 11:20 UTC
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_BROWSER: open
HOMEBREW_CASK_OPTS: []
HOMEBREW_EDITOR: hx
HOMEBREW_MAKE_JOBS: 10
Homebrew Ruby: 2.6.10 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: 10-core 64-bit arm_firestorm_icestorm
Clang: 14.0.3 build 1403
Git: 2.40.1 => /opt/homebrew/bin/git
Curl: 7.87.0 => /usr/bin/curl
macOS: 13.3.1-arm64
CLT: 14.3.0.0.1.1679647830
Xcode: 14.3
Rosetta 2: false
```

```
➜ brew doctor
Your system is ready to brew.
```

### Verification

- [X] My "`brew doctor` output" says `Your system is ready to brew.` and am still able to reproduce my issue.
- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.
- [X] I searched for recent similar issues at https://github.com/Homebrew/homebrew-core/issues?q=is%3Aissue and found no duplicates.

### What were you trying to do (and why)?

I have `helix` installed from source via `brew install --HEAD helix` to keep up to date with development changes, and frequently do reinstalls via `brew reinstall helix`. Since a few weeks (two-three maximum), `brew reinstall helix` fails in the postinstall step. Debug output shows me this:

```
Warning: The post-install step did not complete successfully
You can try again using:
  brew postinstall helix
==> An exception occurred within a child process:
  FormulaClassUnavailableError: No available formula with the name "b3f811592eb918ad5751fa834ae37387dca6e2fea043c995ef580adc27a29b32--helix".
In formula file: /Users/nicholasjunge/Library/Caches/Homebrew/downloads/b3f811592eb918ad5751fa834ae37387dca6e2fea043c995ef580adc27a29b32--helix.rb
Expected to find class B3f811592eb918ad5751fa834ae37387dca6e2fea043c995ef580adc27a29b32-Helix, but only found: Helix.
```

It looks like it tries to load the formula by commit SHA and fails, since no such bottle is created (the one found is only named "Helix"). Curiously, a subsequent `brew postinstall helix` runs just fine.

### What happened (include all command output)?

```
brew reinstall helix --debug

[...lots of output...]

/opt/homebrew/Library/Homebrew/brew.rb (Formulary::FromPathLoader): loading /opt/homebrew/opt/helix/.brew/helix.rb
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::FromPathLoader): loading /Users/nicholasjunge/Library/Caches/Homebrew/downloads/b3f811592eb918ad5751fa834ae37387dca6e2fea043c995ef580adc27a29b32--helix.rb

Warning: The post-install step did not complete successfully
You can try again using:
  brew postinstall helix
==> An exception occurred within a child process:
  FormulaClassUnavailableError: No available formula with the name "b3f811592eb918ad5751fa834ae37387dca6e2fea043c995ef580adc27a29b32--helix".
In formula file: /Users/nicholasjunge/Library/Caches/Homebrew/downloads/b3f811592eb918ad5751fa834ae37387dca6e2fea043c995ef580adc27a29b32--helix.rb
Expected to find class B3f811592eb918ad5751fa834ae37387dca6e2fea043c995ef580adc27a29b32-Helix, but only found: Helix.

/opt/homebrew/Library/Homebrew/formulary.rb:111:in `const_get'
/opt/homebrew/Library/Homebrew/formulary.rb:111:in `load_formula'
/opt/homebrew/Library/Homebrew/formulary.rb:125:in `load_formula_from_path'
/opt/homebrew/Library/Homebrew/formulary.rb:418:in `load_file'
/opt/homebrew/Library/Homebrew/formulary.rb:408:in `klass'
/opt/homebrew/Library/Homebrew/formulary.rb:403:in `get_formula'
/opt/homebrew/Library/Homebrew/formulary.rb:663:in `factory'
/opt/homebrew/Library/Homebrew/formulary.rb:323:in `resolve'
/opt/homebrew/Library/Homebrew/cli/named_args.rb:178:in `resolve_formula'
/opt/homebrew/Library/Homebrew/cli/named_args.rb:98:in `load_formula_or_cask'
/opt/homebrew/Library/Homebrew/cli/named_args.rb:55:in `block in to_formulae_and_casks'
/opt/homebrew/Library/Homebrew/cli/named_args.rb:54:in `each'
/opt/homebrew/Library/Homebrew/cli/named_args.rb:54:in `flat_map'
/opt/homebrew/Library/Homebrew/cli/named_args.rb:54:in `to_formulae_and_casks'
/opt/homebrew/Library/Homebrew/cli/named_args.rb:184:in `to_resolved_formulae'
/opt/homebrew/Library/Homebrew/postinstall.rb:22:in `<main>'
```

### What did you expect to happen?

Helix to reinstall normally, as it has many times before.

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
brew install --HEAD helix
brew reinstall helix
```

**Comment by carlocab** [comment]
CC @Bo98

**Comment by fxcoudert** [comment]
Related to https://github.com/Homebrew/homebrew-core/issues/130496 ?

**Comment by nicholasjng** [comment]
Any news on this? Still happens on my machine as of yesterday.
