### ISSUE TITLE
`bb` formula fails w/unexpected failure

### ISSUE THREAD

**Issue by jasonhemann** [Homebrew/homebrew-core#130961]
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

```shell
brew install bb
Error: formulae require at least a URL
Please report this issue:
  https://docs.brew.sh/Troubleshooting
/opt/homebrew/Library/Homebrew/formula.rb:285:in `determine_active_spec'
/opt/homebrew/Library/Homebrew/formula.rb:216:in `initialize'
/opt/homebrew/Library/Homebrew/formulary.rb:404:in `new'
/opt/homebrew/Library/Homebrew/formulary.rb:404:in `get_formula'
/opt/homebrew/Library/Homebrew/formulary.rb:663:in `factory'
/opt/homebrew/Library/Homebrew/cli/parser.rb:643:in `block in formulae'
/opt/homebrew/Library/Homebrew/cli/parser.rb:639:in `map'
/opt/homebrew/Library/Homebrew/cli/parser.rb:639:in `formulae'
/opt/homebrew/Library/Homebrew/cli/parser.rb:315:in `parse'
/opt/homebrew/Library/Homebrew/cmd/install.rb:167:in `install'
/opt/homebrew/Library/Homebrew/brew.rb:94:in `<main>'
```

### Verification

- [ ] My "`brew doctor` output" says `Your system is ready to brew.` and am still able to reproduce my issue.
- [X] I ran `brew update` and am still able to reproduce my issue.
- [ ] I have resolved all warnings from `brew doctor` and that did not fix my problem.
- [X] I searched for recent similar issues at https://github.com/Homebrew/homebrew-core/issues?q=is%3Aissue and found no duplicates.

### What were you trying to do (and why)?

Nothing interesting; came up in the process of wholesale migrating from the old brew location to the M1 brew location, this error message popped up. 

### What happened (include all command output)?

 $ brew install bb
Error: formulae require at least a URL
Please report this issue:
  https://docs.brew.sh/Troubleshooting
/opt/homebrew/Library/Homebrew/formula.rb:285:in `determine_active_spec'
/opt/homebrew/Library/Homebrew/formula.rb:216:in `initialize'
/opt/homebrew/Library/Homebrew/formulary.rb:404:in `new'
/opt/homebrew/Library/Homebrew/formulary.rb:404:in `get_formula'
/opt/homebrew/Library/Homebrew/formulary.rb:663:in `factory'
/opt/homebrew/Library/Homebrew/cli/parser.rb:643:in `block in formulae'
/opt/homebrew/Library/Homebrew/cli/parser.rb:639:in `map'
/opt/homebrew/Library/Homebrew/cli/parser.rb:639:in `formulae'
/opt/homebrew/Library/Homebrew/cli/parser.rb:315:in `parse'
/opt/homebrew/Library/Homebrew/cmd/install.rb:167:in `install'
/opt/homebrew/Library/Homebrew/brew.rb:94:in `<main>'

### What did you expect to happen?

Either the formula, whatever it was supposed to be, to successfully install or to issue a warning that it was deprecated and no longer supported.

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
`brew install bb`

I believe that should be sufficient to signal the message.
```

**Comment by carlocab** [comment]
Can't reproduce:
```
❯ HOMEBREW_NO_INSTALL_FROM_API= brew install bb
Warning: No available formula with the name "bb". Did you mean bbe?
```
What's the output of `brew info bbe`?

Also:

Please provide the output of `brew config` and `brew doctor`. We require this information from all bug reports at Homebrew.

> Please note we will close your issue without comment if you do not fill out the issue checklist below and provide ALL the requested information.

We can reopen this issue when you've provided the requested information.

**Comment by jasonhemann** [comment]
I believe I solved it; from another tap. The brew message

```
Uninstalling /usr/local/Cellar/bb/0.5.0... (5 files, 17.6MB)
``` 
was probably referring to the following: 

```
/usr/local/bin/brew search bb
==> Formulae
... craftamap/tap/bb
...
```
from `https://github.com/craftamap/homebrew-tap`. The command `brew install craftamap/tap/bb` gives the same output. `bbe` isn't installed, or relevant, AFAIK. 

```
 $ brew config
HOMEBREW_VERSION: 4.0.17-93-gb0dc84b
ORIGIN: https://github.com/Homebrew/brew
HEAD: b0dc84b117f54f6b18e0528b95477c54e409ebdd
Last commit: 2 days ago
Core tap origin: https://github.com/Homebrew/homebrew-core
Core tap HEAD: ce9ea2c975d6f420a247b721fc75011c17987739
Core tap last commit: 3 months ago
Core tap branch: master
Core tap JSON: 14 May 17:37 UTC
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_DISPLAY: /private/tmp/com.apple.launchd.a69EAWXRaS/org.xquartz:0
HOMEBREW_EDITOR: emacsclient -t
HOMEBREW_GITHUB_API_TOKEN: set
HOMEBREW_MAKE_JOBS: 10
Homebrew Ruby: 2.6.10 => /opt/homebrew/Library/Homebrew/vendor/portable-ruby/2.6.10_1/bin/ruby
CPU: 10-core 64-bit arm_firestorm_icestorm
Clang: 14.0.0 build 1400
Git: 2.40.1 => /opt/homebrew/bin/git
Curl: 7.79.1 => /usr/bin/curl
macOS: 12.6-arm64
CLT: 14.1.0.0.1.1666437224
Xcode: 14.1
Rosetta 2: false
$ brew doctor
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: Unbrewed dylibs were found in /usr/local/lib.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected dylibs:
  /usr/local/lib/libprofiler.0.dylib
  /usr/local/lib/libtcmalloc.4.dylib
  /usr/local/lib/libtcmalloc_and_profiler.4.dylib
  /usr/local/lib/libtcmalloc_debug.4.dylib
  /usr/local/lib/libtcmalloc_minimal.4.dylib
  /usr/local/lib/libtcmalloc_minimal_debug.4.dylib

Warning: Unbrewed header files were found in /usr/local/include.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected header files:
  /usr/local/include/google/heap-checker.h
  /usr/local/include/google/heap-profiler.h
  /usr/local/include/google/malloc_extension.h
  /usr/local/include/google/malloc_extension_c.h
  /usr/local/include/google/malloc_hook.h
  /usr/local/include/google/malloc_hook_c.h
  /usr/local/include/google/profiler.h
  /usr/local/include/google/stacktrace.h
  /usr/local/include/google/tcmalloc.h
  /usr/local/include/gperftools/heap-checker.h
  /usr/local/include/gperftools/heap-profiler.h
  /usr/local/include/gperftools/malloc_extension.h
  /usr/local/include/gperftools/malloc_extension_c.h
  /usr/local/include/gperftools/malloc_hook.h
  /usr/local/include/gperftools/malloc_hook_c.h
  /usr/local/include/gperftools/nallocx.h
  /usr/local/include/gperftools/profiler.h
  /usr/local/include/gperftools/stacktrace.h
  /usr/local/include/gperftools/tcmalloc.h

Warning: Unbrewed '.la' files were found in /usr/local/lib.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected '.la' files:
  /usr/local/lib/libprofiler.la
  /usr/local/lib/libtcmalloc.la
  /usr/local/lib/libtcmalloc_and_profiler.la
  /usr/local/lib/libtcmalloc_debug.la
  /usr/local/lib/libtcmalloc_minimal.la
  /usr/local/lib/libtcmalloc_minimal_debug.la

Warning: Unbrewed '.pc' files were found in /usr/local/lib/pkgconfig.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected '.pc' files:
  /usr/local/lib/pkgconfig/libprofiler.pc
  /usr/local/lib/pkgconfig/libtcmalloc.pc
  /usr/local/lib/pkgconfig/libtcmalloc_debug.pc
  /usr/local/lib/pkgconfig/libtcmalloc_minimal.pc
  /usr/local/lib/pkgconfig/libtcmalloc_minimal_debug.pc

Warning: Unbrewed static libraries were found in /usr/local/lib.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected static libraries:
  /usr/local/lib/libprofiler.a
  /usr/local/lib/libtcmalloc.a
  /usr/local/lib/libtcmalloc_and_profiler.a
  /usr/local/lib/libtcmalloc_debug.a
  /usr/local/lib/libtcmalloc_minimal.a
  /usr/local/lib/libtcmalloc_minimal_debug.a

Warning: You have unlinked kegs in your Cellar.
Leaving kegs unlinked can lead to build-trouble and cause formulae that depend on
those kegs to fail to run properly once built. Run `brew link` on these:
  docker
  ipython
  tcl-tk
  pyyaml
  doxygen

Warning: Your Xcode (14.1) is outdated.
Please update to Xcode 14.2 (or delete it).
Xcode can be updated from the App Store.


Warning: Some installed formulae are missing dependencies.
You should `brew install` the missing dependencies:
  brew install emacs

Run `brew missing` for more details.
```

I don't think that's very interesting, YMMV ofc.
