### ISSUE TITLE
`brew doctor` - Error: Unexpected run command

### ISSUE THREAD

**Issue by mprimeaux** [Homebrew/homebrew-core#131291]
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

```shell
I ran `brew doctor` and the output requested that I report the issue.


❯ brew doctor                                                                                                                                              ─╯
Error: Unexpected run command:
Please report this issue:
  https://docs.brew.sh/Troubleshooting
/opt/homebrew/Library/Homebrew/service.rb:571:in `deserialize'
/opt/homebrew/Library/Homebrew/formulary.rb:260:in `block in load_formula_from_api'
/opt/homebrew/Library/Homebrew/formulary.rb:149:in `initialize'
/opt/homebrew/Library/Homebrew/formulary.rb:149:in `new'
/opt/homebrew/Library/Homebrew/formulary.rb:149:in `load_formula_from_api'
/opt/homebrew/Library/Homebrew/formulary.rb:632:in `load_from_api'
/opt/homebrew/Library/Homebrew/formulary.rb:623:in `klass'
/opt/homebrew/Library/Homebrew/formulary.rb:403:in `get_formula'
/opt/homebrew/Library/Homebrew/formulary.rb:663:in `factory'
/opt/homebrew/Library/Homebrew/formulary.rb:711:in `from_keg'
/opt/homebrew/Library/Homebrew/formulary.rb:684:in `from_rack'
/opt/homebrew/Library/Homebrew/diagnostic.rb:717:in `block in check_for_unreadable_installed_formula'
/opt/homebrew/Library/Homebrew/diagnostic.rb:716:in `each'
/opt/homebrew/Library/Homebrew/diagnostic.rb:716:in `check_for_unreadable_installed_formula'
/opt/homebrew/Library/Homebrew/cmd/doctor.rb:60:in `block in doctor'
/opt/homebrew/Library/Homebrew/cmd/doctor.rb:53:in `each'
/opt/homebrew/Library/Homebrew/cmd/doctor.rb:53:in `doctor'
/opt/homebrew/Library/Homebrew/brew.rb:94:in `<main>'
```

### Verification

- [ ] My "`brew doctor` output" says `Your system is ready to brew.` and am still able to reproduce my issue.
- [x] I ran `brew update` and am still able to reproduce my issue.
- [ ] I have resolved all warnings from `brew doctor` and that did not fix my problem.
- [x] I searched for recent similar issues at https://github.com/Homebrew/homebrew-core/issues?q=is%3Aissue and found no duplicates.

### What were you trying to do (and why)?

I ran `brew doctor`.

### What happened (include all command output)?

```shell
❯ brew doctor                                                                                                                                              ─╯
Error: Unexpected run command:
Please report this issue:
  https://docs.brew.sh/Troubleshooting
/opt/homebrew/Library/Homebrew/service.rb:571:in `deserialize'
/opt/homebrew/Library/Homebrew/formulary.rb:260:in `block in load_formula_from_api'
/opt/homebrew/Library/Homebrew/formulary.rb:149:in `initialize'
/opt/homebrew/Library/Homebrew/formulary.rb:149:in `new'
/opt/homebrew/Library/Homebrew/formulary.rb:149:in `load_formula_from_api'
/opt/homebrew/Library/Homebrew/formulary.rb:632:in `load_from_api'
/opt/homebrew/Library/Homebrew/formulary.rb:623:in `klass'
/opt/homebrew/Library/Homebrew/formulary.rb:403:in `get_formula'
/opt/homebrew/Library/Homebrew/formulary.rb:663:in `factory'
/opt/homebrew/Library/Homebrew/formulary.rb:711:in `from_keg'
/opt/homebrew/Library/Homebrew/formulary.rb:684:in `from_rack'
/opt/homebrew/Library/Homebrew/diagnostic.rb:717:in `block in check_for_unreadable_installed_formula'
/opt/homebrew/Library/Homebrew/diagnostic.rb:716:in `each'
/opt/homebrew/Library/Homebrew/diagnostic.rb:716:in `check_for_unreadable_installed_formula'
/opt/homebrew/Library/Homebrew/cmd/doctor.rb:60:in `block in doctor'
/opt/homebrew/Library/Homebrew/cmd/doctor.rb:53:in `each'
/opt/homebrew/Library/Homebrew/cmd/doctor.rb:53:in `doctor'
/opt/homebrew/Library/Homebrew/brew.rb:94:in `<main>'
```

```shell
❯ brew config                                                                                                                                              ─╯
HOMEBREW_VERSION: 4.0.18
ORIGIN: https://github.com/Homebrew/brew
HEAD: b0dc84b117f54f6b18e0528b95477c54e409ebdd
Last commit: 5 days ago
Core tap JSON: 18 May 12:29 UTC
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_MAKE_JOBS: 20
Homebrew Ruby: 2.6.10 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: 20-core 64-bit arm_firestorm_icestorm
Clang: 14.0.3 build 1403
Git: 2.40.1 => /opt/homebrew/bin/git
Curl: 7.87.0 => /usr/bin/curl
macOS: 13.3.1-arm64
CLT: 14.3.0.0.1.1679647830
Xcode: 14.3
Rosetta 2: false
```

### What did you expect to happen?

I expected my system to be ready to brew.

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
See above.
```

**Comment by mprimeaux** [comment]
This appears to be an issue with the [golangci-lint](https://golangci-lint.run/usage/install/#macos) tap. The following solved the issue:

```shell
brew uninstall golangci/tap/golangci-lint
brew untaptap golangci/tap
brew install golangci-lint
```

```shell
brew doctor
Your system is ready to brew.
```

**Comment by dsummersl** [comment]
I'm having a similar stack track for the `dbus` package.
