### ISSUE TITLE
breq doctor ends up with error: Unexpected run command

### ISSUE THREAD

**Issue by typekpb** [Homebrew/homebrew-core#131295]
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

```shell
~ brew config
HOMEBREW_VERSION: 4.0.18
ORIGIN: https://github.com/Homebrew/brew
HEAD: b0dc84b117f54f6b18e0528b95477c54e409ebdd
Last commit: 5 days ago
Core tap JSON: 18 May 12:52 UTC
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_EDITOR: vim
HOMEBREW_MAKE_JOBS: 10
Homebrew Ruby: 2.6.10 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: 10-core 64-bit arm_firestorm_icestorm
Clang: 14.0.3 build 1403
Git: 2.40.1 => /opt/homebrew/bin/git
Curl: 7.87.0 => /usr/bin/curl
macOS: 13.3.1-arm64
CLT: 14.3.0.0.1.1679647830
Xcode: N/A
Rosetta 2: false

~ brew doctor
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: Some installed formulae are deprecated or disabled.
You should find replacements for the following formulae:
  node@14

Warning: You have unlinked kegs in your Cellar.
Leaving kegs unlinked can lead to build-trouble and cause formulae that depend on
those kegs to fail to run properly once built. Run `brew link` on these:
  aws-sam-cli
  pyyaml
  python-typing-extensions
Error: Unexpected run command:
Please report this issue:
  https://docs.brew.sh/Troubleshooting
/opt/homebrew/Library/Homebrew/service.rb:571:in `deserialize'
/opt/homebrew/Library/Homebrew/formulary.rb:260:in `block in load_formula_from_api'
/opt/homebrew/Library/Homebrew/formulary.rb:149:in `initialize'
/opt/homebrew/Library/Homebrew/formulary.rb:149:in `new'
/opt/homebrew/Library/Homebrew/formulary.rb:149:in `load_formula_from_api'
/opt/homebrew/Library/Homebrew/formulary.rb:632:in `load_from_api'
/opt/homebrew/Library/Homebrew/formulary.rb:623:in `klass'
/opt/homebrew/Library/Homebrew/formulary.rb:403:in `get_formula'
/opt/homebrew/Library/Homebrew/formulary.rb:663:in `factory'
/opt/homebrew/Library/Homebrew/formulary.rb:711:in `from_keg'
/opt/homebrew/Library/Homebrew/formulary.rb:684:in `from_rack'
/opt/homebrew/Library/Homebrew/diagnostic.rb:717:in `block in check_for_unreadable_installed_formula'
/opt/homebrew/Library/Homebrew/diagnostic.rb:716:in `each'
/opt/homebrew/Library/Homebrew/diagnostic.rb:716:in `check_for_unreadable_installed_formula'
/opt/homebrew/Library/Homebrew/cmd/doctor.rb:60:in `block in doctor'
/opt/homebrew/Library/Homebrew/cmd/doctor.rb:53:in `each'
/opt/homebrew/Library/Homebrew/cmd/doctor.rb:53:in `doctor'
/opt/homebrew/Library/Homebrew/brew.rb:94:in `<main>'

```

### Verification

- [ ] My "`brew doctor` output" says `Your system is ready to brew.` and am still able to reproduce my issue.
- [X] I ran `brew update` and am still able to reproduce my issue.
- [ ] I have resolved all warnings from `brew doctor` and that did not fix my problem.
- [X] I searched for recent similar issues at https://github.com/Homebrew/homebrew-core/issues?q=is%3Aissue and found no duplicates.

### What were you trying to do (and why)?

trying to perform majority of brew commands ends with the mentioned error

### What happened (include all command output)?

```
Error: Unexpected run command:
Please report this issue:
  https://docs.brew.sh/Troubleshooting
/opt/homebrew/Library/Homebrew/service.rb:571:in `deserialize'
/opt/homebrew/Library/Homebrew/formulary.rb:260:in `block in load_formula_from_api'
/opt/homebrew/Library/Homebrew/formulary.rb:149:in `initialize'
/opt/homebrew/Library/Homebrew/formulary.rb:149:in `new'
/opt/homebrew/Library/Homebrew/formulary.rb:149:in `load_formula_from_api'
/opt/homebrew/Library/Homebrew/formulary.rb:632:in `load_from_api'
/opt/homebrew/Library/Homebrew/formulary.rb:623:in `klass'
/opt/homebrew/Library/Homebrew/formulary.rb:403:in `get_formula'
/opt/homebrew/Library/Homebrew/formulary.rb:663:in `factory'
/opt/homebrew/Library/Homebrew/formulary.rb:711:in `from_keg'
/opt/homebrew/Library/Homebrew/formulary.rb:684:in `from_rack'
/opt/homebrew/Library/Homebrew/diagnostic.rb:717:in `block in check_for_unreadable_installed_formula'
/opt/homebrew/Library/Homebrew/diagnostic.rb:716:in `each'
/opt/homebrew/Library/Homebrew/diagnostic.rb:716:in `check_for_unreadable_installed_formula'
/opt/homebrew/Library/Homebrew/cmd/doctor.rb:60:in `block in doctor'
/opt/homebrew/Library/Homebrew/cmd/doctor.rb:53:in `each'
/opt/homebrew/Library/Homebrew/cmd/doctor.rb:53:in `doctor'
/opt/homebrew/Library/Homebrew/brew.rb:94:in `<main>'
```

### What did you expect to happen?

error-free behaviour

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
brew doctor
```

**Comment by carlocab** [comment]
Looks related to https://github.com/Homebrew/brew/issues/15454.
