### ISSUE TITLE
Unable to brew install podman or podman-compose

### ISSUE THREAD

**Issue by jared-pateman** [Homebrew/homebrew-core#131284]
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

```shell
~ % brew config
HOMEBREW_VERSION: 4.0.18
ORIGIN: https://github.com/Homebrew/brew
HEAD: b0dc84b117f54f6b18e0528b95477c54e409ebdd
Last commit: 5 days ago
Core tap JSON: 18 May 08:16 UTC
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_MAKE_JOBS: 10
Homebrew Ruby: 2.6.10 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: 10-core 64-bit arm_firestorm_icestorm
Clang: 14.0.3 build 1403
Git: 2.39.2 => /Library/Developer/CommandLineTools/usr/bin/git
Curl: 7.87.0 => /usr/bin/curl
macOS: 13.3.1-arm64
CLT: 14.3.0.0.1.1679647830
Xcode: N/A
Rosetta 2: false

~ % brew doctor
Your system is ready to brew.
```

### Verification

- [X] My "`brew doctor` output" says `Your system is ready to brew.` and am still able to reproduce my issue.
- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.
- [X] I searched for recent similar issues at https://github.com/Homebrew/homebrew-core/issues?q=is%3Aissue and found no duplicates.

### What were you trying to do (and why)?

Trying to install podman and podman-compose on my laptop for container development.

### What happened (include all command output)?

~ % brew install podman-compose
==> Downloading https://formulae.brew.sh/api/formula.jws.json
#=#=- #    #
==> Downloading https://formulae.brew.sh/api/cask.jws.json
#=#=- #    #
Error: Unexpected run command:
Please report this issue:
  https://docs.brew.sh/Troubleshooting
/opt/homebrew/Library/Homebrew/service.rb:571:in `deserialize'
/opt/homebrew/Library/Homebrew/formulary.rb:260:in `block in load_formula_from_api'
/opt/homebrew/Library/Homebrew/formulary.rb:149:in `initialize'
/opt/homebrew/Library/Homebrew/formulary.rb:149:in `new'
/opt/homebrew/Library/Homebrew/formulary.rb:149:in `load_formula_from_api'
/opt/homebrew/Library/Homebrew/formulary.rb:632:in `load_from_api'
/opt/homebrew/Library/Homebrew/formulary.rb:623:in `klass'
/opt/homebrew/Library/Homebrew/formulary.rb:403:in `get_formula'
/opt/homebrew/Library/Homebrew/formulary.rb:663:in `factory'
/opt/homebrew/Library/Homebrew/dependency.rb:42:in `to_formula'
/opt/homebrew/Library/Homebrew/dependency.rb:115:in `block in expand'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/delegate.rb:83:in `each'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/delegate.rb:83:in `method_missing'
/opt/homebrew/Library/Homebrew/dependency.rb:100:in `expand'
/opt/homebrew/Library/Homebrew/formula.rb:1997:in `recursive_dependencies'
/opt/homebrew/Library/Homebrew/formula_installer.rb:566:in `expand_requirements'
/opt/homebrew/Library/Homebrew/formula_installer.rb:518:in `compute_dependencies'
/opt/homebrew/Library/Homebrew/formula_installer.rb:228:in `verify_deps_exist'
/opt/homebrew/Library/Homebrew/formula_installer.rb:218:in `prelude'
/opt/homebrew/Library/Homebrew/install.rb:276:in `block in install_formulae'
/opt/homebrew/Library/Homebrew/install.rb:247:in `map'
/opt/homebrew/Library/Homebrew/install.rb:247:in `install_formulae'
/opt/homebrew/Library/Homebrew/cmd/install.rb:274:in `install'
/opt/homebrew/Library/Homebrew/brew.rb:94:in `<main>'

~ % brew install podman
Error: Unexpected run command:
Please report this issue:
  https://docs.brew.sh/Troubleshooting
/opt/homebrew/Library/Homebrew/service.rb:571:in `deserialize'
/opt/homebrew/Library/Homebrew/formulary.rb:260:in `block in load_formula_from_api'
/opt/homebrew/Library/Homebrew/formulary.rb:149:in `initialize'
/opt/homebrew/Library/Homebrew/formulary.rb:149:in `new'
/opt/homebrew/Library/Homebrew/formulary.rb:149:in `load_formula_from_api'
/opt/homebrew/Library/Homebrew/formulary.rb:632:in `load_from_api'
/opt/homebrew/Library/Homebrew/formulary.rb:623:in `klass'
/opt/homebrew/Library/Homebrew/formulary.rb:403:in `get_formula'
/opt/homebrew/Library/Homebrew/formulary.rb:663:in `factory'
/opt/homebrew/Library/Homebrew/cli/parser.rb:643:in `block in formulae'
/opt/homebrew/Library/Homebrew/cli/parser.rb:639:in `map'
/opt/homebrew/Library/Homebrew/cli/parser.rb:639:in `formulae'
/opt/homebrew/Library/Homebrew/cli/parser.rb:315:in `parse'
/opt/homebrew/Library/Homebrew/cmd/install.rb:167:in `install'
/opt/homebrew/Library/Homebrew/brew.rb:94:in `<main>'

Tried on multiple machines and facing the same issue.

### What did you expect to happen?

Podman and podman-compose to be installed on my machine.

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
1. brew update
2. brew doctor
3. brew install podman
4. brew install podman-compose
```

**Comment by hobofan** [comment]
It looks like the formula contains a `service` value of `{}`, which I think is supposed to be `null`.

There was a recent change with the merge of https://github.com/Homebrew/brew/pull/15396, which I assume is the source of this error.

**Comment by hobofan** [comment]
While I assume that the proper fix is supposed to happen server-side, for anyone looking for a client-side workaround in the meantime, you can patch the file `/opt/homebrew/Library/Homebrew/formulary.rb` at line 259 from
```ruby
      if (service_hash = json_formula["service"])
```
to
```ruby
      if (service_hash = json_formula["service"] and service_hash != {})
```

**Comment by jared-pateman** [comment]
> 

Client side fix has worked for now thank you 👍
