### ISSUE TITLE
hashcat 3.40 sha256 mismatch

### ISSUE THREAD

**Issue by DavidCWGA** [Homebrew/homebrew-core#13134]
While trying to upgrade hashcat to 3.40, homebrew 1.2.0 throws a sha256 error.

Other packages upgrade OK.

Things I tried:

- brew cleanup
- Deleting Caches/Homebrew/hashcat-3.40.tar.gz
- Checked gist-logs

### Verbose output

```
$ brew upgrade hashcat --verbose --debug
/usr/local/homebrew/Library/Homebrew/brew.rb (Formulary::FormulaLoader): loading /usr/local/homebrew/Library/Taps/homebrew/homebrew-core/Formula/hashcat.rb
==> Upgrading 1 outdated package, with result:
hashcat 3.40
/usr/local/homebrew/Library/Homebrew/brew.rb (Formulary::FormulaLoader): loading /usr/local/homebrew/Library/Taps/homebrew/homebrew-core/Formula/gnu-sed.rb
==> Upgrading hashcat 
rm /usr/local/homebrew/bin/hashcat
rm /usr/local/homebrew/share/doc/hashcat
rm /usr/local/homebrew/share/hashcat
==> Using the sandbox
/usr/bin/sandbox-exec -f /tmp/homebrew20170501-38437-le8lt8.sb nice /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin/ruby -W0 -I /usr/local/homebrew/Library/Homebrew -- /usr/local/homebrew/Library/Homebrew/build.rb /usr/local/homebrew/Library/Taps/homebrew/homebrew-core/Formula/hashcat.rb --verbose --debug
/usr/local/homebrew/Library/Homebrew/build.rb (Formulary::FromPathLoader): loading /usr/local/homebrew/Library/Taps/homebrew/homebrew-core/Formula/hashcat.rb
/usr/local/homebrew/Library/Homebrew/build.rb (Formulary::FormulaLoader): loading /usr/local/homebrew/Library/Taps/homebrew/homebrew-core/Formula/gnu-sed.rb
==> Downloading https://hashcat.net/files/hashcat-3.40.tar.gz
==> Downloading from https://hashcat.net/hashcat/
/usr/bin/curl --remote-time --location --user-agent Homebrew/1.2.0 (Macintosh; Intel Mac OS X 10.12.4) curl/7.51.0 --fail https://hashcat.net/hashcat/ -C 0 -o /Users/lion/Library/Caches/Homebrew/hashcat-3.40.tar.gz.incomplete --connect-timeout 5
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 15941  100 15941    0     0  15416      0  0:00:01  0:00:01 --:--:-- 15431
==> Verifying hashcat-3.40.tar.gz checksum
ln -s ../Cellar/hashcat/3.10/bin/hashcat hashcat
ln -s ../../Cellar/hashcat/3.10/share/doc/hashcat hashcat
ln -s ../Cellar/hashcat/3.10/share/hashcat hashcat
Error: SHA256 mismatch
Expected: 92627197daa850dc7d723793150801c0791fe31f6c767de68417cee097ad6f4c
Actual: d729bbdccb2b4ab459e910406202f5704ebcf49629902d9edd085630f7ee2ef0
Archive: /Users/lion/Library/Caches/Homebrew/hashcat-3.40.tar.gz
To retry an incomplete download, remove the file above.
/usr/local/homebrew/Library/Homebrew/extend/pathname.rb:331:in `verify_checksum'
/usr/local/homebrew/Library/Homebrew/resource.rb:127:in `verify_download_integrity'
/usr/local/homebrew/Library/Homebrew/resource.rb:85:in `stage'
/usr/local/homebrew/Library/Homebrew/formula.rb:1936:in `stage'
/usr/local/homebrew/Library/Homebrew/formula.rb:1143:in `brew'
/usr/local/homebrew/Library/Homebrew/build.rb:112:in `install'
/usr/local/homebrew/Library/Homebrew/build.rb:189:in `<main>'
```

### Config

```
$ brew config
HOMEBREW_VERSION: 1.2.0
ORIGIN: https://github.com/Homebrew/brew
HEAD: 8cba0352e0be94263e2ed96c98bf93d8f2fce8ef
Last commit: 9 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 0e8e5f6b9cdb5352fe257eae4b105b3b0e3d81d2
Core tap last commit: 2 hours ago
HOMEBREW_PREFIX: /usr/local/homebrew
HOMEBREW_REPOSITORY: /usr/local/homebrew
HOMEBREW_CELLAR: /usr/local/homebrew/Cellar
HOMEBREW_BOTTLE_DOMAIN: https://homebrew.bintray.com
CPU: quad-core 64-bit skylake
Homebrew Ruby: 2.0.0-p648
Clang: 8.1 build 802
Git: 2.11.0 => /Applications/Xcode.app/Contents/Developer/usr/bin/git
Perl: /usr/bin/perl
Python: /usr/local/homebrew/bin/python => /usr/local/homebrew/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/bin/python2.7
Ruby: /usr/bin/ruby => /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin/ruby
Java: N/A
macOS: 10.12.4-x86_64
Xcode: 8.3.2
CLT: N/A
X11: 2.7.11 => /opt/X11
```

### Doctor

```
$ brew doctor
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry and just ignore them. Thanks!

Warning: Your Homebrew's prefix is not /usr/local.
You can install Homebrew anywhere you want but some bottles (binary packages)
can only be used with a /usr/local prefix and some formulae (packages)
may not build correctly with a non-/usr/local prefix.
```

**Comment by neutric** [comment]
Resolved in #13139.
