### ISSUE TITLE
Cruft not running with macOS Ventura + python 3.11 

### ISSUE THREAD

**Issue by AbdelrhmanHamouda** [Homebrew/homebrew-core#135029]
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

```shell
brew config: 

❯ brew config
HOMEBREW_VERSION: 4.0.25
ORIGIN: https://github.com/Homebrew/brew
HEAD: 2ccdb26c45e0ac8c7d4a8c2cc78cd577c28a2707
Last commit: 4 hours ago
Core tap JSON: 26 Jun 16:12 UTC
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_MAKE_JOBS: 10
Homebrew Ruby: 2.6.10 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: 10-core 64-bit arm_firestorm_icestorm
Clang: 14.0.3 build 1403
Git: 2.39.2 => /Library/Developer/CommandLineTools/usr/bin/git
Curl: 7.88.1 => /usr/bin/curl
macOS: 13.4-arm64
CLT: 14.3.0.0.1.1679647830
Xcode: N/A
Rosetta 2: false

❯ brew doctor
Your system is ready to brew.
```

### Verification

- [X] My "`brew doctor` output" says `Your system is ready to brew.` and am still able to reproduce my issue.
- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.
- [X] I searched for recent similar issues at https://github.com/Homebrew/homebrew-core/issues?q=is%3Aissue and found no duplicates.

### What were you trying to do (and why)?

Issue: 
Attempting to run Cruft on my macOS with python 3.11.4 returns an error. 

### What happened (include all command output)?

Error: 
```bash
❯ cruft
Traceback (most recent call last):
  File "/opt/homebrew/bin/cruft", line 5, in <module>
    from cruft._cli import app
  File "/opt/homebrew/Cellar/cruft/2.15.0/libexec/lib/python3.11/site-packages/cruft/__init__.py", line 6, in <module>
    from cruft._commands import check, create, diff, link, update
  File "/opt/homebrew/Cellar/cruft/2.15.0/libexec/lib/python3.11/site-packages/cruft/_commands/__init__.py", line 2, in <module>
    from .check import check
  File "/opt/homebrew/Cellar/cruft/2.15.0/libexec/lib/python3.11/site-packages/cruft/_commands/check.py", line 5, in <module>
    import typer
  File "/opt/homebrew/Cellar/cruft/2.15.0/libexec/lib/python3.11/site-packages/typer/__init__.py", line 7, in <module>
    from click.exceptions import Abort as Abort
ModuleNotFoundError: No module named 'click'
```

### What did you expect to happen?

For Cruft to work. 

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
- brew install cruft

==> Downloading https://formulae.brew.sh/api/formula.jws.json

==> Downloading https://formulae.brew.sh/api/cask.jws.json

Warning: cruft 2.15.0 is already installed and up-to-date.
To reinstall 2.15.0, run:
  brew reinstall cruft
```
- brew reinstall cruft
```
==> Fetching cruft
==> Downloading https://ghcr.io/v2/homebrew/core/cruft/manifests/2.15.0-1
Already downloaded: /Users/abdelrhman.hamouda/Library/Caches/Homebrew/downloads/726bbf04a2816de358186bd688274bc63e1de52843c2076a44cee6afea8fed2c--cruft-2.15.0-1.bottle_manifest.json
==> Downloading https://ghcr.io/v2/homebrew/core/cruft/blobs/sha256:0551ec5eb807
Already downloaded: /Users/abdelrhman.hamouda/Library/Caches/Homebrew/downloads/67b0dc44eaa53ffe3a4685ef1987ff6875fb76769b86922cd707d4473ea22500--cruft--2.15.0.arm64_ventura.bottle.1.tar.gz
==> Reinstalling cruft
==> Pouring cruft--2.15.0.arm64_ventura.bottle.1.tar.gz
🍺  /opt/homebrew/Cellar/cruft/2.15.0: 907 files, 11.0MB
==> Running `brew cleanup cruft`...
Disable this behaviour by setting HOMEBREW_NO_INSTALL_CLEANUP.
Hide these hints with HOMEBREW_NO_ENV_HINTS (see `man brew`).
```
- cruft
```
Traceback (most recent call last):
  File "/opt/homebrew/bin/cruft", line 5, in <module>
    from cruft._cli import app
  File "/opt/homebrew/Cellar/cruft/2.15.0/libexec/lib/python3.11/site-packages/cruft/__init__.py", line 6, in <module>
    from cruft._commands import check, create, diff, link, update
  File "/opt/homebrew/Cellar/cruft/2.15.0/libexec/lib/python3.11/site-packages/cruft/_commands/__init__.py", line 2, in <module>
    from .check import check
  File "/opt/homebrew/Cellar/cruft/2.15.0/libexec/lib/python3.11/site-packages/cruft/_commands/check.py", line 5, in <module>
    import typer
  File "/opt/homebrew/Cellar/cruft/2.15.0/libexec/lib/python3.11/site-packages/typer/__init__.py", line 7, in <module>
    from click.exceptions import Abort as Abort
ModuleNotFoundError: No module named 'click'
```
```

**Comment by cho-m** [comment]
According to formula, `click` should be available from dependency `cookiecutter`.

It looks like `cookiecutter` did not get a revision bump when it updated to `python@3.11`. You can check what version of `cookiecutter` you have installed or the version of Python it is using, e.g. 
```console
❯ ls $(brew --prefix cookiecutter)/libexec/lib
python3.11
```

If this is the issue, `cookiecutter` probably should have a revision bump.

**Comment by carlocab** [comment]
This should be fixed now. Try doing `brew update && brew upgrade cookiecutter` in about ~20 minutes.

**Comment by AbdelrhmanHamouda** [comment]
thank you for fixing this so quickly. 
I tested it and it is working perfectly.
