### ISSUE TITLE
Remove Xcode requirement for `root` (again)

### ISSUE THREAD

**Issue by wickles** [Homebrew/homebrew-core#135714]
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

```shell
❯ brew config
HOMEBREW_VERSION: 4.0.26-35-g9e257fc
ORIGIN: https://github.com/Homebrew/brew
HEAD: 9e257fc96046535dbc066fb557e6a84802feb0b6
Last commit: 3 hours ago
Core tap origin: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 52815a6a386d3e4dacf56464cddb0880823a4576
Core tap last commit: 27 minutes ago
Core tap branch: master
Core tap JSON: 25 May 20:40 UTC
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_CASK_OPTS: ["--no-quarantine"]
HOMEBREW_DISPLAY: /private/tmp/com.apple.launchd.GLKlaXcBsM/org.xquartz:0
HOMEBREW_EDITOR: vim
HOMEBREW_GITHUB_API_TOKEN: set
HOMEBREW_MAKE_JOBS: 8
HOMEBREW_NO_AUTO_UPDATE: set
HOMEBREW_NO_INSTALL_FROM_API: set
Homebrew Ruby: 2.6.10 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: octa-core 64-bit arm_firestorm_icestorm
Clang: 14.0.3 build 1403
Git: 2.39.2 => /Library/Developer/CommandLineTools/usr/bin/git
Curl: 7.88.1 => /usr/bin/curl
macOS: 13.4-arm64
CLT: 14.3.1.0.1.1683849156
Xcode: N/A
Rosetta 2: false
❯ brew doctor
Your system is ready to brew.
```

### Verification

- [X] My "`brew doctor` output" says `Your system is ready to brew.` and am still able to reproduce my issue.
- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.
- [X] I searched for recent similar issues at https://github.com/Homebrew/homebrew-core/issues?q=is%3Aissue and found no duplicates.

### What were you trying to do (and why)?

Build and/or install `root` formula without Xcode. This issue came up before and was resolved (#73947), but since then there was a regression due to https://github.com/Homebrew/homebrew-core/pull/92497 where it was claimed that it "always needs Xcode now".

Xcode still does not appear to be a requirement upstream, and the official release build that I tried does not need it to run. Is it a CI/CD build issue? Problem building binaries for older versions of macOS? Some other quirk of homebrew?

cc @iMichka @henryiii @carlocab @Axel-Naumann 

### What happened (include all command output)?

The build error log cited for requiring Xcode is here: https://github.com/Homebrew/homebrew-core/pull/92497#issuecomment-1004748648.

Attempting to install `root`:

```
❯ brew install root
root: A full installation of Xcode.app is required to compile
this software. Installing just the Command Line Tools is not sufficient.

Xcode can be installed from the App Store.
Error: An unsatisfied requirement failed this build.
```

I forcibly installed the `root` bottle without Xcode to see what runtime errors would show up. 

```
❯ brew install --ignore-dependencies root
...
❯ brew install --only-dependencies root
...
❯ root
warning: no such sysroot directory: '/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/'
C system headers (glibc/Xcode/Windows SDK) must be installed.
error: entry with relative path at the root level is not discoverable
{ 'name': '', 'type': 'directory',
          ^~
Error in modulemap.overlay!

 *** Break *** segmentation violation
[/usr/lib/system/libsystem_platform.dylib] _sigtramp (no debug info)
[/opt/homebrew/Cellar/root/6.28.04/lib/root/libCling.so] llvm::vfs::OverlayFileSystem::pushOverlay(llvm::IntrusiveRefCntPtr<llvm::vfs::FileSystem>) (no debug info)
[/opt/homebrew/Cellar/root/6.28.04/lib/root/libCling.so] (anonymous namespace)::setupCxxModules(clang::CompilerInstance&) (no debug info)
[/opt/homebrew/Cellar/root/6.28.04/lib/root/libCling.so] (anonymous namespace)::createCIImpl(std::__1::unique_ptr<llvm::MemoryBuffer, std::__1::default_delete<llvm::MemoryBuffer>>, cling::CompilerOptions const&, char const*, std::__1::unique_ptr<clang::ASTConsumer, std::__1::default_delete<clang::ASTConsumer>>, std::__1::vector<std::__1::shared_ptr<clang::ModuleFileExtension>, std::__1::allocator<std::__1::shared_ptr<clang::ModuleFileExtension>>> const&, bool, bool) (no debug info)
[/opt/homebrew/Cellar/root/6.28.04/lib/root/libCling.so] cling::CIFactory::createCI(llvm::StringRef, cling::InvocationOptions const&, char const*, std::__1::unique_ptr<clang::ASTConsumer, std::__1::default_delete<clang::ASTConsumer>>, std::__1::vector<std::__1::shared_ptr<clang::ModuleFileExtension>, std::__1::allocator<std::__1::shared_ptr<clang::ModuleFileExtension>>> const&) (no debug info)
[/opt/homebrew/Cellar/root/6.28.04/lib/root/libCling.so] cling::IncrementalParser::IncrementalParser(cling::Interpreter*, char const*, std::__1::vector<std::__1::shared_ptr<clang::ModuleFileExtension>, std::__1::allocator<std::__1::shared_ptr<clang::ModuleFileExtension>>> const&) (no debug info)
[/opt/homebrew/Cellar/root/6.28.04/lib/root/libCling.so] cling::Interpreter::Interpreter(int, char const* const*, char const*, std::__1::vector<std::__1::shared_ptr<clang::ModuleFileExtension>, std::__1::allocator<std::__1::shared_ptr<clang::ModuleFileExtension>>> const&, void*, bool, cling::Interpreter const*) (no debug info)
[/opt/homebrew/Cellar/root/6.28.04/lib/root/libCling.so] TCling::TCling(char const*, char const*, char const* const*, void*) (no debug info)
[/opt/homebrew/Cellar/root/6.28.04/lib/root/libCling.so] CreateInterpreter (no debug info)
[/opt/homebrew/Cellar/root/6.28.04/lib/root/libCore.so] TROOT::InitInterpreter() (no debug info)
[/opt/homebrew/Cellar/root/6.28.04/lib/root/libCore.so] ROOT::Internal::GetROOT2() (no debug info)
[/opt/homebrew/Cellar/root/6.28.04/lib/root/libCore.so] TApplication::TApplication(char const*, int*, char**, void*, int) (no debug info)
[/opt/homebrew/Cellar/root/6.28.04/lib/root/libRint.so] TRint::TRint(char const*, int*, char**, void*, int, bool, bool) (no debug info)
[/opt/homebrew/Cellar/root/6.28.04/bin/root.exe] main (no debug info)
[/usr/lib/dyld] start (no debug info)
```

I also tried to forcibly build from source but there is some random ruby exception? Otherwise I suspect this should work.

```
❯ brew install --build-from-source --verbose --debug --ignore-dependencies root
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::FormulaLoader): loading /opt/homebrew/Library/Taps/homebrew/homebrew-core/Formula/root.rb
Warning: `--ignore-dependencies` is an unsupported Homebrew developer flag!
Adjust your PATH to put any preferred versions of applications earlier in the
PATH rather than using this unsupported flag!

==> Fetching root
==> Downloading https://root.cern.ch/download/root_v6.28.04.source.tar.gz
/usr/bin/env /opt/homebrew/Library/Homebrew/shims/shared/curl --disable --cookie /dev/null --globoff --show-error --user-agent Homebrew/4.0.26-35-g9e257fc\ \(Macintosh\;\ arm64\ Mac\ OS\ X\ 13.4\)\ curl/7.88.1 --header Accept-Language:\ en --retry 3 --fail --location --silent --head https://root.cern.ch/download/root_v6.28.04.source.tar.gz
/usr/bin/env /opt/homebrew/Library/Homebrew/shims/shared/curl --disable --cookie /dev/null --globoff --show-error --user-agent Homebrew/4.0.26-35-g9e257fc\ \(Macintosh\;\ arm64\ Mac\ OS\ X\ 13.4\)\ curl/7.88.1 --header Accept-Language:\ en --retry 3 --fail --location --silent --head --request GET https://root.cern.ch/download/root_v6.28.04.source.tar.gz
Already downloaded: /Users/me/Library/Caches/Homebrew/downloads/647ef49d2de93d323b0bb83dd93915a37c9f36f9d31e4595b5e8675a538744ab--root_v6.28.04.source.tar.gz
==> Verifying checksum for '647ef49d2de93d323b0bb83dd93915a37c9f36f9d31e4595b5e8675a538744ab--root_v6.28.04.source.tar.gz'
/usr/bin/env /opt/homebrew/Library/Homebrew/shims/shared/git --version
/usr/bin/env tar --extract --no-same-owner --file /Users/me/Library/Caches/Homebrew/downloads/647ef49d2de93d323b0bb83dd93915a37c9f36f9d31e4595b5e8675a538744ab--root_v6.28.04.source.tar.gz --directory /private/tmp/d20230703-42642-xgm6fn
/usr/bin/env cp -pR /private/tmp/d20230703-42642-xgm6fn/root-6.28.04/. /private/tmp/root-20230703-42642-1lvniid/root-6.28.04
/opt/homebrew/Library/Homebrew/build.rb (Formulary::FormulaLoader): loading /opt/homebrew/Library/Taps/homebrew/homebrew-core/Formula/util-linux.rb
==> Temporary files retained at:
/private/tmp/root-20230703-42642-1lvniid
Error: An exception occurred within a child process:
  NoMethodError: undefined method `path' for nil:NilClass
/opt/homebrew/Library/Homebrew/formula.rb:1587:in `std_cmake_args'
/opt/homebrew/Library/Taps/homebrew/homebrew-core/Formula/root.rb:84:in `install'
/opt/homebrew/Library/Homebrew/debrew.rb:17:in `block in install'
/opt/homebrew/Library/Homebrew/debrew.rb:88:in `debrew'
/opt/homebrew/Library/Homebrew/debrew.rb:17:in `install'
/opt/homebrew/Library/Homebrew/build.rb:177:in `block (3 levels) in install'
/opt/homebrew/Library/Homebrew/extend/kernel.rb:498:in `with_env'
/opt/homebrew/Library/Homebrew/build.rb:139:in `block (2 levels) in install'
/opt/homebrew/Library/Homebrew/formula.rb:1350:in `block in brew'
/opt/homebrew/Library/Homebrew/formula.rb:2736:in `block (2 levels) in stage'
/opt/homebrew/Library/Homebrew/extend/kernel.rb:498:in `with_env'
/opt/homebrew/Library/Homebrew/formula.rb:2735:in `block in stage'
/opt/homebrew/Library/Homebrew/resource.rb:128:in `block (2 levels) in unpack'
/opt/homebrew/Library/Homebrew/download_strategy.rb:118:in `chdir'
/opt/homebrew/Library/Homebrew/download_strategy.rb:118:in `chdir'
/opt/homebrew/Library/Homebrew/download_strategy.rb:105:in `stage'
/opt/homebrew/Library/Homebrew/resource.rb:124:in `block in unpack'
/opt/homebrew/Library/Homebrew/mktemp.rb:75:in `block in run'
/opt/homebrew/Library/Homebrew/mktemp.rb:75:in `chdir'
/opt/homebrew/Library/Homebrew/mktemp.rb:75:in `run'
/opt/homebrew/Library/Homebrew/resource.rb:228:in `stage_resource'
/opt/homebrew/Library/Homebrew/resource.rb:123:in `unpack'
/opt/homebrew/Library/Homebrew/resource.rb:97:in `stage'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/forwardable.rb:230:in `stage'
/opt/homebrew/Library/Homebrew/formula.rb:2715:in `stage'
/opt/homebrew/Library/Homebrew/formula.rb:1343:in `brew'
/opt/homebrew/Library/Homebrew/build.rb:133:in `block in install'
/opt/homebrew/Library/Homebrew/extend/kernel.rb:498:in `with_env'
/opt/homebrew/Library/Homebrew/build.rb:128:in `install'
/opt/homebrew/Library/Homebrew/build.rb:229:in `<main>'
```

(p.s. this worked after I removed the xcode dependency from the formula instead of trying to override it.)

### What did you expect to happen?

It should build and run without Xcode.app (only CLT).

I have personally never needed a full Xcode installation for anything, since I don't build apps for apple devices.

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
brew install root
# formula dependency error

brew install --ignore-dependencies root
brew install --only-dependencies root
root
# runtime error

brew install cmake ninja pkg-config
brew install --build-from-source --verbose --debug --ignore-dependencies root
# ruby error?
```

**Comment by cho-m** [comment]
We can see what current build looks like in #135719.

The previous failure usually occurs when headers are mixed (e.g. across SDKs and/or installed GCC/LLVM).

**Comment by cho-m** [comment]
On ARM, Ventura succeeded but older macOS failed test when loading CLT, e.g.
```
  ==> /opt/homebrew/Cellar/root/6.28.04/bin/root -b -l -q -e gSystem->LoadAllLibraries(); 0
  input_line_1:1:2: fatal error: malformed or corrupted AST file: 'could not find file '/Library/Developer/CommandLineTools/SDKs/MacOSX12.sdk/usr/include/sys__pthread.modulemap' referenced by AST file'
  #include <new>
   ^
  input_line_1:1:2: note: after modifying system headers, please delete the module cache at '/opt/homebrew/Cellar/root/6.28.04/lib/root'
  input_line_1:1:2: note: imported by module 'std' in '/opt/homebrew/Cellar/root/6.28.04/lib/root/std.pcm'
  Warning in cling::IncrementalParser::CheckABICompatibility():
    Failed to extract C++ standard library version.
  Warning in cling::IncrementalParser::CheckABICompatibility():
    Possible C++ standard library mismatch, compiled with _LIBCPP_ABI_VERSION '1'
    Extraction of runtime standard library version was: ''
  Replaced symbol at_quick_exit cannot be found in JIT!
  <<< cling interactive line includer >>>: fatal error: module file '/opt/homebrew/Cellar/root/6.28.04/lib/root/Darwin.pcm' is out of date and needs to be rebuilt
```

**Comment by wickles** [comment]
Are the existing bottles for older macOS even working? It looks like [CI checks on the last PR](https://github.com/Homebrew/homebrew-core/pull/114543/checks) were failing and skipped.

Are the upstream builds even working for older macOS? Not sure if I can test this without a downgraded mac. Does Xcode let you run builds for older platforms?

**Comment by cho-m** [comment]
> Are the existing bottles for older macOS even working? It looks like [CI checks on the last PR](https://github.com/Homebrew/homebrew-core/pull/114543/checks) were failing and skipped.

You are looking at the wrong checks. Those are for adding bottles. The tests were done on https://github.com/Homebrew/homebrew-core/actions/runs/5434692181/jobs/9883327011 and everything passed

**Comment by wickles** [comment]
Thank you for the correction. I was not sure how to find that before but I see it now.

I checked the upstream macOS 12 build again and I noticed that it actually does run but it throws some (non-fatal) errors due to hard-linking to the CLT MacOSX13.1 SDK.

```
❯ ./root_v6.28.04.macos-12.6-arm64-clang140/root/bin/root
clang: error: argument to '-isysroot' is missing (expected 1 value)
clang: error: no input files
ERROR in cling::CIFactory::createCI(): cannot extract standard library include paths!
Invoking:
  LC_ALL=C /Library/Developer/CommandLineTools/usr/bin/c++ -isysroot;/Library/Developer/CommandLineTools/SDKs/MacOSX13.1.sdk   -xc++ -E -v /dev/null 2>&1 | sed -n -e '/^.include/,${' -e '/^ \/.*++/p' -e '}'
Results was:
clang: error: argument to '-isysroot' is missing (expected 1 value)
clang: error: no input files
With exit code 0
   ------------------------------------------------------------------
  | Welcome to ROOT 6.28/04                        https://root.cern |
  | (c) 1995-2022, The ROOT Team; conception: R. Brun, F. Rademakers |
  | Built for macosxarm64 on May 08 2023, 02:44:07                   |
  | From tags/v6-28-04@v6-28-04                                      |
  | With Apple clang version 14.0.0 (clang-1400.0.29.202)            |
  | Try '.help'/'.?', '.demo', '.license', '.credits', '.quit'/'.q'  |
   ------------------------------------------------------------------

root [0] .q
```

Indeed you can find various hard references specifically to the MacOSX13.1 SDK, and only that SDK, in the macOS 12 build. That shouldn't be available on macOS 12, and also isn't available for me on macOS 13.4. 

```
❯ ls /Library/Developer/CommandLineTools/SDKs/
MacOSX.sdk     MacOSX12.3.sdk MacOSX12.sdk   MacOSX13.3.sdk MacOSX13.sdk
```

That it is working only with Xcode is probably just because Xcode is shipping with all of the SDKs, I'm guessing.

**Comment by carlocab** [comment]
> That it builds successfully for the older OS only with Xcode is probably just because Xcode is providing all of the SDKs, I'm guessing.

Xcode actually typically includes only the latest SDK, which is why we often insist on CLT installations. For example, on Xcode 14.3:
```
❯ ls -la "$(brew ruby -e "puts MacOS::Xcode.sdk_path")/.."
total 0
drwxr-xr-x  5 root  wheel  160  2 Jun 13:25 .
drwxr-xr-x  6 root  wheel  192 20 May 09:16 ..
drwxr-xr-x  7 root  wheel  224 10 Mar 08:58 MacOSX.sdk
lrwxr-xr-x  1 root  wheel   10  2 Jun 13:21 MacOSX13.3.sdk -> MacOSX.sdk
lrwxr-xr-x  1 root  wheel   10  2 Jun 13:21 MacOSX13.sdk -> MacOSX.sdk
```

**Comment by cho-m** [comment]
Haven't checked too much but current failure may be from mixing Xcode.app and CLT, e.g.
```console
❯ rg CMAKE_OSX_SYSROOT:
CMakeCache.txt
522:CMAKE_OSX_SYSROOT:PATH=/Library/Developer/CommandLineTools/SDKs/MacOSX12.sdk

CMakeFiles/CheckFortran/CMakeCache.txt
127:CMAKE_OSX_SYSROOT:PATH=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX13.1.sdk

googletest-prefix/src/googletest-build/CMakeCache.txt
191:CMAKE_OSX_SYSROOT:PATH=/Library/Developer/CommandLineTools/SDKs/MacOSX12.sdk

VDT-prefix/src/VDT-build/CMakeCache.txt
147:CMAKE_OSX_SYSROOT:PATH=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX13.1.sdk

interpreter/cling/tools/plugins/clad/clad-prefix/src/clad-build/CMakeCache.txt
156:CMAKE_OSX_SYSROOT:PATH=/Library/Developer/CommandLineTools/SDKs/MacOSX12.sdk
```

**Comment by cho-m** [comment]
I have a feeling if we were able to `xcode-select` CLT then it would avoid the Xcode.app headers, but that requires sudo and won't work in our CI.

It looks like Homebrew does set correct `HOMEBREW_SYSROOT` & `HOMEBREW_DEVELOPER_DIR` which should allow CLT to be picked up during build assuming commands use our shared environment.

I'm guessing there are some build steps happen without environment variables (`SYSROOT` & `DEVELOPER_DIR`) set causing build to default to `xcode-select`ed path.

Still have no idea how to resolve this. I've tried setting the variables but I think Homebrew's environment may be removing them. Maybe can try to pass CLT info another way.

**Comment by wickles** [comment]
I'll try to spend more time looking into this but I think it will need additional support from upstream. 

For now I think the xcode dependency could be made conditional on the OS. I can make a quick PR and see how it goes.

**Comment by wickles** [comment]
Not resolved/stale.

**Comment by cho-m** [comment]
Modifying upstream's build script works (#135719) but new ARM failures seem to be due to a change elsewhere in brew as failures can be reproduced by building current formula locally.

I did see `rootcling` getting resulting in killed 9. Did also see some `codesign` complaints. One reason for this in another formula was from RPATH rewrites, but haven't had chance to experiment if that could be root cause.

**Comment by Axel-Naumann** [comment]
Can we from root-project help? For instance by looking at the error with ACLiC? You're welcome to discuss with us [here](https://mattermost.web.cern.ch/root/channels/town-square) for low latency progress!

**Comment by wickles** [comment]
@Axel-Naumann whatever you could do to help here would be appreciated. Thanks

**Comment by Axel-Naumann** [comment]
@wickles happy to help - can you share an error message or something you want me to look into?

We currently build the ROOT modules with a certain SDK, but at least for ACLiC we reduce it to the generic `MacOSX.sdk` without SDK version.
