### ISSUE TITLE
Error updating apache-spark on OSX 10.12.4

### ISSUE THREAD

**Issue by gerrymiller** [Homebrew/homebrew-core#13597]
# Please always follow these steps:
- [X] Confirmed this is a problem with `brew install`ing one, specific formula and not every time you run `brew`? If it's a general `brew` problem please file this issue at https://github.com/Homebrew/brew/issues/new. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/caskroom/homebrew-cask/new
- [X] Ran `brew update` and retried your prior step?
- [X] Ran `brew doctor`, fixed all issues and retried your prior step?
- [X] Ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [X] If `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

**Please note we may immediately close your issue without comment if you delete or do not fill out the issue checklist and provide ALL the requested information.**

To help us debug your issue please explain:
- What you were trying to do (and why)
Simple `brew update` / `brew upgrade cycle.`

- What happened (include command output)
```
| => brew upgrade
Updating Homebrew...
==> Upgrading 9 outdated packages, with result:
apache-spark 2.1.1, awscli 1.11.85, dnscrypt-proxy 1.9.5, docker 17.05.0, freetype 2.8, git 2.13.0, glib 2.52.2, node 7.10.0, thefuck 3.18
==> Upgrading apache-spark 
==> Using the sandbox
==> Downloading https://www.apache.org/dyn/closer.lua?path=spark/spark-2.1.1/spark-2.1.1-bin-hadoop2.7.tgz
Already downloaded: /Users/gerry/Library/Caches/Homebrew/apache-spark-2.1.1.tgz
Error: cannot load such file -- find
Please report this bug:
  http://docs.brew.sh/Troubleshooting.html
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/pathname.rb:542:in `find'
/usr/local/Homebrew/Library/Homebrew/download_strategy.rb:50:in `each'
/usr/local/Homebrew/Library/Homebrew/download_strategy.rb:50:in `select'
/usr/local/Homebrew/Library/Homebrew/download_strategy.rb:50:in `source_modified_time'
/usr/local/Homebrew/Library/Homebrew/resource.rb:96:in `block in unpack'
/usr/local/Homebrew/Library/Homebrew/extend/fileutils.rb:14:in `block in mktemp'
/usr/local/Homebrew/Library/Homebrew/extend/fileutils.rb:74:in `block in run'
/usr/local/Homebrew/Library/Homebrew/extend/fileutils.rb:74:in `chdir'
/usr/local/Homebrew/Library/Homebrew/extend/fileutils.rb:74:in `run'
/usr/local/Homebrew/Library/Homebrew/extend/fileutils.rb:13:in `mktemp'
/usr/local/Homebrew/Library/Homebrew/resource.rb:94:in `unpack'
/usr/local/Homebrew/Library/Homebrew/resource.rb:86:in `stage'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1936:in `stage'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1143:in `brew'
/usr/local/Homebrew/Library/Homebrew/build.rb:112:in `install'
/usr/local/Homebrew/Library/Homebrew/build.rb:189:in `<main>'

| => brew config
HOMEBREW_VERSION: 1.2.0-90-gea8be174f
ORIGIN: https://github.com/Homebrew/brew.git
HEAD: ea8be174f6009bc9bdec67b13ca501b5b83fc4b8
Last commit: 14 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 91085c41c049864a0841505d3e1a1efc4c936987
Core tap last commit: 9 hours ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_REPOSITORY: /usr/local/Homebrew
HOMEBREW_CELLAR: /usr/local/Cellar
HOMEBREW_BOTTLE_DOMAIN: https://homebrew.bintray.com
CPU: octa-core 64-bit skylake
Homebrew Ruby: 2.0.0-p648
Clang: 8.1 build 802
Git: 2.12.2 => /usr/local/bin/git
Perl: /usr/bin/perl
Python: /usr/bin/python
Ruby: /usr/bin/ruby => /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin/ruby
Java: 1.8.0_45
macOS: 10.12.4-x86_64
Xcode: 8.3.2
CLT: 8.3.2.0.1.1492020469
X11: N/A

| => brew gist-logs apache-spark
Error: No logs.

______________________________
| ~ @ Gerry's MacBook (gerry) 
| => brew doctor
Your system is ready to brew.
```

- What you expected to happen
A successful update.

- Step-by-step reproduction instructions (by running `brew install` commands)
```
brew update
brew upgrade
```

# New Formulae
To get a new formula into Homebrew please file a [Pull Request](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md).

**Comment by fxcoudert** [comment]
Can you try to manually remove the file that causes the problem (`/Users/gerry/Library/Caches/Homebrew/apache-spark-2.1.1.tgz`)? If that doesn't work, `brew cleanup -s`? And if all this fails, remove the whole cache directory `/Users/gerry/Library/Caches/Homebrew`.

**Comment by gerrymiller** [comment]
Thanks for the reply. Unfortunately, none of this worked. I ended up
uninstalling apache-spark as it was blocking the upgrade of subsequent
packages, but even a new install failed to get this package reinstalled.

What else can I send to help diagnose the problem?

**Comment by fxcoudert** [comment]
Can you post somewhere the output of `tar xfz ~/Library/Caches/Homebrew/apache-spark-2.1.1.tgz`?

**Comment by gerrymiller** [comment]
Here is the output via `ls`: 

```
| => ls spark-2.1.1-bin-hadoop2.7/
total 56
-rw-r--r--    1 gerry  staff    17K Apr 25 19:02 LICENSE
-rw-r--r--    1 gerry  staff    24K Apr 25 19:02 NOTICE
drwxr-xr-x    3 gerry  staff   102B Apr 25 19:02 R/
-rw-r--r--    1 gerry  staff   3.7K Apr 25 19:02 README.md
-rw-r--r--    1 gerry  staff   128B Apr 25 19:02 RELEASE
drwxr-xr-x   25 gerry  staff   850B Apr 25 19:02 bin/
drwxr-xr-x    9 gerry  staff   306B Apr 25 19:02 conf/
drwxr-xr-x    5 gerry  staff   170B Apr 25 19:02 data/
drwxr-xr-x    4 gerry  staff   136B Apr 25 19:02 examples/
drwxr-xr-x  209 gerry  staff   6.9K Apr 25 19:02 jars/
drwxr-xr-x   38 gerry  staff   1.3K Apr 25 19:02 licenses/
drwxr-xr-x   16 gerry  staff   544B Apr 25 19:02 python/
drwxr-xr-x   24 gerry  staff   816B Apr 25 19:02 sbin/
drwxr-xr-x    3 gerry  staff   102B Apr 25 19:02 yarn/
```

If you want the actual files, I zipped them up [here](https://drive.google.com/file/d/0B4liVmyaJDfXWEQtQlFzZDlFdlU/view?usp=sharing).

**Comment by fxcoudert** [comment]
But no error using `tar`? It seems to be a Ruby issue with unpacking the sources…

**Comment by gerrymiller** [comment]
No error with tar.
