### ISSUE TITLE
Upgrading tcl-tk 8.6.13_4 -> 8.6.13_5 gives "Error: Parameter 'old'"

### ISSUE THREAD

**Issue by CONSULitAS** [Homebrew/homebrew-core#141982]
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

```shell
~ brew config && brew doctor
HOMEBREW_VERSION: 4.1.10-31-g96e61c5
ORIGIN: https://github.com/Homebrew/brew
HEAD: 96e61c5ba5f53b807dab4f36827176344ad9a662
Last commit: 48 minutes ago
Core tap origin: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 17c8fb56f0ed5b084b58c2fc2a36130926ef0518
Core tap last commit: 18 minutes ago
Core tap branch: master
Core tap JSON: 11 Sep 14:33 UTC
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CASK_OPTS: []
HOMEBREW_DISPLAY: /private/tmp/com.apple.launchd.FshD6thMZg/org.xquartz:0
HOMEBREW_MAKE_JOBS: 4
HOMEBREW_SORBET_RUNTIME: set
Homebrew Ruby: 2.6.10 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: quad-core 64-bit haswell
Clang: 14.0.0 build 1400
Git: 2.37.1 => /Applications/Xcode.app/Contents/Developer/usr/bin/git
Curl: 8.1.2 => /usr/bin/curl
macOS: 12.6.8-x86_64
CLT: 14.2.0.0.1.1668646533
Xcode: 14.2
Your system is ready to brew.
➜  ~ brew config && brew doctor
HOMEBREW_VERSION: 4.1.10-31-g96e61c5
ORIGIN: https://github.com/Homebrew/brew
HEAD: 96e61c5ba5f53b807dab4f36827176344ad9a662
Last commit: 49 minutes ago
Core tap origin: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 17c8fb56f0ed5b084b58c2fc2a36130926ef0518
Core tap last commit: 19 minutes ago
Core tap branch: master
Core tap JSON: 11 Sep 14:33 UTC
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CASK_OPTS: []
HOMEBREW_DISPLAY: /private/tmp/com.apple.launchd.FshD6thMZg/org.xquartz:0
HOMEBREW_MAKE_JOBS: 4
HOMEBREW_SORBET_RUNTIME: set
Homebrew Ruby: 2.6.10 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: quad-core 64-bit haswell
Clang: 14.0.0 build 1400
Git: 2.37.1 => /Applications/Xcode.app/Contents/Developer/usr/bin/git
Curl: 8.1.2 => /usr/bin/curl
macOS: 12.6.8-x86_64
CLT: 14.2.0.0.1.1668646533
Xcode: 14.2
Your system is ready to brew.
```

### Verification

- [X] My "`brew doctor` output" says `Your system is ready to brew.` and am still able to reproduce my issue.
- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.
- [X] I searched for recent similar issues at https://github.com/Homebrew/homebrew-core/issues?q=is%3Aissue and found no duplicates.

### What were you trying to do (and why)?

`brew upgrade`, regular system cleanup

### What happened (include all command output)?

~ brew upgrade                                        
==> Upgrading 6 outdated packages:
tcl-tk 8.6.13_4 -> 8.6.13_5
libimagequant 4.2.0 -> 4.2.1
unbound 1.17.1_1 -> 1.18.0_1
jq 1.6 -> 1.7
sdl2 2.28.2 -> 2.28.3
qpdf 11.5.0 -> 11.6.1
==> Downloading https://ghcr.io/v2/homebrew/core/tcl-tk/manifests/8.6.13_5
Already downloaded: /Users/hi345gr/Library/Caches/Homebrew/downloads/37d4c98d33cbcc1d4c78fd424a96623554b669eca5da2698a376d9b993fd1a86--tcl-tk-8.6.13_5.bottle_manifest.json
==> Fetching tcl-tk
==> Downloading https://ghcr.io/v2/homebrew/core/tcl-tk/blobs/sha256:72212f6d3cd1874634f6c320f02b50f34f296bd30a26d4db3063bd354d9b15a0
Already downloaded: /Users/hi345gr/Library/Caches/Homebrew/downloads/139153dea4c4a3e80291d99b4f9dfeb90a79789a67567ea8186d071141747fee--tcl-tk--8.6.13_5.monterey.bottle.tar.gz
==> Downloading https://ghcr.io/v2/homebrew/core/libimagequant/manifests/4.2.1
Already downloaded: /Users/hi345gr/Library/Caches/Homebrew/downloads/c09ac0912231aea89312e511e6ea366c2bbec06c77c865dc5c6a7f9d04bf7879--libimagequant-4.2.1.bottle_manifest.json
==> Fetching libimagequant
==> Downloading https://ghcr.io/v2/homebrew/core/libimagequant/blobs/sha256:43edd7ca2e6e5608ca020d728fe5186fdd36105eb47af4ba6c7ec03fd37a0f9f
Already downloaded: /Users/hi345gr/Library/Caches/Homebrew/downloads/fa2ab1aa1cd659a909f442156daefce1c6f959aeb0f562465692a90fa1d08146--libimagequant--4.2.1.monterey.bottle.tar.gz
==> Downloading https://ghcr.io/v2/homebrew/core/unbound/manifests/1.18.0_1
Already downloaded: /Users/hi345gr/Library/Caches/Homebrew/downloads/2be2c3b3f225d8443899e58a9d758a6083e106ff6447128e93d24c37999dc86f--unbound-1.18.0_1.bottle_manifest.json
==> Fetching unbound
==> Downloading https://ghcr.io/v2/homebrew/core/unbound/blobs/sha256:eef12398b6ff2e7296a6d4f1ce9b8927b7b850d307ce6347f81558a2a523a378
Already downloaded: /Users/hi345gr/Library/Caches/Homebrew/downloads/5c681cf3512de8b3b1e73ef85b25c1ebf6ca1e69a4640f4cc650e2110706ef55--unbound--1.18.0_1.monterey.bottle.tar.gz
==> Downloading https://ghcr.io/v2/homebrew/core/jq/manifests/1.7
Already downloaded: /Users/hi345gr/Library/Caches/Homebrew/downloads/f58ea096b48ef3cd8719cb0ec4581f6929b3c5fa4340fd648205306f0e6fab49--jq-1.7.bottle_manifest.json
==> Fetching jq
==> Downloading https://ghcr.io/v2/homebrew/core/jq/blobs/sha256:748e1d8825d2961e082d412583e6e7b6e60ad75408325e976516c0db266720fe
Already downloaded: /Users/hi345gr/Library/Caches/Homebrew/downloads/b3e872af7c3fec2f7607c9d2c6e7f282f5d8ffa9b3dc1902d20e2e1c9684ff1a--jq--1.7.monterey.bottle.tar.gz
==> Downloading https://ghcr.io/v2/homebrew/core/sdl2/manifests/2.28.3
Already downloaded: /Users/hi345gr/Library/Caches/Homebrew/downloads/da57ea306285b8a33f885705d6023efa4bd9d55083d1da1df6af787aeece6c5b--sdl2-2.28.3.bottle_manifest.json
==> Fetching sdl2
==> Downloading https://ghcr.io/v2/homebrew/core/sdl2/blobs/sha256:63d2c2dab020fc0cbd13c815883108174eba3d394220724ae4baa561266a2e1e
Already downloaded: /Users/hi345gr/Library/Caches/Homebrew/downloads/8d2ce3b5bc15e2ab7b5fdec40a677fda4de568b4a695693018c2412650499236--sdl2--2.28.3.monterey.bottle.tar.gz
==> Downloading https://ghcr.io/v2/homebrew/core/qpdf/manifests/11.6.1
Already downloaded: /Users/hi345gr/Library/Caches/Homebrew/downloads/a85ffa23e5c69be01ba8f8fc9801511854db9794fde07d03a42ab6bbfd54e581--qpdf-11.6.1.bottle_manifest.json
==> Fetching qpdf
==> Downloading https://ghcr.io/v2/homebrew/core/qpdf/blobs/sha256:8fe66e87afff15f2f36a4ea6e6b262264a4fb30d32f1479f90eae4efb3e84cad
Already downloaded: /Users/hi345gr/Library/Caches/Homebrew/downloads/78946bedd3376ddbf7ac131930ac233e6919fa034b2c3d48c0ebd1436160cc5e--qpdf--11.6.1.monterey.bottle.tar.gz
==> Upgrading tcl-tk
  8.6.13_4 -> 8.6.13_5 

==> Pouring tcl-tk--8.6.13_5.monterey.bottle.tar.gz
Error: Parameter 'old': Expected type Pathname, got type String with value "@@HOMEBREW_PREFIX@@/opt/openssl@3/lib"
Caller: /usr/local/Homebrew/Library/Homebrew/extend/os/mac/keg_relocate.rb:41
Definition: /usr/local/Homebrew/Library/Homebrew/os/mac/keg.rb:40
Please report this issue:
  https://docs.brew.sh/Troubleshooting
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/sorbet-runtime-0.5.10461/lib/types/configuration.rb:296:in `call_validation_error_handler_default'
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/sorbet-runtime-0.5.10461/lib/types/configuration.rb:303:in `call_validation_error_handler'
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/sorbet-runtime-0.5.10461/lib/types/private/methods/call_validation.rb:187:in `report_error'
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/sorbet-runtime-0.5.10461/lib/types/private/methods/call_validation.rb:116:in `block in validate_call'
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/sorbet-runtime-0.5.10461/lib/types/private/methods/signature.rb:201:in `each_args_value_type'
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/sorbet-runtime-0.5.10461/lib/types/private/methods/call_validation.rb:113:in `validate_call'
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/sorbet-runtime-0.5.10461/lib/types/private/methods/_methods.rb:270:in `block in _on_method_added'
/usr/local/Homebrew/Library/Homebrew/extend/os/mac/keg_relocate.rb:41:in `block (3 levels) in relocate_dynamic_linkage'
/usr/local/Homebrew/Library/Homebrew/extend/os/mac/keg_relocate.rb:138:in `each'
/usr/local/Homebrew/Library/Homebrew/extend/os/mac/keg_relocate.rb:138:in `each_linkage_for'
/usr/local/Homebrew/Library/Homebrew/extend/os/mac/keg_relocate.rb:39:in `block (2 levels) in relocate_dynamic_linkage'
/usr/local/Homebrew/Library/Homebrew/extend/pathname.rb:337:in `ensure_writable'
/usr/local/Homebrew/Library/Homebrew/extend/os/mac/keg_relocate.rb:23:in `block in relocate_dynamic_linkage'
/usr/local/Homebrew/Library/Homebrew/extend/os/mac/keg_relocate.rb:22:in `each'
/usr/local/Homebrew/Library/Homebrew/extend/os/mac/keg_relocate.rb:22:in `relocate_dynamic_linkage'
/usr/local/Homebrew/Library/Homebrew/keg_relocate.rb:130:in `replace_placeholders_with_locations'
/usr/local/Homebrew/Library/Homebrew/formula_installer.rb:1287:in `pour'
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/sorbet-runtime-0.5.10461/lib/types/private/methods/call_validation.rb:157:in `call'
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/sorbet-runtime-0.5.10461/lib/types/private/methods/call_validation.rb:157:in `validate_call'
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/sorbet-runtime-0.5.10461/lib/types/private/methods/_methods.rb:270:in `block in _on_method_added'
/usr/local/Homebrew/Library/Homebrew/formula_installer.rb:437:in `install'
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/sorbet-runtime-0.5.10461/lib/types/private/methods/call_validation.rb:157:in `call'
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/sorbet-runtime-0.5.10461/lib/types/private/methods/call_validation.rb:157:in `validate_call'
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/sorbet-runtime-0.5.10461/lib/types/private/methods/_methods.rb:270:in `block in _on_method_added'
/usr/local/Homebrew/Library/Homebrew/upgrade.rb:218:in `install_formula'
/usr/local/Homebrew/Library/Homebrew/upgrade.rb:191:in `upgrade_formula'
/usr/local/Homebrew/Library/Homebrew/upgrade.rb:101:in `block in upgrade_formulae'
/usr/local/Homebrew/Library/Homebrew/upgrade.rb:100:in `each'
/usr/local/Homebrew/Library/Homebrew/upgrade.rb:100:in `upgrade_formulae'
/usr/local/Homebrew/Library/Homebrew/cmd/upgrade.rb:214:in `upgrade_outdated_formulae'
/usr/local/Homebrew/Library/Homebrew/cmd/upgrade.rb:136:in `upgrade'
/usr/local/Homebrew/Library/Homebrew/brew.rb:94:in `<main>'

### What did you expect to happen?

no error 

```
Error: Parameter 'old': Expected type Pathname, got type String with value "@@HOMEBREW_PREFIX@@/opt/openssl@3/lib"
```

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
brew doctor
brew update
brew upgrade
```

**Comment by SMillerDev** [comment]
Duplicate of https://github.com/Homebrew/brew/issues/15990

**Comment by CONSULitAS** [comment]
@SMillerDev 

Thanks for the extremely quick reply.

#15992 fixed it indeed. Awesome!  🎉🎉🎉🎉🎉🎉
