### ISSUE TITLE
syncthing: does not start at login-time

### ISSUE THREAD

**Issue by keltia** [Homebrew/homebrew-core#143158]
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

```shell
❯ brew gist-logs syncthing
Error: No logs.
```
brew config
```
HOMEBREW_VERSION: 4.1.11-36-g184efd9
ORIGIN: https://github.com/Homebrew/brew
HEAD: 184efd9eabcb116ffa244a9ccaeeff39eee1ece2
Last commit: 30 hours ago
Core tap origin: https://github.com/Homebrew/homebrew-core
Core tap HEAD: f21b9357c0b14a5139b4e730fbc0e1592216b969
Core tap last commit: 3 weeks ago
Core tap branch: master
Core tap JSON: 16 Sep 13:15 UTC
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_CURLRC: yes
HOMEBREW_DISPLAY: :0.0
HOMEBREW_EDITOR: vim
HOMEBREW_FORCE_BREWED_CURL: set
HOMEBREW_GITHUB_API_TOKEN: set
HOMEBREW_MAKE_JOBS: 10
HOMEBREW_NO_ANALYTICS: set
HOMEBREW_SORBET_RUNTIME: set
Homebrew Ruby: 2.6.10 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: 10-core 64-bit arm_firestorm_icestorm
Clang: 14.0.3 build 1403
Git: 2.42.0 => /opt/homebrew/bin/git
Curl: 8.2.1 => /opt/homebrew/opt/curl/bin/curl
macOS: 13.3.1-arm64
CLT: 14.3.0.0.1.1679647830
Xcode: 14.3
Rosetta 2: false
```
```
❯ brew doctor
Your system is ready to brew.
```

### Verification

- [X] My "`brew doctor` output" says `Your system is ready to brew.` and am still able to reproduce my issue.
- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.
- [X] I searched for recent similar issues at https://github.com/Homebrew/homebrew-core/issues?q=is%3Aissue and found no duplicates.

### What were you trying to do (and why)?

Just trying to use synchthing, it was perfectly running for some time and stopped, I don't know when.

### What happened (include all command output)?

/opt/homebrew/var/log/syncthing.log
```
$HOME is not defined
panic: Failed to get user home dir

goroutine 1 [running]:
github.com/syncthing/syncthing/lib/locations.userHomeDir()
        github.com/syncthing/syncthing/lib/locations/locations.go:228 +0x80
github.com/syncthing/syncthing/lib/locations.init.0()
        github.com/syncthing/syncthing/lib/locations/locations.go:56 +0x20
```
adding the HOME variable in the launch file or "--home /Users/roberto" did not work either.

### What did you expect to happen?

synchting running like it was months ago.

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
brew install syncthing
brew services start syncthing
```

**Comment by keltia** [comment]
BTW if I run `/opt/homebrew/.../syncthing` itr does work of course but that's not the point :)
