### ISSUE TITLE
pypy installation crashes in postinstall

### ISSUE THREAD

**Issue by jerzyk** [Homebrew/homebrew-core#14409]
error:
```
Traceback (most recent call last):
  File "setup.py", line 92, in <module>
    cmdclass={'test': PyTest},
  File "/usr/local/Cellar/pypy/5.8.0/libexec/lib-python/2.7/distutils/core.py", line 111, in setup
    _setup_distribution = dist = klass(attrs)
  File "/usr/local/Cellar/pypy/5.8.0/libexec/site-packages/distribute-0.6.40-py2.7.egg/setuptools/dist.py", line 225, in __init__
    _Distribution.__init__(self,attrs)
  File "/usr/local/Cellar/pypy/5.8.0/libexec/lib-python/2.7/distutils/dist.py", line 287, in __init__
    self.finalize_options()
  File "/usr/local/Cellar/pypy/5.8.0/libexec/site-packages/distribute-0.6.40-py2.7.egg/setuptools/dist.py", line 258, in finalize_options
    ep.load()(self, ep.name, value)
  File "/usr/local/Cellar/pypy/5.8.0/libexec/site-packages/distribute-0.6.40-py2.7.egg/pkg_resources.py", line 2036, in load
    raise ImportError("%r has no %r attribute" % (entry,attr))
ImportError: <module 'setuptools.dist' from '/usr/local/Cellar/pypy/5.8.0/libexec/site-packages/distribute-0.6.40-py2.7.egg/setuptools/dist.pyc'> has no 'check_specifier' attribute
```

https://gist.github.com/jerzyk/c724c015dc0cd63cb543e9fa579642b8

**Comment by ilovezfs** [comment]
I cannot reproduce this failure.
