### ISSUE TITLE
`ModuleNotFoundError` when using `awsume`

### ISSUE THREAD

**Issue by marcfrederick** [Homebrew/homebrew-core#151641]
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

```shell
$ brew gist-logs awsume
Error: No logs.

$ brew config
HOMEBREW_VERSION: 4.1.16-9-gab16b59
ORIGIN: https://github.com/Homebrew/brew
HEAD: ab16b59ee73ec799d87f882d2e4351cb52626f83
Last commit: 7 hours ago
Core tap JSON: 18 Oct 09:57 UTC
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_CASK_OPTS: ["--require-sha"]
HOMEBREW_EDITOR: code
HOMEBREW_MAKE_JOBS: 10
HOMEBREW_NO_ANALYTICS: set
HOMEBREW_NO_INSECURE_REDIRECT: set
HOMEBREW_SORBET_RUNTIME: set
Homebrew Ruby: 2.6.10 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: 10-core 64-bit arm_firestorm_icestorm
Clang: 15.0.0 build 1500
Git: 2.39.3 => /Library/Developer/CommandLineTools/usr/bin/git
Curl: 8.1.2 => /usr/bin/curl
macOS: 14.0-arm64
CLT: 15.0.0.0.1.1694021235
Xcode: N/A
Rosetta 2: false

$ brew doctor
Your system is ready to brew.
```

### Verification

- [X] My "`brew doctor` output" says `Your system is ready to brew.` and am still able to reproduce my issue.
- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.
- [X] I searched for recent similar issues at https://github.com/Homebrew/homebrew-core/issues?q=is%3Aissue and found no duplicates.

### What were you trying to do (and why)?

Use the `awsume` formula in any way.

### What happened (include all command output)?

The `awsume` command fails with a `ModuleNotFoundError`.
```
$ awsume --help
Traceback (most recent call last):
  File "/opt/homebrew/bin/awsumepy", line 5, in <module>
    from awsume.awsumepy.main import main
  File "/opt/homebrew/Cellar/awsume/4.5.3_3/libexec/lib/python3.12/site-packages/awsume/awsumepy/__init__.py", line 1, in <module>
    from . import app
  File "/opt/homebrew/Cellar/awsume/4.5.3_3/libexec/lib/python3.12/site-packages/awsume/awsumepy/app.py", line 12, in <module>
    from . lib.autoawsume import create_autoawsume_profile
  File "/opt/homebrew/Cellar/awsume/4.5.3_3/libexec/lib/python3.12/site-packages/awsume/awsumepy/lib/__init__.py", line 1, in <module>
    from . import aws_files
  File "/opt/homebrew/Cellar/awsume/4.5.3_3/libexec/lib/python3.12/site-packages/awsume/awsumepy/lib/aws_files.py", line 9, in <module>
    from . safe_print import safe_print
  File "/opt/homebrew/Cellar/awsume/4.5.3_3/libexec/lib/python3.12/site-packages/awsume/awsumepy/lib/safe_print.py", line 5, in <module>
    import yaml
ModuleNotFoundError: No module named 'yaml'
```

### What did you expect to happen?

The binary to work, without throwing errors due to missing dependencies.

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
brew install awsume
awsume --help
```

**Comment by marcfrederick** [comment]
Closing this, I've managed to resolve the issue by running `brew reinstall pyyaml`.
