### ISSUE TITLE
Module named 'idna' missing in esphome 2023.10.6 

### ISSUE THREAD

**Issue by JL-EU** [Homebrew/homebrew-core#153593]
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

```shell
HOMEBREW_VERSION: 4.1.19
ORIGIN: https://github.com/Homebrew/brew
HEAD: 7f745d04d90eaec76c8d5830d6ce6a0d7db888b3
Last commit: 2 days ago
Core tap JSON: 07 Nov 20:42 UTC
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_MAKE_JOBS: 8
Homebrew Ruby: 2.6.10 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: octa-core 64-bit arm_blizzard_avalanche
Clang: 15.0.0 build 1500
Git: 2.39.3 => /Applications/Xcode.app/Contents/Developer/usr/bin/git
Curl: 8.1.2 => /usr/bin/curl
macOS: 13.6-arm64
CLT: 15.0.0.0.1.1694021235
Xcode: 15.0.1
Rosetta 2: false
```

### Verification

- [X] My "`brew doctor` output" says `Your system is ready to brew.` and am still able to reproduce my issue.
- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.
- [X] I searched for recent similar issues at https://github.com/Homebrew/homebrew-core/issues?q=is%3Aissue and found no duplicates.

### What were you trying to do (and why)?

I can't run esphome and get the following error when : ModuleNotFoundError: No module named 'idna'

https://github.com/Homebrew/homebrew-core/commits/e2bba732d6a3f5289c7357ce5a3ffa8c909aa61a/Formula/e/esphome.rb

esphome/2023.10.6

### What happened (include all command output)?

Traceback (most recent call last):
File "/opt/homebrew/bin/esphome", line 8, in 
sys.exit(main())
^^^^^^
File "/opt/homebrew/Cellar/esphome/2023.10.6/libexec/lib/python3.12/site-packages/esphome/main.py", line 1036, in main
return run_esphome(sys.argv)
^^^^^^^^^^^^^^^^^^^^^
File "/opt/homebrew/Cellar/esphome/2023.10.6/libexec/lib/python3.12/site-packages/esphome/main.py", line 1023, in run_esphome
rc = POST_CONFIG_ACTIONS[args.command](args, config)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/opt/homebrew/Cellar/esphome/2023.10.6/libexec/lib/python3.12/site-packages/esphome/main.py", line 409, in command_compile
exit_code = compile_program(args, config)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/opt/homebrew/Cellar/esphome/2023.10.6/libexec/lib/python3.12/site-packages/esphome/main.py", line 216, in compile_program
rc = platformio_api.run_compile(config, CORE.verbose)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/opt/homebrew/Cellar/esphome/2023.10.6/libexec/lib/python3.12/site-packages/esphome/platformio_api.py", line 108, in run_compile
return run_platformio_cli_run(config, verbose, *args)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/opt/homebrew/Cellar/esphome/2023.10.6/libexec/lib/python3.12/site-packages/esphome/platformio_api.py", line 101, in run_platformio_cli_run
return run_platformio_cli(*command, **kwargs)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/opt/homebrew/Cellar/esphome/2023.10.6/libexec/lib/python3.12/site-packages/esphome/platformio_api.py", line 90, in run_platformio_cli
import platformio.main
File "/opt/homebrew/opt/platformio/libexec/lib/python3.12/site-packages/platformio/main.py", line 21, in 
from platformio import version, exception, maintenance
File "/opt/homebrew/opt/platformio/libexec/lib/python3.12/site-packages/platformio/maintenance.py", line 22, in 
from platformio import version, app, exception, fs, telemetry
File "/opt/homebrew/opt/platformio/libexec/lib/python3.12/site-packages/platformio/telemetry.py", line 25, in 
import requests
File "/opt/homebrew/opt/platformio/libexec/lib/python3.12/site-packages/requests/init.py", line 147, in 
from . import packages, utils
File "/opt/homebrew/opt/platformio/libexec/lib/python3.12/site-packages/requests/packages.py", line 16, in 
locals()[package] = import(package)
^^^^^^^^^^^^^^^^^^^
ModuleNotFoundError: No module named 'idna'

### What did you expect to happen?

esphome compile
without errors

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
brew install esphome
brew install platformio
esphome compile esp32-C3.yaml
```

**Comment by SMillerDev** [comment]
Probably https://github.com/Homebrew/brew/pull/16152

**Comment by rguca** [comment]
Workaround:
```
/opt/homebrew/Cellar/esphome/2023.10.6/libexec/bin/python -m pip install idna
```
It seems like the dependency is missing in ESPHome?

**Comment by roens** [comment]
> Workaround:
> 
> ```
> /opt/homebrew/Cellar/esphome/2023.10.6/libexec/bin/python -m pip install idna
> ```
> 
> It seems like the dependency is missing in ESPHome?

Facing this too.

I found I had to install more than just `idna`…

```shell
/opt/homebrew/Cellar/esphome/2023.10.6/libexec/bin/python -m pip install idna
# `esphome compile` then failed on missing `tabulate`, which further required `chardet` & `uvicorn`
/opt/homebrew/Cellar/esphome/2023.10.6/libexec/bin/python -m pip install tabulate chardet uvicorn
```

And now `esphome compile` succeeds… with:

```yaml
esp32:
  board: lolin_s3
  variant: esp32s3
  framework:
    type: esp-idf
    version: latest
```

**Comment by cho-m** [comment]
Currently formula is set as:
- `esphome` has pth file to `platformio` virtualenv
- `platformio` has pth file to `uvicorn` virtualenv
- `uvicorn` virtualenv has `idna` installed.

May need to check if upgrading/reinstalling corresponding dependencies (e.g. `platformio`, `uvicorn`, `python-tabulate`, etc) works.

**Comment by cho-m** [comment]
Part of issue is pth files are not recursively loaded. Not sure if any compatibility issues with newer versions of `uvicorn`/etc. but can at least fix up pth files first to fix import issue.
