### ISSUE TITLE
Imagemagick 6.9.4-4 download failed

### ISSUE THREAD

**Issue by devster31** [Homebrew/homebrew-core#1584]
Trying to `brew upgrade imagemagick`tells me:
```
$ brew upgrade imagemagick
==> Upgrading 1 outdated package, with result:
imagemagick 6.9.4-4
==> Upgrading imagemagick
==> Downloading https://dl.bintray.com/homebrew/mirror/ImageMagick-6.9.4-4.tar.xz

curl: (22) The requested URL returned error: 404 Not Found
Trying a mirror...
==> Downloading https://www.imagemagick.org/download/ImageMagick-6.9.4-4.tar.xz

curl: (22) The requested URL returned error: 404 Not Found
Error: Failed to download resource "imagemagick"
Download failed: https://www.imagemagick.org/download/ImageMagick-6.9.4-4.tar.xz
```
I believe it has been replaced with version `6.9.4-5`, also latest stable should be `ImageMagick 7.0.1-7`.

**Comment by MikeMcQuaid** [comment]
> also latest stable should be ImageMagick 7.0.1-7.

Could you try and open a pull request? [This document](https://github.com/Homebrew/brew/blob/master/share/doc/homebrew/How-To-Open-a-Homebrew-Pull-Request-(and-get-it-merged).md#how-to-open-a-homebrew-pull-request-and-get-it-merged) should help and I'm happy to walk you through anything else.

Thanks!

**Comment by devster31** [comment]
Hi, I followed the document, edited the formula and passed (I think) the `test` and `audit --strict` steps.
However it fails on the first one, `brew tests` with the following output:
```
$ brew tests
Run options: --seed 14698
##### skipped the many dots and 1 F 
Finished in 64.078727s, 13.3430 runs/s, 32.3040 assertions/s.

  1) Failure:
TapTest#test_git_variant [/usr/local/Library/Homebrew/test/test_tap.rb:157]:
Expected /years ago/
 to match "7 anni fa"
.

855 runs, 2070 assertions, 1 failures, 0 errors, 0 skips
rake aborted!
Command failed with status (1): [ruby -I"lib:/usr/local/Library/Homebrew/test" -I"/usr/local/Library/Homebrew/test/vendor/bundle/ruby/2.0.0/gems/rake-10.5.0/lib" "/usr/local/Library/Homebrew/test/vendor/bundle/ruby/2.0.0/gems/rake-10.5.0/lib/rake/rake_test_loader.rb" "/usr/local/Library/Homebrew/test/test_ARGV.rb" "/usr/local/Library/Homebrew/test/test_bash.rb" "/usr/local/Library/Homebrew/test/test_blacklist.rb" "/usr/local/Library/Homebrew/test/test_bottle_collector.rb" "/usr/local/Library/Homebrew/test/test_bottle_filename.rb" "/usr/local/Library/Homebrew/test/test_bottle_hooks.rb" "/usr/local/Library/Homebrew/test/test_bottle_tag.rb" "/usr/local/Library/Homebrew/test/test_build_environment.rb" "/usr/local/Library/Homebrew/test/test_build_options.rb" "/usr/local/Library/Homebrew/test/test_caveats.rb" "/usr/local/Library/Homebrew/test/test_checksum.rb" "/usr/local/Library/Homebrew/test/test_checksum_verification.rb" "/usr/local/Library/Homebrew/test/test_cleaner.rb" "/usr/local/Library/Homebrew/test/test_cleanup.rb" "/usr/local/Library/Homebrew/test/test_cmd_audit.rb" "/usr/local/Library/Homebrew/test/test_cmd_info.rb" "/usr/local/Library/Homebrew/test/test_commands.rb" "/usr/local/Library/Homebrew/test/test_compiler_failure.rb" "/usr/local/Library/Homebrew/test/test_compiler_selector.rb" "/usr/local/Library/Homebrew/test/test_dependencies.rb" "/usr/local/Library/Homebrew/test/test_dependency.rb" "/usr/local/Library/Homebrew/test/test_dependency_collector.rb" "/usr/local/Library/Homebrew/test/test_dependency_expansion.rb" "/usr/local/Library/Homebrew/test/test_descriptions.rb" "/usr/local/Library/Homebrew/test/test_diagnostic.rb" "/usr/local/Library/Homebrew/test/test_download_strategies.rb" "/usr/local/Library/Homebrew/test/test_ENV.rb" "/usr/local/Library/Homebrew/test/test_exceptions.rb" "/usr/local/Library/Homebrew/test/test_formula.rb" "/usr/local/Library/Homebrew/test/test_formula_installer.rb" "/usr/local/Library/Homebrew/test/test_formula_installer_bottle.rb" "/usr/local/Library/Homebrew/test/test_formula_lock.rb" "/usr/local/Library/Homebrew/test/test_formula_pin.rb" "/usr/local/Library/Homebrew/test/test_formula_spec_selection.rb" "/usr/local/Library/Homebrew/test/test_formula_support.rb" "/usr/local/Library/Homebrew/test/test_formula_validation.rb" "/usr/local/Library/Homebrew/test/test_formulary.rb" "/usr/local/Library/Homebrew/test/test_hardware.rb" "/usr/local/Library/Homebrew/test/test_inreplace.rb" "/usr/local/Library/Homebrew/test/test_integration_cmds.rb" "/usr/local/Library/Homebrew/test/test_json.rb" "/usr/local/Library/Homebrew/test/test_keg.rb" "/usr/local/Library/Homebrew/test/test_language_go.rb" "/usr/local/Library/Homebrew/test/test_language_module_requirement.rb" "/usr/local/Library/Homebrew/test/test_mach.rb" "/usr/local/Library/Homebrew/test/test_migrator.rb" "/usr/local/Library/Homebrew/test/test_mpi_requirement.rb" "/usr/local/Library/Homebrew/test/test_options.rb" "/usr/local/Library/Homebrew/test/test_patch.rb" "/usr/local/Library/Homebrew/test/test_patching.rb" "/usr/local/Library/Homebrew/test/test_pathname.rb" "/usr/local/Library/Homebrew/test/test_pkg_version.rb" "/usr/local/Library/Homebrew/test/test_requirement.rb" "/usr/local/Library/Homebrew/test/test_resource.rb" "/usr/local/Library/Homebrew/test/test_sandbox.rb" "/usr/local/Library/Homebrew/test/test_software_spec.rb" "/usr/local/Library/Homebrew/test/test_stdlib.rb" "/usr/local/Library/Homebrew/test/test_string.rb" "/usr/local/Library/Homebrew/test/test_tab.rb" "/usr/local/Library/Homebrew/test/test_tap.rb" "/usr/local/Library/Homebrew/test/test_update_report.rb" "/usr/local/Library/Homebrew/test/test_utils.rb" "/usr/local/Library/Homebrew/test/test_version_subclasses.rb" "/usr/local/Library/Homebrew/test/test_versions.rb" "/usr/local/Library/Homebrew/test/test_x11_requirement.rb" ]
/Users/devster/.gem/ruby/2.0.0/gems/bundler-1.12.5/lib/bundler/cli/exec.rb:63:in `load'
/Users/devster/.gem/ruby/2.0.0/gems/bundler-1.12.5/lib/bundler/cli/exec.rb:63:in `kernel_load'
/Users/devster/.gem/ruby/2.0.0/gems/bundler-1.12.5/lib/bundler/cli/exec.rb:24:in `run'
/Users/devster/.gem/ruby/2.0.0/gems/bundler-1.12.5/lib/bundler/cli.rb:304:in `exec'
/Users/devster/.gem/ruby/2.0.0/gems/bundler-1.12.5/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
/Users/devster/.gem/ruby/2.0.0/gems/bundler-1.12.5/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
/Users/devster/.gem/ruby/2.0.0/gems/bundler-1.12.5/lib/bundler/vendor/thor/lib/thor.rb:359:in `dispatch'
/Users/devster/.gem/ruby/2.0.0/gems/bundler-1.12.5/lib/bundler/vendor/thor/lib/thor/base.rb:440:in `start'
/Users/devster/.gem/ruby/2.0.0/gems/bundler-1.12.5/lib/bundler/cli.rb:11:in `start'
/Users/devster/.gem/ruby/2.0.0/gems/bundler-1.12.5/exe/bundle:27:in `block in <top (required)>'
/Users/devster/.gem/ruby/2.0.0/gems/bundler-1.12.5/lib/bundler/friendly_errors.rb:98:in `with_friendly_errors'
/Users/devster/.gem/ruby/2.0.0/gems/bundler-1.12.5/exe/bundle:19:in `<top (required)>'
/Users/devster/.gem/ruby/2.0.0/bin/bundle:23:in `load'
/Users/devster/.gem/ruby/2.0.0/bin/bundle:23:in `<main>'
Tasks: TOP => test
(See full trace by running task with --trace)
```
The other steps are:
```
$ brew upgrade imagemagick
==> Upgrading 1 outdated package, with result:
imagemagick 7.0.1-7
==> Upgrading imagemagick
==> Downloading https://www.imagemagick.org/download/ImageMagick-7.0.1-7.tar.xz
######################################################################## 100,0%
==> ./configure --disable-osx-universal-binary --prefix=/usr/local/Cellar/imagemagick/7.0.1-7 --disable-silent-rules --enable-shared --disable-static --with-modules --disable
==> make install
🍺  /usr/local/Cellar/imagemagick/7.0.1-7: 1,519 files, 19.5M, built in 3 minutes 3 seconds

$ brew test imagemagick
Testing imagemagick
==> Using the sandbox
==> /usr/local/Cellar/imagemagick/7.0.1-7/bin/identify /usr/local/Library/Homebrew/test/fixtures/test.png

$ brew audit --strict imagemagick
```
the full line for the config step is truncated, this are my options:
```
--with-x11 --with-webp --with-pango --with-fontconfig --with-ghostscript
```
which should generate this:
```
--disable-osx-universal-binary
--prefix=#{prefix}
--disable-dependency-tracking
--disable-silent-rules
--enable-shared
--disable-static
--with-modules
--with-webp=yes
--with-fontconfig=yes
```
Editing the formula I also noticed that the `little-cms*` dependencies are basically ignored since these are the only 2 lines containing them:
```
  depends_on "little-cms" => :optional
  depends_on "little-cms2" => :optional
```
and the `X11` and `pango` dependency is actually reversed since there are these 2 lines:
```
  depends_on "pango" => :optional
    args << "--without-pango" if build.without? "pango"
```
and:
```
  depends_on :x11 => :optional
    args << "--without-x" if build.without? "x11"
```
but the `:optional` generates a `with-x11` option if I understood the [documentation](https://github.com/Homebrew/brew/blob/master/share/doc/homebrew/Formula-Cookbook.md) correctly and therfore the second line for both would have to be `args << "--with-pango" if build.with? "pango"`.
In this case the reverse should be used since pango support is enabled by default so `depends_on "pango" => : recommended`.
