### ISSUE TITLE
Can't install Influxdb with homebrew

### ISSUE THREAD

**Issue by hanleyhansen** [Homebrew/homebrew-core#16075]
# Please always follow these steps:
- [X] Confirmed this is a problem with `brew install`ing one, specific formula (not cask) and not every time you run `brew`? If it's a general `brew` problem please file this issue at https://github.com/Homebrew/brew/issues/new. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/caskroom/homebrew-cask/new
- [X] Ran `brew update` and retried your prior step?
- [X] Ran `brew doctor`, fixed all issues and retried your prior step?
- [X] Ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [X] If `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

**Please note we will close your issue without comment if you delete or do not fill out the issue checklist and provide ALL the requested information.**

To help us debug your issue please explain:
- What you were trying to do (and why)
- What happened (include command output)
- What you expected to happen
- Step-by-step reproduction instructions (by running `brew install` commands)

# New Formulae
To get a new formula into Homebrew please file a [Pull Request](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md).

# Issue

Brew Doctor:

```bash
$ brew doctor
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry and just ignore them. Thanks!

Warning: "config" scripts exist outside your system or Homebrew directories.
`./configure` scripts often look for *-config scripts to determine if
software packages are installed, and what additional flags to use when
compiling and linking.

Having additional scripts in your path can confuse software installed via
Homebrew if the config script overrides a system or Homebrew provided
script of the same name. We found the following "config" scripts:
  /Users/hhansen/.virtualenvs/default/bin/powerline-config
  /Users/hhansen/.virtualenvs/default/bin/python-config
```

Brew config:

```bash
$ brew config
HOMEBREW_VERSION: 1.2.4
ORIGIN: https://github.com/Homebrew/brew
HEAD: b5529084906af89827f6d9befd613457a1615918
Last commit: 3 weeks ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: c1099004aee3be34949aad3ec61c9311f3c9db6c
Core tap last commit: 30 minutes ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_REPOSITORY: /usr/local/Homebrew
HOMEBREW_CELLAR: /usr/local/Cellar
HOMEBREW_BOTTLE_DOMAIN: https://homebrew.bintray.com
CPU: octa-core 64-bit dunno
Homebrew Ruby: 2.0.0-p648
Clang: 8.1 build 802
Git: 2.11.0 => /Applications/Xcode.app/Contents/Developer/usr/bin/git
Perl: /usr/bin/perl
Python: /Users/hhansen/.virtualenvs/default/bin/python
Ruby: /usr/bin/ruby => /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin/ruby
Java: N/A
macOS: 10.12.6-x86_64
Xcode: 8.3.3
CLT: 8.3.2.0.1.1492020469
X11: N/A
```

When I try to install influxdb I get the following:

```bash
$ brew install influxdb
Error: undefined method `head?' for nil:NilClass
/usr/local/Homebrew/Library/Homebrew/software_spec.rb:55:in `block in owner='
/usr/local/Homebrew/Library/Homebrew/software_spec.rb:53:in `each_value'
/usr/local/Homebrew/Library/Homebrew/software_spec.rb:53:in `owner='
/usr/local/Homebrew/Library/Homebrew/formula.rb:231:in `spec_eval'
/usr/local/Homebrew/Library/Homebrew/formula.rb:188:in `initialize'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:88:in `new'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:88:in `get_formula'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:275:in `factory'
/usr/local/Homebrew/Library/Homebrew/dependency.rb:33:in `to_formula'
/usr/local/Homebrew/Library/Homebrew/dependency.rb:96:in `block in expand'
/usr/local/Homebrew/Library/Homebrew/dependency.rb:83:in `expand'
/usr/local/Homebrew/Library/Homebrew/dependency.rb:96:in `block in expand'
/usr/local/Homebrew/Library/Homebrew/dependency.rb:83:in `expand'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1473:in `recursive_dependencies'
/usr/local/Homebrew/Library/Homebrew/requirement.rb:214:in `expand'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1479:in `recursive_requirements'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1489:in `runtime_dependencies'
/usr/local/Homebrew/Library/Homebrew/formula_installer.rb:414:in `runtime_requirements'
/usr/local/Homebrew/Library/Homebrew/formula_installer.rb:427:in `expand_requirements'
/usr/local/Homebrew/Library/Homebrew/formula_installer.rb:361:in `compute_dependencies'
/usr/local/Homebrew/Library/Homebrew/formula_installer.rb:135:in `verify_deps_exist'
/usr/local/Homebrew/Library/Homebrew/formula_installer.rb:128:in `prelude'
/usr/local/Homebrew/Library/Homebrew/cmd/install.rb:337:in `install_formula'
/usr/local/Homebrew/Library/Homebrew/cmd/install.rb:223:in `block in install'
/usr/local/Homebrew/Library/Homebrew/cmd/install.rb:221:in `each'
/usr/local/Homebrew/Library/Homebrew/cmd/install.rb:221:in `install'
/usr/local/Homebrew/Library/Homebrew/brew.rb:93:in `<main>'
```

Other formulas install fine.

**Comment by ilovezfs** [comment]
>HOMEBREW_VERSION: 1.2.4

You need to brew update to 1.2.5
