### ISSUE TITLE
Error: Stack level too deep

### ISSUE THREAD

**Issue by Pandoks** [Homebrew/homebrew-core#162159]
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

```shell
Note: `brew doctor` doesn't say `Your system is ready to brew`. I got rid of all the errors that normally output from `brew doctor` except for this.

`brew config`:

HOMEBREW_VERSION: 4.2.7-84-ga925911
ORIGIN: https://github.com/Homebrew/brew
HEAD: a92591108dfab9912182fb63f4fb01788d066b0a
Last commit: 11 hours ago
Core tap JSON: 09 Feb 00:14 UTC
Core cask tap JSON: 08 Feb 23:46 UTC
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_EDITOR: nvim
HOMEBREW_MAKE_JOBS: 10
HOMEBREW_SORBET_RUNTIME: set
Homebrew Ruby: 3.1.4 => /opt/homebrew/Library/Homebrew/vendor/portable-ruby/3.1.4/bin/ruby
CPU: 10-core 64-bit arm_firestorm_icestorm
Clang: 15.0.0 build 1500
Git: 2.43.0 => /opt/homebrew/bin/git
Curl: 8.4.0 => /usr/bin/curl
macOS: 14.2.1-arm64
CLT: 15.1.0.0.1.1700200546
Xcode: 15.2
Rosetta 2: false
```

`brew doctor`:
```
Error: stack level too deep
Please report this issue:
  https://docs.brew.sh/Troubleshooting
Warning: Removed Sorbet lines from backtrace!
Rerun with `--verbose` to see the original backtrace
/opt/homebrew/Library/Homebrew/extend/blank.rb:139:in `blank?'
/opt/homebrew/Library/Homebrew/extend/blank.rb:147:in `present?'
/opt/homebrew/Library/Homebrew/extend/blank.rb:40:in `presence'
/opt/homebrew/Library/Homebrew/formulary.rb:918:in `tap_formula_name_type'
/opt/homebrew/Library/Homebrew/formulary.rb:924:in `tap_formula_name_type'
/opt/homebrew/Library/Homebrew/formulary.rb:924:in `tap_formula_name_type'

... repeating about 4500 times ...

/opt/homebrew/Library/Homebrew/formulary.rb:924:in `tap_formula_name_type'
/opt/homebrew/Library/Homebrew/formulary.rb:924:in `tap_formula_name_type'
/opt/homebrew/Library/Homebrew/formulary.rb:924:in `tap_formula_name_type'
/opt/homebrew/Library/Homebrew/formulary.rb:936:in `tap_loader_for'
/opt/homebrew/Library/Homebrew/formulary.rb:958:in `loader_for'
/opt/homebrew/Library/Homebrew/formulary.rb:744:in `factory'
/opt/homebrew/Library/Homebrew/formulary.rb:836:in `from_keg'
/opt/homebrew/Library/Homebrew/formulary.rb:787:in `from_rack'
/opt/homebrew/Library/Homebrew/formula.rb:1973:in `block in installed'
/opt/homebrew/Library/Homebrew/formula.rb:1972:in `each'
/opt/homebrew/Library/Homebrew/formula.rb:1972:in `flat_map'
/opt/homebrew/Library/Homebrew/formula.rb:1972:in `installed'
/opt/homebrew/Library/Homebrew/diagnostic.rb:637:in `check_deprecated_disabled'
/opt/homebrew/Library/Homebrew/cmd/doctor.rb:61:in `block in doctor'
/opt/homebrew/Library/Homebrew/cmd/doctor.rb:54:in `each'
/opt/homebrew/Library/Homebrew/cmd/doctor.rb:54:in `doctor'
/opt/homebrew/Library/Homebrew/brew.rb:86:in `<main>'
```
```


### Verification

- [X] My "`brew doctor` output" says `Your system is ready to brew.` and am still able to reproduce my issue.
- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.
- [X] I searched for recent similar issues at https://github.com/Homebrew/homebrew-core/issues?q=is%3Aissue and found no duplicates.

### What were you trying to do (and why)?

Commands that fail and produce the same error as `brew doctor` (above):
- `brew autoremove`
- `brew cleanup`
- `brew doctor`
- `brew leaves`
- `brew missing`
- `brew outdated`
- `brew upgrade`
- `brew autoremove`

I'm sure I'm missing some, but you get the point. A lot of the commands just don't work.

### What happened (include all command output)?

The same output as `brew doctor shows up except for the last few lines. Here is an example with `autoremove`
`brew autoremove`:
```
Error: stack level too deep
Please report this issue:
  https://docs.brew.sh/Troubleshooting
Warning: Removed Sorbet lines from backtrace!
Rerun with `--verbose` to see the original backtrace
/opt/homebrew/Library/Homebrew/extend/blank.rb:139:in `blank?'
/opt/homebrew/Library/Homebrew/extend/blank.rb:147:in `present?'
/opt/homebrew/Library/Homebrew/extend/blank.rb:40:in `presence'
/opt/homebrew/Library/Homebrew/formulary.rb:918:in `tap_formula_name_type'
/opt/homebrew/Library/Homebrew/formulary.rb:924:in `tap_formula_name_type'
/opt/homebrew/Library/Homebrew/formulary.rb:924:in `tap_formula_name_type'

... repeating about 4500 times ...

/opt/homebrew/Library/Homebrew/formulary.rb:924:in `tap_formula_name_type'
/opt/homebrew/Library/Homebrew/formulary.rb:924:in `tap_formula_name_type'
/opt/homebrew/Library/Homebrew/formulary.rb:924:in `tap_formula_name_type'
/opt/homebrew/Library/Homebrew/formulary.rb:936:in `tap_loader_for'
/opt/homebrew/Library/Homebrew/formulary.rb:958:in `loader_for'
/opt/homebrew/Library/Homebrew/formulary.rb:744:in `factory'
/opt/homebrew/Library/Homebrew/formulary.rb:836:in `from_keg'
/opt/homebrew/Library/Homebrew/formulary.rb:787:in `from_rack'
/opt/homebrew/Library/Homebrew/formula.rb:1973:in `block in installed'
/opt/homebrew/Library/Homebrew/formula.rb:1972:in `each'
/opt/homebrew/Library/Homebrew/formula.rb:1972:in `flat_map'
/opt/homebrew/Library/Homebrew/formula.rb:1972:in `installed'
/opt/homebrew/Library/Homebrew/cleanup.rb:651:in `autoremove'
/opt/homebrew/Library/Homebrew/cmd/autoremove.rb:25:in `autoremove'
/opt/homebrew/Library/Homebrew/brew.rb:86:in `<main>'
```

### What did you expect to happen?

Run normally

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
- `brew autoremove`
- `brew cleanup`
- `brew doctor`
- `brew leaves`
- `brew missing`
- `brew outdated`
- `brew upgrade`
- `brew autoremove`
```

**Comment by SMillerDev** [comment]
I think this should be in @Homebrew/brew . If someone could move it... please?
