### ISSUE TITLE
gst-plugins-bad failed to build on 10.12.5

### ISSUE THREAD

**Issue by Jarvvski** [Homebrew/homebrew-core#16300]
- [x] Confirmed this is a problem with `brew install`ing one, specific formula (not cask) and not every time you run `brew`? If it's a general `brew` problem please file this issue at https://github.com/Homebrew/brew/issues/new. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/caskroom/homebrew-cask/new
- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed all issues and retried your prior step?
- [x] Ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [x] If `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

**Please note we will close your issue without comment if you delete or do not fill out the issue checklist and provide ALL the requested information.**

To help us debug your issue please explain:
- What you were trying to do (and why)
- What happened (include command output)
- What you expected to happen
- Step-by-step reproduction instructions (by running `brew install` commands)

Originally ran `brew upgrade` then attempted `brew upgrade gst-plugins-bad` directly.

Output:

```
brew upgrade gst-plugins-bad
==> Upgrading 1 outdated package, with result:
gst-plugins-bad 1.12.2
==> Upgrading gst-plugins-bad --with-faad2 --with-libmms --with-opus
==> Installing dependencies for gst-plugins-bad: gst-plugins-base
==> Installing gst-plugins-bad dependency: gst-plugins-base
==> Using the sandbox
==> Downloading https://gstreamer.freedesktop.org/src/gst-plugins-base/gst-plugins-base-1.12.2.tar.xz
Already downloaded: /Users/adam/Library/Caches/Homebrew/gst-plugins-base-1.12.2.tar.xz
==> ./configure --prefix=/usr/local/Cellar/gst-plugins-base/1.12.2 --enable-experimental --disable-libvisual --disable-alsa --disable-cdpara
==> make
Last 15 lines from /Users/adam/Library/Logs/Homebrew/gst-plugins-base/02.make:
  File "/usr/local/Cellar/gobject-introspection/1.52.1_1/lib/gobject-introspection/giscanner/sourcescanner.py", line 262, in parse_files
    self._parse(headers)
  File "/usr/local/Cellar/gobject-introspection/1.52.1_1/lib/gobject-introspection/giscanner/sourcescanner.py", line 305, in _parse
    self._cpp_options)
  File "/usr/local/Cellar/gobject-introspection/1.52.1_1/lib/gobject-introspection/giscanner/ccompiler.py", line 200, in preprocess
    extra_postargs=extra_postargs)
  File "/usr/local/Cellar/python/2.7.13_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/unixccompiler.py", line 113, in preprocess
    raise CompileError, msg
distutils.errors.CompileError: command 'clang' terminated by signal 10
make[5]: *** [GstVideo-1.0.gir] Error 1
make[4]: *** [all] Error 2
make[3]: *** [video] Error 2
make[2]: *** [all-recursive] Error 1
make[1]: *** [all-recursive] Error 1
make: *** [all] Error 2

READ THIS: https://docs.brew.sh/Troubleshooting.html
```

Expected it to upgrade correctly?

**brew config**
```
HOMEBREW_VERSION: 1.3.0-15-g2ad03b8
ORIGIN: https://github.com/Homebrew/brew
HEAD: 2ad03b8eb30ca69bf4b45c1cfc1ca619e49b9a04
Last commit: 9 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 6071fea8d51c9b3c5e71cfd9c2649f6732be7e0a
Core tap last commit: 17 minutes ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_REPOSITORY: /usr/local/Homebrew
HOMEBREW_CELLAR: /usr/local/Cellar
HOMEBREW_BOTTLE_DOMAIN: https://homebrew.bintray.com
CPU: octa-core 64-bit haswell
Homebrew Ruby: 2.0.0-p648
Clang: 8.1 build 802
Git: 2.13.4 => /usr/local/bin/git
Perl: /usr/local/bin/perl => /usr/local/Cellar/perl/5.26.0/bin/perl
Python: /usr/local/opt/python/libexec/bin/python => /usr/local/Cellar/python/2.7.13_1/Frameworks/Python.framework/Versions/2.7/bin/python2.7
Ruby: /Users/adam/.rbenv/shims/ruby => /Users/adam/.rbenv/versions/2.3.1/bin/ruby
Java: 1.8.0_111, 1.6.0_65-b14-468
macOS: 10.12.5-x86_64
Xcode: 8.3.3
CLT: 8.3.2.0.1.1492020469
X11: 2.7.112 => /opt/X11
```

**Brew Doctor**: reported all as fine

**Comment by fxcoudert** [comment]
It's `gst-plugins-base` which is failing to build. But it is not clear why it builds from source instead of using our prebuilt bottles.

What is the output for `brew info gst-plugins-base`?

**Comment by Jarvvski** [comment]
@fxcoudert 

**Output:**

```brew info gst-plugins-base
gst-plugins-base: stable 1.12.2 (bottled), HEAD
GStreamer plugins (well-supported, basic set)
https://gstreamer.freedesktop.org/
/usr/local/Cellar/gst-plugins-base/1.10.2 (445 files, 17.0MB) *
  Built from source on 2016-12-05 at 14:22:58 with: --with-libogg --with-theora --with-libvorbis
From: https://github.com/Homebrew/homebrew-core/blob/master/Formula/gst-plugins-base.rb
==> Dependencies
Build: pkg-config ✔
Required: gettext ✔, gstreamer ✔, gobject-introspection ✔
Recommended: orc ✔
Optional: libogg ✔, opus ✔, pango ✘, theora ✔, libvorbis ✔
==> Options
--with-libogg
	Build with libogg support
--with-libvorbis
	Build with libvorbis support
--with-opus
	Build with opus support
--with-pango
	Build with pango support
--with-theora
	Build with theora support
--without-orc
	Build without orc support
--HEAD
	Install HEAD version```

**Comment by fxcoudert** [comment]
On my local machine, `brew install gst-plugins-base --with-libogg --with-theora --with-libvorbis` finishes fine. Can you try that command? If it fails, please post the output of `brew gist-logs gst-plugins-base`

**Comment by Jarvvski** [comment]
@fxcoudert I already have a version installed, so I used that in the upgrade instead. It failed the same as before

[Here's](https://gist.github.com/Jarvvski/5fcc4f8a5acddf8d02bbfa4c093fc673) the `brew gist-logs gst-plugins-base`

**Comment by fxcoudert** [comment]
So the exact error is encountered when building `GEN      GstApp-1.0.gir`.

```
Traceback (most recent call last):
  File "/usr/local/Cellar/gobject-introspection/1.52.1_1/bin/g-ir-scanner", line 66, in <module>
    sys.exit(scanner_main(sys.argv))
  File "/usr/local/Cellar/gobject-introspection/1.52.1_1/lib/gobject-introspection/giscanner/scannermain.py", line 538, in scanner_main
    ss = create_source_scanner(options, args)
  File "/usr/local/Cellar/gobject-introspection/1.52.1_1/lib/gobject-introspection/giscanner/scannermain.py", line 446, in create_source_scanner
    ss.parse_files(filenames)
  File "/usr/local/Cellar/gobject-introspection/1.52.1_1/lib/gobject-introspection/giscanner/sourcescanner.py", line 262, in parse_files
    self._parse(headers)
  File "/usr/local/Cellar/gobject-introspection/1.52.1_1/lib/gobject-introspection/giscanner/sourcescanner.py", line 305, in _parse
    self._cpp_options)
  File "/usr/local/Cellar/gobject-introspection/1.52.1_1/lib/gobject-introspection/giscanner/ccompiler.py", line 200, in preprocess
    extra_postargs=extra_postargs)
  File "/usr/local/Cellar/python/2.7.13_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/unixccompiler.py", line 113, in preprocess
    raise CompileError, msg
distutils.errors.CompileError: command 'clang' terminated by signal 10
make[5]: *** [GstApp-1.0.gir] Error 1
```

But unfortunately I cannot reproduce it on my own system. Could you try maybe reinstalling `python` and `gobject-introspection`?

Other line of inquiry: does the problem persist if you `brew install gst-plugins-base` without the options (`--with-libogg --with-theora --with-libvorbis`) or with only some of the options?

**Comment by JCount** [comment]
@Jarvvski Specifically, I would recommend that you try using a _**bottle installation**_ of `gobject-introspection`. (if you are currently using a version built locally from source)

Similar errors have appeared in the past, and often end up leading back to a locally compiled version of `gobject-introspection`.

**Comment by Jarvvski** [comment]
@fxcoudert after removing and re-installing py2.7 and gobject-introspection the issue still occurs.

I also removed and re-installed gst-plugins-base without options. That does seem to work, however python still crashes once it reaches the next `gst-plugins-X` item. There's something going on between them all and their options it seems?

@JCount I'm using the standard bottle

**Comment by drselump14** [comment]
in my case the error is caused from missing 'gst/audio/audio.h' file.

```
Last 15 lines from /Users/dr_selump14/Library/Logs/Homebrew/gst-plugins-good/02.make:
libtool: link: /usr/bin/nm -B  .libs/libgstautodetect_la-gstautoaudiosink.o .libs/libgstautodetect_la-gstautoaudiosrc.o .libs/libgstautodetect_la-gstautodetect.o .libs/libgstau
todetect_la-gstautovideosink.o .libs/libgstautodetect_la-gstautovideosrc.o   | sed -n -e 's/^.*[         ]\([BCDEGRST][BCDEGRST]*\)[     ][      ]*_\([_A-Za-z][_A-Za-z0-9]*\)$/
\1 _\2 \2/p' | sed '/ __gnu_lto/d' | /usr/local/Homebrew/Library/Homebrew/shims/super/sed 's/.* //' | sort | uniq > .libs/libgstautodetect.exp
gstsbcparse.c:42:10: fatal error: 'gst/audio/audio.h' file not found
#include <gst/audio/audio.h>
         ^
libtool: link: /usr/bin/grep -E -e "^_*gst_plugin_.*" ".libs/libgstautodetect.exp" > ".libs/libgstautodetect.expT"
libtool: link: mv -f ".libs/libgstautodetect.expT" ".libs/libgstautodetect.exp"
libtool: link: sed -e 's|^|_|' < .libs/libgstautodetect.exp > .libs/libgstautodetect-symbols.expsym
libtool: link: clang  -o .libs/libgstautodetect.so -bundle  .libs/libgstautodetect_la-gstautoaudiosink.o .libs/libgstautodetect_la-gstautoaudiosrc.o .libs/libgstautodetect_la-g
stautodetect.o .libs/libgstautodetect_la-gstautovideosink.o .libs/libgstautodetect_la-gstautovideosrc.o   -L/usr/local/Cellar/glib/2.52.3/lib -L/usr/local/opt/gettext/lib -L/us
r/local/Cellar/gstreamer/1.12.2/lib -lgstreamer-1.0 -lgobject-2.0 -lglib-2.0 -lintl  -g -O2 -Wl,-framework -Wl,CoreFoundation   -Wl,-exported_symbols_list,.libs/libgstautodetec
t-symbols.expsym
1 error generated.
make[3]: *** [libgstaudioparsers_la-gstsbcparse.lo] Error 1
libtool: link: ( cd ".libs" && rm -f "libgstautodetect.la" && ln -s "../libgstautodetect.la" "libgstautodetect.la" )
make[2]: *** [audioparsers] Error 2
make[2]: *** [avi] Error 2
make[1]: *** [all-recursive] Error 1
make: *** [all] Error 2
````

**Comment by ilovezfs** [comment]
@Jarvvski have you managed to fix this?

**Comment by Jarvvski** [comment]
@ilovezfs I managed to get around it by re-installing with no options. The error still persists if I try to install `gst-plugins-base` with options however

**Comment by ilovezfs** [comment]
@Jarvvski can you please check if this is still an issue now that 1.12.3 is out?

**Comment by Jarvvski** [comment]
Seems to work fine now @ilovezfs

**Comment by ilovezfs** [comment]
@Jarvvski that's good news :) I'm glad to hear this went away.
