### ISSUE TITLE
Ruby Segfault using `brew bundle install` on a fresh WSL ubuntu 22.04 wsl distro

### ISSUE THREAD

**Issue by chrisguest75** [Homebrew/homebrew-core#166575]
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

```shell
***********************************
** Brew Config
***********************************
HOMEBREW_VERSION: 4.2.13
ORIGIN: https://github.com/Homebrew/brew
HEAD: bb753a6c48575ae018d7ad925d7762d59647fff7
Last commit: 3 days ago
Core tap JSON: 19 Mar 10:29 UTC
HOMEBREW_PREFIX: /home/linuxbrew/.linuxbrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_DISPLAY: :0
HOMEBREW_MAKE_JOBS: 20
Homebrew Ruby: 3.1.4 => /home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/vendor/portable-ruby/3.1.4/bin/ruby
CPU: 20-core 64-bit unknown_0x6_0xba
Clang: N/A
Git: 2.34.1 => /bin/git
Curl: 7.81.0 => /bin/curl
Kernel: Linux 6.1.21.2-microsoft-standard-WSL2+ x86_64 GNU/Linux
OS: Ubuntu 22.04.4 LTS (jammy)
WSL: 2 (Microsoft Store)
Host glibc: 2.35
/usr/bin/gcc: 11.4.0
/usr/bin/ruby: N/A
glibc: N/A
gcc@11: N/A
gcc: N/A
xorg: N/A
***********************************
** Brew Doctor
***********************************
Your system is ready to brew.
```

### Verification

- [X] My `brew doctor` output says `Your system is ready to brew.` and am still able to reproduce my issue.
- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.
- [X] I searched for recent similar issues at https://github.com/Homebrew/homebrew-core/issues?q=is%3Aissue and found no duplicates.

### What were you trying to do (and why)?

I'm trying to provision a new WSL distro.  The distro has nothing else installed.  I do install some APT packages before.  But the crash happens randomly on different package.  Sometimes ffmpeg, sometimes wget and others.  

It really feels like some kind of scheduling issue in Ruby.  

### What happened (include all command output)?

It randomly crashes in the portable ruby.  
```
Installing wget
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/vendor/portable-ruby/3.1.4/lib/ruby/3.1.0/json/common.rb:216: [BUG] Segmentation fault at 0x0000000000000000
ruby 3.1.4p223 (2023-03-30 revision 957bb7cb81) [x86_64-linux]

-- Control frame information -----------------------------------------------
c:0020 p:---- s:0174 e:000173 CFUNC  :parse
c:0019 p:0027 s:0170 e:000169 METHOD /home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/vendor/portable-ruby/3.1.4/lib/ruby/3.1.0/json/common.rb:216
c:0018 p:0221 s:0164 e:000162 METHOD /home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/api.rb:173
c:0017 p:0571 s:0153 e:000152 METHOD /home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/api.rb:110
c:0016 p:0112 s:0134 e:000133 METHOD /home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/api/formula.rb:46
c:0015 p:0012 s:0128 e:000127 METHOD /home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/api/formula.rb:69
c:0014 p:0096 s:0123 e:000122 METHOD /home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/formulary.rb:878
c:0013 p:0009 s:0109 e:000108 BLOCK  /home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/formulary.rb:1182 [FINISH]
c:0012 p:---- s:0104 e:000103 CFUNC  :each
c:0011 p:0119 s:0100 e:000099 METHOD /home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/formulary.rb:1181
c:0010 p:0209 s:0091 e:000090 METHOD /home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/formulary.rb:963
c:0009 p:0038 s:0074 e:000073 BLOCK  /home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/cli/parser.rb:657 [FINISH]
c:0008 p:---- s:0070 e:000069 IFUNC
c:0007 p:---- s:0067 e:000066 CFUNC  :each
c:0006 p:---- s:0064 e:000063 CFUNC  :filter_map
c:0005 p:0044 s:0060 e:000059 METHOD /home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/cli/parser.rb:653
c:0004 p:0069 s:0052 e:000051 METHOD /home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/cli/parser.rb:325
c:0003 p:0005 s:0042 e:000041 METHOD /home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/cmd/install.rb:167
c:0002 p:0608 s:0020 E:0016e0 EVAL   /home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/brew.rb:86 [FINISH]
c:0001 p:0000 s:0003 E:000270 (none) [FINISH]

-- Ruby level backtrace information ----------------------------------------
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/brew.rb:86:in `<main>'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/cmd/install.rb:167:in `install'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/cli/parser.rb:325:in `parse'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/cli/parser.rb:653:in `formulae'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/cli/parser.rb:653:in `filter_map'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/cli/parser.rb:653:in `each'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/cli/parser.rb:657:in `block in formulae'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/formulary.rb:963:in `factory'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/formulary.rb:1181:in `loader_for'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/formulary.rb:1181:in `each'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/formulary.rb:1182:in `block in loader_for'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/formulary.rb:878:in `try_new'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/api/formula.rb:69:in `all_formulae'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/api/formula.rb:46:in `download_and_cache_data!'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/api.rb:110:in `fetch_json_api_file'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/api.rb:173:in `verify_and_parse_jws'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/vendor/portable-ruby/3.1.4/lib/ruby/3.1.0/json/common.rb:216:in `parse'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/vendor/portable-ruby/3.1.4/lib/ruby/3.1.0/json/common.rb:216:in `parse'

-- Machine register context ------------------------------------------------
 RIP: 0x0000556f742c7d56 RBP: 0x0000556f77e3b470 RSP: 0x00007ffe81c24e20
 RAX: 0x0000000000000005 RBX: 0x00007ffe81c24ee0 RCX: 0x3442f8c70b03293b
 RDX: 0x000000000000014f RDI: 0x0000556f750ab800 RSI: 0x000000000000000f
  R8: 0x0000000000000000  R9: 0x0000000000000040 R10: 0x0000000000000000
 R11: 0x0000000000000028 R12: 0x0000556f750ab800 R13: 0x00007f7f65576610
 R14: 0x0000556f750ab800 R15: 0x0000556f750ab810 EFL: 0x0000000000010206

-- C level backtrace information -------------------------------------------
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/vendor/portable-ruby/current/bin/ruby(0x427e83) [0x556f74451e83]
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/vendor/portable-ruby/current/bin/ruby(0x27d054) [0x556f742a7054]
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/vendor/portable-ruby/current/bin/ruby(0x39ec5d) [0x556f743c8c5d]
/lib/x86_64-linux-gnu/libc.so.6(0x7f7f68e42520) [0x7f7f68e42520]
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/vendor/portable-ruby/current/bin/ruby(0x29dd56) [0x556f742c7d56]
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/vendor/portable-ruby/current/bin/ruby(0x2a0695) [0x556f742ca695]
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/vendor/portable-ruby/current/bin/ruby(0x2a1158) [0x556f742cb158]
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/vendor/portable-ruby/current/bin/ruby(0x2a4e95) [0x556f742cee95]
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/vendor/portable-ruby/current/bin/ruby(0x2a5796) [0x556f742cf796]
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/vendor/portable-ruby/current/bin/ruby(rb_wb_protected_newobj_of+0x80) [0x556f742cf970]
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/vendor/portable-ruby/current/bin/ruby(0x3af68f) [0x556f743d968f]
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/vendor/portable-ruby/current/bin/ruby(0x3b241e) [0x556f743dc41e]
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/vendor/portable-ruby/current/bin/ruby(rb_st_update+0x22e) [0x556f743d4c3e]
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/vendor/portable-ruby/current/bin/ruby(0x3ab776) [0x556f743d5776]
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/vendor/portable-ruby/current/bin/ruby(rb_enc_interned_str+0x48) [0x556f743ee748]
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/vendor/portable-ruby/current/bin/ruby(0x187687) [0x556f741b1687]
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/vendor/portable-ruby/current/bin/ruby(0x187bed) [0x556f741b1bed]
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/vendor/portable-ruby/current/bin/ruby(0x188b39) [0x556f741b2b39]
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/vendor/portable-ruby/current/bin/ruby(0x189008) [0x556f741b3008]
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/vendor/portable-ruby/current/bin/ruby(0x189008) [0x556f741b3008]
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/vendor/portable-ruby/current/bin/ruby(0x189008) [0x556f741b3008]
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/vendor/portable-ruby/current/bin/ruby(0x189008) [0x556f741b3008]
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/vendor/portable-ruby/current/bin/ruby(0x189008) [0x556f741b3008]
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/vendor/portable-ruby/current/bin/ruby(0x188913) [0x556f741b2913]
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/vendor/portable-ruby/current/bin/ruby(0x189aa9) [0x556f741b3aa9]
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/vendor/portable-ruby/current/bin/ruby(0x40397b) [0x556f7442d97b]
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/vendor/portable-ruby/current/bin/ruby(0x40e06e) [0x556f7443806e]
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/vendor/portable-ruby/current/bin/ruby(0x410fc2) [0x556f7443afc2]
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/vendor/portable-ruby/current/bin/ruby(rb_vm_exec+0xef) [0x556f744402cf]
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/vendor/portable-ruby/current/bin/ruby(rb_yield+0x78) [0x556f74444e58]
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/vendor/portable-ruby/current/bin/ruby(rb_ary_each+0x3c) [0x556f7425870c]
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/vendor/portable-ruby/current/bin/ruby(0x40397b) [0x556f7442d97b]
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/vendor/portable-ruby/current/bin/ruby(0x40e06e) [0x556f7443806e]
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/vendor/portable-ruby/current/bin/ruby(0x411025) [0x556f7443b025]
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/vendor/portable-ruby/current/bin/ruby(rb_vm_exec+0xef) [0x556f744402cf]
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/vendor/portable-ruby/current/bin/ruby(rb_yield_values2+0x6c) [0x556f744449fc]
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/vendor/portable-ruby/current/bin/ruby(0x268752) [0x556f74292752]
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/vendor/portable-ruby/current/bin/ruby(0x40c8e1) [0x556f744368e1]
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/vendor/portable-ruby/current/bin/ruby(rb_yield+0x78) [0x556f74444e58]
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/vendor/portable-ruby/current/bin/ruby(rb_ary_each+0x3c) [0x556f7425870c]
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/vendor/portable-ruby/current/bin/ruby(0x41b52e) [0x556f7444552e]
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/vendor/portable-ruby/current/bin/ruby(0x41d53f) [0x556f7444753f]
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/vendor/portable-ruby/current/bin/ruby(0x41e52d) [0x556f7444852d]
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/vendor/portable-ruby/current/bin/ruby(0x409a0e) [0x556f74433a0e]
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/vendor/portable-ruby/current/bin/ruby(rb_block_call_kw+0x81) [0x556f74433c01]
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/vendor/portable-ruby/current/bin/ruby(rb_block_call+0xf) [0x556f74433c3f]
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/vendor/portable-ruby/current/bin/ruby(0x26965a) [0x556f7429365a]
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/vendor/portable-ruby/current/bin/ruby(0x40397b) [0x556f7442d97b]
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/vendor/portable-ruby/current/bin/ruby(0x40e06e) [0x556f7443806e]
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/vendor/portable-ruby/current/bin/ruby(0x411025) [0x556f7443b025]
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/vendor/portable-ruby/current/bin/ruby(rb_vm_exec+0xef) [0x556f744402cf]
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/vendor/portable-ruby/current/bin/ruby(0x282c9c) [0x556f742acc9c]
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/vendor/portable-ruby/current/bin/ruby(ruby_run_node+0x5a) [0x556f742b094a]
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/vendor/portable-ruby/current/bin/ruby(0x134b3f) [0x556f7415eb3f]
/lib/x86_64-linux-gnu/libc.so.6(0x7f7f68e29d90) [0x7f7f68e29d90]
/lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0x80) [0x7f7f68e29e40]
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/vendor/portable-ruby/current/bin/ruby(0x556f7415eb82) [0x556f7415eb82]

-- Other runtime information -----------------------------------------------

* Process memory map:

556f7402a000-556f74159000 r--p 00000000 08:60 46172                      /home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/vendor/portable-ruby/3.1.4/bin/ruby
556f74159000-556f74839000 r-xp 0012f000 08:60 46172                      /home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/vendor/portable-ruby/3.1.4/bin/ruby
556f74839000-556f74d87000 r--p 0080f000 08:60 46172                      /home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/vendor/portable-ruby/3.1.4/bin/ruby
556f74d87000-556f74dfd000 r--p 00d5c000 08:60 46172                      /home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/vendor/portable-ruby/3.1.4/bin/ruby
556f74dfd000-556f74e05000 rw-p 00dd2000 08:60 46172                      /home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/vendor/portable-ruby/3.1.4/bin/ruby
556f74e05000-556f74e25000 rw-p 00000000 00:00 0
556f750a7000-556f7800f000 rw-p 00000000 00:00 0                          [heap]
7f7f60aa8000-7f7f6223c000 rw-p 00000000 00:00 0
7f7f6223c000-7f7f63bb1000 rw-p 00000000 00:00 0
7f7f64000000-7f7f6421f000 r--s 00000000 08:60 6608                       /usr/lib/x86_64-linux-gnu/libc.so.6
7f7f64400000-7f7f65336000 r--s 00000000 08:60 46172                      /home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/vendor/portable-ruby/3.1.4/bin/ruby
7f7f65400000-7f7f65403000 r--p 00000000 08:60 6676                       /usr/lib/x86_64-linux-gnu/libgcc_s.so.1
7f7f65403000-7f7f6541a000 r-xp 00003000 08:60 6676                       /usr/lib/x86_64-linux-gnu/libgcc_s.so.1
7f7f6541a000-7f7f6541e000 r--p 0001a000 08:60 6676                       /usr/lib/x86_64-linux-gnu/libgcc_s.so.1
7f7f6541e000-7f7f6541f000 r--p 0001d000 08:60 6676                       /usr/lib/x86_64-linux-gnu/libgcc_s.so.1
7f7f6541f000-7f7f65420000 rw-p 0001e000 08:60 6676                       /usr/lib/x86_64-linux-gnu/libgcc_s.so.1
7f7f65420000-7f7f65650000 rw-p 00000000 00:00 0
7f7f65654000-7f7f65858000 rw-p 00000000 00:00 0
7f7f65858000-7f7f65859000 ---p 00000000 00:00 0
7f7f65859000-7f7f658fa000 rw-p 00000000 00:00 0
7f7f658fa000-7f7f658fb000 ---p 00000000 00:00 0
7f7f658fb000-7f7f6599c000 rw-p 00000000 00:00 0
7f7f6599c000-7f7f6599d000 ---p 00000000 00:00 0
7f7f6599d000-7f7f65a3e000 rw-p 00000000 00:00 0
7f7f65a3e000-7f7f65a3f000 ---p 00000000 00:00 0
7f7f65a3f000-7f7f65ae0000 rw-p 00000000 00:00 0
7f7f65ae0000-7f7f65ae1000 ---p 00000000 00:00 0
7f7f65ae1000-7f7f65b82000 rw-p 00000000 00:00 0
7f7f65b82000-7f7f65b83000 ---p 00000000 00:00 0
7f7f65b83000-7f7f65c24000 rw-p 00000000 00:00 0
7f7f65c24000-7f7f65c25000 ---p 00000000 00:00 0
7f7f65c25000-7f7f65cc6000 rw-p 00000000 00:00 0
7f7f65cc6000-7f7f65cc7000 ---p 00000000 00:00 0
7f7f65cc7000-7f7f65d68000 rw-p 00000000 00:00 0
7f7f65d68000-7f7f65d69000 ---p 00000000 00:00 0
7f7f65d69000-7f7f65e0a000 rw-p 00000000 00:00 0
7f7f65e0a000-7f7f65e0b000 ---p 00000000 00:00 0
7f7f65e0b000-7f7f65eac000 rw-p 00000000 00:00 0
7f7f65eac000-7f7f65ead000 ---p 00000000 00:00 0
7f7f65ead000-7f7f65f4e000 rw-p 00000000 00:00 0
7f7f65f4e000-7f7f65f4f000 ---p 00000000 00:00 0
7f7f65f4f000-7f7f65ff0000 rw-p 00000000 00:00 0
7f7f65ff0000-7f7f65ff1000 ---p 00000000 00:00 0
7f7f65ff1000-7f7f66092000 rw-p 00000000 00:00 0
7f7f66092000-7f7f66093000 ---p 00000000 00:00 0
7f7f66093000-7f7f66134000 rw-p 00000000 00:00 0
7f7f66134000-7f7f66135000 ---p 00000000 00:00 0
7f7f66135000-7f7f661d6000 rw-p 00000000 00:00 0
7f7f661d6000-7f7f661d7000 ---p 00000000 00:00 0
7f7f661d7000-7f7f66278000 rw-p 00000000 00:00 0
7f7f66278000-7f7f66279000 ---p 00000000 00:00 0
7f7f66279000-7f7f6631a000 rw-p 00000000 00:00 0
7f7f6631a000-7f7f6631b000 ---p 00000000 00:00 0
7f7f6631b000-7f7f663bc000 rw-p 00000000 00:00 0
7f7f663bc000-7f7f663bd000 ---p 00000000 00:00 0
7f7f663bd000-7f7f6645e000 rw-p 00000000 00:00 0
7f7f6645e000-7f7f6645f000 ---p 00000000 00:00 0
7f7f6645f000-7f7f66500000 rw-p 00000000 00:00 0
7f7f66500000-7f7f66501000 ---p 00000000 00:00 0
7f7f66501000-7f7f665a2000 rw-p 00000000 00:00 0
7f7f665a2000-7f7f665a3000 ---p 00000000 00:00 0
7f7f665a3000-7f7f66644000 rw-p 00000000 00:00 0
7f7f66644000-7f7f66645000 ---p 00000000 00:00 0
7f7f66645000-7f7f666e6000 rw-p 00000000 00:00 0
7f7f666e6000-7f7f666e7000 ---p 00000000 00:00 0
7f7f666e7000-7f7f66788000 rw-p 00000000 00:00 0
7f7f66788000-7f7f66789000 ---p 00000000 00:00 0
7f7f66789000-7f7f6682a000 rw-p 00000000 00:00 0
7f7f6682a000-7f7f6682b000 ---p 00000000 00:00 0
7f7f6682b000-7f7f668cc000 rw-p 00000000 00:00 0
7f7f668cc000-7f7f668cd000 ---p 00000000 00:00 0
7f7f668cd000-7f7f6696e000 rw-p 00000000 00:00 0
7f7f6696e000-7f7f6696f000 ---p 00000000 00:00 0
7f7f6696f000-7f7f66a10000 rw-p 00000000 00:00 0
7f7f66a10000-7f7f66a11000 ---p 00000000 00:00 0
7f7f66a11000-7f7f66ab2000 rw-p 00000000 00:00 0
7f7f66ab2000-7f7f66ab3000 ---p 00000000 00:00 0
7f7f66ab3000-7f7f66b54000 rw-p 00000000 00:00 0
7f7f66b54000-7f7f66b55000 ---p 00000000 00:00 0
7f7f66b55000-7f7f66bf6000 rw-p 00000000 00:00 0
7f7f66bf6000-7f7f66bf7000 ---p 00000000 00:00 0
7f7f66bf7000-7f7f68c98000 rw-p 00000000 00:00 0
7f7f68c9c000-7f7f68cfc000 rw-p 00000000 00:00 0
7f7f68cff000-7f7f68e00000 rw-p 00000000 00:00 0
7f7f68e00000-7f7f68e28000 r--p 00000000 08:60 6608                       /usr/lib/x86_64-linux-gnu/libc.so.6
7f7f68e28000-7f7f68fbd000 r-xp 00028000 08:60 6608                       /usr/lib/x86_64-linux-gnu/libc.so.6
7f7f68fbd000-7f7f69015000 r--p 001bd000 08:60 6608                       /usr/lib/x86_64-linux-gnu/libc.so.6
7f7f69015000-7f7f69016000 ---p 00215000 08:60 6608                       /usr/lib/x86_64-linux-gnu/libc.so.6
7f7f69016000-7f7f6901a000 r--p 00215000 08:60 6608                       /usr/lib/x86_64-linux-gnu/libc.so.6
7f7f6901a000-7f7f6901c000 rw-p 00219000 08:60 6608                       /usr/lib/x86_64-linux-gnu/libc.so.6
7f7f6901c000-7f7f69029000 rw-p 00000000 00:00 0
7f7f69030000-7f7f690c8000 rw-p 00000000 00:00 0
7f7f690c9000-7f7f69120000 r--p 00000000 08:60 2327                       /usr/lib/locale/C.utf8/LC_CTYPE
7f7f69120000-7f7f69125000 rw-p 00000000 00:00 0
7f7f69125000-7f7f69133000 r--p 00000000 08:60 6770                       /usr/lib/x86_64-linux-gnu/libm.so.6
7f7f69133000-7f7f691af000 r-xp 0000e000 08:60 6770                       /usr/lib/x86_64-linux-gnu/libm.so.6
7f7f691af000-7f7f6920a000 r--p 0008a000 08:60 6770                       /usr/lib/x86_64-linux-gnu/libm.so.6
7f7f6920a000-7f7f6920b000 r--p 000e4000 08:60 6770                       /usr/lib/x86_64-linux-gnu/libm.so.6
7f7f6920b000-7f7f6920c000 rw-p 000e5000 08:60 6770                       /usr/lib/x86_64-linux-gnu/libm.so.6
7f7f6920c000-7f7f6920d000 r--p 00000000 08:60 6638                       /usr/lib/x86_64-linux-gnu/libdl.so.2
7f7f6920d000-7f7f6920e000 r-xp 00001000 08:60 6638                       /usr/lib/x86_64-linux-gnu/libdl.so.2
7f7f6920e000-7f7f6920f000 r--p 00002000 08:60 6638                       /usr/lib/x86_64-linux-gnu/libdl.so.2
7f7f6920f000-7f7f69210000 r--p 00002000 08:60 6638                       /usr/lib/x86_64-linux-gnu/libdl.so.2
7f7f69210000-7f7f69211000 rw-p 00003000 08:60 6638                       /usr/lib/x86_64-linux-gnu/libdl.so.2
7f7f69211000-7f7f69212000 r--p 00000000 08:60 6889                       /usr/lib/x86_64-linux-gnu/librt.so.1
7f7f69212000-7f7f69213000 r-xp 00001000 08:60 6889                       /usr/lib/x86_64-linux-gnu/librt.so.1
7f7f69213000-7f7f69214000 r--p 00002000 08:60 6889                       /usr/lib/x86_64-linux-gnu/librt.so.1
7f7f69214000-7f7f69215000 r--p 00002000 08:60 6889                       /usr/lib/x86_64-linux-gnu/librt.so.1
7f7f69215000-7f7f69216000 rw-p 00003000 08:60 6889                       /usr/lib/x86_64-linux-gnu/librt.so.1
7f7f69216000-7f7f69217000 r--p 00000000 08:60 6883                       /usr/lib/x86_64-linux-gnu/libpthread.so.0
7f7f69217000-7f7f69218000 r-xp 00001000 08:60 6883                       /usr/lib/x86_64-linux-gnu/libpthread.so.0
7f7f69218000-7f7f69219000 r--p 00002000 08:60 6883                       /usr/lib/x86_64-linux-gnu/libpthread.so.0
7f7f69219000-7f7f6921a000 r--p 00002000 08:60 6883                       /usr/lib/x86_64-linux-gnu/libpthread.so.0
7f7f6921a000-7f7f6921b000 rw-p 00003000 08:60 6883                       /usr/lib/x86_64-linux-gnu/libpthread.so.0
7f7f6921b000-7f7f69222000 r--s 00000000 08:60 6379                       /usr/lib/x86_64-linux-gnu/gconv/gconv-modules.cache
7f7f69222000-7f7f69224000 rw-p 00000000 00:00 0
7f7f69224000-7f7f69226000 r--p 00000000 08:60 6412                       /usr/lib/x86_64-linux-gnu/ld-linux-x86-64.so.2
7f7f69226000-7f7f69250000 r-xp 00002000 08:60 6412                       /usr/lib/x86_64-linux-gnu/ld-linux-x86-64.so.2
7f7f69250000-7f7f6925b000 r--p 0002c000 08:60 6412                       /usr/lib/x86_64-linux-gnu/ld-linux-x86-64.so.2
7f7f6925c000-7f7f6925e000 r--p 00037000 08:60 6412                       /usr/lib/x86_64-linux-gnu/ld-linux-x86-64.so.2
7f7f6925e000-7f7f69260000 rw-p 00039000 08:60 6412                       /usr/lib/x86_64-linux-gnu/ld-linux-x86-64.so.2
7ffe8142a000-7ffe81c29000 rw-p 00000000 00:00 0                          [stack]
7ffe81d02000-7ffe81d06000 r--p 00000000 00:00 0                          [vvar]
7ffe81d06000-7ffe81d08000 r-xp 00000000 00:00 0                          [vdso]
```

### What did you expect to happen?

For the process to complete successfully without segfaulting.  

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
# Install brew
# SEE: https://github.com/Homebrew/install/#install-homebrew-on-macos-or-linux
NONINTERACTIVE=1 /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"

# Homebrew
test -d ~/.linuxbrew && eval "$(~/.linuxbrew/bin/brew shellenv)"
test -d /home/linuxbrew/.linuxbrew && eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
test -d /opt/homebrew && eval "$(/opt/homebrew/bin/brew shellenv)"
test -f /usr/local/bin/brew && eval "$(/usr/local/bin/brew shellenv)"

echo "***********************************"
echo "** Brew Config"
echo "***********************************"
brew config

echo "***********************************"
echo "** Brew Doctor"
echo "***********************************"
brew doctor


# Configure brew bundle
export HOMEBREW_BUNDLE_FILE="$HOME/.Brewfile_ShellTools"
export HOMEBREW_BUNDLE_NO_LOCK=true

# Install brew bundles
brew bundle install


## BUNDLE FILE

brew 'zsh'
brew 'zsh-completions'

brew 'shellcheck'
brew 'bats-core'
brew 'gh'
brew 'git-extras'

# ensure later versions 
brew 'bash'
brew 'wget'
brew 'hurl'
brew 'curl'
brew 'htop'
brew 'btop'
brew 'bmon'

brew 'tmux'
brew 'tmuxinator'    

brew 'git'

brew 'imagemagick'

brew 'jq'
brew 'yq'

brew 'dive'
brew 'container-diff'
brew 'container-structure-test'
brew 'oras'

brew 'awscli'

brew 'tfenv'
brew 'terraform-docs'

brew 'kubectx'
brew 'skaffold'
brew 'kubernetes-cli'
brew 'helm'
brew 'k9s'
brew 'yamllint'


brew 'pyenv'
brew 'pipenv'
brew 'poetry'
brew 'cookiecutter'

brew 'nvm'

brew 'nmap'

brew 'ffmpeg'

brew 'glab'
brew 'hurl'

brew 'gpg'
brew 'ssh-copy-id'
brew 'watch'

brew 'kind'
brew 'youtube-dl'
brew 'gomplate'

brew 'just'

brew 'chezmoi'

brew 'pre-commit'
brew 'dos2unix'


tap 'romkatv/powerlevel10k'
brew "powerlevel10k"
```
```

**Comment by Bo98** [comment]
> Linux 6.1.21.2-microsoft-standard-WSL2+

I'm guessing this is related to your issue. 6.1 under WSL 2 is still experimental and they haven't updated it in a year, instead moving back to regular 5.15 updates.

It definitely works under WSL 2 kernel 5.15 and it also works on a real Ubuntu 22.04 kernel 6.5.

**Comment by chrisguest75** [comment]
I'll try rolling back but I'm pretty sure this was happening on the default kernel as well.  It was one of the reasons I upgraded - will update with outcomes.

**Comment by chrisguest75** [comment]
I rolled back to the official wsl kernel and then performed a wsl --update.

It does seem to be working now. After using the 6.1 kernel for a few weeks this wasn't the only issue I saw. But does leave me unsure of the status of WSL regarding this type of support. 

Thanks for the pointer.
