### ISSUE TITLE
warning: Swift error in module errors when using swift from Homebrew

### ISSUE THREAD

**Issue by fgimian** [Homebrew/homebrew-core#170]
- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?
- [x] If you're seeing permission errors tried running `sudo chown -R $(whoami) $(brew --prefix)`?

### Bug reports:

Hello there, I'm not sure if others are experiencing this issue, but after installing Swift with Homebrew:

```bash
brew install swift
```

When I try to start `swift`, I get a bunch of errors like this:

```
otsies-MBP:~ fots$ swift
Welcome to Apple Swift version 2.2 (swiftlang-703.0.18.1 clang-703.0.29). Type :help for assistance.
warning: Swift error in module repl_swiftDebug info from this module will be unavailable in the debugger.

warning: Swift error in module dyldDebug info from this module will be unavailable in the debugger.

warning: Swift error in module libz.1.dylibDebug info from this module will be unavailable in the debugger.

warning: Swift error in module libedit.3.dylibDebug info from this module will be unavailable in the debugger.

warning: Swift error in module libpanel.5.4.dylibDebug info from this module will be unavailable in the debugger.

warning: Swift error in module CoreFoundationDebug info from this module will be unavailable in the debugger.

warning: Swift error in module libncurses.5.4.dylibDebug info from this module will be unavailable in the debugger.

warning: Swift error in module libSystem.B.dylibDebug info from this module will be unavailable in the debugger.

warning: Swift error in module liblzma.5.dylibDebug info from this module will be unavailable in the debugger.

warning: Swift error in module libauto.dylibDebug info from this module will be unavailable in the debugger.

warning: Swift error in module libDiagnosticMessagesClient.dylibDebug info from this module will be unavailable in the debugger.

warning: Swift error in module libicucore.A.dylibDebug info from this module will be unavailable in the debugger.

warning: Swift error in module libcache.dylibDebug info from this module will be unavailable in the debugger.

warning: Swift error in module libcommonCrypto.dylibDebug info from this module will be unavailable in the debugger.

warning: Swift error in module libcompiler_rt.dylibDebug info from this module will be unavailable in the debugger.

warning: Swift error in module libcopyfile.dylibDebug info from this module will be unavailable in the debugger.

warning: Swift error in module libcorecrypto.dylibDebug info from this module will be unavailable in the debugger.

warning: Swift error in module libdispatch.dylibDebug info from this module will be unavailable in the debugger.

warning: Swift error in module libdyld.dylibDebug info from this module will be unavailable in the debugger.

warning: Swift error in module libkeymgr.dylibDebug info from this module will be unavailable in the debugger.

warning: Swift error in module liblaunch.dylibDebug info from this module will be unavailable in the debugger.

warning: Swift error in module libmacho.dylibDebug info from this module will be unavailable in the debugger.

warning: Swift error in module libquarantine.dylibDebug info from this module will be unavailable in the debugger.

warning: Swift error in module libremovefile.dylibDebug info from this module will be unavailable in the debugger.

warning: Swift error in module libsystem_asl.dylibDebug info from this module will be unavailable in the debugger.

warning: Swift error in module libsystem_blocks.dylibDebug info from this module will be unavailable in the debugger.

warning: Swift error in module libsystem_c.dylibDebug info from this module will be unavailable in the debugger.

warning: Swift error in module libsystem_configuration.dylibDebug info from this module will be unavailable in the debugger.

warning: Swift error in module libsystem_coreservices.dylibDebug info from this module will be unavailable in the debugger.

warning: Swift error in module libsystem_coretls.dylibDebug info from this module will be unavailable in the debugger.

warning: Swift error in module libsystem_dnssd.dylibDebug info from this module will be unavailable in the debugger.

warning: Swift error in module libsystem_info.dylibDebug info from this module will be unavailable in the debugger.

warning: Swift error in module libsystem_kernel.dylibDebug info from this module will be unavailable in the debugger.

warning: Swift error in module libsystem_m.dylibDebug info from this module will be unavailable in the debugger.

warning: Swift error in module libsystem_malloc.dylibDebug info from this module will be unavailable in the debugger.

warning: Swift error in module libsystem_network.dylibDebug info from this module will be unavailable in the debugger.

warning: Swift error in module libsystem_networkextension.dylibDebug info from this module will be unavailable in the debugger.

warning: Swift error in module libsystem_notify.dylibDebug info from this module will be unavailable in the debugger.

warning: Swift error in module libsystem_platform.dylibDebug info from this module will be unavailable in the debugger.

warning: Swift error in module libsystem_pthread.dylibDebug info from this module will be unavailable in the debugger.

warning: Swift error in module libsystem_sandbox.dylibDebug info from this module will be unavailable in the debugger.

warning: Swift error in module libsystem_secinit.dylibDebug info from this module will be unavailable in the debugger.

warning: Swift error in module libsystem_trace.dylibDebug info from this module will be unavailable in the debugger.

warning: Swift error in module libunc.dylibDebug info from this module will be unavailable in the debugger.

warning: Swift error in module libunwind.dylibDebug info from this module will be unavailable in the debugger.

warning: Swift error in module libxpc.dylibDebug info from this module will be unavailable in the debugger.

warning: Swift error in module libc++.1.dylibDebug info from this module will be unavailable in the debugger.

warning: Swift error in module libc++abi.dylibDebug info from this module will be unavailable in the debugger.

warning: Swift error in module libcompression.dylibDebug info from this module will be unavailable in the debugger.

warning: Swift error in module libswiftCore.dylibDebug info from this module will be unavailable in the debugger.

warning: Swift error in module libswiftDarwin.dylibDebug info from this module will be unavailable in the debugger.

warning: Swift error in module libobjc.A.dylibDebug info from this module will be unavailable in the debugger.

warning: Swift error in module FoundationDebug info from this module will be unavailable in the debugger.

warning: Swift error in module libextension.dylibDebug info from this module will be unavailable in the debugger.

warning: Swift error in module DiskArbitrationDebug info from this module will be unavailable in the debugger.

warning: Swift error in module libarchive.2.dylibDebug info from this module will be unavailable in the debugger.

warning: Swift error in module libxml2.2.dylibDebug info from this module will be unavailable in the debugger.

warning: Swift error in module CFNetworkDebug info from this module will be unavailable in the debugger.

warning: Swift error in module SystemConfigurationDebug info from this module will be unavailable in the debugger.

warning: Swift error in module SecurityDebug info from this module will be unavailable in the debugger.

warning: Swift error in module CoreServicesDebug info from this module will be unavailable in the debugger.

warning: Swift error in module liblangid.dylibDebug info from this module will be unavailable in the debugger.

warning: Swift error in module IOKitDebug info from this module will be unavailable in the debugger.

warning: Swift error in module libCRFSuite.dylibDebug info from this module will be unavailable in the debugger.

warning: Swift error in module libenergytrace.dylibDebug info from this module will be unavailable in the debugger.

warning: Swift error in module libbsm.0.dylibDebug info from this module will be unavailable in the debugger.

warning: Swift error in module libkxld.dylibDebug info from this module will be unavailable in the debugger.

warning: Swift error in module libxar.1.dylibDebug info from this module will be unavailable in the debugger.

warning: Swift error in module libsqlite3.dylibDebug info from this module will be unavailable in the debugger.

warning: Swift error in module libpam.2.dylibDebug info from this module will be unavailable in the debugger.

warning: Swift error in module libOpenScriptingUtil.dylibDebug info from this module will be unavailable in the debugger.

warning: Swift error in module libbz2.1.0.dylibDebug info from this module will be unavailable in the debugger.

warning: Swift error in module FSEventsDebug info from this module will be unavailable in the debugger.

warning: Swift error in module CarbonCoreDebug info from this module will be unavailable in the debugger.

warning: Swift error in module MetadataDebug info from this module will be unavailable in the debugger.

warning: Swift error in module OSServicesDebug info from this module will be unavailable in the debugger.

warning: Swift error in module SearchKitDebug info from this module will be unavailable in the debugger.

warning: Swift error in module AEDebug info from this module will be unavailable in the debugger.

warning: Swift error in module LaunchServicesDebug info from this module will be unavailable in the debugger.

warning: Swift error in module DictionaryServicesDebug info from this module will be unavailable in the debugger.

warning: Swift error in module SharedFileListDebug info from this module will be unavailable in the debugger.

warning: Swift error in module NetFSDebug info from this module will be unavailable in the debugger.

warning: Swift error in module NetAuthDebug info from this module will be unavailable in the debugger.

warning: Swift error in module loginsupportDebug info from this module will be unavailable in the debugger.

warning: Swift error in module TCCDebug info from this module will be unavailable in the debugger.

warning: Swift error in module libmecabra.dylibDebug info from this module will be unavailable in the debugger.

warning: Swift error in module ApplicationServicesDebug info from this module will be unavailable in the debugger.

warning: Swift error in module CoreGraphicsDebug info from this module will be unavailable in the debugger.

warning: Swift error in module CoreTextDebug info from this module will be unavailable in the debugger.

warning: Swift error in module ImageIODebug info from this module will be unavailable in the debugger.

warning: Swift error in module ATSDebug info from this module will be unavailable in the debugger.

warning: Swift error in module ColorSyncDebug info from this module will be unavailable in the debugger.

warning: Swift error in module HIServicesDebug info from this module will be unavailable in the debugger.

warning: Swift error in module LangAnalysisDebug info from this module will be unavailable in the debugger.

warning: Swift error in module PrintCoreDebug info from this module will be unavailable in the debugger.

warning: Swift error in module QDDebug info from this module will be unavailable in the debugger.

warning: Swift error in module SpeechSynthesisDebug info from this module will be unavailable in the debugger.

warning: Swift error in module IOSurfaceDebug info from this module will be unavailable in the debugger.

warning: Swift error in module AccelerateDebug info from this module will be unavailable in the debugger.

warning: Swift error in module MultitouchSupportDebug info from this module will be unavailable in the debugger.

warning: Swift error in module MetalDebug info from this module will be unavailable in the debugger.

warning: Swift error in module vImageDebug info from this module will be unavailable in the debugger.

warning: Swift error in module vecLibDebug info from this module will be unavailable in the debugger.

warning: Swift error in module libvDSP.dylibDebug info from this module will be unavailable in the debugger.

warning: Swift error in module libvMisc.dylibDebug info from this module will be unavailable in the debugger.

warning: Swift error in module libLAPACK.dylibDebug info from this module will be unavailable in the debugger.

warning: Swift error in module libBLAS.dylibDebug info from this module will be unavailable in the debugger.

warning: Swift error in module libLinearAlgebra.dylibDebug info from this module will be unavailable in the debugger.

warning: Swift error in module libSparseBLAS.dylibDebug info from this module will be unavailable in the debugger.

warning: Swift error in module libmetal_timestamp.dylibDebug info from this module will be unavailable in the debugger.

warning: Swift error in module libCoreFSCache.dylibDebug info from this module will be unavailable in the debugger.

warning: Swift error in module IOAcceleratorDebug info from this module will be unavailable in the debugger.

warning: Swift error in module libFontParser.dylibDebug info from this module will be unavailable in the debugger.

warning: Swift error in module libFontRegistry.dylibDebug info from this module will be unavailable in the debugger.

warning: Swift error in module AppleVPADebug info from this module will be unavailable in the debugger.

warning: Swift error in module AppleJPEGDebug info from this module will be unavailable in the debugger.

warning: Swift error in module libJPEG.dylibDebug info from this module will be unavailable in the debugger.

warning: Swift error in module libTIFF.dylibDebug info from this module will be unavailable in the debugger.

warning: Swift error in module libPng.dylibDebug info from this module will be unavailable in the debugger.

warning: Swift error in module libGIF.dylibDebug info from this module will be unavailable in the debugger.

warning: Swift error in module libJP2.dylibDebug info from this module will be unavailable in the debugger.

warning: Swift error in module libRadiance.dylibDebug info from this module will be unavailable in the debugger.

warning: Swift error in module OpenGLDebug info from this module will be unavailable in the debugger.

warning: Swift error in module CoreVideoDebug info from this module will be unavailable in the debugger.

warning: Swift error in module libGLU.dylibDebug info from this module will be unavailable in the debugger.

warning: Swift error in module libGFXShared.dylibDebug info from this module will be unavailable in the debugger.

warning: Swift error in module libGL.dylibDebug info from this module will be unavailable in the debugger.

warning: Swift error in module libGLImage.dylibDebug info from this module will be unavailable in the debugger.

warning: Swift error in module libCVMSPluginSupport.dylibDebug info from this module will be unavailable in the debugger.

warning: Swift error in module libCoreVMClient.dylibDebug info from this module will be unavailable in the debugger.

warning: Swift error in module libcups.2.dylibDebug info from this module will be unavailable in the debugger.

warning: Swift error in module KerberosDebug info from this module will be unavailable in the debugger.

warning: Swift error in module GSSDebug info from this module will be unavailable in the debugger.

warning: Swift error in module libresolv.9.dylibDebug info from this module will be unavailable in the debugger.

warning: Swift error in module libiconv.2.dylibDebug info from this module will be unavailable in the debugger.

warning: Swift error in module HeimdalDebug info from this module will be unavailable in the debugger.

warning: Swift error in module libheimdal-asn1.dylibDebug info from this module will be unavailable in the debugger.

warning: Swift error in module OpenDirectoryDebug info from this module will be unavailable in the debugger.

warning: Swift error in module CommonAuthDebug info from this module will be unavailable in the debugger.

warning: Swift error in module CFOpenDirectoryDebug info from this module will be unavailable in the debugger.

warning: Swift error in module SecurityFoundationDebug info from this module will be unavailable in the debugger.

warning: Swift error in module CoreAudioDebug info from this module will be unavailable in the debugger.

warning: Swift error in module AudioToolboxDebug info from this module will be unavailable in the debugger.

warning: Swift error in module LanguageModelingDebug info from this module will be unavailable in the debugger.

warning: Swift error in module libmarisa.dylibDebug info from this module will be unavailable in the debugger.

warning: Swift error in module libChineseTokenizer.dylibDebug info from this module will be unavailable in the debugger.

warning: Swift error in module libcmph.dylibDebug info from this module will be unavailable in the debugger.

warning: Swift error in module CoreDataDebug info from this module will be unavailable in the debugger.

warning: Swift error in module ServiceManagementDebug info from this module will be unavailable in the debugger.

warning: Swift error in module libxslt.1.dylibDebug info from this module will be unavailable in the debugger.

  1> ^D
```

Any help would be appreciated 😄

**Comment by mikemcquaid** [comment]
I also see this. CC @Aleksey @jdhealy @C-l-o-u-d and the venerable @mxcl in case any of you have any insights here on what we're doing wrong in https://github.com/Homebrew/homebrew-core/blob/master/Formula/swift.rb

**Comment by mikemcquaid** [comment]
Actually, I see the issue: run `/usr/local/opt/swift/bin/swift` rather than `/usr/bin/swift` and you'll not see these errors (they come from Apple's `swift`, not ours).

**Comment by fgimian** [comment]
Yup, that works, I feel so silly 😄 Thanks!

**Comment by mikemcquaid** [comment]
Well, I did the same thing at first so: don't!

**Comment by mxcl** [comment]
Seems like lldb is loading the wrong libraries, /cc @ddunbar

If we're doing wrong, we'll file a bug.

**Comment by mikemcquaid** [comment]
@mxcl Thanks! FYI it seems to be only reproducible when you have the CLT installed but not Xcode.

**Comment by fgimian** [comment]
@mikemcquaid that's exactly what my setup was also.  After install Xcode yesterday, the version in /usr/bin works too 😄 

However, another problem is that installing Python from Homebrow causes heads pf Python exceptions when running the version in /usr/bin:

e.g.

```
raceback (most recent call last):
  File "<string>", line 1, in <module>
NameError: name 'run_one_line' is not defined
Traceback (most recent call last):
  File "<string>", line 1, in <module>
NameError: name 'run_one_line' is not defined
Traceback (most recent call last):
  File "<string>", line 1, in <module>
NameError: name 'run_one_line' is not defined
```

I'm not 100% sure how to get around this as I need the Homebrew Python installed and wouldn't mind using the Xcode Swift while learning Swift.

Open to thoughts and ideas 😄

**Comment by JonathanBarrosGIT** [comment]
I am also getting exactly the same problem that @fgimian is when trying to rum Swift directly on REPL.

**Comment by MikeMcQuaid** [comment]
@fgimian @JonathanBarrosGIT Please open a new issue.

**Comment by philosopherdog** [comment]
Run 'pip install six'. Apparently the REPL
