### ISSUE TITLE
installing mpv-0.26.0 fails

### ISSUE THREAD

**Issue by Quantizen** [Homebrew/homebrew-core#17144]
# Please always follow these steps:
- [x] Confirmed this is a problem with `brew install`ing one, specific formula (not cask) and not every time you run `brew`? If it's a general `brew` problem please file this issue at https://github.com/Homebrew/brew/issues/new. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/caskroom/homebrew-cask/new
- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed all issues and retried your prior step?
- [x] Ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link? https://gist.github.com/df0f6f4677387fdaf3c5cc1a1b11b094

It came across the following error when I tried to install `mpv` with homebrew:
```
brew install mpv --with-bundle    
==> Downloading https://github.com/mpv-player/mpv/archive/v0.26.0.tar.gz
Already downloaded: /Users/***/Library/Caches/Homebrew/mpv-0.26.0.tar.gz
==> Downloading https://files.pythonhosted.org/packages/05/25/7b5484aca5d46915493f1fd4ecb63c38c333bd32aa9ad
Already downloaded: /Users/***/Library/Caches/Homebrew/mpv--docutils-0.13.1.tar.gz
==> python -c import setuptools... --no-user-cfg install --prefix=/private/tmp/mpv-20170823-40386-1pkdmw/mp
Last 15 lines from /Users/***/Library/Logs/Homebrew/mpv/01.python:
--no-user-cfg
install
--prefix=/private/tmp/mpv-20170823-40386-1pkdmw/mpv-0.26.0/vendor
--single-version-externally-managed
--record=installed.txt

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/local/lib/python2.7/site-packages/setuptools/__init__.py", line 10, in <module>
    from setuptools.extern.six.moves import filter, map
  File "/usr/local/lib/python2.7/site-packages/setuptools/setuptools/__init__.py", line 160, in <module>
    monkey.patch_all()
  File "/usr/local/lib/python2.7/site-packages/setuptools/setuptools/monkey.py", line 48, in patch_all
    distutils.core.Command = setuptools.Command
AttributeError: 'module' object has no attribute 'Command'

READ THIS: https://docs.brew.sh/Troubleshooting.html
```

**Comment by ilovezfs** [comment]
what's the output of
```
env | grep -i py
```

**Comment by Quantizen** [comment]
@ilovezfs nothing

**Comment by Quantizen** [comment]
Maybe we should use `brew cask` to install `mpv` now, it succeeded in my case at least. 
```
~ brew cask install mpv
==> Satisfying dependencies
==> Downloading https://laboratory.stolendata.net/~djinn/mpv_osx/mpv-0.26.0.tar.gz
######################################################################## 100.0%
==> Verifying checksum for Cask mpv
==> Installing Cask mpv
==> Moving App 'mpv.app' to '/Applications/mpv.app'.
==> Linking Binary 'mpv' to '/usr/local/bin/mpv'.
🍺  mpv was successfully installed!
```

**Comment by sl1pkn07** [comment]
```Hackintoch:~ Hakintoch$ brew reinstall mpv --with-bundle --with-libaacs --with-libarchive --with-libbluray --with-libdvdnav --with-libdvdread --with-uchardet --with-libcdio
==> Reinstalling mpv --with-bundle --with-libaacs --with-libarchive --with-libbluray --with-libdvdnav --with-libdvdread --with-uchardet --with-libcdio
==> Installing dependencies for mpv: uchardet, libcdio
==> Installing mpv dependency: uchardet
==> Downloading https://homebrew.bintray.com/bottles/uchardet-0.0.6.sierra.bottle.tar.gz
######################################################################## 100,0%
==> Pouring uchardet-0.0.6.sierra.bottle.tar.gz
🍺  /usr/local/Cellar/uchardet/0.0.6: 12 files, 432.0KB
==> Installing mpv dependency: libcdio
==> Downloading https://homebrew.bintray.com/bottles/libcdio-0.94.sierra.bottle.tar.gz
==> Downloading from https://akamai.bintray.com/a3/a33a83ce904f907197bea29caab598b3fb505c0057a720e4b0ac1d7f8b19e15c?__gda__=exp=1506362847~hmac=52ec6d56207ade7d226a98ef48dcc0e83257ee1242e9aa3451730b199296c51f&response-content-disposition=attachment%3Bfilename%3D%22libcdio-0.94.sierra.bottle.tar.gz%22&response-content-type=applica
######################################################################## 100,0%
==> Pouring libcdio-0.94.sierra.bottle.tar.gz
🍺  /usr/local/Cellar/libcdio/0.94: 84 files, 1.9MB
==> Installing mpv --with-bundle --with-libaacs --with-libarchive --with-libbluray --with-libdvdnav --with-libdvdread --with-uchardet --with-libcdio
==> Downloading https://github.com/mpv-player/mpv/archive/v0.27.0.tar.gz
Already downloaded: /Users/Hakintoch/Library/Caches/Homebrew/mpv-0.27.0.tar.gz
==> Downloading https://files.pythonhosted.org/packages/05/25/7b5484aca5d46915493f1fd4ecb63c38c333bd32aa9ad6e19da8d08895ae/docutils-0.13.1.tar.gz
Already downloaded: /Users/Hakintoch/Library/Caches/Homebrew/mpv--docutils-0.13.1.tar.gz
==> python -c import setuptools... --no-user-cfg install --prefix=/private/tmp/mpv-20170925-72154-1nyihe8/mpv-0.27.0/vendor --single-version-externally-managed --record=installed.txt
==> ./bootstrap.py
==> python3 waf configure --prefix=/usr/local/Cellar/mpv/0.27.0 --enable-zsh-comp --enable-libmpv-shared --enable-html-build --confdir=/usr/local/etc/mpv --datadir=/usr/local/Cellar/mpv/0.27.0/share/mpv --mandir=/usr/local/Cellar/mpv/0.27.0/share/man --docdir=/usr/local/Cellar/mpv/0.27.0/share/doc/mpv --zshdir=/usr/local/Cellar/m
Last 15 lines from /Users/Hakintoch/Library/Logs/Homebrew/mpv/03.python3:
Checking for Linux's fstatfs()                                    : os-linux not found 
Checking for Samba support (makes mpv GPLv3)                      : disabled 
Checking for Lua                                                  : yes (version found: 52) 
Checking for Javascript (MuJS backend)                            : no ('mujs >= 1.0.0' not found) 
Checking for SSA/ASS support                                      : yes 
Checking for libass OSD support                                   : yes 
Checking for dummy OSD support                                    : libass-osd found 
Checking for zlib                                                 : yes 
Checking for Encoding                                             : yes 
Checking for Bluray support                                       : yes 
Checking for dvdread support                                      : yes 
Checking for dvdnav support                                       : yes 
Checking for DVD/IFO support                                      : yes 
Checking for cdda support (libcdio)                               : no ('libcdio_paranoia' not found) 
You manually enabled the feature 'cdda', but the autodetection check failed.

READ THIS: https://docs.brew.sh/Troubleshooting.html

These open issues may also help:
installing mpv-0.26.0 fails https://github.com/Homebrew/homebrew-core/issues/17144
```

**Comment by fxcoudert** [comment]
Was fixed by removal of `--with-libcdio` option (which didn't work)

**Comment by sl1pkn07** [comment]
That is not a fix, i want build mpv with cdda support.

Please add support for libcdio_paranoia

Greetings

**Comment by ilovezfs** [comment]
@sl1pkn07 we'd consider a functioning PR for it, but no maintainers are planning on working on that at this time.

**Comment by fxcoudert** [comment]
@sl1pkn07 we'll be glad to consider a [pull request](https://github.com/Homebrew/homebrew-core/pulls) that adds support for cdda support to mpv.
