### ISSUE TITLE
Problem with ansible-lint formula

### ISSUE THREAD

**Issue by i1tech** [Homebrew/homebrew-core#173128]
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

```shell
MyMac:facts-aap user1$ brew doctor
Your system is ready to brew.
MyMac:facts-aap user1$ brew config
HOMEBREW_VERSION: 4.3.2
ORIGIN: https://github.com/Homebrew/brew
HEAD: 9fdb0d53990d3e62e25325a6f89dbb769e84a530
Last commit: 3 days ago
Core tap JSON: 29 May 13:01 UTC
Core cask tap JSON: 29 May 13:01 UTC
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CASK_OPTS: []
HOMEBREW_MAKE_JOBS: 16
HOMEBREW_SORBET_RUNTIME: set
Homebrew Ruby: 3.3.1 => /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/3.3.1/bin/ruby
CPU: 16-core 64-bit kabylake
Clang: 15.0.0 build 1500
Git: 2.45.1 => /usr/local/bin/git
Curl: 8.4.0 => /usr/bin/curl
macOS: 14.4.1-x86_64
CLT: 15.3.0.0.1.1708646388
Xcode: 15.3
MyMac:facts-aap user1$
```

### Verification

- [X] My `brew doctor` output says `Your system is ready to brew.` and am still able to reproduce my issue.
- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.
- [X] I searched for recent similar issues at https://github.com/Homebrew/homebrew-core/issues?q=is%3Aissue and found no duplicates.

### What were you trying to do (and why)?

When trying to run ansible-lint, it shows an incompatibility between the installed ansible formula (2.16.7) and installed ansible-lint formula (24.5.0), both were installed via brew. Linter fails to execute, output provided below.

### What happened (include all command output)?

`MyMac:facts-aap user1$ ansible-lint
Ansible CLI (2.16.7) and python module (2.16.6) versions do not match. This indicates a broken execution environment.`

### What did you expect to happen?

I expected ansible-lint to run and check ansible content in the directory recursively.

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
brew install ansible ansible-lint
```

**Comment by i1tech** [comment]
Without ansible installed:
```
brew test ansible-lint
==> Testing ansible-lint
==> /usr/local/Cellar/ansible-lint/24.5.0/bin/ansible-lint /private/tmp/ansible-lint-test-20240530-39845-93xc48/playbook.yml
```
After installing ansible (`brew install ansible`)
```
brew test ansible-lint
==> Testing ansible-lint
==> /usr/local/Cellar/ansible-lint/24.5.0/bin/ansible-lint /private/tmp/ansible-lint-test-20240530-41159-mxdgpi/playbook.yml
Last 15 lines from /Users/jsmith446/Library/Logs/Homebrew/ansible-lint/test.01.ansible-lint:
2024-05-30 09:13:19 -0400

/usr/local/Cellar/ansible-lint/24.5.0/bin/ansible-lint
/private/tmp/ansible-lint-test-20240530-41159-mxdgpi/playbook.yml

Ansible CLI (2.16.7) and python module (2.16.6) versions do not match. This indicates a broken execution environment.
Error: ansible-lint: failed
Warning: Removed Sorbet lines from backtrace!
Rerun with `--verbose` to see the original backtrace
An exception occurred within a child process:
  BuildError: Failed executing: /usr/local/Cellar/ansible-lint/24.5.0/bin/ansible-lint /private/tmp/ansible-lint-test-20240530-41159-mxdgpi/playbook.yml
/usr/local/Homebrew/Library/Homebrew/formula.rb:3044:in `block in system'
/usr/local/Homebrew/Library/Homebrew/formula.rb:2980:in `open'
/usr/local/Homebrew/Library/Homebrew/formula.rb:2980:in `system'
/usr/local/opt/ansible-lint/.brew/ansible-lint.rb:185:in `block in <class:AnsibleLint>'
/usr/local/Homebrew/Library/Homebrew/formula.rb:2786:in `block (3 levels) in run_test'
/usr/local/Homebrew/Library/Homebrew/extend/kernel.rb:529:in `with_env'
/usr/local/Homebrew/Library/Homebrew/formula.rb:2785:in `block (2 levels) in run_test'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1189:in `with_logging'
/usr/local/Homebrew/Library/Homebrew/formula.rb:2784:in `block in run_test'
/usr/local/Homebrew/Library/Homebrew/mktemp.rb:75:in `block in run'
/usr/local/Homebrew/Library/Homebrew/mktemp.rb:75:in `chdir'
/usr/local/Homebrew/Library/Homebrew/mktemp.rb:75:in `run'
/usr/local/Homebrew/Library/Homebrew/formula.rb:3095:in `mktemp'
/usr/local/Homebrew/Library/Homebrew/formula.rb:2778:in `run_test'
/usr/local/Homebrew/Library/Homebrew/test.rb:46:in `block in <main>'
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/3.3.1/lib/ruby/3.3.0/timeout.rb:186:in `block in timeout'
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/3.3.1/lib/ruby/3.3.0/timeout.rb:41:in `handle_timeout'
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/3.3.1/lib/ruby/3.3.0/timeout.rb:195:in `timeout'
/usr/local/Homebrew/Library/Homebrew/test.rb:50:in `<main>'
```

**Comment by chenrui333** [comment]
okay, I filed a PR to update the ansible-lint's ansible-core version to make it in sync with ansible.

**Comment by i1tech** [comment]
Thanks! Much appreciated!

**Comment by chenrui333** [comment]
@i1tech we shipped the change, can you give another shot to see if it works for you?

**Comment by i1tech** [comment]
Works perfectly now, thank you!

**Comment by chenrui333** [comment]
glad to hear, thanks for reporting the bug.
