### ISSUE TITLE
brew install python3 leads to broken python3

### ISSUE THREAD

**Issue by jmarrec** [Homebrew/homebrew-core#17700]
# Please always follow these steps:
- [x] Confirmed this is a problem with `brew install`ing one, specific Homebrew/homebrew-core formula (not cask or tap) and not every time you run `brew`? If it's a general `brew` problem please file this issue at https://github.com/Homebrew/brew/issues/new. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/caskroom/homebrew-cask/new. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed all issues and retried your prior step?
- [ ] Ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [ ] If `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

To help us debug your issue please explain:

> What you were trying to do (and why)

I'm trying to re-install python3 after having uninstalled it. I did also uninstall python and reinstalled it as some point too.

> What happened (include command output) & Step-by-step reproduction instructions (by running `brew install` commands)

```
$ brew uninstall python3
$ brew update
Already up-to-date.
$ brew upgrade
$ brew doctor
Your system is ready to brew.
$ which python3 
=> nothing
$ brew install python3
==> Downloading https://homebrew.bintray.com/bottles/python3-3.6.2.sierra.bottle
Already downloaded: /Users/julien/Library/Caches/Homebrew/python3-3.6.2.sierra.bottle.tar.gz
==> Pouring python3-3.6.2.sierra.bottle.tar.gz
==> /usr/local/Cellar/python3/3.6.2/bin/python3 -s setup.py --no-user-cfg instal
==> /usr/local/Cellar/python3/3.6.2/bin/python3 -s setup.py --no-user-cfg instal
==> /usr/local/Cellar/python3/3.6.2/bin/python3 -s setup.py --no-user-cfg instal
==> Caveats
Pip, setuptools, and wheel have been installed. To update them
  pip3 install --upgrade pip setuptools wheel

You can install Python packages with
  pip3 install <package>

They will install into the site-package directory
  /usr/local/lib/python3.6/site-packages

See: https://docs.brew.sh/Homebrew-and-Python.html
==> Summary
🍺  /usr/local/Cellar/python3/3.6.2: 3,598 files, 55.9MB
```

`brew doctor` has still no issues at this point

> - What you expected to happen

I expected python3 to not throw a SyntaxError because it's looking at a the System Library for python 2.7 (?!), instead I got:

```
$ python3
Python 3.6.2 (default, Jul 17 2017, 16:44:45) 
[GCC 4.2.1 Compatible Apple LLVM 8.1.0 (clang-802.0.42)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
Failed calling sys.__interactivehook__
Traceback (most recent call last):
  File "/usr/local/Cellar/python3/3.6.2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site.py", line 388, in register_readline
    import rlcompleter
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/rlcompleter.py", line 60
    raise TypeError,'namespace must be a dictionary'
                   ^
SyntaxError: invalid syntax
>>> 
```

## Gist-logs

[brew gist-logs python3](https://gist.github.com/682b9efbb1f5445f66dbae2932a3f148)

**Comment by jmarrec** [comment]
Well, what do you know, uninstalling, cleaning the cache (with -s), and reinstalling did the trick:

brew uninstall python3
brew cleanup -s
brew install python3
