### ISSUE TITLE
yt-dlp broke with the last update

### ISSUE THREAD

**Issue by chr1st0ph3rGG** [Homebrew/homebrew-core#177766]
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

```shell
>>> brew gist-logs yt-dlp
Error: No logs.

>>> brew config
HOMEBREW_VERSION: 4.3.9-329-g61f5e2b
ORIGIN: https://github.com/Homebrew/brew
HEAD: 61f5e2b6988aa40e93fe044eb56b1a79e9e7307e
Last commit: 2 hours ago
Core tap JSON: 18 Jul 18:06 UTC
Core cask tap JSON: 18 Jul 18:06 UTC
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_MAKE_JOBS: 12
HOMEBREW_SORBET_RUNTIME: set
Homebrew Ruby: 3.3.4 => /opt/homebrew/Library/Homebrew/vendor/portable-ruby/3.3.4/bin/ruby
CPU: dodeca-core 64-bit arm_lobos
Clang: 15.0.0 build 1500
Git: 2.39.3 => /Library/Developer/CommandLineTools/usr/bin/git
Curl: 8.6.0 => /usr/bin/curl
macOS: 14.5-arm64
CLT: 15.3.0.0.1.1708646388
Xcode: 15.4
Rosetta 2: false

>>> brew doctor
Your system is ready to brew.
```

### Verification

- [X] My `brew doctor` output says `Your system is ready to brew.` and am still able to reproduce my issue.
- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.
- [X] I searched for recent similar issues at https://github.com/Homebrew/homebrew-core/issues?q=is%3Aissue and found no duplicates.

### What were you trying to do (and why)?

Install yt-dlp after the last update on the formular. The cli is broken since the update.  The yt-dlp repo pointed me here.
Tried it on 2 macs with the same outcome, so I would call it reproducable?

### What happened (include all command output)?

>>> yt-dlp
Traceback (most recent call last):
  File "/opt/homebrew/bin/yt-dlp", line 5, in <module>
    from yt_dlp import main
  File "/opt/homebrew/Cellar/yt-dlp/2024.7.16/libexec/lib/python3.12/site-packages/yt_dlp/__init__.py", line 18, in <module>
    from .cookies import SUPPORTED_BROWSERS, SUPPORTED_KEYRINGS
  File "/opt/homebrew/Cellar/yt-dlp/2024.7.16/libexec/lib/python3.12/site-packages/yt_dlp/cookies.py", line 23, in <module>
    from .aes import (
  File "/opt/homebrew/Cellar/yt-dlp/2024.7.16/libexec/lib/python3.12/site-packages/yt_dlp/aes.py", line 5, in <module>
    from .dependencies import Cryptodome
  File "/opt/homebrew/Cellar/yt-dlp/2024.7.16/libexec/lib/python3.12/site-packages/yt_dlp/dependencies/__init__.py", line 65, in <module>
    import requests
  File "/opt/homebrew/Cellar/yt-dlp/2024.7.16/libexec/lib/python3.12/site-packages/requests/__init__.py", line 164, in <module>
    from .api import delete, get, head, options, patch, post, put, request
  File "/opt/homebrew/Cellar/yt-dlp/2024.7.16/libexec/lib/python3.12/site-packages/requests/api.py", line 11, in <module>
    from . import sessions
  File "/opt/homebrew/Cellar/yt-dlp/2024.7.16/libexec/lib/python3.12/site-packages/requests/sessions.py", line 15, in <module>
    from .adapters import HTTPAdapter
  File "/opt/homebrew/Cellar/yt-dlp/2024.7.16/libexec/lib/python3.12/site-packages/requests/adapters.py", line 81, in <module>
    _preloaded_ssl_context.load_verify_locations(
FileNotFoundError: [Errno 2] No such file or directory

### What did you expect to happen?

that yt-dlp works and not showing a traceback

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
>>> brew install yt-dlp
>>> yt-dlp
```

**Comment by cho-m** [comment]
I tried steps but didn't see the issue:
```console
❯ brew install yt-dlp
...

❯ yt-dlp

Usage: yt-dlp [OPTIONS] URL [URL...]

yt-dlp: error: You must provide at least one URL.
Type yt-dlp --help to see a list of all options.

❯ yt-dlp --version
2024.07.16
```

---

The error may happen if either the symlink in `certifi` or the file in `ca-certificates` was deleted. For example, if you accidentally deleted or renamed the PEM file:

```console
❯ /opt/homebrew/opt/yt-dlp/libexec/bin/python3 -c 'import requests; print(requests.utils.DEFAULT_CA_BUNDLE_PATH)'
/opt/homebrew/opt/certifi/lib/python3.12/site-packages/certifi/cacert.pem

❯ realpath /opt/homebrew/opt/certifi/lib/python3.12/site-packages/certifi/cacert.pem
/opt/homebrew/etc/ca-certificates/cert.pem

❯ file /opt/homebrew/etc/ca-certificates/cert.pem
/opt/homebrew/etc/ca-certificates/cert.pem: PEM certificate

❯ mv /opt/homebrew/etc/ca-certificates/cert.pem /opt/homebrew/etc/ca-certificates/cert.pem.bak

❯ yt-dlp
Traceback (most recent call last):
  File "/opt/homebrew/bin/yt-dlp", line 5, in <module>
    from yt_dlp import main
```

---

Hard to tell any further what is state of your system that is causing this.

One thing you can try is reinstalling some formulae like `brew reinstall ca-certificates`
