### ISSUE TITLE
ipython fails to install when /usr/local/man does not exist

### ISSUE THREAD

**Issue by sparr** [Homebrew/homebrew-core#17959]
- [X] Confirmed this is a problem with `brew install`ing one, specific Homebrew/homebrew-core formula (not cask or tap) and not every time you run `brew`? If it's a general `brew` problem please file this issue at https://github.com/Homebrew/brew/issues/new. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/caskroom/homebrew-cask/new. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [X] Ran `brew update` and retried your prior step?
- [X] Ran `brew doctor`, fixed all issues and retried your prior step?
- [ ] Ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [ ] If `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

I didn't think to try the last two troubleshooting steps before resolving the problem manually.

I was attempting to do `pip install ipython[zmq,qtconsole,notebook,test]` per the sequence of instructions at https://github.com/nicolashery/mac-dev-setup

After some hundreds of lines of successful results I reached the following:

```
Successfully built simplegeneric scandir tornado terminado MarkupSafe pandocfilters functools32 configparser
Installing collected packages: backports.shutil-get-terminal-size, six, scandir, pathlib2, pickleshare, simplegeneric, wcwidth, prompt-toolkit, decorator, ptyprocess, pexpect, pygments, ipython-genutils, enum34, traitlets, appnope, singledispatch, certifi, backports-abc, tornado, MarkupSafe, jinja2, terminado, functools32, jsonschema, jupyter-core, nbformat, pyzmq, python-dateutil, jupyter-client, configparser, entrypoints, pandocfilters, webencodings, html5lib, bleach, mistune, testpath, nbconvert, ipykernel, notebook, widgetsnbextension, ipywidgets, qtconsole, chardet, idna, urllib3, requests, funcsigs, pbr, mock, nose, ipython
Exception:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/usr/local/lib/python2.7/site-packages/pip/commands/install.py", line 342, in run
    prefix=options.prefix_path,
  File "/usr/local/lib/python2.7/site-packages/pip/req/req_set.py", line 784, in install
    **kwargs
  File "/usr/local/lib/python2.7/site-packages/pip/req/req_install.py", line 851, in install
    self.move_wheel_files(self.source_dir, root=root, prefix=prefix)
  File "/usr/local/lib/python2.7/site-packages/pip/req/req_install.py", line 1064, in move_wheel_files
    isolated=self.isolated,
  File "/usr/local/lib/python2.7/site-packages/pip/wheel.py", line 377, in move_wheel_files
    clobber(source, dest, False, fixer=fixer, filter=filter)
  File "/usr/local/lib/python2.7/site-packages/pip/wheel.py", line 316, in clobber
    ensure_dir(destdir)
  File "/usr/local/lib/python2.7/site-packages/pip/utils/__init__.py", line 83, in ensure_dir
    os.makedirs(path)
  File "/usr/local/Cellar/python/2.7.13_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/os.py", line 150, in makedirs
    makedirs(head, mode)
  File "/usr/local/Cellar/python/2.7.13_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/os.py", line 157, in makedirs
    mkdir(name, mode)
OSError: [Errno 13] Permission denied: '/usr/local/man'
```

My `/usr/local` is not writeable by my user. Most of the directories under it are owned by my user, but '/usr/local/man' man does not exist at all. Creating that directory and `chown`ing it to my user allowed me to proceed.

**Comment by JCount** [comment]
I am not certain how this issue is associated with Homebrew, other than the basic fact that you were using python (pip) installed through Homebrew.

**Comment by sparr** [comment]
I thought the existence of that directory, or the permissions on /usr/local, might be the responsibility of homebrew. Sorry if that's off base.

**Comment by sparr** [comment]
Possibly 'brew install python' should have created that directory if python/pip promises pip installers that it will be available? If not, then I'll take this over to the ipython/pip devs about them making an invalid assumption about the existence of the directory.

**Comment by sparr** [comment]
Installing the dependencies separately, I've narrowed the problem down to installing the `nose` package with pip.

```
$ pip uninstall -y nose && pip install nose
Uninstalling nose-1.3.7:
  Successfully uninstalled nose-1.3.7
Collecting nose
  Using cached nose-1.3.7-py2-none-any.whl
Installing collected packages: nose
Exception:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/usr/local/lib/python2.7/site-packages/pip/commands/install.py", line 342, in run
    prefix=options.prefix_path,
  File "/usr/local/lib/python2.7/site-packages/pip/req/req_set.py", line 784, in install
    **kwargs
  File "/usr/local/lib/python2.7/site-packages/pip/req/req_install.py", line 851, in install
    self.move_wheel_files(self.source_dir, root=root, prefix=prefix)
  File "/usr/local/lib/python2.7/site-packages/pip/req/req_install.py", line 1064, in move_wheel_files
    isolated=self.isolated,
  File "/usr/local/lib/python2.7/site-packages/pip/wheel.py", line 377, in move_wheel_files
    clobber(source, dest, False, fixer=fixer, filter=filter)
  File "/usr/local/lib/python2.7/site-packages/pip/wheel.py", line 316, in clobber
    ensure_dir(destdir)
  File "/usr/local/lib/python2.7/site-packages/pip/utils/__init__.py", line 83, in ensure_dir
    os.makedirs(path)
  File "/usr/local/Cellar/python/2.7.13_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/os.py", line 150, in makedirs
    makedirs(head, mode)
  File "/usr/local/Cellar/python/2.7.13_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/os.py", line 157, in makedirs
    mkdir(name, mode)
OSError: [Errno 13] Permission denied: '/usr/local/man'
```

Still unclear whether this is a problem between homebrew and python, python and pip, or pip and the nose package.

**Comment by sparr** [comment]
https://github.com/nose-devs/nose/issues/1017

**Comment by sparr** [comment]
Going to report this a bit more broadly, as the FHS says /usr/local/man should exist, and I expect that other apps rely on it existing.

**Comment by sparr** [comment]
https://github.com/Homebrew/install/issues/109

**Comment by sparr** [comment]
In case someone makes it this far without clicking the link above... This is a `wontfix` issue for the homebrew install devs :(
