### ISSUE TITLE
Something went wrong with httpd24->httpd rename

### ISSUE THREAD

**Issue by mmindenhall** [Homebrew/homebrew-core#18715]
- [x ] Confirmed this is a problem with `brew install`ing one, specific Homebrew/homebrew-core formula (not cask or tap) and not every time you run `brew`? If it's a general `brew` problem please file this issue at https://github.com/Homebrew/brew/issues/new. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/caskroom/homebrew-cask/new. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [x ] Ran `brew update` and retried your prior step?
- [x ] Ran `brew doctor`, fixed all issues and retried your prior step?
- [x ] Ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [x ] If `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

```
$ brew config
HOMEBREW_VERSION: 1.3.4-33-g296a441
ORIGIN: https://github.com/Homebrew/brew.git
HEAD: 296a44195bb8c8c0d5d9b512f10c7ee70f400efb
Last commit: 2 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 01808f41c8156bc51f5e68db4bfd4e55a3161236
Core tap last commit: 9 minutes ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_REPOSITORY: /usr/local/Homebrew
HOMEBREW_CELLAR: /usr/local/Cellar
HOMEBREW_BOTTLE_DOMAIN: https://homebrew.bintray.com
CPU: octa-core 64-bit haswell
Homebrew Ruby: 2.3.3 => /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/bin/ruby
GCC-4.2: build 5666
Clang: 9.0 build 900
Git: 2.14.2 => /usr/local/bin/git
Perl: /usr/bin/perl
Python: /usr/local/opt/python/libexec/bin/python => /usr/local/Cellar/python/2.7.14/Frameworks/Python.framework/Versions/2.7/bin/python2.7
Ruby: /Users/mmindenhall/.rbenv/shims/ruby => /Users/mmindenhall/.rbenv/versions/2.4.1/bin/ruby
Java: 1.8.0_121, 1.8.0_101, 1.8.0_60, 1.8.0_45, 1.7.0_80
macOS: 10.12.6-x86_64
Xcode: 9.0
CLT: 9.0.0.0.1.1504363082
X11: 2.7.11 => /opt/X11
```

Less than an hour before this issue was submitted, changes were made to the httpd24 formula.
1.  Rename httpd24 -> httpd (7fc16397)
1.  Update the formula (ab315476)

It looks like something went wrong here.

```
$ brew update
Updated 1 tap (homebrew/core).
==> Renamed Formulae
httpd24 -> httpd
Error: 784: unexpected token at '{
  "httpd24": "homebrew/core",
}
'
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/2.3.0/json/common.rb:156:in `parse'
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/2.3.0/json/common.rb:156:in `parse'
/usr/local/Homebrew/Library/Homebrew/tap.rb:475:in `tap_migrations'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:200:in `formula_name_path'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:180:in `initialize'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:351:in `new'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:351:in `loader_for'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:271:in `factory'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:302:in `from_keg'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:285:in `from_rack'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1384:in `block in installed'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1382:in `map'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1382:in `installed'
/usr/local/Homebrew/Library/Homebrew/cmd/update-report.rb:506:in `migrate_formula_rename'
/usr/local/Homebrew/Library/Homebrew/cmd/update-report.rb:101:in `each'
/usr/local/Homebrew/Library/Homebrew/cmd/update-report.rb:101:in `update_report'
/usr/local/Homebrew/Library/Homebrew/brew.rb:95:in `<main>'

$ brew outdated
Error: 784: unexpected token at '{
  "httpd24": "homebrew/core",
}
'
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/2.3.0/json/common.rb:156:in `parse'
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/2.3.0/json/common.rb:156:in `parse'
/usr/local/Homebrew/Library/Homebrew/tap.rb:475:in `tap_migrations'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:200:in `formula_name_path'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:180:in `initialize'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:351:in `new'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:351:in `loader_for'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:271:in `factory'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:302:in `from_keg'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:285:in `from_rack'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1384:in `block in installed'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1382:in `map'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1382:in `installed'
/usr/local/Homebrew/Library/Homebrew/cmd/outdated.rb:28:in `outdated'
/usr/local/Homebrew/Library/Homebrew/brew.rb:95:in `<main>'

$ brew upgrade
Error: 784: unexpected token at '{
  "httpd24": "homebrew/core",
}
'
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/2.3.0/json/common.rb:156:in `parse'
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/2.3.0/json/common.rb:156:in `parse'
/usr/local/Homebrew/Library/Homebrew/tap.rb:475:in `tap_migrations'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:200:in `formula_name_path'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:180:in `initialize'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:351:in `new'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:351:in `loader_for'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:271:in `factory'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:302:in `from_keg'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:285:in `from_rack'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1384:in `block in installed'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1382:in `map'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1382:in `installed'
/usr/local/Homebrew/Library/Homebrew/cmd/upgrade.rb:37:in `upgrade'
/usr/local/Homebrew/Library/Homebrew/brew.rb:95:in `<main>'
```

**Comment by MikeMcQuaid** [comment]
This was fixed: https://github.com/Homebrew/brew/issues/3238
