### ISSUE TITLE
Missing psych for gem after updating to ruby to 2.4.2

### ISSUE THREAD

**Issue by attrib** [Homebrew/homebrew-core#18845]
**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

# Please always follow these steps:
- [x] Confirmed this is a problem with `brew install`ing one, specific Homebrew/homebrew-core formula (not cask or tap) and not every time you run `brew`? If it's a general `brew` problem please file this issue at https://github.com/Homebrew/brew/issues/new. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/caskroom/homebrew-cask/new. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed all issues and retried your prior step?
- [x] Ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [x] If `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

To help us debug your issue please explain:
- What you were trying to do (and why)

       brew upgrade ruby

- What happened (include command output)
   - ruby was successfully upgraded
   - calling gem brings now an error

```
/usr/local/Cellar/ruby/2.4.2/lib/ruby/2.4.0/yaml.rb:5:in `<top (required)>':
It seems your ruby installation is missing psych (for YAML output).
To eliminate this warning, please install libyaml and reinstall your ruby.
/usr/local/Cellar/ruby/2.4.2/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require': dlopen(/Users/karl.fritsche/.gem/ruby/2.4.0/gems/psych-2.2.4/lib/psych.bundle, 9): Library not loaded: /usr/local/opt/ruby/lib/libruby.2.4.1.dylib (LoadError)
  Referenced from: /Users/karl.fritsche/.gem/ruby/2.4.0/gems/psych-2.2.4/lib/psych.bundle
  Reason: image not found - /Users/karl.fritsche/.gem/ruby/2.4.0/gems/psych-2.2.4/lib/psych.bundle
	from /usr/local/Cellar/ruby/2.4.2/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /Users/karl.fritsche/.gem/ruby/2.4.0/gems/psych-2.2.4/lib/psych.rb:8:in `<top (required)>'
	from /usr/local/Cellar/ruby/2.4.2/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/local/Cellar/ruby/2.4.2/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/local/Cellar/ruby/2.4.2/lib/ruby/2.4.0/yaml.rb:6:in `<top (required)>'
	from /usr/local/Cellar/ruby/2.4.2/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/local/Cellar/ruby/2.4.2/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/local/Cellar/ruby/2.4.2/lib/ruby/2.4.0/rubygems.rb:701:in `load_yaml'
	from /usr/local/Cellar/ruby/2.4.2/lib/ruby/2.4.0/rubygems/config_file.rb:340:in `load_file'
	from /usr/local/Cellar/ruby/2.4.2/lib/ruby/2.4.0/rubygems/config_file.rb:202:in `initialize'
	from /usr/local/Cellar/ruby/2.4.2/lib/ruby/2.4.0/rubygems/gem_runner.rb:75:in `new'
	from /usr/local/Cellar/ruby/2.4.2/lib/ruby/2.4.0/rubygems/gem_runner.rb:75:in `do_configuration'
	from /usr/local/Cellar/ruby/2.4.2/lib/ruby/2.4.0/rubygems/gem_runner.rb:40:in `run'
	from /usr/local/bin/gem:21:in `<main>'
```

- What you expected to happen
    - gem still should work, like it did before

- Step-by-step reproduction instructions (by running `brew install` commands)

    - not sure how to best reproduce, as you need a older running ruby version before
    - call `brew upgrade ruby`
    - call `gem` and now you see the error

I also tried the fixed from https://github.com/Homebrew/homebrew-core/issues/18123#issuecomment-330926209

```
brew remove --force ruby # remove all versions installed
sudo rm -rf /usr/local/lib/ruby # remove all gems and leftover files
brew install ruby
gem install bundler
bundle install
```

As asked in the other issue already content of ruby dir:

```
$ ls /usr/local/lib/ruby/gems
2.4.0

$ ls /usr/local/lib/ruby/gems/2.4.0/
cache
gems
specifications

$ ls -l /usr/local/lib/ruby/gems/2.4.0/gems/
drwxr-xr-x  12 karl.fritsche  admin  408  2 Okt 14:30 did_you_mean-1.1.0
drwxr-xr-x   9 karl.fritsche  admin  306  2 Okt 14:30 minitest-5.10.1
drwxr-xr-x   8 karl.fritsche  admin  272  2 Okt 14:30 net-telnet-0.1.1
drwxr-xr-x  11 karl.fritsche  admin  374  2 Okt 14:30 power_assert-0.4.1
drwxr-xr-x  13 karl.fritsche  admin  442  2 Okt 14:30 rake-12.0.0
drwxr-xr-x   3 karl.fritsche  admin  102  2 Okt 14:30 rdoc-5.0.0
drwxr-xr-x  12 karl.fritsche  admin  408  2 Okt 14:30 test-unit-3.2.3
drwxr-xr-x   8 karl.fritsche  admin  272  2 Okt 14:30 xmlrpc-0.2.1
```

Also as mentioned brew install has no problems:

```
$ brew install ruby
Updating Homebrew...
==> Auto-updated Homebrew!
Updated 1 tap (caskroom/cask).
No changes to formulae.

==> Downloading https://homebrew.bintray.com/bottles/ruby-2.4.2.sierra.bottle.tar.gz
Already downloaded: /Users/karl.fritsche/Library/Caches/Homebrew/ruby-2.4.2.sierra.bottle.tar.gz
==> Pouring ruby-2.4.2.sierra.bottle.tar.gz
==> Caveats
Emacs Lisp files have been installed to:
  /usr/local/share/emacs/site-lisp/ruby
==> Summary
🍺  /usr/local/Cellar/ruby/2.4.2: 1,191 files, 15.3MB
```

## brew config

```
HOMEBREW_VERSION: 1.3.4
ORIGIN: https://github.com/Homebrew/brew
HEAD: ac8b58537fe3dd71098a43afcc6a1785dcde1d39
Last commit: 7 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 9e7f19e259bbe905d294eaf048018bb4c8c53f60
Core tap last commit: 26 minutes ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_REPOSITORY: /usr/local/Homebrew
HOMEBREW_CELLAR: /usr/local/Cellar
HOMEBREW_BOTTLE_DOMAIN: https://homebrew.bintray.com
CPU: quad-core 64-bit kabylake
Homebrew Ruby: 2.3.3 => /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/bin/ruby
Clang: 9.0 build 900
Git: 2.13.5 => /Library/Developer/CommandLineTools/usr/bin/git
Perl: /usr/bin/perl
Python: /usr/local/opt/python/libexec/bin/python => /usr/local/Cellar/python/2.7.14/Frameworks/Python.framework/Versions/2.7/bin/python2.7
Ruby: /usr/local/bin/ruby => /usr/local/Cellar/ruby/2.4.2/bin/ruby
Java: 1.8.0_144
macOS: 10.12.6-x86_64
Xcode: 9.0
CLT: 9.0.0.0.1.1504363082
X11: N/A
```

## brew doctor

```
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry and just ignore them. Thanks!

Warning: Some keg-only formula are linked into the Cellar.
Linking a keg-only formula, such as gettext, into the cellar with
`brew link <formula>` will cause other formulae to detect them during
the `./configure` step. This may cause problems when compiling those
other formulae.

Binaries provided by keg-only formulae may override system binaries
with other strange results.

You may wish to `brew unlink` these brews:
  tomcat@7
```

# Formula additions or changes
To get formulae added or changed in Homebrew please file a [Pull Request](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)
We will close issues requesting formulae changes.

**Comment by ilovezfs** [comment]
Can you try

```
rm -rf /Users/karl.fritsche/.gem/ruby/2.4.0/gems/psych-2.2.4
```

**Comment by attrib** [comment]
Didn't worked.

```
$ rm -rf /Users/karl.fritsche/.gem/ruby/2.4.0/gems/psych-2.2.4
$ gem
/usr/local/Cellar/ruby/2.4.2/lib/ruby/2.4.0/yaml.rb:5:in `<top (required)>':
It seems your ruby installation is missing psych (for YAML output).
To eliminate this warning, please install libyaml and reinstall your ruby.
/usr/local/Cellar/ruby/2.4.2/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require': dlopen(/Users/karl.fritsche/.gem/ruby/2.4.0/extensions/x86_64-darwin-16/2.4.0/psych-2.2.4/psych.bundle, 9): Library not loaded: /usr/local/opt/ruby/lib/libruby.2.4.1.dylib (LoadError)
  Referenced from: /Users/karl.fritsche/.gem/ruby/2.4.0/extensions/x86_64-darwin-16/2.4.0/psych-2.2.4/psych.bundle
  Reason: image not found - /Users/karl.fritsche/.gem/ruby/2.4.0/extensions/x86_64-darwin-16/2.4.0/psych-2.2.4/psych.bundle
	from /usr/local/Cellar/ruby/2.4.2/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/local/Cellar/ruby/2.4.2/lib/ruby/2.4.0/psych.rb:8:in `<top (required)>'
	from /usr/local/Cellar/ruby/2.4.2/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/local/Cellar/ruby/2.4.2/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/local/Cellar/ruby/2.4.2/lib/ruby/2.4.0/yaml.rb:6:in `<top (required)>'
	from /usr/local/Cellar/ruby/2.4.2/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/local/Cellar/ruby/2.4.2/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/local/Cellar/ruby/2.4.2/lib/ruby/2.4.0/rubygems.rb:701:in `load_yaml'
	from /usr/local/Cellar/ruby/2.4.2/lib/ruby/2.4.0/rubygems/config_file.rb:340:in `load_file'
	from /usr/local/Cellar/ruby/2.4.2/lib/ruby/2.4.0/rubygems/config_file.rb:202:in `initialize'
	from /usr/local/Cellar/ruby/2.4.2/lib/ruby/2.4.0/rubygems/gem_runner.rb:75:in `new'
	from /usr/local/Cellar/ruby/2.4.2/lib/ruby/2.4.0/rubygems/gem_runner.rb:75:in `do_configuration'
	from /usr/local/Cellar/ruby/2.4.2/lib/ruby/2.4.0/rubygems/gem_runner.rb:40:in `run'
	from /usr/local/bin/gem:21:in `<main>'
```

Tried to remove all in user and reinstall ruby.

```
$ rm -rf ~/.gem/ruby/2.4.0/gems/
$ brew remove --force ruby # remove all versions installed
Uninstalling ruby... (1,191 files, 15.3MB)
$ sudo rm -rf /usr/local/lib/ruby # remove all gems and leftover files
Password:
Sorry, try again.
Password:
karl.fritsche@MBP-133-Karl-Fritsche ~ $ brew install ruby
Updating Homebrew...
==> Auto-updated Homebrew!
Updated 1 tap (homebrew/core).
No changes to formulae.

==> Downloading https://homebrew.bintray.com/bottles/ruby-2.4.2.sierra.bottle.tar.gz
Already downloaded: /Users/karl.fritsche/Library/Caches/Homebrew/ruby-2.4.2.sierra.bottle.tar.gz
==> Pouring ruby-2.4.2.sierra.bottle.tar.gz
==> Caveats
Emacs Lisp files have been installed to:
  /usr/local/share/emacs/site-lisp/ruby
==> Summary
🍺  /usr/local/Cellar/ruby/2.4.2: 1,191 files, 15.3MB
$ gem install bundler
/usr/local/Cellar/ruby/2.4.2/lib/ruby/2.4.0/yaml.rb:5:in `<top (required)>':
It seems your ruby installation is missing psych (for YAML output).
To eliminate this warning, please install libyaml and reinstall your ruby.
/usr/local/Cellar/ruby/2.4.2/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require': dlopen(/Users/karl.fritsche/.gem/ruby/2.4.0/extensions/x86_64-darwin-16/2.4.0/psych-2.2.4/psych.bundle, 9): Library not loaded: /usr/local/opt/ruby/lib/libruby.2.4.1.dylib (LoadError)
  Referenced from: /Users/karl.fritsche/.gem/ruby/2.4.0/extensions/x86_64-darwin-16/2.4.0/psych-2.2.4/psych.bundle
  Reason: image not found - /Users/karl.fritsche/.gem/ruby/2.4.0/extensions/x86_64-darwin-16/2.4.0/psych-2.2.4/psych.bundle
	from /usr/local/Cellar/ruby/2.4.2/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/local/Cellar/ruby/2.4.2/lib/ruby/2.4.0/psych.rb:8:in `<top (required)>'
	from /usr/local/Cellar/ruby/2.4.2/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/local/Cellar/ruby/2.4.2/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/local/Cellar/ruby/2.4.2/lib/ruby/2.4.0/yaml.rb:6:in `<top (required)>'
	from /usr/local/Cellar/ruby/2.4.2/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/local/Cellar/ruby/2.4.2/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/local/Cellar/ruby/2.4.2/lib/ruby/2.4.0/rubygems.rb:701:in `load_yaml'
	from /usr/local/Cellar/ruby/2.4.2/lib/ruby/2.4.0/rubygems/config_file.rb:340:in `load_file'
	from /usr/local/Cellar/ruby/2.4.2/lib/ruby/2.4.0/rubygems/config_file.rb:202:in `initialize'
	from /usr/local/Cellar/ruby/2.4.2/lib/ruby/2.4.0/rubygems/gem_runner.rb:75:in `new'
	from /usr/local/Cellar/ruby/2.4.2/lib/ruby/2.4.0/rubygems/gem_runner.rb:75:in `do_configuration'
	from /usr/local/Cellar/ruby/2.4.2/lib/ruby/2.4.0/rubygems/gem_runner.rb:40:in `run'
	from /usr/local/bin/gem:21:in `<main>' 
```

**Comment by ilovezfs** [comment]
OK try this:
```
mv ~/.gem ~/old_dot_gem
```
and then try again

**Comment by attrib** [comment]
That seems to work:

```
$ mv ~/.gem ~/old_dot_gem
$ rm -rf ~/.gem/ruby/2.4.0/gems/
$ brew remove --force ruby
Uninstalling ruby... (1,191 files, 15.3MB)
$ sudo rm -rf /usr/local/lib/ruby
Password:
$ brew install ruby
==> Downloading https://homebrew.bintray.com/bottles/ruby-2.4.2.sierra.bottle.tar.gz
Already downloaded: /Users/karl.fritsche/Library/Caches/Homebrew/ruby-2.4.2.sierra.bottle.tar.gz
==> Pouring ruby-2.4.2.sierra.bottle.tar.gz
==> Caveats
Emacs Lisp files have been installed to:
  /usr/local/share/emacs/site-lisp/ruby
==> Summary
🍺  /usr/local/Cellar/ruby/2.4.2: 1,191 files, 15.3MB
$ gem install bundler
Fetching: bundler-1.15.4.gem (100%)
Successfully installed bundler-1.15.4
Parsing documentation for bundler-1.15.4
Installing ri documentation for bundler-1.15.4
Done installing documentation for bundler after 4 seconds
1 gem installed
```

Is there anything needs to be fixed in the update process for others?

**Comment by ilovezfs** [comment]
>Is there anything needs to be fixed in the update process for others?

I don't think so since this is really a ruby issue as opposed to a Homebrew issue, but I'm really glad you reported this since we at least know another way it can go :boom: and how to work around it.

**Comment by attrib** [comment]
Thanks for the help.

**Comment by ilovezfs** [comment]
You're welcome!

**Comment by lekimtek** [comment]
Same problem in ubuntu, how to in linux, whith no brew?
