### ISSUE TITLE
gom does not build from source

### ISSUE THREAD

**Issue by fxcoudert** [Homebrew/homebrew-core#19052]
`gom` fails to build from source [on all macOS version from 10.11 to 10.13](https://jenkins.brew.sh/job/Homebrew%20Testing/271/).

```
[35/37] Generating Gom-1.0.gir with a custom command.
FAILED: gom/Gom-1.0.gir 
/usr/local/opt/gobject-introspection/bin/g-ir-scanner ../gom/gom.h ../gom/gom-adapter.h ../gom/gom-command-builder.h ../gom/gom-command.h ../gom/gom-cursor.h ../gom/gom-error.h ../gom/gom-filter.h ../gom/gom-repository.h ../gom/gom-resource-group.h ../gom/gom-resource.h ../gom/gom-autocleanups.h ../gom/gom-sorting.h ../gom/gom-adapter.c ../gom/gom-command-builder.c ../gom/gom-command.c ../gom/gom-cursor.c ../gom/gom-error.c ../gom/gom-filter.c ../gom/gom-repository.c ../gom/gom-resource.c ../gom/gom-resource-group.c ../gom/gom-sorting.c -D_REENTRANT -I/usr/local/Cellar/libffi/3.2.1/lib/libffi-3.2.1/include -I/usr/local/Cellar/pcre/8.41/include -I/usr/local/Cellar/glib/2.54.1/include/glib-2.0 -I/usr/local/Cellar/glib/2.54.1/lib/glib-2.0/include -I/usr/local/opt/gettext/include -I/usr/local/Cellar/gobject-introspection/1.54.1/include/gobject-introspection-1.0 --no-libtool --namespace=Gom --nsversion=1.0 --warn-all --output gom/Gom-1.0.gir -I/private/tmp/gom-20171005-15973-1nidqb5/gom-0.3.3/gom -I/private/tmp/gom-20171005-15973-1nidqb5/gom-0.3.3/build/gom --include=Gio-2.0 --include=GObject-2.0 --symbol-prefix=gom --identifier-prefix=Gom --cflags-begin -D_REENTRANT -I/usr/local/Cellar/pcre/8.41/include -I/usr/local/Cellar/glib/2.54.1/include/glib-2.0 -I/usr/local/Cellar/glib/2.54.1/lib/glib-2.0/include -I/usr/local/opt/gettext/include -I/usr/local/Cellar/sqlite/3.20.1/include --cflags-end -L/private/tmp/gom-20171005-15973-1nidqb5/gom-0.3.3/build/gom -L/usr/local/Cellar/glib/2.54.1/lib -L/usr/local/opt/gettext/lib --extra-library=gio-2.0 --extra-library=gobject-2.0 --extra-library=glib-2.0 --extra-library=intl -L/usr/local/Cellar/sqlite/3.20.1/lib --extra-library=sqlite3 -L/private/tmp/gom-20171005-15973-1nidqb5/gom-0.3.3/build/gom --library gom-1.0
In file included from /private/tmp/gom-20171005-15973-1nidqb5/gom-0.3.3/build/tmp-introspectbIkwzL/Gom-1.0.c:2:
In file included from /usr/local/Cellar/glib/2.54.1/include/glib-2.0/glib.h:30:
In file included from /usr/local/Cellar/glib/2.54.1/include/glib-2.0/glib/galloca.h:32:
/usr/local/Cellar/glib/2.54.1/include/glib-2.0/glib/gtypes.h:423:3: error: '_GStaticAssertCompileTimeAssertion_0' declared as an array with a negative size
  G_STATIC_ASSERT(sizeof (unsigned long long) == sizeof (guint64));
  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/local/Cellar/glib/2.54.1/include/glib-2.0/glib/gmacros.h:232:103: note: expanded from macro 'G_STATIC_ASSERT'
#define G_STATIC_ASSERT(expr) typedef char G_PASTE (_GStaticAssertCompileTimeAssertion_, __COUNTER__)[(expr) ? 1 : -1] G_GNUC_UNUSED
                                                                                                      ^~~~~~~~~~~~~~~
1 error generated.
Traceback (most recent call last):
  File "/usr/local/opt/gobject-introspection/bin/g-ir-scanner", line 66, in <module>
    sys.exit(scanner_main(sys.argv))
  File "/usr/local/Cellar/gobject-introspection/1.54.1/lib/gobject-introspection/giscanner/scannermain.py", line 547, in scanner_main
    shlibs = create_binary(transformer, options, args)
  File "/usr/local/Cellar/gobject-introspection/1.54.1/lib/gobject-introspection/giscanner/scannermain.py", line 422, in create_binary
    gdump_parser.get_error_quark_functions())
  File "/usr/local/Cellar/gobject-introspection/1.54.1/lib/gobject-introspection/giscanner/dumper.py", line 302, in compile_introspection_binary
    return dc.run()
  File "/usr/local/Cellar/gobject-introspection/1.54.1/lib/gobject-introspection/giscanner/dumper.py", line 168, in run
    introspection_obj = self._compile(c_path)
  File "/usr/local/Cellar/gobject-introspection/1.54.1/lib/gobject-introspection/giscanner/dumper.py", line 208, in _compile
    self._options.init_sections)
  File "/usr/local/Cellar/gobject-introspection/1.54.1/lib/gobject-introspection/giscanner/ccompiler.py", line 251, in compile
    output_dir=os.path.abspath(os.sep))
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/ccompiler.py", line 574, in compile
    self._compile(obj, src, ext, cc_args, extra_postargs, pp_opts)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/unixccompiler.py", line 122, in _compile
    raise CompileError, msg
distutils.errors.CompileError: command 'clang' failed with exit status 1
ninja: build stopped: subcommand failed.
```

**Comment by dunn** [comment]
Arguably not supported on macOS then huh

**Comment by DomT4** [comment]
Leave it be bot, it's still a problem.

**Comment by ilovezfs** [comment]
This is the same as https://github.com/Homebrew/homebrew-core/issues/5404. Fixed by https://github.com/Homebrew/homebrew-core/pull/20107.

**Comment by ilovezfs** [comment]
Closed via https://github.com/Homebrew/homebrew-core/pull/20107.
