### ISSUE TITLE
`brew install root` missing CPython symbol

### ISSUE THREAD

**Issue by vepadulano** [Homebrew/homebrew-core#195193]
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

```shell
╰─➤  brew config                                                                                                      1 ↵
HOMEBREW_VERSION: 4.4.2
ORIGIN: https://github.com/Homebrew/brew
HEAD: 35ebf4a047b00b2b3de33ba0081d71293cdadede
Last commit: 32 hours ago
Core tap JSON: 22 Oct 07:33 UTC
Core cask tap JSON: 22 Oct 07:33 UTC
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_DISPLAY: /private/tmp/com.apple.launchd.cMyr3s23zQ/org.xquartz:0
HOMEBREW_MAKE_JOBS: 12
Homebrew Ruby: 3.3.5 => /opt/homebrew/Library/Homebrew/vendor/portable-ruby/3.3.5/bin/ruby
CPU: dodeca-core 64-bit arm_lobos
Clang: 16.0.0 build 1600
Git: 2.39.5 => /Applications/Xcode.app/Contents/Developer/usr/bin/git
Curl: 8.7.1 => /usr/bin/curl
macOS: 15.0-arm64
CLT: 16.0.0.0.1.1724870825
Xcode: 16.0
Rosetta 2: false
```

```
╰─➤  brew doctor
Your system is ready to brew.
```
```


### Verification

- [X] My `brew doctor` output says `Your system is ready to brew.` and am still able to reproduce my issue.
- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.
- [X] I searched for recent similar issues at https://github.com/Homebrew/homebrew-core/issues?q=is%3Aissue and found no duplicates.

### What were you trying to do (and why)?

I am installing the `root` formula on my MacOS 15 machine, i.e. `brew install root`.

### What happened (include all command output)?

Installing the formula produces a package that when imported within a Python session cannot find a symbol from the CPython library:

```
PYTHONPATH=$PYTHONPATH:/opt/homebrew/Cellar/root/6.32.06/lib/root python3                                      130 ↵
Python 3.13.0 (main, Oct  7 2024, 05:02:14) [Clang 16.0.0 (clang-1600.0.26.3)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import ROOT
Traceback (most recent call last):
  File "<python-input-0>", line 1, in <module>
    import ROOT
  File "/opt/homebrew/Cellar/root/6.32.06/lib/root/ROOT/__init__.py", line 25, in <module>
    import cppyy
  File "/opt/homebrew/Cellar/root/6.32.06/lib/root/cppyy/__init__.py", line 81, in <module>
    from ._cpython_cppyy import *
  File "/opt/homebrew/Cellar/root/6.32.06/lib/root/cppyy/_cpython_cppyy.py", line 22, in <module>
    import libcppyy as _backend
ImportError: dlopen(/opt/homebrew/Cellar/root/6.32.06/lib/root/libcppyy.so, 0x0002): symbol not found in flat namespace '__Py_HashPointer'
```

Searching online for that type of error led me to https://stackoverflow.com/questions/35006614/what-does-symbol-not-found-expected-in-flat-namespace-actually-mean . Can this be some issue with the formula installation system? Let me know what other type of information I can provide.



### What did you expect to happen?

Fully working installation of the `root` formula

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
`brew install root`
```

**Comment by carlocab** [comment]
`root` is currently built with `python@3.12`, so you must use that with the Python bindings.

**Comment by carlocab** [comment]
The Python version used by `root` should be shown by `brew info root`. Or, alternatively:
```
❯ brew deps --direct root | grep python
python@3.12
```

**Comment by vepadulano** [comment]
That's great! Thank you so much!!!
