### ISSUE TITLE
glib: locally compiled version has linking errors in typelib

### ISSUE THREAD

**Issue by amolenaar** [Homebrew/homebrew-core#197684]
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

```shell
$ brew config
HOMEBREW_VERSION: 4.4.5-25-g2fb6bf0
ORIGIN: https://github.com/Homebrew/brew
HEAD: 2fb6bf05fbf0984fe7a6ab1476537d657a9fab01
Last commit: 18 hours ago
Core tap HEAD: 0e1ea721ec2ea60deec81fd0947bfaf22ca1c7ae
Core tap last commit: 73 minutes ago
Core tap JSON: 14 Nov 11:50 UTC
Core cask tap HEAD: a48e56b00aa37431851fce451202e08edda4f6c5
Core cask tap last commit: 9 minutes ago
Core cask tap JSON: 14 Nov 11:50 UTC
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_GITHUB_API_TOKEN: set
HOMEBREW_MAKE_JOBS: 8
HOMEBREW_SORBET_RUNTIME: set
Homebrew Ruby: 3.3.6 => /opt/homebrew/Library/Homebrew/vendor/portable-ruby/3.3.6/bin/ruby
CPU: octa-core 64-bit arm_blizzard_avalanche
Clang: 16.0.0 build 1600
Git: 2.39.5 => /Applications/Xcode.app/Contents/Developer/usr/bin/git
Curl: 8.7.1 => /usr/bin/curl
macOS: 14.7.1-arm64
CLT: 16.1.0.0.1.1729049160
Xcode: 16.1
Rosetta 2: false
```

```
$ brew doctor
Your system is ready to brew.
```
```


### Verification

- [X] My `brew doctor` output says `Your system is ready to brew.` and am still able to reproduce my issue.
- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.
- [X] I searched for recent similar issues at https://github.com/Homebrew/homebrew-core/issues?q=is%3Aissue and found no duplicates.

### What were you trying to do (and why)?

I'm trying to compile and install GLib locally.
I use the command

```bash
brew install --build-from-source -v glib
```

However, when I use the typelibs to access the libraries, they point to the temporary folder used to create the "staging" build for GLib.

### What happened (include all command output)?

GLib compiles and installs.

But when I look at, for example, the typelib gile for GLib, you'll see it points to a library on a temporary path:

These kinds of errors is what I see, also in the PR build (#193345):

```
** (process:73712): WARNING **: 15:55:00.351: Failed to load shared library '/private/tmp/glib-20241112-7885-wadaqq/glib-2.82.2/staging/lib/libgobject-2.0.0.dylib' referenced by the typelib: dlopen(/private/tmp/glib-20241112-7885-wadaqq/glib-2.82.2/staging/lib/libgobject-2.0.0.dylib, 0x0009): tried: '/private/tmp/glib-20241112-7885-wadaqq/glib-2.82.2/staging/lib/libgobject-2.0.0.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/private/tmp/glib-20241112-7885-wadaqq/glib-2.82.2/staging/lib/libgobject-2.0.0.dylib' (no such file), '/private/tmp/glib-20241112-7885-wadaqq/glib-2.82.2/staging/lib/libgobject-2.0.0.dylib' (no such file)
```

`/private/tmp/glib-20241112-7885-wadaqq/glib-2.82.2/staging` points to the folder where the staging build happened.

```
$ strings /opt/homebrew/lib/girepository-1.0/GLib-2.0.typelib | head
GOBJ
METADATA
GLib
/private/tmp/glib-20241114-44813-gq42du/glib-2.82.2/staging/lib/libgobject-2.0.0.dylib,libglib-2.0.0.dylib
```

### What did you expect to happen?

I would expect a local installation to work, similarly to how the bottled version works.

Typelibs should not point to libraries in `/private`.

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
brew install --build-from-source -v glib
brew install pygobject3
```

```
/opt/homebrew/bin/python3 -c "from gi.repository import GLib"
```

Output:

```
** (process:54915): WARNING **: 13:30:17.245: Failed to load shared library '/private/tmp/glib-20241114-44813-gq42du/glib-2.82.2/staging/lib/libgobject-2.0.0.dylib' referenced by the typelib: dlopen(/private/tmp/glib-20241114-44813-gq42du/glib-2.82.2/staging/lib/libgobject-2.0.0.dylib, 0x0009): tried: '/opt/gtk/lib/libgobject-2.0.0.dylib' (no such file), '/private/tmp/glib-20241114-44813-gq42du/glib-2.82.2/staging/lib/libgobject-2.0.0.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/private/tmp/glib-20241114-44813-gq42du/glib-2.82.2/staging/lib/libgobject-2.0.0.dylib' (no such file), '/private/tmp/glib-20241114-44813-gq42du/glib-2.82.2/staging/lib/libgobject-2.0.0.dylib' (no such file)
Traceback (most recent call last):
  File "<string>", line 1, in <module>
    from gi.repository import GLib
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 921, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 813, in module_from_spec
  File "/opt/homebrew/lib/python3.13/site-packages/gi/importer.py", line 147, in create_module
    dynamic_module = load_overrides(introspection_module)
  File "/opt/homebrew/lib/python3.13/site-packages/gi/overrides/__init__.py", line 112, in load_overrides
    override_mod = importlib.import_module(override_package_name)
  File "/opt/homebrew/Cellar/python@3.13/3.13.0_1/Frameworks/Python.framework/Versions/3.13/lib/python3.13/importlib/__init__.py", line 88, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.13/site-packages/gi/overrides/GLib.py", line 500, in <module>
    MainLoop = override(MainLoop)
  File "/opt/homebrew/lib/python3.13/site-packages/gi/overrides/__init__.py", line 189, in override
    assert g_type != TYPE_NONE
           ^^^^^^^^^^^^^^^^^^^
AssertionError
```
```

**Comment by carlocab** [comment]
Does applying the patch in https://github.com/Homebrew/homebrew-core/pull/193345#discussion_r1828127494 not work?

In any case -- we don't track problems with source builds in issues. We can continue the discussion at #193345.
