### ISSUE TITLE
Fail to install glibc on OpenSuse Leap 42.3: failure executing (..)ldd (..)gencat not a dynamic executable

### ISSUE THREAD

**Issue by KarlHeitmann** [Homebrew/homebrew-core#20123]
**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

# Please always follow these steps:
- [x] Confirmed this is a problem with `brew install`ing one, specific Homebrew/homebrew-core formula (not cask or tap) and not every time you run `brew`? If it's a general `brew` problem please file this issue at https://github.com/Homebrew/brew/issues/new. If it's a `brew cask` problem please file this issue at https://github.com/caskroom/homebrew-cask/issues/new. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed all issues and retried your prior step?
- [x] Ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?

> https://gist.github.com/KarlHeitmann/e6b36e47353c1c8317cad798438bf4c9

- [ ] If `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

To help us debug your issue please explain:
- What you were trying to do (and why)
I want to start working with NodeJS, I have experience with rbenv and rvm, since I come from RoR world. I understand that brew is some kind of rbenv for javascript. So, I follow http://blog.teamtreehouse.com/install-node-js-npm-linux , and when I've got to the point where you are told to install node, I've had problems.

- What happened (include command output)
When I reached this step on the guide:

> brew install node

The formula crashed when brew tried to compile and install the dependency glibc. I've found only one similar issue on [**Linuxbrew** repository](https://github.com/Linuxbrew/homebrew-core/issues/3361), where " sjackman commented on Jul 29 " suggests to run the command:

> brew install -d glibc

This is the output of this command:
```
/home/karl/.linuxbrew/Homebrew/Library/Homebrew/brew.rb (Formulary::FormulaLoader): loading /home/karl/.linuxbrew/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/glibc.rb
/home/karl/.linuxbrew/Homebrew/Library/Homebrew/brew.rb (Formulary::FormulaLoader): loading /home/karl/.linuxbrew/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/binutils.rb
/home/karl/.linuxbrew/Homebrew/Library/Homebrew/brew.rb (Formulary::FormulaLoader): loading /home/karl/.linuxbrew/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/zlib.rb
/home/karl/.linuxbrew/Homebrew/Library/Homebrew/brew.rb (Formulary::FormulaLoader): loading /home/karl/.linuxbrew/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/linux-headers.rb
/home/karl/.linuxbrew/Homebrew/Library/Homebrew/brew.rb (Formulary::FormulaLoader): loading /home/karl/.linuxbrew/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/patchelf.rb
/home/karl/.linuxbrew/Homebrew/Library/Homebrew/brew.rb (Formulary::FormulaLoader): loading /home/karl/.linuxbrew/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/gcc.rb
/home/karl/.linuxbrew/Homebrew/Library/Homebrew/brew.rb (Formulary::FormulaLoader): loading /home/karl/.linuxbrew/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/bzip2.rb
/home/karl/.linuxbrew/Homebrew/Library/Homebrew/brew.rb (Formulary::FormulaLoader): loading /home/karl/.linuxbrew/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/gmp.rb
/home/karl/.linuxbrew/Homebrew/Library/Homebrew/brew.rb (Formulary::FormulaLoader): loading /home/karl/.linuxbrew/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/xz.rb
/home/karl/.linuxbrew/Homebrew/Library/Homebrew/brew.rb (Formulary::FormulaLoader): loading /home/karl/.linuxbrew/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/m4.rb
/home/karl/.linuxbrew/Homebrew/Library/Homebrew/brew.rb (Formulary::FormulaLoader): loading /home/karl/.linuxbrew/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/libmpc.rb
/home/karl/.linuxbrew/Homebrew/Library/Homebrew/brew.rb (Formulary::FormulaLoader): loading /home/karl/.linuxbrew/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/mpfr.rb
/home/karl/.linuxbrew/Homebrew/Library/Homebrew/brew.rb (Formulary::FormulaLoader): loading /home/karl/.linuxbrew/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/isl.rb
/home/karl/.linuxbrew/Homebrew/Library/Homebrew/build.rb (Formulary::FromPathLoader): loading /home/karl/.linuxbrew/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/glibc.rb
/home/karl/.linuxbrew/Homebrew/Library/Homebrew/build.rb (Formulary::FormulaLoader): loading /home/karl/.linuxbrew/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/binutils.rb
/home/karl/.linuxbrew/Homebrew/Library/Homebrew/build.rb (Formulary::FormulaLoader): loading /home/karl/.linuxbrew/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/zlib.rb
/home/karl/.linuxbrew/Homebrew/Library/Homebrew/build.rb (Formulary::FormulaLoader): loading /home/karl/.linuxbrew/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/linux-headers.rb
/home/karl/.linuxbrew/Homebrew/Library/Homebrew/build.rb (Formulary::FormulaLoader): loading /home/karl/.linuxbrew/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/gcc.rb
/home/karl/.linuxbrew/Homebrew/Library/Homebrew/build.rb (Formulary::FormulaLoader): loading /home/karl/.linuxbrew/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/gcc@4.8.rb
==> Downloading https://ftp.gnu.org/gnu/glibc/glibc-2.23.tar.gz
Already downloaded: /home/karl/.cache/Homebrew/glibc-2.23.tar.gz
==> ../configure --disable-debug --disable-dependency-tracking --disable-silent-rules --prefix=/home/karl/.linuxbrew/Cellar/glibc/2.23 --enable-obsolete-rpc --without-selinux --with-binutils=/home/karl/.linuxb
==> make
==> make install
==> Kept temporary files
Temporary files retained at /tmp/glibc-20171031-23766-bto824
Error: Failure while executing: /home/karl/.linuxbrew/Cellar/glibc/2.23/bin/ldd /home/karl/.linuxbrew/Cellar/glibc/2.23/bin/gencat
        not a dynamic executable
 
/home/karl/.linuxbrew/Homebrew/Library/Homebrew/debrew.rb:11:in `raise'
/home/karl/.linuxbrew/Homebrew/Library/Homebrew/os/linux/elf.rb:60:in `initialize'
/home/karl/.linuxbrew/Homebrew/Library/Homebrew/os/linux/elf.rb:101:in `new'
/home/karl/.linuxbrew/Homebrew/Library/Homebrew/os/linux/elf.rb:101:in `metadata'
/home/karl/.linuxbrew/Homebrew/Library/Homebrew/os/linux/elf.rb:112:in `dynamically_linked_libraries'
/home/karl/.linuxbrew/Homebrew/Library/Homebrew/extend/os/linux/keg_relocate.rb:58:in `block in detect_cxx_stdlibs'
/home/karl/.linuxbrew/Homebrew/Library/Homebrew/extend/os/linux/keg_relocate.rb:56:in `each'
/home/karl/.linuxbrew/Homebrew/Library/Homebrew/extend/os/linux/keg_relocate.rb:56:in `detect_cxx_stdlibs'
/home/karl/.linuxbrew/Homebrew/Library/Homebrew/cxxstdlib.rb:26:in `check_compatibility'
/home/karl/.linuxbrew/Homebrew/Library/Homebrew/build.rb:172:in `detect_stdlibs'
/home/karl/.linuxbrew/Homebrew/Library/Homebrew/build.rb:158:in `block (2 levels) in install'
/home/karl/.linuxbrew/Homebrew/Library/Homebrew/formula.rb:1093:in `block in brew'
/home/karl/.linuxbrew/Homebrew/Library/Homebrew/formula.rb:1911:in `block in stage'
/home/karl/.linuxbrew/Homebrew/Library/Homebrew/resource.rb:97:in `block in unpack'
/home/karl/.linuxbrew/Homebrew/Library/Homebrew/extend/fileutils.rb:14:in `block in mktemp'
/home/karl/.linuxbrew/Homebrew/Library/Homebrew/extend/fileutils.rb:74:in `block in run'
/home/karl/.linuxbrew/Homebrew/Library/Homebrew/extend/fileutils.rb:74:in `chdir'
/home/karl/.linuxbrew/Homebrew/Library/Homebrew/extend/fileutils.rb:74:in `run'
/home/karl/.linuxbrew/Homebrew/Library/Homebrew/extend/fileutils.rb:13:in `mktemp'
/home/karl/.linuxbrew/Homebrew/Library/Homebrew/resource.rb:93:in `unpack'
/home/karl/.linuxbrew/Homebrew/Library/Homebrew/resource.rb:85:in `stage'
/home/karl/.linuxbrew/Homebrew/Library/Homebrew/formula.rb:1888:in `stage'
/home/karl/.linuxbrew/Homebrew/Library/Homebrew/formula.rb:1088:in `brew'
/home/karl/.linuxbrew/Homebrew/Library/Homebrew/build.rb:127:in `block in install'
/home/karl/.linuxbrew/Homebrew/Library/Homebrew/utils.rb:557:in `with_env'
/home/karl/.linuxbrew/Homebrew/Library/Homebrew/build.rb:124:in `install'
/home/karl/.linuxbrew/Homebrew/Library/Homebrew/build.rb:205:in `<main>'
```
- What you expected to happen
I expected to download and install nodejs and all of it's dependencies succesfully.

- Step-by-step reproduction instructions (by running `brew install` commands)
I have already installed gcc, makefile and development tools on my opensuse 43.3

I have OpenSuse Leap 42.3
1. installation via package manager zypper, build essentials
2. installation homebrew
> ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/linuxbrew/go/install)"
3. add 3 lines to my .bashrc
> export PATH="$HOME/.linuxbrew/bin:$PATH"
> export MANPATH="$HOME/.linuxbrew/share/man:$MANPATH"
> export INFOPATH="$HOME/.linuxbrew/share/info:$INFOPATH"
4. installation node
> brew install node

**FAILURE**
```
Already downloaded: /home/karl/.cache/Homebrew/glibc-2.23.tar.gz
==> ../configure --disable-debug --disable-dependency-tracking --disable-silent-rules --prefix=/home/karl/.linuxbrew/Cellar/glibc/2.23 --enable-obsolete-rpc --without-selinux --with-binutils=/home/karl/.linuxb
==> make
==> make install
Error: Failure while executing: /home/karl/.linuxbrew/Cellar/glibc/2.23/bin/ldd /home/karl/.linuxbrew/Cellar/glibc/2.23/bin/gencat
        not a dynamic executable
```

Hope this information would be usefull, I'll be glad to give you more details if this is not enough.
In advance, thanks for your help

# Formula additions or changes
[  ] To get formulae added or changed in Homebrew please file a [Pull Request](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)
We will close issues requesting formulae changes.

**Comment by ilovezfs** [comment]
This is Homebrew not Linuxbrew.
