### ISSUE TITLE
AWS CLI is confused about python versions

### ISSUE THREAD

**Issue by axman6** [Homebrew/homebrew-core#20343]
After updating `awscli`, I can no longer execute any `aws` commands without throwing an exception. Googling the error `aws cli AttributeError: module 'enum' has no attribute 'IntFlag'` returns no useful results. As you can see in the output below, it appears to be trying to use a mixture of python2.7 and python3.6 to execute. Uninstalling awscli and reinstalling doesn't help.

```shell
$ aws --help
Failed to import the site module
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/site.py", line 73, in <module>
    __boot()
  File "/usr/local/lib/python2.7/site-packages/site.py", line 22, in __boot
    loader.load_module('site')
  File "/usr/local/Cellar/awscli/1.11.180_1/libexec/bin/../lib/python3.6/site.py", line 703, in <module>
    main()
  File "/usr/local/Cellar/awscli/1.11.180_1/libexec/bin/../lib/python3.6/site.py", line 694, in main
    execsitecustomize()
  File "/usr/local/Cellar/awscli/1.11.180_1/libexec/bin/../lib/python3.6/site.py", line 548, in execsitecustomize
    import sitecustomize
  File "/usr/local/lib/python2.7/site-packages/sitecustomize.py", line 4, in <module>
    import re
  File "/usr/local/Cellar/awscli/1.11.180_1/libexec/lib/python3.6/re.py", line 142, in <module>
    class RegexFlag(enum.IntFlag):
AttributeError: module 'enum' has no attribute 'IntFlag'
```

# Please always follow these steps:
- [x] Confirmed this is a problem with `brew install`ing one, specific Homebrew/homebrew-core formula (not cask or tap) and not every time you run `brew`? If it's a general `brew` problem please file this issue at https://github.com/Homebrew/brew/issues/new. If it's a `brew cask` problem please file this issue at https://github.com/caskroom/homebrew-cask/issues/new. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed all issues and retried your prior step?
- [x] Ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
```
$ brew gist-logs awscli  
Error: No logs.
```
- [x] If `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?
```
$ brew config          
HOMEBREW_VERSION: 1.3.6-190-ge300713
ORIGIN: https://github.com/Homebrew/brew.git
HEAD: e300713f253029ef91a86bc4006d316582fc6d13
Last commit: 32 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 09c4dd5f89931a49fb2679df3ad05d38b96372e1
Core tap last commit: 5 hours ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_DEV_CMD_RUN: 1
HOMEBREW_GIT_CONFIG_FILE: /usr/local/Homebrew/.git/config
HOMEBREW_NO_AUTO_UPDATE: 1
CPU: octa-core 64-bit haswell
Homebrew Ruby: 2.3.3 => /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/bin/ruby
Clang: 9.0 build 900
Git: 2.15.0 => /usr/local/bin/git
Curl: 7.54.0 => /usr/bin/curl
Perl: /usr/bin/perl
Python: /usr/local/opt/python/libexec/bin/python => /usr/local/Cellar/python/2.7.14/Frameworks/Python.framework/Versions/2.7/bin/python2.7
Ruby: /usr/bin/ruby => /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin/ruby
Java: 1.8.0_25, 1.7.0_75
macOS: 10.12.6-x86_64
Xcode: 9.1
CLT: 9.0.1.0.1.1506734476
X11: 2.7.11 => /opt/X11

$ brew doctor          
Your system is ready to brew.
```

**Comment by ilovezfs** [comment]
I cannot reproduce this issue.

```
iMac-TMP:~ joe$ aws --help
usage: aws [options] <command> <subcommand> [<subcommand> ...] [parameters]
To see help text, you can run:

  aws help
  aws <command> help
  aws <command> <subcommand> help
aws: error: the following arguments are required: command
```

**Comment by axman6** [comment]
Any idea why it would be trying to use the python2.7 site.py? I have no idea how to debug python problems.

**Comment by ilovezfs** [comment]
What's the output of
```
python -c 'import sitecustomize'
```
and
```
python3 -c 'import sitecustomize'
```

**Comment by axman6** [comment]
```shell
$ python -c 'import sitecustomize'

$ python3 -c 'import sitecustomize'
Failed to import the site module
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/site.py", line 73, in <module>
    __boot()
  File "/usr/local/lib/python2.7/site-packages/site.py", line 26, in __boot
    import imp  # Avoid import loop in Python >= 3.3
  File "/usr/local/Cellar/python3/3.6.3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/imp.py", line 27, in <module>
    import tokenize
  File "/usr/local/Cellar/python3/3.6.3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/tokenize.py", line 33, in <module>
    import re
  File "/usr/local/Cellar/python3/3.6.3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/re.py", line 142, in <module>
    class RegexFlag(enum.IntFlag):
AttributeError: module 'enum' has no attribute 'IntFlag'
```
So looks like it could be python3 which is broken (Happy to update title if appropriate)

**Comment by ilovezfs** [comment]
What's the output of
```
env | grep PY
```

**Comment by ilovezfs** [comment]
>Commenting that out fixes the issue.

:tada:
