### ISSUE TITLE
cannot import vtk in python after open-mpi update

### ISSUE THREAD

**Issue by mattia-** [Homebrew/homebrew-core#20421]
# Please always follow these steps:
- [x] Confirmed this is a problem with `brew install`ing one, specific Homebrew/homebrew-core formula (not cask or tap) and not every time you run `brew`? If it's a general `brew` problem please file this issue at https://github.com/Homebrew/brew/issues/new. If it's a `brew cask` problem please file this issue at https://github.com/caskroom/homebrew-cask/issues/new. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed all issues and retried your prior step?
- [x] Ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link? https://gist.github.com/dc6a6526d2f0526e119e58b99a4dbd90
- [x] If `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

To help us debug your issue please explain:
- What you were trying to do (and why)
I tried to import vtk in python (both installed with homebrew)
```
(ins)mattia@endor:vtk$ pwd
/usr/local/lib/python2.7/site-packages/vtk
(ins)mattia@endor:vtk$ echo $PYTHONPATH
/usr/local/lib/python2.7/site-packages/:
(ins)mattia@endor:vtk$ which python
/usr/local/opt/python/libexec/bin/python
(ins)mattia@endor:vtk$ python
Python 2.7.14 (default, Sep 25 2017, 09:53:17) 
[GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.42.1)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
(ins)>>> import vtk
```

- What happened (include command output)
The import failed
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/site-packages/vtk/__init__.py", line 100, in <module>
    from .vtkIOAMR import *
  File "/usr/local/lib/python2.7/site-packages/vtk/vtkIOAMR.py", line 9, in <module>
    from vtkIOAMRPython import *
ImportError: dlopen(./vtkIOAMRPython.so, 2): Library not loaded: /usr/local/opt/open-mpi/lib/libmpi.20.dylib
  Referenced from: /usr/local/lib/libhdf5.101.dylib
  Reason: image not found
(ins)>>> 
```

- What you expected to happen
The import should *not* fail. I believe the issue lies in the recent update of open-mpi. Indeed, the library referenced does not exist, but a different version is instead installed.
```
(ins)mattia@endor:vtk$ ll /usr/local/opt/open-mpi/lib/libmpi.20.dylib
ls: cannot access '/usr/local/opt/open-mpi/lib/libmpi.20.dylib': No such file or directory
(ins)mattia@endor:vtk$ ll /usr/local/opt/open-mpi/lib/libmpi.*.dylib
-r--r--r-- 1 mattia admin 1051144 Nov  5 17:09 /usr/local/opt/open-mpi/lib/libmpi.40.dylib
(ins)mattia@endor:vtk$ 
```
A simple recompilation and rebottle-ing could maybe do the trick (if I understand correctly)

- Step-by-step reproduction instructions (by running `brew install` commands)
Python and VTK were installed by using the standard commands
`brew install python vtk`

**Comment by mattia-** [comment]
On second though, this looks like a problem with the hdf5 bottle, rather than vtk itself. I will try to build hdf5 from source and see what happens to vtk.

Sorry for the hassle

**Comment by mattia-** [comment]
Yep, that was exactly it. Again, really sorry for the inconvenience.

Just in case anyone gets here looking for the solution, the problem was that I had installed hdf5 building it from source, so it was linked to the old version of open-mpi. Just run `brew reinstall hdf5 --build-from-source` and everything will start working again
