### ISSUE TITLE
brew upgrade failed with error message

### ISSUE THREAD

**Issue by zhenyulin** [Homebrew/homebrew-core#20657]
- Tried `brew install node`/`brew upgrade node`, it works fine; 

- Ran `brew doctor`, get the following error message
```
Unexpected header files:
  /usr/local/include/python2.7/greenlet/greenlet.h
  /usr/local/include/python3.6m/greenlet/greenlet.h
Error: formulae require at least a URL
Please report this bug:
  https://docs.brew.sh/Troubleshooting.html
/usr/local/Homebrew/Library/Homebrew/formula.rb:237:in `determine_active_spec'
/usr/local/Homebrew/Library/Homebrew/formula.rb:191:in `initialize'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:89:in `new'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:89:in `get_formula'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:280:in `factory'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:314:in `rescue in from_keg'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:310:in `from_keg'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:294:in `from_rack'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1384:in `block in installed'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1382:in `each'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1382:in `flat_map'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1382:in `installed'
/usr/local/Homebrew/Library/Homebrew/diagnostic.rb:869:in `check_missing_deps'
/usr/local/Homebrew/Library/Homebrew/cmd/doctor.rb:43:in `block in doctor'
/usr/local/Homebrew/Library/Homebrew/cmd/doctor.rb:35:in `each'
/usr/local/Homebrew/Library/Homebrew/cmd/doctor.rb:35:in `doctor'
/usr/local/Homebrew/Library/Homebrew/brew.rb:100:in `<main>'
```
It looks like it is a brew/formula problem, rather than cask/tap problem.

- `brew gist-logs cleanup` output below
```
Error: No available formula with the name "cleanup"
```

- `brew config` output is as below
```
HOMEBREW_VERSION: 1.3.7
ORIGIN: https://github.com/Homebrew/brew.git
HEAD: 441c212f2dd70f053ee21eac8398c5fe5dfd0551
Last commit: 4 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 8c40e71a15fe779a27d059823f1d9cd00a5f70c3
Core tap last commit: 2 hours ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_GIT_CONFIG_FILE: /usr/local/Homebrew/.git/config
CPU: octa-core 64-bit ivybridge
Homebrew Ruby: 2.3.3 => /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/bin/ruby
GCC-4.2: build 5666
Clang: 9.0 build 900
Git: 2.15.0 => /usr/local/bin/git
Curl: 7.54.0 => /usr/bin/curl
Perl: /usr/local/bin/perl => /usr/local/Cellar/perl/5.26.1/bin/perl
Python: /usr/local/opt/python/libexec/bin/python => /usr/local/Cellar/python/2.7.14/Frameworks/Python.framework/Versions/2.7/bin/python2.7
Ruby: /usr/local/bin/ruby => /usr/local/Cellar/ruby/2.4.2_1/bin/ruby
Java: 1.8.0_111
macOS: 10.13.1-x86_64
Xcode: 9.1
CLT: N/A
X11: 2.7.11 => /opt/X11
```

recently just upgraded to macOS 10.13.1, got the error message when firstly run `brew update`, and run `brew update` shows `All up-to-date.`, while run `brew upgrade` fails continuously with the above error message.

**Comment by ilovezfs** [comment]
What's the output of
```
HOMEBREW_DEVELOPER=1 brew install -dv node
```

**Comment by zhenyulin** [comment]
Hi @ilovezfs, thanks for following up.

This output the following:
```
Updating Homebrew...
==> Auto-updated Homebrew!
Updated Homebrew from 79e8cdd3ed to 2225febfb3.
Updated 4 taps (phinze/cask, homebrew/core, caskroom/drivers, caskroom/cask).
==> New Formulae
elasticsearch@5.6                                                       logstash@5.6
==> Updated Formulae
harfbuzz ✔        crystal-icr       kotlin            logstash          nickle            planck            shpotify          vault
azure-cli         elasticsearch     libfaketime       lxc               open-scene-graph  pqiv              sonarqube
citus             filebeat          libtrace          mariadb@10.1      opusfile          purescript        streamlink
cppad             heartbeat         lighttpd          metricbeat        pgrouting         scons             traefik
Error: formulae require at least a URL
Please report this bug:
  https://docs.brew.sh/Troubleshooting.html
/usr/local/Homebrew/Library/Homebrew/formula.rb:237:in `determine_active_spec'
/usr/local/Homebrew/Library/Homebrew/formula.rb:191:in `initialize'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:89:in `new'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:89:in `get_formula'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:280:in `factory'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:314:in `rescue in from_keg'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:310:in `from_keg'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:294:in `from_rack'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1384:in `block in installed'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1382:in `each'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1382:in `flat_map'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1382:in `installed'
/usr/local/Homebrew/Library/Homebrew/cmd/update-report.rb:506:in `migrate_formula_rename'
/usr/local/Homebrew/Library/Homebrew/cmd/update-report.rb:101:in `each'
/usr/local/Homebrew/Library/Homebrew/cmd/update-report.rb:101:in `update_report'
/usr/local/Homebrew/Library/Homebrew/brew.rb:100:in `<main>'
/usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::FormulaLoader): loading /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/node.rb
Warning: node 8.9.1 is already installed
```

It looks it is likely issues with the those listed formulas, where the causes are not clear yet.

**Comment by ilovezfs** [comment]
And what's the output of
```
brew readall -dv
```

**Comment by zhenyulin** [comment]
@ilovezfs it outputs a long list of message like below (part of the sample)
```
/usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::FromPathLoader): loading /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/mkhexgrid.rb
/usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::FromPathLoader): loading /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/btparse.rb
/usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::FromPathLoader): loading /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/maven@3.1.rb
/usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::FromPathLoader): loading /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/task.rb
/usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::FromPathLoader): loading /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/naga.rb
/usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::FromPathLoader): loading /usr/local/Homebrew/Library/Taps/wallix/homebrew-awless/Formula/awless.rb
```
while it didn't throw any error message

**Comment by ilovezfs** [comment]
what's the output of
```
find $(brew --cache) |grep rb
```

**Comment by zhenyulin** [comment]
@ilovezfs it outputs nothing

**Comment by ilovezfs** [comment]
Can you apply this diff to /usr/local/Homebrew/Library/Homebrew/formula.rb
```
diff --git a/Library/Homebrew/formula.rb b/Library/Homebrew/formula.rb
index 4ac66ffc4..de887d8e3 100644
--- a/Library/Homebrew/formula.rb
+++ b/Library/Homebrew/formula.rb
@@ -234,7 +234,7 @@ class Formula
 
   def determine_active_spec(requested)
     spec = send(requested) || stable || devel || head
-    spec || raise(FormulaSpecificationError, "formulae require at least a URL")
+    spec || raise(FormulaSpecificationError, "formulae require at least a URL: #{full_name}: #{path}")
   end
 
   def validate_attributes!
```
and trigger the error again?

**Comment by ilovezfs** [comment]
@zhenyulin ?

**Comment by zhenyulin** [comment]
@ilovezfs Thanks for the update, could you maybe provide some more instructions in details? I'm not entirely familiar with how to apply this, and want to make sure I'm not damaging my homebrew directory.

**Comment by zhenyulin** [comment]
@ilovezfs what do you think would be the cause of the current errors?

**Comment by ilovezfs** [comment]
It's likely some formula file hiding somewhere. Just open /usr/local/Homebrew/Library/Homebrew/formula.rb in a text editor of your choice and change line 234

from
```
    spec || raise(FormulaSpecificationError, "formulae require at least a URL")
```

to
```
    spec || raise(FormulaSpecificationError, "formulae require at least a URL: #{full_name}: #{path}")
```
and then save the file.

**Comment by zhenyulin** [comment]
@ilovezfs it outputs the following new information:
```
Error: formulae require at least a URL: mod_suexec: /usr/local/opt/mod_suexec/.brew/mod_suexec.rb
```

**Comment by ilovezfs** [comment]
:tada: So the problem is /usr/local/opt/mod_suexec/.brew/mod_suexec.rb

What's the output of

```
cat /usr/local/opt/mod_suexec/.brew/mod_suexec.rb
```
and
```
cat /usr/local/opt/mod_suexec/INSTALL_RECEIPT.json
```

**Comment by zhenyulin** [comment]
@ilovezfs cool, is this a submodule of homebrew as well? It seems I'm the only person who gets this error at the moment.

`cat /usr/local/opt/mod_suexec/.brew/mod_suexec.rb`:
```
class ModSuexec < Formula
  desc "Run CGI/SSI programs under different user IDs"
  homepage "https://httpd.apache.org/docs/current/suexec.html"
  case MacOS.version.to_sym
  when :snow_leopard
    url "https://archive.apache.org/dist/httpd/httpd-2.2.24.tar.bz2"
    sha256 "0453f5d2d7e3b1975a1c6a8a22b6d6ff768715a3b0a89b51e5f7b5851628fad7"
  when :lion
    url "https://archive.apache.org/dist/httpd/httpd-2.2.26.tar.bz2"
    sha256 "af908e3dd5673f1c6f0ccc615e11d435e77517940af00e518e68ea25284b42b6"
  when :mountain_lion
    url "https://archive.apache.org/dist/httpd/httpd-2.2.22.tar.bz2"
    sha256 "dcdc9f1dc722f84798caf69d69dca78daa5e09a4269060045aeca7e4f44cb231"
  when :mavericks
    url "https://archive.apache.org/dist/httpd/httpd-2.2.26.tar.bz2"
    sha256 "af908e3dd5673f1c6f0ccc615e11d435e77517940af00e518e68ea25284b42b6"
  when :yosemite
    url "https://archive.apache.org/dist/httpd/httpd-2.4.9.tar.bz2"
    sha256 "f78cc90dfa47caf3d83ad18fd6b4e85f237777c1733fc9088594b70ce2847603"
  when :el_capitan
    url "https://archive.apache.org/dist/httpd/httpd-2.4.16.tar.bz2"
    sha256 "ac660b47aaa7887779a6430404dcb40c0b04f90ea69e7bd49a40552e9ff13743"
  when :sierra
    url "https://archive.apache.org/dist/httpd/httpd-2.4.23.tar.bz2"
    sha256 "0c1694b2aad7765896faf92843452ee2555b9591ae10d4f19b245f2adfe85e58"
  end

  bottle :unneeded

  depends_on "libtool" => :build
  depends_on "pcre"
  depends_on :apr => :build

  def install
    system "./configure",
      "--enable-suexec=shared",
      "--with-suexec-bin=/usr/bin/suexec",
      "--with-suexec-caller=_www",
      "--with-suexec-userdir=Sites",
      "--with-suexec-docroot=/",
      "--with-suexec-uidmin=100",
      "--with-suexec-gidmin=20",
      "--with-suexec-logfile=suexec_log",
      "--with-suexec-safepath=/usr/local/bin:/usr/bin:/bin",
      "--with-apr=#{Formula["apr"].opt_prefix}",
      "--with-apr-util=#{Formula["apr-util"].opt_prefix}"

    args = "CC=#{ENV.cc}" if MacOS.version >= :lion
    system "make", *args

    libexec.install "modules/generators/.libs/mod_suexec.so"
    libexec.install "support/suexec"

    include.install "modules/generators/mod_suexec.h"
  end

  def caveats; <<-EOS.undent
    NOTE: This is formula is not needed with Homebrew httpd22 or httpd24; this
    is intended for use with the built-in httpd. Homebrew httpd22 and httpd24
    build mod_suexec by default.

    To complete the installation, you must execute the following commands
      sudo cp -vf #{libexec}/suexec /usr/bin/
      sudo chown -v root:_www /usr/bin/suexec
      sudo chmod -v 4750 /usr/bin/suexec

    Then, you must edit /etc/apache2/httpd.conf to include
      LoadModule suexec_module #{libexec}/mod_suexec.so

    Upon restarting Apache, you should see the following message in the error log:
      [notice] suEXEC mechanism enabled (wrapper: /usr/bin/suexec)

    Be sure to understand the security implications of suexec by carefully
    reading https://httpd.apache.org/docs/current/suexec.html
    EOS
  end
end
```

`cat /usr/local/opt/mod_suexec/INSTALL_RECEIPT.json`:
```
{"homebrew_version":"1.1.10","used_options":[],"unused_options":[],"built_as_bottle":false,"poured_from_bottle":false,"installed_as_dependency":false,"installed_on_request":true,"changed_files":null,"time":1487689626,"source_modified_time":1467306912,"HEAD":"69d1cedd12d37d6a9535fbba17d2129b165c08f8","stdlib":null,"compiler":"clang","runtime_dependencies":[{"full_name":"pcre","version":"8.39"}],"source":{"path":"/usr/local/Homebrew/Library/Taps/homebrew/homebrew-apache/mod_suexec.rb","tap":"homebrew/apache","spec":"stable","versions":{"stable":"2.4.23","devel":null,"head":null,"version_scheme":0}}}%
```
(The `%` in the end looks uncommon)

**Comment by zhenyulin** [comment]
@ilovezfs I think we will need to add the url for `high_sierra`

**Comment by ilovezfs** [comment]
Are you using that software?

https://github.com/Homebrew/homebrew-apache/ is deprecated so there is nothing to update. 

Your best bet is just to uninstall it at this point. Can you

```
brew uninstall mod_suexec
```
successfully?

**Comment by zhenyulin** [comment]
@ilovezfs got the same error running `uninstall`

**Comment by ilovezfs** [comment]
OK. Open /usr/local/opt/mod_suexec/.brew/mod_suexec.rb and change `when :sierra` to `when :high_sierra`

Then brew uninstall should work.

**Comment by zhenyulin** [comment]
@ilovezfs yep, did so, added hard-code value for `high_sierra`, uninstalled it. Problem solved. 🎉

**Comment by zhenyulin** [comment]
@ilovezfs is there a good way to remove all those deprecated packages at a go?

**Comment by ilovezfs** [comment]
```
brew list | xargs -n1 brew formula
```

and then look for anything that has an output like `/usr/local/opt/mod_suexec/.brew/mod_suexec.rb` instead of an output like `/usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/doxygen.rb`

**Comment by zhenyulin** [comment]
@ilovezfs cool, looks like there isn't any other suspicious package left now. Thanks for helping the debugging, and hope others who encounter similar situation would find this thread useful.

**Comment by ilovezfs** [comment]
@zhenyulin you're welcome! Thanks for your patience debugging it.

**Comment by ilovezfs** [comment]
@zhenyulin be sure to revert the changes to /usr/local/Homebrew/Library/Homebrew/formula.rb so you don't end up with a git conflict later

```
git -C $(brew --repo) checkout -- Library/Homebrew/formula.rb
```

**Comment by zhenyulin** [comment]
@ilovezfs done, thanks.

**Comment by ilovezfs** [comment]
you're welcome :)
