### ISSUE TITLE
qt upgrade and install failing

### ISSUE THREAD

**Issue by GlenHenshaw** [Homebrew/homebrew-core#21438]
**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

# Please always follow these steps:
- [x ] Confirmed this is a problem with `brew install`ing one, specific Homebrew/homebrew-core formula (not cask or tap) and not every time you run `brew`? If it's a general `brew` problem please file this issue at https://github.com/Homebrew/brew/issues/new. If it's a `brew cask` problem please file this issue at https://github.com/caskroom/homebrew-cask/issues/new. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [x ] Ran `brew update` and retried your prior step?
- [ x] Ran `brew doctor`, fixed all issues and retried your prior step?
- [x ] Ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [x ] If `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

To help us debug your issue please explain:
- What you were trying to do (and why)

upgrading qt

- What happened (include command output)

```
> brew upgrade
Error: undefined method `installed?' for nil:NilClass
Did you mean?  instance_of?
Please report this bug:
  https://docs.brew.sh/Troubleshooting.html
/usr/local/Homebrew/Library/Homebrew/formula_installer.rb:452:in `block in expand_requirements'
/usr/local/Homebrew/Library/Homebrew/requirement.rb:235:in `block in prune?'
/usr/local/Homebrew/Library/Homebrew/requirement.rb:233:in `catch'
/usr/local/Homebrew/Library/Homebrew/requirement.rb:233:in `prune?'
/usr/local/Homebrew/Library/Homebrew/requirement.rb:224:in `block (2 levels) in expand'
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/2.3.0/set.rb:306:in `each_key'
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/2.3.0/set.rb:306:in `each'
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/2.3.0/delegate.rb:341:in `block in delegating_block'
/usr/local/Homebrew/Library/Homebrew/requirement.rb:223:in `block in expand'
/usr/local/Homebrew/Library/Homebrew/requirement.rb:222:in `each'
/usr/local/Homebrew/Library/Homebrew/requirement.rb:222:in `expand'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1482:in `recursive_requirements'
/usr/local/Homebrew/Library/Homebrew/formula_installer.rb:444:in `expand_requirements'
/usr/local/Homebrew/Library/Homebrew/formula_installer.rb:378:in `compute_dependencies'
/usr/local/Homebrew/Library/Homebrew/formula_installer.rb:136:in `verify_deps_exist'
/usr/local/Homebrew/Library/Homebrew/formula_installer.rb:129:in `prelude'
/usr/local/Homebrew/Library/Homebrew/cmd/install.rb:336:in `install_formula'
/usr/local/Homebrew/Library/Homebrew/cmd/install.rb:227:in `block in install'
/usr/local/Homebrew/Library/Homebrew/cmd/install.rb:225:in `each'
/usr/local/Homebrew/Library/Homebrew/cmd/install.rb:225:in `install'
/usr/local/Homebrew/Library/Homebrew/brew.rb:100:in `<main>'
```

I then uninstalled qt and attempted to reinstall. I received an identical error.

Also, there's this:

```
$ brew config
HOMEBREW_VERSION: 1.3.9-14-g34b03de
ORIGIN: https://github.com/Homebrew/brew
HEAD: 34b03dea52b4f5134484eba1fcf277dca935a633
Last commit: 11 minutes ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: b4c3e2bc2faf074136e3156143472475b839ba92
Core tap last commit: 40 minutes ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CASK_OPTS: --appdir=~/Applications
HOMEBREW_DEV_CMD_RUN: 1
HOMEBREW_ENV_FILTERING: 1
HOMEBREW_GIT_CONFIG_DEVELOPERMODE: true
CPU: quad-core 64-bit broadwell
Homebrew Ruby: 2.3.3 => /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/bin/ruby
Clang: 9.0 build 900
Git: 2.13.6 => /Applications/Xcode.app/Contents/Developer/usr/bin/git
Curl: 7.54.0 => /usr/bin/curl
Perl: /usr/bin/perl
Python: /usr/local/opt/python/libexec/bin/python => /usr/local/Cellar/python/2.7.14/Frameworks/Python.framework/Versions/2.7/bin/python2.7
Ruby: /usr/bin/ruby => /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/bin/ruby
Java: N/A
macOS: 10.13.1-x86_64
Xcode: 9.1
CLT: 9.1.0.0.1.1508540944
X11: 2.7.11 => /opt/X11

$brew doctor
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry and just ignore them. Thanks!

Warning: Unbrewed dylibs were found in /usr/local/lib.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected dylibs:
  /usr/local/lib/libFREND_lib.dylib
  /usr/local/lib/libgazebo_FREND_msgs.dylib
  /usr/local/lib/libgnuplot_i.dylib

Warning: Some installed formula are missing dependencies.
You should `brew install` the missing dependencies:
  brew install qt

Run `brew missing` for more details.
```

Note that "brew gist-logs" has no log for qt.

**Comment by jcarpent** [comment]
Same issue too.

**Comment by ilovezfs** [comment]
will be fixed soon https://github.com/Homebrew/brew/pull/3539

**Comment by ilovezfs** [comment]
It's now fixed if you `brew update`

**Comment by GlenHenshaw** [comment]
I can verify that it now works for me. Thanks.

**Comment by ilovezfs** [comment]
Thanks for testing @GlenHenshaw!
