### ISSUE TITLE
Problem installing git-cola

### ISSUE THREAD

**Issue by houtanb** [Homebrew/homebrew-core#21439]
# Please always follow these steps:
- [x] Confirmed this is a problem with `brew install`ing one, specific Homebrew/homebrew-core formula (not cask or tap) and not every time you run `brew`? If it's a general `brew` problem please file this issue at https://github.com/Homebrew/brew/issues/new. If it's a `brew cask` problem please file this issue at https://github.com/caskroom/homebrew-cask/issues/new. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed all issues and retried your prior step?
- [x] Ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
https://gist.github.com/houtanb/44c464607f3a9d7cc8e416d26c9c9e67
- [x] If `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?
```
• brew config
HOMEBREW_VERSION: 1.3.9-16-g360d7bc
ORIGIN: https://github.com/Homebrew/brew
HEAD: 360d7bc6f4cdea996b55c14d885a8b78da5dd7ad
Last commit: 19 minutes ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: b4c3e2bc2faf074136e3156143472475b839ba92
Core tap last commit: 60 minutes ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_DEV_CMD_RUN: 1
HOMEBREW_ENV_FILTERING: 1
HOMEBREW_GIT_CONFIG_DEVELOPERMODE: true
HOMEBREW_TEMP: /Users/houtanb/scratch/homebrew_tmp
HOMEBREW_VISUAL: emacs
CPU: octa-core 64-bit haswell
Homebrew Ruby: 2.3.3 => /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/bin/ruby
Clang: 9.0 build 900
Git: 2.14.3 => /Applications/Xcode.app/Contents/Developer/usr/bin/git
Curl: 7.54.0 => /usr/bin/curl
Perl: /usr/bin/perl
Python: /usr/local/opt/python/libexec/bin/python => /usr/local/Cellar/python/2.7.14/Frameworks/Python.framework/Versions/2.7/bin/python2.7
Ruby: /usr/bin/ruby => /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin/ruby
Java: 1.6.0_65-b14-468
macOS: 10.12.6-x86_64
Xcode: 9.2
CLT: 9.1.0.0.1.1508540944
X11: 2.7.11 => /opt/X11
```
```
• brew doctor
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry and just ignore them. Thanks!

Warning: You have unlinked kegs in your Cellar
Leaving kegs unlinked can lead to build-trouble and cause brews that depend on
those kegs to fail to run properly once built. Run `brew link` on these:
  ghostscript
  gnupg

Warning: Some keg-only formula are linked into the Cellar.
Linking a keg-only formula, such as gettext, into the cellar with
`brew link <formula>` will cause other formulae to detect them during
the `./configure` step. This may cause problems when compiling those
other formulae.

Binaries provided by keg-only formulae may override system binaries
with other strange results.

You may wish to `brew unlink` these brews:
  bison
  flex
```

To help us debug your issue please explain:
- What you were trying to do (and why)
I was trying to install `git-cola`
- What happened (include command output)
```
• brew install git-cola
Error: undefined method `installed?' for nil:NilClass
Did you mean?  instance_of?
Please report this bug:
  https://docs.brew.sh/Troubleshooting.html
/usr/local/Homebrew/Library/Homebrew/formula_installer.rb:453:in `block in expand_requirements'
/usr/local/Homebrew/Library/Homebrew/requirement.rb:235:in `block in prune?'
/usr/local/Homebrew/Library/Homebrew/requirement.rb:233:in `catch'
/usr/local/Homebrew/Library/Homebrew/requirement.rb:233:in `prune?'
/usr/local/Homebrew/Library/Homebrew/requirement.rb:224:in `block (2 levels) in expand'
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/2.3.0/set.rb:306:in `each_key'
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/2.3.0/set.rb:306:in `each'
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/2.3.0/delegate.rb:341:in `block in delegating_block'
/usr/local/Homebrew/Library/Homebrew/requirement.rb:223:in `block in expand'
/usr/local/Homebrew/Library/Homebrew/requirement.rb:222:in `each'
/usr/local/Homebrew/Library/Homebrew/requirement.rb:222:in `expand'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1482:in `recursive_requirements'
/usr/local/Homebrew/Library/Homebrew/formula_installer.rb:445:in `expand_requirements'
/usr/local/Homebrew/Library/Homebrew/formula_installer.rb:378:in `compute_dependencies'
/usr/local/Homebrew/Library/Homebrew/formula_installer.rb:136:in `verify_deps_exist'
/usr/local/Homebrew/Library/Homebrew/formula_installer.rb:129:in `prelude'
/usr/local/Homebrew/Library/Homebrew/cmd/install.rb:336:in `install_formula'
/usr/local/Homebrew/Library/Homebrew/cmd/install.rb:227:in `block in install'
/usr/local/Homebrew/Library/Homebrew/cmd/install.rb:225:in `each'
/usr/local/Homebrew/Library/Homebrew/cmd/install.rb:225:in `install'
/usr/local/Homebrew/Library/Homebrew/brew.rb:100:in `<main>'
```
- What you expected to happen
I expected it to be installed
- Step-by-step reproduction instructions (by running `brew install` commands)
Run `brew install git-cola`

**Comment by ilovezfs** [comment]
It's now fixed if you `brew update` https://github.com/Homebrew/brew/pull/3539
