### ISSUE TITLE
Brew-installed pipenv fails with UTF-8 error

### ISSUE THREAD

**Issue by amitkot** [Homebrew/homebrew-core#21926]
**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

# Please always follow these steps:
- [x] Confirmed this is a problem with `brew install`ing one, specific Homebrew/homebrew-core formula (not cask or tap) and not every time you run `brew`? If it's a general `brew` problem please file this issue at https://github.com/Homebrew/brew/issues/new. If it's a `brew cask` problem please file this issue at https://github.com/caskroom/homebrew-cask/issues/new. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed all issues and retried your prior step?
- [x] Ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [x] If `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

To help us debug your issue please explain:
- What you were trying to do (and why)

I installed the pipenv formula and wanted to use pipenv to install a library dependency in a project.

- What happened (include command output)
```
$ pipenv install aiohttp
Creating a virtualenv for this project…
⠋Traceback (most recent call last):
  File "/usr/local/Cellar/pipenv/8.3.2_2/libexec/tools/pew", line 11, in <module>
    load_entry_point('pew==1.1.0', 'console_scripts', 'pew')()
  File "/usr/local/Cellar/pipenv/8.3.2_2/libexec/lib/python3.6/site-packages/pkg_resources/__init__.py", line 572, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/local/Cellar/pipenv/8.3.2_2/libexec/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2752, in load_entry_point
    return ep.load()
  File "/usr/local/Cellar/pipenv/8.3.2_2/libexec/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2405, in load
    return self.resolve()
  File "/usr/local/Cellar/pipenv/8.3.2_2/libexec/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2411, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/local/Cellar/pipenv/8.3.2_2/libexec/lib/python3.6/site-packages/pew/__init__.py", line 11, in <module>
    from . import pew
  File "/usr/local/Cellar/pipenv/8.3.2_2/libexec/lib/python3.6/site-packages/pew/pew.py", line 42, in <module>
    from pew._utils import (check_call, invoke, expandpath, own, env_bin_dir,
  File "/usr/local/Cellar/pipenv/8.3.2_2/libexec/lib/python3.6/site-packages/pew/_utils.py", line 22, in <module>
    encoding = locale.getlocale()[1] or 'ascii'
  File "/usr/local/Cellar/pipenv/8.3.2_2/libexec/lib/python3.6/locale.py", line 581, in getlocale
    return _parse_localename(localename)
  File "/usr/local/Cellar/pipenv/8.3.2_2/libexec/lib/python3.6/locale.py", line 490, in _parse_localename
    raise ValueError('unknown locale: %s' % localename)
ValueError: unknown locale: UTF-8

Virtualenv location:
Installing aiohttp…
⠴
Error:  An error occurred while installing aiohttp!
/bin/sh: /bin/pip: No such file or directory
```

- What you expected to happen
The dependency to be installed

- Step-by-step reproduction instructions (by running `brew install` commands)
```
$ brew install pipenv
$ pipenv install aiohttp
```

---
```
$ brew gist-logs pipenv
Error: No logs.

$ brew config
HOMEBREW_VERSION: 1.4.1
ORIGIN: https://github.com/Homebrew/brew
HEAD: b4d43e950fd45c24e48d6ebfd3013357abcd21a9
Last commit: 4 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 2ba81e80b82d1f86ef61334dacfdfe5635eb64a7
Core tap last commit: 29 minutes ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_GITHUB_API_TOKEN: set
HOMEBREW_NO_ANALYTICS_THIS_RUN: 1
CPU: octa-core 64-bit sandybridge
Homebrew Ruby: 2.3.3 => /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/bin/ruby
Clang: 9.0 build 900
Git: 2.14.3 => /Applications/Xcode.app/Contents/Developer/usr/bin/git
Curl: 7.54.0 => /usr/bin/curl
Perl: /usr/bin/perl
Python: /usr/local/opt/python/libexec/bin/python => /usr/local/Cellar/python/2.7.14/Frameworks/Python.framework/Versions/2.7/bin/python2.7
Ruby: /usr/bin/ruby => /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin/ruby
Java: 1.8.0_92
macOS: 10.12.6-x86_64
Xcode: 9.2
CLT: 9.2.0.0.1.1510905681
X11: N/A

$ brew doctor
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: You have unlinked kegs in your Cellar
Leaving kegs unlinked can lead to build-trouble and cause brews that depend on
those kegs to fail to run properly once built. Run `brew link` on these:
  android-ndk-r10e
  bash-completion

Warning: Homebrew's sbin was not found in your PATH but you have installed
formulae that put executables in /usr/local/sbin.
Consider setting the PATH for example like so
  echo 'export PATH="/usr/local/sbin:$PATH"' >> ~/.bash_profile
```

**Comment by ilovezfs** [comment]
does it help to

```
export LC_ALL=en_US.UTF-8
```

**Comment by JCount** [comment]
Also, what is the output of running `locale` in your terminal?

**Comment by amitkot** [comment]
Sorry for the delayed response.
In the meantime I upgraded to the new version of pipenv and while it didn't work immediately, changing the locale helped.

The output of running `locale` is:

```
$ locale
LANG="en_US.UTF-8"
LC_COLLATE="en_US.UTF-8"
LC_CTYPE="UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_MONETARY="en_US.UTF-8"
LC_NUMERIC="en_US.UTF-8"
LC_TIME="en_US.UTF-8"
LC_ALL=
```

And running 

```
export LC_ALL=en_US.UTF-8
```

does solve the issue.

Thanks!
