### ISSUE TITLE
ruby `gem update` do not work after ruby upgrade 

### ISSUE THREAD

**Issue by monouser7dig** [Homebrew/homebrew-core#22012]
# Please always follow these steps:
- [x] Confirmed this is a problem with `brew install`ing one, specific Homebrew/homebrew-core formula (not cask or tap) and not every time you run `brew`? If it's a general `brew` problem please file this issue at https://github.com/Homebrew/brew/issues/new. If it's a `brew cask` problem please file this issue at https://github.com/caskroom/homebrew-cask/issues/new. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed all issues and retried your prior step?
- [x] Ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [x] If `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

```
brew gist-logs ruby
Error: No logs.

brew doctor
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: Putting non-prefixed coreutils in your path can cause gmp builds to fail.

Warning: Putting non-prefixed findutils in your path can cause python builds to fail.


brew config
HOMEBREW_VERSION: 1.4.1-9-gbd471d6
ORIGIN: https://github.com/Homebrew/brew
HEAD: bd471d6b9ba11c778ce1ba9349608d89521bf9f1
Last commit: 5 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 135240df46b6a1dcaa36d9a696440ef5dfdd37e1
Core tap last commit: 14 minutes ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_DEV_CMD_RUN: 1
CPU: quad-core 64-bit skylake
Homebrew Ruby: 2.3.3 => /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/bin/ruby
Clang: 9.0 build 900
Git: 2.15.1 => /usr/local/bin/git
Curl: 7.54.0 => /usr/bin/curl
Perl: /usr/bin/perl
Python: /usr/local/opt/python/libexec/bin/python => /usr/local/Cellar/python/2.7.14/Frameworks/Python.framework/Versions/2.7/bin/python2.7
Ruby: /usr/local/bin/ruby => /usr/local/Cellar/ruby/2.4.3_1/bin/ruby
Java: 9.0.1, 1.8.0_144
macOS: 10.13.2-x86_64
Xcode: 9.2
CLT: N/A
X11: N/A

```

To help us debug your issue please explain:
- What you were trying to do (and why)
brew upgrade because I want to upgrade formulas 
- What happened (include command output)
formulas were upgraded, output is gone now
- What you expected to happen
continue my ruby to work
- Step-by-step reproduction instructions (by running `brew install` commands)
upgraded from the last ruby version to the latest

```
which ruby
/usr/local/bin/ruby

ruby --version
ruby 2.3.3p222 (2016-11-21 revision 56859) [universal.x86_64-darwin17]

/usr/local/bin/ruby --version
ruby 2.4.3p205 (2017-12-14 revision 61247) [x86_64-darwin17]

which gem
/usr/local/bin/gem

gem --version
Ignoring bigdecimal-1.3.2 because its extensions are not built.  Try: gem pristine bigdecimal --version 1.3.2
```

## gem update now fail with 
```
gem update
Ignoring bigdecimal-1.3.2 because its extensions are not built.  Try: gem pristine bigdecimal --version 1.3.2
Ignoring json-2.1.0 because its extensions are not built.  Try: gem pristine json --version 2.1.0
Ignoring openssl-2.0.6 because its extensions are not built.  Try: gem pristine openssl --version 2.0.6
/usr/local/Cellar/ruby/2.4.3_1/lib/ruby/2.4.0/yaml.rb:5:in `<top (required)>':
It seems your ruby installation is missing psych (for YAML output).
To eliminate this warning, please install libyaml and reinstall your ruby.
/usr/local/Cellar/ruby/2.4.3_1/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require': dlopen(/usr/local/lib/ruby/gems/2.4.0/gems/psych-3.0.0/lib/psych.bundle, 9): Library not loaded: /usr/local/opt/ruby/lib/libruby.2.4.2.dylib (LoadError)
  Referenced from: /usr/local/lib/ruby/gems/2.4.0/gems/psych-3.0.0/lib/psych.bundle
  Reason: image not found - /usr/local/lib/ruby/gems/2.4.0/gems/psych-3.0.0/lib/psych.bundle
	from /usr/local/Cellar/ru
.... etc. etc.
```

**Comment by DomT4** [comment]
```
=> rm -f /usr/local/lib/ruby/gems/2.4.0/gems/psych-3.0.0/lib/psych.bundle
=> rm -f /usr/local/lib/ruby/gems/2.4.0/extensions/x86_64-darwin-17/3.0.0/psych-2.2.4/psych.bundle
=> /usr/local/bin/gem uninstall psych
```

**Comment by monouser7dig** [comment]
What command is this the output of? Is „gem“ expected to work again afterwards?
Thanks

**Comment by Eitot** [comment]
The third command (above) is not working. Have the same error as OP.

**Comment by DomT4** [comment]
> What command is this the output of?

It's not from a command. Run the three commands in order.

@Eitot You want the same commands but with `3.0.1` instead of `3.0.0`.

**Comment by monouser7dig** [comment]
I see.
```
=>/usr/local/bin/gem uninstall psych

Ignoring bigdecimal-1.3.2 because its extensions are not built.  Try: gem pristine bigdecimal --version 1.3.2
Ignoring json-2.1.0 because its extensions are not built.  Try: gem pristine json --version 2.1.0
Ignoring openssl-2.0.6 because its extensions are not built.  Try: gem pristine openssl --version 2.0.6
/usr/local/Cellar/ruby/2.4.3_1/lib/ruby/2.4.0/yaml.rb:5:in `<top (required)>':
It seems your ruby installation is missing psych (for YAML output).
To eliminate this warning, please install libyaml and reinstall your ruby.
```

do you happen to know why these issues are caused after a brew upgrade? maybe I can do something to avoid it. 
So far I thought my ruby installation was pretty default, nothing fancy/ should work out of the box but maybe I was wrong?

**Comment by DomT4** [comment]
@monouser7dig Can you try `brew reinstall ruby` and them run `gem` and see if you hit issues still?

**Comment by DomT4** [comment]
> do you happen to know why these issues are caused after a brew upgrade? maybe I can do something to avoid it.

I need to report this upstream really. It's a ridiculous situation. Essentially `gem` has an internal `psych` that it requires to run, which is fine, but instead of making some effort to _specifically_ require that internal `psych` it's distinctly _not fussy_ about which `psych` it uses.

The problem starts when users run `gem install psych` themselves at some point prior to upgrade, or that external `psych` is dragged in as a dep of something else; that `psych` generates a `.bundle` which is linked to the old `libruby.x.y.z.dylib` which, of course, is unlinked after upgrade in favour of the new version, breaking the linkage and causing `gem` to panic.

**Comment by DomT4** [comment]
The same thing can happen with anything that generates a `.bundle`, but because `psych` is used internally by `gem` and it isn't fussy about which `psych` it uses, that is always the problematic one.

**Comment by monouser7dig** [comment]
> Can you try brew reinstall ruby and them run gem and see if you hit issues still?

sure, but does not help

```
=> brew reinstall ruby

==> Reinstalling ruby 
==> Downloading https://homebrew.bintray.com/bottles/ruby-2.4.3_1.high_sierra.bottle.
Already downloaded: ~/Library/Caches/Homebrew/ruby-2.4.3_1.high_sierra.bottle.tar.gz
==> Pouring ruby-2.4.3_1.high_sierra.bottle.tar.gz
==> Caveats
Emacs Lisp files have been installed to:
  /usr/local/share/emacs/site-lisp/ruby
==> Summary
🍺  /usr/local/Cellar/ruby/2.4.3_1: 3,042 files, 16.3MB
```

I am not in desperate need to run ruby 2.4 (or respective gems) right now so if this issues get's resolved somewhere down the line it is fine for me.

When I `gem update` I am asked if I want to replace/ overwrite certain gems (I do not have the exact wording at hand right now) and thought maybe this had caused the issue because I was not sure what I was doing at that time, but does not seem to be the case.

**Comment by DomT4** [comment]
> sure, but does not help

Does `gem` still bork? In precisely the same way? If it does can you do `ls -1 /usr/local/lib/ruby/gems/2.4.0/gems/` and provide that output? Thanks.

> When I gem update I am asked if I want to replace/ overwrite certain gems (I do not have the exact wording at hand right now)

Off the top of my head I think you're talking about `rake` and `rdoc` maybe? If so those _usually_ aren't problematic to overwrite, I tend to do so personally.

**Comment by monouser7dig** [comment]
full output of `gem`
<details>

```
gem
Ignoring bigdecimal-1.3.2 because its extensions are not built.  Try: gem pristine bigdecimal --version 1.3.2
Ignoring json-2.1.0 because its extensions are not built.  Try: gem pristine json --version 2.1.0
Ignoring openssl-2.0.6 because its extensions are not built.  Try: gem pristine openssl --version 2.0.6
/usr/local/Cellar/ruby/2.4.3_1/lib/ruby/2.4.0/yaml.rb:5:in `<top (required)>':
It seems your ruby installation is missing psych (for YAML output).
To eliminate this warning, please install libyaml and reinstall your ruby.
/usr/local/Cellar/ruby/2.4.3_1/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require': dlopen(/usr/local/lib/ruby/gems/2.4.0/extensions/x86_64-darwin-17/2.4.0/psych-3.0.0/psych.bundle, 9): Library not loaded: /usr/local/opt/ruby/lib/libruby.2.4.2.dylib (LoadError)
  Referenced from: /usr/local/lib/ruby/gems/2.4.0/extensions/x86_64-darwin-17/2.4.0/psych-3.0.0/psych.bundle
  Reason: image not found - /usr/local/lib/ruby/gems/2.4.0/extensions/x86_64-darwin-17/2.4.0/psych-3.0.0/psych.bundle
	from /usr/local/Cellar/ruby/2.4.3_1/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/local/lib/ruby/gems/2.4.0/gems/psych-3.0.0/lib/psych.rb:11:in `rescue in <top (required)>'
	from /usr/local/lib/ruby/gems/2.4.0/gems/psych-3.0.0/lib/psych.rb:8:in `<top (required)>'
	from /usr/local/Cellar/ruby/2.4.3_1/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/local/Cellar/ruby/2.4.3_1/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/local/Cellar/ruby/2.4.3_1/lib/ruby/2.4.0/yaml.rb:6:in `<top (required)>'
	from /usr/local/Cellar/ruby/2.4.3_1/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/local/Cellar/ruby/2.4.3_1/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/local/Cellar/ruby/2.4.3_1/lib/ruby/2.4.0/rubygems.rb:701:in `load_yaml'
	from /usr/local/Cellar/ruby/2.4.3_1/lib/ruby/2.4.0/rubygems/config_file.rb:340:in `load_file'
	from /usr/local/Cellar/ruby/2.4.3_1/lib/ruby/2.4.0/rubygems/config_file.rb:202:in `initialize'
	from /usr/local/Cellar/ruby/2.4.3_1/lib/ruby/2.4.0/rubygems/gem_runner.rb:75:in `new'
	from /usr/local/Cellar/ruby/2.4.3_1/lib/ruby/2.4.0/rubygems/gem_runner.rb:75:in `do_configuration'
	from /usr/local/Cellar/ruby/2.4.3_1/lib/ruby/2.4.0/rubygems/gem_runner.rb:40:in `run'
	from /usr/local/bin/gem:21:in `<main>'
```

(still the same as before just to make sure we are on the same page though)
```
which gem
/usr/local/bin/gem

gem --version
 same error as `gem`
```
</details>

```
(may be a bit messy, have not used it a whole lot)
ls -1 /usr/local/lib/ruby/gems/2.4.0/gems/

ast-2.3.0
bigdecimal-1.3.2
did_you_mean-1.1.0
did_you_mean-1.1.2
git-1.3.0
json-2.1.0
minitest-5.10.1
minitest-5.10.3
net-telnet-0.1.1
openssl-2.0.6
parallel-1.12.0
parser-2.4.0.2
power_assert-0.4.1
power_assert-1.1.1
powerpack-0.1.1
psych-3.0.0
public_suffix-3.0.1
rainbow-2.2.2
rainbow-3.0.0
rake-12.0.0
rake-12.3.0
rdoc-5.0.0
rdoc-5.1.0
rubocop-0.51.0
rubocop-cask-0.15.1
ruby-progressbar-1.9.0
test-unit-3.2.3
test-unit-3.2.6
unicode-display_width-1.3.0
xmlrpc-0.2.1
xmlrpc-0.3.0
```

yes maybe those two, I was surprised though cause I thought the homebrew-ruby installed gems were all separate

**Comment by DomT4** [comment]
@monouser7dig Try `rm -f /usr/local/lib/ruby/gems/2.4.0/extensions/x86_64-darwin-17/2.4.0/psych-3.0.0/psych.bundle` and then `gem` again.

**Comment by monouser7dig** [comment]
> Try rm -f /usr/local/lib/ruby/gems/2.4.0/extensions/x86_64-darwin-17/2.4.0/psych-3.0.0/psych.bundle and then gem again

this improves the situation

```
=> gem 

Ignoring bigdecimal-1.3.2 because its extensions are not built.  Try: gem pristine bigdecimal --version 1.3.2
Ignoring json-2.1.0 because its extensions are not built.  Try: gem pristine json --version 2.1.0
Ignoring openssl-2.0.6 because its extensions are not built.  Try: gem pristine openssl --version 2.0.6
RubyGems is a sophisticated package manager for Ruby.  This is a
basic help message containing pointers to more information.

  Usage:
    gem -h/--help
    gem -v/--version
    gem command [arguments...] [options...]

  Examples:
    gem install rake
    gem list --local
...etc. etc.

```
> "RubyGems is a sophisticated package manager for Ruby"

lol


```
=> gem --version

Ignoring bigdecimal-1.3.2 because its extensions are not built.  Try: gem pristine bigdecimal --version 1.3.2
Ignoring json-2.1.0 because its extensions are not built.  Try: gem pristine json --version 2.1.0
Ignoring openssl-2.0.6 because its extensions are not built.  Try: gem pristine openssl --version 2.0.6
2.6.14
```

```
=> gem update

Ignoring bigdecimal-1.3.2 because its extensions are not built.  Try: gem pristine bigdecimal --version 1.3.2
Ignoring json-2.1.0 because its extensions are not built.  Try: gem pristine json --version 2.1.0
Ignoring openssl-2.0.6 because its extensions are not built.  Try: gem pristine openssl --version 2.0.6
ERROR:  Loading command: update (LoadError)
	dlopen(/usr/local/lib/ruby/gems/2.4.0/gems/openssl-2.0.6/lib/openssl.bundle, 9): Library not loaded: /usr/local/opt/ruby/lib/libruby.2.4.2.dylib
  Referenced from: /usr/local/lib/ruby/gems/2.4.0/gems/openssl-2.0.6/lib/openssl.bundle
  Reason: image not found - /usr/local/lib/ruby/gems/2.4.0/gems/openssl-2.0.6/lib/openssl.bundle
ERROR:  While executing gem ... (NoMethodError)
    undefined method `invoke_with_build_args' for nil:NilClass
```

```
=> gem pristine --all

Ignoring bigdecimal-1.3.2 because its extensions are not built.  Try: gem pristine bigdecimal --version 1.3.2
Ignoring json-2.1.0 because its extensions are not built.  Try: gem pristine json --version 2.1.0
Ignoring openssl-2.0.6 because its extensions are not built.  Try: gem pristine openssl --version 2.0.6
ERROR:  Loading command: pristine (LoadError)
	dlopen(/usr/local/lib/ruby/gems/2.4.0/gems/openssl-2.0.6/lib/openssl.bundle, 9): Library not loaded: /usr/local/opt/ruby/lib/libruby.2.4.2.dylib
  Referenced from: /usr/local/lib/ruby/gems/2.4.0/gems/openssl-2.0.6/lib/openssl.bundle
  Reason: image not found - /usr/local/lib/ruby/gems/2.4.0/gems/openssl-2.0.6/lib/openssl.bundle
ERROR:  While executing gem ... (NoMethodError)
    undefined method `invoke_with_build_args' for nil:NilClass
```

**Comment by DomT4** [comment]
You're definitely reaffirming my habit of removing all my gems prior to update & reinstalling from a script every time, that's for sure 😄.

If you haven't yet run `brew cleanup` it might be easier to do something like:

```
=> brew switch ruby 2.4.2_1
=> gem uninstall openssl json bigdecimal
=> brew switch ruby 2.4.3_1
=> gem install openssl json bigdecimal psych
```

If you have run `brew cleanup` already you're going to need to repeat that selective use of `rm -f` for each `.bundle` 😓.

**Comment by monouser7dig** [comment]
do you happen to have that script at hand? I might copy that habit although I'd have to pin ruby for that to work together with brew upgrade I guess

## I am actually pleasantly surprised that I still have ruby 2.4.2_1
```
=> brew switch ruby 2.4.2_1


Cleaning /usr/local/Cellar/ruby/2.4.2_1
Cleaning /usr/local/Cellar/ruby/2.4.3_1
Cleaning /usr/local/Cellar/ruby/2.4.2
3004 links created for /usr/local/Cellar/ruby/2.4.2_1
```

```
=> gem uninstall openssl json bigdecimal


Ignoring bigdecimal-1.3.2 because its extensions are not built.  Try: gem pristine bigdecimal --version 1.3.2
Ignoring json-2.1.0 because its extensions are not built.  Try: gem pristine json --version 2.1.0
Ignoring openssl-2.0.6 because its extensions are not built.  Try: gem pristine openssl --version 2.0.6
Successfully uninstalled bigdecimal-1.3.2
Successfully uninstalled json-2.1.0
Successfully uninstalled openssl-2.0.6
```

```
=> brew switch ruby 2.4.3_1


Cleaning /usr/local/Cellar/ruby/2.4.2_1
Cleaning /usr/local/Cellar/ruby/2.4.3_1
Cleaning /usr/local/Cellar/ruby/2.4.2
3004 links created for /usr/local/Cellar/ruby/2.4.3_1
```

```
=> gem install openssl json bigdecimal psych


Fetching: openssl-2.1.0.gem (100%)
Building native extensions.  This could take a while...
Successfully installed openssl-2.1.0
Parsing documentation for openssl-2.1.0
Installing ri documentation for openssl-2.1.0
Done installing documentation for openssl after 2 seconds
Fetching: json-2.1.0.gem (100%)
Building native extensions.  This could take a while...
Successfully installed json-2.1.0
Parsing documentation for json-2.1.0
Installing ri documentation for json-2.1.0
Done installing documentation for json after 0 seconds
Fetching: bigdecimal-1.3.3.gem (100%)
Building native extensions.  This could take a while...
Successfully installed bigdecimal-1.3.3
Parsing documentation for bigdecimal-1.3.3
Installing ri documentation for bigdecimal-1.3.3
Done installing documentation for bigdecimal after 0 seconds
Fetching: psych-3.0.2.gem (100%)
Building native extensions.  This could take a while...
Successfully installed psych-3.0.2
Parsing documentation for psych-3.0.2
Installing ri documentation for psych-3.0.2
Done installing documentation for psych after 1 seconds
4 gems installed
```

## and the situation has improved further
and I have my error message back about which I was talking earlier (for now I just aborted)
```
=> gem update

Updating installed gems
Updating did_you_mean
Fetching: did_you_mean-1.2.0.gem (100%)
ERROR:  Error installing did_you_mean:
	did_you_mean requires Ruby version >= 2.5.0dev.
Updating parallel
Fetching: parallel-1.12.1.gem (100%)
Successfully installed parallel-1.12.1
Parsing documentation for parallel-1.12.1
Installing ri documentation for parallel-1.12.1
Installing darkfish documentation for parallel-1.12.1
Done installing documentation for parallel after 0 seconds
Parsing documentation for parallel-1.12.1
Done installing documentation for parallel after 0 seconds
Updating rdoc
Fetching: rdoc-6.0.0.gem (100%)
rdoc's executable "rdoc" conflicts with /usr/local/bin/rdoc
Overwrite the executable? [yN]  
```
`Overwrite the executable? [yN] ` which I thought was strange cause I thought the homebrew-version was separate and I am not even sure which executable it wants to overwrite, I mean I probably want to use the homebrew version

**Comment by DomT4** [comment]
> do you happen to have that script at hand? I might copy that habit although I'd have to pin ruby for that to work together with brew upgrade I guess

I use `rbenv` for most of my actual Ruby dev stuff simply because it is a lot easier to dispose of each time. The script itself is a very basic `bash` script:
```bash
#!/usr/bin/env bash
read -p "Install many gems. Proceed? (y/n)" -n 1 -r
echo    # blank echo to prevent errors
if [[ $REPLY =~ ^[Yy]$ ]]
then
    gem install CFPropertyList
    gem install faraday
    gem install io-console
    gem install json
    gem install libxml-ruby
    [snip]
    echo "Finished at last!"
fi
```
which I execute after doing `rbenv global system && rbenv uninstall 2.4.2 && rbenv install 2.4.3 && rbenv global 2.4.3`. Piece of cake right 🙈 😅.

> Overwrite the executable? [yN] which I thought was strange cause I thought the homebrew-version was separate and I am not even sure which executable it wants to overwrite

Ruby ships its own version of `rdoc` and `rake`, which Homebrew symlinks into `HOMEBREW_PREFIX/bin` along with `ruby`, `gem`, etc. The installation is essentially going _"Erm, am I okay to overwrite those symlinks with these updated executables?"_. That comes down to user choice, personally I say yes and it hasn't yet blown up in my face

**Comment by monouser7dig** [comment]
ok I'll write that down somewhere, thanks.

**Comment by DomT4** [comment]
In terms of things that are _potentially_ actionable here for Homebrew:

* Stop building a dynamic library for Ruby & instead only build the static library.
* Report `gem`'s overly-promiscuous relationship with `pysch`  upstream and point out if you're going to vendor something internally actually making sure you're using that internal version is sane.
* Attempt to tweak Ruby so the "real" dylib is something like `librubyx.y` with a symlink to `librubyx.y.z` rather than the other way around, which means this should only happen on API breaks.
* Use `gems/"#{version}"` rather than `"gems/#{api_version}"`, forcing everyone to reinstall all their gems every update. Annoying but should be effective.

I punt to @ilovezfs for opinions on all/any of the above.

**Comment by ilovezfs** [comment]
I don't think we need to make any changes but 👍 to reporting upstream if you think they can do something to make things easier for people.

**Comment by ilovezfs** [comment]
@DomT4 is pysch unusual in linking again the full libruby.2.4.3.dylib or is that typical of other gems that link against the dylib?

**Comment by DomT4** [comment]
No, it's completely standard. Ruby seems to ship the real dylib as `libruby.x.y.z` with `libruby.x.y` and `libruby` being symlinks to it. Happens with the system `ruby` too but obviously that's extremely rarely updated:

```
/Library/Ruby/Gems/2.0.0/gems/libxml-ruby-3.0.0/ext/libxml/libxml_ruby.bundle:
	/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/libruby.2.0.0.dylib (compatibility version 2.0.0, current version 2.0.0)
	/usr/lib/libxml2.2.dylib (compatibility version 10.0.0, current version 10.9.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1238.50.2)
	/usr/lib/libobjc.A.dylib (compatibility version 1.0.0, current version 228.0.0)
```

**Comment by ilovezfs** [comment]
Hmm ... but is that actually what determines which one is used? Look at `ls -l /usr/lib` where you have that same situation for `libstdc++` and `libnetsnmp`.

**Comment by ilovezfs** [comment]
```
bash-3.2$ pkg-config --libs ruby-2.4
-L/usr/local/opt/libyaml/lib -L/usr/local/opt/openssl/lib -L/usr/local/opt/readline/lib -Wl,-undefined,dynamic_lookup -Wl,-multiply_defined,suppress -lruby.2.4.3 -lpthread -ldl -lobjc
bash-3.2$ 
```
That can't be helpful. I wonder what determines the same for gem.

**Comment by ilovezfs** [comment]
>Use gems/"#{version}" rather than "gems/#{api_version}", forcing everyone to reinstall all their gems every update. Annoying but should be effective.

This seems like the right answer if upstream is intentionally breaking everything with shared library linkage every time. I wonder what the Linux distros are doing here.

**Comment by DomT4** [comment]
>  I wonder what determines the same for gem.

Annoyingly, after reading through API documentation, I'm none the wiser. Hopefully I'm missing something obvious 😓.

> I wonder what the Linux distros are doing here.

Somehow, they've pegged it to build against `libruby.x.y` _(essentially)_ rather than `libruby.x.y.z` even though `libruby.x.y.z` is the real shared library. This would mean only causing breakage when the API breaks presumably, which seems logical, rather than every single update.

![virtualbox_ubuntu_26_12_2017_04_44_18](https://user-images.githubusercontent.com/6998367/34347129-a2c3566e-e9f7-11e7-8bb3-3ac1877ac2fb.png)

**Comment by DomT4** [comment]
Debian passes these flags:
```
export RUBY_VERSION       := $(patsubst ruby%,%,$(DEB_SOURCE))
export RUBY_API_VERSION   := $(RUBY_VERSION).0

configure_options += --prefix=/usr
configure_options += --enable-multiarch
configure_options += --target=$(DEB_HOST_MULTIARCH)
configure_options += --program-suffix=$(RUBY_VERSION)
configure_options += --with-soname=ruby-$(RUBY_VERSION)
configure_options += --enable-shared
configure_options += --disable-rpath
configure_options += --with-sitedir='/usr/local/lib/site_ruby'
configure_options += --with-sitearchdir="/usr/local/lib/$(DEB_HOST_MULTIARCH)/site_ruby"

# the following are ignored by ./configure, but used by some extconf.rb scripts
configure_options += --enable-ipv6
configure_options += --with-dbm-type=gdbm_compat
```

**Comment by ilovezfs** [comment]
Fixed.
```
==> Summary
🍺  /usr/local/Cellar/ruby/2.4.3_1: 3,042 files, 16.3MB, built in 5 minutes 34 seconds
bash-3.2$ otool -L /usr/local/Cellar/ruby/2.4.3_1/lib/ruby/2.4.0/x86_64-darwin17/psych.bundle
/usr/local/Cellar/ruby/2.4.3_1/lib/ruby/2.4.0/x86_64-darwin17/psych.bundle:
	/usr/local/Cellar/ruby/2.4.3_1/lib/libruby.2.4.dylib (compatibility version 2.4.0, current version 2.4.3)
	/usr/local/opt/libyaml/lib/libyaml-0.2.dylib (compatibility version 3.0.0, current version 3.5.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1252.0.0)
	/usr/lib/libobjc.A.dylib (compatibility version 1.0.0, current version 228.0.0)
bash-3.2$ otool -L /usr/local/Cellar/ruby/2.4.3_1/lib/libruby.2.4.3.dylib 
/usr/local/Cellar/ruby/2.4.3_1/lib/libruby.2.4.3.dylib:
	/usr/local/opt/ruby/lib/libruby.2.4.dylib (compatibility version 2.4.0, current version 2.4.3)
	/System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation (compatibility version 150.0.0, current version 1445.12.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1252.0.0)
	/usr/lib/libobjc.A.dylib (compatibility version 1.0.0, current version 228.0.0)
bash-3.2$ ls -l /usr/local/Cellar/ruby/2.4.3_1/lib
total 4432
-r--r--r--  1 joe  admin  2265864 Dec 25 22:52 libruby.2.4.3.dylib
lr-xr-xr-x  1 joe  admin       19 Dec 25 22:52 libruby.2.4.dylib -> libruby.2.4.3.dylib
lr-xr-xr-x  1 joe  admin       19 Dec 25 22:52 libruby.dylib -> libruby.2.4.3.dylib
drwxr-xr-x  3 joe  admin       96 Dec 25 22:52 pkgconfig
drwxr-xr-x  4 joe  admin      128 Dec 25 22:52 ruby
bash-3.2$ 
```

```
diff --git a/configure b/configure
index ea9b889..8e7ac39 100755
--- a/configure
+++ b/configure
@@ -25691,7 +25691,7 @@ esac
 	    libprefix="@executable_path/../${libdir_basename}"
 	    LIBRUBY_RELATIVE=yes
 	fi
-	LIBRUBY_DLDFLAGS="$LIBRUBY_DLDFLAGS "'-install_name '${libprefix}'/$(LIBRUBY_SO)'
+	LIBRUBY_DLDFLAGS="$LIBRUBY_DLDFLAGS "'-install_name '${libprefix}'/lib$(RUBY_BASE_NAME).$(MAJOR).$(MINOR).dylib'
 	LIBRUBY_DLDFLAGS="$LIBRUBY_DLDFLAGS "'-compatibility_version $(MAJOR).$(MINOR)'
 	LIBRUBY_DLDFLAGS="$LIBRUBY_DLDFLAGS "'-current_version $(RUBY_PROGRAM_VERSION)'
 	if test "$visibility_option" = ld; then
```

**Comment by ilovezfs** [comment]
```
bash-3.2$ otool -L /usr/local/Cellar/ruby/2.4.3_1/lib/ruby/2.4.0/x86_64-darwin17/psych.bundle
/usr/local/Cellar/ruby/2.4.3_1/lib/ruby/2.4.0/x86_64-darwin17/psych.bundle:
	/usr/local/Cellar/ruby/2.4.3_1/lib/libruby.2.4.dylib (compatibility version 2.4.0, current version 2.4.3)
	/usr/local/opt/libyaml/lib/libyaml-0.2.dylib (compatibility version 3.0.0, current version 3.5.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1252.0.0)
	/usr/lib/libobjc.A.dylib (compatibility version 1.0.0, current version 228.0.0)
```

**Comment by ilovezfs** [comment]
It looks like MacPorts is applying an identical patch:
https://github.com/macports/macports-ports/blob/master/lang/ruby24/files/patch-configure.diff

**Comment by ilovezfs** [comment]
Their corresponding issues are
https://trac.macports.org/ticket/54866
https://github.com/macports/macports-ports/commit/8522b08b8a42aaee3b4d9b0485ec2ef4cf3d3e53

And as noted there, this is apparently fixed in trunk and 2.5.0
https://bugs.ruby-lang.org/projects/ruby-trunk/repository/revisions/60018
https://bugs.ruby-lang.org/issues/13931

**Comment by ilovezfs** [comment]
I can confirm it's fixed in 2.5.0 without patching:
```
🍺  /usr/local/Cellar/ruby/2.5.0: 3,321 files, 18.4MB, built in 4 minutes 22 seconds
bash-3.2$ otool -L /usr/local/Cellar/ruby/2.5.0/lib/libruby.2.5.0.dylib 
/usr/local/Cellar/ruby/2.5.0/lib/libruby.2.5.0.dylib:
	/usr/local/opt/ruby/lib/libruby.2.5.dylib (compatibility version 2.5.0, current version 2.5.0)
	/System/Library/Frameworks/Foundation.framework/Versions/C/Foundation (compatibility version 300.0.0, current version 1443.14.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1252.0.0)
	/usr/lib/libobjc.A.dylib (compatibility version 1.0.0, current version 228.0.0)
	/System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation (compatibility version 150.0.0, current version 1445.12.0)
bash-3.2$ otool -L /usr/local/Cellar/ruby/2.5.0/lib/ruby/2.5.0/x86_64-darwin17/psych.bundle
/usr/local/Cellar/ruby/2.5.0/lib/ruby/2.5.0/x86_64-darwin17/psych.bundle:
	/usr/local/Cellar/ruby/2.5.0/lib/libruby.2.5.dylib (compatibility version 2.5.0, current version 2.5.0)
	/usr/local/opt/libyaml/lib/libyaml-0.2.dylib (compatibility version 3.0.0, current version 3.5.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1252.0.0)
	/usr/lib/libobjc.A.dylib (compatibility version 1.0.0, current version 228.0.0)
bash-3.2$ ls -l /usr/local/Cellar/ruby/2.5.0/lib
total 4640
-r--r--r--  1 joe  admin  2372216 Dec 25 23:26 libruby.2.5.0.dylib
lr-xr-xr-x  1 joe  admin       19 Dec 25 23:25 libruby.2.5.dylib -> libruby.2.5.0.dylib
lr-xr-xr-x  1 joe  admin       19 Dec 25 23:25 libruby.dylib -> libruby.2.5.0.dylib
drwxr-xr-x  3 joe  admin       96 Dec 25 23:25 pkgconfig
drwxr-xr-x  4 joe  admin      128 Dec 25 23:25 ruby
bash-3.2$
```

**Comment by ilovezfs** [comment]
The problem did not affect <= ruby@2.3 (they named the libraries libruby.2.3.0.dylib, libruby.2.2.0.dylib, etc. regardless of actual patch level version) so we only need to worry about backporting the patch to the new ruby@2.4 formula until/unless upstream backports it to the 2.4 branch and does a new release.

**Comment by ilovezfs** [comment]
The relevant commits are
https://github.com/ruby/ruby/commit/2c644a50ce69b66d85be2f19a4a090a551a18bde#diff-7e056ddc530791272d363e50c1f25647
https://github.com/ruby/ruby/commit/c739150c1e7ed9012e07a973c9bd280bc3cb376a#diff-7e056ddc530791272d363e50c1f25647

and have not been backported to the 2.4 branch yet.

**Comment by DomT4** [comment]
Nice hunting, and certainly good to know this has been fixed and won't keep happening _every minor update_.

> and have not been backported to the 2.4 branch yet.

I think if we accept a `ruby@2.4` formula we need to, at minimum, add the patch you proposed in https://github.com/Homebrew/homebrew-core/issues/22012#issuecomment-353928269. In terms of UX the existing linkage 🐛 is pretty unpleasant.

**Comment by ilovezfs** [comment]
Perhaps a good reason not to have a ruby@2.4.

**Comment by DomT4** [comment]
No objection here. The less versioned formulae the better, as a general rule.
