### ISSUE TITLE
PhantomJS 2.1.1 not working on macOS High Sierra (10.13.3)

### ISSUE THREAD

**Issue by megclaypool** [Homebrew/homebrew-core#23708]
I installed phantomjs using `brew install phantomjs`. It appeared to install normally. Brew info produces the following:
```
$ brew info phantomjs
phantomjs: stable 2.1.1 (bottled)
Headless WebKit scriptable with a JavaScript API
http://phantomjs.org/
/usr/local/Cellar/phantomjs/2.1.1 (50 files, 50.3MB) *
  Poured from bottle on 2018-02-05 at 11:57:01
From: https://github.com/Homebrew/homebrew-core/blob/master/Formula/phantomjs.rb
```
However, when I run `phantomjs` in the command line, I get the following sadness:
```
$  phantomjs
internal/child_process.js:325
    throw errnoException(err, 'spawn');
    ^

Error: spawn ENOTDIR
    at _errnoException (util.js:1021:11)
    at ChildProcess.spawn (internal/child_process.js:325:11)
    at exports.spawn (child_process.js:494:9)
    at Object.<anonymous> (/Users/noxlady/.nvm/versions/node/v8.7.0/lib/node_modules/phantomjs-prebuilt/bin/phantomjs:22:10)
    at Module._compile (module.js:624:30)
    at Object.Module._extensions..js (module.js:635:10)
    at Module.load (module.js:545:32)
    at tryModuleLoad (module.js:508:12)
    at Function.Module._load (module.js:500:3)
    at Function.Module.runMain (module.js:665:10)
```

I have run brew update and brew doctor. Brew gist logs gets the following:
```
$  brew gist-logs phantomjs
Error: No logs.
``` 

I'd really like to be able to use PhantomJS on my local as I write my tests, since that's what we're running on the test server. It's a pain to write tests that work locally and then fail on the server because I'm currently using ChromeDriver instead of PhantomJS :P Please let me know if there's any other info I can provide to assist in troubleshooting!

**Comment by ilovezfs** [comment]
Sorry I cannot reproduce this on 10.11 or 10.13. You'll need to discuss the error with the upstream project.
