### ISSUE TITLE
Error with "brew info llvm"

### ISSUE THREAD

**Issue by RMeli** [Homebrew/homebrew-core#23709]
**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

# Please always follow these steps:
- [x] Confirmed this is a problem with `brew install`ing one, specific Homebrew/homebrew-core formula (not cask or tap) and not every time you run `brew`? If it's a general `brew` problem please file this issue at https://github.com/Homebrew/brew/issues/new. If it's a `brew cask` problem please file this issue at https://github.com/caskroom/homebrew-cask/issues/new. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed all issues and retried your prior step?
- [x] Ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?

```
Error: undefined method `patch' for #<Resource:0x0000010224d508>
Please report this bug:
  https://docs.brew.sh/Troubleshooting.html
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/llvm.rb:66:in `block (2 levels) in <class:Llvm>'
/usr/local/Homebrew/Library/Homebrew/resource.rb:49:in `instance_eval'
/usr/local/Homebrew/Library/Homebrew/resource.rb:49:in `initialize'
/usr/local/Homebrew/Library/Homebrew/software_spec.rb:111:in `new'
/usr/local/Homebrew/Library/Homebrew/software_spec.rb:111:in `resource'
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/llvm.rb:59:in `block in <class:Llvm>'
/usr/local/Homebrew/Library/Homebrew/formula.rb:2109:in `instance_eval'
/usr/local/Homebrew/Library/Homebrew/formula.rb:2109:in `stable'
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/llvm.rb:23:in `<class:Llvm>'
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/llvm.rb:19:in `load_formula'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:27:in `module_eval'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:27:in `load_formula'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:47:in `load_formula_from_path'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:102:in `load_file'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:93:in `klass'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:89:in `get_formula'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:280:in `factory'
/usr/local/Homebrew/Library/Homebrew/extend/ARGV.rb:69:in `block in resolved_formulae'
/usr/local/Homebrew/Library/Homebrew/extend/ARGV.rb:54:in `map'
/usr/local/Homebrew/Library/Homebrew/extend/ARGV.rb:54:in `resolved_formulae'
/usr/local/Homebrew/Library/Homebrew/cmd/gist-logs.rb:125:in `gist_logs'
/usr/local/Homebrew/Library/Homebrew/brew.rb:100:in `<main>'
```

- [x] If `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

```
brew config
------------
HOMEBREW_VERSION: 1.5.0
ORIGIN: https://github.com/Homebrew/brew
HEAD: 985202cf8e3f9e221753dd99adf1e8874fece03a
Last commit: 3 weeks ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: dc0c6aa82e15ec88b75b91d1760b1f0e6230c899
Core tap last commit: 8 hours ago
HOMEBREW_PREFIX: /usr/local
CPU: octa-core 64-bit ivybridge
Homebrew Ruby: 2.3.3 => /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/bin/ruby
Clang: 9.0 build 900
Git: 2.14.3 => /Applications/Xcode.app/Contents/Developer/usr/bin/git
Curl: 7.54.0 => /usr/bin/curl
Perl: /usr/bin/perl
Python: /usr/local/opt/python/libexec/bin/python => /usr/local/Cellar/python/2.7.14_2/Frameworks/Python.framework/Versions/2.7/bin/python2.7
Ruby: /usr/local/bin/ruby => /usr/local/Cellar/ruby/2.5.0/bin/ruby
Java: 1.8.0_144
macOS: 10.13.3-x86_64
Xcode: 9.2
CLT: 9.2.0.0.1.1510905681
X11: 2.7.11 => /opt/X11
```

```
brew doctor
------------
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: "config" scripts exist outside your system or Homebrew directories.
`./configure` scripts often look for *-config scripts to determine if
software packages are installed, and what additional flags to use when
compiling and linking.

Having additional scripts in your path can confuse software installed via
Homebrew if the config script overrides a system or Homebrew provided
script of the same name. We found the following "config" scripts:
  /Users/rmeli/anaconda/envs/py36/bin/icu-config
  /Users/rmeli/anaconda/envs/py36/bin/freetype-config
  /Users/rmeli/anaconda/envs/py36/bin/xslt-config
  /Users/rmeli/anaconda/envs/py36/bin/libpng16-config
  /Users/rmeli/anaconda/envs/py36/bin/python3.6m-config
  /Users/rmeli/anaconda/envs/py36/bin/libpng-config
  /Users/rmeli/anaconda/envs/py36/bin/xml2-config
  /Users/rmeli/anaconda/envs/py36/bin/python3-config
  /Users/rmeli/anaconda/envs/py36/bin/curl-config
  /Users/rmeli/anaconda/envs/py36/bin/python3.6-config
  /Users/rmeli/anaconda/bin/icu-config
  /Users/rmeli/anaconda/bin/freetype-config
  /Users/rmeli/anaconda/bin/xslt-config
  /Users/rmeli/anaconda/bin/libpng16-config
  /Users/rmeli/anaconda/bin/python3.6m-config
  /Users/rmeli/anaconda/bin/libpng-config
  /Users/rmeli/anaconda/bin/xml2-config
  /Users/rmeli/anaconda/bin/python3-config
  /Users/rmeli/anaconda/bin/curl-config
  /Users/rmeli/anaconda/bin/python3.6-config

Warning: Unbrewed dylibs were found in /usr/local/lib.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected dylibs:
  /usr/local/lib/libtcl8.6.dylib
  /usr/local/lib/libtk8.6.dylib

Warning: Unbrewed header files were found in /usr/local/include.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected header files:
  /usr/local/include/fakemysql.h
  /usr/local/include/fakepq.h
  /usr/local/include/fakesql.h
  /usr/local/include/itcl.h
  /usr/local/include/itcl2TclOO.h
  /usr/local/include/itclDecls.h
  /usr/local/include/itclInt.h
  /usr/local/include/itclIntDecls.h
  /usr/local/include/itclMigrate2TclCore.h
  /usr/local/include/itclTclIntStubsFcn.h
  /usr/local/include/mysqlStubs.h
  /usr/local/include/node/android-ifaddrs.h
  /usr/local/include/node/libplatform/libplatform-export.h
  /usr/local/include/node/libplatform/libplatform.h
  /usr/local/include/node/libplatform/v8-tracing.h
  /usr/local/include/node/node.h
  /usr/local/include/node/node_api.h
  /usr/local/include/node/node_api_types.h
  /usr/local/include/node/node_buffer.h
  /usr/local/include/node/node_object_wrap.h
  /usr/local/include/node/node_version.h
  /usr/local/include/node/openssl/aes.h
  /usr/local/include/node/openssl/archs/BSD-x86/opensslconf.h
  /usr/local/include/node/openssl/archs/BSD-x86_64/opensslconf.h
  /usr/local/include/node/openssl/archs/VC-WIN32/opensslconf.h
  /usr/local/include/node/openssl/archs/VC-WIN64A/opensslconf.h
  /usr/local/include/node/openssl/archs/aix-gcc/opensslconf.h
  /usr/local/include/node/openssl/archs/aix64-gcc/opensslconf.h
  /usr/local/include/node/openssl/archs/darwin-i386-cc/opensslconf.h
  /usr/local/include/node/openssl/archs/darwin64-x86_64-cc/opensslconf.h
  /usr/local/include/node/openssl/archs/linux-aarch64/opensslconf.h
  /usr/local/include/node/openssl/archs/linux-armv4/opensslconf.h
  /usr/local/include/node/openssl/archs/linux-elf/opensslconf.h
  /usr/local/include/node/openssl/archs/linux-ppc/opensslconf.h
  /usr/local/include/node/openssl/archs/linux-ppc64/opensslconf.h
  /usr/local/include/node/openssl/archs/linux-x32/opensslconf.h
  /usr/local/include/node/openssl/archs/linux-x86_64/opensslconf.h
  /usr/local/include/node/openssl/archs/linux32-s390x/opensslconf.h
  /usr/local/include/node/openssl/archs/linux64-s390x/opensslconf.h
  /usr/local/include/node/openssl/archs/solaris-x86-gcc/opensslconf.h
  /usr/local/include/node/openssl/archs/solaris64-x86_64-gcc/opensslconf.h
  /usr/local/include/node/openssl/asn1.h
  /usr/local/include/node/openssl/asn1_mac.h
  /usr/local/include/node/openssl/asn1t.h
  /usr/local/include/node/openssl/bio.h
  /usr/local/include/node/openssl/blowfish.h
  /usr/local/include/node/openssl/bn.h
  /usr/local/include/node/openssl/buffer.h
  /usr/local/include/node/openssl/camellia.h
  /usr/local/include/node/openssl/cast.h
  /usr/local/include/node/openssl/cmac.h
  /usr/local/include/node/openssl/cms.h
  /usr/local/include/node/openssl/comp.h
  /usr/local/include/node/openssl/conf.h
  /usr/local/include/node/openssl/conf_api.h
  /usr/local/include/node/openssl/crypto.h
  /usr/local/include/node/openssl/des.h
  /usr/local/include/node/openssl/des_old.h
  /usr/local/include/node/openssl/dh.h
  /usr/local/include/node/openssl/dsa.h
  /usr/local/include/node/openssl/dso.h
  /usr/local/include/node/openssl/dtls1.h
  /usr/local/include/node/openssl/e_os2.h
  /usr/local/include/node/openssl/ebcdic.h
  /usr/local/include/node/openssl/ec.h
  /usr/local/include/node/openssl/ecdh.h
  /usr/local/include/node/openssl/ecdsa.h
  /usr/local/include/node/openssl/engine.h
  /usr/local/include/node/openssl/err.h
  /usr/local/include/node/openssl/evp.h
  /usr/local/include/node/openssl/hmac.h
  /usr/local/include/node/openssl/idea.h
  /usr/local/include/node/openssl/krb5_asn.h
  /usr/local/include/node/openssl/kssl.h
  /usr/local/include/node/openssl/lhash.h
  /usr/local/include/node/openssl/md4.h
  /usr/local/include/node/openssl/md5.h
  /usr/local/include/node/openssl/mdc2.h
  /usr/local/include/node/openssl/modes.h
  /usr/local/include/node/openssl/obj_mac.h
  /usr/local/include/node/openssl/objects.h
  /usr/local/include/node/openssl/ocsp.h
  /usr/local/include/node/openssl/opensslconf.h
  /usr/local/include/node/openssl/opensslv.h
  /usr/local/include/node/openssl/ossl_typ.h
  /usr/local/include/node/openssl/pem.h
  /usr/local/include/node/openssl/pem2.h
  /usr/local/include/node/openssl/pkcs12.h
  /usr/local/include/node/openssl/pkcs7.h
  /usr/local/include/node/openssl/pqueue.h
  /usr/local/include/node/openssl/rand.h
  /usr/local/include/node/openssl/rc2.h
  /usr/local/include/node/openssl/rc4.h
  /usr/local/include/node/openssl/ripemd.h
  /usr/local/include/node/openssl/rsa.h
  /usr/local/include/node/openssl/safestack.h
  /usr/local/include/node/openssl/seed.h
  /usr/local/include/node/openssl/sha.h
  /usr/local/include/node/openssl/srp.h
  /usr/local/include/node/openssl/srtp.h
  /usr/local/include/node/openssl/ssl.h
  /usr/local/include/node/openssl/ssl2.h
  /usr/local/include/node/openssl/ssl23.h
  /usr/local/include/node/openssl/ssl3.h
  /usr/local/include/node/openssl/stack.h
  /usr/local/include/node/openssl/symhacks.h
  /usr/local/include/node/openssl/tls1.h
  /usr/local/include/node/openssl/ts.h
  /usr/local/include/node/openssl/txt_db.h
  /usr/local/include/node/openssl/ui.h
  /usr/local/include/node/openssl/ui_compat.h
  /usr/local/include/node/openssl/whrlpool.h
  /usr/local/include/node/openssl/x509.h
  /usr/local/include/node/openssl/x509_vfy.h
  /usr/local/include/node/openssl/x509v3.h
  /usr/local/include/node/pthread-barrier.h
  /usr/local/include/node/stdint-msvc2008.h
  /usr/local/include/node/tree.h
  /usr/local/include/node/uv-aix.h
  /usr/local/include/node/uv-bsd.h
  /usr/local/include/node/uv-darwin.h
  /usr/local/include/node/uv-errno.h
  /usr/local/include/node/uv-linux.h
  /usr/local/include/node/uv-os390.h
  /usr/local/include/node/uv-posix.h
  /usr/local/include/node/uv-sunos.h
  /usr/local/include/node/uv-threadpool.h
  /usr/local/include/node/uv-unix.h
  /usr/local/include/node/uv-version.h
  /usr/local/include/node/uv-win.h
  /usr/local/include/node/uv.h
  /usr/local/include/node/v8-debug.h
  /usr/local/include/node/v8-inspector-protocol.h
  /usr/local/include/node/v8-inspector.h
  /usr/local/include/node/v8-platform.h
  /usr/local/include/node/v8-profiler.h
  /usr/local/include/node/v8-testing.h
  /usr/local/include/node/v8-util.h
  /usr/local/include/node/v8-value-serializer-version.h
  /usr/local/include/node/v8-version-string.h
  /usr/local/include/node/v8-version.h
  /usr/local/include/node/v8.h
  /usr/local/include/node/v8config.h
  /usr/local/include/node/zconf.h
  /usr/local/include/node/zlib.h
  /usr/local/include/odbcStubs.h
  /usr/local/include/pqStubs.h
  /usr/local/include/tcl.h
  /usr/local/include/tclDecls.h
  /usr/local/include/tclOO.h
  /usr/local/include/tclOODecls.h
  /usr/local/include/tclPlatDecls.h
  /usr/local/include/tclThread.h
  /usr/local/include/tclTomMath.h
  /usr/local/include/tclTomMathDecls.h
  /usr/local/include/tdbc.h
  /usr/local/include/tdbcDecls.h
  /usr/local/include/tdbcInt.h
  /usr/local/include/tk.h
  /usr/local/include/tkDecls.h
  /usr/local/include/tkPlatDecls.h

Warning: Unbrewed .pc files were found in /usr/local/lib/pkgconfig.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected .pc files:
  /usr/local/lib/pkgconfig/tcl.pc
  /usr/local/lib/pkgconfig/tk.pc

Warning: Unbrewed static libraries were found in /usr/local/lib.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected static libraries:
  /usr/local/lib/libtclstub8.6.a
  /usr/local/lib/libtkstub8.6.a

Warning: You have unlinked kegs in your Cellar
Leaving kegs unlinked can lead to build-trouble and cause brews that depend on
those kegs to fail to run properly once built. Run `brew link` on these:
  mpich

Warning: Some directories in your path end in a slash.
Directories in your path should not end in a slash. This can break other
doctor checks. The following directories should be edited:
  /Applications/qe-6.2/bin/

Warning: Broken symlinks were found. Remove them with `brew prune`:
  /usr/local/bin/docker
  /usr/local/bin/docker-compose
  /usr/local/bin/docker-credential-osxkeychain
  /usr/local/bin/docker-machine
  /usr/local/bin/electron
  /usr/local/bin/git-lfs
  /usr/local/bin/github
  /usr/local/bin/hyperkit
  /usr/local/bin/notary
  /usr/local/bin/vpnkit
  /usr/local/share/doc/ghc
  /usr/local/share/man/man1/al.1
  /usr/local/share/man/man1/asp-state.1
  /usr/local/share/man/man1/cccheck.1
  /usr/local/share/man/man1/ccrewrite.1
  /usr/local/share/man/man1/cert-sync.1
  /usr/local/share/man/man1/cert2spc.1
  /usr/local/share/man/man1/certmgr.1
  /usr/local/share/man/man1/chktrust.1
  /usr/local/share/man/man1/csharp.1
  /usr/local/share/man/man1/dbsessmgr.1
  /usr/local/share/man/man1/disco.1
  /usr/local/share/man/man1/dtd2xsd.1
  /usr/local/share/man/man1/fastcgi-mono-server.1
  /usr/local/share/man/man1/gacutil.1
  /usr/local/share/man/man1/genxs.1
  /usr/local/share/man/man1/httpcfg.1
  /usr/local/share/man/man1/ilasm.1
  /usr/local/share/man/man1/lc.1
  /usr/local/share/man/man1/macpack.1
  /usr/local/share/man/man1/makecert.1
  /usr/local/share/man/man1/mconfig.1
  /usr/local/share/man/man1/mcs.1
  /usr/local/share/man/man1/mdassembler.1
  /usr/local/share/man/man1/mdoc-assemble.1
  /usr/local/share/man/man1/mdoc-export-html.1
  /usr/local/share/man/man1/mdoc-export-msxdoc.1
  /usr/local/share/man/man1/mdoc-update.1
  /usr/local/share/man/man1/mdoc-validate.1
  /usr/local/share/man/man1/mdoc.1
  /usr/local/share/man/man1/mdvalidater.1
  /usr/local/share/man/man1/mkbundle.1
  /usr/local/share/man/man1/mod-mono-server.1
  /usr/local/share/man/man1/mono-api-info.1
  /usr/local/share/man/man1/mono-cil-strip.1
  /usr/local/share/man/man1/mono-configuration-crypto.1
  /usr/local/share/man/man1/mono-service.1
  /usr/local/share/man/man1/mono-shlib-cop.1
  /usr/local/share/man/man1/mono-symbolicate.1
  /usr/local/share/man/man1/mono-xmltool.1
  /usr/local/share/man/man1/mono.1
  /usr/local/share/man/man1/monodis.1
  /usr/local/share/man/man1/monodocer.1
  /usr/local/share/man/man1/monodocs2html.1
  /usr/local/share/man/man1/monolinker.1
  /usr/local/share/man/man1/monop.1
  /usr/local/share/man/man1/mozroots.1
  /usr/local/share/man/man1/mprof-report.1
  /usr/local/share/man/man1/msbuild.1
  /usr/local/share/man/man1/pdb2mdb.1
  /usr/local/share/man/man1/permview.1
  /usr/local/share/man/man1/resgen.1
  /usr/local/share/man/man1/secutil.1
  /usr/local/share/man/man1/setreg.1
  /usr/local/share/man/man1/sgen.1
  /usr/local/share/man/man1/signcode.1
  /usr/local/share/man/man1/sn.1
  /usr/local/share/man/man1/soapsuds.1
  /usr/local/share/man/man1/sqlsharp.1
  /usr/local/share/man/man1/vbnc.1
  /usr/local/share/man/man1/wsdl.1
  /usr/local/share/man/man1/xbuild.1
  /usr/local/share/man/man1/xsd.1
  /usr/local/share/man/man1/xsp.1
  /usr/local/share/man/man5/mdoc.5
Warning: Calling 'depends_on :fortran' is deprecated!
Use 'depends_on "gcc"' instead.
/usr/local/Homebrew/Library/Homebrew/dependency_collector.rb:88:in `parse_spec'

Warning: Calling 'depends_on :ant' is deprecated!
Use 'depends_on "ant"' instead.
/usr/local/Homebrew/Library/Homebrew/dependency_collector.rb:88:in `parse_spec'
```

To help us debug your issue please explain:
- What you were trying to do (and why): `brew info llvm` (to see if I can install `clang-tidy`)
- What happened (include command output):

```
brew info llvm
--------------
Error: undefined method `patch' for #<Resource:0x000001012fb7f8>
Please report this bug:
  https://docs.brew.sh/Troubleshooting.html
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/llvm.rb:66:in `block (2 levels) in <class:Llvm>'
/usr/local/Homebrew/Library/Homebrew/resource.rb:49:in `instance_eval'
/usr/local/Homebrew/Library/Homebrew/resource.rb:49:in `initialize'
/usr/local/Homebrew/Library/Homebrew/software_spec.rb:111:in `new'
/usr/local/Homebrew/Library/Homebrew/software_spec.rb:111:in `resource'
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/llvm.rb:59:in `block in <class:Llvm>'
/usr/local/Homebrew/Library/Homebrew/formula.rb:2109:in `instance_eval'
/usr/local/Homebrew/Library/Homebrew/formula.rb:2109:in `stable'
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/llvm.rb:23:in `<class:Llvm>'
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/llvm.rb:19:in `load_formula'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:27:in `module_eval'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:27:in `load_formula'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:47:in `load_formula_from_path'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:102:in `load_file'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:93:in `klass'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:89:in `get_formula'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:280:in `factory'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:453:in `find_with_priority'
/usr/local/Homebrew/Library/Homebrew/cmd/info.rb:55:in `block in print_info'
/usr/local/Homebrew/Library/Homebrew/cmd/info.rb:49:in `each'
/usr/local/Homebrew/Library/Homebrew/cmd/info.rb:49:in `each_with_index'
/usr/local/Homebrew/Library/Homebrew/cmd/info.rb:49:in `print_info'
/usr/local/Homebrew/Library/Homebrew/cmd/info.rb:38:in `info'
/usr/local/Homebrew/Library/Homebrew/brew.rb:100:in `<main>'
```

- What you expected to happen:  Display `llvm` info.
- Step-by-step reproduction instructions (by running `brew install` commands): `brew info llvm` or `brew install llvm` fail in the same way (see above).

# Formula additions or changes
To get formulae added or changed in Homebrew please file a [Pull Request](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)
We will close issues requesting formulae changes.

**Comment by DomT4** [comment]
Try `brew update --force`.
