### ISSUE TITLE
Pyqt pyrcc5 not working properly

### ISSUE THREAD

**Issue by Nenuial** [Homebrew/homebrew-core#24972]
**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [x] are reporting a bug others will be able to reproduce and not asking a question. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh
- [x] have a problem with `brew install` (or `upgrade`, `reinstall`) a single, official formula (not cask)? If it's a general `brew` problem please file this issue at Homebrew/brew: https://github.com/Homebrew/brew/issues/new. If it's a `brew cask` problem please file this issue at https://github.com/caskroom/homebrew-cask/issues/new. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [ ] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

I try to install pyqt as a dependency for QGIS3 and the pyrcc5/pyuic5 tools throw the following error when executed in the Terminal:
```
'import sitecustomize' failed; use -v for traceback
Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/usr/local/lib/python3.6/site-packages/PyQt5/pyrcc_main.py", line 21, in <module>
    from PyQt5.QtCore import PYQT_VERSION_STR, QDir, QFile
ImportError: dlopen(/usr/local/lib/python3.6/site-packages/PyQt5/QtCore.so, 2): Symbol not found: _PyBytes_AsString
  Referenced from: /usr/local/lib/python3.6/site-packages/PyQt5/QtCore.so
  Expected in: flat namespace
 in /usr/local/lib/python3.6/site-packages/PyQt5/QtCore.so
```

Logs can be found here : [gist-log](https://gist.github.com/Nenuial/7663d226969d7fcd4cee63469594215e)

**Comment by Nenuial** [comment]
Seems to be working now...
