### ISSUE TITLE
After upgrading python3: various binaries/modules are no longer found

### ISSUE THREAD

**Issue by Argon-** [Homebrew/homebrew-core#2545]
After upgrading `python3` `pip3` is no longer available and several modules are no longer found. 
The caveats of `python3` say:

    Pip, setuptools, and wheel have been installed. To update them
     pip3 install --upgrade pip setuptools wheel
    [...]
    They will install into the site-package directory
      /usr/local/lib/python3.5/site-packages

 But `pip3` is no longer found and e.g. `setuptools` is not found either:

    → pip3
    zsh: command not found: pip3
    → python3 -m setuptools
    /usr/local/bin/python3: No module named setuptools

After the upgrade there is neither a `pip3` nor a `pip` binary found on my system, only `pip2`.

The mentioned site-package directory does exist and looks like before the upgrade. It contains a pip folder and the mentioned modules (as well as things I installed (with `pip3`) and successfully used earlier).

This used to work prior to the update: The mentioned modules and binaries were found. I assume they are still there but something regarding paths changed. I did not change anything in my environment, I simply updated `python3`.
Except of exporting `PYTHONIOENCODING=UTF-8` I do not change any environmental variables regarding python, i.e. no `PYTHONPATH` etc.

* `brew` is up to date (updated before upgrading python, just a few minutes ago)
* `brew doctor` reports no problems

**Comment by Argon-** [comment]
For completion: `brew test` fails of course

    → brew test python3
    Testing python3
    ==> Using the sandbox
    ==> /usr/local/Cellar/python3/3.5.2/bin/python3.5 -c import sqlite3
    ==> /usr/local/Cellar/python3/3.5.2/bin/python3.5 -c import tkinter; root = tkinter.Tk()
    ==> /usr/local/Cellar/python3/3.5.2/bin/pip3 list
    Last 15 lines from /Users/Julian/Library/Logs/Homebrew/python3/03.pip3:
    2016-07-01 18:53:23 +0900
    
    /usr/local/Cellar/python3/3.5.2/bin/pip3
    list
    
    Error: python3: failed
    Failed executing: /usr/local/Cellar/python3/3.5.2/bin/pip3 list
    /usr/local/Library/Homebrew/formula.rb:1486:in `block in system'
    /usr/local/Library/Homebrew/formula.rb:1423:in `open'
    /usr/local/Library/Homebrew/formula.rb:1423:in `system'
    /usr/local/Library/Taps/homebrew/homebrew-core/Formula/python3.rb:353:in `block in <class:Python3>'
    /usr/local/Library/Homebrew/formula.rb:1328:in `block in run_test'
    /usr/local/Library/Homebrew/extend/fileutils.rb:14:in `block in mktemp'
    /usr/local/Library/Homebrew/extend/fileutils.rb:75:in `block in run'
    /usr/local/Library/Homebrew/extend/fileutils.rb:75:in `chdir'
    /usr/local/Library/Homebrew/extend/fileutils.rb:75:in `run'
    /usr/local/Library/Homebrew/extend/fileutils.rb:13:in `mktemp'
    /usr/local/Library/Homebrew/formula.rb:1322:in `run_test'
    /usr/local/Library/Homebrew/test.rb:28:in `block in <main>'
    /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/timeout.rb:66:in `timeout'
    /usr/local/Library/Homebrew/test.rb:27:in `<main>'

**Comment by Argon-** [comment]
In all the text output I did not notice one crucial message:

    Warning: The post-install step did not complete successfully

Executing `brew postinstall python3` worked and the above problems seem to be fixed. I would expect the formula to actually fail when such a crucial(?) step fails.
