### ISSUE TITLE
Error: undefined method `md5' for #<Class:0x000001012c4c58>

### ISSUE THREAD

**Issue by MakrisHuang** [Homebrew/homebrew-core#26585]
**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [x] are reporting a bug others will be able to reproduce and not asking a question. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh
- [x] have a problem with `brew install` (or `upgrade`, `reinstall`) a single, official formula (not cask)? If it's a general `brew` problem please file this issue at Homebrew/brew: https://github.com/Homebrew/brew/issues/new. If it's a `brew cask` problem please file this issue at https://github.com/caskroom/homebrew-cask/issues/new. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [x] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

To help us debug your issue please explain:
- What you were trying to do (and why)
run ``brew update``
- What happened (include command output)
```
Error: undefined method `md5' for #<Class:0x000001012c4c58>
Please report this bug:
  https://docs.brew.sh/Troubleshooting
/usr/local/opt/sshpass/.brew/sshpass.rb:6:in `<class:Sshpass>'
/usr/local/opt/sshpass/.brew/sshpass.rb:3:in `load_formula'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:26:in `module_eval'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:26:in `load_formula'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:46:in `load_formula_from_path'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:101:in `load_file'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:92:in `klass'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:88:in `get_formula'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:280:in `factory'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:308:in `from_keg'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:294:in `from_rack'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1388:in `block in installed'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1386:in `each'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1386:in `flat_map'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1386:in `installed'
/usr/local/Homebrew/Library/Homebrew/cmd/update-report.rb:505:in `migrate_formula_rename'
/usr/local/Homebrew/Library/Homebrew/cmd/update-report.rb:100:in `each'
/usr/local/Homebrew/Library/Homebrew/cmd/update-report.rb:100:in `update_report'
/usr/local/Homebrew/Library/Homebrew/brew.rb:101:in `<main>'
```
- What you expected to happen
Already up to date

- Step-by-step reproduction instructions (by running `brew install` commands)
By run either ``brew update`` or ``brew doctor``, I got this error

- Environment
macOS High Sierra 10.13.3
Homebrew 1.6.0
Homebrew/homebrew-core (git revision 13117; last commit 2018-04-14)

**Comment by MakrisHuang** [comment]
Solved, thanks
