### ISSUE TITLE
[root] formula does not link against python@2 correctly.

### ISSUE THREAD

**Issue by kratsg** [Homebrew/homebrew-core#26921]
```bash
kratsg:~$ brew install root --with-python@2 --without-python
....
kratsg:~$ . /usr/local/bin/thisroot.sh
kratsg:~$ python
Python 2.7.14 (default, Mar 22 2018, 15:04:47) 
[GCC 4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.39.2)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import ROOT
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/Cellar/root/6.12.06/lib/root/ROOT.py", line 24, in <module>
    import cppyy
  File "/usr/local/Cellar/root/6.12.06/lib/root/cppyy.py", line 61, in <module>
    import libPyROOT as _backend
ImportError: dynamic module does not define init function (initlibPyROOT)
```

Brew doctor: system raring to brew (no issues)

What I expect to happen: being able to import PyROOT without issues as in all previous versions of homebrew-root.

**Comment by commitay** [comment]
**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**
