### ISSUE TITLE
 Removing sshpass throws the following error

### ISSUE THREAD

**Issue by rajeshkp** [Homebrew/homebrew-core#27317]
**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [ ] are reporting a bug others will be able to reproduce and not asking a question. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh
- [ ] have a problem with `brew install` (or `upgrade`, `reinstall`) a single, official formula (not cask)? If it's a general `brew` problem please file this issue at Homebrew/brew: https://github.com/Homebrew/brew/issues/new. If it's a `brew cask` problem please file this issue at https://github.com/caskroom/homebrew-cask/issues/new. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [ ] ran `brew update` and can still reproduce the problem?
- [ ] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [ ] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [ ] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

To help us debug your issue please explain:
- What you were trying to do (and why)
- What happened (include command output)
- What you expected to happen
- Step-by-step reproduction instructions (by running `brew install` commands)

# Formula additions or changes
To get formulae added or changed in Homebrew please file a [Pull Request](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)
We will close issues requesting formulae changes.

```
brew --version
Homebrew 1.6.2
Homebrew/homebrew-core (git revision c7482; last commit 2018-05-01)
```

```
brew update
Already up-to-date.
```

```
brew rm sshpass
Error: undefined method `md5' for #<Class:0x0000010153df70>
Please report this bug:
  https://docs.brew.sh/Troubleshooting
/usr/local/opt/sshpass/.brew/sshpass.rb:6:in `<class:Sshpass>'
/usr/local/opt/sshpass/.brew/sshpass.rb:3:in `load_formula'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:26:in `module_eval'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:26:in `load_formula'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:46:in `load_formula_from_path'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:101:in `load_file'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:92:in `klass'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:88:in `get_formula'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:280:in `factory'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:308:in `from_keg'
/usr/local/Homebrew/Library/Homebrew/keg.rb:380:in `to_formula'
/usr/local/Homebrew/Library/Homebrew/keg.rb:110:in `block in find_some_installed_dependents'
/usr/local/Homebrew/Library/Homebrew/keg.rb:106:in `each'
/usr/local/Homebrew/Library/Homebrew/keg.rb:106:in `group_by'
/usr/local/Homebrew/Library/Homebrew/keg.rb:106:in `find_some_installed_dependents'
/usr/local/Homebrew/Library/Homebrew/cmd/uninstall.rb:100:in `check_for_dependents'
/usr/local/Homebrew/Library/Homebrew/cmd/uninstall.rb:93:in `handle_unsatisfied_dependents'
/usr/local/Homebrew/Library/Homebrew/cmd/uninstall.rb:31:in `uninstall'
/usr/local/Homebrew/Library/Homebrew/brew.rb:101:in `<main>'
```

**Comment by SMillerDev** [comment]
Did the fix from #26585 work for you?

**Comment by rajeshkp** [comment]
Yes, I need sshpass as well. If I install sshpass I run into the same issue.

**Comment by SMillerDev** [comment]
You'll need to modify the formula to stop using md5 hashes then. There's multiple options for people who did that before if you google it though, one of the first results: https://github.com/hudochenkov/homebrew-sshpass/blob/master/sshpass.rb
