### ISSUE TITLE
pipenv installed but not working. Should we have pipenv in `pip3 list` after install?

### ISSUE THREAD

**Issue by EMayej** [Homebrew/homebrew-core#27746]
**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [x] are reporting a bug others will be able to reproduce and not asking a question. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh
- [x] have a problem with `brew install` (or `upgrade`, `reinstall`) a single, official formula (not cask)? If it's a general `brew` problem please file this issue at Homebrew/brew: https://github.com/Homebrew/brew/issues/new/choose. If it's a `brew cask` problem please file this issue at https://github.com/caskroom/homebrew-cask/issues/new. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?

https://gist.github.com/EMayej/726a0398126cfaf365537506c043d397
- [x] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

To help us debug your issue please explain:

1. Install pipenv with `brew install pipenv`
2. `pipenv` reports python can't find pipenv when running the command
```
 ~/temp  pipenv install sh
Creating a virtualenv for this project…
Using /usr/local/bin/python3 (3.6.5) to create virtualenv…
⠋/usr/local/opt/python/bin/python3.6: Error while finding module specification for 'pipenv.pew' (ModuleNotFoundError: No module named 'pipenv')

Virtualenv location:
Creating a Pipfile for this project…
Traceback (most recent call last):
  File "/usr/local/Cellar/pipenv/11.10.4/libexec/bin/pipenv", line 11, in <module>
    load_entry_point('pipenv==11.10.4', 'console_scripts', 'pipenv')()
  File "/usr/local/Cellar/pipenv/11.10.4/libexec/lib/python3.6/site-packages/pipenv/vendor/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/Cellar/pipenv/11.10.4/libexec/lib/python3.6/site-packages/pipenv/vendor/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/Cellar/pipenv/11.10.4/libexec/lib/python3.6/site-packages/pipenv/vendor/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/Cellar/pipenv/11.10.4/libexec/lib/python3.6/site-packages/pipenv/vendor/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/Cellar/pipenv/11.10.4/libexec/lib/python3.6/site-packages/pipenv/vendor/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/Cellar/pipenv/11.10.4/libexec/lib/python3.6/site-packages/pipenv/cli.py", line 402, in install
    selective_upgrade=selective_upgrade,
  File "/usr/local/Cellar/pipenv/11.10.4/libexec/lib/python3.6/site-packages/pipenv/core.py", line 1781, in do_install
    skip_requirements=skip_requirements,
  File "/usr/local/Cellar/pipenv/11.10.4/libexec/lib/python3.6/site-packages/pipenv/core.py", line 650, in ensure_project
    ensure_pipfile(validate=validate, skip_requirements=skip_requirements, system=system)
  File "/usr/local/Cellar/pipenv/11.10.4/libexec/lib/python3.6/site-packages/pipenv/core.py", line 304, in ensure_pipfile
    project.create_pipfile(python=python)
  File "/usr/local/Cellar/pipenv/11.10.4/libexec/lib/python3.6/site-packages/pipenv/project.py", line 601, in create_pipfile
    required_python = self.which('python')
  File "/usr/local/Cellar/pipenv/11.10.4/libexec/lib/python3.6/site-packages/pipenv/core.py", line 128, in which
    p = os.sep.join([location] + ['bin/{0}'.format(command)])
TypeError: sequence item 0: expected str instance, NoneType found
```
3. there is no pipenv in `pip3 list`
```
 ✘  ~/temp  pip3 list
Package    Version
---------- -------
pip        10.0.1
setuptools 39.0.1
wheel      0.31.0
```
4. after manually install pipenv with pip3, pipenv is fine
```shell
 ~/temp  pip3 install pipenv
Collecting pipenv
  Using cached https://files.pythonhosted.org/packages/ac/49/b95f5a1d5e1a0bbdb42ac96c19927a4af7b067aecefc1b6eeefbe4e3706c/pipenv-11.10.4-py3-none-any.whl
Collecting virtualenv-clone>=0.2.5 (from pipenv)
  Using cached https://files.pythonhosted.org/packages/6d/c2/dccb5ccf599e0c5d1eea6acbd058af7a71384f9740179db67a9182a24798/virtualenv_clone-0.3.0-py2.py3-none-any.whl
Requirement already satisfied: pip>=9.0.1 in /usr/local/lib/python3.6/site-packages (from pipenv) (10.0.1)
Collecting virtualenv (from pipenv)
  Using cached https://files.pythonhosted.org/packages/ed/ea/e20b5cbebf45d3096e8138ab74eda139595d827677f38e9dd543e6015bdf/virtualenv-15.2.0-py2.py3-none-any.whl
Collecting certifi (from pipenv)
  Using cached https://files.pythonhosted.org/packages/7c/e6/92ad559b7192d846975fc916b65f667c7b8c3a32bea7372340bfe9a15fa5/certifi-2018.4.16-py2.py3-none-any.whl
Requirement already satisfied: setuptools>=36.2.1 in /usr/local/lib/python3.6/site-packages (from pipenv) (39.0.1)
Installing collected packages: virtualenv-clone, virtualenv, certifi, pipenv
Could not install packages due to an EnvironmentError: [Errno 13] Permission denied: '/usr/local/bin/pipenv'
Consider using the `--user` option or check the permissions.

 ✘  ~/temp  pipenv install sh
Creating a virtualenv for this project…
Using /usr/local/bin/python3 (3.6.5) to create virtualenv…
⠋Running virtualenv with interpreter /usr/local/bin/python3
Using base prefix '/usr/local/Cellar/python/3.6.5/Frameworks/Python.framework/Versions/3.6'
New python executable in /Users/EMayej/.local/share/virtualenvs/temp-wcU4UHMl/bin/python3.6
Also creating executable in /Users/EMayej/.local/share/virtualenvs/temp-wcU4UHMl/bin/python
Installing setuptools, pip, wheel...done.

Virtualenv location: /Users/EMayej/.local/share/virtualenvs/temp-wcU4UHMl
Creating a Pipfile for this project…
Installing sh…
Collecting sh
  Using cached https://files.pythonhosted.org/packages/4a/22/17b22ef5b049f12080f5815c41bf94de3c229217609e469001a8f80c1b3d/sh-1.12.14-py2.py3-none-any.whl
Installing collected packages: sh
Successfully installed sh-1.12.14

Adding sh to Pipfile's [packages]…
Pipfile.lock not found, creating…
Locking [dev-packages] dependencies…
Locking [packages] dependencies…
Updated Pipfile.lock (ddb902)!
Installing dependencies from Pipfile.lock (ddb902)…
  🐍   ▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉ 1/1 — 00:00:00
To activate this project's virtualenv, run the following:
 $ pipenv shell
```

This appears on both my macbook air and mac mini. How should I dig the problem?
@richardcooper

**Comment by ilovezfs** [comment]
I cannot reproduce this with the latest `pipenv`.
```
iMac-TMP:~ joe$ brew install pipenv
==> Downloading https://homebrew.bintray.com/bottles/pipenv-2018.5.18.el_capitan.bottle.tar.gz
######################################################################## 100.0%
==> Pouring pipenv-2018.5.18.el_capitan.bottle.tar.gz
==> Caveats
Bash completion has been installed to:
  /usr/local/etc/bash_completion.d
==> Summary
🍺  /usr/local/Cellar/pipenv/2018.5.18: 1,540 files, 23MB
iMac-TMP:~ joe$ mkdir testpipenv
iMac-TMP:~ joe$ cd testpipenv/
iMac-TMP:testpipenv joe$ pipenv install sh
Creating a virtualenv for this project…
Using /usr/local/Cellar/pipenv/2018.5.18/libexec/bin/python3.6 (3.6.5) to create virtualenv…
⠋Already using interpreter /usr/local/Cellar/pipenv/2018.5.18/libexec/bin/python3.6
Using real prefix '/usr/local/Cellar/python/3.6.5/Frameworks/Python.framework/Versions/3.6'
New python executable in /Users/joe/.local/share/virtualenvs/testpipenv-KLMEsg1a/bin/python3.6
Also creating executable in /Users/joe/.local/share/virtualenvs/testpipenv-KLMEsg1a/bin/python
Installing setuptools, pip, wheel...done.

Virtualenv location: /Users/joe/.local/share/virtualenvs/testpipenv-KLMEsg1a
Creating a Pipfile for this project…
Installing sh…
Collecting sh
  Downloading https://files.pythonhosted.org/packages/4a/22/17b22ef5b049f12080f5815c41bf94de3c229217609e469001a8f80c1b3d/sh-1.12.14-py2.py3-none-any.whl
Installing collected packages: sh
Successfully installed sh-1.12.14

Adding sh to Pipfile's [packages]…
Pipfile.lock not found, creating…
Locking [dev-packages] dependencies…
Locking [packages] dependencies…
Updated Pipfile.lock (ddb902)!
Installing dependencies from Pipfile.lock (ddb902)…
  🐍   ▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉ 1/1 — 00:00:00
To activate this project's virtualenv, run the following:
 $ pipenv shell
iMac-TMP:testpipenv joe$ 
```
Please let us know if you're still having a problem after `brew update && brew upgrade`

**Comment by EMayej** [comment]
Thanks for your response.

I looked around and finally find out that this problem comes from my environment setting. 

My shell is launched with `__PYVENV_LAUNCHER__=/usr/local/bin/python3`, thus `sys.executable` is always `/usr/local/bin/python3`, instead of `/usr/local/Cellar/pipenv/2018.5.18/libexec/bin/python3.6`. 

pipenv relies on `sys.executable` to find python executable but `sys.executable` is polluted so it can't find the real file it needs.

**Comment by ilovezfs** [comment]
Nice sleuthing! Thanks for following up.
