### ISSUE TITLE
OSError: [Errno 1] Operation not permitted for python@2 –with-tcl-tk

### ISSUE THREAD

**Issue by Marslo** [Homebrew/homebrew-core#28168]
**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [x] are reporting a bug others will be able to reproduce and not asking a question. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh
- [x] have a problem with `brew install` (or `upgrade`, `reinstall`) a single, official formula (not cask)? If it's a general `brew` problem please file this issue at Homebrew/brew: https://github.com/Homebrew/brew/issues/new/choose. If it's a `brew cask` problem please file this issue at https://github.com/caskroom/homebrew-cask/issues/new/choose. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
gist link: https://gist.github.com/Marslo/e84db14e8dad58be32a2c657ccf56d8a
- [ ] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

To help us debug your issue please explain:
- What you were trying to do (and why)
- What happened (include command output) 
- What you expected to happen
- Step-by-step reproduction instructions (by running `brew install` commands)

----------

To fix the python IDLE WARNING "OSError: [Errno 1] Operation not permitted for python@2 –with-tcl-tk"
I've uninstalled the python@2, and install the tcl-tk and reinstall the python@2:
```
$ brew uninstall --force python@2
$ rm -rf /usr/local/lib/python2.7*
$ brew install tcl-tk
$ brew install python@2 --with-tcl-tk --HEAD
```
Error shows as below:
```
$ brew install python@2 --with-tcl-tk --HEAD
Updating Homebrew...
==> Cloning https://github.com/python/cpython.git
Cloning into '/Users/marslo/Library/Caches/Homebrew/python@2--git'...
Warning: Permanently added 'github.com,192.30.253.112' (RSA) to the list of known hosts.
remote: Counting objects: 4847, done.
remote: Compressing objects: 100% (4285/4285), done.
remote: Total 4847 (delta 643), reused 2614 (delta 470), pack-reused 0
Receiving objects: 100% (4847/4847), 17.28 MiB | 22.00 KiB/s, done.
Resolving deltas: 100% (643/643), done.
Checking out files: 100% (4593/4593), done.
==> Checking out branch 2.7
==> Downloading https://raw.githubusercontent.com/Homebrew/patches/42fcf22/python/brewed-tk-patch.diff
==> Patching
==> Applying brewed-tk-patch.diff
patching file setup.py
Hunk #1 succeeded at 1882 (offset 72 lines).
Hunk #2 succeeded at 1927 (offset 72 lines).
Hunk #3 succeeded at 1951 (offset 72 lines).
==> ./configure --prefix=/usr/local/Cellar/python@2/HEAD-3ccc313 --enable-ipv6 --datarootdir=/usr/local/Cellar/python@2/HEAD-3ccc313/share --datadir=/usr/local/Cellar/python@2/HEAD-3ccc313/share --enable-framework=/usr/local/Cellar/python@2/HEAD-3ccc313/Frameworks --without-ensurepip --without-gcc MACOSX_DEPLOYMENT_TARGET=10.13 LDFLAGS=-L/usr/local/opt/tcl-tk/lib CPPFLAGS=-I/usr/local/opt/tcl-tk/include
==> make
==> make install PYTHONAPPSDIR=/usr/local/Cellar/python@2/HEAD-3ccc313
==> make frameworkinstallextras PYTHONAPPSDIR=/usr/local/Cellar/python@2/HEAD-3ccc313/share/python@2
Last 15 lines from /Users/marslo/Library/Logs/Homebrew/python@2/04.make:
copy ./../Demo/README /usr/local/Cellar/python@2/HEAD-3ccc313/share/python@2/Extras/Demo/README
Traceback (most recent call last):
  File "./Extras.install.py", line 54, in <module>
    main()
  File "./Extras.install.py", line 51, in main
    copycleandir(sys.argv[1], sys.argv[2])
  File "./Extras.install.py", line 37, in copycleandir
    shutil.copy2(os.path.join(cursrc, fn), os.path.join(curdst, fn))
  File "/private/tmp/python@2-20180522-5265-hrazr9/Lib/shutil.py", line 145, in copy2
    copystat(src, dst)
  File "/private/tmp/python@2-20180522-5265-hrazr9/Lib/shutil.py", line 117, in copystat
    os.chflags(dst, st.st_flags)
OSError: [Errno 1] Operation not permitted: '/usr/local/Cellar/python@2/HEAD-3ccc313/share/python@2/Extras/Demo/README'
make[1]: *** [installextras] Error 1
make: *** [frameworkinstallextras] Error 2

READ THIS: https://docs.brew.sh/Troubleshooting
```

So, according to the [Homebrew Troubleshooting](https://docs.brew.sh/Troubleshooting) page, I've ran:
```
$ brew update
$ brew update
$ brew doctor      <<-- only warning, no error
$ cd /usr/local
$ sudo chown -R $(whoami) bin etc include lib sbin share var Frameworks
chown: cannot access 'Frameworks': No such file or directory
```

And rerun the brew install with and without --HEAD, but no lucky:
```
$ brew install python@2 --with-tcl-tk
$ brew install python@2 --with-tcl-tk --HEAD
```

So, I've tried build it manually (according the commands print out in brew install):
```
$ cd /Users/marslo/Library/Caches/Homebrew/python@2--git
$ ./configure --prefix=/usr/local/Cellar/python@2/HEAD-3ccc313 --enable-ipv6 --datarootdir=/usr/local/Cellar/python@2/HEAD-3ccc313/share --datadir=/usr/local/Cellar/python@2/HEAD-3ccc313/share --enable-framework=/usr/local/Cellar/python@2/HEAD-3ccc313/Frameworks --without-ensurepip --without-gcc MACOSX_DEPLOYMENT_TARGET=10.13 LDFLAGS=-L/usr/local/opt/tcl-tk/lib CPPFLAGS=-I/usr/local/opt/tcl-tk/include
$ make
...
Python build finished, but the necessary bits to build these modules were not found:
_bsddb             _ssl               dl
imageop            linuxaudiodev      ossaudiodev
spwd               sunaudiodev
To find the necessary bits, look in setup.py in detect_modules() for the module's name.
...
$ make install PYTHONAPPSDIR=/usr/local/Cellar/python@2/HEAD-3ccc313
$ make frameworkinstallextras PYTHONAPPSDIR=/usr/local/Cellar/python@2/HEAD-3ccc313/share/python@2
cd Mac && /Applications/Xcode.app/Contents/Developer/usr/bin/make installextras DESTDIR=""
/usr/local/opt/coreutils/libexec/gnubin/install -c -d "/usr/local/Cellar/python@2/HEAD-3ccc313/share/python@2/Extras"
/usr/local/opt/coreutils/libexec/gnubin/install -c ./Extras.ReadMe.txt "/usr/local/Cellar/python@2/HEAD-3ccc313/share/python@2/Extras/ReadMe.txt"
DYLD_FRAMEWORK_PATH=/Users/marslo/Library/Caches/Homebrew/python@2--git ../python.exe ./Extras.install.py ./../Demo \
		"/usr/local/Cellar/python@2/HEAD-3ccc313/share/python@2/Extras/Demo"
mkdir /usr/local/Cellar/python@2/HEAD-3ccc313/share/python@2/Extras/Demo
copy ./../Demo/README /usr/local/Cellar/python@2/HEAD-3ccc313/share/python@2/Extras/Demo/README
Traceback (most recent call last):
  File "./Extras.install.py", line 54, in <module>
    main()
  File "./Extras.install.py", line 51, in main
    copycleandir(sys.argv[1], sys.argv[2])
  File "./Extras.install.py", line 37, in copycleandir
    shutil.copy2(os.path.join(cursrc, fn), os.path.join(curdst, fn))
  File "/Users/marslo/Library/Caches/Homebrew/python@2--git/Lib/shutil.py", line 145, in copy2
    copystat(src, dst)
  File "/Users/marslo/Library/Caches/Homebrew/python@2--git/Lib/shutil.py", line 117, in copystat
    os.chflags(dst, st.st_flags)
OSError: [Errno 1] Operation not permitted: '/usr/local/Cellar/python@2/HEAD-3ccc313/share/python@2/Extras/Demo/README'
make[1]: *** [installextras] Error 1
make: *** [frameworkinstallextras] Error 2
```

Still the same error. So, I've re-run the `chown` in `/usr/local`, no lucky.

Finally, I've using `sudo` for `make install`, and it works:
```
$ sudo make frameworkinstallextras PYTHONAPPSDIR=/usr/local/Cellar/python@2/HEAD-3ccc313/share/python@2
cd Mac && /Applications/Xcode.app/Contents/Developer/usr/bin/make installextras DESTDIR=""
/usr/local/opt/coreutils/libexec/gnubin/install -c -d "/usr/local/Cellar/python@2/HEAD-3ccc313/share/python@2/Extras"
/usr/local/opt/coreutils/libexec/gnubin/install -c ./Extras.ReadMe.txt "/usr/local/Cellar/python@2/HEAD-3ccc313/share/python@2/Extras/ReadMe.txt"
DYLD_FRAMEWORK_PATH=/Users/marslo/Library/Caches/Homebrew/python@2--git ../python.exe ./Extras.install.py ./../Demo \
		"/usr/local/Cellar/python@2/HEAD-3ccc313/share/python@2/Extras/Demo"
mkdir /usr/local/Cellar/python@2/HEAD-3ccc313/share/python@2/Extras/Demo
.....
.....
copy ./Demo/sound/morse.py /usr/local/Cellar/python@2/HEAD-3ccc313/share/python@2/Extras/Demo.Mac/sound/morse.py
$ cd /usr/local
$ sudo chown -R $(whoami) bin etc include lib sbin share var
```

But, actually, I don't know what should do after the command `make frameworkinstallextras PYTHONAPPSDIR=/usr/local/Cellar/python@2/HEAD-3ccc313/share/python@2` succeed.
I still want this issue will be fixed.

**Comment by apjanke** [comment]
I cannot reproduce on macOS 10.13.4, with or without `--HEAD`. Sounds like permission issues in your particular machine's filesystem.

Side note: The `--HEAD` option is really for developers only; it's normal for it to be broken, and Homebrew can't really support that. Try removing all the `--HEAD` options from all the `brew` stuff you've done and try again, and don't use them in the future. (If you need help building stuff from `--HEAD`, you need to report that to the upstream maintainers of those packages, which isn't something Homebrew can help much with.)

Based on this from your build log...

```
copy ./../Demo/README /usr/local/Cellar/python@2/2.7.15/share/python@2/Extras/Demo/README
Traceback (most recent call last):
  File "./Extras.install.py", line 54, in <module>
    main()
  File "./Extras.install.py", line 51, in main
    copycleandir(sys.argv[1], sys.argv[2])
  File "./Extras.install.py", line 37, in copycleandir
    shutil.copy2(os.path.join(cursrc, fn), os.path.join(curdst, fn))
  File "/private/tmp/python@2-20180523-86976-1squ00z/Python-2.7.15/Lib/shutil.py", line 145, in copy2
    copystat(src, dst)
  File "/private/tmp/python@2-20180523-86976-1squ00z/Python-2.7.15/Lib/shutil.py", line 117, in copystat
    os.chflags(dst, st.st_flags)
OSError: [Errno 1] Operation not permitted: '/usr/local/Cellar/python@2/2.7.15/share/python@2/Extras/Demo/README'
make[1]: *** [installextras] Error 1
make: *** [frameworkinstallextras] Error 2
```

...it looks to me like you may have a previous `python@2` installation hanging around from a previous `sudo brew` incantation, or as a different user.

`sudo` does not play well with Homebrew. I'd recommend avoiding it.

I recommend you completely blow away your old `python@2` installations by doing this:

```
sudo rm -rf /usr/local/Cellar/python@2
```

...and then re-installing Python with `brew install python@2 --=with-tcl-tk`

And if that doesn't work, completely blow away `/usr/local` and re-install Homebrew from scratch, and avoid using `sudo` with it at all. You will also need to re-install `node` (which I see from your `doctor` logs is present in `/usr/local` but apparently not managed by `brew`), which you can do with `brew`.

**Comment by Marslo** [comment]
Thanks @apjanke, sorry for replay late. I will have a try and give your feedback.
