### ISSUE TITLE
Failure "brew doctor" and "brew cleanup"

### ISSUE THREAD

**Issue by daisuuke** [Homebrew/homebrew-core#2829]
### Bug reports:
```
brew doctor
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry and just ignore them. Thanks!

Warning: Python is installed at /Library/Frameworks/Python.framework

Homebrew only supports building against the System-provided Python or a
brewed Python. In particular, Pythons installed to /Library can interfere
with other software installs.

Warning: You have unlinked kegs in your Cellar
Leaving kegs unlinked can lead to build-trouble and cause brews that depend on
those kegs to fail to run properly once built. Run `brew link` on these:
    python
    ruby
    wxmac

Warning: Suspicious git origin remote found.

With a non-standard origin, Homebrew won't pull updates from
the main repository. The current git origin is:
  https://github.com/Homebrew/brew.git

Unless you have compelling reasons, consider setting the
origin remote to point at the main repository, located at:
  https://github.com/Homebrew/homebrew.git
Error: Unsupported special dependency :perl
Please report this bug:
    https://git.io/brew-troubleshooting
/usr/local/Library/Homebrew/dependency_collector.rb:123:in `parse_symbol_spec'
/usr/local/Library/Homebrew/compat/dependency_collector.rb:17:in `parse_symbol_spec'
/usr/local/Library/Homebrew/dependency_collector.rb:73:in `parse_spec'
/usr/local/Library/Homebrew/dependency_collector.rb:61:in `build'
/usr/local/Library/Homebrew/dependency_collector.rb:48:in `block in fetch'
/usr/local/Library/Homebrew/dependency_collector.rb:48:in `fetch'
/usr/local/Library/Homebrew/dependency_collector.rb:48:in `fetch'
/usr/local/Library/Homebrew/dependency_collector.rb:38:in `add'
/usr/local/Library/Homebrew/software_spec.rb:155:in `depends_on'
/usr/local/Library/Homebrew/formula.rb:1859:in `block in depends_on'
/usr/local/Library/Homebrew/formula.rb:1859:in `each'
/usr/local/Library/Homebrew/formula.rb:1859:in `depends_on'
/usr/local/Library/Taps/homebrew/homebrew-core/Formula/imagemagick.rb:55:in `<class:Imagemagick>'
/usr/local/Library/Taps/homebrew/homebrew-core/Formula/imagemagick.rb:1:in `load_formula'
/usr/local/Library/Homebrew/formulary.rb:21:in `module_eval'
/usr/local/Library/Homebrew/formulary.rb:21:in `load_formula'
/usr/local/Library/Homebrew/formulary.rb:34:in `load_formula_from_path'
/usr/local/Library/Homebrew/formulary.rb:83:in `load_file'
/usr/local/Library/Homebrew/formulary.rb:74:in `klass'
/usr/local/Library/Homebrew/formulary.rb:70:in `get_formula'
/usr/local/Library/Homebrew/formulary.rb:167:in `get_formula'
/usr/local/Library/Homebrew/formulary.rb:207:in `factory'
/usr/local/Library/Homebrew/formulary.rb:226:in `from_rack'
/usr/local/Library/Homebrew/formula.rb:1134:in `block in installed'
/usr/local/Library/Homebrew/formula.rb:1132:in `map'
/usr/local/Library/Homebrew/formula.rb:1132:in `installed'
/usr/local/Library/Homebrew/diagnostic.rb:1119:in `check_missing_deps'
/usr/local/Library/Homebrew/cmd/doctor.rb:34:in `block in doctor'
/usr/local/Library/Homebrew/cmd/doctor.rb:27:in `each'
/usr/local/Library/Homebrew/cmd/doctor.rb:27:in `doctor'
/usr/local/Library/brew.rb:83:in `<main>'
```

```
brew cleanup
Error: Unsupported special dependency :perl
Please report this bug:
    https://git.io/brew-troubleshooting
/usr/local/Library/Homebrew/dependency_collector.rb:123:in `parse_symbol_spec'
/usr/local/Library/Homebrew/compat/dependency_collector.rb:17:in `parse_symbol_spec'
/usr/local/Library/Homebrew/dependency_collector.rb:73:in `parse_spec'
/usr/local/Library/Homebrew/dependency_collector.rb:61:in `build'
/usr/local/Library/Homebrew/dependency_collector.rb:48:in `block in fetch'
/usr/local/Library/Homebrew/dependency_collector.rb:48:in `fetch'
/usr/local/Library/Homebrew/dependency_collector.rb:48:in `fetch'
/usr/local/Library/Homebrew/dependency_collector.rb:38:in `add'
/usr/local/Library/Homebrew/software_spec.rb:155:in `depends_on'
/usr/local/Library/Homebrew/formula.rb:1859:in `block in depends_on'
/usr/local/Library/Homebrew/formula.rb:1859:in `each'
/usr/local/Library/Homebrew/formula.rb:1859:in `depends_on'
/usr/local/Library/Taps/homebrew/homebrew-core/Formula/imagemagick.rb:55:in `<class:Imagemagick>'
/usr/local/Library/Taps/homebrew/homebrew-core/Formula/imagemagick.rb:1:in `load_formula'
/usr/local/Library/Homebrew/formulary.rb:21:in `module_eval'
/usr/local/Library/Homebrew/formulary.rb:21:in `load_formula'
/usr/local/Library/Homebrew/formulary.rb:34:in `load_formula_from_path'
/usr/local/Library/Homebrew/formulary.rb:83:in `load_file'
/usr/local/Library/Homebrew/formulary.rb:74:in `klass'
/usr/local/Library/Homebrew/formulary.rb:70:in `get_formula'
/usr/local/Library/Homebrew/formulary.rb:167:in `get_formula'
/usr/local/Library/Homebrew/formulary.rb:207:in `factory'
/usr/local/Library/Homebrew/formulary.rb:226:in `from_rack'
/usr/local/Library/Homebrew/formula.rb:1134:in `block in installed'
/usr/local/Library/Homebrew/formula.rb:1132:in `map'
/usr/local/Library/Homebrew/formula.rb:1132:in `installed'
/usr/local/Library/Homebrew/cleanup.rb:41:in `cleanup_cellar'
/usr/local/Library/Homebrew/cleanup.rb:10:in `cleanup'
/usr/local/Library/Homebrew/cmd/cleanup.rb:7:in `cleanup'
/usr/local/Library/brew.rb:83:in `<main>'
```

**Comment by ilovezfs** [comment]
```
cd /usr/local
git checkout master
git fetch origin
git reset --hard origin/master
```
```
cd /usr/local/Library/Taps/homebrew/homebrew-core
git checkout master
git fetch origin
git reset --hard origin/master
```
```
brew update
```

**Comment by daisuuke** [comment]
thank you! it's solved.

**Comment by ilovezfs** [comment]
You're welcome :)
