### ISSUE TITLE
After upgrade Mac to 10.13.5, cannot upgrade/install some formula

### ISSUE THREAD

**Issue by chenyang1992** [Homebrew/homebrew-core#28647]
**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [x] are reporting a bug others will be able to reproduce and not asking a question. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh
- [x] have a problem with `brew install` (or `upgrade`, `reinstall`) a single, official formula (not cask)? If it's a general `brew` problem please file this issue at Homebrew/brew: https://github.com/Homebrew/brew/issues/new/choose. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/homebrew-cask/issues/new/choose. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [ ] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [ ] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

To help us debug your issue please explain:
- What you were trying to do (and why)
I tried to upgrade cloudfoundry/tap/cf-cli and reinstall scala.
- What happened (include command output)
brew upgrade
brew install scala
- What you expected to happen
- Step-by-step reproduction instructions (by running `brew install` commands)

```
$ brew upgrade
==> Upgrading 1 outdated package, with result:
cloudfoundry/tap/cf-cli 6.36.2 -> 6.37.0
==> Upgrading cloudfoundry/tap/cf-cli 
Error: NaN
Please report this bug:
  https://docs.brew.sh/Troubleshooting
/usr/local/Homebrew/Library/Homebrew/os/mac/xcode.rb:152:in `to_i'
/usr/local/Homebrew/Library/Homebrew/os/mac/xcode.rb:152:in `detect_version_from_clang_version'
/usr/local/Homebrew/Library/Homebrew/os/mac/xcode.rb:144:in `detect_version'
/usr/local/Homebrew/Library/Homebrew/os/mac/xcode.rb:114:in `version'
/usr/local/Homebrew/Library/Homebrew/os/mac/xcode.rb:58:in `without_clt?'
/usr/local/Homebrew/Library/Homebrew/extend/os/mac/extend/ENV/super.rb:27:in `homebrew_extra_paths'
/usr/local/Homebrew/Library/Homebrew/extend/ENV/super.rb:108:in `determine_path'
/usr/local/Homebrew/Library/Homebrew/extend/ENV/super.rb:43:in `setup_build_environment'
/usr/local/Homebrew/Library/Homebrew/extend/os/mac/extend/ENV/super.rb:107:in `setup_build_environment'
/usr/local/Homebrew/Library/Homebrew/build.rb:82:in `install'
/usr/local/Homebrew/Library/Homebrew/build.rb:189:in `<main>'


$ brew install scala
Error: NaN
Please report this bug:
  https://docs.brew.sh/Troubleshooting
/usr/local/Homebrew/Library/Homebrew/os/mac/xcode.rb:152:in `to_i'
/usr/local/Homebrew/Library/Homebrew/os/mac/xcode.rb:152:in `detect_version_from_clang_version'
/usr/local/Homebrew/Library/Homebrew/os/mac/xcode.rb:144:in `detect_version'
/usr/local/Homebrew/Library/Homebrew/os/mac/xcode.rb:114:in `version'
/usr/local/Homebrew/Library/Homebrew/os/mac/xcode.rb:58:in `without_clt?'
/usr/local/Homebrew/Library/Homebrew/extend/os/mac/extend/ENV/super.rb:27:in `homebrew_extra_paths'
/usr/local/Homebrew/Library/Homebrew/extend/ENV/super.rb:108:in `determine_path'
/usr/local/Homebrew/Library/Homebrew/extend/ENV/super.rb:43:in `setup_build_environment'
/usr/local/Homebrew/Library/Homebrew/extend/os/mac/extend/ENV/super.rb:107:in `setup_build_environment'
/usr/local/Homebrew/Library/Homebrew/build.rb:82:in `install'
/usr/local/Homebrew/Library/Homebrew/build.rb:189:in `<main>'


$ brew doctor
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: Unbrewed dylibs were found in /usr/local/lib.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected dylibs:
  /usr/local/lib/libxerces-c-3.1.dylib

Warning: You have unlinked kegs in your Cellar
Leaving kegs unlinked can lead to build-trouble and cause brews that depend on
those kegs to fail to run properly once built. Run `brew link` on these:
  libidn2
  libunistring
  zookeeper


$ brew config
HOMEBREW_VERSION: 1.6.6
ORIGIN: https://github.com/Homebrew/brew
HEAD: e4c02fafdaef5676cf40dd6d16e74976cf54b265
Last commit: 10 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 02bd93ed944780eda88d81313a12ae1b6b97af67
Core tap last commit: 6 hours ago
HOMEBREW_PREFIX: /usr/local
CPU: octa-core 64-bit skylake
Homebrew Ruby: 2.3.3 => /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/bin/ruby
Clang: N/A
Git: 2.17.1 => /usr/local/bin/git
Curl: 7.54.0 => /usr/bin/curl
Java: 1.8.0_151, 1.8.0_144
macOS: 10.13.5-x86_64
Error: NaN
Please report this bug:
  https://docs.brew.sh/Troubleshooting
/usr/local/Homebrew/Library/Homebrew/os/mac/xcode.rb:152:in `to_i'
/usr/local/Homebrew/Library/Homebrew/os/mac/xcode.rb:152:in `detect_version_from_clang_version'
/usr/local/Homebrew/Library/Homebrew/os/mac/xcode.rb:144:in `detect_version'
/usr/local/Homebrew/Library/Homebrew/os/mac/xcode.rb:114:in `version'
/usr/local/Homebrew/Library/Homebrew/extend/os/mac/system_config.rb:37:in `clt'
/usr/local/Homebrew/Library/Homebrew/extend/os/mac/system_config.rb:51:in `dump_verbose_config'
/usr/local/Homebrew/Library/Homebrew/cmd/config.rb:12:in `config'
/usr/local/Homebrew/Library/Homebrew/brew.rb:95:in `<main>'
```

**Comment by DomT4** [comment]
Same issue as https://github.com/Homebrew/brew/issues/4276, so you may want to track that one as well.

**Comment by fxcoudert** [comment]
This issue is due to using Xcode 10 beta, for which brew support has just been merged: https://github.com/Homebrew/brew/issues/4276

Will be fixed with the next brew tag.
