### ISSUE TITLE
Cannot upgrade gradle to 4.8

### ISSUE THREAD

**Issue by HazCod** [Homebrew/homebrew-core#28664]
- What you were trying to do (and why)
Trying to upgrade gradle from 4.7 to 4.8

```
user@hyde:~$ brew update
Already up-to-date.
```

```
user@hyde:~$ brew upgrade gradle
==> Upgrading 1 outdated package, with result:
gradle 4.7 -> 4.8
==> Upgrading gradle
Error: NaN
Please report this bug:
  https://docs.brew.sh/Troubleshooting
/usr/local/Homebrew/Library/Homebrew/os/mac/xcode.rb:152:in `to_i'
/usr/local/Homebrew/Library/Homebrew/os/mac/xcode.rb:152:in `detect_version_from_clang_version'
/usr/local/Homebrew/Library/Homebrew/os/mac/xcode.rb:144:in `detect_version'
/usr/local/Homebrew/Library/Homebrew/os/mac/xcode.rb:114:in `version'
/usr/local/Homebrew/Library/Homebrew/os/mac/xcode.rb:58:in `without_clt?'
/usr/local/Homebrew/Library/Homebrew/extend/os/mac/extend/ENV/super.rb:27:in `homebrew_extra_paths'
/usr/local/Homebrew/Library/Homebrew/extend/ENV/super.rb:108:in `determine_path'
/usr/local/Homebrew/Library/Homebrew/extend/ENV/super.rb:43:in `setup_build_environment'
/usr/local/Homebrew/Library/Homebrew/extend/os/mac/extend/ENV/super.rb:107:in `setup_build_environment'
/usr/local/Homebrew/Library/Homebrew/build.rb:82:in `install'
/usr/local/Homebrew/Library/Homebrew/build.rb:189:in `<main>'
```

```
user@hyde:~$ brew doctor
Your system is ready to brew.
```

**Comment by fxcoudert** [comment]
This issue is due to using Xcode 10 beta, for which brew support has just been merged: https://github.com/Homebrew/brew/issues/4276

Will be fixed with the next brew tag.
