### ISSUE TITLE
python upgrade failing

### ISSUE THREAD

**Issue by swensonator** [Homebrew/homebrew-core#29214]
running "brew update ; brew upgrade" results in the following error when upgrading python from 3.6.5 -> 3.6.5_1

```
[ ~/Code/homebrew/Cellar ] brew reinstall python
==> Reinstalling python
==> Downloading https://www.python.org/ftp/python/3.6.5/Python-3.6.5.tar.xz
Already downloaded: /Volumes/atm0/Users/***/Library/Caches/Homebrew/python-3.6.5.tar.xz
==> ./configure --prefix=/Volumes/atm0/Users/***/Code/homebrew/Cellar/python/3.6.5_1 --enable-ipv6 --datarootdir=/Volumes/atm0/Users/***/Code/homebrew/Cellar/python/3.6.5_1/share --datadir=/
==> make
==> make install PYTHONAPPSDIR=/Volumes/atm0/Users/***/Code/homebrew/Cellar/python/3.6.5_1
==> make frameworkinstallextras PYTHONAPPSDIR=/Volumes/atm0/Users/***/Code/homebrew/Cellar/python/3.6.5_1/share/python
==> Downloading https://files.pythonhosted.org/packages/1a/04/d6f1159feaccdfc508517dba1929eb93a2854de729fa68da9d5c6b48fa00/setuptools-39.2.0.zip
Already downloaded: /Volumes/atm0/Users/***/Library/Caches/Homebrew/python--setuptools-39.2.0.zip
==> Downloading https://files.pythonhosted.org/packages/ae/e8/2340d46ecadb1692a1e455f13f75e596d4eab3d11a57446f08259dee8f02/pip-10.0.1.tar.gz
Already downloaded: /Volumes/atm0/Users/***/Library/Caches/Homebrew/python--pip-10.0.1.tar.gz
==> Downloading https://files.pythonhosted.org/packages/2a/fb/aefe5d5dbc3f4fe1e815bcdb05cbaab19744d201bbc9b59cfa06ec7fc789/wheel-0.31.1.tar.gz
Already downloaded: /Volumes/atm0/Users/***/Library/Caches/Homebrew/python--wheel-0.31.1.tar.gz
==> make html
Error: No such file or directory @ realpath_rec - /Volumes/atm0/Users/***/Code/homebrew/Cellar/python/3.6.5_1/Frameworks/Python.framework/Version
```

If I try to upgrade to python-devel instead, I get a variation on the error:

```
Error: No such file or directory @ realpath_rec - /Volumes/atm0/Users/***/Code/homebrew/Cellar/python/3.7.0rc1_1/Frameworks/Python.framework/Vers
```

The directory it is trying to access is actually named '<prefix>/Frameworks/Python.framework/Versions/', so the 's/' is being dropped in the first error and the 'ions/' is being dropped in the second case. The dropping of characters coincides with the addition of the '_1' to the version in python 3.6.5_1 and the addition of the 'rc1_1' for python 3.7.0rc1_1.

I am not familiar enough with Ruby or with the python formula to determine on what line the error is occurring (other than it happens after the call to 'system "make", "html"').

**Comment by mistydemeo** [comment]
Hm, that's interesting. I'm unable to reproduce myself.

Can you please provide all of the logs requested when you file a new issue, including the output of `brew gist-logs python`? Thanks!

**Comment by swensonator** [comment]
Here is the brew gist-logs:

The brew doctor command has a lot of warnings, mainly because I keep my homebrew in a non-standard directory, but that has never been an issue before (3 years of using homebrew). The remaining warnings towards the end are all a result of my attempts to uninstall and re-install python.

[https://gist.github.com/be7c5379fe90dab27e1ff5a709c59e9d](https://gist.github.com/be7c5379fe90dab27e1ff5a709c59e9d)

**Comment by mistydemeo** [comment]
Can you please try `brew upgrade python --debug`, and show the full output of that? The error message you're showing is getting truncated to fit your terminal - that's actually the reason why you're seeing `Version` instead of `Versions`, not that it's actually cutting off the string.

I wonder if this is related to the fact that you have a case-sensitive file system.

**Comment by swensonator** [comment]
Here is the output of `brew install python --debug`:

```
[caswenso@gs614wisbrae ~ ] brew install python --debug
Updating Homebrew...
==> Auto-updated Homebrew!
Updated 1 tap (homebrew/core).
==> New Formulae
beagle
==> Updated Formulae
beast                    cgrep                    gjstest                  libosinfo                osm-pbf                  protobuf-c               supersonic               wireguard-tools
bluepill                 citus                    gnome-builder            libphonenumber           parallel                 protobuf-swift           upscaledb                wtf
brew-cask-completion     dfix                     grpc                     mosh                     pdftoedn                 pulseaudio               vala                     zbackup
caffe                    flow                     heroku                   node                     protobuf                 quicktype                vault

/Volumes/atm0/Users/caswenso/Code/homebrew/Library/Homebrew/brew.rb (Formulary::FormulaLoader): loading /Volumes/atm0/Users/caswenso/Code/homebrew/Library/Taps/homebrew/homebrew-core/Formula/python.rb
/Volumes/atm0/Users/caswenso/Code/homebrew/Library/Homebrew/brew.rb (Formulary::FormulaLoader): loading /Volumes/atm0/Users/caswenso/Code/homebrew/Library/Taps/homebrew/homebrew-core/Formula/gdbm.rb
/Volumes/atm0/Users/caswenso/Code/homebrew/Library/Homebrew/brew.rb (Formulary::FormulaLoader): loading /Volumes/atm0/Users/caswenso/Code/homebrew/Library/Taps/homebrew/homebrew-core/Formula/openssl.rb
/Volumes/atm0/Users/caswenso/Code/homebrew/Library/Homebrew/brew.rb (Formulary::FormulaLoader): loading /Volumes/atm0/Users/caswenso/Code/homebrew/Library/Taps/homebrew/homebrew-core/Formula/readline.rb
/Volumes/atm0/Users/caswenso/Code/homebrew/Library/Homebrew/brew.rb (Formulary::FormulaLoader): loading /Volumes/atm0/Users/caswenso/Code/homebrew/Library/Taps/homebrew/homebrew-core/Formula/sqlite.rb
/Volumes/atm0/Users/caswenso/Code/homebrew/Library/Homebrew/brew.rb (Formulary::FormulaLoader): loading /Volumes/atm0/Users/caswenso/Code/homebrew/Library/Taps/homebrew/homebrew-core/Formula/xz.rb
/Volumes/atm0/Users/caswenso/Code/homebrew/Library/Homebrew/brew.rb (Formulary::FormulaLoader): loading /Volumes/atm0/Users/caswenso/Code/homebrew/Library/Taps/homebrew/homebrew-core/Formula/pkg-config.rb
/Volumes/atm0/Users/caswenso/Code/homebrew/Library/Homebrew/brew.rb (Formulary::FormulaLoader): loading /Volumes/atm0/Users/caswenso/Code/homebrew/Library/Taps/homebrew/homebrew-core/Formula/sphinx-doc.rb
/Volumes/atm0/Users/caswenso/Code/homebrew/Library/Homebrew/brew.rb (Formulary::FormulaLoader): loading /Volumes/atm0/Users/caswenso/Code/homebrew/Library/Taps/homebrew/homebrew-core/Formula/makedepend.rb
/Volumes/atm0/Users/caswenso/Code/homebrew/Library/Homebrew/build.rb (Formulary::FromPathLoader): loading /Volumes/atm0/Users/caswenso/Code/homebrew/Library/Taps/homebrew/homebrew-core/Formula/python.rb
/Volumes/atm0/Users/caswenso/Code/homebrew/Library/Homebrew/build.rb (Formulary::FormulaLoader): loading /Volumes/atm0/Users/caswenso/Code/homebrew/Library/Taps/homebrew/homebrew-core/Formula/gdbm.rb
/Volumes/atm0/Users/caswenso/Code/homebrew/Library/Homebrew/build.rb (Formulary::FormulaLoader): loading /Volumes/atm0/Users/caswenso/Code/homebrew/Library/Taps/homebrew/homebrew-core/Formula/openssl.rb
/Volumes/atm0/Users/caswenso/Code/homebrew/Library/Homebrew/build.rb (Formulary::FormulaLoader): loading /Volumes/atm0/Users/caswenso/Code/homebrew/Library/Taps/homebrew/homebrew-core/Formula/readline.rb
/Volumes/atm0/Users/caswenso/Code/homebrew/Library/Homebrew/build.rb (Formulary::FormulaLoader): loading /Volumes/atm0/Users/caswenso/Code/homebrew/Library/Taps/homebrew/homebrew-core/Formula/sqlite.rb
/Volumes/atm0/Users/caswenso/Code/homebrew/Library/Homebrew/build.rb (Formulary::FormulaLoader): loading /Volumes/atm0/Users/caswenso/Code/homebrew/Library/Taps/homebrew/homebrew-core/Formula/xz.rb
/Volumes/atm0/Users/caswenso/Code/homebrew/Library/Homebrew/build.rb (Formulary::FormulaLoader): loading /Volumes/atm0/Users/caswenso/Code/homebrew/Library/Taps/homebrew/homebrew-core/Formula/pkg-config.rb
/Volumes/atm0/Users/caswenso/Code/homebrew/Library/Homebrew/build.rb (Formulary::FormulaLoader): loading /Volumes/atm0/Users/caswenso/Code/homebrew/Library/Taps/homebrew/homebrew-core/Formula/sphinx-doc.rb
/Volumes/atm0/Users/caswenso/Code/homebrew/Library/Homebrew/build.rb (Formulary::FormulaLoader): loading /Volumes/atm0/Users/caswenso/Code/homebrew/Library/Taps/homebrew/homebrew-core/Formula/makedepend.rb
==> Downloading https://www.python.org/ftp/python/3.6.5/Python-3.6.5.tar.xz
Already downloaded: /Volumes/atm0/Users/caswenso/Library/Caches/Homebrew/python-3.6.5.tar.xz
==> ./configure --prefix=/Volumes/atm0/Users/caswenso/Code/homebrew/Cellar/python/3.6.5_1 --enable-ipv6 --datarootdir=/Volumes/atm0/Users/caswenso/Code/homebrew/Cellar/python/3.6.5_1/share --datadir=/
==> make
==> make install PYTHONAPPSDIR=/Volumes/atm0/Users/caswenso/Code/homebrew/Cellar/python/3.6.5_1
==> make frameworkinstallextras PYTHONAPPSDIR=/Volumes/atm0/Users/caswenso/Code/homebrew/Cellar/python/3.6.5_1/share/python
==> Downloading https://files.pythonhosted.org/packages/1a/04/d6f1159feaccdfc508517dba1929eb93a2854de729fa68da9d5c6b48fa00/setuptools-39.2.0.zip
Already downloaded: /Volumes/atm0/Users/caswenso/Library/Caches/Homebrew/python--setuptools-39.2.0.zip
==> Downloading https://files.pythonhosted.org/packages/ae/e8/2340d46ecadb1692a1e455f13f75e596d4eab3d11a57446f08259dee8f02/pip-10.0.1.tar.gz
Already downloaded: /Volumes/atm0/Users/caswenso/Library/Caches/Homebrew/python--pip-10.0.1.tar.gz
==> Downloading https://files.pythonhosted.org/packages/2a/fb/aefe5d5dbc3f4fe1e815bcdb05cbaab19744d201bbc9b59cfa06ec7fc789/wheel-0.31.1.tar.gz
Already downloaded: /Volumes/atm0/Users/caswenso/Library/Caches/Homebrew/python--wheel-0.31.1.tar.gz
==> make html
/Volumes/atm0/Users/caswenso/Code/homebrew/Library/Taps/homebrew/homebrew-core/Formula/python.rb:219:in `realpath'
Errno::ENOENT: No such file or directory @ realpath_rec - /Volumes/atm0/Users/caswenso/Code/homebrew/Cellar/python/3.6.5_1/Frameworks/Python.framework/Version
1. raise
2. backtrace
3. shell
Choose an action: 2
/Volumes/atm0/Users/caswenso/Code/homebrew/Library/Taps/homebrew/homebrew-core/Formula/python.rb:219:in `realpath'
/Volumes/atm0/Users/caswenso/Code/homebrew/Library/Taps/homebrew/homebrew-core/Formula/python.rb:219:in `realpath'
/Volumes/atm0/Users/caswenso/Code/homebrew/Library/Taps/homebrew/homebrew-core/Formula/python.rb:219:in `block in install'
/Volumes/atm0/Users/caswenso/Code/homebrew/Library/Taps/homebrew/homebrew-core/Formula/python.rb:218:in `each'
/Volumes/atm0/Users/caswenso/Code/homebrew/Library/Taps/homebrew/homebrew-core/Formula/python.rb:218:in `install'
/Volumes/atm0/Users/caswenso/Code/homebrew/Library/Homebrew/debrew.rb:22:in `block in install'
/Volumes/atm0/Users/caswenso/Code/homebrew/Library/Homebrew/debrew.rb:92:in `debrew'
/Volumes/atm0/Users/caswenso/Code/homebrew/Library/Homebrew/debrew.rb:22:in `install'
/Volumes/atm0/Users/caswenso/Code/homebrew/Library/Homebrew/build.rb:142:in `block (2 levels) in install'
/Volumes/atm0/Users/caswenso/Code/homebrew/Library/Homebrew/formula.rb:1116:in `block in brew'
/Volumes/atm0/Users/caswenso/Code/homebrew/Library/Homebrew/formula.rb:1957:in `block (2 levels) in stage'
/Volumes/atm0/Users/caswenso/Code/homebrew/Library/Homebrew/utils.rb:556:in `with_env'
/Volumes/atm0/Users/caswenso/Code/homebrew/Library/Homebrew/formula.rb:1956:in `block in stage'
/Volumes/atm0/Users/caswenso/Code/homebrew/Library/Homebrew/resource.rb:119:in `block in unpack'
/Volumes/atm0/Users/caswenso/Code/homebrew/Library/Homebrew/extend/fileutils.rb:13:in `block in mktemp'
/Volumes/atm0/Users/caswenso/Code/homebrew/Library/Homebrew/extend/fileutils.rb:73:in `block in run'
/Volumes/atm0/Users/caswenso/Code/homebrew/Library/Homebrew/extend/fileutils.rb:73:in `chdir'
/Volumes/atm0/Users/caswenso/Code/homebrew/Library/Homebrew/extend/fileutils.rb:73:in `run'
/Volumes/atm0/Users/caswenso/Code/homebrew/Library/Homebrew/extend/fileutils.rb:12:in `mktemp'
/Volumes/atm0/Users/caswenso/Code/homebrew/Library/Homebrew/resource.rb:114:in `unpack'
/Volumes/atm0/Users/caswenso/Code/homebrew/Library/Homebrew/resource.rb:92:in `stage'
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/forwardable.rb:189:in `stage'
/Volumes/atm0/Users/caswenso/Code/homebrew/Library/Homebrew/formula.rb:1934:in `stage'
/Volumes/atm0/Users/caswenso/Code/homebrew/Library/Homebrew/formula.rb:1111:in `brew'
/Volumes/atm0/Users/caswenso/Code/homebrew/Library/Homebrew/build.rb:113:in `block in install'
/Volumes/atm0/Users/caswenso/Code/homebrew/Library/Homebrew/utils.rb:556:in `with_env'
/Volumes/atm0/Users/caswenso/Code/homebrew/Library/Homebrew/build.rb:110:in `install'
/Volumes/atm0/Users/caswenso/Code/homebrew/Library/Homebrew/build.rb:191:in `<main>'
```

The file system has been case-sensitive for as long as I have been using homebrew and it has never caused any problems. I have upgraded python@3 through several minor versions without any problem. Did something change in the python formula recently that would be causing these problems?

**Comment by chdiza** [comment]
> These days you have to really go out of your way to choose a case-insensitive OS.

You really have to go out of your way to choose macOS?

**Comment by swensonator** [comment]
Ah, that's right, the default is case-insensitive for HFS+ filesystem. I forgot. I work in a mixed OS work environment, so all of our macOS installs are set to case-sensitive so they can share network shares with *nix and Windows systems.

**Comment by Flimm** [comment]
For the record, Windows also handles file paths in a case-insensitive manner (even though the filesystem NTFS can be used case-sensitively).
