### ISSUE TITLE
unable to build/install mpv - generator raised StopIteration

### ISSUE THREAD

**Issue by globau** [Homebrew/homebrew-core#29619]
- [X] are reporting a bug others will be able to reproduce and not asking a question
- [X] have a problem with `brew install` (or `upgrade`, `reinstall`) a single, official formula
- [X] ran `brew update` and can still reproduce the problem?
- [X] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [X] ran `brew gist-logs <formula>`
- [x] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

trying to install `mpv` with custom options results in `RuntimeError: generator raised StopIteration`.

```
glob ~$ brew reinstall mpv
==> Reinstalling mpv --with-bundle --with-libaacs --with-libarchive --with-libbluray --with-libcaca --with-libdvdnav --with-libdvdread --with-uchardet --with-vapoursynth
==> Downloading https://github.com/mpv-player/mpv/archive/v0.28.2.tar.gz
Already downloaded: /Users/byron/Library/Caches/Homebrew/mpv-0.28.2.tar.gz
==> Downloading https://files.pythonhosted.org/packages/05/25/7b5484aca5d46915493f1fd4ecb63c38c333bd32aa9ad6e19da8d08895ae/docutils-0.13.1.tar.gz
Already downloaded: /Users/byron/Library/Caches/Homebrew/mpv--docutils-0.13.1.tar.gz
==> python2.7 -c import setuptools... --no-user-cfg install --prefix=/private/tmp/mpv-20180702-15427-288kiz/mpv-0.28.2/vendor --single-version-externally-managed --record=installed.
==> ./bootstrap.py
==> python3 waf configure --prefix=/usr/local/Cellar/mpv/0.28.2 --enable-libmpv-shared --enable-html-build --enable-lua --confdir=/usr/local/etc/mpv --datadir=/usr/local/Cellar/mpv/
Last 15 lines from /Users/byron/Library/Logs/Homebrew/mpv/03.python3:
  File "/private/tmp/mpv-20180702-15427-288kiz/mpv-0.28.2/.waf3-1.9.8-17756245c4cc550633dacf3b08eec42a/waflib/Context.py", line 129, in recurse
    user_function(self)
  File "/private/tmp/mpv-20180702-15427-288kiz/mpv-0.28.2/wscript", line 939, in options
    opt.load('compiler_c')
  File "/private/tmp/mpv-20180702-15427-288kiz/mpv-0.28.2/.waf3-1.9.8-17756245c4cc550633dacf3b08eec42a/waflib/Context.py", line 85, in load
    fun(self)
  File "/private/tmp/mpv-20180702-15427-288kiz/mpv-0.28.2/.waf3-1.9.8-17756245c4cc550633dacf3b08eec42a/waflib/Tools/compiler_c.py", line 40, in options
    opt.load_special_tools('c_*.py',ban=['c_dumbpreproc.py'])
  File "/private/tmp/mpv-20180702-15427-288kiz/mpv-0.28.2/.waf3-1.9.8-17756245c4cc550633dacf3b08eec42a/waflib/Context.py", line 319, in load_special_tools
    lst=self.root.find_node(waf_dir).find_node('waflib/extras').ant_glob(var)
  File "/private/tmp/mpv-20180702-15427-288kiz/mpv-0.28.2/.waf3-1.9.8-17756245c4cc550633dacf3b08eec42a/waflib/Node.py", line 344, in ant_glob
    ret=[x for x in self.ant_iter(accept=accept,pats=[to_pat(incl),to_pat(excl)],maxdepth=kw.get('maxdepth',25),dir=dir,src=src,remove=kw.get('remove',True))]
  File "/private/tmp/mpv-20180702-15427-288kiz/mpv-0.28.2/.waf3-1.9.8-17756245c4cc550633dacf3b08eec42a/waflib/Node.py", line 344, in <listcomp>
    ret=[x for x in self.ant_iter(accept=accept,pats=[to_pat(incl),to_pat(excl)],maxdepth=kw.get('maxdepth',25),dir=dir,src=src,remove=kw.get('remove',True))]
RuntimeError: generator raised StopIteration
```

unfortunately `brew gist-logs` failed:
```
glob ~$ brew gist-logs mpv
Error: source sequence is illegal/malformed utf-8
Please report this bug:
  https://docs.brew.sh/Troubleshooting
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3_2/lib/ruby/2.3.0/json/common.rb:224:in `generate'
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3_2/lib/ruby/2.3.0/json/common.rb:224:in `generate'
/usr/local/Homebrew/Library/Homebrew/utils/github.rb:148:in `open_api'
/usr/local/Homebrew/Library/Homebrew/cmd/gist-logs.rb:116:in `create_gist'
/usr/local/Homebrew/Library/Homebrew/cmd/gist-logs.rb:58:in `gistify_logs'
/usr/local/Homebrew/Library/Homebrew/cmd/gist-logs.rb:129:in `gist_logs'
/usr/local/Homebrew/Library/Homebrew/brew.rb:99:in `<main>'
glob ~$ brew config
HOMEBREW_VERSION: 1.6.9
ORIGIN: https://github.com/Homebrew/brew.git
HEAD: c814199a791867ab75f90a22715e2475706b13d8
Last commit: 13 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: a501ea67ab62f8a58a6565d720952e4f5fe83854
Core tap last commit: 6 minutes ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_GITHUB_API_TOKEN: set
HOMEBREW_NO_ANALYTICS: 1
CPU: quad-core 64-bit haswell
Homebrew Ruby: 2.3.3 => /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3_2/bin/ruby
Clang: 9.1 build 902
Git: 2.18.0 => /usr/local/bin/git
Curl: 7.54.0 => /usr/bin/curl
Java: 1.8.0_31
macOS: 10.13.5-x86_64
CLT: 10.0.0.0.1.1527767617
Xcode: 9.4.1
XQuartz: N/A
glob ~$ brew doctor
Your system is ready to brew.
```

i've run `brew reinstall` with `--verbose`; output is at https://gist.github.com/globau/c6ce68c81a7912a98613d9b0821cefa5

it appears the problem is brew recently upgraded python 3 to 3.7.0, which no longer supports generators raising `StopIteration`.  `waf` is generating this error.

`bootstrap.py` downloads waf version 1.9.8; according to https://gitlab.com/ita1024/waf/blob/master/ChangeLog you need to use version 2.0.7 or later.

**Comment by globau** [comment]
filed https://github.com/mpv-player/mpv/issues/5958

**Comment by globau** [comment]
fwiw i was able to build mpv by using python 2.7 with waf-1.9.8 instead of python 3.

**Comment by ilovezfs** [comment]
I've switched it to python2. Thanks for reporting @globau
