### ISSUE TITLE
Unable to update Ruby

### ISSUE THREAD

**Issue by tjg37** [Homebrew/homebrew-core#31327]
- [X] are reporting a bug others will be able to reproduce and not asking a question. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh
- [X] have a problem with `brew install` (or `upgrade`, `reinstall`) a single, official formula (not cask)? If it's a general `brew` problem please file this issue at Homebrew/brew: https://github.com/Homebrew/brew/issues/new/choose. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/homebrew-cask/issues/new/choose. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [X] ran `brew update` and can still reproduce the problem? Ran Twice as directed. 
- [X] ran `brew doctor`, fixed all issues and can still reproduce the problem? Ran `brew doctor` but it threw an error. 
- [ ] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [X] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

To help us debug your issue please explain:
- What you were trying to do (and why)

I am trying to update the version of Ruby on my mac, but I think that the configuration of Ruby is not correct on my computer and the errors suggested that I should `Please report this bug`.

- What happened (include command output)

1) When I tried to update ruby using the following command ` \curl -sSL https://get.rvm.io | bash -s stable --ruby`, I received the following output: 

```
Downloading https://github.com/rvm/rvm/archive/1.29.4.tar.gz
Downloading https://github.com/rvm/rvm/releases/download/1.29.4/1.29.4.tar.gz.asc
Found PGP signature at: 'https://github.com/rvm/rvm/releases/download/1.29.4/1.29.4.tar.gz.asc',
but no GPG software exists to validate it, skipping.
Upgrading the RVM installation in /Users/tejogol/.rvm/
    RVM PATH line found in /Users/tejogol/.mkshrc /Users/tejogol/.profile /Users/tejogol/.bashrc /Users/tejogol/.zshrc.
    RVM sourcing line found in /Users/tejogol/.profile /Users/tejogol/.bash_profile /Users/tejogol/.zlogin.
    Fixing environment link for default.
Upgrade of RVM in /Users/tejogol/.rvm/ is complete.
  * No new notes to display.

Ruby enVironment Manager 1.29.4 (latest) (c) 2009-2017 Michal Papis, Piotr Kuczynski, Wayne E. Seguin

Searching for binary rubies, this might take some time.
No binary rubies available for: osx/10.12/x86_64/ruby-2.5.1.
Continuing with compilation. Please read 'rvm help mount' to get more information on binary rubies.
Checking requirements for osx.
Installing requirements for osx.
Updating system..........
Installing required packages: automake, libtool, coreutils, libyaml, readline, openssl@1.1...There were package installation errors, make sure to read the log.

Try `brew tap --repair` and make sure `brew doctor` looks reasonable.
/
Check Homebrew requirements https://github.com/Homebrew/homebrew/wiki/Installation
.
Error running 'requirements_osx_brew_libs_install automake libtool coreutils libyaml readline openssl@1.1',
please read /Users/tejogol/.rvm/log/1534879581_ruby-2.5.1/package_install_automake_libtool_coreutils_libyaml_readline_openssl@1.1.log
Requirements installation failed with status: 1.
Required ruby-2.5.1 is not installed.
Creating alias default for ruby-2.5.1.....

  * To start using RVM you need to run `source /Users/tejogol/.rvm/scripts/rvm`
    in all your open shell windows, in rare cases you need to reopen all shell windows.
```
2) Following the instructions, I then performed `brew tap --repair` which completed successfully and gave no output. 

3) I then performed `brew doctor` and got the following output:

```
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry and just ignore them. Thanks!

Warning: python is symlinked to python3
This will confuse build scripts and in general lead to subtle breakage.

Warning: "config" scripts exist outside your system or Homebrew directories.
`./configure` scripts often look for *-config scripts to determine if
software packages are installed, and what additional flags to use when
compiling and linking.

Having additional scripts in your path can confuse software installed via
Homebrew if the config script overrides a system or Homebrew provided
script of the same name. We found the following "config" scripts:
  /Users/tejogol/miniconda3/bin/python3-config
  /Users/tejogol/miniconda3/bin/python3.6-config
  /Users/tejogol/miniconda3/bin/python3.6m-config
  /Users/tejogol/miniconda2/bin/python-config
  /Users/tejogol/miniconda2/bin/python2-config
  /Users/tejogol/miniconda2/bin/python2.7-config
Error: /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/coreutils.rb:73: syntax error, unexpected <<
  def caveats; <<~EOS
                 ^
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/coreutils.rb:77: syntax error, unexpected tIDENTIFIER, expecting keyword_end
    can add a "gnubin" directory to your PATH from your bashrc like:
                                ^
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/coreutils.rb:77: syntax error, unexpected ':', expecting keyword_end
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/coreutils.rb:79: dynamic constant assignment
        PATH="#{opt_libexec}/gnubin:$PATH"
             ^
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/coreutils.rb:81: dynamic constant assignment
    Additionally, you can access their man pag...
                 ^
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/coreutils.rb:81: syntax error, unexpected tIDENTIFIER, expecting keyword_do or '{' or '('
    Additionally, you can access their man pages with ...
                         ^
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/coreutils.rb:82: syntax error, unexpected tIDENTIFIER, expecting keyword_end
    the "gnuman" directory to your MANPATH from your bashrc as well:
                          ^
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/coreutils.rb:82: syntax error, unexpected ':', expecting keyword_end
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/coreutils.rb:84: dynamic constant assignment
        MANPATH="#{opt_libexec}/gnuman:$MANPATH"
                ^
Please report this bug:
  https://git.io/brew-troubleshooting
/usr/local/Homebrew/Library/Homebrew/formulary.rb:25:in `module_eval'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:25:in `load_formula'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:42:in `load_formula_from_path'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:97:in `load_file'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:88:in `klass'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:84:in `get_formula'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:222:in `factory'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1411:in `[]'
/usr/local/Homebrew/Library/Homebrew/diagnostic.rb:944:in `check_for_non_prefixed_coreutils'
/usr/local/Homebrew/Library/Homebrew/cmd/doctor.rb:43:in `block in doctor'
/usr/local/Homebrew/Library/Homebrew/cmd/doctor.rb:35:in `each'
/usr/local/Homebrew/Library/Homebrew/cmd/doctor.rb:35:in `doctor'
/usr/local/Homebrew/Library/Homebrew/brew.rb:94:in `<main>'
```
4) I then tried `brew update` and got the following output: `Already up-to-date.`.

5) When trying `brew upgrade` I got the following error:

```
Warning: You are using a pre-release version of Xcode.
You may encounter build failures or other breakages.
Please create pull-requests instead of filing issues.
Error: /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/automake.rb:36: unknown regexp options - har
Please report this bug:
  https://git.io/brew-troubleshooting
/usr/local/Homebrew/Library/Homebrew/formulary.rb:25:in `module_eval'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:25:in `load_formula'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:42:in `load_formula_from_path'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:97:in `load_file'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:88:in `klass'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:84:in `get_formula'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:222:in `factory'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:250:in `from_keg'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:236:in `from_rack'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1357:in `block in installed'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1355:in `map'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1355:in `installed'
/usr/local/Homebrew/Library/Homebrew/cmd/upgrade.rb:37:in `upgrade'
/usr/local/Homebrew/Library/Homebrew/brew.rb:94:in `<main>'
```

6) Tried to install Ruby again  using `\curl -sSL https://get.rvm.io | bash -s stable --ruby` but ran into the same issue as in 1).

The output from `brew config` is:

```
HOMEBREW_VERSION: >1.0.0 (no git repository)
ORIGIN: https://github.com/Homebrew/brew
HEAD: a63b58ea3d8c59befa48750feb293ce4756747b7
Last commit: never
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 5ffba742307f7c24e85c0789f3d63e46e03190dd
Core tap last commit: 3 hours ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_REPOSITORY: /usr/local/Homebrew
HOMEBREW_CELLAR: /usr/local/Cellar
HOMEBREW_BOTTLE_DOMAIN: https://homebrew.bintray.com
CPU: quad-core 64-bit broadwell
Homebrew Ruby: 2.0.0-p648
Clang: 9.0 build 900
Git: 2.14.3 => /Library/Developer/CommandLineTools/usr/bin/git
Perl: /usr/bin/perl
Python: /Users/tejogol/miniconda3/bin/python => /Users/tejogol/miniconda3/bin/python3.6
Ruby: /Users/tejogol/.rvm/rubies/ruby-2.2.1/bin/ruby
Java: 1.8.0_60
macOS: 10.12.6-x86_64
Xcode: 9.2
CLT: 9.2.0.0.1.1510905681
X11: N/A
MacPorts/Fink: /opt/local/bin/port
```

- What you expected to happen

I expected Ruby to be updated without any issue. 

- Step-by-step reproduction instructions (by running `brew install` commands)

In addition to what's been outlined above if I run `brew install ruby`, I get the following error:

```
Error: /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/ruby.rb:128: syntax error, unexpected <<, expecting keyword_end
  def rubygems_config(api_version); <<~EOS
                                      ^
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/ruby.rb:129: module definition in method body
Please report this bug:
  https://git.io/brew-troubleshooting
/usr/local/Homebrew/Library/Homebrew/formulary.rb:25:in `module_eval'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:25:in `load_formula'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:42:in `load_formula_from_path'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:97:in `load_file'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:88:in `klass'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:84:in `get_formula'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:222:in `factory'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:387:in `find_with_priority'
/usr/local/Homebrew/Library/Homebrew/extend/ARGV.rb:20:in `block in formulae'
/usr/local/Homebrew/Library/Homebrew/extend/ARGV.rb:16:in `map'
/usr/local/Homebrew/Library/Homebrew/extend/ARGV.rb:16:in `formulae'
/usr/local/Homebrew/Library/Homebrew/cmd/install.rb:107:in `install'
/usr/local/Homebrew/Library/Homebrew/brew.rb:94:in `<main>'
```

**Comment by DomT4** [comment]
```
HOMEBREW_VERSION: >1.0.0 (no git repository)
ORIGIN: https://github.com/Homebrew/brew
HEAD: a63b58ea3d8c59befa48750feb293ce4756747b7
Last commit: never
```

That's your problem. What's the output of `git -C $(brew --repo) status` and `git -C $(brew --repo) remote -v`?

**Comment by tjg37** [comment]
Thanks for the quick response! 

The output from `git -C $(brew --repo) status` is: 

```
fatal: bad object HEAD
```

and the output from `git -C $(brew --repo) remote -v` is:

```
origin	https://github.com/Homebrew/brew (fetch)
origin	https://github.com/Homebrew/brew (push)
```

What can I do to fix?

**Comment by SMillerDev** [comment]
Can you try running `git -C $(brew --repo) update-ref HEAD origin/master`?

**Comment by tjg37** [comment]
Tried running `git -C $(brew --repo) update-ref HEAD origin/master` and received no output. 

`brew config` still gives the following output:

```
HOMEBREW_VERSION: >1.0.0 (no git repository)
ORIGIN: https://github.com/Homebrew/brew
HEAD: a63b58ea3d8c59befa48750feb293ce4756747b7
Last commit: never
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 3b2b5110e1aa5e00865edb180113ae84ff81a8e1
Core tap last commit: 71 minutes ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_REPOSITORY: /usr/local/Homebrew
HOMEBREW_CELLAR: /usr/local/Cellar
HOMEBREW_BOTTLE_DOMAIN: https://homebrew.bintray.com
CPU: quad-core 64-bit broadwell
Homebrew Ruby: 2.0.0-p648
Clang: 9.0 build 900
Git: 2.14.3 => /Library/Developer/CommandLineTools/usr/bin/git
Perl: /usr/bin/perl
Python: /Users/tejogol/miniconda3/bin/python => /Users/tejogol/miniconda3/bin/python3.6
Ruby: /usr/bin/ruby => /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin/ruby
Java: 1.8.0_60
macOS: 10.12.6-x86_64
Xcode: 9.2
CLT: 9.2.0.0.1.1510905681
X11: N/A
MacPorts/Fink: /opt/local/bin/port
```

The output from `git -C $(brew --repo) status` is still:

```
fatal: bad object HEAD
```

**Comment by SMillerDev** [comment]
your brew seems to be at a version that predates brew as we know it today (
https://github.com/Homebrew/legacy-homebrew/commit/a63b58ea3d8c59befa48750feb293ce4756747b7). @MikeMcQuaid got any advice on this situation?

**Comment by DomT4** [comment]
@tjg37 Any luck if you run the classic _"Everything is broken"_ command?

```
cd $(brew --repo) && git fetch && git reset --hard origin/master
```

**Comment by tjg37** [comment]
@DomT4 No luck unfortunately. 

Running the command `cd $(brew --repo) && git fetch && git reset --hard origin/master` gives me the following output:

```
error: refs/heads/master does not point to a valid object!
error: refs/remotes/origin/master does not point to a valid object!
error: refs/heads/master does not point to a valid object!
error: refs/remotes/origin/master does not point to a valid object!
error: refs/heads/master does not point to a valid object!
error: refs/remotes/origin/master does not point to a valid object!
error: refs/heads/master does not point to a valid object!
error: refs/remotes/origin/master does not point to a valid object!
error: Could not read 893c80d3ba4aaacba640a7b3a8234e755721ad3f
error: Could not read 954445634cdd6138c589ce9f91a9398d93c8bba8
remote: Counting objects: 36446, done.
remote: Compressing objects: 100% (8847/8847), done.
remote: Total 36446 (delta 27781), reused 35276 (delta 26801), pack-reused 0
Receiving objects: 100% (36446/36446), 6.14 MiB | 3.14 MiB/s, done.
Resolving deltas: 100% (27781/27781), completed with 442 local objects.
error: refs/heads/master does not point to a valid object!
error: refs/remotes/origin/master does not point to a valid object!
fatal: bad object HEAD
error: https://github.com/Homebrew/brew did not send all necessary objects
```

**Comment by DomT4** [comment]
@tjg37 Let's try nuking `git` there then and see what happens:

```
cd $(brew --repo) && rm -rf .git && git init && git remote add origin https://github.com/Homebrew/brew.git && git fetch --all && git reset --hard origin/master
```

**Comment by tjg37** [comment]
@DomT4 That seemed to give a better result. I'm going to try again with the ruby update. Thanks for all your help so far. 

```
Initialized empty Git repository in /usr/local/Homebrew/.git/
Fetching origin
remote: Counting objects: 107851, done.
remote: Compressing objects: 100% (7/7), done.
remote: Total 107851 (delta 0), reused 2 (delta 0), pack-reused 107844
Receiving objects: 100% (107851/107851), 24.41 MiB | 2.65 MiB/s, done.
Resolving deltas: 100% (78825/78825), done.
From https://github.com/Homebrew/brew
 * [new branch]          master     -> origin/master
 * [new tag]             0.1        -> 0.1
 * [new tag]             0.2        -> 0.2
 * [new tag]             0.3        -> 0.3
 * [new tag]             0.4        -> 0.4
 * [new tag]             0.5        -> 0.5
 * [new tag]             0.6        -> 0.6
 * [new tag]             0.7        -> 0.7
 * [new tag]             0.7.1      -> 0.7.1
 * [new tag]             0.8        -> 0.8
 * [new tag]             0.8.1      -> 0.8.1
 * [new tag]             0.9        -> 0.9
 * [new tag]             0.9.1      -> 0.9.1
 * [new tag]             0.9.2      -> 0.9.2
 * [new tag]             0.9.3      -> 0.9.3
 * [new tag]             0.9.4      -> 0.9.4
 * [new tag]             0.9.5      -> 0.9.5
 * [new tag]             0.9.8      -> 0.9.8
 * [new tag]             0.9.9      -> 0.9.9
 * [new tag]             1.0.0      -> 1.0.0
 * [new tag]             1.0.1      -> 1.0.1
 * [new tag]             1.0.2      -> 1.0.2
 * [new tag]             1.0.3      -> 1.0.3
 * [new tag]             1.0.4      -> 1.0.4
 * [new tag]             1.0.5      -> 1.0.5
 * [new tag]             1.0.6      -> 1.0.6
 * [new tag]             1.0.7      -> 1.0.7
 * [new tag]             1.0.8      -> 1.0.8
 * [new tag]             1.0.9      -> 1.0.9
 * [new tag]             1.1.0      -> 1.1.0
 * [new tag]             1.1.1      -> 1.1.1
 * [new tag]             1.1.10     -> 1.1.10
 * [new tag]             1.1.11     -> 1.1.11
 * [new tag]             1.1.12     -> 1.1.12
 * [new tag]             1.1.13     -> 1.1.13
 * [new tag]             1.1.2      -> 1.1.2
 * [new tag]             1.1.3      -> 1.1.3
 * [new tag]             1.1.4      -> 1.1.4
 * [new tag]             1.1.5      -> 1.1.5
 * [new tag]             1.1.6      -> 1.1.6
 * [new tag]             1.1.7      -> 1.1.7
 * [new tag]             1.1.8      -> 1.1.8
 * [new tag]             1.1.9      -> 1.1.9
 * [new tag]             1.2.0      -> 1.2.0
 * [new tag]             1.2.1      -> 1.2.1
 * [new tag]             1.2.2      -> 1.2.2
 * [new tag]             1.2.3      -> 1.2.3
 * [new tag]             1.2.4      -> 1.2.4
 * [new tag]             1.2.5      -> 1.2.5
 * [new tag]             1.2.6      -> 1.2.6
 * [new tag]             1.3.0      -> 1.3.0
 * [new tag]             1.3.1      -> 1.3.1
 * [new tag]             1.3.2      -> 1.3.2
 * [new tag]             1.3.3      -> 1.3.3
 * [new tag]             1.3.4      -> 1.3.4
 * [new tag]             1.3.5      -> 1.3.5
 * [new tag]             1.3.6      -> 1.3.6
 * [new tag]             1.3.7      -> 1.3.7
 * [new tag]             1.3.8      -> 1.3.8
 * [new tag]             1.3.9      -> 1.3.9
 * [new tag]             1.4.0      -> 1.4.0
 * [new tag]             1.4.1      -> 1.4.1
 * [new tag]             1.4.2      -> 1.4.2
 * [new tag]             1.4.3      -> 1.4.3
 * [new tag]             1.5.0      -> 1.5.0
 * [new tag]             1.5.1      -> 1.5.1
 * [new tag]             1.5.10     -> 1.5.10
 * [new tag]             1.5.11     -> 1.5.11
 * [new tag]             1.5.12     -> 1.5.12
 * [new tag]             1.5.13     -> 1.5.13
 * [new tag]             1.5.14     -> 1.5.14
 * [new tag]             1.5.2      -> 1.5.2
 * [new tag]             1.5.3      -> 1.5.3
 * [new tag]             1.5.4      -> 1.5.4
 * [new tag]             1.5.5      -> 1.5.5
 * [new tag]             1.5.6      -> 1.5.6
 * [new tag]             1.5.7      -> 1.5.7
 * [new tag]             1.5.8      -> 1.5.8
 * [new tag]             1.5.9      -> 1.5.9
 * [new tag]             1.6.0      -> 1.6.0
 * [new tag]             1.6.1      -> 1.6.1
 * [new tag]             1.6.10     -> 1.6.10
 * [new tag]             1.6.11     -> 1.6.11
 * [new tag]             1.6.12     -> 1.6.12
 * [new tag]             1.6.13     -> 1.6.13
 * [new tag]             1.6.14     -> 1.6.14
 * [new tag]             1.6.15     -> 1.6.15
 * [new tag]             1.6.16     -> 1.6.16
 * [new tag]             1.6.17     -> 1.6.17
 * [new tag]             1.6.2      -> 1.6.2
 * [new tag]             1.6.3      -> 1.6.3
 * [new tag]             1.6.4      -> 1.6.4
 * [new tag]             1.6.5      -> 1.6.5
 * [new tag]             1.6.6      -> 1.6.6
 * [new tag]             1.6.7      -> 1.6.7
 * [new tag]             1.6.8      -> 1.6.8
 * [new tag]             1.6.9      -> 1.6.9
 * [new tag]             1.7.0      -> 1.7.0
 * [new tag]             1.7.1      -> 1.7.1
 * [new tag]             1.7.2      -> 1.7.2
HEAD is now at 1c7c876f3 Merge pull request #4736 from scpeters/bottle_json_local_filename
```

**Comment by tjg37** [comment]
@DomT4 It looks like it fixed the issue. I was able to get brew working again and upgrade Ruby. 

Thanks so much for your help!

**Comment by DomT4** [comment]
@tjg37 Great! Glad things seem to be working as-expected again. Let us know if you need any further help with anything, but closing here as resolved 🎉.
