### ISSUE TITLE
"brew install nvm" fail,turn out "Error: Version value must be a string; got a NilClass ()"

### ISSUE THREAD

**Issue by shaoxueqian** [Homebrew/homebrew-core#3142]
"brew install nvm" fail,turn out "Error: Version value must be a string; got a NilClass ()"

**Comment by ilovezfs** [comment]
Sorry but you have not followed the requested steps on the Troubleshooting page: https://github.com/Homebrew/brew/blob/master/share/doc/homebrew/Troubleshooting.md

Please follow (all of) these steps and post the information here so we can help you with your problem.

Thanks!

For what it's worth, I cannot reproduce this issue.

**Comment by mistydemeo** [comment]
Ping?

**Comment by ilovezfs** [comment]
@shaoxueqian please let us know if this is still a problem for you.

**Comment by wookoouk** [comment]
Still a problem for me.
```
[pagem@software x86_64]$ brew install git
which: no shasum in (/tsl/software/testing/bin/core/../..//git/1.9/x86_64/bin:/tsl/software/production/bin/core/../..//hpccore/5/x86_64/bin:/tsl/software/testing/bin/core/../..//brew/custom/x86_64/bin:/usr/local/bin:/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/sbin:/tsl/software/testing/bin:/tsl/software/testing/libraries/bin:/tsl/software/production/bin:/tsl/software/production/libraries/bin:/usr/users/sl/pagem/.local/bin:/usr/users/sl/pagem/bin)
Error: Version value must be a string; got a NilClass ()
Please report this bug:
  https://github.com/Linuxbrew/brew/blob/master/docs/Troubleshooting.md#troubleshooting
/tsl/software/testing/brew/custom/x86_64/Library/Homebrew/version.rb:198:in `initialize'
/tsl/software/testing/brew/custom/x86_64/Library/Homebrew/tap.rb:265:in `new'
/tsl/software/testing/brew/custom/x86_64/Library/Homebrew/tap.rb:265:in `install'
/tsl/software/testing/brew/custom/x86_64/Library/Homebrew/cmd/tap.rb:52:in `tap'
/tsl/software/testing/brew/custom/x86_64/Library/Homebrew/brew.rb:100:in `<main>'
Error: Failure while executing: /tsl/software/testing/brew/custom/x86_64/bin/brew tap homebrew/core -q
```
