### ISSUE TITLE
pipenv cannot easily manage multiple python versions

### ISSUE THREAD

**Issue by damonmaria** [Homebrew/homebrew-core#31487]
- [X] are reporting a bug others will be able to reproduce and not asking a question. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh
- [X] have a problem with `brew install` (or `upgrade`, `reinstall`) a single, official formula (not cask)? If it's a general `brew` problem please file this issue at Homebrew/brew: https://github.com/Homebrew/brew/issues/new/choose. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/homebrew-cask/issues/new/choose. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [X] ran `brew update` and can still reproduce the problem?
- [ ] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [X] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [ ] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

Note: [I asked this as a question first](https://discourse.brew.sh/t/pipenv-only-works-with-one-specific-python-version/2475), and am pretty sure it's a bug (or at least a large shortcoming).

# What you were trying to do (and why)
Use the brew installed `pipenv` to install a virtual environment that is not brew's current version of python (but is a version of python previously installed by brew). 

Why? Because this is a large part of the purpose of pipenv. 

# What happened (include command output)
```shell
$ brew doctor
Your system is ready to brew.
$ which python3
/usr/local/bin/python3
$ python3 --version
Python 3.7.0
$ brew list --versions python
python 3.7.0 3.6.5_1 3.6.5
$ pipenv install --python 3.6
Warning: Python 3.6 was not found on your system...
You can specify specific versions of Python with:
  $ pipenv --python path/to/python
```

OK, specify full path to brew python 3.6.5_1:
```shell
$ pipenv install --python /usr/local/Cellar/python/3.6.5_1/bin/python3 
Creating a virtualenv for this project...
Pipfile: /Users/damon/Downloads/pipenv-test/tracking/Pipfile
Using /usr/local/Cellar/python/3.6.5_1/bin/python3 (3.6.5) to create virtualenv...
⠋Running virtualenv with interpreter /usr/local/Cellar/python/3.6.5_1/bin/python3
Using base prefix '/usr/local/Cellar/python/3.6.5_1/Frameworks/Python.framework/Versions/3.6'
New python executable in /Users/damon/Downloads/pipenv-test/tracking/.venv/bin/python3.6
Traceback (most recent call last):
  File "/usr/local/Cellar/pipenv/2018.7.1/libexec/lib/python3.7/site-packages/virtualenv.py", line 2343, in <module>
    main()
  File "/usr/local/Cellar/pipenv/2018.7.1/libexec/lib/python3.7/site-packages/virtualenv.py", line 712, in main
    symlink=options.symlink)
  File "/usr/local/Cellar/pipenv/2018.7.1/libexec/lib/python3.7/site-packages/virtualenv.py", line 927, in create_environment
    site_packages=site_packages, clear=clear, symlink=symlink))
  File "/usr/local/Cellar/pipenv/2018.7.1/libexec/lib/python3.7/site-packages/virtualenv.py", line 1233, in install_python
    shutil.copyfile(executable, py_executable)
  File "/usr/local/Cellar/python/3.6.5_1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/shutil.py", line 120, in copyfile
    with open(src, 'rb') as fsrc:
FileNotFoundError: [Errno 2] No such file or directory: '/usr/local/opt/python/bin/python3.6'
```

OK then, switch python version:
```shell
$ brew switch python 3.6.5_1 
Cleaning /usr/local/Cellar/python/3.7.0
Cleaning /usr/local/Cellar/python/3.6.5_1
Cleaning /usr/local/Cellar/python/3.6.5
25 links created for /usr/local/Cellar/python/3.6.5_1
$ pipenv install --python 3.6
dyld: Library not loaded: @executable_path/../.Python
  Referenced from: /usr/local/Cellar/pipenv/2018.7.1/libexec/bin/python3.7
  Reason: image not found
Abort trap: 6
```

To make it work you have to also switch pipenv to be the version at the time the older version of python existed:
```shell
$ brew switch pipenv 2018.6.25 
Cleaning /usr/local/Cellar/pipenv/2018.6.25
Cleaning /usr/local/Cellar/pipenv/2018.7.1
2 links created for /usr/local/Cellar/pipenv/2018.6.25
$ pipenv install --python 3.6
Creating a virtualenv for this project...
...
```

But this is a pain to figure out and not obvious. Also, it re-introduces old pipenv bugs which in my case has stopped certain pipfiles from working (kind of a catch-22). 

# What you expected to happen
Best solution would be for brew's pipenv to be able to use any brew installed version of python without switching. But as a compromise it would be better if switching to the version of python wanted, installing, and then switching back worked.

# Step-by-step reproduction instructions (by running `brew install` commands)
See above.

**Comment by damonmaria** [comment]
Is this seen as an issue? One of the primary purposes of `pipenv` is that you can have virtual environments with specific python versions but that doesn't seem very practical as currently implemented through homebrew. 

First things first, when `pipenv` tries to build a environment from a non-current version of python, stop it following symlinks through to `/usr/local/opt/python`, it needs to stay within `/usr/local/Cellar/python/`

And then a close to perfect solution would be if all homebrew versions of python in the cellar were available to pipenv when it ran, so you didn't need to pass the full `/usr/local/Cellar/python/...` path to pipenv. I'm not sure how that would be appropriate tho.

**Comment by damonmaria** [comment]
Looking into the issue with `/usr/local/opt/python` further, `sysconfig` returns a mixture of `opt` and `Cellar` paths. Thus `python3-config` also returns `opt` paths. 

Also, the few files in `/usr/local/Cellar/python/*/bin` that are not symlinks are short little python scripts also hard coded to `opt`. 

I am sure there's a reason to use a mixture of `/usr/local/opt/python` and `/usr/local/Cellar/python` paths but any use of `/usr/local/opt/` means the Cellar install is unusable if it's not the current homebrew version.

**Comment by VanessaHenderson** [comment]
I am also facing the above issue. Any help would be appreciated. I need to be able to use pipenv with a specific version of python.

**Comment by nmishra** [comment]
this issue still exists with pipenv running on `/usr/local/Cellar/pipenv/2018.7.1`

**Comment by ashleyblackmore** [comment]
Still exists with pipenv 2018.10.13_1

**Comment by rhazegh** [comment]
Having the same problem. 

Since this seems to be a main feature of the pipenv, I hope this issue is given a higher priority. 

```
[pipenv-test]$ which python3
/usr/local/bin/python3
[pipenv-test]$ python3 --version
Python 3.7.1
[pipenv-test]$ brew list --versions python
python 3.7.0 3.7.1 3.6.3 3.6.5 2.7.14
[pipenv-test]$ pipenv install --python 3.6.5
Warning: Python 3.6.5 was not found on your system…
You can specify specific versions of Python with:
  $ pipenv --python path/to/python
[pipenv-test]$ pipenv install --python /usr/local/Cellar/python/3.6.5/bin/python3
Creating a virtualenv for this project…
Pipfile: /Users/ramin/projects/test/pipenv-test/Pipfile
Using /usr/local/Cellar/python/3.6.5/bin/python3 (3.6.5) to create virtualenv…
⠴Running virtualenv with interpreter /usr/local/Cellar/python/3.6.5/bin/python3
Using base prefix '/usr/local/Cellar/python/3.6.5/Frameworks/Python.framework/Versions/3.6'
New python executable in /Users/ramin/.local/share/virtualenvs/pipenv-test-lmVJ1RwT/bin/python3.6
Traceback (most recent call last):
  File "/usr/local/Cellar/pipenv/2018.10.13_1/libexec/lib/python3.7/site-packages/virtualenv.py", line 2343, in <module>
    main()
  File "/usr/local/Cellar/pipenv/2018.10.13_1/libexec/lib/python3.7/site-packages/virtualenv.py", line 712, in main
    symlink=options.symlink)
  File "/usr/local/Cellar/pipenv/2018.10.13_1/libexec/lib/python3.7/site-packages/virtualenv.py", line 927, in create_environment
    site_packages=site_packages, clear=clear, symlink=symlink))
  File "/usr/local/Cellar/pipenv/2018.10.13_1/libexec/lib/python3.7/site-packages/virtualenv.py", line 1233, in install_python
    shutil.copyfile(executable, py_executable)
  File "/usr/local/Cellar/python/3.6.5/Frameworks/Python.framework/Versions/3.6/lib/python3.6/shutil.py", line 120, in copyfile
    with open(src, 'rb') as fsrc:
FileNotFoundError: [Errno 2] No such file or directory: '/usr/local/opt/python/bin/python3.6'

Traceback (most recent call last):
  File "/usr/local/Cellar/pipenv/2018.10.13_1/libexec/bin/pipenv", line 11, in <module>
    load_entry_point('pipenv==2018.10.13', 'console_scripts', 'pipenv')()
  File "/usr/local/Cellar/pipenv/2018.10.13_1/libexec/lib/python3.7/site-packages/pipenv/vendor/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/Cellar/pipenv/2018.10.13_1/libexec/lib/python3.7/site-packages/pipenv/vendor/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/usr/local/Cellar/pipenv/2018.10.13_1/libexec/lib/python3.7/site-packages/pipenv/vendor/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/Cellar/pipenv/2018.10.13_1/libexec/lib/python3.7/site-packages/pipenv/vendor/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/Cellar/pipenv/2018.10.13_1/libexec/lib/python3.7/site-packages/pipenv/vendor/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/Cellar/pipenv/2018.10.13_1/libexec/lib/python3.7/site-packages/pipenv/vendor/click/decorators.py", line 64, in new_func
    return ctx.invoke(f, obj, *args, **kwargs)
  File "/usr/local/Cellar/pipenv/2018.10.13_1/libexec/lib/python3.7/site-packages/pipenv/vendor/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/Cellar/pipenv/2018.10.13_1/libexec/lib/python3.7/site-packages/pipenv/vendor/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/Cellar/pipenv/2018.10.13_1/libexec/lib/python3.7/site-packages/pipenv/cli/command.py", line 249, in install
    editable_packages=state.installstate.editables,
  File "/usr/local/Cellar/pipenv/2018.10.13_1/libexec/lib/python3.7/site-packages/pipenv/core.py", line 1724, in do_install
    pypi_mirror=pypi_mirror,
  File "/usr/local/Cellar/pipenv/2018.10.13_1/libexec/lib/python3.7/site-packages/pipenv/core.py", line 565, in ensure_project
    pypi_mirror=pypi_mirror,
  File "/usr/local/Cellar/pipenv/2018.10.13_1/libexec/lib/python3.7/site-packages/pipenv/core.py", line 500, in ensure_virtualenv
    python=python, site_packages=site_packages, pypi_mirror=pypi_mirror
  File "/usr/local/Cellar/pipenv/2018.10.13_1/libexec/lib/python3.7/site-packages/pipenv/core.py", line 901, in do_create_virtualenv
    click.echo(crayons.blue("{0}".format(c.err)), err=True)
  File "/usr/local/Cellar/pipenv/2018.10.13_1/libexec/lib/python3.7/site-packages/pipenv/vendor/delegator.py", line 146, in err
    return self._pexpect_out
  File "/usr/local/Cellar/pipenv/2018.10.13_1/libexec/lib/python3.7/site-packages/pipenv/vendor/delegator.py", line 114, in _pexpect_out
    result += self.subprocess.after
TypeError: can only concatenate str (not "type") to str
```

**Comment by dealancer** [comment]
Any ideas how to fix it?
