### ISSUE TITLE
llnode fails to build on 10.14

### ISSUE THREAD

**Issue by DomT4** [Homebrew/homebrew-core#31617]
```
==> make plugin
node scripts/configure.js
Build dir is: /private/tmp/llnode-20180831-94315-j3e66y/llnode-1.7.1
Using lldb executable lldb

Looking for llvm-config...
No llvm-config found

Reading lldb version...
Deduced lldb version from Xcode version: Xcode 10.0 -> lldb 3.9
Installing llnode for lldb, lldb version 3.9

Looking for headers for lldb 3.9...
Could not find the headers, will download them later

Looking for shared libraries for lldb 3.9...
Could not find the shared libraries 
llnode will be linked to the LLDB shared framework from the Xcode installation

Skip cloning lldb headers because /private/tmp/llnode-20180831-94315-j3e66y/llnode-1.7.1/lldb-3.9 exists
Writing config.gypi:
{
  "variables": {
    "lldb_include_dir%": "/private/tmp/llnode-20180831-94315-j3e66y/llnode-1.7.1/lldb-3.9/include"
  }
}
Writing llnode.sh shortcut to /private/tmp/llnode-20180831-94315-j3e66y/llnode-1.7.1/llnode.sh
```

```
gyp info spawn make
gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
make[1]: warning: jobserver unavailable: using -j1.  Add `+' to parent make rule.
  CXX(target) Release/obj.target/plugin/src/llnode.o
  CXX(target) Release/obj.target/plugin/src/llv8.o
  CXX(target) Release/obj.target/plugin/src/llv8-constants.o
  CXX(target) Release/obj.target/plugin/src/llscan.o
  SOLINK(target) Release/plugin.dylib
ld: framework not found LLDB
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[1]: *** [Release/plugin.dylib] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/Cellar/node/10.9.0/libexec/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:239:12)
gyp ERR! System Darwin 18.0.0
gyp ERR! command "/usr/local/Cellar/node/10.9.0/bin/node" "/usr/local/opt/node/libexec/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /private/tmp/llnode-20180831-94315-j3e66y/llnode-1.7.1
gyp ERR! node -v v10.9.0
gyp ERR! node-gyp -v v3.7.0
gyp ERR! not ok 
make: *** [plugin] Error 1
```

**Comment by SConaway** [comment]
Seems to build on my 10.14

**Comment by DomT4** [comment]
Do you have the headers package installed? That might be the difference here; our CI machines don't have it installed because it's due to go away soon.

**Comment by SConaway** [comment]
Yes, although I'm not quite sure what you mean.

**Comment by DomT4** [comment]
Do you have a link for `brew gist-logs llnode`?

**Comment by SConaway** [comment]
I meant i'm confused on 

> That might be the difference here; our CI machines don't have it installed because it's due to go away soon.

**Comment by DomT4** [comment]
Aye, I was mostly curious to see where your build was different from our's.

The header package, which in the earlier days of 10.14 Homebrew encouraged people to install, is being removed by Apple. As of 10.14 there will not be a `/usr/include` regardless of whether you install Xcode, the CLT or both.

**Comment by SConaway** [comment]
And what will be the workaround, or will the headers be back to how they were in High Sierra?

**Comment by SConaway** [comment]
Is there a list?

**Comment by SConaway** [comment]
@DomT4 hello?

**Comment by SMillerDev** [comment]
There's an overarching issue here. 

https://github.com/Homebrew/homebrew-core/issues/28817

**Comment by SConaway** [comment]
I know, I'm just adding logs.

**Comment by chrmoritz** [comment]
Did something changed here? I can't reproduce the build failure with 10.14 `18A389` (without sdk heades installed), node v10.10.0 and brew master.

https://gist.github.com/chrmoritz/edf4d335f59a3c09dca38522e752be5b
