### ISSUE TITLE
Brew doctor fails on 10.10.5

### ISSUE THREAD

**Issue by isaacmediacore** [Homebrew/homebrew-core#3173]
# Please follow the general troubleshooting steps first:

- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?

### Bug reports:

`brew doctor` fails with `Error: undefined method 'cask' for Formulary::FormulaNamespace6f4c291e8070f07ab44a624bbc890b8c:Module`

output and `brew config` at: https://gist.github.com/isaacmediacore/8d9efc14059134491baa8434f61e2042

I'm just coming back to this computer after not seriously using it for a few months, so I'm afraid things are probably horridly out of date.  Please let me know if there's any more info you need.  Thanks!

**Comment by DomT4** [comment]
```
Error: undefined method `cask' for Formulary::FormulaNamespace6f4c291e8070f07ab44a624bbc890b8c:Module
Please report this bug:
    https://git.io/brew-troubleshooting
/Users/isaac.havard/Library/Caches/Homebrew/Formula/ngrok.rb:1:in `load_formula'
```

This is unusual. Can you try `brew cleanup --prune=0` & run `brew doctor` again? Wondering if you've somehow got a corrupted formula file in there.

**Comment by isaacmediacore** [comment]
Thanks for getting back to me!  Unfortunately `brew cleanup` gives me the same error.

```
[isaac.havard@IHAVARD-01 ~]$ brew cleanup --prune=0
Error: undefined method `cask' for Formulary::FormulaNamespace6f4c291e8070f07ab44a624bbc890b8c:Module
Please report this bug:
    https://git.io/brew-troubleshooting
/Users/isaac.havard/Library/Caches/Homebrew/Formula/ngrok.rb:1:in `load_formula'
/usr/local/Library/Homebrew/formulary.rb:25:in `module_eval'
/usr/local/Library/Homebrew/formulary.rb:25:in `load_formula'
/usr/local/Library/Homebrew/formulary.rb:42:in `load_formula_from_path'
/usr/local/Library/Homebrew/formulary.rb:91:in `load_file'
/usr/local/Library/Homebrew/formulary.rb:82:in `klass'
/usr/local/Library/Homebrew/formulary.rb:78:in `get_formula'
/usr/local/Library/Homebrew/formulary.rb:215:in `factory'
/usr/local/Library/Homebrew/formulary.rb:245:in `rescue in from_keg'
/usr/local/Library/Homebrew/formulary.rb:241:in `from_keg'
/usr/local/Library/Homebrew/formulary.rb:225:in `from_rack'
/usr/local/Library/Homebrew/formula.rb:1150:in `block in installed'
/usr/local/Library/Homebrew/formula.rb:1148:in `map'
/usr/local/Library/Homebrew/formula.rb:1148:in `installed'
/usr/local/Library/Homebrew/cleanup.rb:41:in `cleanup_cellar'
/usr/local/Library/Homebrew/cleanup.rb:10:in `cleanup'
/usr/local/Library/Homebrew/cmd/cleanup.rb:20:in `cleanup'
/usr/local/Library/Homebrew/brew.rb:87:in `<main>'
```

**Comment by DomT4** [comment]
Heh. Let's try the non-brew way of that then:
```bash
rm -rf $(brew --cache)
```

If that doesn't work try:
```bash
cd $(brew --prefix) && git fetch && git reset --hard origin/master
```

**Comment by isaacmediacore** [comment]
Well I'll be, that fixed it.  Thanks so much for your help!

**Comment by DomT4** [comment]
Great! Let us know if you need help with anything else 😃
