### ISSUE TITLE
Error: undefined method `to_str' for :master:Symbol when installing dinghy

### ISSUE THREAD

**Issue by bbmreed** [Homebrew/homebrew-core#31840]
**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [x] are reporting a bug others will be able to reproduce and not asking a question. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh
- [x] have a problem with `brew install` (or `upgrade`, `reinstall`) a single, official formula (not cask)? If it's a general `brew` problem please file this issue at Homebrew/brew: https://github.com/Homebrew/brew/issues/new/choose. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/homebrew-cask/issues/new/choose. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [x] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

To help us debug your issue please explain:
- What you were trying to do (and why)

Installing dinghy via homebrew.

- What happened (include command output)

```
$ brew install --HEAD dinghy
==> Installing dinghy from codekitchen/dinghy
==> Installing dependencies for codekitchen/dinghy/dinghy: automake
==> Installing codekitchen/dinghy/dinghy dependency: automake
==> Downloading https://homebrew.bintray.com/bottles/automake-1.16.1_1.sierra.bottle.tar.gz
######################################################################## 100.0%
==> Pouring automake-1.16.1_1.sierra.bottle.tar.gz
🍺  /usr/local/Cellar/automake/1.16.1_1: 131 files, 3.4MB
==> Installing codekitchen/dinghy/dinghy --HEAD
==> Cloning https://github.com/codekitchen/dinghy.git
Updating /Users/mike/Library/Caches/Homebrew/dinghy--git
From https://github.com/codekitchen/dinghy
   05349a3..c7c0a2e  master     -> origin/master
 * [new tag]         v4.6.5     -> v4.6.5
 * [new tag]         v4.6.4     -> v4.6.4
Fetching submodule cli/fsevents_to_vm
From https://github.com/codekitchen/fsevents_to_vm
   eab8080..9a32dbc  master     -> origin/master
==> Checking out branch master
Error: undefined method `to_str' for :master:Symbol
Please report this bug:
  https://docs.brew.sh/Troubleshooting
/usr/local/Homebrew/Library/Homebrew/system_command.rb:113:in `block in expanded_args'
/usr/local/Homebrew/Library/Homebrew/system_command.rb:107:in `map'
/usr/local/Homebrew/Library/Homebrew/system_command.rb:107:in `expanded_args'
/usr/local/Homebrew/Library/Homebrew/system_command.rb:71:in `command'
/usr/local/Homebrew/Library/Homebrew/system_command.rb:119:in `each_output_line'
/usr/local/Homebrew/Library/Homebrew/system_command.rb:35:in `run!'
/usr/local/Homebrew/Library/Homebrew/system_command.rb:23:in `run'
/usr/local/Homebrew/Library/Homebrew/system_command.rb:27:in `run!'
/usr/local/Homebrew/Library/Homebrew/system_command.rb:16:in `system_command!'
/usr/local/Homebrew/Library/Homebrew/download_strategy.rb:105:in `system_command!'
/usr/local/Homebrew/Library/Homebrew/download_strategy.rb:871:in `checkout'
/usr/local/Homebrew/Library/Homebrew/download_strategy.rb:776:in `update'
/usr/local/Homebrew/Library/Homebrew/download_strategy.rb:128:in `fetch'
/usr/local/Homebrew/Library/Homebrew/resource.rb:119:in `fetch'
/usr/local/Homebrew/Library/Homebrew/resource.rb:72:in `stage'
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/2.3.0/forwardable.rb:202:in `stage'
/usr/local/Homebrew/Library/Homebrew/formula.rb:2022:in `stage'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1117:in `brew'
/usr/local/Homebrew/Library/Homebrew/build.rb:113:in `block in install'
/usr/local/Homebrew/Library/Homebrew/utils.rb:520:in `with_env'
/usr/local/Homebrew/Library/Homebrew/build.rb:110:in `install'
/usr/local/Homebrew/Library/Homebrew/build.rb:191:in `<main>'
```

- What you expected to happen

Dinghy to be installed with no error.

- Step-by-step reproduction instructions (by running `brew install` commands)

brew install --HEAD dinghy

- Debugging output

```
$ brew doctor
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: You have unlinked kegs in your Cellar
Leaving kegs unlinked can lead to build-trouble and cause brews that depend on
those kegs to fail to run properly once built. Run `brew link` on these:
  dinghy

Warning: Broken symlinks were found. Remove them with `brew prune`:
  /usr/local/lib/ruby/gems/2.4.0/gems/tmuxinator-0.10.1/completion/mux.fish

Warning: Some installed formulae are missing dependencies.
You should `brew install` the missing dependencies:
  brew install clingo libidn2 libunistring lua

Run `brew missing` for more details.
```

```
$ brew config
HOMEBREW_VERSION: 1.7.3
ORIGIN: https://github.com/Homebrew/brew
HEAD: 61ace27006a1cb444552c0be10087fcbc3051643
Last commit: 2 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: be44bcad42cbd5e6e015bec71f11ef56b228ad59
Core tap last commit: 60 minutes ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_GIT: git
CPU: quad-core 64-bit skylake
Homebrew Ruby: 2.3.7 => /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/bin/ruby
Clang: 9.0 build 900
Git: 2.14.3 => /usr/bin/git
Curl: 7.54.0 => /usr/bin/curl
Java: 9, 1.8.0_144
macOS: 10.12.6-x86_64
CLT: 9.2.0.0.1.1510905681
Xcode: 9.2
XQuartz: N/A
```

### Crux of the issue

This is the offending code:

```
  def expanded_args
    @expanded_args ||= args.map do |arg|
      if arg.respond_to?(:to_path)
        File.absolute_path(arg)
      elsif arg.is_a?(Integer) || arg.is_a?(Float) || arg.is_a?(URI)
        arg.to_s
      else
        arg.to_str
      end
    end
  end
```

If `arg` is a keyword, we should call `.to_s` and not `.to_str`, so I think the fix might be as simple as adding a keyword check on the argument.

**Comment by fxcoudert** [comment]
The `dinghy` formula is not part of Homebrew core, but from an external tap: [`codekitchen/dinghy`](https://github.com/codekitchen/homebrew-dinghy) and should be reported to the tap's maintainers. This issue is at line 5 of the formula (https://github.com/codekitchen/homebrew-dinghy/blob/master/Formula/dinghy.rb#L5) where:

```
head "https://github.com/codekitchen/dinghy.git", :branch => :master
```

should instead be:

```
head "https://github.com/codekitchen/dinghy.git", :branch => "master"
```

**Comment by bbmreed** [comment]
@fxcoudert Thanks for finding this! I filed an issue with dinghy, hopefully they can resolve this.

This does seem like an easy mistake to make, would it be worth accepting keywords here to prevent this from happening from other external taps?
