### ISSUE TITLE
undefined method `shelljoin' for nil:NilClass

### ISSUE THREAD

**Issue by jpmhglance** [Homebrew/homebrew-core#32062]
When installing someone's bug fix version of libimobiledevice, got an error and a "Please report this bug".

```
/usr/local/Homebrew/Library/Homebrew/utils/fork.rb:49:in `write': Broken pipe (Errno::EPIPE)
	from /usr/local/Homebrew/Library/Homebrew/utils/fork.rb:49:in `puts'
	from /usr/local/Homebrew/Library/Homebrew/utils/fork.rb:49:in `rescue in block (3 levels) in safe_fork'
	from /usr/local/Homebrew/Library/Homebrew/utils/fork.rb:31:in `block (3 levels) in safe_fork'
	from /usr/local/Homebrew/Library/Homebrew/utils/fork.rb:30:in `fork'
	from /usr/local/Homebrew/Library/Homebrew/utils/fork.rb:30:in `block (2 levels) in safe_fork'
	from /usr/local/Homebrew/Library/Homebrew/utils/fork.rb:27:in `open'
	from /usr/local/Homebrew/Library/Homebrew/utils/fork.rb:27:in `block in safe_fork'
	from /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/2.3.0/tmpdir.rb:89:in `mktmpdir'
	from /usr/local/Homebrew/Library/Homebrew/utils/fork.rb:26:in `safe_fork'
	from /usr/local/Homebrew/Library/Homebrew/formula_installer.rb:719:in `build'
	from /usr/local/Homebrew/Library/Homebrew/formula_installer.rb:311:in `install'
	from /usr/local/Homebrew/Library/Homebrew/cmd/install.rb:321:in `install_formula'
	from /usr/local/Homebrew/Library/Homebrew/cmd/install.rb:253:in `block in install'
	from /usr/local/Homebrew/Library/Homebrew/cmd/install.rb:251:in `each'
	from /usr/local/Homebrew/Library/Homebrew/cmd/install.rb:251:in `install'
	from /usr/local/Homebrew/Library/Homebrew/brew.rb:89:in `<main>'
Error: undefined method `shelljoin' for nil:NilClass
Please report this bug:
  https://docs.brew.sh/Troubleshooting
/usr/local/Homebrew/Library/Homebrew/exceptions.rb:546:in `initialize'
/usr/local/Homebrew/Library/Homebrew/utils/fork.rb:7:in `new'
/usr/local/Homebrew/Library/Homebrew/utils/fork.rb:7:in `rewrite_child_error'
/usr/local/Homebrew/Library/Homebrew/utils/fork.rb:78:in `block (3 levels) in safe_fork'
/usr/local/Homebrew/Library/Homebrew/utils.rb:399:in `ignore_interrupts'
/usr/local/Homebrew/Library/Homebrew/utils/fork.rb:57:in `block (2 levels) in safe_fork'
/usr/local/Homebrew/Library/Homebrew/utils/fork.rb:27:in `open'
/usr/local/Homebrew/Library/Homebrew/utils/fork.rb:27:in `block in safe_fork'
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/2.3.0/tmpdir.rb:89:in `mktmpdir'
/usr/local/Homebrew/Library/Homebrew/utils/fork.rb:26:in `safe_fork'
/usr/local/Homebrew/Library/Homebrew/formula_installer.rb:719:in `build'
/usr/local/Homebrew/Library/Homebrew/formula_installer.rb:311:in `install'
/usr/local/Homebrew/Library/Homebrew/cmd/install.rb:321:in `install_formula'
/usr/local/Homebrew/Library/Homebrew/cmd/install.rb:253:in `block in install'
/usr/local/Homebrew/Library/Homebrew/cmd/install.rb:251:in `each'
/usr/local/Homebrew/Library/Homebrew/cmd/install.rb:251:in `install'
/usr/local/Homebrew/Library/Homebrew/brew.rb:89:in `<main>'
```

Made a more complete log of this install, output from brew doctor & brew config (and some related installs I did prior fwiw): https://gist.github.com/jpmhglance/afe0894ea0cd0499986cb0bcdcff41ca

Was trying to install an bug fix to libimobiledevice as described on at https://github.com/libimobiledevice/libimobiledevice/issues/510#issuecomment-319731404

Updated to the Xcode 10 GM this morning, so this could be part of it, but several brew installs before this error worked without problem, so it doesn't seems like my setup is totally hosed.

**Comment by SMillerDev** [comment]
We can't really fix a gist someone uploaded. Unless this also happens with the default install (if that one is in homebrew-core) there's nothing we can do really.

**Comment by jpmhglance** [comment]
I didn't expect that the gist needed fixing or that you'd attempt that, however it looked like maybe it was exposing a homebrew bug, seemingly why the output emphasized "Please report this bug". But, you know better than I, feel free to close.

(My interest in this issue is over in any case. I followed someone else suggestion to remove the "--with-ios11" option and found that the install worked as did the installed software)

**Comment by shuxiao9058** [comment]
the same error when install emacs-plus.

```
Last login: Thu Sep 27 20:15:22 on ttys000
➜  workspace brew reinstall emacs-plus --without-spacemacs-icon --HEAD  --with-xwidgets --with-x11 --with-mailutils --with-no-titlebar --with-dbus --with-ctags
==> Reinstalling d12frosted/emacs-plus/emacs-plus --without-spacemacs-icon --with-ctags --with-x11 --with-no-titlebar --with-xwidgets --with-dbus --with-mailutils
==> Cloning https://github.com/emacs-mirror/emacs.git
Updating /Users/jiya/Library/Caches/Homebrew/emacs-plus--git
==> Checking out branch master
Already on 'master'
Your branch is up to date with 'origin/master'.
HEAD is now at 21fc322763 * etc/NEWS: Mention syntax change in add-dir-local-variable (bug#32817)
==> Downloading https://raw.githubusercontent.com/d12frosted/homebrew-emacs-plus/master/patches/borderless-frame-on-macOS.patch
Already downloaded: /Users/jiya/Library/Caches/Homebrew/downloads/543dc0c38762e42f061f9244aa062b7c21a0a16ef0a3a969a53b01b84882a5d1--borderless-frame-on-macOS.patch
==> Downloading https://gist.githubusercontent.com/aatxe/260261daf70865fbf1749095de9172c5/raw/214b50c62450be1cbee9f11cecba846dd66c7d06/patch-multicolor-font.diff
Already downloaded: /Users/jiya/Library/Caches/Homebrew/downloads/7dccd5b8ea0bb2eb29cfb643365489d84c16ea33b1743261be66fa9691733a1e--patch-multicolor-font.diff
==> Downloading https://gist.githubusercontent.com/fuxialexander/0231e994fd27be6dd87db60339238813/raw/b30c2d3294835f41e2c8afa1e63571531a38f3cf/0_all_webkit.patch
Already downloaded: /Users/jiya/Library/Caches/Homebrew/downloads/b34d7183e6c2a943f83c0691bff4134248cee3995b03be387be86e44d51357a2--0_all_webkit.patch
==> Downloading https://github.com/emacs-mirror/emacs/compare/scratch/ns-drawing.patch
Already downloaded: /Users/jiya/Library/Caches/Homebrew/downloads/c1db0ec448ad4654a5da7e1e68f13ffec201eb9c2ddea96d5d8e34f6da2a8cd2--ns-drawing.patch
==> Downloading http://emacs.1067599.n8.nabble.com/attachment/465838/0/0001-Fix-crash-on-flush-to-display-bug-32812.patch
Already downloaded: /Users/jiya/Library/Caches/Homebrew/downloads/67ff2d2c690d38749dfe088d243a743d039300a0d9c40516b729521c65476d52--0001-Fix-crash-on-flush-to-display-bug-32812.patch
==> Patching
==> Applying borderless-frame-on-macOS.patch
patching file src/nsterm.m
Hunk #1 FAILED at 425.
Hunk #2 FAILED at 1888.
Hunk #3 FAILED at 6842.
Hunk #4 FAILED at 7218.
Hunk #5 FAILED at 7253.
5 out of 5 hunks FAILED -- saving rejects to file src/nsterm.m.rej
Error: undefined method `shelljoin' for nil:NilClass
Please report this bug:
  https://docs.brew.sh/Troubleshooting
/usr/local/Homebrew/Library/Homebrew/exceptions.rb:547:in `initialize'
/usr/local/Homebrew/Library/Homebrew/utils/fork.rb:7:in `new'
/usr/local/Homebrew/Library/Homebrew/utils/fork.rb:7:in `rewrite_child_error'
/usr/local/Homebrew/Library/Homebrew/utils/fork.rb:84:in `block (3 levels) in safe_fork'
/usr/local/Homebrew/Library/Homebrew/utils.rb:402:in `ignore_interrupts'
/usr/local/Homebrew/Library/Homebrew/utils/fork.rb:60:in `block (2 levels) in safe_fork'
/usr/local/Homebrew/Library/Homebrew/utils/fork.rb:29:in `open'
/usr/local/Homebrew/Library/Homebrew/utils/fork.rb:29:in `block in safe_fork'
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/tmpdir.rb:89:in `mktmpdir'
/usr/local/Homebrew/Library/Homebrew/utils/fork.rb:28:in `safe_fork'
/usr/local/Homebrew/Library/Homebrew/formula_installer.rb:729:in `build'
/usr/local/Homebrew/Library/Homebrew/formula_installer.rb:317:in `install'
/usr/local/Homebrew/Library/Homebrew/reinstall.rb:33:in `reinstall_formula'
/usr/local/Homebrew/Library/Homebrew/cmd/reinstall.rb:26:in `block in reinstall'
/usr/local/Homebrew/Library/Homebrew/cmd/reinstall.rb:20:in `each'
/usr/local/Homebrew/Library/Homebrew/cmd/reinstall.rb:20:in `reinstall'
/usr/local/Homebrew/Library/Homebrew/brew.rb:91:in `<main>'
➜  workspace
```

**Comment by fxcoudert** [comment]
@shuxiao9058 please report the problem to `emacs-plus`: https://github.com/d12frosted/homebrew-emacs-plus/issues
