### ISSUE TITLE
brew install git-lfs => gem install ronn fails

### ISSUE THREAD

**Issue by king7532** [Homebrew/homebrew-core#32212]
- [x] are reporting a bug others will be able to reproduce and not asking a question. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh
- [x] have a problem with `brew install` (or `upgrade`, `reinstall`) a single, official formula (not cask)? If it's a general `brew` problem please file this issue at Homebrew/brew: https://github.com/Homebrew/brew/issues/new/choose. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/homebrew-cask/issues/new/choose. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
  - I have some files in my /usr/local that `brew doctor` complains about, which have nothing to do with ruby or gems
- [x] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
   - https://gist.github.com/e9be84de594ce7d0f6fdf488c1e6a891

```
$ sw_vers
ProductName:	Mac OS X
ProductVersion:	10.13.6
BuildVersion:	17G65

$ xcodebuild -version
Xcode 10.0
Build version 10A255
```

```
$ brew --version
Homebrew 1.7.5-15-g9d49146
Homebrew/homebrew-core (git revision 4bd74; last commit 2018-09-18)
Homebrew/homebrew-cask (git revision 07825; last commit 2018-09-18)

$ ruby --version   # brew install ruby
ruby 2.5.1p57 (2018-03-29 revision 63029) [x86_64-darwin17]
```

```
$ brew install git-lfs
==> Downloading https://github.com/git-lfs/git-lfs/archive/v2.5.2.tar.gz
Already downloaded: /Users/king/Library/Caches/Homebrew/downloads/113d93d1b2db7b7a7be94d394b182c25ab9c41a51ebda9a7d356b01d24345dfa--git-lfs-2.5.2.tar.gz
==> gem install ronn
Last 15 lines from /Users/king/Library/Logs/Homebrew/git-lfs/01.gem:
	from /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/mkmf.rb:350:in `block in postpone'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/mkmf.rb:320:in `open'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/mkmf.rb:346:in `postpone'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/mkmf.rb:941:in `checking_for'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/mkmf.rb:1050:in `have_func'
	from extconf.rb:5:in `<main>'

To see why this extension failed to compile, please check the mkmf.log which can be found here:

  /private/tmp/git-lfs-20180918-66795-23nd4z/git-lfs-2.5.2/src/github.com/git-lfs/git-lfs/.gem_home/extensions/universal-darwin-17/2.3.0/rdiscount-2.2.0.1/mkmf.log

extconf failed, exit code 1

Gem files will remain installed in /private/tmp/git-lfs-20180918-66795-23nd4z/git-lfs-2.5.2/src/github.com/git-lfs/git-lfs/.gem_home/gems/rdiscount-2.2.0.1 for inspection.
Results logged to /private/tmp/git-lfs-20180918-66795-23nd4z/git-lfs-2.5.2/src/github.com/git-lfs/git-lfs/.gem_home/extensions/universal-darwin-17/2.3.0/rdiscount-2.2.0.1/gem_make.out
/usr/local/Homebrew/Library/Homebrew/utils/fork.rb:49:in `write': Broken pipe (Errno::EPIPE)
	from /usr/local/Homebrew/Library/Homebrew/utils/fork.rb:49:in `puts'
	from /usr/local/Homebrew/Library/Homebrew/utils/fork.rb:49:in `rescue in block (3 levels) in safe_fork'
	from /usr/local/Homebrew/Library/Homebrew/utils/fork.rb:31:in `block (3 levels) in safe_fork'
	from /usr/local/Homebrew/Library/Homebrew/utils/fork.rb:30:in `fork'
	from /usr/local/Homebrew/Library/Homebrew/utils/fork.rb:30:in `block (2 levels) in safe_fork'
	from /usr/local/Homebrew/Library/Homebrew/utils/fork.rb:27:in `open'
	from /usr/local/Homebrew/Library/Homebrew/utils/fork.rb:27:in `block in safe_fork'
	from /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/2.3.0/tmpdir.rb:89:in `mktmpdir'
	from /usr/local/Homebrew/Library/Homebrew/utils/fork.rb:26:in `safe_fork'
	from /usr/local/Homebrew/Library/Homebrew/formula_installer.rb:729:in `build'
	from /usr/local/Homebrew/Library/Homebrew/formula_installer.rb:317:in `install'
	from /usr/local/Homebrew/Library/Homebrew/cmd/install.rb:325:in `install_formula'
	from /usr/local/Homebrew/Library/Homebrew/cmd/install.rb:256:in `block in install'
	from /usr/local/Homebrew/Library/Homebrew/cmd/install.rb:254:in `each'
	from /usr/local/Homebrew/Library/Homebrew/cmd/install.rb:254:in `install'
	from /usr/local/Homebrew/Library/Homebrew/brew.rb:89:in `<main>'
```

**Comment by king7532** [comment]
Why is `brew install` using `/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0` instead of the Home-brew ruby 2.5.1?

**Comment by king7532** [comment]
I can successfully install `gem install ronn` outside of the formula:
```
$ gem install ronn
Fetching: mustache-1.0.5.gem (100%)
Successfully installed mustache-1.0.5
Fetching: rdiscount-2.2.0.1.gem (100%)
Building native extensions. This could take a while...
Successfully installed rdiscount-2.2.0.1
Fetching: hpricot-0.8.6.gem (100%)
Building native extensions. This could take a while...
Successfully installed hpricot-0.8.6
Fetching: ronn-0.7.3.gem (100%)
Successfully installed ronn-0.7.3
Parsing documentation for mustache-1.0.5
Installing ri documentation for mustache-1.0.5
Parsing documentation for rdiscount-2.2.0.1
Installing ri documentation for rdiscount-2.2.0.1
Parsing documentation for hpricot-0.8.6
Installing ri documentation for hpricot-0.8.6
Parsing documentation for ronn-0.7.3
Installing ri documentation for ronn-0.7.3
Done installing documentation for mustache, rdiscount, hpricot, ronn after 2 seconds
4 gems installed
```

**Comment by king7532** [comment]
When I run `brew install --verbose git-lfs`:
```
==> gem install ronn
Successfully installed mustache-1.0.5
Building native extensions.  This could take a while...
ERROR:  Error installing ronn:
	ERROR: Failed to build gem native extension.

    current directory: /private/tmp/git-lfs-20180918-76689-yqvhll/git-lfs-2.5.2/src/github.com/git-lfs/git-lfs/.gem_home/gems/rdiscount-2.2.0.1/ext
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/bin/ruby -r ./siteconf20180918-76700-z9dz47.rb extconf.rb
checking for random()... *** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
	--with-opt-dir
	--without-opt-dir
	--with-opt-include
	--without-opt-include=${opt-dir}/include
	--with-opt-lib
	--without-opt-lib=${opt-dir}/lib
	--with-make-prog
	--without-make-prog
	--srcdir=.
	--curdir
	--ruby=/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/bin/$(RUBY_BASE_NAME)
	--with-rdiscount-dir
	--without-rdiscount-dir
	--with-rdiscount-include
	--without-rdiscount-include=${rdiscount-dir}/include
	--with-rdiscount-lib
	--without-rdiscount-lib=${rdiscount-dir}/lib
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/mkmf.rb:456:in `try_do': The compiler failed to generate an executable file. (RuntimeError)
You have to install development tools first.
	from /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/mkmf.rb:535:in `block in try_link0'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/tmpdir.rb:89:in `mktmpdir'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/mkmf.rb:532:in `try_link0'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/mkmf.rb:556:in `try_link'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/mkmf.rb:765:in `try_func'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/mkmf.rb:1051:in `block in have_func'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/mkmf.rb:942:in `block in checking_for'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/mkmf.rb:350:in `block (2 levels) in postpone'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/mkmf.rb:320:in `open'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/mkmf.rb:350:in `block in postpone'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/mkmf.rb:320:in `open'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/mkmf.rb:346:in `postpone'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/mkmf.rb:941:in `checking_for'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/mkmf.rb:1050:in `have_func'
	from extconf.rb:5:in `<main>'

To see why this extension failed to compile, please check the mkmf.log which can be found here:

  /private/tmp/git-lfs-20180918-76689-yqvhll/git-lfs-2.5.2/src/github.com/git-lfs/git-lfs/.gem_home/extensions/universal-darwin-17/2.3.0/rdiscount-2.2.0.1/mkmf.log

extconf failed, exit code 1
```

**Comment by MikeMcQuaid** [comment]
@king7532 Please fill out the issue template.

**Comment by king7532** [comment]
@MikeMcQuaid I updated the issue description.

**Comment by MikeMcQuaid** [comment]
> Warning: You have HOMEBREW_BUILD_FROM_SOURCE set. This environment variable is intended for use by Homebrew developers. If you are encountering errors, please try unsetting this. Please do not file issues if you encounter errors when using this environment variable.

@king7532 Did that help your problem?

**Comment by MikeMcQuaid** [comment]
@king7532 There may be but unfortunately we do not support the use of `HOMEBREW_BUILD_FROM_SOURCE`. We'll review a pull request or fix issues if we see them in our CI.
