### ISSUE TITLE
neovim `--HEAD` install broken

### ISSUE THREAD

**Issue by t0str** [Homebrew/homebrew-core#32231]
Installing neovim with `--HEAD` fails because of a broken download link.

```
$ brew reinstall --HEAD neovim
==> Reinstalling neovim
==> Cloning https://github.com/neovim/neovim.git
Updating /Users/ost/Library/Caches/Homebrew/neovim--git
==> Checking out branch master
Already on 'master'
Your branch is up to date with 'origin/master'.
HEAD is now at 8b60253ce cleanup/TUI: remove old unused code #9013
==> Downloading https://luarocks.org/manifests/gvvaughan/lpeg-1.0.1-1.src.rock
Already downloaded: /Users/ost/Library/Caches/Homebrew/downloads/8dfe80834670fa8af7d5264d07d66afc6fb5b4f253e772a06014f0a8b734eaf6--lpeg-1.0.1-1.src.rock
==> Downloading https://github.com/libmpack/libmpack-lua/releases/download/1.0.7/libmpack-lua-1.0.7.tar.gz
Already downloaded: /Users/ost/Library/Caches/Homebrew/downloads/ad0f976ceb0dc87d6ce2195e0a405fc851ae85b558580477f1bac0c93c2a933a--libmpack-lua-1.0.7.tar.gz
==> Downloading https://luarocks.org/manifests/kikito/inspect-3.1.1-0.src.rock
Already downloaded: /Users/ost/Library/Caches/Homebrew/downloads/ecc1fa84ce4c83c9406f6d1202d4a88c80ede4a0a2bfd8d8d2bd54fd042226bb--inspect-3.1.1-0.src.rock
==> Downloading https://luarocks.org/luabitop-1.0.2-1.src.rock

curl: (22) The requested URL returned error: 404 Not Found
/usr/local/Homebrew/Library/Homebrew/utils/fork.rb:49:in `write': Broken pipe (Errno::EPIPE)
        from /usr/local/Homebrew/Library/Homebrew/utils/fork.rb:49:in `puts'
        from /usr/local/Homebrew/Library/Homebrew/utils/fork.rb:49:in `rescue in block (3 levels) in safe_fork'
        from /usr/local/Homebrew/Library/Homebrew/utils/fork.rb:31:in `block (3 levels) in safe_fork'
        from /usr/local/Homebrew/Library/Homebrew/utils/fork.rb:30:in `fork'
        from /usr/local/Homebrew/Library/Homebrew/utils/fork.rb:30:in `block (2 levels) in safe_fork'
        from /usr/local/Homebrew/Library/Homebrew/utils/fork.rb:27:in `open'
        from /usr/local/Homebrew/Library/Homebrew/utils/fork.rb:27:in `block in safe_fork'
        from /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/tmpdir.rb:89:in `mktmpdir'
        from /usr/local/Homebrew/Library/Homebrew/utils/fork.rb:26:in `safe_fork'
        from /usr/local/Homebrew/Library/Homebrew/formula_installer.rb:719:in `build'
        from /usr/local/Homebrew/Library/Homebrew/formula_installer.rb:311:in `install'
        from /usr/local/Homebrew/Library/Homebrew/reinstall.rb:33:in `reinstall_formula'
        from /usr/local/Homebrew/Library/Homebrew/cmd/reinstall.rb:26:in `block in reinstall'
        from /usr/local/Homebrew/Library/Homebrew/cmd/reinstall.rb:20:in `each'
        from /usr/local/Homebrew/Library/Homebrew/cmd/reinstall.rb:20:in `reinstall'
        from /usr/local/Homebrew/Library/Homebrew/brew.rb:89:in `<main>'
Error: An exception occured within a build process:
  DownloadError: Failed to download resource "neovim--luabitop"
Download failed: https://luarocks.org/luabitop-1.0.2-1.src.rock
```

MacOS 10.13.6
Homebrew 1.7.5
Homebrew/homebrew-core (git revision dfee2; last commit 2018-09-19)
Homebrew/homebrew-cask (git revision b7448; last commit 2018-09-19)

**Comment by t0str** [comment]
I missed that there already was an issue for that (#32144). Closing this one.
