### ISSUE TITLE
python@2 issues with lldb after most recent Xcode command line tools update

### ISSUE THREAD

**Issue by caitp** [Homebrew/homebrew-core#32284]
Xcode-bundled lldb seems to freak out really badly with the python@2 recipe, and it bothered me enough to throw it away and switch to python3 --- Which is great in theory, but there is a chance I'll need to use scripts not compatible with python3, and six probably won't fix it.

So in order, I ran into the following:

```
$ lldb
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Applications/Xcode.app/Contents/SharedFrameworks/LLDB.framework/Resources/Python/lldb/__init__.py", line 98, in <module>
    import six
ImportError: No module named six
Traceback (most recent call last):
  File "<string>", line 1, in <module>
NameError: name 'run_one_line' is not defined
Traceback (most recent call last):
  File "<string>", line 1, in <module>
NameError: name 'run_one_line' is not defined
Traceback (most recent call last):
  File "<string>", line 1, in <module>
NameError: name 'run_one_line' is not defined
Traceback (most recent call last):
  File "<string>", line 1, in <module>
NameError: name 'run_one_line' is not defined
Traceback (most recent call last):
  File "<string>", line 1, in <module>
NameError: name 'run_one_line' is not defined
Traceback (most recent call last):
  File "<string>", line 1, in <module>
NameError: name 'run_one_line' is not defined
(lldb) quit
```

After installing `six`,

```
$ sudo -H pip install six
Collecting six
  Downloading https://files.pythonhosted.org/packages/67/4b/141a581104b1f6397bfa78ac9d43d8ad29a7ca43ea90a2d863fe3056e86a/six-1.11.0-py2.py3-none-any.whl
Installing collected packages: six
Successfully installed six-1.11.0
$ lldb
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "/usr/local/Cellar/python@2/2.7.15_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/copy.py", line 52, in <module>
    import weakref
  File "/usr/local/Cellar/python@2/2.7.15_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/weakref.py", line 14, in <module>
    from _weakref import (
ImportError: cannot import name _remove_dead_weakref
(lldb) quit
```

lldb is still technically usable, but any lldb command whatsoever will result in a lot of spam sent to the terminal, and it's really unpleasant and frustrating to work with --- so I wound up uninstalling python@2 and everything that depends on it (including mercurial and watchman, but I'm not using them much now), and installing python3 --- my most used lldb commands still work with it, so that works for me.

BUT, it would be nice if python2 were still usable for cases where it's required.

**Comment by MikeMcQuaid** [comment]
We cannot control or change the system `lldb`, sorry.

Please always fill out the issue template in future.

**Comment by caitp** [comment]
The issue was with python@2, not system lldb

**Comment by MikeMcQuaid** [comment]
@caitp Your issue is not with `python@2` but with the behaviour of the system `lldb` when it is installed. We cannot control that.
