### ISSUE TITLE
install/upgrade most apps failed in 10.14

### ISSUE THREAD

**Issue by rayl-brbio** [Homebrew/homebrew-core#32519]
```
➜  ~ brew upgrade/install go                                                                        
Updating Homebrew...
Error: NaN
/usr/local/Homebrew/Library/Homebrew/os/mac/xcode.rb:152:in `to_i'
/usr/local/Homebrew/Library/Homebrew/os/mac/xcode.rb:152:in `detect_version_from_clang_version'
/usr/local/Homebrew/Library/Homebrew/os/mac/xcode.rb:144:in `detect_version'
/usr/local/Homebrew/Library/Homebrew/os/mac/xcode.rb:114:in `version'
/usr/local/Homebrew/Library/Homebrew/os/mac/xcode.rb:58:in `without_clt?'
/usr/local/Homebrew/Library/Homebrew/os/mac/xcode.rb:49:in `needs_clt_installed?'
/usr/local/Homebrew/Library/Homebrew/extend/os/mac/diagnostic.rb:113:in `check_if_xcode_needs_clt_installed'
/usr/local/Homebrew/Library/Homebrew/cmd/install.rb:320:in `block in check_development_tools'
/usr/local/Homebrew/Library/Homebrew/cmd/install.rb:319:in `each'
/usr/local/Homebrew/Library/Homebrew/cmd/install.rb:319:in `check_development_tools'
/usr/local/Homebrew/Library/Homebrew/cmd/install.rb:339:in `perform_preinstall_checks'
/usr/local/Homebrew/Library/Homebrew/cmd/upgrade.rb:30:in `upgrade'
/usr/local/Homebrew/Library/Homebrew/brew.rb:100:in `<main>'
```

**Comment by rayl-brbio** [comment]
```bash➜  ~ brew upgrade ruby
Updating Homebrew...
Error: NaN
/usr/local/Homebrew/Library/Homebrew/os/mac/xcode.rb:152:in `to_i'
/usr/local/Homebrew/Library/Homebrew/os/mac/xcode.rb:152:in `detect_version_from_clang_version'
/usr/local/Homebrew/Library/Homebrew/os/mac/xcode.rb:144:in `detect_version'
/usr/local/Homebrew/Library/Homebrew/os/mac/xcode.rb:114:in `version'
/usr/local/Homebrew/Library/Homebrew/os/mac/xcode.rb:58:in `without_clt?'
/usr/local/Homebrew/Library/Homebrew/os/mac/xcode.rb:49:in `needs_clt_installed?'
/usr/local/Homebrew/Library/Homebrew/extend/os/mac/diagnostic.rb:113:in `check_if_xcode_needs_clt_installed'
/usr/local/Homebrew/Library/Homebrew/cmd/install.rb:320:in `block in check_development_tools'
/usr/local/Homebrew/Library/Homebrew/cmd/install.rb:319:in `each'
/usr/local/Homebrew/Library/Homebrew/cmd/install.rb:319:in `check_development_tools'
/usr/local/Homebrew/Library/Homebrew/cmd/install.rb:339:in `perform_preinstall_checks'
/usr/local/Homebrew/Library/Homebrew/cmd/upgrade.rb:30:in `upgrade'
/usr/local/Homebrew/Library/Homebrew/brew.rb:100:in `<main>'
```

**Comment by rayl-brbio** [comment]
the same error raised in all commands of `brew`

**Comment by rayl-brbio** [comment]
```bash
➜  ~ cd "$(brew --repo)" && git fetch && git reset --hard origin/master && brew update 
HEAD is now at cb2cf654a Merge pull request #4855 from MikeMcQuaid/keg-caskroom-writable
Already up-to-date.
```
