### ISSUE TITLE
Cannot import python modules inside vim

### ISSUE THREAD

**Issue by fgsch** [Homebrew/homebrew-core#32587]
- [x] I am reporting a bug others will be able to reproduce and not asking a question. 
- [x] ran `brew update`

- What you were trying to do (and why)

Use https://github.com/sjl/gundo.vim.

- What happened (include command output)

Got an error:

```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/<redacted>/autoload/gundo.py", line 11, in <module>
    import difflib
  File "/usr/local/Cellar/python@2/2.7.15_1/Frameworks/Python.framework/Versions/2.
7/lib/python2.7/difflib.py", line 33, in <module>
    import heapq
  File "/usr/local/Cellar/python@2/2.7.15_1/Frameworks/Python.framework/Versions/2.
7/lib/python2.7/heapq.py", line 132, in <module>
    from itertools import islice, count, imap, izip, tee, chain
ImportError: dlopen(/usr/local/Cellar/python@2/2.7.15_1/Frameworks/Python.framework
/Versions/2.7/lib/python2.7/lib-dynload/itertools.so, 2): no suitable image found.
 Did find:
^I/usr/local/Cellar/python@2/2.7.15_1/Frameworks/Python.framework/Versions/2.7/lib/
python2.7/lib-dynload/itertools.so: code signature in (/usr/local/Cellar/python@2/2
.7.15_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-dynload/itertool
s.so) not valid for use in process using Library Validation: mapped file has no cdh
ash, completely unsigned? Code has to be at least ad-hoc signed.
...
```
- What you expected to happen

gundo is working

- Step-by-step reproduction instructions (by running `brew install` commands)

Inside vim type `:python import difflib`

- vim version output:

```
vim --version                                                                                                                           <<<
VIM - Vi IMproved 8.1 (2018 May 18, compiled Sep 30 2018 19:54:41)
macOS version
Included patches: 1-400
Compiled by Homebrew
Huge version without GUI.  Features included (+) or not (-):
+acl               +extra_search      +mouse_netterm     +tag_old_static
+arabic            +farsi             +mouse_sgr         -tag_any_white
+autocmd           +file_in_path      -mouse_sysmouse    -tcl
+autochdir         +find_in_path      +mouse_urxvt       +termguicolors
-autoservername    +float             +mouse_xterm       +terminal
-balloon_eval      +folding           +multi_byte        +terminfo
+balloon_eval_term -footer            +multi_lang        +termresponse
-browse            +fork()            -mzscheme          +textobjects
++builtin_terms    -gettext           +netbeans_intg     +timers
+byte_offset       -hangul_input      +num64             +title
+channel           +iconv             +packages          -toolbar
+cindent           +insert_expand     +path_extra        +user_commands
-clientserver      +job               +perl              +vartabs
+clipboard         +jumplist          +persistent_undo   +vertsplit
+cmdline_compl     +keymap            +postscript        +virtualedit
+cmdline_hist      +lambda            +printer           +visual
+cmdline_info      +langmap           +profile           +visualextra
+comments          +libcall           -python            +viminfo
+conceal           +linebreak         +python3           +vreplace
+cryptv            +lispindent        +quickfix          +wildignore
+cscope            +listcmds          +reltime           +wildmenu
+cursorbind        +localmap          +rightleft         +windows
+cursorshape       +lua               +ruby              +writebackup
+dialog_con        +menu              +scrollbind        -X11
+diff              +mksession         +signs             -xfontset
+digraphs          +modify_fname      +smartindent       -xim
-dnd               +mouse             +startuptime       -xpm
-ebcdic            -mouseshape        +statusline        -xsmp
+emacs_tags        +mouse_dec         -sun_workshop      -xterm_clipboard
+eval              -mouse_gpm         +syntax            -xterm_save
+ex_extra          -mouse_jsbterm     +tag_binary
   system vimrc file: "$VIM/vimrc"
     user vimrc file: "$HOME/.vimrc"
 2nd user vimrc file: "~/.vim/vimrc"
      user exrc file: "$HOME/.exrc"
       defaults file: "$VIMRUNTIME/defaults.vim"
  fall-back for $VIM: "/usr/local/share/vim"
Compilation: clang -c -I. -Iproto -DHAVE_CONFIG_H   -DMACOS_X -DMACOS_X_DARWIN  -g -O2 -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1
Linking: clang   -L. -fstack-protector -L/usr/local/lib -L/usr/local/opt/libyaml/lib -L/usr/local/opt/openssl/lib -L/usr/local/opt/readline/lib  -L/usr/local/lib -o vim        -lncurses -liconv -framework AppKit  -L/usr/local/opt/lua/lib -llua5.3 -mmacosx-version-min=10.14 -fstack-protector-strong -L/usr/local/lib  -L/usr/local/Cellar/perl/5.28.0/lib/perl5/5.28.0/darwin-thread-multi-2level/CORE -lperl -lm -lutil -lc  -L/usr/local/opt/python/Frameworks/Python.framework/Versions/3.7/lib/python3.7/config-3.7m-darwin -lpython3.7m -framework CoreFoundation  -lruby.2.5.1 -lobjc
```

**Comment by SMillerDev** [comment]
Could you also fill out the rest of the issue template? It's really difficult to infer any real issue from your current information other than vim being broken if you install a plugin (which would seem like a vim, plugin or python issue)

**Comment by fgsch** [comment]
@SMillerDev I filled in all the relevant fields. What is it missing?
Plugin aside importing a python module is broken as you can see if you try doing `:python import difflib` inside vim. Isn't that enough?

**Comment by MikeMcQuaid** [comment]
From the issue template:

> **Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you do not read fill out the issue template repeatedly you will be blocked from ever submitting issues to Homebrew again.**

If you add the necessary information to this issue (don't create a new one, please) then this issue may be reopened.

**Comment by neuhalje** [comment]
Please re-open. Same here with Powerline plugin. Started well before Mojave

**Comment by MikeMcQuaid** [comment]
@neuhalje We don't have the information we need to solve this problem. If you're willing to fill out the issue template: please open a new issue with the required information.

**Comment by neuhalje** [comment]
@fgsch Bad luck :-( 

- What does `vim --clean  -c "python import difflib"` say  (mind: I have to use `python3 import difflib`)?
- Have you tried a complete 'fresh' vim?:
```sh
TMP_VIM=/tmp/vim
mkdir -p ${TMP_VIM}/.vim/{autoload,bundle}

cat<<EOF>${TMP_VIM}/.vimrc
set nocp
EOF

HOME=${TMP_VIM} vim   -c "python import difflib"
```

**Comment by fgsch** [comment]
@neuhalje Whatever was the issue, I cannot longer reproduce it after today's upgrade:

```
VIM - Vi IMproved 8.1 (2018 May 18, compiled Oct  3 2018 13:00:16)
macOS version
Included patches: 1-450
```
