### ISSUE TITLE
Many formulae fail to post-install

### ISSUE THREAD

**Issue by alexreg** [Homebrew/homebrew-core#32758]
**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [x] are reporting a bug others will be able to reproduce and not asking a question. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh
- [x] have a problem with `brew install` (or `upgrade`, `reinstall`) a single, official formula (not cask)? If it's a general `brew` problem please file this issue at Homebrew/brew: https://github.com/Homebrew/brew/issues/new/choose. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/homebrew-cask/issues/new/choose. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [x] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

To help us debug your issue please explain:
- What you were trying to do (and why)
- What happened (include command output)
- What you expected to happen
- Step-by-step reproduction instructions (by running `brew install` commands)

I just upgraded to macOS Mojave, and now when I do `brew upgrade formula` or `brew postinstall formula`, I get the following, e.g.

```$ brew postinstall libepoxy
==> Postinstalling libepoxy
Warning: The post-install step did not complete successfully
You can try again using `brew postinstall libepoxy`
```

This also occurs for other formulae, e.g. `exercism`, `unrar`... possibly all formulae?

`gist-logs` doesn't produce anything, but here's the output of `config`:

```
HOMEBREW_VERSION: 1.7.6-114-g8883735
ORIGIN: https://github.com/Homebrew/brew.git
HEAD: 88837353fbbc2cd2061b78ae79f4dda577312738
Last commit: 2 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: ae74080d8e1f5dcb89c365197bbbdcca402398d4
Core tap last commit: 5 hours ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_DEV_CMD_RUN: 1
HOMEBREW_GITHUB_API_TOKEN: set
HOMEBREW_VISUAL: mate_wait
CPU: octa-core 64-bit haswell
Homebrew Ruby: 2.3.7 => /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/bin/ruby
Clang: 10.0 build 1000
Git: 2.19.0 => /usr/local/bin/git
Curl: 7.54.0 => /usr/bin/curl
Java: 1.8.0_60
macOS: 10.14-x86_64
CLT: N/A
Xcode: 10.0
XQuartz: 2.7.11 => /opt/X11
```

And `doctor`:

```
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: "config" scripts exist outside your system or Homebrew directories.
`./configure` scripts often look for *-config scripts to determine if
software packages are installed, and what additional flags to use when
compiling and linking.

Having additional scripts in your path can confuse software installed via
Homebrew if the config script overrides a system or Homebrew provided
script of the same name. We found the following "config" scripts:
  /Users/alex/.cargo/bin/cargo-install-update-config

Warning: Unbrewed dylibs were found in /usr/local/lib.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected dylibs:
  /usr/local/lib/libaspell.15.1.4.dylib
  /usr/local/lib/libaubio.4.1.1.dylib
  /usr/local/lib/libbitcoin-client.0.dylib
  /usr/local/lib/libbitcoin-explorer.0.dylib
  /usr/local/lib/libbitcoin.0.dylib
  /usr/local/lib/libchkp.dylib
  /usr/local/lib/libd2xx_table.dylib
  /usr/local/lib/libgdsl.1.dylib
  /usr/local/lib/libiCheckKernel.dylib
  /usr/local/lib/libifcore.dylib
  /usr/local/lib/libifcoremt.dylib
  /usr/local/lib/libifport.dylib
  /usr/local/lib/libifportmt.dylib
  /usr/local/lib/libimf.dylib
  /usr/local/lib/libintlc.dylib
  /usr/local/lib/libiomp5.dylib
  /usr/local/lib/libiompstubs5.dylib
  /usr/local/lib/libirc.dylib
  /usr/local/lib/libirng.dylib
  /usr/local/lib/libmkl_avx.dylib
  /usr/local/lib/libmkl_avx2.dylib
  /usr/local/lib/libmkl_avx512.dylib
  /usr/local/lib/libmkl_blacs_mpich_ilp64.dylib
  /usr/local/lib/libmkl_blacs_mpich_lp64.dylib
  /usr/local/lib/libmkl_cdft_core.dylib
  /usr/local/lib/libmkl_core.dylib
  /usr/local/lib/libmkl_intel_ilp64.dylib
  /usr/local/lib/libmkl_intel_lp64.dylib
  /usr/local/lib/libmkl_intel_thread.dylib
  /usr/local/lib/libmkl_mc.dylib
  /usr/local/lib/libmkl_mc3.dylib
  /usr/local/lib/libmkl_rt.dylib
  /usr/local/lib/libmkl_scalapack_ilp64.dylib
  /usr/local/lib/libmkl_scalapack_lp64.dylib
  /usr/local/lib/libmkl_sequential.dylib
  /usr/local/lib/libmkl_tbb_thread.dylib
  /usr/local/lib/libmkl_vml_avx.dylib
  /usr/local/lib/libmkl_vml_avx2.dylib
  /usr/local/lib/libmkl_vml_avx512.dylib
  /usr/local/lib/libmkl_vml_mc.dylib
  /usr/local/lib/libmkl_vml_mc2.dylib
  /usr/local/lib/libmkl_vml_mc3.dylib
  /usr/local/lib/libpcl_apps.1.6.0.dylib
  /usr/local/lib/libpcl_common.1.6.0.dylib
  /usr/local/lib/libpcl_features.1.6.0.dylib
  /usr/local/lib/libpcl_filters.1.6.0.dylib
  /usr/local/lib/libpcl_geometry.1.6.0.dylib
  /usr/local/lib/libpcl_io.1.6.0.dylib
  /usr/local/lib/libpcl_io_ply.1.6.0.dylib
  /usr/local/lib/libpcl_kdtree.1.6.0.dylib
  /usr/local/lib/libpcl_keypoints.1.6.0.dylib
  /usr/local/lib/libpcl_octree.1.6.0.dylib
  /usr/local/lib/libpcl_registration.1.6.0.dylib
  /usr/local/lib/libpcl_sample_consensus.1.6.0.dylib
  /usr/local/lib/libpcl_search.1.6.0.dylib
  /usr/local/lib/libpcl_segmentation.1.6.0.dylib
  /usr/local/lib/libpcl_surface.1.6.0.dylib
  /usr/local/lib/libpcl_tracking.1.6.0.dylib
  /usr/local/lib/libpcl_visualization.1.6.0.dylib
  /usr/local/lib/libpspell.15.1.4.dylib
  /usr/local/lib/libsbuf.0.dylib
  /usr/local/lib/libsecp256k1.0.dylib
  /usr/local/lib/libsvml.dylib
  /usr/local/lib/libtbb.dylib
  /usr/local/lib/libtbbmalloc.dylib
  /usr/local/lib/libtbbmalloc_proxy.dylib

Warning: Unbrewed header files were found in /usr/local/include.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected header files:
  /usr/local/include/argp.h
  /usr/local/include/aspell.h
  /usr/local/include/aubio/aubio.h
  /usr/local/include/aubio/cvec.h
  /usr/local/include/aubio/fmat.h
  /usr/local/include/aubio/fvec.h
  /usr/local/include/aubio/io/audio_unit.h
  /usr/local/include/aubio/io/sink.h
  /usr/local/include/aubio/io/sink_apple_audio.h
  /usr/local/include/aubio/io/sink_sndfile.h
  /usr/local/include/aubio/io/sink_wavwrite.h
  /usr/local/include/aubio/io/source.h
  /usr/local/include/aubio/io/source_apple_audio.h
  /usr/local/include/aubio/io/source_avcodec.h
  /usr/local/include/aubio/io/source_sndfile.h
  /usr/local/include/aubio/io/source_wavread.h
  /usr/local/include/aubio/lvec.h
  /usr/local/include/aubio/mathutils.h
  /usr/local/include/aubio/musicutils.h
  /usr/local/include/aubio/onset/onset.h
  /usr/local/include/aubio/onset/peakpicker.h
  /usr/local/include/aubio/pitch/pitch.h
  /usr/local/include/aubio/pitch/pitchfcomb.h
  /usr/local/include/aubio/pitch/pitchmcomb.h
  /usr/local/include/aubio/pitch/pitchschmitt.h
  /usr/local/include/aubio/pitch/pitchspecacf.h
  /usr/local/include/aubio/pitch/pitchyin.h
  /usr/local/include/aubio/pitch/pitchyinfft.h
  /usr/local/include/aubio/spectral/fft.h
  /usr/local/include/aubio/spectral/filterbank.h
  /usr/local/include/aubio/spectral/filterbank_mel.h
  /usr/local/include/aubio/spectral/mfcc.h
  /usr/local/include/aubio/spectral/phasevoc.h
  /usr/local/include/aubio/spectral/specdesc.h
  /usr/local/include/aubio/spectral/tss.h
  /usr/local/include/aubio/synth/sampler.h
  /usr/local/include/aubio/synth/wavetable.h
  /usr/local/include/aubio/tempo/beattracking.h
  /usr/local/include/aubio/tempo/tempo.h
  /usr/local/include/aubio/temporal/a_weighting.h
  /usr/local/include/aubio/temporal/biquad.h
  /usr/local/include/aubio/temporal/c_weighting.h
  /usr/local/include/aubio/temporal/filter.h
  /usr/local/include/aubio/temporal/resampler.h
  /usr/local/include/aubio/types.h
  /usr/local/include/aubio/utils/hist.h
  /usr/local/include/aubio/utils/parameter.h
  /usr/local/include/aubio/utils/scale.h
  /usr/local/include/aubio/vecutils.h
  /usr/local/include/bitcoin/bitcoin/compat.h
  /usr/local/include/cpplib.h
  /usr/local/include/gdsl.h
  /usr/local/include/gdsl/_gdsl_bintree.h
  /usr/local/include/gdsl/_gdsl_bstree.h
  /usr/local/include/gdsl/_gdsl_list.h
  /usr/local/include/gdsl/_gdsl_node.h
  /usr/local/include/gdsl/gdsl_2darray.h
  /usr/local/include/gdsl/gdsl_bstree.h
  /usr/local/include/gdsl/gdsl_hash.h
  /usr/local/include/gdsl/gdsl_heap.h
  /usr/local/include/gdsl/gdsl_interval_heap.h
  /usr/local/include/gdsl/gdsl_list.h
  /usr/local/include/gdsl/gdsl_macros.h
  /usr/local/include/gdsl/gdsl_perm.h
  /usr/local/include/gdsl/gdsl_queue.h
  /usr/local/include/gdsl/gdsl_rbtree.h
  /usr/local/include/gdsl/gdsl_sort.h
  /usr/local/include/gdsl/gdsl_stack.h
  /usr/local/include/gdsl/gdsl_types.h
  /usr/local/include/gl_array_list.h
  /usr/local/include/gl_array_oset.h
  /usr/local/include/gl_avltree_list.h
  /usr/local/include/gl_avltree_oset.h
  /usr/local/include/gl_avltreehash_list.h
  /usr/local/include/gl_carray_list.h
  /usr/local/include/gl_linked_list.h
  /usr/local/include/gl_linkedhash_list.h
  /usr/local/include/gl_list.h
  /usr/local/include/gl_oset.h
  /usr/local/include/gl_rbtree_list.h
  /usr/local/include/gl_rbtree_oset.h
  /usr/local/include/gl_rbtreehash_list.h
  /usr/local/include/gl_sublist.h
  /usr/local/include/gl_xlist.h
  /usr/local/include/gl_xoset.h
  /usr/local/include/gl_xsublist.h
  /usr/local/include/jack/control.h
  /usr/local/include/jack/intclient.h
  /usr/local/include/jack/jack.h
  /usr/local/include/jack/jslist.h
  /usr/local/include/jack/metadata.h
  /usr/local/include/jack/midiport.h
  /usr/local/include/jack/net.h
  /usr/local/include/jack/ringbuffer.h
  /usr/local/include/jack/session.h
  /usr/local/include/jack/statistics.h
  /usr/local/include/jack/systemdeps.h
  /usr/local/include/jack/thread.h
  /usr/local/include/jack/transport.h
  /usr/local/include/jack/types.h
  /usr/local/include/jack/uuid.h
  /usr/local/include/jack/weakjack.h
  /usr/local/include/jack/weakmacros.h
  /usr/local/include/memstream.h
  /usr/local/include/pspell/pspell.h
  /usr/local/include/python2.6/sip.h
  /usr/local/include/python3.6m/pygame/_camera.h
  /usr/local/include/python3.6m/pygame/_pygame.h
  /usr/local/include/python3.6m/pygame/_surface.h
  /usr/local/include/python3.6m/pygame/bitmask.h
  /usr/local/include/python3.6m/pygame/camera.h
  /usr/local/include/python3.6m/pygame/fastevents.h
  /usr/local/include/python3.6m/pygame/font.h
  /usr/local/include/python3.6m/pygame/freetype.h
  /usr/local/include/python3.6m/pygame/mask.h
  /usr/local/include/python3.6m/pygame/mixer.h
  /usr/local/include/python3.6m/pygame/pgarrinter.h
  /usr/local/include/python3.6m/pygame/pgbufferproxy.h
  /usr/local/include/python3.6m/pygame/pgcompat.h
  /usr/local/include/python3.6m/pygame/pgopengl.h
  /usr/local/include/python3.6m/pygame/pygame.h
  /usr/local/include/python3.6m/pygame/scrap.h
  /usr/local/include/python3.6m/pygame/surface.h
  /usr/local/include/sbuf.h
  /usr/local/include/secp256k1.h
  /usr/local/include/secp256k1_recovery.h
  /usr/local/include/smart_ptr.h
  /usr/local/include/sptr.h
  /usr/local/include/sptr/util.h
  /usr/local/include/valgrind/callgrind.h
  /usr/local/include/valgrind/config.h
  /usr/local/include/valgrind/drd.h
  /usr/local/include/valgrind/helgrind.h
  /usr/local/include/valgrind/libvex.h
  /usr/local/include/valgrind/libvex_basictypes.h
  /usr/local/include/valgrind/libvex_emnote.h
  /usr/local/include/valgrind/libvex_guest_amd64.h
  /usr/local/include/valgrind/libvex_guest_arm.h
  /usr/local/include/valgrind/libvex_guest_arm64.h
  /usr/local/include/valgrind/libvex_guest_mips32.h
  /usr/local/include/valgrind/libvex_guest_mips64.h
  /usr/local/include/valgrind/libvex_guest_offsets.h
  /usr/local/include/valgrind/libvex_guest_ppc32.h
  /usr/local/include/valgrind/libvex_guest_ppc64.h
  /usr/local/include/valgrind/libvex_guest_s390x.h
  /usr/local/include/valgrind/libvex_guest_tilegx.h
  /usr/local/include/valgrind/libvex_guest_x86.h
  /usr/local/include/valgrind/libvex_ir.h
  /usr/local/include/valgrind/libvex_s390x_common.h
  /usr/local/include/valgrind/libvex_trc_values.h
  /usr/local/include/valgrind/memcheck.h
  /usr/local/include/valgrind/pub_tool_addrinfo.h
  /usr/local/include/valgrind/pub_tool_aspacehl.h
  /usr/local/include/valgrind/pub_tool_aspacemgr.h
  /usr/local/include/valgrind/pub_tool_basics.h
  /usr/local/include/valgrind/pub_tool_basics_asm.h
  /usr/local/include/valgrind/pub_tool_clientstate.h
  /usr/local/include/valgrind/pub_tool_clreq.h
  /usr/local/include/valgrind/pub_tool_debuginfo.h
  /usr/local/include/valgrind/pub_tool_deduppoolalloc.h
  /usr/local/include/valgrind/pub_tool_errormgr.h
  /usr/local/include/valgrind/pub_tool_execontext.h
  /usr/local/include/valgrind/pub_tool_gdbserver.h
  /usr/local/include/valgrind/pub_tool_guest.h
  /usr/local/include/valgrind/pub_tool_hashtable.h
  /usr/local/include/valgrind/pub_tool_libcassert.h
  /usr/local/include/valgrind/pub_tool_libcbase.h
  /usr/local/include/valgrind/pub_tool_libcfile.h
  /usr/local/include/valgrind/pub_tool_libcprint.h
  /usr/local/include/valgrind/pub_tool_libcproc.h
  /usr/local/include/valgrind/pub_tool_libcsetjmp.h
  /usr/local/include/valgrind/pub_tool_libcsignal.h
  /usr/local/include/valgrind/pub_tool_machine.h
  /usr/local/include/valgrind/pub_tool_mallocfree.h
  /usr/local/include/valgrind/pub_tool_options.h
  /usr/local/include/valgrind/pub_tool_oset.h
  /usr/local/include/valgrind/pub_tool_poolalloc.h
  /usr/local/include/valgrind/pub_tool_rangemap.h
  /usr/local/include/valgrind/pub_tool_redir.h
  /usr/local/include/valgrind/pub_tool_replacemalloc.h
  /usr/local/include/valgrind/pub_tool_seqmatch.h
  /usr/local/include/valgrind/pub_tool_signals.h
  /usr/local/include/valgrind/pub_tool_sparsewa.h
  /usr/local/include/valgrind/pub_tool_stacktrace.h
  /usr/local/include/valgrind/pub_tool_threadstate.h
  /usr/local/include/valgrind/pub_tool_tooliface.h
  /usr/local/include/valgrind/pub_tool_transtab.h
  /usr/local/include/valgrind/pub_tool_vki.h
  /usr/local/include/valgrind/pub_tool_vkiscnums.h
  /usr/local/include/valgrind/pub_tool_vkiscnums_asm.h
  /usr/local/include/valgrind/pub_tool_wordfm.h
  /usr/local/include/valgrind/pub_tool_xarray.h
  /usr/local/include/valgrind/valgrind.h
  /usr/local/include/valgrind/vki/vki-amd64-linux.h
  /usr/local/include/valgrind/vki/vki-arm-linux.h
  /usr/local/include/valgrind/vki/vki-arm64-linux.h
  /usr/local/include/valgrind/vki/vki-darwin.h
  /usr/local/include/valgrind/vki/vki-linux-drm.h
  /usr/local/include/valgrind/vki/vki-linux.h
  /usr/local/include/valgrind/vki/vki-mips32-linux.h
  /usr/local/include/valgrind/vki/vki-mips64-linux.h
  /usr/local/include/valgrind/vki/vki-posixtypes-amd64-linux.h
  /usr/local/include/valgrind/vki/vki-posixtypes-arm-linux.h
  /usr/local/include/valgrind/vki/vki-posixtypes-arm64-linux.h
  /usr/local/include/valgrind/vki/vki-posixtypes-mips32-linux.h
  /usr/local/include/valgrind/vki/vki-posixtypes-mips64-linux.h
  /usr/local/include/valgrind/vki/vki-posixtypes-ppc32-linux.h
  /usr/local/include/valgrind/vki/vki-posixtypes-ppc64-linux.h
  /usr/local/include/valgrind/vki/vki-posixtypes-s390x-linux.h
  /usr/local/include/valgrind/vki/vki-posixtypes-x86-linux.h
  /usr/local/include/valgrind/vki/vki-ppc32-linux.h
  /usr/local/include/valgrind/vki/vki-ppc64-linux.h
  /usr/local/include/valgrind/vki/vki-s390x-linux.h
  /usr/local/include/valgrind/vki/vki-scnums-amd64-linux.h
  /usr/local/include/valgrind/vki/vki-scnums-arm-linux.h
  /usr/local/include/valgrind/vki/vki-scnums-arm64-linux.h
  /usr/local/include/valgrind/vki/vki-scnums-darwin.h
  /usr/local/include/valgrind/vki/vki-scnums-mips32-linux.h
  /usr/local/include/valgrind/vki/vki-scnums-mips64-linux.h
  /usr/local/include/valgrind/vki/vki-scnums-ppc32-linux.h
  /usr/local/include/valgrind/vki/vki-scnums-ppc64-linux.h
  /usr/local/include/valgrind/vki/vki-scnums-s390x-linux.h
  /usr/local/include/valgrind/vki/vki-scnums-solaris.h
  /usr/local/include/valgrind/vki/vki-scnums-x86-linux.h
  /usr/local/include/valgrind/vki/vki-solaris-repcache.h
  /usr/local/include/valgrind/vki/vki-solaris.h
  /usr/local/include/valgrind/vki/vki-x86-linux.h
  /usr/local/include/valgrind/vki/vki-xen-domctl.h
  /usr/local/include/valgrind/vki/vki-xen-evtchn.h
  /usr/local/include/valgrind/vki/vki-xen-gnttab.h
  /usr/local/include/valgrind/vki/vki-xen-hvm.h
  /usr/local/include/valgrind/vki/vki-xen-memory.h
  /usr/local/include/valgrind/vki/vki-xen-mmuext.h
  /usr/local/include/valgrind/vki/vki-xen-physdev.h
  /usr/local/include/valgrind/vki/vki-xen-schedop.h
  /usr/local/include/valgrind/vki/vki-xen-sysctl.h
  /usr/local/include/valgrind/vki/vki-xen-tmem.h
  /usr/local/include/valgrind/vki/vki-xen-version.h
  /usr/local/include/valgrind/vki/vki-xen-x86.h
  /usr/local/include/valgrind/vki/vki-xen-xsm.h
  /usr/local/include/valgrind/vki/vki-xen.h
  /usr/local/include/xalloc-oversized.h
  /usr/local/include/xalloc.h
  /usr/local/include/zproc.h
  /usr/local/include/ztrie.h

Warning: Unbrewed .la files were found in /usr/local/lib.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected .la files:
  /usr/local/lib/libaspell.la
  /usr/local/lib/libbitcoin-client.la
  /usr/local/lib/libbitcoin-explorer.la
  /usr/local/lib/libbitcoin.la
  /usr/local/lib/libgdsl.la
  /usr/local/lib/libpspell.la
  /usr/local/lib/libsbuf.la
  /usr/local/lib/libsecp256k1.la

Warning: Unbrewed .pc files were found in /usr/local/lib/pkgconfig.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected .pc files:
  /usr/local/lib/pkgconfig/aubio.pc
  /usr/local/lib/pkgconfig/blkid.pc
  /usr/local/lib/pkgconfig/com_err.pc
  /usr/local/lib/pkgconfig/e2p.pc
  /usr/local/lib/pkgconfig/ext2fs.pc
  /usr/local/lib/pkgconfig/fuse-ext2.pc
  /usr/local/lib/pkgconfig/jack.pc
  /usr/local/lib/pkgconfig/libbitcoin-client.pc
  /usr/local/lib/pkgconfig/libbitcoin-explorer.pc
  /usr/local/lib/pkgconfig/libbitcoin.pc
  /usr/local/lib/pkgconfig/libsecp256k1.pc
  /usr/local/lib/pkgconfig/ss.pc
  /usr/local/lib/pkgconfig/valgrind.pc

Warning: Unbrewed static libraries were found in /usr/local/lib.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected static libraries:
  /usr/local/lib/libargp.a
  /usr/local/lib/libaubio.a
  /usr/local/lib/libbitcoin-client.a
  /usr/local/lib/libbitcoin-explorer.a
  /usr/local/lib/libbitcoin.a
  /usr/local/lib/libboost_locale.a
  /usr/local/lib/libboost_thread.a
  /usr/local/lib/libcpp.a
  /usr/local/lib/libdatastruct.a
  /usr/local/lib/libgdsl.a
  /usr/local/lib/libmemstream.a
  /usr/local/lib/libsbuf.a
  /usr/local/lib/libsecp256k1.a
  /usr/local/lib/libsptr.a
Error: No such file or directory @ dir_s_mkdir - /var/folders/sh/xb5grs3d247c0cxy_7s57_2r0000gk/T/brewdo.KDmiNgiH/Library/Caches/Homebrew/.d20181005-33089-13mtah4
```

No idea what the last error is about in `doctor`... very strange!

**Comment by fxcoudert** [comment]
Can you rerun with `--debug`?

**Comment by alexreg** [comment]
Aha, permissions error. Looks like things got changed upgrading to Mojave? What do you recommend?

```
==> Postinstalling libepoxy
Warning: The post-install step did not complete successfully
You can try again using `brew postinstall libepoxy`
==> An exception occured within a child process:
  Errno::EACCES: Permission denied @ dir_s_mkdir - 
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/fileutils.rb:254:in `mkdir'
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/fileutils.rb:254:in `fu_mkdir'
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/fileutils.rb:228:in `block (2 levels) in mkdir_p'
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/fileutils.rb:226:in `reverse_each'
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/fileutils.rb:226:in `block in mkdir_p'
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/fileutils.rb:211:in `each'
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/fileutils.rb:211:in `mkdir_p'
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/pathname.rb:576:in `mkpath'
/usr/local/Homebrew/Library/Homebrew/formula_installer.rb:901:in `block in post_install'
/usr/local/Homebrew/Library/Homebrew/utils/fork.rb:38:in `block (3 levels) in safe_fork'
/usr/local/Homebrew/Library/Homebrew/utils/fork.rb:32:in `fork'
/usr/local/Homebrew/Library/Homebrew/utils/fork.rb:32:in `block (2 levels) in safe_fork'
/usr/local/Homebrew/Library/Homebrew/utils/fork.rb:29:in `open'
/usr/local/Homebrew/Library/Homebrew/utils/fork.rb:29:in `block in safe_fork'
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/tmpdir.rb:89:in `mktmpdir'
/usr/local/Homebrew/Library/Homebrew/utils/fork.rb:28:in `safe_fork'
/usr/local/Homebrew/Library/Homebrew/formula_installer.rb:898:in `post_install'
/usr/local/Homebrew/Library/Homebrew/cmd/postinstall.rb:14:in `block in postinstall'
/usr/local/Homebrew/Library/Homebrew/cmd/postinstall.rb:11:in `each'
/usr/local/Homebrew/Library/Homebrew/cmd/postinstall.rb:11:in `postinstall'
/usr/local/Homebrew/Library/Homebrew/brew.rb:91:in `<main>'
```

**Comment by fxcoudert** [comment]
Can you check that you own all Homebrew-related directories and files under `/usr/local`?

**Comment by alexreg** [comment]
I use (and maintain) brewdo, so it's the `_homebrew` user, but here's my `ls -la`.

```
drwxr-xr-x    26 root       wheel        832  5 Oct 16:59 .
drwxr-xr-x@   10 root       wheel        320  5 Oct 16:55 ..
-rw-r--r--     1 root       wheel          0 17 Jul 22:50 .com.apple.installer.keep
drwxr-xr-x    24 _homebrew  wheel        768  5 Oct 17:00 Caskroom
drwxr-xr-x   351 _homebrew  _homebrew  11232  5 Oct 17:00 Cellar
drwxr-xr-x     3 _homebrew  wheel         96  5 Oct 16:58 Frameworks
drwxr-xr-x    20 _homebrew  wheel        640  5 Oct 17:00 Homebrew
drwxr-xr-x     8 _homebrew  wheel        256  5 Oct 17:00 Library
drwxr-xr-x     7 root       wheel        224  5 Oct 16:59 MacGPG2
drwxr-xr-x     3 root       admin         96  5 Oct 16:53 OpenSourceVersions
drwxr-xr-x  1966 _homebrew  wheel      62912  5 Oct 18:53 bin
drwxr-xr-x     3 root       wheel         96  5 Oct 16:57 cuda
drwxr-xr-x     7 root       admin        224  5 Oct 16:57 dyndns
drwxrwxr-x    58 _homebrew  wheel       1856  5 Oct 16:59 etc
drwxr-xr-x     8 root       admin        256  5 Oct 16:58 git
drwxrwxr-x   429 _homebrew  wheel      13728  5 Oct 18:53 include
drwxrwxr-x  1268 _homebrew  wheel      40576  5 Oct 18:53 lib
drwxrwxr-x     4 _homebrew  wheel        128  5 Oct 16:56 libexec
drwxr-xr-x     7 root       wheel        224  5 Oct 17:00 lmm
lrwxr-xr-x     1 499        admin          9 25 Nov  2013 man -> share/man
drwxrwxr-x   389 _homebrew  wheel      12448  5 Oct 18:53 opt
drwxr-xr-x     3 root       admin         96  5 Oct 16:59 remotedesktop
drwxr-xr-x     5 _homebrew  wheel        160  5 Oct 16:58 sbin
drwxrwxr-x   106 _homebrew  wheel       3392  5 Oct 17:00 share
drwxr-xr-x     4 root       admin        128  5 Oct 16:59 texlive
drwxrwxr-x    15 _homebrew  wheel        480  5 Oct 16:59 var
```

**Comment by fxcoudert** [comment]
I am not sure what is `brewdo`, but it may be the root of the issue. We haven't had any other report like this. Also, the large number of warnings in `brew doctor` indicate that there is something weird going on in your system.

Can you reproduce on a clean install?

**Comment by alexreg** [comment]
I don't have the ability to test with a clean installation. In any case, the `brew doctor` issues are not so concerning, since they are all clearly due to other software installing in `/usr/local` (which is acceptable, since it's where most 3rd-party software that is not an app should go).

Here is [brewdo](https://github.com/brewdo/brewdo).
