### ISSUE TITLE
Cleanup Crash: unknown version :x86_64_linux

### ISSUE THREAD

**Issue by MikelArdanaz** [Homebrew/homebrew-core#33304]
I have a problem after running `brew cleanup`. This issue appeared previously at #33220. I have already run `brew update` 2x and `brew doctor`.

Here is the output of `brew cleanup`:

```
Error: unknown version :x86_64_linux
Please report this bug:
  https://docs.brew.sh/Troubleshooting
/usr/local/Homebrew/Library/Homebrew/os/mac/version.rb:23:in `block in from_symbol'
/usr/local/Homebrew/Library/Homebrew/os/mac/version.rb:22:in `fetch'
/usr/local/Homebrew/Library/Homebrew/os/mac/version.rb:22:in `from_symbol'
/usr/local/Homebrew/Library/Homebrew/extend/os/mac/utils/bottles.rb:60:in `block in find_older_compatible_tag'
/usr/local/Homebrew/Library/Homebrew/extend/os/mac/utils/bottles.rb:53:in `each'
/usr/local/Homebrew/Library/Homebrew/extend/os/mac/utils/bottles.rb:53:in `find'
/usr/local/Homebrew/Library/Homebrew/extend/os/mac/utils/bottles.rb:53:in `find_older_compatible_tag'
/usr/local/Homebrew/Library/Homebrew/extend/os/mac/utils/bottles.rb:31:in `find_matching_tag'
/usr/local/Homebrew/Library/Homebrew/utils/bottles.rb:94:in `fetch_checksum_for'
/usr/local/Homebrew/Library/Homebrew/software_spec.rb:381:in `checksum_for'
/usr/local/Homebrew/Library/Homebrew/software_spec.rb:368:in `tag?'
/usr/local/Homebrew/Library/Homebrew/software_spec.rb:96:in `bottled?'
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/forwardable.rb:202:in `bottled?'
/usr/local/Homebrew/Library/Homebrew/formula.rb:343:in `bottle'
/usr/local/Homebrew/Library/Homebrew/utils/bottles.rb:20:in `file_outdated?'
/usr/local/Homebrew/Library/Homebrew/cleanup.rb:106:in `stale_formula?'
/usr/local/Homebrew/Library/Homebrew/cleanup.rb:60:in `stale?'
/usr/local/Homebrew/Library/Homebrew/cleanup.rb:264:in `block in cleanup_cache'
/usr/local/Homebrew/Library/Homebrew/cleanup.rb:250:in `each'
/usr/local/Homebrew/Library/Homebrew/cleanup.rb:250:in `cleanup_cache'
/usr/local/Homebrew/Library/Homebrew/cleanup.rb:192:in `cleanup_formula'
/usr/local/Homebrew/Library/Homebrew/cleanup.rb:156:in `block in clean!'
/usr/local/Homebrew/Library/Homebrew/cleanup.rb:155:in `each'
/usr/local/Homebrew/Library/Homebrew/cleanup.rb:155:in `clean!'
/usr/local/Homebrew/Library/Homebrew/cmd/cleanup.rb:30:in `cleanup'
/usr/local/Homebrew/Library/Homebrew/brew.rb:89:in `<main>'
```

And here is my `brew config`:

HOMEBREW_VERSION: 1.8.0
ORIGIN: https://github.com/Homebrew/brew
HEAD: fdd8e9b7cf1e53322492e1e90f685c19bdfde506
Last commit: 2 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 40239659c89eacc57883a80919d809ee7fa39221
Core tap last commit: 40 minutes ago
HOMEBREW_PREFIX: /usr/local
CPU: quad-core 64-bit haswell
Homebrew Ruby: 2.3.7 => /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/bin/ruby
Clang: 10.0 build 1000
Git: 2.17.1 => /Applications/Xcode.app/Contents/Developer/usr/bin/git
Curl: 7.54.0 => /usr/bin/curl
Java: 1.8.0_60
macOS: 10.14-x86_64
CLT: 10.0.0.0.1.1535735448
Xcode: 10.0
XQuartz: 2.7.11 => /opt/X11

**Comment by fxcoudert** [comment]
What is the output of `brew doctor`?

**Comment by MikelArdanaz** [comment]
Here is the output:
```
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: "config" scripts exist outside your system or Homebrew directories.
`./configure` scripts often look for *-config scripts to determine if
software packages are installed, and what additional flags to use when
compiling and linking.

Having additional scripts in your path can confuse software installed via
Homebrew if the config script overrides a system or Homebrew provided
script of the same name. We found the following "config" scripts:
  /opt/local/bin/pkg-config
  /opt/local/bin/MagickCore-config
  /opt/local/bin/MagickWand-config
  /opt/local/bin/freetype-config
  /opt/local/bin/libpng16-config
  /opt/local/bin/python2.7-config
  /opt/local/bin/Magick++-config
  /opt/local/bin/libpng-config
  /opt/local/bin/xml2-config
  /opt/local/bin/ncursesw6-config
  /opt/local/bin/Wand-config
  /opt/local/bin/Magick-config
  /opt/local/bin/uuid-config
  /opt/local/bin/pcre-config
  /opt/local/bin/ncurses6-config
  /Library/Frameworks/Python.framework/Versions/3.6/bin/python3.6m-config
  /Library/Frameworks/Python.framework/Versions/3.6/bin/python3-config
  /Library/Frameworks/Python.framework/Versions/3.6/bin/python3.6-config
  //anaconda/bin/libdynd-config
  //anaconda/bin/python2-config
  //anaconda/bin/freetype-config
  //anaconda/bin/xslt-config
  //anaconda/bin/libpng16-config
  //anaconda/bin/python2.7-config
  //anaconda/bin/libpng-config
  //anaconda/bin/xml2-config
  //anaconda/bin/powerline-config
  //anaconda/bin/python-config
  //anaconda/bin/curl-config

Warning: You have MacPorts or Fink installed:
  /opt/local/bin/port

This can cause trouble. You don't have to uninstall them, but you may want to
temporarily move them out of the way, e.g.

  sudo mv /opt/local ~/macports

Warning: You have unlinked kegs in your Cellar
Leaving kegs unlinked can lead to build-trouble and cause brews that depend on
those kegs to fail to run properly once built. Run `brew link` on these:
  libzmq
```

**Comment by MikeMcQuaid** [comment]
This is now fixed, please `brew update`.
