### ISSUE TITLE
zanata-client is not compatible with java > 1.8

### ISSUE THREAD

**Issue by bendem** [Homebrew/homebrew-core#33480]
- [x] are reporting a bug others will be able to reproduce and not asking a question. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh
- [ ] have a problem with `brew install` (or `upgrade`, `reinstall`) a single, official formula (not cask)? If it's a general `brew` problem please file this issue at Homebrew/brew: https://github.com/Homebrew/brew/issues/new/choose. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/homebrew-cask/issues/new/choose. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [x] ran `brew update` and can still reproduce the problem?
- [ ] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [ ] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [ ] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

To help us debug your issue please explain:
- What you were trying to do (and why)
I tried to use any functionality of the program except help
- What happened (include command output)
```
[ERROR] Execution failed:
javax.xml.bind.JAXBException
 - with linked exception:
[java.lang.ClassNotFoundException: com.sun.xml.internal.bind.v2.ContextFactory]
	at javax.xml.bind.ContextFinder.newInstance(ContextFinder.java:241)
	at javax.xml.bind.ContextFinder.find(ContextFinder.java:477)
	at javax.xml.bind.JAXBContext.newInstance(JAXBContext.java:656)
	at javax.xml.bind.JAXBContext.newInstance(JAXBContext.java:599)
	at org.zanata.client.commands.OptionsUtil.readProjectConfigFile(OptionsUtil.java:157)
	at org.zanata.client.commands.OptionsUtil.applyProjectConfigToProjectOptions(OptionsUtil.java:87)
	at org.zanata.client.commands.OptionsUtil.applyConfigFiles(OptionsUtil.java:55)
	at org.zanata.client.commands.ArgsUtil.runCommand(ArgsUtil.java:42)
	at org.zanata.client.ZanataClient.processArgs(ZanataClient.java:182)
	at org.zanata.client.ZanataClient.main(ZanataClient.java:103)
Caused by: java.lang.ClassNotFoundException: com.sun.xml.internal.bind.v2.ContextFactory
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:583)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
	at javax.xml.bind.ContextFinder.safeLoadClass(ContextFinder.java:594)
	at javax.xml.bind.ContextFinder.newInstance(ContextFinder.java:239)
	... 9 more
```
- What you expected to happen
The program to work, or at least pick use the JAVA_HOME I have set instead of overriding it.
(This is very wrong, it overrides the variable that's specifically used to prevent this very problem from happning):
```
       │ File: /usr/local/bin/zanata-cli
───────┼───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
   1   │ #!/bin/bash
   2   │ JAVA_HOME="$(/usr/libexec/java_home --version 1.8+)" exec "/usr/local/Cellar/zanata-client/4.6.2/libexec/bin/zanata-cli" "$@"
```

- Step-by-step reproduction instructions (by running `brew install` commands)
Run any command doing actual work with a version of java higher than 8, see the error.

- Additional notes
I can provide a fix by `s/1\.8\+/1.8/`, but there is a fundamental problem with the way that script is generated. `JAVA_HOME` should not get overridden if it's already set.

**Comment by apjanke** [comment]
I can't reproduce because I don't have Zanata set up to exercise its features, but I'm happy to take your word on this. We've seen similar errors at https://github.com/Homebrew/homebrew-core/issues/28760.

Here's a PR to fix: https://github.com/Homebrew/homebrew-core/pull/33500

> JAVA_HOME should not get overridden if it's already set.

This is intentional. Homebrew's view is that the Java version required by a Java application (as opposed to a library) is an internal implementation detail, and should be handled entirely by the application installation. `JAVA_HOME` is more of a developer control, and we think that Java apps should work regardless of its setting, especially since a user might have a mix of applications that require different incompatible Java versions.

**Comment by bendem** [comment]
Alright, I understand the rational from a software packaging standpoint. Thanks for the quick reaction and fixes!
