### ISSUE TITLE
python2 and python3 install fail with undefined method `sdk_path_if_needed' for OS::Mac:Module error

### ISSUE THREAD

**Issue by noworries883** [Homebrew/homebrew-core#33949]
trying to install python3 on macos High Sierra and getting this error : 
undefined method `sdk_path_if_needed' for OS::Mac:Module

==> Installing python
==> Downloading https://www.python.org/ftp/python/3.7.1/Python-3.7.1.tar.xz
######################################################################## 100.0%
Error: undefined method `sdk_path_if_needed' for OS::Mac:Module
Please report this bug:
  https://docs.brew.sh/Troubleshooting
/usr/local/homebrew/Library/Taps/homebrew/homebrew-core/Formula/python.rb:91:in `install'
/usr/local/homebrew/Library/Homebrew/build.rb:142:in `block (2 levels) in install'
/usr/local/homebrew/Library/Homebrew/formula.rb:1116:in `block in brew'
/usr/local/homebrew/Library/Homebrew/formula.rb:1957:in `block (2 levels) in stage'
/usr/local/homebrew/Library/Homebrew/utils.rb:556:in `with_env'
/usr/local/homebrew/Library/Homebrew/formula.rb:1956:in `block in stage'
/usr/local/homebrew/Library/Homebrew/resource.rb:119:in `block in unpack'
/usr/local/homebrew/Library/Homebrew/extend/fileutils.rb:13:in `block in mktemp'
/usr/local/homebrew/Library/Homebrew/extend/fileutils.rb:73:in `block in run'
/usr/local/homebrew/Library/Homebrew/extend/fileutils.rb:73:in `chdir'
/usr/local/homebrew/Library/Homebrew/extend/fileutils.rb:73:in `run'
/usr/local/homebrew/Library/Homebrew/extend/fileutils.rb:12:in `mktemp'
/usr/local/homebrew/Library/Homebrew/resource.rb:114:in `unpack'
/usr/local/homebrew/Library/Homebrew/resource.rb:92:in `stage'
/usr/local/homebrew/Library/Homebrew/formula.rb:1934:in `stage'
/usr/local/homebrew/Library/Homebrew/formula.rb:1111:in `brew'
/usr/local/homebrew/Library/Homebrew/build.rb:113:in `block in install'
/usr/local/homebrew/Library/Homebrew/utils.rb:556:in `with_env'
/usr/local/homebrew/Library/Homebrew/build.rb:110:in `install'
/usr/local/homebrew/Library/Homebrew/build.rb:191:in `<main>'

Same with python2 which is a dependency of mongoDB when I try to upgrade mongodb.

I think it is related to this issue : https://github.com/Linuxbrew/homebrew-core/pull/9073/commits/3fdb03a5c291370262bc74e4c121ea53fb9acec5

**Comment by fxcoudert** [comment]
Please fill in the full issue template, otherwise there is really nothing we can do to help.

**Comment by noworries883** [comment]
Sorry I am a newbie.
I ran `brew update`
I ran `brew doctor` and fixed all I could

By the time I fixed the problem and was able to install python3 successfully : 
In the homebrew-core/Formula/python.rb,
line 91 is 
`if MacOS.sdk_path_if_needed`
and I replaced it by 
`if OS.mac? && MacOS.sdk_path`

Same fix is needed in homebrew-core/Formula/python@2.rb line 108

Hope this helps, let me know if you need more information

For the record
result of `brew config`
```
HOMEBREW_VERSION: 1.6.9
ORIGIN: https://github.com/Homebrew/brew.git
HEAD: c814199a791867ab75f90a22715e2475706b13d8
Last commit: 5 months ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 8c4f8922934ac829c5f4edcdb5d37615d021535d
Core tap last commit: 55 minutes ago
HOMEBREW_PREFIX: /usr/local/homebrew
HOMEBREW_REPOSITORY: /usr/local/homebrew
HOMEBREW_CELLAR: /usr/local/homebrew/Cellar
HOMEBREW_GITHUB_API_TOKEN: set
CPU: 12-core 64-bit kabylake
Homebrew Ruby: 2.3.3 => /usr/local/homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3_2/bin/ruby
Clang: 10.0 build 1000
Git: 2.17.2 => /Applications/Xcode.app/Contents/Developer/usr/bin/git
Curl: 7.54.0 => /usr/bin/curl
Java: 11.0.1, 1.8.0_171, 1.8.0_151, 1.8.0_111, 1.7.0_51
macOS: 10.13.6-x86_64
CLT: 10.1.0.0.1.1539992718
Xcode: 10.1
XQuartz: 2.7.11 => /opt/X11
```
result of `brew gist-logs python3` : 
https://gist.github.com/2276dd10ab40e36687b6575189e8d8a2

result of brew doctor
```
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: Unbrewed dylibs were found in /usr/local/lib.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected dylibs:
  /usr/local/lib/libqmi_api.dylib

Warning: Unbrewed header files were found in /usr/local/include.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected header files:
  /usr/local/include/node/android-ifaddrs.h
  /usr/local/include/node/ares.h
  /usr/local/include/node/ares_build.h
  /usr/local/include/node/ares_rules.h
  /usr/local/include/node/ares_version.h
  /usr/local/include/node/libplatform/libplatform.h
  /usr/local/include/node/nameser.h
  /usr/local/include/node/node.h
  /usr/local/include/node/node_buffer.h
  /usr/local/include/node/node_object_wrap.h
  /usr/local/include/node/node_version.h
  /usr/local/include/node/openssl/aes.h
  /usr/local/include/node/openssl/archs/BSD-x86/opensslconf.h
  /usr/local/include/node/openssl/archs/BSD-x86_64/opensslconf.h
  /usr/local/include/node/openssl/archs/VC-WIN32/opensslconf.h
  /usr/local/include/node/openssl/archs/VC-WIN64A/opensslconf.h
  /usr/local/include/node/openssl/archs/aix-gcc/opensslconf.h
  /usr/local/include/node/openssl/archs/aix64-gcc/opensslconf.h
  /usr/local/include/node/openssl/archs/darwin-i386-cc/opensslconf.h
  /usr/local/include/node/openssl/archs/darwin64-x86_64-cc/opensslconf.h
  /usr/local/include/node/openssl/archs/linux-aarch64/opensslconf.h
  /usr/local/include/node/openssl/archs/linux-armv4/opensslconf.h
  /usr/local/include/node/openssl/archs/linux-elf/opensslconf.h
  /usr/local/include/node/openssl/archs/linux-ppc/opensslconf.h
  /usr/local/include/node/openssl/archs/linux-ppc64/opensslconf.h
  /usr/local/include/node/openssl/archs/linux-x32/opensslconf.h
  /usr/local/include/node/openssl/archs/linux-x86_64/opensslconf.h
  /usr/local/include/node/openssl/archs/linux32-s390x/opensslconf.h
  /usr/local/include/node/openssl/archs/linux64-s390x/opensslconf.h
  /usr/local/include/node/openssl/archs/solaris-x86-gcc/opensslconf.h
  /usr/local/include/node/openssl/archs/solaris64-x86_64-gcc/opensslconf.h
  /usr/local/include/node/openssl/asn1.h
  /usr/local/include/node/openssl/asn1_mac.h
  /usr/local/include/node/openssl/asn1t.h
  /usr/local/include/node/openssl/bio.h
  /usr/local/include/node/openssl/blowfish.h
  /usr/local/include/node/openssl/bn.h
  /usr/local/include/node/openssl/buffer.h
  /usr/local/include/node/openssl/camellia.h
  /usr/local/include/node/openssl/cast.h
  /usr/local/include/node/openssl/cmac.h
  /usr/local/include/node/openssl/cms.h
  /usr/local/include/node/openssl/comp.h
  /usr/local/include/node/openssl/conf.h
  /usr/local/include/node/openssl/conf_api.h
  /usr/local/include/node/openssl/crypto.h
  /usr/local/include/node/openssl/des.h
  /usr/local/include/node/openssl/des_old.h
  /usr/local/include/node/openssl/dh.h
  /usr/local/include/node/openssl/dsa.h
  /usr/local/include/node/openssl/dso.h
  /usr/local/include/node/openssl/dtls1.h
  /usr/local/include/node/openssl/e_os2.h
  /usr/local/include/node/openssl/ebcdic.h
  /usr/local/include/node/openssl/ec.h
  /usr/local/include/node/openssl/ecdh.h
  /usr/local/include/node/openssl/ecdsa.h
  /usr/local/include/node/openssl/engine.h
  /usr/local/include/node/openssl/err.h
  /usr/local/include/node/openssl/evp.h
  /usr/local/include/node/openssl/hmac.h
  /usr/local/include/node/openssl/idea.h
  /usr/local/include/node/openssl/krb5_asn.h
  /usr/local/include/node/openssl/kssl.h
  /usr/local/include/node/openssl/lhash.h
  /usr/local/include/node/openssl/md4.h
  /usr/local/include/node/openssl/md5.h
  /usr/local/include/node/openssl/mdc2.h
  /usr/local/include/node/openssl/modes.h
  /usr/local/include/node/openssl/obj_mac.h
  /usr/local/include/node/openssl/objects.h
  /usr/local/include/node/openssl/ocsp.h
  /usr/local/include/node/openssl/opensslconf.h
  /usr/local/include/node/openssl/opensslv.h
  /usr/local/include/node/openssl/ossl_typ.h
  /usr/local/include/node/openssl/pem.h
  /usr/local/include/node/openssl/pem2.h
  /usr/local/include/node/openssl/pkcs12.h
  /usr/local/include/node/openssl/pkcs7.h
  /usr/local/include/node/openssl/pqueue.h
  /usr/local/include/node/openssl/rand.h
  /usr/local/include/node/openssl/rc2.h
  /usr/local/include/node/openssl/rc4.h
  /usr/local/include/node/openssl/ripemd.h
  /usr/local/include/node/openssl/rsa.h
  /usr/local/include/node/openssl/safestack.h
  /usr/local/include/node/openssl/seed.h
  /usr/local/include/node/openssl/sha.h
  /usr/local/include/node/openssl/srp.h
  /usr/local/include/node/openssl/srtp.h
  /usr/local/include/node/openssl/ssl.h
  /usr/local/include/node/openssl/ssl2.h
  /usr/local/include/node/openssl/ssl23.h
  /usr/local/include/node/openssl/ssl3.h
  /usr/local/include/node/openssl/stack.h
  /usr/local/include/node/openssl/symhacks.h
  /usr/local/include/node/openssl/tls1.h
  /usr/local/include/node/openssl/ts.h
  /usr/local/include/node/openssl/txt_db.h
  /usr/local/include/node/openssl/ui.h
  /usr/local/include/node/openssl/ui_compat.h
  /usr/local/include/node/openssl/whrlpool.h
  /usr/local/include/node/openssl/x509.h
  /usr/local/include/node/openssl/x509_vfy.h
  /usr/local/include/node/openssl/x509v3.h
  /usr/local/include/node/pthread-barrier.h
  /usr/local/include/node/pthread-fixes.h
  /usr/local/include/node/stdint-msvc2008.h
  /usr/local/include/node/tree.h
  /usr/local/include/node/uv-aix.h
  /usr/local/include/node/uv-bsd.h
  /usr/local/include/node/uv-darwin.h
  /usr/local/include/node/uv-errno.h
  /usr/local/include/node/uv-linux.h
  /usr/local/include/node/uv-sunos.h
  /usr/local/include/node/uv-threadpool.h
  /usr/local/include/node/uv-unix.h
  /usr/local/include/node/uv-version.h
  /usr/local/include/node/uv-win.h
  /usr/local/include/node/uv.h
  /usr/local/include/node/v8-debug.h
  /usr/local/include/node/v8-experimental.h
  /usr/local/include/node/v8-platform.h
  /usr/local/include/node/v8-profiler.h
  /usr/local/include/node/v8-testing.h
  /usr/local/include/node/v8-util.h
  /usr/local/include/node/v8-version.h
  /usr/local/include/node/v8.h
  /usr/local/include/node/v8config.h
  /usr/local/include/node/zconf.h
  /usr/local/include/node/zlib.h

Warning: Your Homebrew's prefix is not /usr/local.
You can install Homebrew anywhere you want but some bottles (binary packages)
can only be used with a /usr/local prefix and some formulae (packages)
may not build correctly with a non-/usr/local prefix.
```

**Comment by fxcoudert** [comment]
Your problem comes from `HOMEBREW_VERSION: 1.6.9`. You are running a very old version of `brew`, with the latest version of the core formulas.

Running `brew update-reset` should get you back on your feet.

**Comment by noworries883** [comment]
thanks, it fixed the problem !

this command should be added int the troubleshooting section :-)
