### ISSUE TITLE
Can't install *any* package on macOS Sierra

### ISSUE THREAD

**Issue by ELLIOTTCABLE** [Homebrew/homebrew-core#3454]
So, I'm unable to install *any* package. Here's a few examples:

#### `gcc`
```
> brew upgrade gcc
Warning: You are using OS X 10.12.
We do not provide support for this pre-release version.
You may encounter build failures or other breakages.
Please create pull-requests instead of filing issues.
==> Upgrading 1 outdated package, with result:
gcc 6.1.0
==> Upgrading gcc
==> Installing dependencies for gcc: gmp, mpfr, isl
==> Installing gcc dependency: gmp
==> Downloading https://gmplib.org/download/gmp/gmp-6.1.1.tar.xz
######################################################################## 100.0%
==> ./configure --prefix=/usr/local/Cellar/gmp/6.1.1 --enable-cxx
Last 15 lines from /Users/ec/Library/Logs/Homebrew/gmp/01.configure:
checking for awk... awk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking whether to enable maintainer-specific portions of Makefiles... no
checking ABI=64
checking whether clang is gcc... yes
checking compiler clang -O2 -pedantic -fomit-frame-pointer -m64 ... no, gnupro alpha ev6 char spilling
checking ABI=x32
checking whether clang is gcc... yes
checking compiler clang -O2 -pedantic -fomit-frame-pointer -mx32 ... no, gnupro alpha ev6 char spilling
checking ABI=32
checking whether clang is gcc... yes
checking compiler clang -m32 -O2 -pedantic -fomit-frame-pointer ... no, gnupro alpha ev6 char spilling
checking compiler clang -O2 -pedantic -fomit-frame-pointer ... no, gnupro alpha ev6 char spilling
configure: error: could not find a working compiler, see config.log for details

READ THIS: https://git.io/brew-troubleshooting
If reporting this issue please do so at (not Homebrew/brew):
  https://github.com/Homebrew/homebrew-core/issues

These open issues may also help:
Update missing gmp 6.1.0 file https://github.com/Homebrew/homebrew-core/issues/1053
```

#### `boost`
```
> brew upgrade boost
Warning: You are using OS X 10.12.
We do not provide support for this pre-release version.
You may encounter build failures or other breakages.
Please create pull-requests instead of filing issues.
==> Upgrading 1 outdated package, with result:
boost 1.60.0_2
==> Upgrading boost
==> Downloading https://downloads.sourceforge.net/project/boost/boost/1.60.0/boost_1_60_0.tar.bz2
Already downloaded: /Users/ec/Library/Caches/Homebrew/boost-1.60.0.tar.bz2
==> Downloading https://raw.githubusercontent.com/Homebrew/formula-patches/9e56b45/boost/boost1_60_0_python_class_metadata.diff
Already downloaded: /Users/ec/Library/Caches/Homebrew/boost--patch-1a470c3a2738af409f68e3301eaecd8d07f27a8965824baf8aee0adef463b844.diff
==> Patching
patching file boost/graph/adjacency_matrix.hpp
==> Applying boost1_60_0_python_class_metadata.diff
patching file boost/python/object/class_metadata.hpp
==> ./bootstrap.sh --prefix=/usr/local/Cellar/boost/1.60.0_2 --libdir=/usr/local/Cellar/boost/1.60.0_2/lib --without-icu --without-libr
Last 15 lines from /Users/ec/Library/Logs/Homebrew/boost/01.bootstrap.sh:
2016-07-30 04:59:45 -0500

./bootstrap.sh
--prefix=/usr/local/Cellar/boost/1.60.0_2
--libdir=/usr/local/Cellar/boost/1.60.0_2/lib
--without-icu
--without-libraries=python,mpi

Building Boost.Build engine with toolset darwin... 
Failed to build Boost.Build build engine
Consult 'bootstrap.log' for more details

READ THIS: https://git.io/brew-troubleshooting
If reporting this issue please do so at (not Homebrew/brew):
  https://github.com/Homebrew/homebrew-core/issues

These open issues may also help:
boost and log4cxx --HEAD https://github.com/Homebrew/homebrew-core/pull/2843
boost, boost-python 1.61.0 https://github.com/Homebrew/homebrew-core/pull/1200
```

#### `reattach-to-user-namespace`
```
Warning: You are using OS X 10.12.
We do not provide support for this pre-release version.
You may encounter build failures or other breakages.
Please create pull-requests instead of filing issues.
==> Downloading https://github.com/ChrisJohnsen/tmux-MacOSX-pasteboard/archive/v2.4.tar.gz
Already downloaded: /Users/ec/Library/Caches/Homebrew/reattach-to-user-namespace-2.4.tar.gz
==> make
Last 15 lines from /Users/ec/Library/Logs/Homebrew/reattach-to-user-namespace/01.make:
         ^
1 error generated.
reattach-to-user-namespace.c:32:10: fatal error: 'string.h' file not found
#include <string.h>    /* strlen, strcpy, strcmp, strrchr */
         ^
1 error generated.
move_to_user_namespace.c:2:10: fatal error: 'stdlib.h' file not found
#include <stdlib.h>
         ^
make: *** [msg.o] Error 1
make: *** Waiting for unfinished jobs....
make: *** [test.o] Error 1
make: *** [reattach-to-user-namespace.o] Error 1
1 error generated.
make: *** [move_to_user_namespace.o] Error 1

READ THIS: https://git.io/brew-troubleshooting
If reporting this issue please do so at (not Homebrew/brew):
  https://github.com/Homebrew/homebrew-core/issues
```

I'm on either Beta 2 or Beta 3; due to an aborted recent attempt at updating, I'm not sure which. Unfortunately, I'm not even sure where to *start* trying to debug this; does anybody know what I could try fiddling with, that could be causing all sorts of compilation errors?

----

#### `brew doctor`
```
> brew doctor
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry and just ignore them. Thanks!

Warning: Your XQuartz (2.7.7) is outdated
Please install XQuartz 2.7.9:
  https://xquartz.macosforge.org

Warning: You have unlinked kegs in your Cellar
Leaving kegs unlinked can lead to build-trouble and cause brews that depend on
those kegs to fail to run properly once built. Run `brew link` on these:
    python3

Warning: You are using OS X 10.12.
We do not provide support for this pre-release version.
You may encounter build failures or other breakages.
Please create pull-requests instead of filing issues.

Warning: You have a curlrc file
If you have trouble downloading packages with Homebrew, then maybe this
is the problem? If the following command doesn't work, then try removing
your curlrc:
  curl https://github.com

Warning: Homebrew's sbin was not found in your PATH but you have installed
formulae that put executables in /usr/local/sbin.
Consider setting the PATH for example like so
  echo 'export PATH="/usr/local/sbin:$PATH"' >> ~/.zshrc

Warning: Your Xcode (7.3.1) is outdated
Please update to Xcode 8.0.
Xcode can be updated from
  https://developer.apple.com/xcode/downloads/

Warning: Calling Formula.sha1 is deprecated!
Use Formula.sha256 instead.
/usr/local/Library/Taps/nwoolls/homebrew-xgminer/cgminer.rb:7:in `<class:Cgminer>'

Warning: Calling SoftwareSpec#sha1 is deprecated!
Use SoftwareSpec#sha256 instead.
/usr/local/Library/Homebrew/compat/sha1.rb:4:in `sha1'

Warning: Calling Resource#sha1 is deprecated!
Use Resource#sha256 instead.
/usr/local/Library/Homebrew/compat/sha1.rb:11:in `sha1'


Warning: Some installed formula are missing dependencies.
You should `brew install` the missing dependencies:
  brew install gx gx-go texinfo

Run `brew missing` for more details.
```

**Comment by DomT4** [comment]
>  Warning: Your Xcode (7.3.1) is outdated
Please update to Xcode 8.0.
Xcode can be updated from
  https://developer.apple.com/xcode/downloads/

Xcode 7 doesn't have the 10.12 SDK, so everything breaking isn't a surprise. Update to the Xcode 8 beta & you should be alright. Please let us know if that doesn't prove the case and we'll be happy to take another look.

**Comment by arderyp** [comment]
I'm receiving lots of "Calling SoftwareSpec#sha1 is deprecated!" errors as well. Do we really need to upgrade to a beta to resolve it? Did it work for you @DomT4 ?

**Comment by DomT4** [comment]
@arderyp That's very much unrelated to the problem in this Issue. You may wish to glance through https://github.com/Homebrew/brew/issues/606 which details that change a little further.

**Comment by arderyp** [comment]
ahh, thanks!

**Comment by SomeGuy54321** [comment]
Last step here after installing Xcode 8.0 is to run this:
`ln -s /Applications/Xcode-beta.app /Applications/Xcode.app`
Seems that Homebrew searches only the path `/Applications/Xcode.app/` for its compilers and such, but Xcode 8.0 ATM creates `/Applications/Xcode-beta.app/`.

**Comment by DomT4** [comment]
That shouldn't be the case. Homebrew determines the developer tools path by using `xcode-select`, so you need to ensure you've `sudo xcode-select --switch`'d over to the beta Xcode. After that there shouldn't be any issues Homebrew's side.

Some upstreams hardcode in `/Applications/Xcode.app` as the search path which is another issue, but it's pretty rare these days.

**Comment by SomeGuy54321** [comment]
@DomT4 ya that explains it, I had Xcode7 installed then installed Xcode8.
