### ISSUE TITLE
Byobu - byobu-config does not work on OS X 10.14.2

### ISSUE THREAD

**Issue by anudeepsamaiya** [Homebrew/homebrew-core#35291]
**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [x] are reporting a bug others will be able to reproduce and not asking a question or requesting software. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh. To get software added or changed in Homebrew please file a [Pull Request](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)
- [ ] have a problem with `brew install` (or `upgrade`, `reinstall`) a single, official formula (not cask)? If it's a general `brew` problem please file this issue at Homebrew/brew: https://github.com/Homebrew/brew/issues/new/choose. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/homebrew-cask/issues/new/choose. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [x] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

## `brew config` output:
```
HOMEBREW_VERSION: 1.8.6
ORIGIN: https://github.com/Homebrew/brew
HEAD: 858c5e1afb0eb00079a4f014e8fbedf9065d50e4
Last commit: 4 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 1e763c8e81b8fc68b46b2a585c4b1c372581ea31
Core tap last commit: 5 hours ago
HOMEBREW_PREFIX: /usr/local
CPU: quad-core 64-bit broadwell
Homebrew Ruby: 2.3.7 => /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/bin/ruby
Clang: 10.0 build 1000
Git: 2.17.2 => /Library/Developer/CommandLineTools/usr/bin/git
Curl: 7.54.0 => /usr/bin/curl
macOS: 10.14.2-x86_64
CLT: 10.1.0.0.1.1539992718
Xcode: N/A
```
## `brew doctor` output:
```
anudeepsamaiya@orion:~$ brew doctor
Your system is ready to brew.
anudeepsamaiya@orion:~$
```

To help us debug your issue please explain:
- What you were trying to do (and why)
  I was trying to configure `byobu` using `byobu-config`
- What happened (include command output)
   The following output was thrown:
   ```
   ERROR: Could not import the python snack module
   ```
- What you expected to happen
   To have `byobu-config` screen available.
- Step-by-step reproduction instructions (by running `brew install` commands)
```
==> Installing dependencies for byobu: libpng
==> Installing byobu dependency: libpng
==> Downloading https://homebrew.bintray.com/bottles/libpng-1.6.36.mojave.bottle.tar.gz
######################################################################## 100.0%
==> Pouring libpng-1.6.36.mojave.bottle.tar.gz
🍺  /usr/local/Cellar/libpng/1.6.36: 27 files, 1.2MB
==> Installing byobu
==> Downloading https://homebrew.bintray.com/bottles/byobu-5.127.mojave.bottle.tar.gz
Already downloaded: /Users/anudeepsamaiya/Library/Caches/Homebrew/downloads/3fe19a65f2242c25abf8e714481a8a13b67b15da5dc7b36872a6d57221c29407--byobu-5.127.mojave.bottle.tar.gz
==> Pouring byobu-5.127.mojave.bottle.tar.gz
==> Caveats
Add the following to your shell configuration file:
  export BYOBU_PREFIX=/usr/local
==> Summary
🍺  /usr/local/Cellar/byobu/5.127: 161 files, 651.5KB
==> Caveats
==> byobu
Add the following to your shell configuration file:
  export BYOBU_PREFIX=/usr/local
```
```
anudeepsamaiya@orion:~$ $BYOBU_PREFIX
bash: /usr/local: Is a directory
```
```
anudeepsamaiya@orion:~$ byobu-config
ERROR: Could not import the python snack module
anudeepsamaiya@orion:~$
```

**Comment by SMillerDev** [comment]
What does `brew doctor` say? And are you using `anaconda` by any chance? https://github.com/Homebrew/legacy-homebrew/issues/43989 suggests that might be a cause.

**Comment by anudeepsamaiya** [comment]
```
anudeepsamaiya@orion:~$ brew doctor
Your system is ready to brew.
anudeepsamaiya@orion:~$
```

No not using `anaconda.`

`python` and `python@2` installed with brew.

**Comment by SMillerDev** [comment]
what happens when you run `python2.7 -c "import snack"`?

**Comment by anudeepsamaiya** [comment]
Well its says ImportError
```
anudeepsamaiya@orion:~$ python2.7 -c "import snack"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: No module named snack
1 anudeepsamaiya@orion:~$ 
```

**Comment by SMillerDev** [comment]
Could you run `brew reinstall newt` and `brew test newt` and report the outcome?

**Comment by anudeepsamaiya** [comment]
```
anudeepsamaiya@orion:~$ brew reinstall newt
==> Reinstalling newt 
==> Downloading https://homebrew.bintray.com/bottles/newt-0.52.20.mojave.bottle.tar.gz
Already downloaded: /Users/anudeepsamaiya/Library/Caches/Homebrew/downloads/7c7197cc936f983d4a4133ca217f02e61bd2b9ece4b5a0bd08bb1233760b145d--newt-0.52.20.mojave.bottle.tar.gz
==> Pouring newt-0.52.20.mojave.bottle.tar.gz
🍺  /usr/local/Cellar/newt/0.52.20: 88 files, 324.5KB
anudeepsamaiya@orion:~$ brew test newt
Testing newt
==> python2.7 -c import snack
Last 15 lines from /Users/anudeepsamaiya/Library/Logs/Homebrew/newt/test.01.python2.7:
2018-12-20 21:29:48 +0530

python2.7
-c
import snack

Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: No module named snack
Error: newt: failed
Failed executing:
/usr/local/Homebrew/Library/Homebrew/formula.rb:1921:in `block in system'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1858:in `open'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1858:in `system'
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/newt.rb:42:in `block in <class:Newt>'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1732:in `block (3 levels) in run_test'
/usr/local/Homebrew/Library/Homebrew/utils.rb:523:in `with_env'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1731:in `block (2 levels) in run_test'
/usr/local/Homebrew/Library/Homebrew/formula.rb:870:in `with_logging'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1730:in `block in run_test'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1971:in `block in mktemp'
/usr/local/Homebrew/Library/Homebrew/mktemp.rb:55:in `block in run'
/usr/local/Homebrew/Library/Homebrew/mktemp.rb:55:in `chdir'
/usr/local/Homebrew/Library/Homebrew/mktemp.rb:55:in `run'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1970:in `mktemp'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1724:in `run_test'
/usr/local/Homebrew/Library/Homebrew/test.rb:28:in `block in <main>'
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/timeout.rb:91:in `block in timeout'
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/timeout.rb:33:in `block in catch'
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/timeout.rb:33:in `catch'
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/timeout.rb:33:in `catch'
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/timeout.rb:106:in `timeout'
/usr/local/Homebrew/Library/Homebrew/test.rb:27:in `<main>'
1 anudeepsamaiya@orion:~$ 
```

**Comment by martinslota** [comment]
I tried to dig a bit around why the `newt` build does not include the `snack` module. On Mojave I get the following output from `./configure`:

```
newt-0.52.20 $ ./configure
...
checking for python versions... 
checking for gettext in -lc... no
...
```

This is with the system Python as well as both `python` and `python@2` brew packages installed. The script detects no python installation because this is how it checks for one:

```
PYTHONVERS=$(ls /usr/include/python*/Python.h 2> /dev/null | sed 's|.*\(python[0-9]*\.[0-9]*\).*|\1|g' | tr '\n' ' ')
```

It manages to detect Python correctly if I change that part to this instead:

```
PYTHONVERS=$(find /usr/local/Cellar -name 'Python.h' 2> /dev/null | sed 's|.*\(python[0-9]*\.[0-9]*\).*|\1|g' | tr '\n' ' ')
```

I'm guessing that's not exactly the right change to. Nevertheless, `make` then manages to create both `python2.7/_snack.so` as well as `python3.7/_snack.so` which it didn't create before. I then hack-patched the `site-packages` in `/usr/local/lib` using the created files and that seemed to mostly get `byobu` up and running.

I'd love to help make this a proper patch but I don't really know how to proceed.

**Comment by silverbucket** [comment]
Running into this issue as well, when I run `byobu-config` initially I get:

```
$ byobu-config 
/usr/local/bin/byobu-config: /usr/local/lib/byobu/include/config.py: /usr/bin/python3: bad interpreter: No such file or directory
```

If I first `export BYOBU_PYTHON=/usr/local/bin/python3` then I get the following:

```
$ export BYOBU_PYTHON=/usr/local/bin/python3
$ byobu-config
ERROR: Could not import the python snack module
```

Trying to (naively) install snack:

```
$ python3 -m pip  install snack
Collecting snack
  Downloading https://files.pythonhosted.org/packages/15/52/7889541bad6bd053c6554e3158c91cf0d4092b251b34de5fa35e20040968/snack-0.0.3.tar.gz (155kB)
    100% |████████████████████████████████| 163kB 2.7MB/s 
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/s_/r0gbm_m519g64jjtbhkdr2bm0000gy/T/pip-install-o53y2fac/snack/setup.py", line 47
        print GCC_VERSION
                        ^
    SyntaxError: Missing parentheses in call to 'print'. Did you mean print(GCC_VERSION)?
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/s_/r0gbm_m519g64jjtbhkdr2bm0000gy/T/pip-install-o53y2fac/snack/
Fri Feb  1 11:36:38 CET 2019
```

**Comment by silverbucket** [comment]
Still getting this

**Comment by baramon** [comment]
Me too

**Comment by martinslota** [comment]
Me too

**Comment by SMillerDev** [comment]
The stalebot isn't really a participation call. If nobody is interacting with the issue to solve it it's better to just close it no matter if you're affected by it.
