### ISSUE TITLE
install go issues

### ISSUE THREAD

**Issue by droid-Q** [Homebrew/homebrew-core#3558]
brew doctor：
```
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry and just ignore them. Thanks!

Warning: Unbrewed dylibs were found in /usr/local/lib.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected dylibs:
    /usr/local/lib/librtmp.dylib

Warning: Unbrewed header files were found in /usr/local/include.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected header files:
    /usr/local/include/python2.7/greenlet/greenlet.h
    /usr/local/include/python3.4m/greenlet/greenlet.h

Warning: You are using OS X 10.12.
We do not provide support for this pre-release version.
You may encounter build failures or other breakages.
Please create pull-requests instead of filing issues.`
```
my install log：
```
==> Downloading https://storage.googleapis.com/golang/go1.6.3.src.tar.gz
Already downloaded: /Users/droid/Library/Caches/Homebrew/go-1.6.3.tar.gz
==> Downloading https://storage.googleapis.com/golang/go1.4.2.darwin-amd64-osx10.8.tar.gz
Already downloaded: /Users/droid/Library/Caches/Homebrew/go--gobootstrap-10.8.tar.gz
==> ./make.bash --no-clean
Last 15 lines from /Users/droid/Library/Logs/Homebrew/go/01.make.bash:
	/private/tmp/go-20160803-45479-1u7e4sb/go/gobootstrap/src/cmd/go/pkg.go:919 +0x74 fp=0xc2080c9c50 sp=0xc2080c9b40
main.runInstall(0x3f9a40, 0xc20800a090, 0x1, 0x1)
	/private/tmp/go-20160803-45479-1u7e4sb/go/gobootstrap/src/cmd/go/build.go:330 +0x55 fp=0xc2080c9d98 sp=0xc2080c9c50
main.main()
	/private/tmp/go-20160803-45479-1u7e4sb/go/gobootstrap/src/cmd/go/main.go:163 +0x608 fp=0xc2080c9f98 sp=0xc2080c9d98
runtime.main()
	/usr/local/go/src/runtime/proc.go:63 +0xf3 fp=0xc2080c9fe0 sp=0xc2080c9f98
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:2232 +0x1 fp=0xc2080c9fe8 sp=0xc2080c9fe0

goroutine 5 [syscall]:
os/signal.loop()
	/usr/local/go/src/os/signal/signal_unix.go:21 +0x1f
created by os/signal.init·1
	/usr/local/go/src/os/signal/signal_unix.go:27 +0x35
```

**Comment by DomT4** [comment]
This is likely related to the discussion in https://github.com/golang/go/issues/16579.

**Comment by buildmaster** [comment]
tried to install rc5 
```
$ brew install go --devel
Warning: You are using OS X 10.12.
We do not provide support for this pre-release version.
You may encounter build failures or other breakages.
Please create pull-requests instead of filing issues.
==> Downloading https://storage.googleapis.com/golang/go1.7rc5.src.tar.gz
Already downloaded: /Users/owen/Library/Caches/Homebrew/go-1.7rc5.tar.gz
==> Downloading https://storage.googleapis.com/golang/go1.4.2.darwin-amd64-osx10.8.tar.gz
Already downloaded: /Users/owen/Library/Caches/Homebrew/go--gobootstrap-10.8.tar.gz
==> ./make.bash --no-clean
Last 15 lines from /Users/owen/Library/Logs/Homebrew/go/01.make.bash:
	/usr/local/go/src/syscall/syscall_unix.go:136 +0x58
os.(*File).read(0xc2083189a8, 0xc208400c00, 0x200, 0x200, 0xc208400c00, 0x0, 0x0)
	/usr/local/go/src/os/file_unix.go:191 +0x86
os.(*File).Read(0xc2083189a8, 0xc208400c00, 0x200, 0x200, 0xa, 0x0, 0x0)
	/usr/local/go/src/os/file.go:95 +0x91
bytes.(*Buffer).ReadFrom(0xc2081d90a0, 0x46e4c8, 0xc2083189a8, 0x0, 0x0, 0x0)
	/usr/local/go/src/bytes/buffer.go:169 +0x25a
io.Copy(0x47a390, 0xc2081d90a0, 0x46e4c8, 0xc2083189a8, 0x0, 0x0, 0x0)
	/usr/local/go/src/io/io.go:358 +0x13d
os/exec.func·003(0x0, 0x0)
	/usr/local/go/src/os/exec/exec.go:221 +0x7d
os/exec.func·004(0xc2080c4840)
	/usr/local/go/src/os/exec/exec.go:328 +0x2d
created by os/exec.(*Cmd).Start
	/usr/local/go/src/os/exec/exec.go:329 +0xb6d
```

**Comment by DomT4** [comment]
Yeah. As far as I understand it this is the problem:

> We should also consider making a 1.4.4 release with this fix, unfortunately, so that people can bootstrap from source. But not until there is a final release of Mac OS Sierra.

I suspect everything Go will keep breaking on 10.12 until that 1.4.4 release is available.

**Comment by droid-Q** [comment]
this is my gist-log :
[gist-log](https://gist.github.com/7ba2295ae4984ca2486b4610bbfd99aa)

**Comment by DomT4** [comment]
See https://github.com/Homebrew/homebrew-core/pull/3581.

**Comment by droid-Q** [comment]
@DomT4  It's working!.thanks.
