### ISSUE TITLE
brew install nginx-full --with-rtmp-module has an prob

### ISSUE THREAD

**Issue by carmyang** [Homebrew/homebrew-core#35789]
localhost:~ CarmYang$ brew install nginx-full --with-rtmp-module
Error: undefined method `name' for nil:NilClass
Please report this bug:
  https://docs.brew.sh/Troubleshooting
/usr/local/Homebrew/Library/Homebrew/exceptions.rb:186:in `block in initialize'
/usr/local/Homebrew/Library/Homebrew/exceptions.rb:185:in `map'
/usr/local/Homebrew/Library/Homebrew/exceptions.rb:185:in `initialize'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:414:in `new'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:414:in `loader_for'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:310:in `factory'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:490:in `find_with_priority'
/usr/local/Homebrew/Library/Homebrew/extend/ARGV.rb:49:in `block in formulae'
/usr/local/Homebrew/Library/Homebrew/extend/ARGV.rb:45:in `map'
/usr/local/Homebrew/Library/Homebrew/extend/ARGV.rb:45:in `formulae'
/usr/local/Homebrew/Library/Homebrew/cmd/install.rb:129:in `install'
/usr/local/Homebrew/Library/Homebrew/brew.rb:89:in `<main>'
localhost:~ CarmYang$

**Comment by fxcoudert** [comment]
Please fill the full template issue, otherwise we really cannot guess what the problem is.

**Comment by carmyang** [comment]
I had reInstall homebrew,and installed nginx ,and I want to ($brew install nginx-full --with-rtmp-module) but had another problem:

localhost:bin CarmYang$ brew install nginx-full --with-rtmp-module
Updating Homebrew...
To restore the stashed changes to /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core run:
  'cd /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core && git stash pop'
==> Auto-updated Homebrew!
Updated 1 tap (homebrew/core).
==> Updated Formulae
mutt

Error: No available formula with the name "nginx-full" 
==> Searching for a previously deleted formula (in the last month)...
Warning: homebrew/core is shallow clone. To get complete history run:
  git -C "$(brew --repo homebrew/core)" fetch --unshallow

Error: No previously deleted formula found.
==> Searching for similarly named formulae...
Error: No similarly named formulae found.
==> Searching taps...
==> Searching taps on GitHub...
Error: No formulae found in taps.
localhost:bin CarmYang$ 

localhost:bin CarmYang$ brew info nginx
nginx: stable 1.15.8 (bottled), HEAD
HTTP(S) server and reverse proxy, and IMAP/POP3 proxy server
https://nginx.org/
/usr/local/Cellar/nginx/1.15.8 (23 files, 1.4MB) *
  Poured from bottle on 2019-01-08 at 17:31:54
From: https://github.com/Homebrew/homebrew-core/blob/master/Formula/nginx.rb
==> Dependencies
Required: openssl ✔, pcre ✔
Optional: passenger ✔
==> Options
--with-passenger
	Compile with support for Phusion Passenger module
--HEAD
	Install HEAD version
==> Caveats
Docroot is: /usr/local/var/www

The default port has been set in /usr/local/etc/nginx/nginx.conf to 8080 so that
nginx can run without sudo.

nginx will load all files in /usr/local/etc/nginx/servers/.

To have launchd start nginx now and restart at login:
  brew services start nginx
Or, if you don't want/need a background service you can just run:
  nginx
==> Analytics
install: 32,595 (30 days), 105,506 (90 days), 437,938 (365 days)
install_on_request: 30,246 (30 days), 97,573 (90 days), 391,236 (365 days)
build_error: 0 (30 days)
localhost:bin CarmYang$ 

I want to use rtmp server:

localhost:bin CarmYang$ nginx
nginx: [emerg] unknown directive "rtmp" in /usr/local/etc/nginx/nginx.conf:119
localhost:bin CarmYang$ 
localhost:bin CarmYang$ open /usr/local/etc/nginx/nginx.conf


rtmp{
	server{
		listen 1935;
		application rtmplive{
			live on;
			max_connections 1024;
		}
	}
}

how can I install the rtmp-module?
please help me!thx
