### ISSUE TITLE
Libsodium

### ISSUE THREAD

**Issue by xx-anthony** [Homebrew/homebrew-core#36027]
>>> import libnacl.public
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Library/Python/2.7/site-packages/libnacl/__init__.py", line 83, in <module>
    nacl = _get_nacl()
  File "/Library/Python/2.7/site-packages/libnacl/__init__.py", line 47, in _get_nacl
    raise OSError(msg)
OSError: Could not locate nacl lib, searched for libsodium

I'm using macOS Mojave. I get that error.

**Comment by Ziudin** [comment]
Truss gimana

**Comment by SMillerDev** [comment]
Please fill out the entire issue template. It's really difficult to help you without it so I'm going to close this until we have the required information to help you debug.
