### ISSUE TITLE
Python - Libsodium (Don't delete pls, need some answers.. thanks)

### ISSUE THREAD

**Issue by xx-anthony** [Homebrew/homebrew-core#36029]
>>> import libnacl.public
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Library/Python/2.7/site-packages/libnacl/__init__.py", line 83, in <module>
    nacl = _get_nacl()
  File "/Library/Python/2.7/site-packages/libnacl/__init__.py", line 47, in _get_nacl
    raise OSError(msg)
OSError: Could not locate nacl lib, searched for libsodium

Does anybody encountered this error? I'm using macOS Mojave.

**Comment by SMillerDev** [comment]
Could you fill out the issue template please? It's pretty essential in debugging issues. This issue can be reopened once we have all the information needed to start debugging.
