### ISSUE TITLE
brew cleanup issue -- cannot load such file -- find

### ISSUE THREAD

**Issue by chu01** [Homebrew/homebrew-core#36647]
I just copied and put the issue here. after running "brew cleanup"
=========================================
Warning: Skipping zsh-completions: most recent version 0.30.0 not installed
Error: cannot load such file -- find
Please report this bug:
  https://docs.brew.sh/Troubleshooting
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/2.3.0/pathname.rb:559:in `find'
/usr/local/Homebrew/Library/Homebrew/cleanup.rb:410:in `block in prune_prefix_symlinks_and_directories'
/usr/local/Homebrew/Library/Homebrew/cleanup.rb:407:in `each'
/usr/local/Homebrew/Library/Homebrew/cleanup.rb:407:in `prune_prefix_symlinks_and_directories'
/usr/local/Homebrew/Library/Homebrew/cleanup.rb:197:in `clean!'
/usr/local/Homebrew/Library/Homebrew/cmd/cleanup.rb:35:in `cleanup'
/usr/local/Homebrew/Library/Homebrew/brew.rb:105:in `<main>'

**Comment by chu01** [comment]
This fixed my issue: 
- sudo chown -R <username> /Users/<username>/Library/Logs
