### ISSUE TITLE
Python 3.7.2 install fails

### ISSUE THREAD

**Issue by swensonator** [Homebrew/homebrew-core#36753]
**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [x] are reporting a bug others will be able to reproduce and not asking a question or requesting software. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh. To get software added or changed in Homebrew please file a [Pull Request](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)
- [x] have a problem with `brew install` (or `upgrade`, `reinstall`) a single, Homebrew/homebrew-core formula (not cask) on macOS? If it's a general `brew` problem please file this issue at Homebrew/brew: https://github.com/Homebrew/brew/issues/new/choose. If it's a Linux problem please file this issue at https://github.com/Linuxbrew/homebrew-core/issues/new/choose. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/homebrew-cask/issues/new/choose. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [ ] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

To help us debug your issue please explain:
- What you were trying to do (and why)
Now that `brew install vim --with-python@2` is no longer an option, I am attempting to install python@3 and upgrade vim, but without any success.

- What happened (include command output)

```
~ ] brew install --debug python
Updating Homebrew...
/Volumes/atm0/Users/caswenso/homebrew/Library/Homebrew/brew.rb (Formulary::FormulaLoader): loading /Volumes/atm0/Users/caswenso/homebrew/Library/Taps/homebrew/homebrew-core/Formula/python.rb
/Volumes/atm0/Users/caswenso/homebrew/Library/Homebrew/brew.rb (Formulary::FormulaLoader): loading /Volumes/atm0/Users/caswenso/homebrew/Library/Taps/homebrew/homebrew-core/Formula/pkg-config.rb
/Volumes/atm0/Users/caswenso/homebrew/Library/Homebrew/brew.rb (Formulary::FormulaLoader): loading /Volumes/atm0/Users/caswenso/homebrew/Library/Taps/homebrew/homebrew-core/Formula/gdbm.rb
/Volumes/atm0/Users/caswenso/homebrew/Library/Homebrew/brew.rb (Formulary::FormulaLoader): loading /Volumes/atm0/Users/caswenso/homebrew/Library/Taps/homebrew/homebrew-core/Formula/openssl.rb
/Volumes/atm0/Users/caswenso/homebrew/Library/Homebrew/brew.rb (Formulary::FormulaLoader): loading /Volumes/atm0/Users/caswenso/homebrew/Library/Taps/homebrew/homebrew-core/Formula/readline.rb
/Volumes/atm0/Users/caswenso/homebrew/Library/Homebrew/brew.rb (Formulary::FormulaLoader): loading /Volumes/atm0/Users/caswenso/homebrew/Library/Taps/homebrew/homebrew-core/Formula/sqlite.rb
/Volumes/atm0/Users/caswenso/homebrew/Library/Homebrew/brew.rb (Formulary::FormulaLoader): loading /Volumes/atm0/Users/caswenso/homebrew/Library/Taps/homebrew/homebrew-core/Formula/xz.rb
/Volumes/atm0/Users/caswenso/homebrew/Library/Homebrew/build.rb (Formulary::FromPathLoader): loading /Volumes/atm0/Users/caswenso/homebrew/Library/Taps/homebrew/homebrew-core/Formula/python.rb
/Volumes/atm0/Users/caswenso/homebrew/Library/Homebrew/build.rb (Formulary::FormulaLoader): loading /Volumes/atm0/Users/caswenso/homebrew/Library/Taps/homebrew/homebrew-core/Formula/gdbm.rb
/Volumes/atm0/Users/caswenso/homebrew/Library/Homebrew/build.rb (Formulary::FormulaLoader): loading /Volumes/atm0/Users/caswenso/homebrew/Library/Taps/homebrew/homebrew-core/Formula/openssl.rb
/Volumes/atm0/Users/caswenso/homebrew/Library/Homebrew/build.rb (Formulary::FormulaLoader): loading /Volumes/atm0/Users/caswenso/homebrew/Library/Taps/homebrew/homebrew-core/Formula/readline.rb
/Volumes/atm0/Users/caswenso/homebrew/Library/Homebrew/build.rb (Formulary::FormulaLoader): loading /Volumes/atm0/Users/caswenso/homebrew/Library/Taps/homebrew/homebrew-core/Formula/sqlite.rb
/Volumes/atm0/Users/caswenso/homebrew/Library/Homebrew/build.rb (Formulary::FormulaLoader): loading /Volumes/atm0/Users/caswenso/homebrew/Library/Taps/homebrew/homebrew-core/Formula/xz.rb
/Volumes/atm0/Users/caswenso/homebrew/Library/Homebrew/build.rb (Formulary::FormulaLoader): loading /Volumes/atm0/Users/caswenso/homebrew/Library/Taps/homebrew/homebrew-core/Formula/pkg-config.rb
/usr/bin/curl -q --show-error --user-agent Homebrew/2.0.0\ \(Macintosh\;\ Intel\ Mac\ OS\ X\ 10.13.6\)\ curl/7.54.0 --location --silent --head https://www.python.org/ftp/python/3.7.2/Python-3.7.2.tgz
==> Downloading https://www.python.org/ftp/python/3.7.2/Python-3.7.2.tgz
/usr/bin/curl -q --show-error --user-agent Homebrew/2.0.0\ \(Macintosh\;\ Intel\ Mac\ OS\ X\ 10.13.6\)\ curl/7.54.0 --fail --progress-bar --location --remote-time --continue-at 0 --output /Volumes/atm0/Users/caswenso/Library/Caches/Homebrew/downloads/c0a14628b5078ca696f1e18227df67d9c5fbe04462c041d9252709c120ea3e1a--Python-3.7.2.tgz.incomplete https://www.python.org/ftp/python/3.7.2/Python-3.7.2.tgz
######################################################################## 100.0%
tar xf /Volumes/atm0/Users/caswenso/Library/Caches/Homebrew/downloads/c0a14628b5078ca696f1e18227df67d9c5fbe04462c041d9252709c120ea3e1a--Python-3.7.2.tgz -C /Volumes/atm0/Users/caswenso/homebrew/tmp/d20190205-88441-10axl4e
cp -pR /Volumes/atm0/Users/caswenso/homebrew/tmp/d20190205-88441-10axl4e/Python-3.7.2/. /Volumes/atm0/Users/caswenso/homebrew/tmp/python-20190205-88441-tp8p5x/Python-3.7.2
==> ./configure --prefix=/Volumes/atm0/Users/caswenso/homebrew/Cellar/python/3.7.2_1 --enable-ipv6 --datarootdir=/Volumes/atm0/Users/caswenso/homebrew/Cellar/python/3.7.2_1/share --datadir=/Volumes/atm0/Users/caswenso/homebrew/Cellar/python/3.7.2_1/share --enable-framework=/Volumes/atm0/Users/ caswenso/homebrew/Cellar/python/3.7.2_1/Frameworks --enable-loadable-sqlite-extensions --without-ensurepip --with-dtrace --with-openssl=/Volumes/atm0/Users/caswenso/homebrew/opt/openssl --without-gcc MACOSX_DEPLOYMENT_TARGET=10.13 CFLAGS=-isysroot /Applications/Xcode.app/Contents/Developer/    Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/usr/include -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/System/Library/       Frameworks/Tk.framework/Versions/8.5/Headers LDFLAGS=-isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk
==> make
==> make install PYTHONAPPSDIR=/Volumes/atm0/Users/caswenso/homebrew/Cellar/python/3.7.2_1
==> make frameworkinstallextras PYTHONAPPSDIR=/Volumes/atm0/Users/caswenso/homebrew/Cellar/python/3.7.2_1/share/python
/usr/bin/curl -q --show-error --user-agent Homebrew/2.0.0\ \(Macintosh\;\ Intel\ Mac\ OS\ X\ 10.13.6\)\ curl/7.54.0 --location --silent --head https://files.pythonhosted.org/packages/37/1b/b25507861991beeade31473868463dad0e58b1978c209de27384ae541b0b/setuptools-40.6.3.zip
==> Downloading https://files.pythonhosted.org/packages/37/1b/b25507861991beeade31473868463dad0e58b1978c209de27384ae541b0b/setuptools-40.6.3.zip
/usr/bin/curl -q --show-error --user-agent Homebrew/2.0.0\ \(Macintosh\;\ Intel\ Mac\ OS\ X\ 10.13.6\)\ curl/7.54.0 --fail --progress-bar --location --remote-time --continue-at 0 --output /Volumes/atm0/Users/caswenso/Library/Caches/Homebrew/downloads/db35d64db50c77fd8d1c71a34dea53793212ff10926cce3996211152a2be6077--setuptools-40.6.3.zip.incomplete https://files.pythonhosted.org/packages/37/1b/b25507861991beeade31473868463dad0e58b1978c209de27384ae541b0b/setuptools-40.6.3.zip
######################################################################## 100.0%
unzip -qq /Volumes/atm0/Users/caswenso/Library/Caches/Homebrew/downloads/db35d64db50c77fd8d1c71a34dea53793212ff10926cce3996211152a2be6077--setuptools-40.6.3.zip -d /Volumes/atm0/Users/caswenso/homebrew/tmp/d20190205-88441-1xlie5t
cp -pR /Volumes/atm0/Users/caswenso/homebrew/tmp/d20190205-88441-1xlie5t/setuptools-40.6.3/. /Volumes/atm0/Users/caswenso/homebrew/tmp/python--setuptools-20190205-88441-1rwooh6/setuptools-40.6.3
/usr/bin/curl -q --show-error --user-agent Homebrew/2.0.0\ \(Macintosh\;\ Intel\ Mac\ OS\ X\ 10.13.6\)\ curl/7.54.0 --location --silent --head https://files.pythonhosted.org/packages/45/ae/8a0ad77defb7cc903f09e551d88b443304a9bd6e6f124e75c0fbbf6de8f7/pip-18.1.tar.gz
==> Downloading https://files.pythonhosted.org/packages/45/ae/8a0ad77defb7cc903f09e551d88b443304a9bd6e6f124e75c0fbbf6de8f7/pip-18.1.tar.gz
/usr/bin/curl -q --show-error --user-agent Homebrew/2.0.0\ \(Macintosh\;\ Intel\ Mac\ OS\ X\ 10.13.6\)\ curl/7.54.0 --fail --progress-bar --location --remote-time --continue-at 0 --output /Volumes/atm0/Users/caswenso/Library/Caches/Homebrew/downloads/49675dad98271e4b941f60d10b32b309d3d0a8133fc6f779c65eb050e19f4f84--pip-18.1.tar.gz.incomplete https://files.pythonhosted.org/packages/45/ae/8a0ad77defb7cc903f09e551d88b443304a9bd6e6f124e75c0fbbf6de8f7/pip-18.1.tar.gz
######################################################################## 100.0%
tar xf /Volumes/atm0/Users/caswenso/Library/Caches/Homebrew/downloads/49675dad98271e4b941f60d10b32b309d3d0a8133fc6f779c65eb050e19f4f84--pip-18.1.tar.gz -C /Volumes/atm0/Users/caswenso/homebrew/tmp/d20190205-88441-1n35ixj
cp -pR /Volumes/atm0/Users/caswenso/homebrew/tmp/d20190205-88441-1n35ixj/pip-18.1/. /Volumes/atm0/Users/caswenso/homebrew/tmp/python--pip-20190205-88441-4btip1/pip-18.1
/usr/bin/curl -q --show-error --user-agent Homebrew/2.0.0\ \(Macintosh\;\ Intel\ Mac\ OS\ X\ 10.13.6\)\ curl/7.54.0 --location --silent --head https://files.pythonhosted.org/packages/d8/55/221a530d66bf78e72996453d1e2dedef526063546e131d70bed548d80588/wheel-0.32.3.tar.gz
==> Downloading https://files.pythonhosted.org/packages/d8/55/221a530d66bf78e72996453d1e2dedef526063546e131d70bed548d80588/wheel-0.32.3.tar.gz
/usr/bin/curl -q --show-error --user-agent Homebrew/2.0.0\ \(Macintosh\;\ Intel\ Mac\ OS\ X\ 10.13.6\)\ curl/7.54.0 --fail --progress-bar --location --remote-time --continue-at 0 --output /Volumes/atm0/Users/caswenso/Library/Caches/Homebrew/downloads/67e874601fa70fac6ed5e2bd91f7a9d719609be2b09874b79b0b2a11b90028dc--wheel-0.32.3.tar.gz.incomplete https://files.pythonhosted.org/packages/d8/55/221a530d66bf78e72996453d1e2dedef526063546e131d70bed548d80588/wheel-0.32.3.tar.gz
######################################################################## 100.0%
tar xf /Volumes/atm0/Users/caswenso/Library/Caches/Homebrew/downloads/67e874601fa70fac6ed5e2bd91f7a9d719609be2b09874b79b0b2a11b90028dc--wheel-0.32.3.tar.gz -C /Volumes/atm0/Users/caswenso/homebrew/tmp/d20190205-88441-g7ungg
cp -pR /Volumes/atm0/Users/caswenso/homebrew/tmp/d20190205-88441-g7ungg/wheel-0.32.3/. /Volumes/atm0/Users/caswenso/homebrew/tmp/python--wheel-20190205-88441-1266mm7/wheel-0.32.3
Changing dylib ID of /Volumes/atm0/Users/caswenso/homebrew/Cellar/python/3.7.2_1/Frameworks/Python.framework/Versions/3.7/Python
  from /Volumes/atm0/Users/caswenso/homebrew/Cellar/python/3.7.2_1/Frameworks/Python.framework/Versions/3.7/Python
    to /Volumes/atm0/Users/caswenso/homebrew/opt/python/Frameworks/Python.framework/Versions/3.7/Python
/Volumes/atm0/Users/caswenso/homebrew/Library/Homebrew/postinstall.rb (Formulary::FromPathLoader): loading /Volumes/atm0/Users/caswenso/homebrew/Library/Taps/homebrew/homebrew-core/Formula/python.rb
==> /Volumes/atm0/Users/caswenso/homebrew/Cellar/python/3.7.2_1/bin/python3 -s setup.py --no-user-cfg install --force --verbose --install-scripts=/Volumes/atm0/Users/caswenso/homebrew/Cellar/python/3.7.2_1/bin --install-lib=/Volumes/atm0/Users/caswenso/homebrew/lib/python3.7/site-packages --single-version-externally-managed --record=installed.txt
Last 15 lines from /Volumes/atm0/Users/caswenso/Library/Logs/Homebrew/python/post_install.01.python3:
2019-02-05 14:02:05 -0500

/Volumes/atm0/Users/caswenso/homebrew/Cellar/python/3.7.2_1/bin/python3
-s
setup.py
--no-user-cfg
install
--force
--verbose
--install-scripts=/Volumes/atm0/Users/caswenso/homebrew/Cellar/python/3.7.2_1/bin
--install-lib=/Volumes/atm0/Users/caswenso/homebrew/lib/python3.7/site-packages
--single-version-externally-managed
--record=installed.txt

/usr/bin/curl --version
/usr/libexec/java_home --xml --failfast
/usr/libexec/java_home --xml --failfast
Warning: The post-install step did not complete successfully
You can try again using `brew postinstall python`
==> Failed executing:
/Volumes/atm0/Users/caswenso/homebrew/Library/Homebrew/formula.rb:1921:in `block in system'
/Volumes/atm0/Users/caswenso/homebrew/Library/Homebrew/formula.rb:1858:in `open'
/Volumes/atm0/Users/caswenso/homebrew/Library/Homebrew/formula.rb:1858:in `system'
/Volumes/atm0/Users/caswenso/homebrew/Library/Taps/homebrew/homebrew-core/Formula/python.rb:202:in `block (2 levels) in post_install'
/Volumes/atm0/Users/caswenso/homebrew/Library/Homebrew/extend/pathname.rb:255:in `block in cd'
/Volumes/atm0/Users/caswenso/homebrew/Library/Homebrew/extend/pathname.rb:255:in `chdir'
/Volumes/atm0/Users/caswenso/homebrew/Library/Homebrew/extend/pathname.rb:255:in `cd'
/Volumes/atm0/Users/caswenso/homebrew/Library/Taps/homebrew/homebrew-core/Formula/python.rb:201:in `block in post_install'
/Volumes/atm0/Users/caswenso/homebrew/Library/Taps/homebrew/homebrew-core/Formula/python.rb:200:in `each'
/Volumes/atm0/Users/caswenso/homebrew/Library/Taps/homebrew/homebrew-core/Formula/python.rb:200:in `post_install'
/Volumes/atm0/Users/caswenso/homebrew/Library/Homebrew/formula.rb:1013:in `block (2 levels) in run_post_install'
/Volumes/atm0/Users/caswenso/homebrew/Library/Homebrew/formula.rb:870:in `with_logging'
/Volumes/atm0/Users/caswenso/homebrew/Library/Homebrew/formula.rb:1012:in `block in run_post_install'
/Volumes/atm0/Users/caswenso/homebrew/Library/Homebrew/utils.rb:539:in `with_env'
/Volumes/atm0/Users/caswenso/homebrew/Library/Homebrew/formula.rb:1004:in `run_post_install'
/Volumes/atm0/Users/caswenso/homebrew/Library/Homebrew/postinstall.rb:16:in `<main>'
==> Caveats
Python has been installed as
  /Volumes/atm0/Users/caswenso/homebrew/bin/python3

Unversioned symlinks `python`, `python-config`, `pip` etc. pointing to
`python3`, `python3-config`, `pip3` etc., respectively, have been installed into
  /Volumes/atm0/Users/caswenso/homebrew/opt/python/libexec/bin

If you need Homebrew's Python 2.7 run
  brew install python@2

You can install Python packages with
  pip3 install <package>
They will install into the site-package directory
  /Volumes/atm0/Users/caswenso/homebrew/lib/python3.7/site-packages

See: https://docs.brew.sh/Homebrew-and-Python
==> Summary
🍺  /Volumes/atm0/Users/caswenso/homebrew/Cellar/python/3.7.2_1: 7,943 files, 112MB, built in 11 minutes 35 seconds
```
As you can see, the installation of at least the base python installation runs to completion, but the postinstall does not run correctly. The expected directory structure is created and `$(brew --prefix)/bin/python3` exists, but I get "Permission denied" if I try to run `python3`. Additionally, `setuptools, pip, and wheel` do not appear to be installed, so maybe that is where the installation is failing.

Here is the gistlog link:
[https://gist.github.com/3e5c3ba4c238a582f8f5a7ba17697e39](https://gist.github.com/3e5c3ba4c238a582f8f5a7ba17697e39)

My `brew doctor` output contains a number of "errors" due to my not using `/usr/local` as my brew prefix, but those have never impacted previous installations of python@2 or vim.

- What you expected to happen
I expected python3 to be installed.

- Step-by-step reproduction instructions (by running `brew install` commands)
brew install python

**Comment by SMillerDev** [comment]
> However do yourself a favour and install to /usr/local. Some things may not build when installed elsewhere. One of the reasons Homebrew just works relative to the competition is because we recommend installing to /usr/local. Pick another prefix at your peril!

Copied from https://docs.brew.sh/Installation

For your particular install this is especially true. All homebrew related files seem to be mashed into a single folder and there's tons of dependencies that homebrew didn't install.

**Comment by swensonator** [comment]
No can do. It is a managed computer and I do not have admin access.

Additionally, all the dependencies are already installed and I have a total of 60 brews installed - python3 is LITERALLY the only thing that fails to install. I have run homebrew in a custom folder for over 4 years now with minimal additional effort required, but I'm unable to solve this problem.
