### ISSUE TITLE
Icu4c does not set PATH or properly link icu-config file

### ISSUE THREAD

**Issue by nicholastulach** [Homebrew/homebrew-core#36958]
- What you were trying to do (and why)

I am trying to install icu4c as a dependency for the python package pyicu.

- What happened (include command output)

When running the following commands:
```
brew install icu4c
brew link icu4c
pip install pyicu
```
i receive the following stack trace:

```
Traceback (most recent call last):
      File "/private/var/folders/wj/643zq6fs1d5f2l96m424hz8h0000gp/T/pip-install-hwydq0cu/pyicu/setup.py", line 43, in <module>
        ICU_VERSION = os.environ['ICU_VERSION']
      File "/Users/jillzimmerman/.ve/bin/../lib/python3.7/os.py", line 678, in __getitem__
        raise KeyError(key) from None
    KeyError: 'ICU_VERSION'
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "/private/var/folders/wj/643zq6fs1d5f2l96m424hz8h0000gp/T/pip-install-hwydq0cu/pyicu/setup.py", line 46, in <module>
        ICU_VERSION = check_output(('icu-config', '--version')).strip()
      File "/usr/local/Cellar/python/3.7.2_2/Frameworks/Python.framework/Versions/3.7/lib/python3.7/subprocess.py", line 395, in check_output
        **kwargs).stdout
      File "/usr/local/Cellar/python/3.7.2_2/Frameworks/Python.framework/Versions/3.7/lib/python3.7/subprocess.py", line 472, in run
        with Popen(*popenargs, **kwargs) as process:
      File "/usr/local/Cellar/python/3.7.2_2/Frameworks/Python.framework/Versions/3.7/lib/python3.7/subprocess.py", line 775, in __init__
        restore_signals, start_new_session)
      File "/usr/local/Cellar/python/3.7.2_2/Frameworks/Python.framework/Versions/3.7/lib/python3.7/subprocess.py", line 1522, in _execute_child
        raise child_exception_type(errno_num, err_msg, err_filename)
    FileNotFoundError: [Errno 2] No such file or directory: 'icu-config': 'icu-config'
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/wj/643zq6fs1d5f2l96m424hz8h0000gp/T/pip-install-hwydq0cu/pyicu/setup.py", line 53, in <module>
        ''')
    RuntimeError:
    Please set the ICU_VERSION environment variable to the version of
    ICU you have installed.
```

I also receive the following output from `brew link icu4c --force`:

```
$ brew link icu4c --force
Warning: Refusing to link macOS-provided software: icu4c
If you need to have icu4c first in your PATH run:
  echo 'export PATH="/usr/local/opt/icu4c/bin:$PATH"' >> ~/.bash_profile
  echo 'export PATH="/usr/local/opt/icu4c/sbin:$PATH"' >> ~/.bash_profile

For compilers to find icu4c you may need to set:
  export LDFLAGS="-L/usr/local/opt/icu4c/lib"
  export CPPFLAGS="-I/usr/local/opt/icu4c/include"

For pkg-config to find icu4c you may need to set:
  export PKG_CONFIG_PATH="/usr/local/opt/icu4c/lib/pkgconfig"
```

- What you expected to happen

I expect `pyicu` to be successfully installed without any additional intervention. 
I expect `icu4c` to link the `icu-config` file properly so manual intervention (setting the PATH environment variable) isn't necessary.
This used to work (i.e. additional PATH setting was unnecessary) in older versions of icu4c/pyicu.

- Step-by-step reproduction instructions (by running `brew install` commands)
```
brew install icu4c
brew link icu4c --force
pip install --no-cache-dir pyicu
```

**Comment by SMillerDev** [comment]
The functionality to overwrite system tools have been removed in 1.9.0 iirc. It caused a lot of problems for people so now you'll have to put in a little more work. This is not something that'll change back any time soon.
