### ISSUE TITLE
cannot run any  brew comands -- cannot load such file -- concurrent /map(LoadError)

### ISSUE THREAD

**Issue by Ypixel** [Homebrew/homebrew-core#37269]
**Any brew commands couldn't be used , I have no idea.** 
**maybe the update of  macOS to 10.14.3?**
```
# brew
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require': cannot load such file -- concurrent/map (LoadError)
	from /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/ruby/2.3.0/gems/activesupport-5.2.2/lib/active_support/core_ext/object/blank.rb:4:in `<top (required)>'
	from /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/local/Homebrew/Library/Homebrew/global.rb:10:in `<top (required)>'
	from /usr/local/Homebrew/Library/Homebrew/brew.rb:17:in `require_relative'
	from /usr/local/Homebrew/Library/Homebrew/brew.rb:17:in `<main>'
```

**Comment by SMillerDev** [comment]
Please fill out the issue template as it is impossible to debug issues without it. I'm going to close this until all the required information is provided.

**Comment by waako** [comment]
I had this issue and re-ran the homebrew installer from https://brew.sh/ and that fixed it.
