### ISSUE TITLE
brew search Error: undefined method `undent' for #<String

### ISSUE THREAD

**Issue by michealzh** [Homebrew/homebrew-core#37677]
iterm version:3.2.7
zsh version:zsh 5.7.1 (x86_64-apple-darwin18.2.0)

when search openresty by brew throw exception in blew:

```shell
➜  ~ brew info openresty
openresty: stable 1.13.6.1
Scalable Web Platform by Extending NGINX with Lua
https://openresty.org
/usr/local/Cellar/openresty/1.13.6.1 (284 files, 6.2MB) *
  Built from source on 2017-11-15 at 10:18:11
From: /usr/local/opt/openresty/.brew/openresty.rb
==> Dependencies
Required: pcre ✔, homebrew/nginx/openresty-openssl ✘, geoip ✔
Optional: postgresql ✘
==> Options
--with-debug
	Compile with support for debug logging but without proper gdb debugging symbols
--with-iconv
	Compile with ngx_http_iconv_module
--with-postgresql
	Compile with ngx_http_postgres_module
--with-slice
	Compile with ngx_http_slice_module
Error: undefined method `undent' for #<String:0x00007ffa860e3020>
Please report this bug:
  https://docs.brew.sh/Troubleshooting
/usr/local/opt/openresty/.brew/openresty.rb:104:in `plist'
/usr/local/Homebrew/Library/Homebrew/extend/os/mac/caveats.rb:6:in `plist_caveats'
/usr/local/Homebrew/Library/Homebrew/caveats.rb:26:in `caveats'
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/forwardable.rb:202:in `empty?'
/usr/local/Homebrew/Library/Homebrew/cmd/info.rb:209:in `info_formula'
/usr/local/Homebrew/Library/Homebrew/cmd/info.rb:83:in `block in print_info'
/usr/local/Homebrew/Library/Homebrew/cmd/info.rb:72:in `each'
/usr/local/Homebrew/Library/Homebrew/cmd/info.rb:72:in `each_with_index'
/usr/local/Homebrew/Library/Homebrew/cmd/info.rb:72:in `print_info'
/usr/local/Homebrew/Library/Homebrew/cmd/info.rb:59:in `info'
/usr/local/Homebrew/Library/Homebrew/brew.rb:102:in `<main>'
```

**Comment by SMillerDev** [comment]
Please follow the issue template (just running the first few steps would be enough to resolve this). Without it it's also pretty much impossible to debug issues so I'll close it until the required information is provided.
