### ISSUE TITLE
Bind formula mixes up python versions

### ISSUE THREAD

**Issue by aabdnn** [Homebrew/homebrew-core#38022]
I have an up to date brew, and installed bind. Brew chose to install from the bottle. After installation, some utilities of the bind package don't run. For example, the dnssec-keymgr utility fails as follows:

```
$ dnssec-keymgr
Traceback (most recent call last):
  File "/usr/local/sbin/dnssec-keymgr", line 24, in <module>
    import isc.keymgr
  File "/usr/local/Cellar/bind/9.12.4/lib/python2.7/site-packages/isc/__init__.py", line 20, in <module>
    from isc.keyseries import *
  File "/usr/local/Cellar/bind/9.12.4/lib/python2.7/site-packages/isc/keyseries.py", line 16, in <module>
    from .policy import *
  File "/usr/local/Cellar/bind/9.12.4/lib/python2.7/site-packages/isc/policy.py", line 13, in <module>
    import ply.lex as lex
ImportError: No module named ply.lex
```

Looking at the formula, it seems that the bind formula wants python3, and also wants a python module called “ply”. This “ply” module is used to build a module called “isc” that contains python code used by various utilities in bind. However, they appear to have been built for python2. If I look inside the bottle archive, I see this:

```
bind/9.12.4/lib/python2.7/site-packages/isc/
```

And then:

```
bind/9.12.4/libexec/vendor/lib/python3.7/site-packages/ply/
```

Upon further examination of the “dnssec-keymgr” utility, I see that it is calling /usr/bin/python, rather than /usr/local/bin/python3.

Now, bind’s “configure” script looks for python by looking for “python” in the paths defined in PATH. So I don’t understand why the “isc” module is built for the system python2 instead of Homebrew’s python3.

Does anyone have any idea what is going on here?

**Comment by fwal** [comment]
Tracked down the exact PR that introduced the error: https://github.com/Homebrew/brew/pull/5413

**Comment by aabdnn** [comment]
I note that the BIND formula has been updated to version 9.14.0, but this issue remains!

**Comment by aabdnn** [comment]
Hi,

I've updated my bind package, but it still fails, because "ply" isn't installed:

```
$ dnssec-keymgr
Traceback (most recent call last):
  File "/usr/local/sbin/dnssec-keymgr", line 24, in <module>
    import isc.keymgr
  File "/usr/local/Cellar/bind/9.14.0_1/lib/python3.7/site-packages/isc/__init__.py", line 20, in <module>
    from isc.keyseries import *
  File "/usr/local/Cellar/bind/9.14.0_1/lib/python3.7/site-packages/isc/keyseries.py", line 16, in <module>
    from .policy import *
  File "/usr/local/Cellar/bind/9.14.0_1/lib/python3.7/site-packages/isc/policy.py", line 13, in <module>
    import ply.lex as lex
ModuleNotFoundError: No module named 'ply'
```
