### ISSUE TITLE
Unsupported special dependency :maximum_macos

### ISSUE THREAD

**Issue by anx1ang** [Homebrew/homebrew-core#38604]
- [x] ran `brew update` and can still reproduce the problem?

- [ ] ran `brew doctor`, fixed all issues and can still reproduce the problem?

- [ ] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [x] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?
brew config
```
HOMEBREW_VERSION: 1.5.11
ORIGIN: https://github.com/Homebrew/brew.git
HEAD: 058dad61b1ddb203e38187115517957824d51a2c
Last commit: 1 year ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 4d06ca00fb0e3aa6ef964fefe06d7d8b7926040f
Core tap last commit: 7 hours ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_RUBY_WARNINGS: -W0
CPU: 12-core 64-bit kabylake
Homebrew Ruby: 2.3.3 => /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/bin/ruby
Clang: N/A
Git: 2.20.1 => /Applications/Xcode.app/Contents/Developer/usr/bin/git
Curl: 7.54.0 => /usr/bin/curl
Perl: /usr/bin/perl
Python: /Users/anx1ang/.pyenv/shims/python => /usr/bin/python
Ruby: /usr/bin/ruby => /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/bin/ruby
Java: 1.8.0_131, 1.8.0_101
macOS: 10.14.3-x86_64
Xcode: 10.2
CLT: 10.1.0.0.1.1539992718
X11: N/A
```
brew doctor
`Error: Unrecognized Mach-O load command: 0x32`
To help us debug your issue please explain:
- What you were trying to do (and why)
  `brew update`,`brew install` and `brew uninstall`  error
- What happened (include command output)
 brew update
```
Fast-forwarded master to origin/master.
Updated 1 tap (homebrew/core).
==> Updated Formulae
apache-arrow                            apache-arrow-glib                       atomist-cli                             rakudo-star                             ruby-build                              vert.x
Error: Unsupported special dependency :maximum_macos
/usr/local/Homebrew/Library/Homebrew/dependency_collector.rb:128:in `parse_symbol_spec'
/usr/local/Homebrew/Library/Homebrew/compat/dependency_collector.rb:63:in `parse_symbol_spec'
/usr/local/Homebrew/Library/Homebrew/dependency_collector.rb:96:in `parse_spec'
/usr/local/Homebrew/Library/Homebrew/dependency_collector.rb:52:in `build'
/usr/local/Homebrew/Library/Homebrew/dependency_collector.rb:39:in `block in fetch'
/usr/local/Homebrew/Library/Homebrew/dependency_collector.rb:39:in `fetch'
/usr/local/Homebrew/Library/Homebrew/dependency_collector.rb:39:in `fetch'
/usr/local/Homebrew/Library/Homebrew/dependency_collector.rb:29:in `add'
/usr/local/Homebrew/Library/Homebrew/software_spec.rb:165:in `depends_on'
/usr/local/Homebrew/Library/Homebrew/formula.rb:2211:in `block in depends_on'
/usr/local/Homebrew/Library/Homebrew/formula.rb:2211:in `each'
/usr/local/Homebrew/Library/Homebrew/formula.rb:2211:in `depends_on'
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/wine.rb:24:in `<class:Wine>'
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/wine.rb:7:in `load_formula'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:27:in `module_eval'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:27:in `load_formula'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:47:in `load_formula_from_path'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:102:in `load_file'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:239:in `load_file'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:93:in `klass'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:89:in `get_formula'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:229:in `get_formula'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:280:in `factory'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:311:in `from_keg'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:294:in `from_rack'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1386:in `block in installed'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1384:in `each'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1384:in `flat_map'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1384:in `installed'
/usr/local/Homebrew/Library/Homebrew/cmd/update-report.rb:506:in `migrate_formula_rename'
/usr/local/Homebrew/Library/Homebrew/cmd/update-report.rb:101:in `each'
/usr/local/Homebrew/Library/Homebrew/cmd/update-report.rb:101:in `update_report'
/usr/local/Homebrew/Library/Homebrew/brew.rb:100:in `<main>'
```
brew  uninstall php
```
Error: Unsupported special dependency :maximum_macos
/usr/local/Homebrew/Library/Homebrew/dependency_collector.rb:128:in `parse_symbol_spec'
/usr/local/Homebrew/Library/Homebrew/compat/dependency_collector.rb:63:in `parse_symbol_spec'
/usr/local/Homebrew/Library/Homebrew/dependency_collector.rb:96:in `parse_spec'
/usr/local/Homebrew/Library/Homebrew/dependency_collector.rb:52:in `build'
/usr/local/Homebrew/Library/Homebrew/dependency_collector.rb:39:in `block in fetch'
/usr/local/Homebrew/Library/Homebrew/dependency_collector.rb:39:in `fetch'
/usr/local/Homebrew/Library/Homebrew/dependency_collector.rb:39:in `fetch'
/usr/local/Homebrew/Library/Homebrew/dependency_collector.rb:29:in `add'
/usr/local/Homebrew/Library/Homebrew/software_spec.rb:165:in `depends_on'
/usr/local/Homebrew/Library/Homebrew/formula.rb:2211:in `block in depends_on'
/usr/local/Homebrew/Library/Homebrew/formula.rb:2211:in `each'
/usr/local/Homebrew/Library/Homebrew/formula.rb:2211:in `depends_on'
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/wine.rb:24:in `<class:Wine>'
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/wine.rb:7:in `load_formula'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:27:in `module_eval'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:27:in `load_formula'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:47:in `load_formula_from_path'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:102:in `load_file'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:239:in `load_file'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:93:in `klass'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:89:in `get_formula'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:229:in `get_formula'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:280:in `factory'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:311:in `from_keg'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:294:in `from_rack'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1386:in `block in installed'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1384:in `each'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1384:in `flat_map'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1384:in `installed'
/usr/local/Homebrew/Library/Homebrew/keg.rb:120:in `find_some_installed_dependents'
/usr/local/Homebrew/Library/Homebrew/cmd/uninstall.rb:100:in `check_for_dependents'
/usr/local/Homebrew/Library/Homebrew/cmd/uninstall.rb:93:in `handle_unsatisfied_dependents'
/usr/local/Homebrew/Library/Homebrew/cmd/uninstall.rb:31:in `uninstall'
/usr/local/Homebrew/Library/Homebrew/brew.rb:100:in `<main>'
```
- What you expected to happen
solve it
- Step-by-step reproduction instructions (by running `brew install` commands)
brew uninstall
brew doctor
brew update

**Comment by SMillerDev** [comment]
You have a a very very old homebrew version. Please run `brew update-reset` to reset it to the latest version.

**Comment by anx1ang** [comment]
it's ok.thank you.

> You have a a very very old homebrew version. Please run `brew update-reset` to reset it to the latest version.
