### ISSUE TITLE
gradle failed to upgrade on 10.11.6

### ISSUE THREAD

**Issue by gribnut** [Homebrew/homebrew-core#3973]
# Please follow the general troubleshooting steps first:

- [x] Ran `brew update` and retried your prior step?
    yes
- [x] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?
    No problems identified.

### Bug reports:

Unable to upgrade gradle.
`brew gist-logs gradle`
Error: No logs.

brew upgrade gradle

==> Upgrading 1 outdated package, with result:
gradle 3.0
==> Upgrading gradle
==> Using the sandbox
Error: undefined method `>=' for nil:NilClass
Please report this bug:
    https://git.io/brew-troubleshooting
/usr/local/Library/Homebrew/extend/os/mac/extend/ENV/shared.rb:4:in `no_weak_imports?'
/usr/local/Library/Homebrew/extend/os/mac/extend/ENV/super.rb:87:in `determine_cccfg'
/usr/local/Library/Homebrew/extend/ENV/super.rb:48:in `setup_build_environment'
/usr/local/Library/Homebrew/extend/os/mac/extend/ENV/super.rb:93:in `setup_build_environment'
/usr/local/Library/Homebrew/build.rb:86:in `install'
/usr/local/Library/Homebrew/build.rb:179:in `<main>'

**Comment by gribnut** [comment]
Thank you Mike.  All working well after your fix.
