### ISSUE TITLE
<formula unkonwn> undefined method `rebuild' 

### ISSUE THREAD

**Issue by appkr** [Homebrew/homebrew-core#4204]
If Homebrew was updated on Aug 10-11th 2016 and `brew update` always says `Already up-to-date.` you need to run: `cd $(brew --repo); git fetch; git reset --hard origin/master; brew update`.

# Please follow the general troubleshooting steps first:

- [v] Ran `brew update` and retried your prior step?
- [v ] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?
- [ ] If you're seeing permission errors tried running `sudo chown -R $(whoami) $(brew --prefix)`?

_You can erase any parts of this template not applicable to your Issue._

### Bug reports:

I got this message when I ran `brew doctor`

```sh
Error: undefined method `rebuild' for #<BottleSpecification:0x007fd359befe90>
Please report this bug:
    https://git.io/brew-troubleshooting
/usr/local/Library/Taps/homebrew/homebrew-php/Formula/php56.rb:16:in `block in <class:Php56>'
/usr/local/Library/Homebrew/software_spec.rb:91:in `instance_eval'
/usr/local/Library/Homebrew/software_spec.rb:91:in `bottle'
/usr/local/Library/Homebrew/formula.rb:1737:in `bottle'
/usr/local/Library/Taps/homebrew/homebrew-php/Formula/php56.rb:15:in `<class:Php56>'
/usr/local/Library/Taps/homebrew/homebrew-php/Formula/php56.rb:3:in `load_formula'
/usr/local/Library/Homebrew/formulary.rb:25:in `module_eval'
/usr/local/Library/Homebrew/formulary.rb:25:in `load_formula'
/usr/local/Library/Homebrew/formulary.rb:42:in `load_formula_from_path'
/usr/local/Library/Homebrew/formulary.rb:91:in `load_file'
/usr/local/Library/Homebrew/formulary.rb:82:in `klass'
/usr/local/Library/Homebrew/formulary.rb:78:in `get_formula'
/usr/local/Library/Homebrew/formulary.rb:215:in `factory'
/usr/local/Library/Homebrew/formula.rb:1187:in `[]'
/usr/local/Library/Taps/homebrew/homebrew-php/Requirements/php-meta-requirement.rb:14:in `<class:PhpMetaRequirement>'
/usr/local/Library/Taps/homebrew/homebrew-php/Requirements/php-meta-requirement.rb:3:in `<top (required)>'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/usr/local/Library/Taps/homebrew/homebrew-php/Abstract/abstract-php-phar.rb:2:in `<top (required)>'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/usr/local/Library/Taps/homebrew/homebrew-php/Formula/composer.rb:1:in `load_formula'
/usr/local/Library/Homebrew/formulary.rb:25:in `module_eval'
/usr/local/Library/Homebrew/formulary.rb:25:in `load_formula'
/usr/local/Library/Homebrew/formulary.rb:42:in `load_formula_from_path'
/usr/local/Library/Homebrew/formulary.rb:91:in `load_file'
/usr/local/Library/Homebrew/formulary.rb:82:in `klass'
/usr/local/Library/Homebrew/formulary.rb:78:in `get_formula'
/usr/local/Library/Homebrew/formulary.rb:175:in `get_formula'
/usr/local/Library/Homebrew/formulary.rb:215:in `factory'
/usr/local/Library/Homebrew/formulary.rb:234:in `from_rack'
/usr/local/Library/Homebrew/formula.rb:1138:in `block in installed'
/usr/local/Library/Homebrew/formula.rb:1136:in `map'
/usr/local/Library/Homebrew/formula.rb:1136:in `installed'
/usr/local/Library/Homebrew/diagnostic.rb:899:in `check_missing_deps'
/usr/local/Library/Homebrew/cmd/doctor.rb:42:in `block in doctor'
/usr/local/Library/Homebrew/cmd/doctor.rb:35:in `each'
/usr/local/Library/Homebrew/cmd/doctor.rb:35:in `doctor'
/usr/local/Library/brew.rb:87:in `<main>'
```

### Formula Requests:

**Please note by far the quickest way to get a new formula into Homebrew is to file a [Pull Request](https://github.com/Homebrew/homebrew-core/blob/master/.github/CONTRIBUTING.md).**

We will consider your request but it may be closed if it's something we're not actively planning to work on.

**Comment by MikeMcQuaid** [comment]
Sorry but you have not followed the requested steps on [the Troubleshooting page](https://github.com/Homebrew/brew/blob/master/share/doc/homebrew/Troubleshooting.md#troubleshooting)

Please follow (all of) these steps and post the information here so we can help you with your problem.

Thanks!

**Comment by appkr** [comment]
Sorry for interrupting you. I manage to fix the problem, but I don't remember what I did. Anyway thanks.

**Comment by heisjoe** [comment]
I did the following code to  resolve the problem 
```
cd $(brew --prefix)
rm Library/Formula/argp-standalone.rb
rm Library/Formula/cocot.rb
```
And then do the
```
git fetch origin
git reset --hard origin/master
brew update
```
i  dont know why but it done

**Comment by WadeShuler** [comment]
Followed the OP's instructions:

    cd $(brew --repo); git fetch; git reset --hard origin/master; brew update

Worked like a charm :) This should be on the main README as a failsafe to force brew to update so we can get back in action.

**Comment by retokromer** [comment]
Actually it is! https://github.com/Homebrew/brew

**Comment by WadeShuler** [comment]
oh wow. maybe i was on another page or just scrolled right past it not expecting it to be the very first thing..
