### ISSUE TITLE
`module_eval' failed to build on 10.9.5; chokes on <html lang="en" class="">

### ISSUE THREAD

**Issue by rdmoore6** [Homebrew/homebrew-core#4224]
If Homebrew was updated on Aug 10-11th 2016 and `brew update` always says `Already up-to-date.` you need to run: `cd $(brew --repo); git fetch; git reset --hard origin/master; brew update`.

### Bug reports:

`brew gist-logs <formula>`
(where `<formula>` is the name of the formula that failed to build).

An attempt to: brew install https://github.com/google/protobuf/releases/tag/v3.0.0 failed due to unexpected HTML in the document.  First two non-blank lines are:
```
<!DOCTYPE html>
<html lang="en" class="">
```

```
Exported Terminal Log Text follows (failure is at the end).
________________________________________________________________________
Last login: Thu Aug 25 03:40:58 on ttys001
roger-mini-local-5:~ rogermoo$ brew upgrade
==> Auto-updated Homebrew!
Updated Homebrew from 4f6a46f to 6e535e1.
Updated 1 tap (homebrew/core).
==> Updated Formulae
konoha          ncdu            openvpn         sngrep          tailor        
mkvtoolnix      open-mpi        pcap_dnsproxy   swiftlint     
brew upgrade
==> Upgrading 5 outdated packages, with result:
boost 1.61.0_1, git 2.9.3, libpng 1.6.24, postgresql 9.5.4, sqlite 3.14.1
==> Upgrading boost
==> Downloading https://homebrew.bintray.com/bottles/boost-1.61.0_1.mavericks.bo
######################################################################## 100.0%
==> Pouring boost-1.61.0_1.mavericks.bottle.tar.gz
🍺  /usr/local/Cellar/boost/1.61.0_1: 12,259 files, 419.8M
==> Upgrading git
==> Downloading https://homebrew.bintray.com/bottles/git-2.9.3.mavericks.bottle.
######################################################################## 100.0%
==> Pouring git-2.9.3.mavericks.bottle.tar.gz
==> Caveats
Bash completion has been installed to:
  /usr/local/etc/bash_completion.d

zsh completion has been installed to:
  /usr/local/share/zsh/site-functions

Emacs Lisp files have been installed to:
  /usr/local/share/emacs/site-lisp/git
==> Summary
🍺  /usr/local/Cellar/git/2.9.3: 1,428 files, 31.5M
==> Upgrading libpng
==> Downloading https://homebrew.bintray.com/bottles/libpng-1.6.24.mavericks.bot
######################################################################## 100.0%
==> Pouring libpng-1.6.24.mavericks.bottle.tar.gz
🍺  /usr/local/Cellar/libpng/1.6.24: 26 files, 1.2M
==> Upgrading postgresql
==> Downloading https://homebrew.bintray.com/bottles/postgresql-9.5.4.mavericks.
######################################################################## 100.0%
==> Pouring postgresql-9.5.4.mavericks.bottle.tar.gz
==> Using the sandbox
==> Caveats
If builds of PostgreSQL 9 are failing and you have version 8.x installed,
you may need to remove the previous version first. See:
  https://github.com/Homebrew/homebrew/issues/2510

To migrate existing data from a previous major version (pre-9.0) of PostgreSQL, see:
  https://www.postgresql.org/docs/9.5/static/upgrading.html

To migrate existing data from a previous minor version (9.0-9.4) of PostgreSQL, see:
  https://www.postgresql.org/docs/9.5/static/pgupgrade.html

  You will need your previous PostgreSQL installation from brew to perform `pg_upgrade`.
  Do not run `brew cleanup postgresql` until you have performed the migration.

To have launchd start postgresql now and restart at login:
  brew services start postgresql
Or, if you don't want/need a background service you can just run:
  postgres -D /usr/local/var/postgres
==> Summary
🍺  /usr/local/Cellar/postgresql/9.5.4: 3,147 files, 35.3M
==> Upgrading sqlite
==> Downloading https://homebrew.bintray.com/bottles/sqlite-3.14.1.mavericks.bot
######################################################################## 100.0%
==> Pouring sqlite-3.14.1.mavericks.bottle.tar.gz
==> Caveats
This formula is keg-only, which means it was not symlinked into /usr/local.

OS X provides an older sqlite3.

Generally there are no consequences of this for you. If you build your
own software and it requires this formula, you'll need to add to your
build variables:

    LDFLAGS:  -L/usr/local/opt/sqlite/lib
    CPPFLAGS: -I/usr/local/opt/sqlite/include

==> Summary
🍺  /usr/local/Cellar/sqlite/3.14.1: 10 files, 3M
roger-mini-local-5:~ rogermoo$ brew upgrade
roger-mini-local-5:~ rogermoo$ brew ugrade
Error: Unknown command: ugrade
roger-mini-local-5:~ rogermoo$ brew upgrade
roger-mini-local-5:~ rogermoo$ cd Documents/Miscƒ/PkemonGoƒ/BrewPlayPen
-bash: cd: Documents/Miscƒ/PkemonGoƒ/BrewPlayPen: No such file or directory
roger-mini-local-5:~ rogermoo$ cd Documents/Miscƒ/PokemonGoƒ/BrewPlayPen
roger-mini-local-5:BrewPlayPen rogermoo$ pwd
/Users/rogermoo/Documents/Miscƒ/PokemonGoƒ/BrewPlayPen
roger-mini-local-5:BrewPlayPen rogermoo$ brew install https://github.com/google/protobuf/releases/tag/v3.0.0
######################################################################## 100.0%
Error: /Users/rogermoo/Library/Caches/Homebrew/Formula/v3.0.0:5: syntax error, unexpected '<'
<!DOCTYPE html>
 ^
/Users/rogermoo/Library/Caches/Homebrew/Formula/v3.0.0:6: syntax error, unexpected '<'
<html lang="en" class="">
 ^
/Users/rogermoo/Library/Caches/Homebrew/Formula/v3.0.0:6: syntax error, unexpected keyword_class, expecting end-of-input
<html lang="en" class="">
                     ^
Please report this bug:
    https://git.io/brew-troubleshooting
/usr/local/Library/Homebrew/formulary.rb:25:in `module_eval'
/usr/local/Library/Homebrew/formulary.rb:25:in `load_formula'
/usr/local/Library/Homebrew/formulary.rb:42:in `load_formula_from_path'
/usr/local/Library/Homebrew/formulary.rb:91:in `load_file'
/usr/local/Library/Homebrew/formulary.rb:146:in `load_file'
/usr/local/Library/Homebrew/formulary.rb:82:in `klass'
/usr/local/Library/Homebrew/formulary.rb:78:in `get_formula'
/usr/local/Library/Homebrew/formulary.rb:215:in `factory'
/usr/local/Library/Homebrew/extend/ARGV.rb:18:in `block in formulae'
/usr/local/Library/Homebrew/extend/ARGV.rb:16:in `map'
/usr/local/Library/Homebrew/extend/ARGV.rb:16:in `formulae'
/usr/local/Library/Homebrew/cmd/install.rb:102:in `install'
/usr/local/Library/Homebrew/brew.rb:91:in `<main>'
roger-mini-local-5:BrewPlayPen rogermoo$ 
```

**Comment by MikeMcQuaid** [comment]
Sorry but you have not followed the requested steps on [the Troubleshooting page](https://github.com/Homebrew/brew/blob/master/share/doc/homebrew/Troubleshooting.md#troubleshooting)

Please follow (all of) these steps and post the information here so we can help you with your problem.

Thanks!

**Comment by DomT4** [comment]
You're attempting to install a webpage. `brew install` can only install formulae, whether local or remote. You can `brew create` from a git repo or a tagged release, but you can't `install` arbitrary things. You may wish to track https://github.com/Homebrew/homebrew-core/pull/4145, by the looks of it.
