### ISSUE TITLE
Brew upgrade error on Mac Catalina 10.15

### ISSUE THREAD

**Issue by jtsom** [Homebrew/homebrew-core#45187]
Error displayed when doing a 'brew upgrade'

details in gist:

https://gist.github.com/jtsom/c1f127b16c765825d768b5eb4773c78e

**Comment by TylerADavis** [comment]
I saw something similar, though with this being the final output before the huge error trace:
```
==> Summary
🍺  /usr/local/Cellar/mosh/1.3.2_9: 14 files, 847.2KB
Removing: /usr/local/Cellar/mosh/1.3.2_5... (14 files, 876.5KB)
Removing: /usr/local/Cellar/gsettings-desktop-schemas/3.32.0... (96 files, 4MB)
Removing: /usr/local/Cellar/ocaml/4.07.1... (2,113 files, 237.2MB)
```

**Comment by 9mm** [comment]
Same

```
🍺  /usr/local/Cellar/ffmpeg/4.2.1_1: 287 files, 56.6MB
Removing: /usr/local/Cellar/ffmpeg/4.2.1... (287 files, 56.5MB)
Removing: /usr/local/Cellar/x264/r2917... (11 files, 5.9MB)
Removing: /usr/local/Cellar/x265/3.1.2... (11 files, 35.2MB)
Error: stack level too deep
Please report this bug:
  https://docs.brew.sh/Troubleshooting
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/pathname.rb:46:in `chop_basename'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/pathname.rb:359:in `plus'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/pathname.rb:351:in `+'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:452:in `core_path'
/usr/local/Homebrew/Library/Homebrew/formula.rb:185:in `initialize'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:114:in `new'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:114:in `get_formula'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:317:in `factory'
/usr/local/Homebrew/Library/Homebrew/dependency.rb:37:in `to_formula'
/usr/local/Homebrew/Library/Homebrew/dependency.rb:105:in `block in expand'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/delegate.rb:349:in `each'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/delegate.rb:349:in `block in delegating_block'
/usr/local/Homebrew/Library/Homebrew/dependency.rb:87:in `expand'
/usr/local/Homebrew/Library/Homebrew/dependency.rb:105:in `block in expand'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/delegate.rb:349:in `each'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/delegate.rb:349:in `block in delegating_block'
/usr/local/Homebrew/Library/Homebrew/dependency.rb:87:in `expand'
/usr/local/Homebrew/Library/Homebrew/dependency.rb:105:in `block in expand'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/delegate.rb:349:in `each'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/delegate.rb:349:in `block in delegating_block'
/usr/local/Homebrew/Library/Homebrew/dependency.rb:87:in `expand'
/usr/local/Homebrew/Library/Homebrew/dependency.rb:105:in `block in expand'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/delegate.rb:349:in `each'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/delegate.rb:349:in `block in delegating_block'
/usr/local/Homebrew/Library/Homebrew/dependency.rb:87:in `expand'
/usr/local/Homebrew/Library/Homebrew/dependency.rb:105:in `block in expand'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/delegate.rb:349:in `each'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/delegate.rb:349:in `block in delegating_block'
/usr/local/Homebrew/Library/Homebrew/dependency.rb:87:in `expand'
/usr/local/Homebrew/Library/Homebrew/dependency.rb:105:in `block in expand'
```

**Comment by derekschinke** [comment]
Same exact bug for me

**Comment by gesa** [comment]
Catalina may be a red herring. I'm still on Mojave (14.6) and got the same error this evening. Re-running my intended commands (below)… i can't confidently say it _resolved_ the issue, but i have no further specific problems to speak of.

```
[~] brew update && brew upgrade && brew cleanup
Already up-to-date.
Pruned 0 symbolic links and 7 directories from /usr/local
[~] brew doctor
Your system is ready to brew.
[~] brew update && brew upgrade && brew cleanup
Already up-to-date.
Updating Homebrew...
```

see absurdly lengthy recursive [console output](https://gist.github.com/gesa/367f6a5cfcd910015b45e56b3facc7c3)

**Comment by forquare** [comment]
10.14.6 here also.  [Console log](https://gist.github.com/forquare/6edf6598a4293a4e3c660861a122ab7b).

**Comment by enkunkun** [comment]
I got same error on Mojave (10.14.6).

[console output](https://gist.github.com/enkunkun/602c12ecffe0ef74618e8a4b92ea1b95)

**Comment by blirp** [comment]
Seeing the same thing when upgrading meson:
```==> Pouring meson-0.52.0.catalina.bottle.tar.gz
🍺  /usr/local/Cellar/meson/0.52.0: 139 files, 2.2MB
Removing: /usr/local/Cellar/meson/0.51.2... (122 files, 2MB)
Removing: /Users/<user>/Library/Caches/Homebrew/meson--0.51.2.mojave.bottle.tar.gz... (444.6KB)
Removing: /usr/local/Cellar/x264/r2917... (11 files, 5.9MB)
Removing: /usr/local/Cellar/x265/3.1.2... (11 files, 35.2MB)
Error: stack level too deep
Please report this bug:
  https://docs.brew.sh/Troubleshooting
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/pathname.rb:46:in `chop_basename'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/pathname.rb:359:in `plus'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/pathname.rb:351:in `+'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:452:in `core_path'
/usr/local/Homebrew/Library/Homebrew/formula.rb:185:in `initialize'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:114:in `new'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:114:in `get_formula'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:317:in `factory'
/usr/local/Homebrew/Library/Homebrew/dependency.rb:37:in `to_formula'
/usr/local/Homebrew/Library/Homebrew/dependency.rb:105:in `block in expand'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/delegate.rb:349:in `each'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/delegate.rb:349:in `block in delegating_block'
/usr/local/Homebrew/Library/Homebrew/dependency.rb:87:in `expand'
/usr/local/Homebrew/Library/Homebrew/dependency.rb:105:in `block in expand'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/delegate.rb:349:in `each'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/delegate.rb:349:in `block in delegating_block'
/usr/local/Homebrew/Library/Homebrew/dependency.rb:87:in `expand'
/usr/local/Homebrew/Library/Homebrew/dependency.rb:105:in `block in expand'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/delegate.rb:349:in `each'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/delegate.rb:349:in `block in delegating_block'
/usr/local/Homebrew/Library/Homebrew/dependency.rb:87:in `expand'
/usr/local/Homebrew/Library/Homebrew/dependency.rb:105:in `block in expand'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/delegate.rb:349:in `each'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/delegate.rb:349:in `block in delegating_block'
/usr/local/Homebrew/Library/Homebrew/dependency.rb:87:in `expand'
/usr/local/Homebrew/Library/Homebrew/dependency.rb:105:in `block in expand'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/delegate.rb:349:in `each'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/delegate.rb:349:in `block in delegating_block'
/usr/local/Homebrew/Library/Homebrew/dependency.rb:87:in `expand'
/usr/local/Homebrew/Library/Homebrew/dependency.rb:105:in `block in expand'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/delegate.rb:349:in `each'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/delegate.rb:349:in `block in delegating_block'
/usr/local/Homebrew/Library/Homebrew/dependency.rb:87:in `expand'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1521:in `recursive_dependencies'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1778:in `declared_runtime_dependencies'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1556:in `runtime_dependencies'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1564:in `runtime_formula_dependencies'
/usr/local/Homebrew/Library/Homebrew/linkage_checker.rb:168:in `check_formula_deps'
/usr/local/Homebrew/Library/Homebrew/linkage_checker.rb:145:in `check_dylibs'
/usr/local/Homebrew/Library/Homebrew/linkage_checker.rb:27:in `initialize'
/usr/local/Homebrew/Library/Homebrew/cmd/upgrade.rb:279:in `new'
/usr/local/Homebrew/Library/Homebrew/cmd/upgrade.rb:279:in `block (3 levels) in broken_dependents'
/usr/local/Homebrew/Library/Homebrew/cmd/upgrade.rb:273:in `each'
/usr/local/Homebrew/Library/Homebrew/cmd/upgrade.rb:273:in `block (2 levels) in broken_dependents'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/set.rb:338:in `each_key'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/set.rb:338:in `each'
/usr/local/Homebrew/Library/Homebrew/cmd/upgrade.rb:263:in `block in broken_dependents'
/usr/local/Homebrew/Library/Homebrew/cache_store.rb:17:in `use
/usr/local/Homebrew/Library/Homebrew/cmd/upgrade.rb:262:in `broken_dependents'
/usr/local/Homebrew/Library/Homebrew/cmd/upgrade.rb:293:in `block (2 levels) in broken_dependents'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/set.rb:338:in `each_key'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/set.rb:338:in `each'
/usr/local/Homebrew/Library/Homebrew/cmd/upgrade.rb:263:in `block in broken_dependents'
'```
Where those last 6 lines repeats until failure, ending with: ```/usr/local/Homebrew/Library/Homebrew/cmd/upgrade.rb:263:in `block in broken_dependents'
/usr/local/Homebrew/Library/Homebrew/cache_store.rb:17:in `use'
/usr/local/Homebrew/Library/Homebrew/cmd/upgrade.rb:262:in `broken_dependents'
/usr/local/Homebrew/Library/Homebrew/cmd/upgrade.rb:293:in `block (2 levels) in broken_dependents'
/usr/local/Homebrew/Library/Homebrew/cmd/upgrade.rb:263:in `each'
/usr/local/Homebrew/Library/Homebrew/cmd/upgrade.rb:263:in `block in broken_dependents'
/usr/local/Homebrew/Library/Homebrew/cache_store.rb:17:in `use'
/usr/local/Homebrew/Library/Homebrew/cmd/upgrade.rb:262:in `broken_dependents'
/usr/local/Homebrew/Library/Homebrew/cmd/upgrade.rb:364:in `check_dependents'
/usr/local/Homebrew/Library/Homebrew/cmd/upgrade.rb:114:in `upgrade'
/usr/local/Homebrew/Library/Homebrew/brew.rb:102:in `<main>'```

**Comment by pelargir** [comment]
Same error upgrading ffmpeg on Catalina:

```
==> Pouring ffmpeg-4.2.1_1.catalina.bottle.tar.gz
🍺  /usr/local/Cellar/ffmpeg/4.2.1_1: 287 files, 56.6MB
Removing: /usr/local/Cellar/ffmpeg/4.2.1... (287 files, 56.5MB)
Removing: /usr/local/Cellar/x264/r2917... (11 files, 5.9MB)
Removing: /usr/local/Cellar/x265/3.1.2... (11 files, 35.2MB)
Removing: /Users/pelargir/Library/Caches/Homebrew/x265--3.1.2.mojave.bottle.tar.gz... (4.8MB)
Error: stack level too deep
```

**Comment by j-e-clark** [comment]
I got the same upgrading ffmpeg on Mojave (10.14.6) so it's not limited to Catalina.

**Comment by knetch** [comment]
Different error when upgrading ffmpeg.
(Still on Mojave after failed Catalina update)

```
==> Pouring libheif-1.5.1_1.mojave.bottle.tar.gz
==> /usr/local/opt/shared-mime-info/bin/update-mime-database /usr/local/share/mime
🍺  /usr/local/Cellar/libheif/1.5.1_1: 19 files, 2.3MB
Removing: /usr/local/Cellar/libheif/1.5.1... (19 files, 2.3MB)
Error: stack level too deep
Please report this bug:
  https://docs.brew.sh/Troubleshooting
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3/lib/ruby/2.6.0/pathname.rb:42:in `chop_basename'
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3/lib/ruby/2.6.0/pathname.rb:359:in `plus'
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3/lib/ruby/2.6.0/pathname.rb:351:in `+'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:452:in `core_path'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:409:in `loader_for'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:317:in `factory'
/usr/local/Homebrew/Library/Homebrew/dependency.rb:37:in `to_formula'
/usr/local/Homebrew/Library/Homebrew/dependency.rb:105:in `block in expand'
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3/lib/ruby/2.6.0/delegate.rb:349:in `each'
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3/lib/ruby/2.6.0/delegate.rb:349:in `block in delegating_block'
/usr/local/Homebrew/Library/Homebrew/dependency.rb:87:in `expand'
/usr/local/Homebrew/Library/Homebrew/dependency.rb:105:in `block in expand'
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3/lib/ruby/2.6.0/delegate.rb:349:in `each'
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3/lib/ruby/2.6.0/delegate.rb:349:in `block in delegating_block'
/usr/local/Homebrew/Library/Homebrew/dependency.rb:87:in `expand'
etc etc etc etc
```

**Comment by CarterPape** [comment]
same for me also as well

**Comment by gmw** [comment]
Same here, with Xcode 11.0
$ uname -a
Darwin macaroon.lan 19.0.0 Darwin Kernel Version 19.0.0: Wed Sep 25 20:18:50 PDT 2019; root:xnu-6153.11.26~2/RELEASE_X86_64 x86_64
$ brew --version
Homebrew [2.1.13]
Homebrew/homebrew-core (git revision 61d6a; last commit 2019-10-12)
[Homebrew error log](https://gist.github.com/gmw/e449a3e05092870018500e22b90a7e90)

**Comment by hannesbraun** [comment]
Same here with macOS 10.14.6
[Console output](https://gist.github.com/hannesbraun/a2b0b3be642979de28a881a5a9ad202f)

**Comment by tatoalo** [comment]
Same error trying to:
```
==> Upgrading ffmpeg 
==> Installing dependencies for ffmpeg: x264
==> Installing ffmpeg dependency: x264
```
I'm on MacOS Mojave 10.14.6, though.

**Comment by jcolson** [comment]
on mojave as well ... same issue:

`==> Pouring ffmpeg-4.2.1_1.mojave.bottle.tar.gz
🍺  /usr/local/Cellar/ffmpeg/4.2.1_1: 287 files, 56.5MB
Removing: /usr/local/Cellar/ffmpeg/4.2.1... (287 files, 56.5MB)
Removing: /usr/local/Cellar/x264/r2917... (11 files, 5.9MB)
Removing: /usr/local/Cellar/x265/3.1.2... (11 files, 35.2MB)
Removing: /Users/jcolson/Library/Caches/Homebrew/x265--3.1.2.mojave.bottle.tar.gz... (4.8MB)
Error: stack level too deep
Please report this bug:
  https://docs.brew.sh/Troubleshooting
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/pathname.rb:40:in ... `
