### ISSUE TITLE
brew update broken (Mavericks, Yosemite, Sierra) on gnupg - undefined local variable or method `shell_profile'

### ISSUE THREAD

**Issue by bobsummerwill** [Homebrew/homebrew-core#4527]
In the last few hours, something has changed which is breaking `brew update` for all our TravisCI images - Mavericks, Yosemite and Sierra in exactly the same way.

    Upgrading gnupg
    ==> Downloading https://homebrew.bintray.com/bottles/gnupg-1.4.21.el_capitan.bot
    ==> Pouring gnupg-1.4.21.el_capitan.bottle.1.tar.gz
    Error: undefined local variable or method `shell_profile' for #<Formulary::FormulaNamespace5dd7b37cba9aa4eb2dc45b970786b8c0::Gnupg:0x007fed41433da8>
    Please report this bug:
        https://git.io/brew-troubleshooting
    /usr/local/Library/Taps/homebrew/homebrew-core/Formula/gnupg.rb:56:in `caveats'
    /usr/local/Library/Homebrew/caveats.rb:12:in `caveats'

See:

Happy - https://travis-ci.org/ethereum/cpp-ethereum/builds/157487980

Sad - https://travis-ci.org/ethereum/cpp-ethereum/builds/157538329

**Comment by bobsummerwill** [comment]
Looks like the last change to that package's formula was 5 days ago, by @DomT4:

https://github.com/Homebrew/homebrew-core/commits/master/Formula/gnupg.rb

But I can pinpoint this failure to somewhere within the last 8 hours or so at the time of writing.

It is conceivable that something changed within the TravisCI VM images, but from the error message it looks like something more fundamental with this undefined `shell_profile` symbol.

**Comment by bobsummerwill** [comment]
From the timing and the PR description, @MikeMcQuaid, I suspect that this is a knock-on from this pull request which was merged 8 hours ago ...

https://github.com/Homebrew/brew/pull/201

**Comment by bobsummerwill** [comment]
Closed.

This is a dupe of an issue logged 5 hours ago by @WillAbides, reporting the exact same issue.

See https://github.com/Homebrew/brew/issues/875
