### ISSUE TITLE
brew install postgres borks with error " undefined method `rebuild' for #<BottleSpecification:0x007f7f8b2d2320>"

### ISSUE THREAD

**Issue by ivankocienski** [Homebrew/homebrew-core#4607]
### brew install postgresql (crashes)

```
Error: undefined method `rebuild' for #<BottleSpecification:0x007f7f8b2d2320>
Please report this bug:
    https://git.io/brew-troubleshooting
/usr/local/Library/Taps/homebrew/homebrew-core/Formula/postgresql.rb:8:in `block in     <class:Postgresql>'
/usr/local/Library/Homebrew/software_spec.rb:91:in `instance_eval'
/usr/local/Library/Homebrew/software_spec.rb:91:in `bottle'
/usr/local/Library/Homebrew/formula.rb:1726:in `bottle'
/usr/local/Library/Taps/homebrew/homebrew-core/Formula/postgresql.rb:7:in   `<class:Postgresql>'
/usr/local/Library/Taps/homebrew/homebrew-core/Formula/postgresql.rb:1:in `load_formula'
/usr/local/Library/Homebrew/formulary.rb:21:in `module_eval'
/usr/local/Library/Homebrew/formulary.rb:21:in `load_formula'
/usr/local/Library/Homebrew/formulary.rb:34:in `load_formula_from_path'
/usr/local/Library/Homebrew/formulary.rb:83:in `load_file'
/usr/local/Library/Homebrew/formulary.rb:74:in `klass'
/usr/local/Library/Homebrew/formulary.rb:70:in `get_formula'
/usr/local/Library/Homebrew/formulary.rb:207:in `factory'
/usr/local/Library/Homebrew/formulary.rb:216:in `from_rack'
/usr/local/Library/Homebrew/extend/ARGV.rb:37:in `block in resolved_formulae'
/usr/local/Library/Homebrew/extend/ARGV.rb:27:in `map'
/usr/local/Library/Homebrew/extend/ARGV.rb:27:in `resolved_formulae'
/usr/local/Library/Homebrew/cmd/gist-logs.rb:164:in `gist_logs'
/usr/local/Library/brew.rb:97:in `<main>'
```
### brew update

```
Unpacking objects: 100% (18/18), done.
error: The following untracked working tree files would be overwritten by merge:
    share/man/man1/brew-cask.1
Please move or remove them before you can merge.
Aborting
Updated 1 tap (caskroom/cask).
No changes to formulae.
```
### brew doctor

```
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry and just ignore them. Thanks!

Warning: "config" scripts exist outside your system or Homebrew directories.
`./configure` scripts often look for *-config scripts to determine if
software packages are installed, and what additional flags to use when
compiling and linking.

Having additional scripts in your path can confuse software installed via
Homebrew if the config script overrides a system or Homebrew provided
script of the same name. We found the following "config" scripts:
    /Library/Frameworks/Python.framework/Versions/3.5/bin/python3-config
    /Library/Frameworks/Python.framework/Versions/3.5/bin/python3.5-config
    /Library/Frameworks/Python.framework/Versions/3.5/bin/python3.5m-config
    /opt/local/bin/python-config

Warning: Python is installed at /Library/Frameworks/Python.framework

Homebrew only supports building against the System-provided Python or a
brewed Python. In particular, Pythons installed to /Library can interfere
with other software installs.

Warning: You have MacPorts or Fink installed:
  /opt/local/bin/port

This can cause trouble. You don't have to uninstall them, but you may want to
temporarily move them out of the way, e.g.

  sudo mv /opt/local ~/macports

Warning: You have leftover files from an older version of Xcode.
You should delete them using:
  /Developer/Library/uninstall-developer-folder

Warning: Unbrewed header files were found in /usr/local/include.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected header files:
    /usr/local/include/GLFW/glfw3.h
    /usr/local/include/GLFW/glfw3native.h
    /usr/local/include/node/android-ifaddrs.h
    /usr/local/include/node/ares.h
    /usr/local/include/node/ares_version.h
    /usr/local/include/node/libplatform/libplatform.h
    /usr/local/include/node/nameser.h
    /usr/local/include/node/node.h
    /usr/local/include/node/node_buffer.h
    /usr/local/include/node/node_internals.h
    /usr/local/include/node/node_object_wrap.h
    /usr/local/include/node/node_version.h
    /usr/local/include/node/openssl/aes.h
    /usr/local/include/node/openssl/archs/aix-gcc/opensslconf.h
    /usr/local/include/node/openssl/archs/aix64-gcc/opensslconf.h
    /usr/local/include/node/openssl/archs/BSD-x86/opensslconf.h
    /usr/local/include/node/openssl/archs/BSD-x86_64/opensslconf.h
    /usr/local/include/node/openssl/archs/darwin-i386-cc/opensslconf.h
    /usr/local/include/node/openssl/archs/darwin64-x86_64-cc/opensslconf.h
    /usr/local/include/node/openssl/archs/linux-aarch64/opensslconf.h
    /usr/local/include/node/openssl/archs/linux-armv4/opensslconf.h
    /usr/local/include/node/openssl/archs/linux-elf/opensslconf.h
    /usr/local/include/node/openssl/archs/linux-ppc/opensslconf.h
    /usr/local/include/node/openssl/archs/linux-ppc64/opensslconf.h
    /usr/local/include/node/openssl/archs/linux-x32/opensslconf.h
    /usr/local/include/node/openssl/archs/linux-x86_64/opensslconf.h
    /usr/local/include/node/openssl/archs/solaris-x86-gcc/opensslconf.h
    /usr/local/include/node/openssl/archs/solaris64-x86_64-gcc/opensslconf.h
    /usr/local/include/node/openssl/archs/VC-WIN32/opensslconf.h
    /usr/local/include/node/openssl/archs/VC-WIN64A/opensslconf.h
    /usr/local/include/node/openssl/asn1.h
    /usr/local/include/node/openssl/asn1_mac.h
    /usr/local/include/node/openssl/asn1t.h
    /usr/local/include/node/openssl/bio.h
    /usr/local/include/node/openssl/blowfish.h
    /usr/local/include/node/openssl/bn.h
    /usr/local/include/node/openssl/buffer.h
    /usr/local/include/node/openssl/camellia.h
    /usr/local/include/node/openssl/cast.h
    /usr/local/include/node/openssl/cmac.h
    /usr/local/include/node/openssl/cms.h
    /usr/local/include/node/openssl/comp.h
    /usr/local/include/node/openssl/conf.h
    /usr/local/include/node/openssl/conf_api.h
    /usr/local/include/node/openssl/crypto.h
    /usr/local/include/node/openssl/des.h
    /usr/local/include/node/openssl/des_old.h
    /usr/local/include/node/openssl/dh.h
    /usr/local/include/node/openssl/dsa.h
    /usr/local/include/node/openssl/dso.h
    /usr/local/include/node/openssl/dtls1.h
    /usr/local/include/node/openssl/e_os2.h
    /usr/local/include/node/openssl/ebcdic.h
    /usr/local/include/node/openssl/ec.h
    /usr/local/include/node/openssl/ecdh.h
    /usr/local/include/node/openssl/ecdsa.h
    /usr/local/include/node/openssl/engine.h
    /usr/local/include/node/openssl/err.h
    /usr/local/include/node/openssl/evp.h
    /usr/local/include/node/openssl/hmac.h
    /usr/local/include/node/openssl/idea.h
    /usr/local/include/node/openssl/krb5_asn.h
    /usr/local/include/node/openssl/kssl.h
    /usr/local/include/node/openssl/lhash.h
    /usr/local/include/node/openssl/md4.h
    /usr/local/include/node/openssl/md5.h
    /usr/local/include/node/openssl/mdc2.h
    /usr/local/include/node/openssl/modes.h
    /usr/local/include/node/openssl/obj_mac.h
    /usr/local/include/node/openssl/objects.h
    /usr/local/include/node/openssl/ocsp.h
    /usr/local/include/node/openssl/opensslconf.h
    /usr/local/include/node/openssl/opensslv.h
    /usr/local/include/node/openssl/ossl_typ.h
    /usr/local/include/node/openssl/pem.h
    /usr/local/include/node/openssl/pem2.h
    /usr/local/include/node/openssl/pkcs12.h
    /usr/local/include/node/openssl/pkcs7.h
    /usr/local/include/node/openssl/pqueue.h
    /usr/local/include/node/openssl/rand.h
    /usr/local/include/node/openssl/rc2.h
    /usr/local/include/node/openssl/rc4.h
    /usr/local/include/node/openssl/ripemd.h
    /usr/local/include/node/openssl/rsa.h
    /usr/local/include/node/openssl/safestack.h
    /usr/local/include/node/openssl/seed.h
    /usr/local/include/node/openssl/sha.h
    /usr/local/include/node/openssl/srp.h
    /usr/local/include/node/openssl/srtp.h
    /usr/local/include/node/openssl/ssl.h
    /usr/local/include/node/openssl/ssl2.h
    /usr/local/include/node/openssl/ssl23.h
    /usr/local/include/node/openssl/ssl3.h
    /usr/local/include/node/openssl/stack.h
    /usr/local/include/node/openssl/symhacks.h
    /usr/local/include/node/openssl/tls1.h
    /usr/local/include/node/openssl/ts.h
    /usr/local/include/node/openssl/txt_db.h
    /usr/local/include/node/openssl/ui.h
    /usr/local/include/node/openssl/ui_compat.h
    /usr/local/include/node/openssl/whrlpool.h
    /usr/local/include/node/openssl/x509.h
    /usr/local/include/node/openssl/x509_vfy.h
    /usr/local/include/node/openssl/x509v3.h
    /usr/local/include/node/pthread-fixes.h
    /usr/local/include/node/stdint-msvc2008.h
    /usr/local/include/node/tree.h
    /usr/local/include/node/uv-aix.h
    /usr/local/include/node/uv-bsd.h
    /usr/local/include/node/uv-darwin.h
    /usr/local/include/node/uv-errno.h
    /usr/local/include/node/uv-linux.h
    /usr/local/include/node/uv-sunos.h
    /usr/local/include/node/uv-threadpool.h
    /usr/local/include/node/uv-unix.h
    /usr/local/include/node/uv-version.h
    /usr/local/include/node/uv-win.h
    /usr/local/include/node/uv.h
    /usr/local/include/node/v8-debug.h
    /usr/local/include/node/v8-platform.h
    /usr/local/include/node/v8-profiler.h
    /usr/local/include/node/v8-testing.h
    /usr/local/include/node/v8-util.h
    /usr/local/include/node/v8-version.h
    /usr/local/include/node/v8.h
    /usr/local/include/node/v8config.h
    /usr/local/include/node/zconf.h
    /usr/local/include/node/zlib.h

Warning: Unbrewed .pc files were found in /usr/local/lib/pkgconfig.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected .pc files:
    /usr/local/lib/pkgconfig/glfw3.pc

Warning: Unbrewed static libraries were found in /usr/local/lib.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected static libraries:
    /usr/local/lib/libglfw3.a
Error: undefined method `rebuild' for #<BottleSpecification:0x007fc4830390e0>
Please report this bug:
    https://git.io/brew-troubleshooting
/usr/local/Library/Taps/homebrew/homebrew-core/Formula/python3.rb:22:in `block in <class:Python3>'
/usr/local/Library/Homebrew/software_spec.rb:91:in `instance_eval'
/usr/local/Library/Homebrew/software_spec.rb:91:in `bottle'
/usr/local/Library/Homebrew/formula.rb:1726:in `bottle'
/usr/local/Library/Taps/homebrew/homebrew-core/Formula/python3.rb:21:in `<class:Python3>'
/usr/local/Library/Taps/homebrew/homebrew-core/Formula/python3.rb:1:in `load_formula'
/usr/local/Library/Homebrew/formulary.rb:21:in `module_eval'
/usr/local/Library/Homebrew/formulary.rb:21:in `load_formula'
/usr/local/Library/Homebrew/formulary.rb:34:in `load_formula_from_path'
/usr/local/Library/Homebrew/formulary.rb:83:in `load_file'
/usr/local/Library/Homebrew/formulary.rb:74:in `klass'
/usr/local/Library/Homebrew/formulary.rb:70:in `get_formula'
/usr/local/Library/Homebrew/formulary.rb:167:in `get_formula'
/usr/local/Library/Homebrew/formulary.rb:207:in `factory'
/usr/local/Library/Homebrew/formulary.rb:226:in `from_rack'
/usr/local/Library/Homebrew/diagnostic.rb:1339:in `block in check_for_unlinked_but_not_keg_only'
/usr/local/Library/Homebrew/diagnostic.rb:1336:in `reject'
/usr/local/Library/Homebrew/diagnostic.rb:1336:in `check_for_unlinked_but_not_keg_only'
/usr/local/Library/Homebrew/cmd/doctor.rb:38:in `block in doctor'
/usr/local/Library/Homebrew/cmd/doctor.rb:31:in `each'
/usr/local/Library/Homebrew/cmd/doctor.rb:31:in `doctor'
/usr/local/Library/brew.rb:97:in `<main>'
```

**Comment by ivankocienski** [comment]
I should add that I have run `brew update` with the following output
```
Unpacking objects: 100% (34/34), done.
error: The following untracked working tree files would be overwritten by merge:
	share/man/man1/brew-cask.1
Please move or remove them before you can merge.
Aborting
Already up-to-date.
```

`brew install postgresql` has the same output

**Comment by ilovezfs** [comment]
`mv /usr/local/share/man/man1/brew-cask.1 ~/` and try again.

**Comment by matthewmrichter** [comment]
+1 I'm having this issue as well

**Comment by dunn** [comment]
You may be stuck in the update bug: https://github.com/Homebrew/homebrew-core#update-bug

**Comment by apjanke** [comment]
Ping. Did either ilovezfs or dunn's suggestions help with this?

**Comment by fxcoudert** [comment]
With no response, I am closing this issue for now.
