### ISSUE TITLE
brew install php55

### ISSUE THREAD

**Issue by AxunA** [Homebrew/homebrew-core#4768]
**I run the command below:**
`brew install php55 --with-imap --with-tidy --with-debug --with-mysql --with-fpm`

**but was not done by the log below**

```
/usr/local/Homebrew/Library/Homebrew/utils/github.rb:216:in `raise_api_error': Validation Failed (GitHub::Error)
	from /usr/local/Homebrew/Library/Homebrew/utils/github.rb:174:in `open'
	from /usr/local/Homebrew/Library/Homebrew/utils/github.rb:223:in `issues_matching'
	from /usr/local/Homebrew/Library/Homebrew/utils/github.rb:256:in `issues_for_formula'
	from /usr/local/Homebrew/Library/Homebrew/exceptions.rb:312:in `fetch_issues'
	from /usr/local/Homebrew/Library/Homebrew/exceptions.rb:308:in `issues'
	from /usr/local/Homebrew/Library/Homebrew/exceptions.rb:353:in `dump'
	from /usr/local/Homebrew/Library/Homebrew/brew.rb:135:in `rescue in <main>'
	from /usr/local/Homebrew/Library/Homebrew/brew.rb:30:in `<main>'
```

**Comment by zmwangx** [comment]
Please rerun your install command with the `--verbose --debug` options and provide the full output.

Also, have you tried

```bash
cd "$(brew --repo)" && git fetch && git reset --hard origin/master && brew update
```

**Comment by AxunA** [comment]
It looks work by running 

cd "$(brew --repo)" && git fetch && git reset --hard origin/master && brew update

thanks a lots...

**Comment by zmwangx** [comment]
Glad to hear, you're welcome.
