### ISSUE TITLE
easy-git: Unknown download strategy ssl3 was requested

### ISSUE THREAD

**Issue by samford** [Homebrew/homebrew-core#47879]
# Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.

- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [ ] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

## What you were trying to do (and why)

Running `brew audit --strict easy-git` (this also occurs without the `--strict` flag).

## What happened (include command output)

<details>
  <summary>Command output</summary>
  <pre>

  Error: Unknown download strategy ssl3 was requested

  </pre>
</details>

## What you expected to happen

No output (i.e., a clean audit).

## Step-by-step reproduction instructions (by running `brew install` commands)

1. `brew audit --strict easy-git`

## Comments

easy-git installs and tests fine but it fails a `brew audit`.  This error message comes from [brew/Library/Homebrew/download_strategy.rb](https://github.com/Homebrew/brew/blob/b62758a763ac58a2e50ac802f0b8cc15926cbfa3/Library/Homebrew/download_strategy.rb#L1125).

At least on the surface, it seems like this error would only occur if the formula had an unrecognized `:using` symbol (e.g., `url '...', :using => :ssl3`).  The easy-git.rb formula did have this in the past but it's not present in the current formula, so this error is a bit baffling.

I mainly bring this up because this formula's error causes a full audit of the available formulae to halt partway.

**Comment by alebcay** [comment]
I can reproduce the issue. Full trace:

```
❯ brew audit --strict --verbose --debug easy-git
/usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::FormulaLoader): loading /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/easy-git.rb
/usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::FormulaContentsLoader): loading /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/easy-git.rb
/usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::FormulaContentsLoader): loading /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/easy-git.rb
/usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::FormulaContentsLoader): loading /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/easy-git.rb
/usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::FormulaContentsLoader): loading /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/easy-git.rb
/usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::FormulaContentsLoader): loading /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/easy-git.rb
/usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::FormulaContentsLoader): loading /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/easy-git.rb
/usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::FormulaContentsLoader): loading /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/easy-git.rb
Error: Unknown download strategy ssl3 was requested.
/usr/local/Homebrew/Library/Homebrew/download_strategy.rb:1125:in `detect_from_symbol'
/usr/local/Homebrew/Library/Homebrew/download_strategy.rb:1070:in `detect'
/usr/local/Homebrew/Library/Homebrew/resource.rb:149:in `url'
/usr/local/Homebrew/Library/Homebrew/software_spec.rb:76:in `url'
/usr/local/Homebrew/Library/Homebrew/formula.rb:2184:in `url'
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/easy-git.rb:5:in `<class:EasyGit>'
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/easy-git.rb:3:in `load_formula'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:34:in `module_eval'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:34:in `load_formula'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:311:in `klass'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:122:in `get_formula'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:388:in `from_contents'
/usr/local/Homebrew/Library/Homebrew/formula_versions.rb:42:in `block in formula_at_revision'
/usr/local/Homebrew/Library/Homebrew/utils.rb:377:in `nostdout'
/usr/local/Homebrew/Library/Homebrew/formula_versions.rb:42:in `formula_at_revision'
/usr/local/Homebrew/Library/Homebrew/formula_versions.rb:103:in `block in version_attributes_map'
/usr/local/Homebrew/Library/Homebrew/formula_versions.rb:28:in `block (2 levels) in rev_list'
/usr/local/Homebrew/Library/Homebrew/utils/popen.rb:31:in `block in popen'
/usr/local/Homebrew/Library/Homebrew/utils/popen.rb:27:in `popen'
/usr/local/Homebrew/Library/Homebrew/utils/popen.rb:27:in `popen'
/usr/local/Homebrew/Library/Homebrew/utils/popen.rb:5:in `popen_read'
/usr/local/Homebrew/Library/Homebrew/formula_versions.rb:27:in `block in rev_list'
/usr/local/Homebrew/Library/Homebrew/extend/pathname.rb:281:in `block in cd'
/usr/local/Homebrew/Library/Homebrew/extend/pathname.rb:281:in `chdir'
/usr/local/Homebrew/Library/Homebrew/extend/pathname.rb:281:in `cd'
/usr/local/Homebrew/Library/Homebrew/formula_versions.rb:26:in `rev_list'
/usr/local/Homebrew/Library/Homebrew/formula_versions.rb:102:in `version_attributes_map'
/usr/local/Homebrew/Library/Homebrew/dev-cmd/audit.rb:818:in `audit_revision_and_version_scheme'
/usr/local/Homebrew/Library/Homebrew/dev-cmd/audit.rb:1007:in `block in audit'
/usr/local/Homebrew/Library/Homebrew/dev-cmd/audit.rb:1000:in `each'
/usr/local/Homebrew/Library/Homebrew/dev-cmd/audit.rb:1000:in `audit'
/usr/local/Homebrew/Library/Homebrew/dev-cmd/audit.rb:123:in `block in audit'
/usr/local/Homebrew/Library/Homebrew/dev-cmd/audit.rb:116:in `each'
/usr/local/Homebrew/Library/Homebrew/dev-cmd/audit.rb:116:in `audit'
/usr/local/Homebrew/Library/Homebrew/brew.rb:102:in `<main>'
```

**Comment by samford** [comment]
Apparently this also affects jam.rb, another formula which [used the `:ssl3` download strategy at one point](https://github.com/Homebrew/homebrew-core/commit/f8e45e8bbd456e120e38fe1f05fda54b637931a1).  Oddly enough, this doesn't affect monetdb.rb, which meets the same criteria.

**Comment by fxcoudert** [comment]
The audit code loads the formula for the previous version, in order to perform some checks (is the version increasing? has the checksum changed without version increase?). It will walk back revisions until it finds an earlier version, then stop.

I think this error triggers on `jam` and `easy-git` because they used `:ssl3` in a formula with the same version that still exists currently (i.e., they didn't have their version updated since the ssl3 removal).

I'm moving this to a `brew` issue. Not sure if it's worth fixing, though :)
