### ISSUE TITLE
brew test clang-omp fails

### ISSUE THREAD

**Issue by jamer** [Homebrew/homebrew-core#479]
- [✓] Ran `brew update` and retried your prior step?
- [✓] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?

`brew doctor` says Warning: Your Homebrew is not installed to /usr/local

### Bug report

Running the test for clang-omp fails due to inability to `#include <omp.h>`. GCC from Homebrew can compile files with omp.h fine on the same system.

```
$ brew test clang-omp
Testing clang-omp
==> Using the sandbox
==> /Users/pdm/Library/Homebrew/Cellar/clang-omp/2015-04-01/bin/clang-omp -liomp
Last 15 lines from /Users/pdm/Library/Logs/Homebrew/clang-omp/01.clang-omp:
2016-04-20 01:04:50 -0700

/Users/pdm/Library/Homebrew/Cellar/clang-omp/2015-04-01/bin/clang-omp
-liomp5
-fopenmp
test.c
-o
test

test.c:3:10: fatal error: 'omp.h' file not found
#include <omp.h>
         ^
1 error generated.
Error: clang-omp: failed
Failed executing: /Users/pdm/Library/Homebrew/Cellar/clang-omp/2015-04-01/bin/clang-omp -liomp5 -fopenmp test.c -o test
/Users/pdm/Library/Homebrew/Library/Homebrew/formula.rb:1492:in `block in system'
/Users/pdm/Library/Homebrew/Library/Homebrew/formula.rb:1429:in `open'
/Users/pdm/Library/Homebrew/Library/Homebrew/formula.rb:1429:in `system'
/Users/pdm/Library/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/clang-omp.rb:97:in `block in <class:ClangOmp>'
/Users/pdm/Library/Homebrew/Library/Homebrew/formula.rb:1334:in `block in run_test'
/Users/pdm/Library/Homebrew/Library/Homebrew/extend/fileutils.rb:14:in `block in mktemp'
/Users/pdm/Library/Homebrew/Library/Homebrew/extend/fileutils.rb:75:in `block in run'
/Users/pdm/Library/Homebrew/Library/Homebrew/extend/fileutils.rb:75:in `chdir'
/Users/pdm/Library/Homebrew/Library/Homebrew/extend/fileutils.rb:75:in `run'
/Users/pdm/Library/Homebrew/Library/Homebrew/extend/fileutils.rb:13:in `mktemp'
/Users/pdm/Library/Homebrew/Library/Homebrew/formula.rb:1328:in `run_test'
/Users/pdm/Library/Homebrew/Library/Homebrew/test.rb:28:in `block in <main>'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/timeout.rb:66:in `timeout'
/Users/pdm/Library/Homebrew/Library/Homebrew/test.rb:27:in `<main>'
```

Full log is https://gist.github.com/jamer/d0ab786386bfb74572c7e737b4a82adc

Clang version is:

```
Apple LLVM version 7.3.0 (clang-703.0.29)
Target: x86_64-apple-darwin15.4.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
```

**Comment by ilovezfs** [comment]
I think it's just not finding your omp.h file because you're not using the default prefix.

**Comment by ilovezfs** [comment]
@jamer were you able to successfully compile?

**Comment by jamer** [comment]
Yep, it compiles successfully when built in the default prefix.

**Comment by ilovezfs** [comment]
@jamer OK, good. So that means it should work fine in a non-default prefix as well if you spell out the library path(s) in the LDFLAGS and the include path(s) in the the CFLAGS.
