### ISSUE TITLE
Error: undefined method `downcase' for #<Pathname:percona-server>

### ISSUE THREAD

**Issue by quard8** [Homebrew/homebrew-core#4930]
I have run issue for every brew command:

```
brew update
Error: undefined method `downcase' for #<Pathname:percona-server>
Please report this bug:
    https://git.io/brew-troubleshooting
/usr/local/Library/Homebrew/formulary.rb:349:in `core_path'
/usr/local/Library/Homebrew/formulary.rb:301:in `loader_for'
/usr/local/Library/Homebrew/formulary.rb:219:in `factory'
/usr/local/Library/Homebrew/utils.rb:637:in `rescue in rescue in block in migrate_legacy_keg_symlinks_if_necessary'
/usr/local/Library/Homebrew/utils.rb:634:in `rescue in block in migrate_legacy_keg_symlinks_if_necessary'
/usr/local/Library/Homebrew/utils.rb:631:in `block in migrate_legacy_keg_symlinks_if_necessary'
/usr/local/Library/Homebrew/utils.rb:629:in `each'
/usr/local/Library/Homebrew/utils.rb:629:in `migrate_legacy_keg_symlinks_if_necessary'
/usr/local/Library/Homebrew/brew.rb:91:in `<main>'
```

```brew doctor``` did't work, nothing works :)

I did few steps to fix, but it did't help me:
1. update homebrew
2. cleanup via git

What can I do without reinstalling everything?

**Comment by pedroscocco** [comment]
Getting the same error but for `#<Pathname:git>` instead.

**Comment by tovytovy** [comment]
all "brew doctor, upgrade, update" show  same error .

> $ brew doctor
Error: undefined method `downcase' for #<Pathname:babl>
Please report this bug:
    https://git.io/brew-troubleshooting
/usr/local/Library/Homebrew/formulary.rb:349:in `core_path'
/usr/local/Library/Homebrew/formulary.rb:301:in `loader_for'
/usr/local/Library/Homebrew/formulary.rb:219:in `factory'
/usr/local/Library/Homebrew/utils.rb:637:in `rescue in rescue in block in migrate_legacy_keg_symlinks_if_necessary'
/usr/local/Library/Homebrew/utils.rb:634:in `rescue in block in migrate_legacy_keg_symlinks_if_necessary'
/usr/local/Library/Homebrew/utils.rb:631:in `block in migrate_legacy_keg_symlinks_if_necessary'
/usr/local/Library/Homebrew/utils.rb:629:in `each'
/usr/local/Library/Homebrew/utils.rb:629:in `migrate_legacy_keg_symlinks_if_necessary'
/usr/local/Library/Homebrew/brew.rb:91:in `<main>'

**Comment by zmwangx** [comment]
Sorry, this should be fixed once we ship Homebrew/brew#1003 or something comparable. Could you please test the change in Homebrew/brew#1003? Or if you're unsure about how to do that, just wait and we'll notify you.

**Comment by ilovezfs** [comment]
https://github.com/Homebrew/brew/pull/1003 has shipped. Please update, and this should be fixed.

**Comment by justinclift** [comment]
Interestingly, it's still possible to hit this.  With an empty repo list on my main desktop here, I just started getting:

```
Error: undefined method `downcase' for #<Pathname:0x007f88fccdbae0>
/usr/local/Homebrew/Library/Homebrew/formulary.rb:405:in `tap_paths'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:354:in `loader_for'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:259:in `factory'
/usr/local/Homebrew/Library/Homebrew/cmd/update-report.rb:372:in `block in report'
/usr/local/Homebrew/Library/Homebrew/cmd/update-report.rb:350:in `each_line'
/usr/local/Homebrew/Library/Homebrew/cmd/update-report.rb:350:in `report'
/usr/local/Homebrew/Library/Homebrew/cmd/update-report.rb:559:in `add'
/usr/local/Homebrew/Library/Homebrew/cmd/update-report.rb:77:in `block in update_report'
/usr/local/Homebrew/Library/Homebrew/tap.rb:479:in `block (2 levels) in each'
/usr/local/Homebrew/Library/Homebrew/tap.rb:478:in `each'
/usr/local/Homebrew/Library/Homebrew/tap.rb:478:in `block in each'
/usr/local/Homebrew/Library/Homebrew/tap.rb:477:in `each'
/usr/local/Homebrew/Library/Homebrew/tap.rb:477:in `each'
/usr/local/Homebrew/Library/Homebrew/cmd/update-report.rb:67:in `update_report'
/usr/local/Homebrew/Library/Homebrew/brew.rb:94:in `<main>'
Error: undefined method `downcase' for #<Pathname:0x007f88fc41ec40>
/usr/local/Homebrew/Library/Homebrew/formulary.rb:405:in `tap_paths'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:354:in `loader_for'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:259:in `factory'
/usr/local/Homebrew/Library/Homebrew/cmd/update-report.rb:372:in `block in report'
/usr/local/Homebrew/Library/Homebrew/cmd/update-report.rb:350:in `each_line'
/usr/local/Homebrew/Library/Homebrew/cmd/update-report.rb:350:in `report'
/usr/local/Homebrew/Library/Homebrew/cmd/update-report.rb:559:in `add'
/usr/local/Homebrew/Library/Homebrew/cmd/update-report.rb:77:in `block in update_report'
/usr/local/Homebrew/Library/Homebrew/tap.rb:479:in `block (2 levels) in each'
/usr/local/Homebrew/Library/Homebrew/tap.rb:478:in `each'
/usr/local/Homebrew/Library/Homebrew/tap.rb:478:in `block in each'
/usr/local/Homebrew/Library/Homebrew/tap.rb:477:in `each'
/usr/local/Homebrew/Library/Homebrew/tap.rb:477:in `each'
/usr/local/Homebrew/Library/Homebrew/cmd/update-report.rb:67:in `update_report'
/usr/local/Homebrew/Library/Homebrew/brew.rb:94:in `<main>'
[etc]
```

When doing `brew update`.

The trigger was shown by `brew doctor`:

```
Warning: Broken symlinks were found. Remove them with `brew prune`:
  /usr/local/share/man/man1/npm-README.1
  /usr/local/share/man/man1/npm-access.1
  /usr/local/share/man/man1/npm-adduser.1
  /usr/local/share/man/man1/npm-bin.1
  /usr/local/share/man/man1/npm-bugs.1
  /usr/local/share/man/man1/npm-build.1
  /usr/local/share/man/man1/npm-bundle.1
  /usr/local/share/man/man1/npm-cache.1
  /usr/local/share/man/man1/npm-completion.1
  /usr/local/share/man/man1/npm-config.1
  /usr/local/share/man/man1/npm-dedupe.1
  /usr/local/share/man/man1/npm-deprecate.1
[etc]
```

Running `brew prune` did fix the problem.

Mentioning this as although this is an edge case, it might be useful to make the code around this a bit more robust. :smile:
