### ISSUE TITLE
Elasticsearch (6.8.6) does not work on MacOS Catalina

### ISSUE THREAD

**Issue by spape** [Homebrew/homebrew-core#49922]
https://gist.github.com/c1da55ec72f9e4b30f6eddb6bf0f4b8c

## What you were trying to do (and why)

Tried to install elasticsearch (6.8.6) on macOS Catalina, also tried old version (6.8.5). Both failed.

```
brew install elasticsearch
```

## What happened (include command output)

Elasticsearch does not start up. When trying to start it by hand, it fails with the following error:

```
>elasticsearch
OpenJDK 64-Bit Server VM warning: Cannot open file logs/gc.log due to No such file or directory

[2020-02-09T14:26:25,365][WARN ][o.e.b.ElasticsearchUncaughtExceptionHandler] [unknown] uncaught exception in thread [main]
org.elasticsearch.bootstrap.StartupException: ElasticsearchException[java.io.IOException: failed to read [id:4, file:/usr/local/var/lib/elasticsearch/nodes/0/_state/node-4.st]]; nested: IOException[failed to read [id:4, file:/usr/local/var/lib/elasticsearch/nodes/0/_state/node-4.st]]; nested: XContentParseException[[-1:36] [node_meta_data] unknown field [node_version], parser not found];
	at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:163) ~[elasticsearch-6.8.5.jar:6.8.5]
	at org.elasticsearch.bootstrap.Elasticsearch.execute(Elasticsearch.java:150) ~[elasticsearch-6.8.5.jar:6.8.5]
	at org.elasticsearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:86) ~[elasticsearch-6.8.5.jar:6.8.5]
	at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:124) ~[elasticsearch-cli-6.8.5.jar:6.8.5]
	at org.elasticsearch.cli.Command.main(Command.java:90) ~[elasticsearch-cli-6.8.5.jar:6.8.5]
	at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:116) ~[elasticsearch-6.8.5.jar:6.8.5]
	at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:93) ~[elasticsearch-6.8.5.jar:6.8.5]
Caused by: org.elasticsearch.ElasticsearchException: java.io.IOException: failed to read [id:4, file:/usr/local/var/lib/elasticsearch/nodes/0/_state/node-4.st]
	at org.elasticsearch.ExceptionsHelper.maybeThrowRuntimeAndSuppress(ExceptionsHelper.java:165) ~[elasticsearch-6.8.5.jar:6.8.5]
	at org.elasticsearch.gateway.MetaDataStateFormat.loadLatestStateWithGeneration(MetaDataStateFormat.java:306) ~[elasticsearch-6.8.5.jar:6.8.5]
	at org.elasticsearch.gateway.MetaDataStateFormat.loadLatestState(MetaDataStateFormat.java:324) ~[elasticsearch-6.8.5.jar:6.8.5]
	at org.elasticsearch.env.NodeEnvironment.loadOrCreateNodeMetaData(NodeEnvironment.java:417) ~[elasticsearch-6.8.5.jar:6.8.5]
	at org.elasticsearch.env.NodeEnvironment.<init>(NodeEnvironment.java:305) ~[elasticsearch-6.8.5.jar:6.8.5]
	at org.elasticsearch.node.Node.<init>(Node.java:296) ~[elasticsearch-6.8.5.jar:6.8.5]
	at org.elasticsearch.node.Node.<init>(Node.java:266) ~[elasticsearch-6.8.5.jar:6.8.5]
	at org.elasticsearch.bootstrap.Bootstrap$5.<init>(Bootstrap.java:212) ~[elasticsearch-6.8.5.jar:6.8.5]
	at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:212) ~[elasticsearch-6.8.5.jar:6.8.5]
	at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:333) ~[elasticsearch-6.8.5.jar:6.8.5]
	at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:159) ~[elasticsearch-6.8.5.jar:6.8.5]
	... 6 more
Caused by: java.io.IOException: failed to read [id:4, file:/usr/local/var/lib/elasticsearch/nodes/0/_state/node-4.st]
	at org.elasticsearch.gateway.MetaDataStateFormat.loadLatestStateWithGeneration(MetaDataStateFormat.java:300) ~[elasticsearch-6.8.5.jar:6.8.5]
	at org.elasticsearch.gateway.MetaDataStateFormat.loadLatestState(MetaDataStateFormat.java:324) ~[elasticsearch-6.8.5.jar:6.8.5]
	at org.elasticsearch.env.NodeEnvironment.loadOrCreateNodeMetaData(NodeEnvironment.java:417) ~[elasticsearch-6.8.5.jar:6.8.5]
	at org.elasticsearch.env.NodeEnvironment.<init>(NodeEnvironment.java:305) ~[elasticsearch-6.8.5.jar:6.8.5]
	at org.elasticsearch.node.Node.<init>(Node.java:296) ~[elasticsearch-6.8.5.jar:6.8.5]
	at org.elasticsearch.node.Node.<init>(Node.java:266) ~[elasticsearch-6.8.5.jar:6.8.5]
	at org.elasticsearch.bootstrap.Bootstrap$5.<init>(Bootstrap.java:212) ~[elasticsearch-6.8.5.jar:6.8.5]
	at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:212) ~[elasticsearch-6.8.5.jar:6.8.5]
	at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:333) ~[elasticsearch-6.8.5.jar:6.8.5]
	at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:159) ~[elasticsearch-6.8.5.jar:6.8.5]
	... 6 more
Caused by: org.elasticsearch.common.xcontent.XContentParseException: [-1:36] [node_meta_data] unknown field [node_version], parser not found
	at org.elasticsearch.common.xcontent.ObjectParser.getParser(ObjectParser.java:369) ~[elasticsearch-x-content-6.8.5.jar:6.8.5]
	at org.elasticsearch.common.xcontent.ObjectParser.parse(ObjectParser.java:158) ~[elasticsearch-x-content-6.8.5.jar:6.8.5]
	at org.elasticsearch.common.xcontent.ObjectParser.apply(ObjectParser.java:182) ~[elasticsearch-x-content-6.8.5.jar:6.8.5]
	at org.elasticsearch.env.NodeMetaData$1.fromXContent(NodeMetaData.java:110) ~[elasticsearch-6.8.5.jar:6.8.5]
	at org.elasticsearch.env.NodeMetaData$1.fromXContent(NodeMetaData.java:94) ~[elasticsearch-6.8.5.jar:6.8.5]
	at org.elasticsearch.gateway.MetaDataStateFormat.read(MetaDataStateFormat.java:197) ~[elasticsearch-6.8.5.jar:6.8.5]
	at org.elasticsearch.gateway.MetaDataStateFormat.loadLatestStateWithGeneration(MetaDataStateFormat.java:296) ~[elasticsearch-6.8.5.jar:6.8.5]
	at org.elasticsearch.gateway.MetaDataStateFormat.loadLatestState(MetaDataStateFormat.java:324) ~[elasticsearch-6.8.5.jar:6.8.5]
	at org.elasticsearch.env.NodeEnvironment.loadOrCreateNodeMetaData(NodeEnvironment.java:417) ~[elasticsearch-6.8.5.jar:6.8.5]
	at org.elasticsearch.env.NodeEnvironment.<init>(NodeEnvironment.java:305) ~[elasticsearch-6.8.5.jar:6.8.5]
	at org.elasticsearch.node.Node.<init>(Node.java:296) ~[elasticsearch-6.8.5.jar:6.8.5]
	at org.elasticsearch.node.Node.<init>(Node.java:266) ~[elasticsearch-6.8.5.jar:6.8.5]
	at org.elasticsearch.bootstrap.Bootstrap$5.<init>(Bootstrap.java:212) ~[elasticsearch-6.8.5.jar:6.8.5]
	at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:212) ~[elasticsearch-6.8.5.jar:6.8.5]
	at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:333) ~[elasticsearch-6.8.5.jar:6.8.5]
	at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:159) ~[elasticsearch-6.8.5.jar:6.8.5]
	... 6 more
```

## What you expected to happen

That elasticsearch starts up, especially because downloading the packaged elasticsearch.tar.gz and running it manually works.

## Step-by-step reproduction instructions (by running `brew install` commands)

```
brew install elasticsearch
elasticsearch
```

**Comment by SMillerDev** [comment]
Can you try and report this to the elastic search developers too? It seems like a data structure mismatch to me which brew can't really solve.

**Comment by spape** [comment]
@SMillerDev the reason I posted it here first, was because the packaged elasticsearch that I downloaded from elastic.co works, so I though it might be related to some details in the brew formula.

But I will let them know too.

**Comment by Bo98** [comment]
I know this happens when you downgrade from 7.x to 6.x. Is it possible that is what happened here?
