### ISSUE TITLE
Updating python3 doesn't update cerificates CA

### ISSUE THREAD

**Issue by kam193** [Homebrew/homebrew-core#50027]
- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link? https://gist.github.com/kam193/45420aac24518b27c0da98880faf04f0
- [x] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

## What you were trying to do (and why)

I try to use some of python package that downloads files over HTTPS.

## What happened (include command output)

I got SSL exception "urllib.error.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1056)>"

<details>
  <summary>Command output</summary>
  <pre>
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/lib/python3.7/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/lib/python3.7/urllib/request.py", line 525, in open
    response = self._open(req, data)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/lib/python3.7/urllib/request.py", line 543, in _open
    '_open', req)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/lib/python3.7/urllib/request.py", line 503, in _call_chain
    result = func(*args)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/lib/python3.7/urllib/request.py", line 1360, in https_open
    context=self._context, check_hostname=self._check_hostname)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/lib/python3.7/urllib/request.py", line 1319, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1056)>
  </pre>
</details>

## What you expected to happen

The file/url should be opened.

## Step-by-step reproduction instructions (by running `brew install` commands)

1. Have installed not-latest python3 version, like 3.7.x.
2. Update `brew upgrade` or `brew upgrade python` to get 3.7.x+1
3. Open python3 and try run following script:

```
from urllib.request import urlopen
urlopen('https://google.com')
``` 

## Related materials and issues

* It looks like the same as closed without solution issue #42198
* The StackOverflow has solution for similar problem for non-brew installation, but brew version doesn't have required command script, e.g. https://stackoverflow.com/questions/50236117/scraping-ssl-certificate-verify-failed-error-for-http-en-wikipedia-org
* Manually download and run script https://github.com/python/cpython/blob/master/Mac/BuildScript/resources/install_certificates.command (with a few steps more, like creating those dirs) solves problem, but it should be done during Python update

**Comment by DesPenny** [comment]
@kam193 What were the few more steps you carried out in point 3 to work around this?

**Comment by kam193** [comment]
I got this script and try to run it from python and fix any issue during this. It could be like missing package, but at most missing directory (path `openssl_dir` = `/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.7/etc/ssl` didn't exist on my mac), no more magic.

**Comment by DesPenny** [comment]
Yea I did that but that i was missing some magic step. I'll keep tinkering. Cheers for getting back

**Comment by kam193** [comment]
No problem :)

**Comment by fxcoudert** [comment]
I cannot reproduce here. I have the latest brew `python`, which was upgraded from a previous version, and it works fine:

```
$ python3
Python 3.7.6 (default, Dec 30 2019, 19:38:26) 
[Clang 11.0.0 (clang-1100.0.33.16)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from urllib.request import urlopen
>>> urlopen('https://google.com')
<http.client.HTTPResponse object at 0x101228990>
```

I suspect if it hit all users, we would have heard about it before, so there must be additional conditions to reproduce. Maybe it's because your `python` is unlinked?

**Comment by DesPenny** [comment]
All sorted my end carrying out the steps kam193 provided. I just had a local set up causing confusion initially.

**Comment by mgenereu** [comment]
There is an additional condition. It must be some outdated CA situation.

```python
Python 3.7.6 (default, Dec 30 2019, 19:38:26) 
[Clang 11.0.0 (clang-1100.0.33.16)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from urllib.request import urlopen
>>> urlopen('https://google.com')
<http.client.HTTPResponse object at 0x10f05b150>
>>> urlopen('https://raw.githubusercontent.com/scalacenter/nailgun/a2520c1e/pynailgun/ng.py')
Traceback (most recent call last):
  File "/usr/local/Cellar/python/3.7.6_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/urllib/request.py", line 1319, in do_open
    encode_chunked=req.has_header('Transfer-encoding'))
  File "/usr/local/Cellar/python/3.7.6_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/http/client.py", line 1252, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/local/Cellar/python/3.7.6_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/http/client.py", line 1298, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/local/Cellar/python/3.7.6_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/http/client.py", line 1247, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/local/Cellar/python/3.7.6_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/http/client.py", line 1026, in _send_output
    self.send(msg)
  File "/usr/local/Cellar/python/3.7.6_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/http/client.py", line 966, in send
    self.connect()
  File "/usr/local/Cellar/python/3.7.6_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/http/client.py", line 1422, in connect
    server_hostname=server_hostname)
  File "/usr/local/Cellar/python/3.7.6_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/ssl.py", line 423, in wrap_socket
    session=session
  File "/usr/local/Cellar/python/3.7.6_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/ssl.py", line 870, in _create
    self.do_handshake()
  File "/usr/local/Cellar/python/3.7.6_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/ssl.py", line 1139, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1076)
```

**Comment by mgenereu** [comment]
Ignore my last message.  It's a firewall issue interfering with the certificates.

**Comment by mgenereu** [comment]
Actually, it was a non-root certificate from the firewall that isn't loaded.  See #1072 for reasons.
