### ISSUE TITLE
docker-slim: docker-slim-sensor does not installed

### ISSUE THREAD

**Issue by superbrothers** [Homebrew/homebrew-core#50646]
- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [x] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

## What you were trying to do (and why)

I tried to install docker-slim via Homebrew, and build a slim image from an original image.

## What happened (include command output)

It failed to build a slim image because docker-slim-sensor did not be installed.

<details>
  <summary>Command output</summary>
  <pre>
$ docker-slim build nginx:1.17.3-alpine
docker-slim[build]: info=http.probe message='using default probe'
docker-slim[build]: state=started
docker-slim[build]: info=params target=nginx:1.17.3-alpine continue.mode=probe
docker-slim[build]: state=image.inspection.start
time="2020-02-24T22:39:04+09:00" level=fatal msg="docker-slim: failure" error="open /usr/local/bin/docker-slim-sensor: no such file or directory" stack="goroutine 1 [running]:\nruntime/debug.Stack(0x0, 0x1762e60, 0xc0001a5d10)\n\truntime/debug/stack.go:24 +0x9d\ngithub.com/docker-slim/docker-slim/pkg/util/errutil.FailOn(0x1762e60, 0xc0001a5d10)\n\tgithub.com/docker-slim/docker-slim@/pkg/util/errutil/errutil.go:14 +0x54\ngithub.com/docker-slim/docker-slim/pkg/util/fsutil.PrepareImageStateDirs(0x0, 0x0, 0xc0002de000, 0x47, 0x1, 0x31, 0x0, 0x0, 0x0, 0x0, ...)\n\tgithub.com/docker-slim/docker-slim@/pkg/util/fsutil/fsutil.go:547 +0x9df\ngithub.com/docker-slim/docker-slim/internal/app/master/commands.OnBuild(0x15bc301, 0x168981f, 0x10, 0x0, 0x0, 0x0, 0x0, 0x0, 0x1680000, 0xc0001a4f90, ...)\n\tgithub.com/docker-slim/docker-slim@/internal/app/master/commands/build.go:180 +0x958\ngithub.com/docker-slim/docker-slim/internal/app/master.init.0.func6(0xc0001b0160, 0x0, 0xc0001b62b0)\n\tgithub.com/docker-slim/docker-slim@/internal/app/master/cli.go:775 +0x1709\ngithub.com/urfave/cli.HandleAction(0x15a7620, 0x16ada70, 0xc0001b0160, 0xc0001b0160, 0x0)\n\tgithub.com/urfave/cli@v1.22.1/app.go:523 +0xbe\ngithub.com/urfave/cli.Command.Run(0x1680714, 0x5, 0x0, 0x0, 0xc0001565a0, 0x1, 0x1, 0x16a1d0a, 0x3e, 0x0, ...)\n\tgithub.com/urfave/cli@v1.22.1/command.go:174 +0x51c\ngithub.com/urfave/cli.(*App).Run(0xc000178000, 0xc00001e1b0, 0x3, 0x3, 0x0, 0x0)\n\tgithub.com/urfave/cli@v1.22.1/app.go:276 +0x718\ngithub.com/docker-slim/docker-slim/internal/app/master.runCli()\n\tgithub.com/docker-slim/docker-slim@/internal/app/master/cli.go:1159 +0x55\ngithub.com/docker-slim/docker-slim/internal/app/master.Run()\n\tgithub.com/docker-slim/docker-slim@/internal/app/master/app.go:6 +0x25\nmain.main()\n\tgithub.com/docker-slim/docker-slim@/cmd/docker-slim/main.go:8 +0x20\n" version="darwin|Transformer|1.26.1|latest|latest"
  </pre>
</details>

## What you expected to happen

It is to succeed in building a slim image from an original image.

## Step-by-step reproduction instructions (by running `brew install` commands)

```
$ brew install docker-slim
==> Downloading https://homebrew.bintray.com/bottles/docker-slim-1.26.1.catalina.bottle.tar.gz
==> Downloading from https://akamai.bintray.com/5c/5c3287964ff0aa01af0b14d6474fd3bc087972d29c587402314b267a2c9b2512?__gda__=exp=1582552205~hmac=7993cdf874ee2401a0c6d488011b64065fd2a657e7de0b4a37667f68af9ab08c&response-content-disposition=attachment%3Bfil
######################################################################## 100.0%
==> Pouring docker-slim-1.26.1.catalina.bottle.tar.gz
🍺  /usr/local/Cellar/docker-slim/1.26.1: 6 files, 12.2MB
$ docker pull nginx:1.17.3-alpine
1.17.3-alpine: Pulling from library/nginx
9d48c3bd43c5: Pull complete
b6dac14ba0a9: Pull complete
Digest: sha256:99be6ae8d32943b676031b3513782ad55c8540c1d040b1f7b8c335c67a241b06
Status: Downloaded newer image for nginx:1.17.3-alpine
docker.io/library/nginx:1.17.3-alpine
$ docker-slim build nginx:1.17.3-alpine
docker-slim[build]: info=http.probe message='using default probe'
docker-slim[build]: state=started
docker-slim[build]: info=params target=nginx:1.17.3-alpine continue.mode=probe
docker-slim[build]: state=image.inspection.start
time="2020-02-24T22:39:04+09:00" level=fatal msg="docker-slim: failure" error="open /usr/local/bin/docker-slim-sensor: no such file or directory" stack="goroutine 1 [running]:\nruntime/debug.Stack(0x0, 0x1762e60, 0xc0001a5d10)\n\truntime/debug/stack.go:24 +0x9d\ngithub.com/docker-slim/docker-slim/pkg/util/errutil.FailOn(0x1762e60, 0xc0001a5d10)\n\tgithub.com/docker-slim/docker-slim@/pkg/util/errutil/errutil.go:14 +0x54\ngithub.com/docker-slim/docker-slim/pkg/util/fsutil.PrepareImageStateDirs(0x0, 0x0, 0xc0002de000, 0x47, 0x1, 0x31, 0x0, 0x0, 0x0, 0x0, ...)\n\tgithub.com/docker-slim/docker-slim@/pkg/util/fsutil/fsutil.go:547 +0x9df\ngithub.com/docker-slim/docker-slim/internal/app/master/commands.OnBuild(0x15bc301, 0x168981f, 0x10, 0x0, 0x0, 0x0, 0x0, 0x0, 0x1680000, 0xc0001a4f90, ...)\n\tgithub.com/docker-slim/docker-slim@/internal/app/master/commands/build.go:180 +0x958\ngithub.com/docker-slim/docker-slim/internal/app/master.init.0.func6(0xc0001b0160, 0x0, 0xc0001b62b0)\n\tgithub.com/docker-slim/docker-slim@/internal/app/master/cli.go:775 +0x1709\ngithub.com/urfave/cli.HandleAction(0x15a7620, 0x16ada70, 0xc0001b0160, 0xc0001b0160, 0x0)\n\tgithub.com/urfave/cli@v1.22.1/app.go:523 +0xbe\ngithub.com/urfave/cli.Command.Run(0x1680714, 0x5, 0x0, 0x0, 0xc0001565a0, 0x1, 0x1, 0x16a1d0a, 0x3e, 0x0, ...)\n\tgithub.com/urfave/cli@v1.22.1/command.go:174 +0x51c\ngithub.com/urfave/cli.(*App).Run(0xc000178000, 0xc00001e1b0, 0x3, 0x3, 0x0, 0x0)\n\tgithub.com/urfave/cli@v1.22.1/app.go:276 +0x718\ngithub.com/docker-slim/docker-slim/internal/app/master.runCli()\n\tgithub.com/docker-slim/docker-slim@/internal/app/master/cli.go:1159 +0x55\ngithub.com/docker-slim/docker-slim/internal/app/master.Run()\n\tgithub.com/docker-slim/docker-slim@/internal/app/master/app.go:6 +0x25\nmain.main()\n\tgithub.com/docker-slim/docker-slim@/cmd/docker-slim/main.go:8 +0x20\n" version="darwin|Transformer|1.26.1|latest|latest"
```

**Comment by superbrothers** [comment]
This was fixed by #50648.
