### ISSUE TITLE
ruby-build should include libyaml as a dependency

### ISSUE THREAD

**Issue by dkam** [Homebrew/homebrew-core#5086]
If Homebrew was updated on Aug 10-11th 2016 and `brew update` always says `Already up-to-date.` you need to run: `cd "$(brew --repo)" && git fetch && git reset --hard origin/master && brew update`.

# Please follow the general troubleshooting steps first:

- [X] Ran `brew update` and retried your prior step?
- [X] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?

_You can erase any parts of this template not applicable to your Issue._

### Bug reports:

I believe ruby-build should include libyaml as a dependency

https://gist.github.com/dkam/15b5947ef3bfd7dbc2453626d57e5fd5

```
/Users/dkam/.rbenv/versions/2.3.1/lib/ruby/2.3.0/yaml.rb:5:in `<top (required)>':
It seems your ruby installation is missing psych (for YAML output).
To eliminate this warning, please install libyaml and reinstall your ruby.
The Ruby yaml extension was not compiled.
ERROR: Ruby install aborted due to missing extensions
Configure options used:
  --prefix=/Users/dkam/.rbenv/versions/2.3.1
  --with-openssl-dir=/usr/local/opt/openssl
  --with-readline-dir=/usr/local/opt/readline
  CC=clang
  CFLAGS= -O3 -Wno-error=shorten-64-to-32 
  LDFLAGS=-L/Users/dkam/.rbenv/versions/2.3.1/lib 
  CPPFLAGS=-I/Users/dkam/.rbenv/versions/2.3.1/include
```

**Comment by zmwangx** [comment]
That doesn't look like errors produced by `brew install ruby-build` because all it does is a few `mkdir` and `install`s: https://github.com/rbenv/ruby-build/blob/master/install.sh.

What command did you run?

**Comment by dkam** [comment]
It's an error from rbenv install 2.3.1

**Comment by zmwangx** [comment]
And why is that brew's fault?

**Comment by dkam** [comment]
I assumed that formula for ruby-build would install the decencies required for ruby-build to build ruby.

**Comment by zmwangx** [comment]
rbenv and ruby-build are popular formulae and so far we've yet to see issue reports but I'll look into it.

**Comment by zmwangx** [comment]
According to https://github.com/rbenv/ruby-build/wiki,

```sh
# optional, but recommended:
brew install openssl libyaml libffi
```

so I think you should follow that wiki.

**Comment by dkam** [comment]
Thanks @zmwangx  - perhaps it's actually an issue with Ruby-Build: 

```
 $ brew install openssl libyaml libffi
Warning: openssl-1.0.2h_1 already installed
Warning: libyaml-0.1.6_1 already installed
==> Downloading https://homebrew.bintray.com/bottles/libffi-3.0.13.sierra.bottle.tar.gz
######################################################################## 100.0%
==> Pouring libffi-3.0.13.sierra.bottle.tar.gz
==> Caveats
This formula is keg-only, which means it was not symlinked into /usr/local.

Some formulae require a newer version of libffi.

Generally there are no consequences of this for you. If you build your
own software and it requires this formula, you'll need to add to your
build variables:

    LDFLAGS:  -L/usr/local/opt/libffi/lib
    PKG_CONFIG_PATH: /usr/local/opt/libffi/lib/pkgconfig

==> Summary
🍺  /usr/local/Cellar/libffi/3.0.13: 15 files, 361.8K
dkam@Nervous-Energy ~  $ rbenv install 2.3.1
rbenv: /Users/dkam/.rbenv/versions/2.3.1 already exists
continue with installation? (y/N) y
Downloading ruby-2.3.1.tar.bz2...
-> https://cache.ruby-lang.org/pub/ruby/2.3/ruby-2.3.1.tar.bz2
Installing ruby-2.3.1...

BUILD FAILED (OS X 10.12 using ruby-build 20160602)

Inspect or clean up the working tree at /var/folders/m2/k7jbgnn56nd47_kd_qzjly780000gr/T/ruby-build.20160922120303.73435
Results logged to /var/folders/m2/k7jbgnn56nd47_kd_qzjly780000gr/T/ruby-build.20160922120303.73435.log

Last 10 log lines:
The Ruby yaml extension was not compiled.
ERROR: Ruby install aborted due to missing extensions
Configure options used:
  --prefix=/Users/dkam/.rbenv/versions/2.3.1
  --with-openssl-dir=/usr/local/opt/openssl
  --with-readline-dir=/usr/local/opt/readline
  CC=clang
  CFLAGS= -O3 -Wno-error=shorten-64-to-32 
  LDFLAGS=-L/Users/dkam/.rbenv/versions/2.3.1/lib 
  CPPFLAGS=-I/Users/dkam/.rbenv/versions/2.3.1/include 
```

The log file : 

```
installing capi-docs:         /Users/dkam/.rbenv/versions/2.3.1/share/doc/ruby
Ignoring bcrypt-3.1.11 because its extensions are not built.  Try: gem pristine bcrypt --version 3.1.11
Ignoring bcrypt-3.1.10 because its extensions are not built.  Try: gem pristine bcrypt --version 3.1.10
Ignoring binding_of_caller-0.7.2 because its extensions are not built.  Try: gem pristine binding_of_caller --version 0.7.2
Ignoring byebug-9.0.5 because its extensions are not built.  Try: gem pristine byebug --version 9.0.5
Ignoring byebug-8.2.4 because its extensions are not built.  Try: gem pristine byebug --version 8.2.4
Ignoring byebug-8.2.2 because its extensions are not built.  Try: gem pristine byebug --version 8.2.2
Ignoring cld-0.7.0 because its extensions are not built.  Try: gem pristine cld --version 0.7.0
Ignoring debug_inspector-0.0.2 because its extensions are not built.  Try: gem pristine debug_inspector --version 0.0.2
/Users/dkam/.rbenv/versions/2.3.1/lib/ruby/2.3.0/yaml.rb:5:in `<top (required)>':
It seems your ruby installation is missing psych (for YAML output).
To eliminate this warning, please install libyaml and reinstall your ruby.
The Ruby yaml extension was not compiled.
ERROR: Ruby install aborted due to missing extensions
Configure options used:
  --prefix=/Users/dkam/.rbenv/versions/2.3.1
  --with-openssl-dir=/usr/local/opt/openssl
  --with-readline-dir=/usr/local/opt/readline
  CC=clang
  CFLAGS= -O3 -Wno-error=shorten-64-to-32 
  LDFLAGS=-L/Users/dkam/.rbenv/versions/2.3.1/lib 
  CPPFLAGS=-I/Users/dkam/.rbenv/versions/2.3.1/include 
```

**Comment by zmwangx** [comment]
I can't reproduce on a clean 10.12 VM. Steps:

```sh
$ /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
$ brew install rbenv
$ rbenv install 2.3.1
...
Installed ruby-2.3.1 to /Users/zmwang/.rbenv/versions/2.3.1
```

**Comment by ilovezfs** [comment]
brew upgrade not brew install for things already installed

**Comment by dkam** [comment]
@ilovezfs  Thanks, homebrew was installed yesterday, and the formula are all up to date.

**Comment by dkam** [comment]
I should say, reinstalled.  I uninstalled from /usr/local, installed to ~/.brew, gave up on that idea and reinstalled in /usr/local.

**Comment by ilovezfs** [comment]
It's possible it's caused by `Ruby: /Users/dkam/.rbenv/shims/ruby => /Users/dkam/.rbenv/versions/2.3.1/bin/ruby`, which is what your brew config shows. I'd suggest trying this in a new user account to see if the problem is your profile or some other config problem.

**Comment by dkam** [comment]
Thanks @ilovezfs  - removing .rbenv and installing from scratch fixed this issue.

**Comment by ilovezfs** [comment]
You're welcome. Glad to hear it's fixed!
