### ISSUE TITLE
pypy failed to build on 10.12

### ISSUE THREAD

**Issue by Neal** [Homebrew/homebrew-core#5093]
Ran `brew upgrade` but pypy 5.4.1 fails to build.

https://gist.github.com/anonymous/f5e9f04f9cfe50d8555a8db568d4c420

**Comment by ilovezfs** [comment]
```
diff --git a/Formula/pypy.rb b/Formula/pypy.rb
index 2e0e85d..8db5f78 100644
--- a/Formula/pypy.rb
+++ b/Formula/pypy.rb
@@ -21,6 +21,7 @@ class Pypy < Formula
   depends_on "gdbm" => :recommended
   depends_on "sqlite" => :recommended
   depends_on "openssl"
+  depends_on "libffi"
 
   resource "bootstrap" do
     url "https://bitbucket.org/pypy/pypy/downloads/pypy-2.5.0-osx64.tar.bz2"
```

**Comment by mistydemeo** [comment]
Hm, pypy links against the system libffi okay on older versions of OS X.

**Comment by zmwangx** [comment]
This is a known issue. #4841 #1957 

I could be wrong but IIRC the problem isn't libffi, but rather librt.

**Comment by ilovezfs** [comment]
On 10.11
```
[c:writing] rpython_tool.c
[c:writing] rpython_translator.c
[c:writing] rpython_translator_c.c
[translation:info] written: /private/tmp/pypy-20160921-80760-ntmcn/pypy2-v5.4.1-src/usession-release-pypy2.7-v5.4.1-0/testing_1/testing_1.c
[30e1e] translation-task}
[translation:info] Compiling c source...
[30e1e] {translation-task
starting compile_c
[platform:execute] make -j 7 in /private/tmp/pypy-20160921-80760-ntmcn/pypy2-v5.4.1-src/usession-release-pypy2.7-v5.4.1-0/testing_1
[platform:Error] ld: library not found for -lrt
[platform:Error] clang: error: linker command failed with exit code 1 (use -v to see invocation)
[platform:Error] make: *** [libpypy-c.dylib] Error 1
[30e36] translation-task}
[Timer] Timings:
[Timer] annotate                       ---  321.4 s
[Timer] rtype_lltype                   ---  432.8 s
[Timer] pyjitpl_lltype                 ---  719.1 s
[Timer] backendopt_lltype              ---  109.2 s
[Timer] stackcheckinsertion_lltype     ---   63.4 s
[Timer] database_c                     ---  240.2 s
[Timer] source_c                       ---  110.3 s
[Timer] compile_c                      ---  139.4 s
[Timer] ===========================================
[Timer] Total:                         --- 2135.8 s
[translation:info] Error:
   File "/private/tmp/pypy-20160921-80760-ntmcn/pypy2-v5.4.1-src/rpython/translator/goal/translate.py", line 318, in main
    drv.proceed(goals)
   File "/private/tmp/pypy-20160921-80760-ntmcn/pypy2-v5.4.1-src/rpython/translator/driver.py", line 551, in proceed
    result = self._execute(goals, task_skip = self._maybe_skip())
   File "/private/tmp/pypy-20160921-80760-ntmcn/pypy2-v5.4.1-src/rpython/translator/tool/taskengine.py", line 114, in _execute
    res = self._do(goal, taskcallable, *args, **kwds)
   File "/private/tmp/pypy-20160921-80760-ntmcn/pypy2-v5.4.1-src/rpython/translator/driver.py", line 278, in _do
    res = func()
   File "/private/tmp/pypy-20160921-80760-ntmcn/pypy2-v5.4.1-src/rpython/translator/driver.py", line 518, in task_compile_c
    cbuilder.compile(**kwds)
   File "/private/tmp/pypy-20160921-80760-ntmcn/pypy2-v5.4.1-src/rpython/translator/c/genc.py", line 396, in compile
    extra_opts)
   File "/private/tmp/pypy-20160921-80760-ntmcn/pypy2-v5.4.1-src/rpython/translator/platform/posix.py", line 219, in execute_makefile
    self._handle_error(returncode, stdout, stderr, path.join('make'))
   File "/private/tmp/pypy-20160921-80760-ntmcn/pypy2-v5.4.1-src/rpython/translator/platform/__init__.py", line 152, in _handle_error
    raise CompilationError(stdout, stderr)
[translation:ERROR] CompilationError: CompilationError(err="""
	ld: library not found for -lrt
	clang: error: linker command failed with exit code 1 (use -v to see invocation)
	make: *** [libpypy-c.dylib] Error 1
	""")
[translation] start debugger...
in get_rpath_flags, rel_libdirs is not fixed up ['/usr/local/Cellar/openssl/1.0.2h_1/lib', '/usr/lib']
> /private/tmp/pypy-20160921-80760-ntmcn/pypy2-v5.4.1-src/rpython/translator/platform/__init__.py(152)_handle_error()
-> raise CompilationError(stdout, stderr)
Traceback (most recent call last):
  File "app_main.py", line 75, in run_toplevel
    raise SystemExit(exitcode)
  File "/private/tmp/pypy-20160921-80760-ntmcn/pypy2-v5.4.1-src/rpython/bin/rpython", line 20, in <module>
    main()
  File "/private/tmp/pypy-20160921-80760-ntmcn/pypy2-v5.4.1-src/rpython/translator/goal/translate.py", line 325, in main
    debug(True)
  File "/private/tmp/pypy-20160921-80760-ntmcn/pypy2-v5.4.1-src/rpython/translator/goal/translate.py", line 278, in debug
    pdb_plus_show.start(tb)
  File "/private/tmp/pypy-20160921-80760-ntmcn/pypy2-v5.4.1-src/rpython/translator/tool/pdbplus.py", line 442, in start
    fn(*args)
  File "/private/tmp/pypy-20160921-80760-ntmcn/pypy2-v5.4.1-src/rpython/translator/tool/pdbplus.py", line 25, in post_mortem
    self.interaction(t.tb_frame, t)
  File "/private/tmp/pypy-20160921-80760-ntmcn/pypy2-v5.4.1-src/bootstrap/lib-python/2.7/pdb.py", line 210, in interaction
    self.cmdloop()
  File "/private/tmp/pypy-20160921-80760-ntmcn/pypy2-v5.4.1-src/bootstrap/lib-python/2.7/cmd.py", line 109, in cmdloop
    self.preloop()
  File "/private/tmp/pypy-20160921-80760-ntmcn/pypy2-v5.4.1-src/rpython/translator/tool/pdbplus.py", line 29, in preloop
    raise NoTTY("Cannot start the debugger when stdout is captured.")
NoTTY: Cannot start the debugger when stdout is captured.
/usr/local/Homebrew/Library/Homebrew/debrew.rb:11:in `raise'
BuildError: Failed executing: /private/tmp/pypy-20160921-80760-ntmcn/pypy2-v5.4.1-src/bootstrap/bin/pypy /private/tmp/pypy-20160921-80760-ntmcn/pypy2-v5.4.1-src/rpython/bin/rpython -Ojit --shared --cc clang --verbose --make-jobs 7 targetpypystandalone.py
```

**Comment by zmwangx** [comment]
Makes sense. I think the problem could be pypy's build system assuming `-lrt` when `clock_gettime` is available.

**Comment by dcrosta** [comment]
I've logged https://bitbucket.org/pypy/pypy/issues/2407/pypy-541-fails-to-build-on-macos-sierra, in case this ends up requiring an upstream fix.
