### ISSUE TITLE
bug: brew audit  is throwing Error: type mismatch: String given

### ISSUE THREAD

**Issue by rogeriopradoj** [Homebrew/homebrew-core#5249]
[brew config and brew doctor outputs](https://gist.github.com/rogeriopradoj/b917b023452e8740eba59f8a37b3a343)

- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?

When I trying to create a new formula, build (`brew install`) got ok but audit (`brew audit`) throws a error (with flags `--new-formula` or `--online --strict`):

```
$ brew audit --new-formula /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/hostess.rb

Error: type mismatch: String given
Please report this bug:
    https://git.io/brew-troubleshooting
/usr/local/Homebrew/Library/Homebrew/cmd/search.rb:153:in `=~'
/usr/local/Homebrew/Library/Homebrew/cmd/search.rb:153:in `block in search_tap'
/usr/local/Homebrew/Library/Homebrew/cmd/search.rb:153:in `select'
/usr/local/Homebrew/Library/Homebrew/cmd/search.rb:153:in `search_tap'
/usr/local/Homebrew/Library/Homebrew/dev-cmd/audit.rb:347:in `block (2 levels) in audit_formula_name'
```

```
$ brew audit --online --strict /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/hostess.rb
Error: type mismatch: String given
Please report this bug:
    https://git.io/brew-troubleshooting
/usr/local/Homebrew/Library/Homebrew/cmd/search.rb:153:in `=~'
/usr/local/Homebrew/Library/Homebrew/cmd/search.rb:153:in `block in search_tap'
/usr/local/Homebrew/Library/Homebrew/cmd/search.rb:153:in `select'
/usr/local/Homebrew/Library/Homebrew/cmd/search.rb:153:in `search_tap'
/usr/local/Homebrew/Library/Homebrew/dev-cmd/audit.rb:347:in `block (2 levels) in audit_formula_name'
```

When running a simple `brew audit` against the same formula, everything goes fine:

```
$ brew audit /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/hostess.rb

# no output
```

When running separatelly `brew audit --online` or `brew audit --strict`, everything goes fine:

```
$ brew audit --online  /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/hostess.rb

# no output
```

```
$ brew audit --strict  /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/hostess.rb

# no output
```

In order to prove that the issue is not with my new formula but with `homebrew`, that's the output of `brew audit` against other official formulas:

- **coda-cli**

```
$ brew audit --strict coda-cli
# no output

$ brew audit --online coda-cli
# no output

$ brew audit --online --strict coda-cli
Error: type mismatch: String given
Please report this bug:
    https://git.io/brew-troubleshooting
/usr/local/Homebrew/Library/Homebrew/cmd/search.rb:153:in `=~'
/usr/local/Homebrew/Library/Homebrew/cmd/search.rb:153:in `block in search_tap'
/usr/local/Homebrew/Library/Homebrew/cmd/search.rb:153:in `select'
/usr/local/Homebrew/Library/Homebrew/cmd/search.rb:153:in `search_tap'
/usr/local/Homebrew/Library/Homebrew/dev-cmd/audit.rb:347:in `block (2 levels) in audit_formula_name'

$ brew audit --new-formula coda-cli
Error: type mismatch: String given
Please report this bug:
    https://git.io/brew-troubleshooting
/usr/local/Homebrew/Library/Homebrew/cmd/search.rb:153:in `=~'
/usr/local/Homebrew/Library/Homebrew/cmd/search.rb:153:in `block in search_tap'
/usr/local/Homebrew/Library/Homebrew/cmd/search.rb:153:in `select'
/usr/local/Homebrew/Library/Homebrew/cmd/search.rb:153:in `search_tap'
/usr/local/Homebrew/Library/Homebrew/dev-cmd/audit.rb:347:in `block (2 levels) in audit_formula_name'
```
- ** ipcalc**

```
$ brew audit --strict ipcalc
# no output

$ brew audit --online ipcalc
# no output

$ brew audit --online --strict ipcalc
Error: type mismatch: String given
Please report this bug:
    https://git.io/brew-troubleshooting
/usr/local/Homebrew/Library/Homebrew/cmd/search.rb:153:in `=~'
/usr/local/Homebrew/Library/Homebrew/cmd/search.rb:153:in `block in search_tap'
/usr/local/Homebrew/Library/Homebrew/cmd/search.rb:153:in `select'
/usr/local/Homebrew/Library/Homebrew/cmd/search.rb:153:in `search_tap'
/usr/local/Homebrew/Library/Homebrew/dev-cmd/audit.rb:347:in `block (2 levels) in audit_formula_name'

$ brew audit --new-formula ipcalc
Error: type mismatch: String given
Please report this bug:
    https://git.io/brew-troubleshooting
/usr/local/Homebrew/Library/Homebrew/cmd/search.rb:153:in `=~'
/usr/local/Homebrew/Library/Homebrew/cmd/search.rb:153:in `block in search_tap'
/usr/local/Homebrew/Library/Homebrew/cmd/search.rb:153:in `select'
/usr/local/Homebrew/Library/Homebrew/cmd/search.rb:153:in `search_tap'
/usr/local/Homebrew/Library/Homebrew/dev-cmd/audit.rb:347:in `block (2 levels) in audit_formula_name'
```

Thanks in advance!

**Comment by ilovezfs** [comment]
Have you run `brew update`? I believe this was fixed in https://github.com/Homebrew/brew/commit/6e5735565b9a31ec2b01e02a479a361189729c22

**Comment by rogeriopradoj** [comment]
Hi, @ilovezfs , yes, I run! https://gist.github.com/rogeriopradoj/b917b023452e8740eba59f8a37b3a343

**Comment by ilovezfs** [comment]
Can you try `git checkout master` and see if it goes away?

**Comment by rogeriopradoj** [comment]
```
$ pwd
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula

$ git checkout master
Already on 'master'
Your branch is up-to-date with 'origin/master'.

$ git remote -v
origin	https://github.com/Homebrew/homebrew-core (fetch)
origin	https://github.com/Homebrew/homebrew-core (push)
```

**Comment by rogeriopradoj** [comment]
@ilovezfs Wrong path?

**Comment by ilovezfs** [comment]
Yeah, sorry `cd /usr/local/Homebrew`

**Comment by rogeriopradoj** [comment]
@ilovezfs worked! Is `git checkout master` just a workaround, or it is permanent?

**Comment by ilovezfs** [comment]
It's a workaround until you get upgraded to 1.0.5
https://github.com/Homebrew/brew/releases

**Comment by rogeriopradoj** [comment]
@ilovezfs alright, thanks! I saw that I was stucked with 1.0.3 (even with 1.0.4 released).

`brew update` should have bumped it to 1.0.4? I did something wrong?

**Comment by ilovezfs** [comment]
Na, you didn't do anything wrong. That was another bug that left some people stranded at an earlier point.

**Comment by rogeriopradoj** [comment]
@ilovezfs alright, thanks! Could you help me with the commands that I should run when 1.0.5 is released?

```
cd "$(brew --repo)" && git fetch && git reset --hard origin/master && brew update
```

**Comment by ilovezfs** [comment]
I believe `brew update` will automatically put you on the tag. But what you said above is fine in terms of doing it manually as long as you also `git checkout 1.0.5` at the end :)

**Comment by rogeriopradoj** [comment]
Alright. I'll ping you if that works in the end. Thanks again!

**Comment by ilovezfs** [comment]
You're welcome :)

**Comment by dunn** [comment]
Assuming fixed.

**Comment by rogeriopradoj** [comment]
:+1:
