### ISSUE TITLE
All brew commands broken after installing `emacs-plus`

### ISSUE THREAD

**Issue by dymk** [Homebrew/homebrew-core#5256]
If Homebrew was updated on Aug 10-11th 2016 and `brew update` always says `Already up-to-date.` you need to run: `cd "$(brew --repo)" && git fetch && git reset --hard origin/master && brew update`.

# Please follow the general troubleshooting steps first:

`brew update`, `brew doctor` have been attempted

After installing `emacs-plus`, using the instructions provided on https://github.com/syl20bnr/spacemacs/blob/master/README.md#os-x, 

which performed this: 

```
dymk@Codeinator ~/.e/l/PG (master) [1]> brew install emacs-plus --with-cocoa --with-gnutls --with-librsvg --with-imagemagick --with-spacemacs-icon
==> Installing emacs-plus from d12frosted/emacs-plus
==> Installing dependencies for d12frosted/emacs-plus/emacs-plus: libtasn1, nettle, gnutls, libpng, freetype, fontconfig, pixman, gettext, pcre, glib, cairo, libtiff, pkg-config, gobject-introspection, gdk-pixbuf, libcroco, icu4c, harfbuzz, pango, librsvg, imagemagick
==> Installing d12frosted/emacs-plus/emacs-plus dependency: libtasn1
==> Downloading https://homebrew.bintray.com/bottles/libtasn1-4.9.el_capitan.bottle.tar.gz
######################################################################## 100.0%
==> Pouring libtasn1-4.9.el_capitan.bottle.tar.gz
🍺  /usr/local/Cellar/libtasn1/4.9: 58 files, 437K

.... more lines ...

==> Pouring libcroco-0.6.11.el_capitan.bottle.tar.gz
Error: No such file or directory - getcwd
Warning: Bottle installation failed: building from source.
==> Installing dependencies for libcroco: intltool
==> Installing libcroco dependency: intltool
==> Downloading https://homebrew.bintray.com/bottles/intltool-0.51.0.el_capitan.bottle.tar.gz
######################################################################## 100.0%
Error: No such file or directory - getcwd
Warning: Bottle installation failed: building from source.
sudo: cannot get working directory
/usr/local/Homebrew/Library/Homebrew/utils.rb:424:in `[]': No such file or directory - getcwd (Errno::ENOENT)
	from /usr/local/Homebrew/Library/Homebrew/utils.rb:424:in `which_all'
	from /usr/local/Homebrew/Library/Homebrew/gpg.rb:5:in `find_gpg'
	from /usr/local/Homebrew/Library/Homebrew/gpg.rb:17:in `gpg2'
	from /usr/local/Homebrew/Library/Homebrew/gpg.rb:20:in `<class:Gpg>'
	from /usr/local/Homebrew/Library/Homebrew/gpg.rb:3:in `<top (required)>'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/local/Homebrew/Library/Homebrew/requirements/gpg2_requirement.rb:2:in `<top (required)>'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/local/Homebrew/Library/Homebrew/requirements.rb:4:in `<top (required)>'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/local/Homebrew/Library/Homebrew/dependency_collector.rb:5:in `<top (required)>'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/local/Homebrew/Library/Homebrew/software_spec.rb:7:in `<top (required)>'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/local/Homebrew/Library/Homebrew/formula.rb:10:in `<top (required)>'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/local/Homebrew/Library/Homebrew/readall.rb:1:in `<top (required)>'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/local/Homebrew/Library/Homebrew/tap.rb:2:in `<top (required)>'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/local/Homebrew/Library/Homebrew/compat/tap.rb:1:in `<top (required)>'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/local/Homebrew/Library/Homebrew/compat.rb:2:in `<top (required)>'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/local/Homebrew/Library/Homebrew/global.rb:55:in `<top (required)>'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/local/Homebrew/Library/Homebrew/build.rb:6:in `<main>'
Error: Failure while executing: /usr/bin/sandbox-exec -f /tmp/homebrew20160926-47296-svhh5a.sb nice /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin/ruby -W0 -I /usr/local/Homebrew/Library/Homebrew -- /usr/local/Homebrew/Library/Homebrew/build.rb /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/intltool.rb
```

Running any brew command results in this: 

```
dymk@Codeinator ~/.e/l/PG [1]> brew uninstall emacs-plus
shell-init: error retrieving current directory: getcwd: cannot access parent directories: No such file or directory
chdir: error retrieving current directory: getcwd: cannot access parent directories: No such file or directory
chdir: error retrieving current directory: getcwd: cannot access parent directories: No such file or directory
chdir: error retrieving current directory: getcwd: cannot access parent directories: No such file or directory
pwd: error retrieving current directory: getcwd: cannot access parent directories: No such file or directory
Error: The current working directory doesn't exist, cannot proceed.
dymk@Codeinator ~/.e/l/PG [1]> brew update
shell-init: error retrieving current directory: getcwd: cannot access parent directories: No such file or directory
chdir: error retrieving current directory: getcwd: cannot access parent directories: No such file or directory
chdir: error retrieving current directory: getcwd: cannot access parent directories: No such file or directory
chdir: error retrieving current directory: getcwd: cannot access parent directories: No such file or directory
pwd: error retrieving current directory: getcwd: cannot access parent directories: No such file or directory
Error: The current working directory doesn't exist, cannot proceed.
dymk@Codeinator ~/.e/l/PG [1]> brew --repo
shell-init: error retrieving current directory: getcwd: cannot access parent directories: No such file or directory
chdir: error retrieving current directory: getcwd: cannot access parent directories: No such file or directory
chdir: error retrieving current directory: getcwd: cannot access parent directories: No such file or directory
chdir: error retrieving current directory: getcwd: cannot access parent directories: No such file or directory
/usr/local/Homebrew
dymk@Codeinator ~/.e/l/PG> brew doctor
shell-init: error retrieving current directory: getcwd: cannot access parent directories: No such file or directory
chdir: error retrieving current directory: getcwd: cannot access parent directories: No such file or directory
chdir: error retrieving current directory: getcwd: cannot access parent directories: No such file or directory
chdir: error retrieving current directory: getcwd: cannot access parent directories: No such file or directory
pwd: error retrieving current directory: getcwd: cannot access parent directories: No such file or directory
Error: The current working directory doesn't exist, cannot proceed.
dymk@Codeinator ~/.e/l/PG [1]> brew gist-logs emacs-plus
shell-init: error retrieving current directory: getcwd: cannot access parent directories: No such file or directory
chdir: error retrieving current directory: getcwd: cannot access parent directories: No such file or directory
chdir: error retrieving current directory: getcwd: cannot access parent directories: No such file or directory
chdir: error retrieving current directory: getcwd: cannot access parent directories: No such file or directory
pwd: error retrieving current directory: getcwd: cannot access parent directories: No such file or directory
Error: The current working directory doesn't exist, cannot proceed.
```

**Comment by dymk** [comment]
This seems to be triggered when `brew` is run from a directory which does not exist. Perhaps this  is a case that should be handled?

**Comment by dunn** [comment]
Many commands fail when run from a non-existent directory, I don't think this is unique to `brew`.

**Comment by DomT4** [comment]
Yeah, this is pretty unixy and I'm not sure it wouldn't be more confusing if we handled it in `brew` and then the second you stepped outside `brew` to start doing things in that no-longer-existing directory commands started failing or behaving strangely.

Would potentially review a PR to handle it in `brew` but I'm not sure how sensible it is to mess with the status quo here, which is at least well understood.

**Comment by dymk** [comment]
👍  Sounds reasonable to me
