### ISSUE TITLE
brew install aws-ssh throws aerror

### ISSUE THREAD

**Issue by malayprocore** [Homebrew/homebrew-core#53468]
- [Yes ] ran `brew update` and can still reproduce the problem? Yes
- [ Yes] ran `brew doctor`, fixed all issues and can still reproduce the problem? Yes
- [ Yes] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [Yes ] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

## What you were trying to do (and why)

Installing aws-ssh to run ssh in aws

Executed brew tap procore/tap git@github.com:procore/homebrew-tap.git
Then executed  brew install aws-ssh
Got below error

<details>
  <summary>Command output</summary>
  <pre>

   Updating Homebrew...
Error: undefined method `name' for nil:NilClass
Please report this issue:
  https://docs.brew.sh/Troubleshooting
/usr/local/Homebrew/Library/Homebrew/exceptions.rb:189:in `block in initialize'
/usr/local/Homebrew/Library/Homebrew/exceptions.rb:188:in `map'
/usr/local/Homebrew/Library/Homebrew/exceptions.rb:188:in `initialize'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:436:in `new'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:436:in `loader_for'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:332:in `factory'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:499:in `find_with_priority'
/usr/local/Homebrew/Library/Homebrew/cli/args.rb:90:in `block in formulae'
/usr/local/Homebrew/Library/Homebrew/cli/args.rb:86:in `map'
/usr/local/Homebrew/Library/Homebrew/cli/args.rb:86:in `formulae'
/usr/local/Homebrew/Library/Homebrew/cli/parser.rb:190:in `formula_options'
/usr/local/Homebrew/Library/Homebrew/cmd/install.rb:90:in `block in install_args'
/usr/local/Homebrew/Library/Homebrew/cli/parser.rb:53:in `instance_eval'
/usr/local/Homebrew/Library/Homebrew/cli/parser.rb:53:in `initialize'
/usr/local/Homebrew/Library/Homebrew/cmd/install.rb:17:in `new'
/usr/local/Homebrew/Library/Homebrew/cmd/install.rb:17:in `install_args'
/usr/local/Homebrew/Library/Homebrew/cmd/install.rb:96:in `install'
/usr/local/Homebrew/Library/Homebrew/brew.rb:110:in `<main>' 

  </pre>
</details>

## What you expected to happen

brew tap procore/tap git@github.com:procore/homebrew-tap.git
brew install aws-ssh

**Comment by malayprocore** [comment]
Here is brew tap output
$ brew tap
homebrew/core
homebrew/services
malay.biswal@procore.com/tap
procore/tap
weaveworks/tap

**Comment by malayprocore** [comment]
$ brew config
HOMEBREW_VERSION: 2.2.13
ORIGIN: https://github.com/Homebrew/brew
HEAD: 3d9cf83fec45a75af61551f53d25383abe009d31
Last commit: 8 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 2fe1503805753121be8767d9a6889ce84bc09fed
Core tap last commit: 5 hours ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_MAKE_JOBS: 12
CPU: dodeca-core 64-bit kabylake
Homebrew Ruby: 2.6.3 => /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3/bin/ruby
Clang: 11.0 build 1100
Git: 2.21.0 => /Library/Developer/CommandLineTools/usr/bin/git
Curl: 7.64.1 => /usr/bin/curl
Java: 13.0.1, 1.8.0_232
macOS: 10.15.3-x86_64
CLT: 11.0.33.16
Xcode: N/A

**Comment by malayprocore** [comment]
I did brew untap procore/homebrew-tap
and then i could install aws-ssh
