### ISSUE TITLE
Unable to install postgresql by using brew

### ISSUE THREAD

**Issue by BDitta** [Homebrew/homebrew-core#54622]
1) ran `brew update` and can still reproduce the problem?

Yes

2) ran `brew doctor`, fixed all issues and can still reproduce the problem?

That command gives a similar error, this one:

```
Error: Cannot parse /usr/local/Cellar/ncurses/6.1/INSTALL_RECEIPT.json: 767: unexpected token at ''
Please report this issue:
  https://docs.brew.sh/Troubleshooting
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/json/common.rb:156:in `parse'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/json/common.rb:156:in `parse'
/usr/local/Homebrew/Library/Homebrew/tab.rb:64:in `from_file_content'
/usr/local/Homebrew/Library/Homebrew/tab.rb:58:in `block in from_file'
/usr/local/Homebrew/Library/Homebrew/tab.rb:58:in `fetch'
/usr/local/Homebrew/Library/Homebrew/tab.rb:58:in `from_file'
/usr/local/Homebrew/Library/Homebrew/tab.rb:107:in `for_keg'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:367:in `from_keg'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:351:in `from_rack'
/usr/local/Homebrew/Library/Homebrew/diagnostic.rb:754:in `block in check_for_unlinked_but_not_keg_only'
/usr/local/Homebrew/Library/Homebrew/diagnostic.rb:751:in `reject'
/usr/local/Homebrew/Library/Homebrew/diagnostic.rb:751:in `check_for_unlinked_but_not_keg_only'
/usr/local/Homebrew/Library/Homebrew/cmd/doctor.rb:61:in `block in doctor'
/usr/local/Homebrew/Library/Homebrew/cmd/doctor.rb:53:in `each'
/usr/local/Homebrew/Library/Homebrew/cmd/doctor.rb:53:in `doctor'
/usr/local/Homebrew/Library/Homebrew/brew.rb:110:in `<main>'
```

3) ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?

No formula, just the command I wrote.

4) if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

**brew config** gives this:

```
HOMEBREW_VERSION: 2.2.16
ORIGIN: https://github.com/Homebrew/brew
HEAD: c0f5a52d85d3606e7600162a9d38936ab4b46f4f
Last commit: 2 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 5d25169f884afb701a922651e1e4ecb03131db71
Core tap last commit: 59 minutes ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_MAKE_JOBS: 8
CPU: octa-core 64-bit kabylake
Homebrew Ruby: 2.6.3 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
Clang: 11.0 build 1103
Git: 2.22.0 => /usr/local/bin/git
Curl: 7.64.1 => /usr/bin/curl
Java: 11.0.6, 1.8.0_65
macOS: 10.15.4-x86_64
CLT: 11.4.1.0.1.1586360307
Xcode: N/A
```

**brew doctor**: see above

## What you were trying to do (and why)

Tried to install postgresql by using the command `brew install postgresql@11`.

## What happened (include command output)

Got this output:
```
Updating Homebrew...
==> Installing dependencies for postgresql@11: icu4c, openssl@1.1 and readline
Error: Cannot parse /usr/local/Cellar/icu4c/64.2/INSTALL_RECEIPT.json: 767: unexpected token at '<web-app xmlns="http://java.sun.com/xml/ns/j2ee"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://java.sun.com/xml/ns/j2ee
http://java.sun.com/xml/ns/j2ee/web-app_2_4.xsd"
         version="2.4">
    <servlet>
        <servlet-name>Hello</servlet-name>
        <servlet-class>org.gradle.HelloServlet</servlet-class>
    </servlet>
    <servlet-mapping>
        <servlet-name>Hello</servlet-name>
        <url-pattern>/hello</url-pattern>
    </servlet-mapping>
??v}|B???/?٭??Z??PAI??'Z?D?hⱃl??L~??H???RI:i(????h?*'????Z?&??2??M?|x?AU??)f~́????#/
Please report this issue:
  https://docs.brew.sh/Troubleshooting
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/json/common.rb:156:in `parse'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/json/common.rb:156:in `parse'
/usr/local/Homebrew/Library/Homebrew/tab.rb:64:in `from_file_content'
/usr/local/Homebrew/Library/Homebrew/tab.rb:58:in `block in from_file'
/usr/local/Homebrew/Library/Homebrew/tab.rb:58:in `fetch'
/usr/local/Homebrew/Library/Homebrew/tab.rb:58:in `from_file'
/usr/local/Homebrew/Library/Homebrew/tab.rb:151:in `for_formula'
/usr/local/Homebrew/Library/Homebrew/formula_installer.rb:566:in `install_dependency'
/usr/local/Homebrew/Library/Homebrew/formula_installer.rb:558:in `block in install_dependencies'
/usr/local/Homebrew/Library/Homebrew/formula_installer.rb:558:in `each'
/usr/local/Homebrew/Library/Homebrew/formula_installer.rb:558:in `install_dependencies'
/usr/local/Homebrew/Library/Homebrew/formula_installer.rb:265:in `install'
/usr/local/Homebrew/Library/Homebrew/cmd/install.rb:329:in `install_formula'
/usr/local/Homebrew/Library/Homebrew/cmd/install.rb:261:in `block in install'
/usr/local/Homebrew/Library/Homebrew/cmd/install.rb:259:in `each'
/usr/local/Homebrew/Library/Homebrew/cmd/install.rb:259:in `install'
/usr/local/Homebrew/Library/Homebrew/brew.rb:110:in `<main>'
```

## What you expected to happen

I expected postgresql to be installed and also expected to be notified by a message that the installation was successful.

## Step-by-step reproduction instructions (by running `brew install` commands)

Run the command `brew install postgresql@11` (in the home directory).

## Note

Originally, I received another similar error message when I was trying to uninstall postgresql and then I deleted the file (in which brew found the unexpected token), which fixed the issue. However, I'm not sure if I simply deleting every file brew has a problem with is the correct solution...

**Comment by SMillerDev** [comment]
Somehow something overwrote some homebrew files with a java configuration file. To restore functionality you might want to remove the specific files it complains about and then do `brew reinstall ncurses icu4c`

**Comment by BDitta** [comment]
> Somehow something overwrote some homebrew files with a java configuration file. To restore functionality you might want to remove the specific files it complains about and then do `brew reinstall ncurses icu4c`

This worked, thanks! :)
