### ISSUE TITLE
'cython' distribution was not found and is required by urh

### ISSUE THREAD

**Issue by mikemorris** [Homebrew/homebrew-core#55177]
- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew gist-logs urh`https://gist.github.com/mikemorris/a0769646d758c61841518daba91dbdeb
- [ ] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

## What you were trying to do (and why)

```shellsession
$ brew install urh
$ urh
```

## What happened (include command output)

Attempting to run `urh` fails because it can't find installed `cython` lib.

<details>
  <summary>Command output</summary>
  <pre>
  Traceback (most recent call last):
  File "/usr/local/Cellar/urh/2.8.8/libexec/bin/urh", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/usr/local/lib/python3.8/site-packages/pkg_resources/__init__.py", line 3255, in <module>
    def _initialize_master_working_set():
  File "/usr/local/lib/python3.8/site-packages/pkg_resources/__init__.py", line 3238, in _call_aside
    f(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/pkg_resources/__init__.py", line 3267, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/local/lib/python3.8/site-packages/pkg_resources/__init__.py", line 584, in _build_master
    ws.require(__requires__)
  File "/usr/local/lib/python3.8/site-packages/pkg_resources/__init__.py", line 901, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/local/lib/python3.8/site-packages/pkg_resources/__init__.py", line 787, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'cython' distribution was not found and is required by urh
  </pre>
</details>

## What you expected to happen

`urh` should launch without needing to manually install dependencies.

## Step-by-step reproduction instructions (by running `brew install` commands)

Running `/usr/local/bin/pip3.8 install cython` to manually install Cython fixes the missing dependency and `urh` launches fine.

**Comment by mikemorris** [comment]
From discussion in https://github.com/Homebrew/homebrew-core/pull/13794 I'm guessing this should maybe be migrated from a Cython resource to `depends_on "cython" => :build` but I'm not entirely sure if `PYTHONPATH` or some other build config would need to be adjusted.

**Comment by Amar1729** [comment]
This can be closed, above PR's commits were merged.
