### ISSUE TITLE
libass fails to upgrade 0.13.3 to 0.13.4 on 10.12, Xcode 8

### ISSUE THREAD

**Issue by dchammond** [Homebrew/homebrew-core#5614]
# Please follow the general troubleshooting steps first:

- [X] Ran `brew update` and retried your prior step?
- [X] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?
### Bug reports:

```
Upgrading to libass to 0.13.4 fails with the error `==> Upgrading 1 outdated package, with result:
libass 0.13.4
==> Upgrading libass
==> Using the sandbox
Error: undefined method 
/' for nil:NilClass
Please report this bug:
  https://git.io/brew-troubleshooting
/usr/local/Homebrew/Library/Homebrew/os/mac/xquartz.rb:127:in `bin'
/usr/local/Homebrew/Library/Homebrew/extend/os/mac/extend/ENV/super.rb:22:in `homebrew_extra_paths'
/usr/local/Homebrew/Library/Homebrew/extend/ENV/super.rb:111:in `determine_path'
/usr/local/Homebrew/Library/Homebrew/extend/ENV/super.rb:45:in `setup_build_environment'
/usr/local/Homebrew/Library/Homebrew/extend/os/mac/extend/ENV/super.rb:89:in `setup_build_environment'
/usr/local/Homebrew/Library/Homebrew/build.rb:85:in `install'
/usr/local/Homebrew/Library/Homebrew/build.rb:187:in `<main>'
```

For some reason `brew gist-logs libass` gives `Error: No logs.`

**Comment by BrettDong** [comment]
Strange, I managed to upgrade to libass 0.13.4 this morning.
```
BrettdeMacBook-Air:art-of-readme brett$ brew info libass
libass: stable 0.13.4 (bottled), HEAD
Subtitle renderer for the ASS/SSA subtitle format
https://github.com/libass/libass
/usr/local/Cellar/libass/0.13.3 (9 files, 509.0K)
  Poured from bottle on 2016-10-04 at 17:59:42
/usr/local/Cellar/libass/0.13.4 (10 files, 511.2K) *
  Poured from bottle on 2016-10-07 at 09:52:40
From: https://github.com/Homebrew/homebrew-core/blob/master/Formula/libass.rb
==> Dependencies
Build: pkg-config ✔, yasm ✔
Required: freetype ✔, fribidi ✔
Recommended: harfbuzz ✔
Optional: fontconfig ✔
==> Options
--with-fontconfig
	Disable CoreText backend in favor of the more traditional fontconfig
--without-harfbuzz
	Build without harfbuzz support
--HEAD
	Install HEAD version
```

**Comment by dchammond** [comment]
Hm well the issue seems to have fixed itself... I was able to upgrade with no problems. Bizarre.
