### ISSUE TITLE
pup crashes, file reports compiled magic version doesn't match

### ISSUE THREAD

**Issue by PenelopeFudd** [Homebrew/homebrew-core#58333]
# Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.

- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [n/a] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [x] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?
```
$ brew config
HOMEBREW_VERSION: 2.4.8
ORIGIN: https://github.com/Homebrew/brew
HEAD: 13f0d4ad2b0773c01c5fdd5f8cba3e4f312c1c96
Last commit: 4 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: b8d04beb5bcb29fbe34f85157a51b3fd070983de
Core tap last commit: 22 minutes ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_EDITOR: vim
HOMEBREW_MAKE_JOBS: 8
CPU: octa-core 64-bit haswell
Homebrew Ruby: 2.6.3 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
Clang: 11.0 build 1103
Git: 2.24.3 => /Library/Developer/CommandLineTools/usr/bin/git
Curl: 7.64.1 => /usr/bin/curl
Java: 1.8.0_242
macOS: 10.15.5-x86_64
CLT: 11.5.0.0.1.1588476445
Xcode: N/A

$ brew doctor
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: Putting non-prefixed findutils in your path can cause python builds to fail.
```

## What you were trying to do (and why)

I was trying to run the 'pup' command to extract text from html files.  Then I tried running the 'file' command to see why pup was dying with a signal 11.

## What happened (include command output)

<details>
  <summary>Command output</summary>
  <pre>
  $ pup
  Segmentation fault: 11
  $ file -L $(which pup)
  file: Compiled magic version [538] does not match with shared library magic version [539]

  /usr/local/bin/pup: Mach-O 64-bit x86_64 executable, flags:&lt;NOUNDEFS&gt;
  </pre>
</details>

## What you expected to happen

I expected to get a usage message from pup.
I didn't expect a warning message from file.

## Step-by-step reproduction instructions (by running `brew install` commands)

```
brew update
brew upgrade
brew install file
brew install pup
pup  # Segmentation fault: 11 --- not a usage message as expected.
file $(which pup)
```

Not shown: the problems I had with broken library dependencies (readline, openssl, gawk, yamllint, possibly others)
At one point, I had to link /usr/bin/awk to /usr/local/bin/gawk temporarily to get unstuck.

**Comment by SMillerDev** [comment]
What does `brew test pup` say?

**Comment by Bo98** [comment]
The `file` part should be fixed now. Please run `brew upgrade file`.

**Comment by PenelopeFudd** [comment]
```
$ brew test pup
Testing pup
==> /usr/local/Cellar/pup/0.4.0/bin/pup p text{}
Error: pup: failed
An exception occurred within a child process:
  Test::Unit::AssertionFailedError: <0> expected but was
<nil>.
/Library/Ruby/Gems/2.6.0/gems/test-unit-3.2.9/lib/test/unit/assertions.rb:55:in `block in assert_block'
/Library/Ruby/Gems/2.6.0/gems/test-unit-3.2.9/lib/test/unit/assertions.rb:1636:in `_wrap_assertion'
/Library/Ruby/Gems/2.6.0/gems/test-unit-3.2.9/lib/test/unit/assertions.rb:53:in `assert_block'
/Library/Ruby/Gems/2.6.0/gems/test-unit-3.2.9/lib/test/unit/assertions.rb:240:in `assert_equal'
/usr/local/Homebrew/Library/Homebrew/formula_assertions.rb:28:in `pipe_output'
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/pup.rb:36:in `block in <class:Pup>'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1825:in `block (3 levels) in run_test'
/usr/local/Homebrew/Library/Homebrew/utils.rb:474:in `with_env'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1824:in `block (2 levels) in run_test'
/usr/local/Homebrew/Library/Homebrew/formula.rb:900:in `with_logging'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1823:in `block in run_test'
/usr/local/Homebrew/Library/Homebrew/formula.rb:2067:in `block in mktemp'
/usr/local/Homebrew/Library/Homebrew/mktemp.rb:57:in `block in run'
/usr/local/Homebrew/Library/Homebrew/mktemp.rb:57:in `chdir'
/usr/local/Homebrew/Library/Homebrew/mktemp.rb:57:in `run'
/usr/local/Homebrew/Library/Homebrew/formula.rb:2066:in `mktemp'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1817:in `run_test'
/usr/local/Homebrew/Library/Homebrew/test.rb:35:in `block in <main>'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/timeout.rb:93:in `block in timeout'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/timeout.rb:33:in `block in catch'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/timeout.rb:33:in `catch'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/timeout.rb:33:in `catch'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/timeout.rb:108:in `timeout'
/usr/local/Homebrew/Library/Homebrew/test.rb:34:in `<main>'
```

**Comment by PenelopeFudd** [comment]
```
$ brew upgrade file
...
Error: No available formula with the name "file"

$ brew upgrade file-formula
(success)

$ file -L $(which pup)
/usr/local/bin/pup: Mach-O 64-bit x86_64 executable, flags:<NOUNDEFS>
```
Thanks!

**Comment by Bo98** [comment]
I'm not able to reproduce the `pup` issue. Is there a crash report/backtrace that could help point to the issue?

**Comment by PenelopeFudd** [comment]
I wish there was!

I attempted to create one:
```
$ sudo bash
$ ulimit -c unlimited
$ pup

Segmentation fault: 11 (core dumped)
    ... wait 3 minutes ...
bash: cannot create temp file for here-document: No space left on device

$ ls -la /cores

drwxr-xr-x   3 root  wheel            96 Jul 22 17:26 ./
drwxr-xr-x  22 root  admin           704 Jun  4 20:59 ../
-r--------   1 root  wheel  586809073664 Jul 22 17:29 core.85940
```

That's a 546 GB core file!

What's the right way to get a crash report/backtrace?

I'm attaching the output of 'brew list --versions', if that helps.
[brew-list-versions.txt](https://github.com/Homebrew/homebrew-core/files/4963348/brew-list-versions.txt)

**Comment by Bo98** [comment]
Yikes. Maybe running it through `lldb` and viewing the backtrace might reveal something?

**Comment by dtrodrigues** [comment]
That's super strange - might be worth saving off the executable to look at later. What's the size and md5sum of it? Since you're on 10.15, it should be 4254864 and 89fd6d567fa923d79bc7ccc2800318a5. If it's not that (or even if it is), can you try a verbose reinstall via `brew reinstall -v pup` and share that output?

**Comment by PenelopeFudd** [comment]
It's 5537728 and 312ede72eef0ac91c67ea3cf5676fe80, pup 0.4.0.

INSTALL_RECEIPT.json
```json
{
  "homebrew_version": "2.4.8",
  "used_options": [],
  "unused_options": [],
  "built_as_bottle": false,
  "poured_from_bottle": false,
  "installed_as_dependency": false,
  "installed_on_request": true,
  "changed_files": null,
  "time": 1595357302,
  "source_modified_time": 1469249666,
  "HEAD": "13f0d4ad2b0773c01c5fdd5f8cba3e4f312c1c96",
  "stdlib": null,
  "compiler": "clang",
  "aliases": [],
  "runtime_dependencies": [],
  "source": {
    "path": "/Users/charleshowes/Library/Caches/Homebrew/Formula/pup.rb",
    "tap": null,
    "spec": "stable",
    "versions": {
      "stable": "0.4.0",
      "devel": "",
      "head": "",
      "version_scheme": 0
    }
  }
}
```

After `brew reinstall -v pup`, it started working and the size+checksum match what you've got.
The new INSTALL_RECEIPT.json file is different:
```
{
  "homebrew_version": "2.1.15",
  "used_options": [],
  "unused_options": [],
  "built_as_bottle": true,
  "poured_from_bottle": true,
  "installed_as_dependency": false,
  "installed_on_request": true,
  "changed_files": [
    "INSTALL_RECEIPT.json"
  ],
  "time": 1595528213,
  "source_modified_time": 1469249535,
  "HEAD": null,
  "stdlib": null,
  "compiler": "clang",
  "aliases": [],
  "runtime_dependencies": [],
  "source": {
    "path": "/usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/pup.rb",
    "tap": "homebrew/core",
    "spec": "stable",
    "versions": {
      "stable": "0.4.0",
      "devel": "",
      "head": "HEAD",
      "version_scheme": 0
    }
  }
}
```
Additionally, the /usr/local/Cellar/pup/0.4.0 directory has more files (LICENSE and README.md; not sure about .brew since I had run 'ls -l *', which doesn't show dot-files.).

All fixed, thanks!
