### ISSUE TITLE
OSError: dlopen(/usr/local/lib/libgdal.dylib, 6): Symbol not found: _GEOSArea

### ISSUE THREAD

**Issue by PaoloC68** [Homebrew/homebrew-core#5979]
After re-running the standard installation:

	$ brew install postgresql
	$ brew install postgis
	$ brew install gdal
	$ brew install libgeoip
	
I got this:

	(reports) MacBook-Pro:pmrw_reports paolo$ ./manage.py runserver
	Unhandled exception in thread started by <function wrapper at 0x1108e0c80>
	Traceback (most recent call last):
	  File "/Users/paolo/.virtualenvs/reports/lib/python2.7/site-packages/django/utils/autoreload.py", line 229, in wrapper
	    fn(*args, **kwargs)
	  File "/Users/paolo/.virtualenvs/reports/lib/python2.7/site-packages/django/core/management/commands/runserver.py", line 107, in inner_run
	    autoreload.raise_last_exception()
	  File "/Users/paolo/.virtualenvs/reports/lib/python2.7/site-packages/django/utils/autoreload.py", line 252, in raise_last_exception
	    six.reraise(*_exception)
	  File "/Users/paolo/.virtualenvs/reports/lib/python2.7/site-packages/django/utils/autoreload.py", line 229, in wrapper
	    fn(*args, **kwargs)
	  File "/Users/paolo/.virtualenvs/reports/lib/python2.7/site-packages/django/__init__.py", line 18, in setup
	    apps.populate(settings.INSTALLED_APPS)
	  File "/Users/paolo/.virtualenvs/reports/lib/python2.7/site-packages/django/apps/registry.py", line 108, in populate
	    app_config.import_models(all_models)
	  File "/Users/paolo/.virtualenvs/reports/lib/python2.7/site-packages/django/apps/config.py", line 198, in import_models
	    self.models_module = import_module(models_module_name)
	  File "/usr/local/Cellar/python/2.7.12_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/importlib/__init__.py", line 37, in import_module
	    __import__(name)
	  File "/Users/paolo/Documents/Projects/pmrw_reports/common/models.py", line 4, in <module>
	    class Status(models.Model):
	  File "/Users/paolo/.virtualenvs/reports/lib/python2.7/site-packages/django/db/models/base.py", line 139, in __new__
	    new_class.add_to_class('_meta', Options(meta, **kwargs))
	  File "/Users/paolo/.virtualenvs/reports/lib/python2.7/site-packages/django/db/models/base.py", line 324, in add_to_class
	    value.contribute_to_class(cls, name)
	  File "/Users/paolo/.virtualenvs/reports/lib/python2.7/site-packages/django/db/models/options.py", line 250, in contribute_to_class
	    self.db_table = truncate_name(self.db_table, connection.ops.max_name_length())
	  File "/Users/paolo/.virtualenvs/reports/lib/python2.7/site-packages/django/db/__init__.py", line 36, in __getattr__
	    return getattr(connections[DEFAULT_DB_ALIAS], item)
	  File "/Users/paolo/.virtualenvs/reports/lib/python2.7/site-packages/django/db/utils.py", line 241, in __getitem__
	    backend = load_backend(db['ENGINE'])
	  File "/Users/paolo/.virtualenvs/reports/lib/python2.7/site-packages/django/db/utils.py", line 112, in load_backend
	    return import_module('%s.base' % backend_name)
	  File "/usr/local/Cellar/python/2.7.12_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/importlib/__init__.py", line 37, in import_module
	    __import__(name)
	  File "/Users/paolo/.virtualenvs/reports/lib/python2.7/site-packages/django/contrib/gis/db/backends/postgis/base.py", line 8, in <module>
	    from .features import DatabaseFeatures
	  File "/Users/paolo/.virtualenvs/reports/lib/python2.7/site-packages/django/contrib/gis/db/backends/postgis/features.py", line 1, in <module>
	    from django.contrib.gis.db.backends.base.features import BaseSpatialFeatures
	  File "/Users/paolo/.virtualenvs/reports/lib/python2.7/site-packages/django/contrib/gis/db/backends/base/features.py", line 3, in <module>
	    from django.contrib.gis.db.models import aggregates
	  File "/Users/paolo/.virtualenvs/reports/lib/python2.7/site-packages/django/contrib/gis/db/models/__init__.py", line 7, in <module>
	    from django.contrib.gis.geos import HAS_GEOS
	  File "/Users/paolo/.virtualenvs/reports/lib/python2.7/site-packages/django/contrib/gis/geos/__init__.py", line 15, in <module>
	    from .geometry import GEOSGeometry, wkt_regex, hex_regex
	  File "/Users/paolo/.virtualenvs/reports/lib/python2.7/site-packages/django/contrib/gis/geos/geometry.py", line 10, in <module>
	    from django.contrib.gis.gdal.error import SRSException
	  File "/Users/paolo/.virtualenvs/reports/lib/python2.7/site-packages/django/contrib/gis/gdal/__init__.py", line 47, in <module>
	    from django.contrib.gis.gdal.driver import Driver  # NOQA
	  File "/Users/paolo/.virtualenvs/reports/lib/python2.7/site-packages/django/contrib/gis/gdal/driver.py", line 5, in <module>
	    from django.contrib.gis.gdal.prototypes import ds as vcapi, raster as rcapi
	  File "/Users/paolo/.virtualenvs/reports/lib/python2.7/site-packages/django/contrib/gis/gdal/prototypes/ds.py", line 9, in <module>
	    from django.contrib.gis.gdal.libgdal import lgdal
	  File "/Users/paolo/.virtualenvs/reports/lib/python2.7/site-packages/django/contrib/gis/gdal/libgdal.py", line 48, in <module>
	    lgdal = CDLL(lib_path)
	  File "/usr/local/Cellar/python/2.7.12_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/ctypes/__init__.py", line 362, in __init__
	    self._handle = _dlopen(self._name, mode)
	OSError: dlopen(/usr/local/lib/libgdal.dylib, 6): Symbol not found: _GEOSArea
	  Referenced from: /usr/local/opt/libspatialite/lib/libspatialite.7.dylib
	  Expected in: flat namespace
	 in /usr/local/opt/libspatialite/lib/libspatialite.7.dylib

Help please!

**Comment by MikeMcQuaid** [comment]
Sorry but you have not followed the requested steps on [the Troubleshooting page](https://github.com/Homebrew/brew/blob/master/docs/Troubleshooting.md#troubleshooting)

Please follow (all of) these steps and post the information here so we can help you with your problem.

Thanks!

**Comment by kpantic** [comment]
@PaoloC68 Hi had this same issue and was able to solve it by uninstalling GDAL from Homebrew and installing the GDAL Complete package from KyngChaos: http://www.kyngchaos.com/software/frameworks

**Comment by acdha** [comment]
If anyone else finds this, it appears to be a duplicate of #5161

**Comment by stephane** [comment]
gdal seems to be compiled against the wrong version of libproj, my ugly workaround is:
ln -s /usr/local/opt/proj/lib/libproj.12.dylib /usr/local/opt/proj/lib/libproj.9.dylib
