### ISSUE TITLE
sshuttle --HEAD build issues

### ISSUE THREAD

**Issue by rax-rstark** [Homebrew/homebrew-core#62489]
# Bug report

**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [X] ran `brew update` and can still reproduce the problem?
- [X] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [X] ran `brew gist-logs sshuttle` - https://gist.github.com/rax-rstark/eae027199248ee41e1401610b02254f9

- [ ] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

## What you were trying to do (and why)

I am installing sshuttle using the `--HEAD` option in order to take advantage of newly (re-added) functionality not available in the stable release, but the resulting installation does not function.

### Background

Sshuttle dropped support for python2 with the [1.0.0 release](https://sshuttle.readthedocs.io/en/stable/changes.html#id8). The current master branch of sshuttle has [re-implemented python2 support](https://github.com/sshuttle/sshuttle/pull/513) (much rejoice!) and added a new dependency of `psutil` in the process. The current sshuttle homebrew formula does not appear to pull in this dependency when building from HEAD. It builds fine, but sshuttle does not function as expected (see next section).

## What happened (include command output)

Execution of sshuttle errors out due to missing dependency:
<details>
  <summary>Command output</summary>
  <pre>

$ sshuttle --version
Traceback (most recent call last):
  File "/usr/local/bin/sshuttle", line 33, in <module>
    sys.exit(load_entry_point('sshuttle==0.1.dev3+gafad317', 'console_scripts', 'sshuttle')())
  File "/usr/local/bin/sshuttle", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/importlib/metadata.py", line 77, in load
    module = import_module(match.group('module'))
  File "/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/usr/local/Cellar/sshuttle/HEAD-afad317/libexec/lib/python3.8/site-packages/sshuttle/cmdline.py", line 5, in <module>
    import sshuttle.client as client
  File "/usr/local/Cellar/sshuttle/HEAD-afad317/libexec/lib/python3.8/site-packages/sshuttle/client.py", line 9, in <module>
    import psutil
ModuleNotFoundError: No module named 'psutil'

  </pre>
</details>

## What you expected to happen

I expect a functional sshuttle after successful brew installation

## Step-by-step reproduction instructions (by running `brew install` commands)

Build sshuttle from HEAD:
```
$ brew install sshuttle --HEAD
Updating Homebrew...
==> Auto-updated Homebrew!
Updated 2 taps (homebrew/cask-versions and homebrew/core).
==> Updated Formulae
Updated 9 formulae.
==> Updated Casks
slack-beta

==> Downloading https://files.pythonhosted.org/packages/85/3e/6c3abf78b2207f3565ebadd0b99d1945f4ff18abdc6879617a4f6d939e41/virtualenv-20.0.33.tar.gz
Already downloaded: /Users/rstark/Library/Caches/Homebrew/downloads/16fe908d73b872543d52a1b985e8f871cbd57be6ce67ec8c76839278e3259cd5--virtualenv-20.0.33.tar.gz
==> Downloading https://files.pythonhosted.org/packages/d7/d8/05696357e0311f5b5c316d7b95f46c669dd9c15aaeecbb48c7d0aeb88c40/appdirs-1.4.4.tar.gz
Already downloaded: /Users/rstark/Library/Caches/Homebrew/downloads/d46628d315f103ea527907020cf5f6c94365bbb549783f75a794526482afb672--appdirs-1.4.4.tar.gz
==> Downloading https://files.pythonhosted.org/packages/2f/83/1eba07997b8ba58d92b3e51445d5bf36f9fba9cb8166bcae99b9c3464841/distlib-0.3.1.zip
Already downloaded: /Users/rstark/Library/Caches/Homebrew/downloads/b25916e85753e80fccf86f2f1ba088b86d1a82c93cd36bdb72613c81cb830c55--distlib-0.3.1.zip
==> Downloading https://files.pythonhosted.org/packages/14/ec/6ee2168387ce0154632f856d5cc5592328e9cf93127c5c9aeca92c8c16cb/filelock-3.0.12.tar.gz
Already downloaded: /Users/rstark/Library/Caches/Homebrew/downloads/6132211d03cc3113b135a5b72510e3b6ea1df5bf527eb89d71c3f45085c252a7--filelock-3.0.12.tar.gz
==> Downloading https://files.pythonhosted.org/packages/6b/34/415834bfdafca3c5f451532e8a8d9ba89a21c9743a0c59fbd0205c7f9426/six-1.15.0.tar.gz
Already downloaded: /Users/rstark/Library/Caches/Homebrew/downloads/e99698a932bde9f5fb8ca552923ae339984f284e1c7764df95c12175f573c0d7--six-1.15.0.tar.gz
==> Cloning https://github.com/sshuttle/sshuttle.git
Updating /Users/rstark/Library/Caches/Homebrew/sshuttle--git
==> Checking out branch master
Already on 'master'
Your branch is up to date with 'origin/master'.
HEAD is now at afad317 Merge pull request #536 from ed-velez/add_psutil_to_setup
==> python3.8 -c import setuptools... --no-user-cfg install --prefix=/private/tmp/sshuttle--homebrew-virtualenv-20201007-24314-cm0dbq/target/vendor --install-scripts=/private/tmp/sshuttle--homebrew-virtualenv-20201007-24314-cm0dbq/target/vendor/bin --single-version-externally-managed --record=installed.txt
==> python3.8 -c import setuptools... --no-user-cfg install --prefix=/private/tmp/sshuttle--homebrew-virtualenv-20201007-24314-cm0dbq/target/vendor --install-scripts=/private/tmp/sshuttle--homebrew-virtualenv-20201007-24314-cm0dbq/target/vendor/bin --single-version-externally-managed --record=installed.txt
==> python3.8 -c import setuptools... --no-user-cfg install --prefix=/private/tmp/sshuttle--homebrew-virtualenv-20201007-24314-cm0dbq/target/vendor --install-scripts=/private/tmp/sshuttle--homebrew-virtualenv-20201007-24314-cm0dbq/target/vendor/bin --single-version-externally-managed --record=installed.txt
==> python3.8 -c import setuptools... --no-user-cfg install --prefix=/private/tmp/sshuttle--homebrew-virtualenv-20201007-24314-cm0dbq/target/vendor --install-scripts=/private/tmp/sshuttle--homebrew-virtualenv-20201007-24314-cm0dbq/target/vendor/bin --single-version-externally-managed --record=installed.txt
==> python3.8 -c import setuptools... --no-user-cfg install --prefix=/private/tmp/sshuttle--homebrew-virtualenv-20201007-24314-cm0dbq/target --install-scripts=/private/tmp/sshuttle--homebrew-virtualenv-20201007-24314-cm0dbq/target/bin --single-version-externally-managed --record=installed.txt
==> python3.8 -s /private/tmp/sshuttle--homebrew-virtualenv-20201007-24314-cm0dbq/target/bin/virtualenv -p python3.8 /usr/local/Cellar/sshuttle/HEAD-afad317/libexec
==> /usr/local/Cellar/sshuttle/HEAD-afad317/libexec/bin/pip install -v --no-deps --no-binary :all: --ignore-installed /private/tmp/sshuttle-20201007-24314-17q61eu
🍺  /usr/local/Cellar/sshuttle/HEAD-afad317: 987 files, 10.3MB, built in 17 seconds
```

### Install dependency post-install:
```
$ source /usr/local/Cellar/sshuttle/HEAD-afad317/libexec/bin/activate
$ /usr/local/Cellar/sshuttle/HEAD-afad317/libexec/bin/pip install psutil
Processing /Users/rstark/Library/Caches/pip/wheels/91/cf/b0/0c9998060b55ca80ea7a50a8639c3bdc6ba886eeff014bc9ac/psutil-5.7.2-cp38-cp38-macosx_10_15_x86_64.whl
Installing collected packages: psutil
Successfully installed psutil-5.7.2
$ deactivate
$ sshuttle --version
0.1.dev3+gafad317
```

### Explicitly add dependency to formula:
add to `/usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/sshuttle.rb`:
```
resource "psutil" do
    url "https://files.pythonhosted.org/packages/aa/3e/d18f2c04cf2b528e18515999b0c8e698c136db78f62df34eee89cee205f1/psutil-5.7.2.tar.gz"
    sha256 "90990af1c3c67195c44c9a889184f84f5b2320dce3ee3acbd054e3ba0b4a7beb"
  end
```
And then install:
```
$ brew install sshuttle --HEAD
Updating Homebrew...
==> Auto-updated Homebrew!
Updated 1 tap (homebrew/core).
==> Updated Formulae
Updated 7 formulae.

==> Downloading https://files.pythonhosted.org/packages/85/3e/6c3abf78b2207f3565ebadd0b99d1945f4ff18abdc6879617a4f6d939e41/virtualenv-20.0.33.tar.gz
Already downloaded: /Users/rstark/Library/Caches/Homebrew/downloads/16fe908d73b872543d52a1b985e8f871cbd57be6ce67ec8c76839278e3259cd5--virtualenv-20.0.33.tar.gz
==> Downloading https://files.pythonhosted.org/packages/d7/d8/05696357e0311f5b5c316d7b95f46c669dd9c15aaeecbb48c7d0aeb88c40/appdirs-1.4.4.tar.gz
Already downloaded: /Users/rstark/Library/Caches/Homebrew/downloads/d46628d315f103ea527907020cf5f6c94365bbb549783f75a794526482afb672--appdirs-1.4.4.tar.gz
==> Downloading https://files.pythonhosted.org/packages/2f/83/1eba07997b8ba58d92b3e51445d5bf36f9fba9cb8166bcae99b9c3464841/distlib-0.3.1.zip
Already downloaded: /Users/rstark/Library/Caches/Homebrew/downloads/b25916e85753e80fccf86f2f1ba088b86d1a82c93cd36bdb72613c81cb830c55--distlib-0.3.1.zip
==> Downloading https://files.pythonhosted.org/packages/14/ec/6ee2168387ce0154632f856d5cc5592328e9cf93127c5c9aeca92c8c16cb/filelock-3.0.12.tar.gz
Already downloaded: /Users/rstark/Library/Caches/Homebrew/downloads/6132211d03cc3113b135a5b72510e3b6ea1df5bf527eb89d71c3f45085c252a7--filelock-3.0.12.tar.gz
==> Downloading https://files.pythonhosted.org/packages/6b/34/415834bfdafca3c5f451532e8a8d9ba89a21c9743a0c59fbd0205c7f9426/six-1.15.0.tar.gz
Already downloaded: /Users/rstark/Library/Caches/Homebrew/downloads/e99698a932bde9f5fb8ca552923ae339984f284e1c7764df95c12175f573c0d7--six-1.15.0.tar.gz
==> Downloading https://files.pythonhosted.org/packages/aa/3e/d18f2c04cf2b528e18515999b0c8e698c136db78f62df34eee89cee205f1/psutil-5.7.2.tar.gz
######################################################################## 100.0%
==> Cloning https://github.com/sshuttle/sshuttle.git
Updating /Users/rstark/Library/Caches/Homebrew/sshuttle--git
==> Checking out branch master
Already on 'master'
Your branch is up to date with 'origin/master'.
HEAD is now at afad317 Merge pull request #536 from ed-velez/add_psutil_to_setup
==> python3.8 -c import setuptools... --no-user-cfg install --prefix=/private/tmp/sshuttle--homebrew-virtualenv-20201007-26779-ftpjrm/target/vendor --install-scripts=/private/tmp/sshuttle--homebrew-virtualenv-20201007-26779-ftpjrm/target/vendor/bin --single-version-externally-managed --record=installed.txt
==> python3.8 -c import setuptools... --no-user-cfg install --prefix=/private/tmp/sshuttle--homebrew-virtualenv-20201007-26779-ftpjrm/target/vendor --install-scripts=/private/tmp/sshuttle--homebrew-virtualenv-20201007-26779-ftpjrm/target/vendor/bin --single-version-externally-managed --record=installed.txt
==> python3.8 -c import setuptools... --no-user-cfg install --prefix=/private/tmp/sshuttle--homebrew-virtualenv-20201007-26779-ftpjrm/target/vendor --install-scripts=/private/tmp/sshuttle--homebrew-virtualenv-20201007-26779-ftpjrm/target/vendor/bin --single-version-externally-managed --record=installed.txt
==> python3.8 -c import setuptools... --no-user-cfg install --prefix=/private/tmp/sshuttle--homebrew-virtualenv-20201007-26779-ftpjrm/target/vendor --install-scripts=/private/tmp/sshuttle--homebrew-virtualenv-20201007-26779-ftpjrm/target/vendor/bin --single-version-externally-managed --record=installed.txt
==> python3.8 -c import setuptools... --no-user-cfg install --prefix=/private/tmp/sshuttle--homebrew-virtualenv-20201007-26779-ftpjrm/target --install-scripts=/private/tmp/sshuttle--homebrew-virtualenv-20201007-26779-ftpjrm/target/bin --single-version-externally-managed --record=installed.txt
==> python3.8 -s /private/tmp/sshuttle--homebrew-virtualenv-20201007-26779-ftpjrm/target/bin/virtualenv -p python3.8 /usr/local/Cellar/sshuttle/HEAD-afad317/libexec
==> /usr/local/Cellar/sshuttle/HEAD-afad317/libexec/bin/pip install -v --no-deps --no-binary :all: --ignore-installed /private/tmp/sshuttle--psutil-20201007-26779-1yc64tw/psutil-5.7.2
==> /usr/local/Cellar/sshuttle/HEAD-afad317/libexec/bin/pip install -v --no-deps --no-binary :all: --ignore-installed /private/tmp/sshuttle-20201007-26779-1wi5br2
🍺  /usr/local/Cellar/sshuttle/HEAD-afad317: 1,053 files, 11.8MB, built in 21 seconds
```

And lastly, test:
```
$ sshuttle --version
0.1.dev3+gafad317
$ sshuttle -r host 10.0.0.0/16
[local sudo] Password:
client: Connected.
```

**Comment by rax-rstark** [comment]
Adding the dependency of `psutil` to the `sshuttle.rb` formula should not alter current functionality of the stable release, and enable proper funcationaility for `--HEAD` installs.

**Comment by SMillerDev** [comment]
We don't support head builds so you'll have to fix it for yourself (as you did). I'm closing this.
