### ISSUE TITLE
Cannot upgrade macvim on 10.11.6, tar xzf fails

### ISSUE THREAD

**Issue by SteamedFish** [Homebrew/homebrew-core#6274]
I cannot upgrade macvim. The error said that `tar xzf /Users/SteamedFish/Library/Caches/Homebrew/macvim-8.0-113.tar.gz` failed.

tried `sudo chown -R $(whoami) $(brew --prefix)`, didn't work.

here is logs in detail:

```
SteamedFish@SteamedFishs-iMac:~$ brew update
Already up-to-date.
SteamedFish@SteamedFishs-iMac:~$ brew update
Already up-to-date.
```
```
SteamedFish@SteamedFishs-iMac:~$ brew doctor
Your system is ready to brew.
```
```
SteamedFish@SteamedFishs-iMac:~$ brew upgrade -vd macvim
/usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::FormulaLoader): loading /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/macvim.rb
==> Upgrading 1 outdated package, with result:
macvim 8.0-113
/usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::FormulaLoader): loading /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/cscope.rb
==> Upgrading macvim
rm /usr/local/bin/gview
rm /usr/local/bin/gvim
rm /usr/local/bin/gvimdiff
rm /usr/local/bin/gvimex
rm /usr/local/bin/mview
rm /usr/local/bin/mvim
rm /usr/local/bin/mvimdiff
rm /usr/local/bin/mvimex
rm /usr/local/bin/vi
rm /usr/local/bin/view
rm /usr/local/bin/vim
rm /usr/local/bin/vimdiff
rm /usr/local/bin/vimex
==> Using the sandbox
/usr/bin/sandbox-exec -f /tmp/homebrew20161026-1910-mpuks4.sb nice /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin/ruby -W0 -I /usr/local/Homebrew/Library/Homebrew -- /usr/local/Homebrew/Library/Homebrew/build.rb /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/macvim.rb --verbose --debug --with-override-system-vim
/usr/local/Homebrew/Library/Homebrew/build.rb (Formulary::FromPathLoader): loading /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/macvim.rb
/usr/local/Homebrew/Library/Homebrew/build.rb (Formulary::FormulaLoader): loading /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/cscope.rb
/usr/local/Homebrew/Library/Homebrew/build.rb (Formulary::FormulaLoader): loading /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/python.rb
==> Downloading https://github.com/macvim-dev/macvim/archive/snapshot-113.tar.gz
Already downloaded: /Users/SteamedFish/Library/Caches/Homebrew/macvim-8.0-113.tar.gz
==> Verifying macvim-8.0-113.tar.gz checksum
tar xzf /Users/SteamedFish/Library/Caches/Homebrew/macvim-8.0-113.tar.gz
macvim-snapshot-113/src/MacVim/Sparkle.framework/Headers: Can't create 'macvim-snapshot-113/src/MacVim/Sparkle.framework/Headers'
macvim-snapshot-113/src/MacVim/Sparkle.framework/Modules: Can't create 'macvim-snapshot-113/src/MacVim/Sparkle.framework/Modules'
macvim-snapshot-113/src/MacVim/Sparkle.framework/PrivateHeaders: Can't create 'macvim-snapshot-113/src/MacVim/Sparkle.framework/PrivateHeaders'
macvim-snapshot-113/src/MacVim/Sparkle.framework/Resources: Can't create 'macvim-snapshot-113/src/MacVim/Sparkle.framework/Resources'
macvim-snapshot-113/src/MacVim/Sparkle.framework/Sparkle: Can't create 'macvim-snapshot-113/src/MacVim/Sparkle.framework/Sparkle'
macvim-snapshot-113/src/MacVim/Sparkle.framework/Versions/A/Resources/fr_CA.lproj: Can't create 'macvim-snapshot-113/src/MacVim/Sparkle.framework/Versions/A/Resources/fr_CA.lproj'
macvim-snapshot-113/src/MacVim/Sparkle.framework/Versions/A/Resources/pt.lproj: Can't create 'macvim-snapshot-113/src/MacVim/Sparkle.framework/Versions/A/Resources/pt.lproj'
macvim-snapshot-113/src/MacVim/Sparkle.framework/Versions/Current: Can't create 'macvim-snapshot-113/src/MacVim/Sparkle.framework/Versions/Current'
tar: Error exit delayed from previous errors.
ln -s ../Cellar/macvim/8.0-112/bin/gview gview
ln -s ../Cellar/macvim/8.0-112/bin/gvim gvim
ln -s ../Cellar/macvim/8.0-112/bin/gvimdiff gvimdiff
ln -s ../Cellar/macvim/8.0-112/bin/gvimex gvimex
ln -s ../Cellar/macvim/8.0-112/bin/mview mview
ln -s ../Cellar/macvim/8.0-112/bin/mvim mvim
ln -s ../Cellar/macvim/8.0-112/bin/mvimdiff mvimdiff
ln -s ../Cellar/macvim/8.0-112/bin/mvimex mvimex
ln -s ../Cellar/macvim/8.0-112/bin/vi vi
ln -s ../Cellar/macvim/8.0-112/bin/view view
ln -s ../Cellar/macvim/8.0-112/bin/vim vim
ln -s ../Cellar/macvim/8.0-112/bin/vimdiff vimdiff
ln -s ../Cellar/macvim/8.0-112/bin/vimex vimex
Error: Failure while executing: tar xzf /Users/SteamedFish/Library/Caches/Homebrew/macvim-8.0-113.tar.gz
/usr/local/Homebrew/Library/Homebrew/utils.rb:276:in `safe_system'
/usr/local/Homebrew/Library/Homebrew/download_strategy.rb:79:in `safe_system'
/usr/local/Homebrew/Library/Homebrew/download_strategy.rb:247:in `block in stage'
/usr/local/Homebrew/Library/Homebrew/utils.rb:254:in `with_system_path'
/usr/local/Homebrew/Library/Homebrew/download_strategy.rb:243:in `stage'
/usr/local/Homebrew/Library/Homebrew/resource.rb:95:in `block in unpack'
/usr/local/Homebrew/Library/Homebrew/extend/fileutils.rb:14:in `block in mktemp'
/usr/local/Homebrew/Library/Homebrew/extend/fileutils.rb:74:in `block in run'
/usr/local/Homebrew/Library/Homebrew/extend/fileutils.rb:74:in `chdir'
/usr/local/Homebrew/Library/Homebrew/extend/fileutils.rb:74:in `run'
/usr/local/Homebrew/Library/Homebrew/extend/fileutils.rb:13:in `mktemp'
/usr/local/Homebrew/Library/Homebrew/resource.rb:94:in `unpack'
/usr/local/Homebrew/Library/Homebrew/resource.rb:86:in `stage'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1799:in `stage'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1075:in `brew'
/usr/local/Homebrew/Library/Homebrew/build.rb:112:in `install'
/usr/local/Homebrew/Library/Homebrew/build.rb:187:in `<main>'
SteamedFish@SteamedFishs-iMac:~$ brew gist-logs macvim
Error: No logs.
```
```
SteamedFish@SteamedFishs-iMac:~$ tar xzf /Users/SteamedFish/Library/Caches/Homebrew/macvim-8.0-113.tar.gz
SteamedFish@SteamedFishs-iMac:~$ echo $?
0
```
```
SteamedFish@SteamedFishs-iMac:~$ brew config
HOMEBREW_VERSION: 1.0.8-133-g84d1661
ORIGIN: https://github.com/Homebrew/brew
HEAD: 84d1661b9af04501473660eccf3f7941061744d3
Last commit: 14 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 169c240ade102775defd9cc4e82c4a68348b6f4b
Core tap last commit: 5 hours ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_REPOSITORY: /usr/local/Homebrew
HOMEBREW_CELLAR: /usr/local/Cellar
HOMEBREW_BOTTLE_DOMAIN: https://homebrew.bintray.com
CPU: quad-core 64-bit haswell
Homebrew Ruby: 2.0.0-p648
Clang: 8.0 build 800
Git: 2.8.4 => /Applications/Xcode.app/Contents/Developer/usr/bin/git
Perl: /usr/bin/perl
Python: /usr/local/bin/python => /usr/local/Cellar/python/2.7.12_2/Frameworks/Python.framework/Versions/2.7/bin/python2.7
Ruby: /usr/bin/ruby => /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin/ruby
Java: 1.8.0_101
macOS: 10.11.6-x86_64
Xcode: 8.0
CLT: 7.3.1.0.1.1461711523
X11: 2.7.10 => /opt/X11
```

**Comment by apjanke** [comment]
That's rather strange, especially since the `tar` succeeds from the command line. I can't reproduce on my 10.11.6 machine.

Interesting that only some stuff from `Sparkle.framework` seems to fail during the extract, and not other files. One possible related item: those failed items that failed to extract are symlinks, and not regular directories or files.

```
[~/tmp/macvim-snapshot-113/src/MacVim/Sparkle.framework]
$ ls -la
total 20
drwxr-xr-x  8 janke staff  272 Oct 22 02:57 .
drwxr-xr-x 65 janke staff 2210 Oct 22 02:57 ..
lrwxr-xr-x  1 janke staff   24 Oct 22 02:57 Headers -> Versions/Current/Headers
lrwxr-xr-x  1 janke staff   24 Oct 22 02:57 Modules -> Versions/Current/Modules
lrwxr-xr-x  1 janke staff   31 Oct 22 02:57 PrivateHeaders -> Versions/Current/PrivateHeaders
lrwxr-xr-x  1 janke staff   26 Oct 22 02:57 Resources -> Versions/Current/Resources
lrwxr-xr-x  1 janke staff   24 Oct 22 02:57 Sparkle -> Versions/Current/Sparkle
drwxr-xr-x  4 janke staff  136 Oct 22 02:57 Versions
...
[~/tmp/macvim-snapshot-113/src/MacVim/Sparkle.framework/Versions/A/Resources]
$ ls -la
total 32
drwxr-xr-x 38 janke staff  1292 Oct 22 02:57 .
drwxr-xr-x  7 janke staff   238 Oct 22 02:57 ..
drwxr-xr-x  3 janke staff   102 Oct 22 02:57 Autoupdate.app
-rw-r--r--  1 janke staff  1242 Oct 22 02:57 Info.plist
...
drwxr-xr-x  3 janke staff   102 Oct 22 02:57 fi.lproj
drwxr-xr-x  6 janke staff   204 Oct 22 02:57 fr.lproj
lrwxr-xr-x  1 janke staff     8 Oct 22 02:57 fr_CA.lproj -> fr.lproj
drwxr-xr-x  3 janke staff   102 Oct 22 02:57 he.lproj
...
drwxr-xr-x  6 janke staff   204 Oct 22 02:57 pl.lproj
lrwxr-xr-x  1 janke staff    11 Oct 22 02:57 pt.lproj -> pt_BR.lproj
drwxr-xr-x  6 janke staff   204 Oct 22 02:57 pt_BR.lproj
drwxr-xr-x  6 janke staff   204 Oct 22 02:57 pt_PT.lproj
```

Are you able to build other packages from source on this machine?

What's the output of `brew doctor`? Any chance this is running on a case-sensitive filesystem?

**Comment by apjanke** [comment]
Oh, sorry; I missed that you had included a clean `brew doctor` output in your original post.

**Comment by SteamedFish** [comment]
Thank you. I found that I cannot create any symlinks on `/tmp`, which is strange.
I can create symblinks on other directories. 
Deleting and recreating `/tmp` directory fixed the issue. 
Sorry for submit a issue that is not Homebrew's fault.

**Comment by apjanke** [comment]
Quite strange. Glad you got it figured out!
