### ISSUE TITLE
Problem installing matplotlib for jupyterlab venv in python 3.9

### ISSUE THREAD

**Issue by hjmallon** [Homebrew/homebrew-core#63544]
# Bug report

**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [x] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

<details>
  <summary>brew config, brew doctor</summary>
  <pre>
 % brew config
HOMEBREW_VERSION: 2.5.7-14-ge1b9887
ORIGIN: https://github.com/Homebrew/brew
HEAD: e1b988770a041f9e4458ea3d88cfa5e9be0eaaa8
Last commit: 3 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 5407e07937c416d252863ec24ca945dd02bbe863
Core tap last commit: 26 minutes ago
Core tap branch: master
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CASK_OPTS: []
HOMEBREW_DISPLAY: /private/tmp/com.apple.launchd.1Y87UpEiq6/org.macosforge.xquartz:0
HOMEBREW_MAKE_JOBS: 4
Homebrew Ruby: 2.6.3 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: quad-core 64-bit haswell
Clang: 12.0 build 1200
Git: 2.29.1 => /usr/local/bin/git
Curl: 7.64.1 => /usr/bin/curl
Java: 1.8.0_60
macOS: 10.15.7-x86_64
CLT: N/A
Xcode: 12.1
XQuartz: 2.7.11 => /opt/X11

% brew doctor
Your system is ready to brew.
  </pre>
</details>

## What you were trying to do (and why)

I want to use matplotlib inside jupyterlab. i.e. a jupyter notebook with `import matplotlib` etc. Because jupyterlab installs into a venv with brew we have to install the python libraries inside the same venv. I actually forgot how to do this after fixing it last time in 2.2.8, maybe could be added to `brew info jupyterlab`?

## What happened (include command output)

Matplotlib fails to build.

<details>
  <summary>Installing matplotlib in jupyterlab venv</summary>
  <pre>

% source /usr/local/Cellar/jupyterlab/2.2.9/libexec/bin/activate

(libexec) % pip install matplotlib
Collecting matplotlib
  Downloading matplotlib-3.3.2.tar.gz (37.9 MB)
     |████████████████████████████████| 37.9 MB 1.2 MB/s 
    ERROR: Command errored out with exit status 1:
     command: /usr/local/Cellar/jupyterlab/2.2.9/libexec/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/sl/f_v_6kld10x80gn94p_sgz_h0000gn/T/pip-install-bov_y60n/matplotlib/setup.py'"'"'; __file__='"'"'/private/var/folders/sl/f_v_6kld10x80gn94p_sgz_h0000gn/T/pip-install-bov_y60n/matplotlib/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /private/var/folders/sl/f_v_6kld10x80gn94p_sgz_h0000gn/T/pip-pip-egg-info-2bekvfa_
         cwd: /private/var/folders/sl/f_v_6kld10x80gn94p_sgz_h0000gn/T/pip-install-bov_y60n/matplotlib/
    Complete output (62 lines):
    
    Edit setup.cfg to change the build options; suppress output with --quiet.
    
    BUILDING MATPLOTLIB
      matplotlib: yes [3.3.2]
          python: yes [3.9.0 (default, Oct  6 2020, 04:17:54)  [Clang 12.0.0
                      (clang-1200.0.32.2)]]
        platform: yes [darwin]
     sample_data: yes [installing]
           tests: no  [skipping due to configuration]
          macosx: yes [installing]
    
    running egg_info
    creating /private/var/folders/sl/f_v_6kld10x80gn94p_sgz_h0000gn/T/pip-pip-egg-info-2bekvfa_/matplotlib.egg-info
    writing /private/var/folders/sl/f_v_6kld10x80gn94p_sgz_h0000gn/T/pip-pip-egg-info-2bekvfa_/matplotlib.egg-info/PKG-INFO
    writing dependency_links to /private/var/folders/sl/f_v_6kld10x80gn94p_sgz_h0000gn/T/pip-pip-egg-info-2bekvfa_/matplotlib.egg-info/dependency_links.txt
    writing namespace_packages to /private/var/folders/sl/f_v_6kld10x80gn94p_sgz_h0000gn/T/pip-pip-egg-info-2bekvfa_/matplotlib.egg-info/namespace_packages.txt
    writing requirements to /private/var/folders/sl/f_v_6kld10x80gn94p_sgz_h0000gn/T/pip-pip-egg-info-2bekvfa_/matplotlib.egg-info/requires.txt
    writing top-level names to /private/var/folders/sl/f_v_6kld10x80gn94p_sgz_h0000gn/T/pip-pip-egg-info-2bekvfa_/matplotlib.egg-info/top_level.txt
    writing manifest file '/private/var/folders/sl/f_v_6kld10x80gn94p_sgz_h0000gn/T/pip-pip-egg-info-2bekvfa_/matplotlib.egg-info/SOURCES.txt'
    init_dgelsd failed init
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/sl/f_v_6kld10x80gn94p_sgz_h0000gn/T/pip-install-bov_y60n/matplotlib/setup.py", line 242, in <module>
        setup(  # Finally, pass this all along to distutils to do the heavy lifting.
      File "/usr/local/Cellar/jupyterlab/2.2.9/libexec/lib/python3.9/site-packages/setuptools/__init__.py", line 153, in setup
        return distutils.core.setup(**attrs)
      File "/usr/local/Cellar/python@3.9/3.9.0/Frameworks/Python.framework/Versions/3.9/lib/python3.9/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/usr/local/Cellar/python@3.9/3.9.0/Frameworks/Python.framework/Versions/3.9/lib/python3.9/distutils/dist.py", line 966, in run_commands
        self.run_command(cmd)
      File "/usr/local/Cellar/python@3.9/3.9.0/Frameworks/Python.framework/Versions/3.9/lib/python3.9/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/usr/local/Cellar/jupyterlab/2.2.9/libexec/lib/python3.9/site-packages/setuptools/command/egg_info.py", line 293, in run
        self.find_sources()
      File "/usr/local/Cellar/jupyterlab/2.2.9/libexec/lib/python3.9/site-packages/setuptools/command/egg_info.py", line 300, in find_sources
        mm.run()
      File "/usr/local/Cellar/jupyterlab/2.2.9/libexec/lib/python3.9/site-packages/setuptools/command/egg_info.py", line 531, in run
        self.add_defaults()
      File "/usr/local/Cellar/jupyterlab/2.2.9/libexec/lib/python3.9/site-packages/setuptools/command/egg_info.py", line 567, in add_defaults
        sdist.add_defaults(self)
      File "/usr/local/Cellar/python@3.9/3.9.0/Frameworks/Python.framework/Versions/3.9/lib/python3.9/distutils/command/sdist.py", line 228, in add_defaults
        self._add_defaults_ext()
      File "/usr/local/Cellar/python@3.9/3.9.0/Frameworks/Python.framework/Versions/3.9/lib/python3.9/distutils/command/sdist.py", line 311, in _add_defaults_ext
        build_ext = self.get_finalized_command('build_ext')
      File "/usr/local/Cellar/python@3.9/3.9.0/Frameworks/Python.framework/Versions/3.9/lib/python3.9/distutils/cmd.py", line 299, in get_finalized_command
        cmd_obj.ensure_finalized()
      File "/usr/local/Cellar/python@3.9/3.9.0/Frameworks/Python.framework/Versions/3.9/lib/python3.9/distutils/cmd.py", line 107, in ensure_finalized
        self.finalize_options()
      File "/private/var/folders/sl/f_v_6kld10x80gn94p_sgz_h0000gn/T/pip-install-bov_y60n/matplotlib/setup.py", line 88, in finalize_options
        self.distribution.ext_modules[:] = [
      File "/private/var/folders/sl/f_v_6kld10x80gn94p_sgz_h0000gn/T/pip-install-bov_y60n/matplotlib/setup.py", line 91, in <listcomp>
        for ext in package.get_extensions()
      File "/private/var/folders/sl/f_v_6kld10x80gn94p_sgz_h0000gn/T/pip-install-bov_y60n/matplotlib/setupext.py", line 345, in get_extensions
        add_numpy_flags(ext)
      File "/private/var/folders/sl/f_v_6kld10x80gn94p_sgz_h0000gn/T/pip-install-bov_y60n/matplotlib/setupext.py", line 469, in add_numpy_flags
        import numpy as np
      File "/private/var/folders/sl/f_v_6kld10x80gn94p_sgz_h0000gn/T/pip-install-bov_y60n/matplotlib/.eggs/numpy-1.19.2-py3.9-macosx-10.15-x86_64.egg/numpy/__init__.py", line 286, in <module>
        raise RuntimeError(msg)
    RuntimeError: Polyfit sanity test emitted a warning, most likely due to using a buggy Accelerate backend. If you compiled yourself, see site.cfg.example for information. Otherwise report this to the vendor that provided NumPy.
    RankWarning: Polyfit may be poorly conditioned
    
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
WARNING: You are using pip version 20.2.3; however, version 20.2.4 is available.
You should consider upgrading via the '/usr/local/Cellar/jupyterlab/2.2.9/libexec/bin/python -m pip install --upgrade pip' command.

  </pre>
</details>

## What you expected to happen

When I did this with jupyterlab 2.2.8 and python@3.8 it worked.

Next I tried doing the same on jupyterlab installed with `brew install --build-from-source jupyterlab`, this returns the same error.

Next I tried editing the jupyterlab formula and adding `depends_on "numpy"`. When I do that and build from source then I am able to install matplotlib! Hooray!

## Step-by-step reproduction instructions (by running `brew install` commands)

```
brew install jupyterlab
source /usr/local/Cellar/jupyterlab/2.2.9/libexec/bin/activate
pip install matplotlib
```

**Comment by fxcoudert** [comment]
Try to install `openblas`, and see if installing `matplotlib` after that can link to it (instead of the buggy Accelerate framework)

**Comment by fxcoudert** [comment]
If openblas is available on your system, installing numpy inside the venv should detect it. If not, it's possibly an issue with numpy (they should not link against Accelerate at all).

**Comment by Najibu-noAgent** [comment]
Installing python from the site worked for me. https://www.python.org/downloads/release/python-390/

**Comment by fxcoudert** [comment]
Closing as an upstream issue: numpy shouldn't link against Accelerate (and it appears it won't in future versions)
