### ISSUE TITLE
Node15 on HighSierra: post-install step did not complete successfully

### ISSUE THREAD

**Issue by Zabrane** [Homebrew/homebrew-core#64304]
I'm unable to complete `Node15` install on `HighSierra` as you can see:

```
$ brew doctor 
Your system is ready to brew.

$ brew install node                                                                                                                                                                  
Updating Homebrew...
==> Downloading https://homebrew.bintray.com/bottles/node-15.1.0.high_sierra.bottle.tar.gz
Already downloaded: /Users/micka/Library/Caches/Homebrew/downloads/68771f0bcb7b4c8e0c64ed5784e08138141a35323dbe879416e4d3ba7b819152--node-15.1.0.high_sierra.bottle.tar.gz
==> Pouring node-15.1.0.high_sierra.bottle.tar.gz
Warning: The post-install step did not complete successfully
You can try again using `brew postinstall node`
==> Caveats
Bash completion has been installed to:
  /usr/local/etc/bash_completion.d
==> Summary
🍺  /usr/local/Cellar/node/15.1.0: 3,262 files, 55.2MB

$ brew -v postinstall node
==> Postinstalling node                                                                                                                                                       
/usr/bin/sandbox-exec -f /private/tmp/homebrew20201107-30663-xm01z2.sb nice ruby -W0 -I $LOAD_PATH -- /usr/local/Homebrew/Library/Homebrew/postinstall.rb /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/node.rb
Warning: The post-install step did not complete successfully
You can try again using `brew postinstall node`

$ brew -v postinstall node                                                                                                                                                           
==> Postinstalling node
/usr/bin/sandbox-exec -f /private/tmp/homebrew20201107-43160-1wmyiht.sb nice ruby -W0 -I $LOAD_PATH -- /usr/local/Homebrew/Library/Homebrew/postinstall.rb /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/node.rb
/Warning: The post-install step did not complete successfully
You can try again using `brew postinstall node`
```

The command `brew -v postinstall node ` didn't help.

**Comment by gromgit** [comment]
What does `brew postinstall --debug node` output?

**Comment by Zabrane** [comment]
Here you are:

```
$ brew postinstall --debug node
/usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::FormulaLoader): loading /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/node.rb
==> Postinstalling node
Warning: The post-install step did not complete successfully
You can try again using `brew postinstall node`
==> An exception occurred within a child process:
  Errno::EACCES: Permission denied @ rb_sysopen - /usr/local/lib/node_modules/npm/.npmignore

/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3_2/lib/ruby/2.6.0/fileutils.rb:1386:in `initialize'
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3_2/lib/ruby/2.6.0/fileutils.rb:1386:in `open'
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3_2/lib/ruby/2.6.0/fileutils.rb:1386:in `block in copy_file'
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3_2/lib/ruby/2.6.0/fileutils.rb:1385:in `open'
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3_2/lib/ruby/2.6.0/fileutils.rb:1385:in `copy_file'
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3_2/lib/ruby/2.6.0/fileutils.rb:1353:in `copy'
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3_2/lib/ruby/2.6.0/fileutils.rb:478:in `block in copy_entry'
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3_2/lib/ruby/2.6.0/fileutils.rb:1484:in `wrap_traverse'
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3_2/lib/ruby/2.6.0/fileutils.rb:1487:in `block in wrap_traverse'
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3_2/lib/ruby/2.6.0/fileutils.rb:1486:in `each'
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3_2/lib/ruby/2.6.0/fileutils.rb:1486:in `wrap_traverse'
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3_2/lib/ruby/2.6.0/fileutils.rb:475:in `copy_entry'
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3_2/lib/ruby/2.6.0/fileutils.rb:453:in `block in cp_r'
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3_2/lib/ruby/2.6.0/fileutils.rb:1557:in `block in fu_each_src_dest'
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3_2/lib/ruby/2.6.0/fileutils.rb:1571:in `fu_each_src_dest0'
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3_2/lib/ruby/2.6.0/fileutils.rb:1555:in `fu_each_src_dest'
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3_2/lib/ruby/2.6.0/fileutils.rb:452:in `cp_r'
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/node.rb:70:in `post_install'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1041:in `block (2 levels) in run_post_install'
/usr/local/Homebrew/Library/Homebrew/formula.rb:901:in `with_logging'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1040:in `block in run_post_install'
/usr/local/Homebrew/Library/Homebrew/utils.rb:497:in `with_env'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1030:in `run_post_install'
/usr/local/Homebrew/Library/Homebrew/postinstall.rb:22:in `<main>'
```
