### ISSUE TITLE
Poetry fails to install numpy on big sur

### ISSUE THREAD

**Issue by nacaclanga** [Homebrew/homebrew-core#66164]
# Bug report

**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [x] ran `brew update` and can still reproduce the problem?
- [ ] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [ ] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [ ] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

## What you were trying to do (and why)

Using poetry to manage dependencies and install plattform dependend packages like numpy.

## What happened (include command output)

<details>
  <summary>Command output</summary>
  <pre>
%poetry add numpy
  Using version ^1.19.4 for numpy

Updating dependencies
Resolving dependencies... (0.9s)

Writing lock file

Package operations: 9 installs, 0 updates, 0 removals

  • Installing pyparsing (2.4.7)
  • Installing attrs (20.3.0)
  • Installing more-itertools (8.6.0)
  • Installing packaging (20.7)
  • Installing pluggy (0.13.1)
  • Installing py (1.9.0)
  • Installing wcwidth (0.2.5)
  • Installing numpy (1.19.4): Failed

  EnvCommandError

  Command ['/Users/sannaj/Library/Caches/pypoetry/virtualenvs/bigsurtest-oBpdMjZr-py3.9/bin/pip', 'install', '--no-deps', 'file:///Users/sannaj/Library/Caches/pypoetry/artifacts/73/82/44/220b707252fd91e000dd4b03beaa62dad1e7ef8d32db919dd96ad6f104/numpy-1.19.4.zip'] errored with the following return code 1, and output: 
  Processing /Users/sannaj/Library/Caches/pypoetry/artifacts/73/82/44/220b707252fd91e000dd4b03beaa62dad1e7ef8d32db919dd96ad6f104/numpy-1.19.4.zip
    Installing build dependencies: started
    Installing build dependencies: finished with status 'done'
    Getting requirements to build wheel: started
    Getting requirements to build wheel: finished with status 'done'
      Preparing wheel metadata: started
      Preparing wheel metadata: finished with status 'error'
      ERROR: Command errored out with exit status 1:
       command: /Users/sannaj/Library/Caches/pypoetry/virtualenvs/bigsurtest-oBpdMjZr-py3.9/bin/python /Users/sannaj/Library/Caches/pypoetry/virtualenvs/bigsurtest-oBpdMjZr-py3.9/lib/python3.9/site-packages/pip/_vendor/pep517/_in_process.py prepare_metadata_for_build_wheel /var/folders/kf/25msxpx52j98k6qm2pgq11rh0000gn/T/tmpdya657f2
           cwd: /private/var/folders/kf/25msxpx52j98k6qm2pgq11rh0000gn/T/pip-req-build-zkhrmwam
      Complete output (209 lines):
      Running from numpy source directory.
      setup.py:480: UserWarning: Unrecognized setuptools command, proceeding with generating Cython sources and expanding templates
        run_build = parse_setuppy_commands()
      Processing numpy/random/_bounded_integers.pxd.in
      Processing numpy/random/_philox.pyx
      Processing numpy/random/_bounded_integers.pyx.in
      Processing numpy/random/_sfc64.pyx
      Processing numpy/random/_mt19937.pyx
      Processing numpy/random/bit_generator.pyx
      Processing numpy/random/mtrand.pyx
      Processing numpy/random/_generator.pyx
      Processing numpy/random/_pcg64.pyx
      Processing numpy/random/_common.pyx
      Cythonizing sources
      blas_opt_info:
      blas_mkl_info:
      customize UnixCCompiler
        libraries mkl_rt not found in ['/Users/sannaj/Library/Caches/pypoetry/virtualenvs/bigsurtest-oBpdMjZr-py3.9/lib', '/usr/local/lib', '/usr/lib']
        NOT AVAILABLE
      
      blis_info:
        libraries blis not found in ['/Users/sannaj/Library/Caches/pypoetry/virtualenvs/bigsurtest-oBpdMjZr-py3.9/lib', '/usr/local/lib', '/usr/lib']
        NOT AVAILABLE
      
      openblas_info:
        libraries openblas not found in ['/Users/sannaj/Library/Caches/pypoetry/virtualenvs/bigsurtest-oBpdMjZr-py3.9/lib', '/usr/local/lib', '/usr/lib']
        NOT AVAILABLE
      
      atlas_3_10_blas_threads_info:
      Setting PTATLAS=ATLAS
        libraries tatlas not found in ['/Users/sannaj/Library/Caches/pypoetry/virtualenvs/bigsurtest-oBpdMjZr-py3.9/lib', '/usr/local/lib', '/usr/lib']
        NOT AVAILABLE
      
      atlas_3_10_blas_info:
        libraries satlas not found in ['/Users/sannaj/Library/Caches/pypoetry/virtualenvs/bigsurtest-oBpdMjZr-py3.9/lib', '/usr/local/lib', '/usr/lib']
        NOT AVAILABLE
      
      atlas_blas_threads_info:
      Setting PTATLAS=ATLAS
        libraries ptf77blas,ptcblas,atlas not found in ['/Users/sannaj/Library/Caches/pypoetry/virtualenvs/bigsurtest-oBpdMjZr-py3.9/lib', '/usr/local/lib', '/usr/lib']
        NOT AVAILABLE
      
      atlas_blas_info:
        libraries f77blas,cblas,atlas not found in ['/Users/sannaj/Library/Caches/pypoetry/virtualenvs/bigsurtest-oBpdMjZr-py3.9/lib', '/usr/local/lib', '/usr/lib']
        NOT AVAILABLE
      
      accelerate_info:
        libraries accelerate not found in ['/Users/sannaj/Library/Caches/pypoetry/virtualenvs/bigsurtest-oBpdMjZr-py3.9/lib', '/usr/local/lib', '/usr/lib']
      Library accelerate was not found. Ignoring
        libraries veclib not found in ['/Users/sannaj/Library/Caches/pypoetry/virtualenvs/bigsurtest-oBpdMjZr-py3.9/lib', '/usr/local/lib', '/usr/lib']
      Library veclib was not found. Ignoring
        FOUND:
          extra_compile_args = ['-msse3', '-I/System/Library/Frameworks/vecLib.framework/Headers']
          extra_link_args = ['-Wl,-framework', '-Wl,Accelerate']
          define_macros = [('NO_ATLAS_INFO', 3), ('HAVE_CBLAS', None)]
      
        FOUND:
          extra_compile_args = ['-msse3', '-I/System/Library/Frameworks/vecLib.framework/Headers']
          extra_link_args = ['-Wl,-framework', '-Wl,Accelerate']
          define_macros = [('NO_ATLAS_INFO', 3), ('HAVE_CBLAS', None)]
      
      non-existing path in 'numpy/distutils': 'site.cfg'
      lapack_opt_info:
      lapack_mkl_info:
        libraries mkl_rt not found in ['/Users/sannaj/Library/Caches/pypoetry/virtualenvs/bigsurtest-oBpdMjZr-py3.9/lib', '/usr/local/lib', '/usr/lib']
        NOT AVAILABLE
      
      openblas_lapack_info:
        libraries openblas not found in ['/Users/sannaj/Library/Caches/pypoetry/virtualenvs/bigsurtest-oBpdMjZr-py3.9/lib', '/usr/local/lib', '/usr/lib']
        NOT AVAILABLE
      
      openblas_clapack_info:
        libraries openblas,lapack not found in ['/Users/sannaj/Library/Caches/pypoetry/virtualenvs/bigsurtest-oBpdMjZr-py3.9/lib', '/usr/local/lib', '/usr/lib']
        NOT AVAILABLE
      
      flame_info:
        libraries flame not found in ['/Users/sannaj/Library/Caches/pypoetry/virtualenvs/bigsurtest-oBpdMjZr-py3.9/lib', '/usr/local/lib', '/usr/lib']
        NOT AVAILABLE
      
      atlas_3_10_threads_info:
      Setting PTATLAS=ATLAS
        libraries lapack_atlas not found in /Users/sannaj/Library/Caches/pypoetry/virtualenvs/bigsurtest-oBpdMjZr-py3.9/lib
        libraries tatlas,tatlas not found in /Users/sannaj/Library/Caches/pypoetry/virtualenvs/bigsurtest-oBpdMjZr-py3.9/lib
        libraries lapack_atlas not found in /usr/local/lib
        libraries tatlas,tatlas not found in /usr/local/lib
        libraries lapack_atlas not found in /usr/lib
        libraries tatlas,tatlas not found in /usr/lib
      <class 'numpy.distutils.system_info.atlas_3_10_threads_info'>
        NOT AVAILABLE
      
      atlas_3_10_info:
        libraries lapack_atlas not found in /Users/sannaj/Library/Caches/pypoetry/virtualenvs/bigsurtest-oBpdMjZr-py3.9/lib
        libraries satlas,satlas not found in /Users/sannaj/Library/Caches/pypoetry/virtualenvs/bigsurtest-oBpdMjZr-py3.9/lib
        libraries lapack_atlas not found in /usr/local/lib
        libraries satlas,satlas not found in /usr/local/lib
        libraries lapack_atlas not found in /usr/lib
        libraries satlas,satlas not found in /usr/lib
      <class 'numpy.distutils.system_info.atlas_3_10_info'>
        NOT AVAILABLE
      
      atlas_threads_info:
      Setting PTATLAS=ATLAS
        libraries lapack_atlas not found in /Users/sannaj/Library/Caches/pypoetry/virtualenvs/bigsurtest-oBpdMjZr-py3.9/lib
        libraries ptf77blas,ptcblas,atlas not found in /Users/sannaj/Library/Caches/pypoetry/virtualenvs/bigsurtest-oBpdMjZr-py3.9/lib
        libraries lapack_atlas not found in /usr/local/lib
        libraries ptf77blas,ptcblas,atlas not found in /usr/local/lib
        libraries lapack_atlas not found in /usr/lib
        libraries ptf77blas,ptcblas,atlas not found in /usr/lib
      <class 'numpy.distutils.system_info.atlas_threads_info'>
        NOT AVAILABLE
      
      atlas_info:
        libraries lapack_atlas not found in /Users/sannaj/Library/Caches/pypoetry/virtualenvs/bigsurtest-oBpdMjZr-py3.9/lib
        libraries f77blas,cblas,atlas not found in /Users/sannaj/Library/Caches/pypoetry/virtualenvs/bigsurtest-oBpdMjZr-py3.9/lib
        libraries lapack_atlas not found in /usr/local/lib
        libraries f77blas,cblas,atlas not found in /usr/local/lib
        libraries lapack_atlas not found in /usr/lib
        libraries f77blas,cblas,atlas not found in /usr/lib
      <class 'numpy.distutils.system_info.atlas_info'>
        NOT AVAILABLE
      
        FOUND:
          extra_compile_args = ['-msse3', '-I/System/Library/Frameworks/vecLib.framework/Headers']
          extra_link_args = ['-Wl,-framework', '-Wl,Accelerate']
          define_macros = [('NO_ATLAS_INFO', 3), ('HAVE_CBLAS', None)]
      
      /usr/local/Cellar/python@3.9/3.9.0_4/Frameworks/Python.framework/Versions/3.9/lib/python3.9/distutils/dist.py:274: UserWarning: Unknown distribution option: 'define_macros'
        warnings.warn(msg)
      running dist_info
      running build_src
      build_src
      building py_modules sources
      creating build
      creating build/src.macosx-11-x86_64-3.9
      creating build/src.macosx-11-x86_64-3.9/numpy
      creating build/src.macosx-11-x86_64-3.9/numpy/distutils
      building library "npymath" sources
      Traceback (most recent call last):
        File "/Users/sannaj/Library/Caches/pypoetry/virtualenvs/bigsurtest-oBpdMjZr-py3.9/lib/python3.9/site-packages/pip/_vendor/pep517/_in_process.py", line 280, in <module>
          main()
        File "/Users/sannaj/Library/Caches/pypoetry/virtualenvs/bigsurtest-oBpdMjZr-py3.9/lib/python3.9/site-packages/pip/_vendor/pep517/_in_process.py", line 263, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "/Users/sannaj/Library/Caches/pypoetry/virtualenvs/bigsurtest-oBpdMjZr-py3.9/lib/python3.9/site-packages/pip/_vendor/pep517/_in_process.py", line 133, in prepare_metadata_for_build_wheel
          return hook(metadata_directory, config_settings)
        File "/private/var/folders/kf/25msxpx52j98k6qm2pgq11rh0000gn/T/pip-build-env-xia9l98z/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 157, in prepare_metadata_for_build_wheel
          self.run_setup()
        File "/private/var/folders/kf/25msxpx52j98k6qm2pgq11rh0000gn/T/pip-build-env-xia9l98z/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 248, in run_setup
          super(_BuildMetaLegacyBackend,
        File "/private/var/folders/kf/25msxpx52j98k6qm2pgq11rh0000gn/T/pip-build-env-xia9l98z/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 142, in run_setup
          exec(compile(code, __file__, 'exec'), locals())
        File "setup.py", line 508, in <module>
          setup_package()
        File "setup.py", line 500, in setup_package
          setup(**metadata)
        File "/private/var/folders/kf/25msxpx52j98k6qm2pgq11rh0000gn/T/pip-req-build-zkhrmwam/numpy/distutils/core.py", line 169, in setup
          return old_setup(**new_attr)
        File "/private/var/folders/kf/25msxpx52j98k6qm2pgq11rh0000gn/T/pip-build-env-xia9l98z/overlay/lib/python3.9/site-packages/setuptools/__init__.py", line 165, in setup
          return distutils.core.setup(**attrs)
        File "/usr/local/Cellar/python@3.9/3.9.0_4/Frameworks/Python.framework/Versions/3.9/lib/python3.9/distutils/core.py", line 148, in setup
          dist.run_commands()
        File "/usr/local/Cellar/python@3.9/3.9.0_4/Frameworks/Python.framework/Versions/3.9/lib/python3.9/distutils/dist.py", line 966, in run_commands
          self.run_command(cmd)
        File "/usr/local/Cellar/python@3.9/3.9.0_4/Frameworks/Python.framework/Versions/3.9/lib/python3.9/distutils/dist.py", line 985, in run_command
          cmd_obj.run()
        File "/private/var/folders/kf/25msxpx52j98k6qm2pgq11rh0000gn/T/pip-build-env-xia9l98z/overlay/lib/python3.9/site-packages/setuptools/command/dist_info.py", line 31, in run
          egg_info.run()
        File "/private/var/folders/kf/25msxpx52j98k6qm2pgq11rh0000gn/T/pip-req-build-zkhrmwam/numpy/distutils/command/egg_info.py", line 24, in run
          self.run_command("build_src")
        File "/usr/local/Cellar/python@3.9/3.9.0_4/Frameworks/Python.framework/Versions/3.9/lib/python3.9/distutils/cmd.py", line 313, in run_command
          self.distribution.run_command(command)
        File "/usr/local/Cellar/python@3.9/3.9.0_4/Frameworks/Python.framework/Versions/3.9/lib/python3.9/distutils/dist.py", line 985, in run_command
          cmd_obj.run()
        File "/private/var/folders/kf/25msxpx52j98k6qm2pgq11rh0000gn/T/pip-req-build-zkhrmwam/numpy/distutils/command/build_src.py", line 144, in run
          self.build_sources()
        File "/private/var/folders/kf/25msxpx52j98k6qm2pgq11rh0000gn/T/pip-req-build-zkhrmwam/numpy/distutils/command/build_src.py", line 155, in build_sources
          self.build_library_sources(*libname_info)
        File "/private/var/folders/kf/25msxpx52j98k6qm2pgq11rh0000gn/T/pip-req-build-zkhrmwam/numpy/distutils/command/build_src.py", line 288, in build_library_sources
          sources = self.generate_sources(sources, (lib_name, build_info))
        File "/private/var/folders/kf/25msxpx52j98k6qm2pgq11rh0000gn/T/pip-req-build-zkhrmwam/numpy/distutils/command/build_src.py", line 378, in generate_sources
          source = func(extension, build_dir)
        File "numpy/core/setup.py", line 658, in get_mathlib_info
          st = config_cmd.try_link('int main(void) { return 0;}')
        File "/usr/local/Cellar/python@3.9/3.9.0_4/Frameworks/Python.framework/Versions/3.9/lib/python3.9/distutils/command/config.py", line 241, in try_link
          self._check_compiler()
        File "/private/var/folders/kf/25msxpx52j98k6qm2pgq11rh0000gn/T/pip-req-build-zkhrmwam/numpy/distutils/command/config.py", line 80, in _check_compiler
          self.fcompiler = new_fcompiler(compiler=self.fcompiler,
        File "/private/var/folders/kf/25msxpx52j98k6qm2pgq11rh0000gn/T/pip-req-build-zkhrmwam/numpy/distutils/fcompiler/__init__.py", line 880, in new_fcompiler
          compiler = get_default_fcompiler(plat, requiref90=requiref90,
        File "/private/var/folders/kf/25msxpx52j98k6qm2pgq11rh0000gn/T/pip-req-build-zkhrmwam/numpy/distutils/fcompiler/__init__.py", line 851, in get_default_fcompiler
          compiler_type =  _find_existing_fcompiler(matching_compiler_types,
        File "/private/var/folders/kf/25msxpx52j98k6qm2pgq11rh0000gn/T/pip-req-build-zkhrmwam/numpy/distutils/fcompiler/__init__.py", line 802, in _find_existing_fcompiler
          c.customize(dist)
        File "/private/var/folders/kf/25msxpx52j98k6qm2pgq11rh0000gn/T/pip-req-build-zkhrmwam/numpy/distutils/fcompiler/__init__.py", line 526, in customize
          linker_so_flags = self.flag_vars.linker_so
        File "/private/var/folders/kf/25msxpx52j98k6qm2pgq11rh0000gn/T/pip-req-build-zkhrmwam/numpy/distutils/fcompiler/environment.py", line 37, in __getattr__
          return self._get_var(name, conf_desc)
        File "/private/var/folders/kf/25msxpx52j98k6qm2pgq11rh0000gn/T/pip-req-build-zkhrmwam/numpy/distutils/fcompiler/environment.py", line 53, in _get_var
          var = self._hook_handler(name, hook)
        File "/private/var/folders/kf/25msxpx52j98k6qm2pgq11rh0000gn/T/pip-req-build-zkhrmwam/numpy/distutils/fcompiler/__init__.py", line 705, in _environment_hook
          return hook()
        File "/private/var/folders/kf/25msxpx52j98k6qm2pgq11rh0000gn/T/pip-req-build-zkhrmwam/numpy/distutils/fcompiler/gnu.py", line 346, in get_flags_linker_so
          flags = GnuFCompiler.get_flags_linker_so(self)
        File "/private/var/folders/kf/25msxpx52j98k6qm2pgq11rh0000gn/T/pip-req-build-zkhrmwam/numpy/distutils/fcompiler/gnu.py", line 136, in get_flags_linker_so
          os.environ['MACOSX_DEPLOYMENT_TARGET'] = target
        File "/usr/local/Cellar/python@3.9/3.9.0_4/Frameworks/Python.framework/Versions/3.9/lib/python3.9/os.py", line 684, in __setitem__
          value = self.encodevalue(value)
        File "/usr/local/Cellar/python@3.9/3.9.0_4/Frameworks/Python.framework/Versions/3.9/lib/python3.9/os.py", line 756, in encode
          raise TypeError("str expected, not %s" % type(value).__name__)
      TypeError: str expected, not int
      ----------------------------------------
  ERROR: Command errored out with exit status 1: /Users/sannaj/Library/Caches/pypoetry/virtualenvs/bigsurtest-oBpdMjZr-py3.9/bin/python /Users/sannaj/Library/Caches/pypoetry/virtualenvs/bigsurtest-oBpdMjZr-py3.9/lib/python3.9/site-packages/pip/_vendor/pep517/_in_process.py prepare_metadata_for_build_wheel /var/folders/kf/25msxpx52j98k6qm2pgq11rh0000gn/T/tmpdya657f2 Check the logs for full command output.
  WARNING: You are using pip version 20.2.4; however, version 20.3.1 is available.
  You should consider upgrading via the '/Users/sannaj/Library/Caches/pypoetry/virtualenvs/bigsurtest-oBpdMjZr-py3.9/bin/python -m pip install --upgrade pip' command.
  

  at /usr/local/Cellar/poetry/1.1.4/libexec/lib/python3.9/site-packages/poetry/utils/env.py:1074 in _run
      1070│                 output = subprocess.check_output(
      1071│                     cmd, stderr=subprocess.STDOUT, **kwargs
      1072│                 )
      1073│         except CalledProcessError as e:
    → 1074│             raise EnvCommandError(e, input=input_)
      1075│ 
      1076│         return decode(output)
      1077│ 
      1078│     def execute(self, bin, *args, **kwargs):

  • Installing pytest (5.4.3)

Failed to add packages, reverting the pyproject.toml file to its original content.

  </pre>
</details>

## What you expected to happen

Successfull installation

## Step-by-step reproduction instructions (by running `brew install` commands)

`brew install poetry`
`poetry new bigsurtest`
`cd bigsurtest`
`poetry add numpy`

I suspect that this is due to homebrew using an older version of "packaging" for poetry, that fails to use macOS 10.X wheels on Big Sur. See e.g. https://github.com/pypa/pip/issues/9138 https://github.com/pypa/packaging/pull/319. The poetry formula installes pinned versions different from https://github.com/python-poetry/poetry/blob/master/poetry.lock so this likely issue.

**Comment by fxcoudert** [comment]
This is an issue in numpy: https://github.com/numpy/numpy/pull/17906
