### ISSUE TITLE
brew install ansible --HEAD fails on Big Sur (unexpected MACOSX_DEPLOYMENT_TARGET)

### ISSUE THREAD

**Issue by rgaufman** [Homebrew/homebrew-core#66848]
# Bug report

**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [X] ran `brew update` and can still reproduce the problem?
- [X] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [X] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [X] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

I tried to run brew gist-logs ansible to get a link, but I got:
```
iMac.local ➜  brew gist-logs ansible
Error: Calling `brew gist-logs` with a password is disabled! Use HOMEBREW_GITHUB_API_TOKEN instead.
```

Here is brew config
```
iMac.local ➜  brew config
HOMEBREW_VERSION: 2.6.1
ORIGIN: https://github.com/Homebrew/brew
HEAD: 2c77a540b522c2eee74af0745851167412adb83b
Last commit: 3 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 0445b7fecf80bbacaa4841de8eda7b8058902640
Core tap last commit: 26 minutes ago
Core tap branch: master
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CASK_OPTS: []
HOMEBREW_MAKE_JOBS: 12
Homebrew Ruby: 2.6.3 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: dodeca-core 64-bit kabylake
Clang: 12.0 build 1200
Git: 2.24.3 => /Applications/Xcode.app/Contents/Developer/usr/bin/git
Curl: 7.64.1 => /usr/bin/curl
Java: 14.0.2, 1.8.261.12, 1.8.0_275
macOS: 11.0.1-x86_64
CLT: 12.0.32.27
Xcode: 12.2
```

Here is brew doctor:
```
iMac.local ➜   brew doctor
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: Putting non-prefixed coreutils in your path can cause gmp builds to fail.
iMac.local ➜ 
```

## What you were trying to do (and why)

This is the exact problem:

```
        return tuple(map(int, get_config_var("MACOSX_DEPLOYMENT_TARGET").split('.')))
    AttributeError: 'int' object has no attribute 'split'
```

MACOSX_DEPLOYMENT_TARGET on Mac versions older than Big Sur used to have 10.5, etc but Big Sur just reports 11 which cannot be split by a period.

The full error is

<details>
  <summary>Command output</summary>
  <pre>
==> /usr/local/Cellar/ansible/HEAD-0044091_1/libexec/bin/pip install -v --no-deps --no-binary :all: --ignore-installed /private/tmp/ansible--boto3-20201212-84958-
==> /usr/local/Cellar/ansible/HEAD-0044091_1/libexec/bin/pip install -v --no-deps --no-binary :all: --ignore-installed /private/tmp/ansible--botocore-20201212-849
==> /usr/local/Cellar/ansible/HEAD-0044091_1/libexec/bin/pip install -v --no-deps --no-binary :all: --ignore-installed /private/tmp/ansible--cachetools-20201212-8
==> /usr/local/Cellar/ansible/HEAD-0044091_1/libexec/bin/pip install -v --no-deps --no-binary :all: --ignore-installed /private/tmp/ansible--certifi-20201212-8495
==> /usr/local/Cellar/ansible/HEAD-0044091_1/libexec/bin/pip install -v --no-deps --no-binary :all: --ignore-installed /private/tmp/ansible--cffi-20201212-84958-1
Last 15 lines from /Users/hackeron/Library/Logs/Homebrew/ansible/29.pip:
  File "/usr/local/Cellar/ansible/HEAD-0044091_1/libexec/lib/python3.9/site-packages/pip/_internal/distributions/sdist.py", line 40, in prepare_distribution_metadata
    self.req.prepare_metadata()
  File "/usr/local/Cellar/ansible/HEAD-0044091_1/libexec/lib/python3.9/site-packages/pip/_internal/req/req_install.py", line 555, in prepare_metadata
    self.metadata_directory = self._generate_metadata()
  File "/usr/local/Cellar/ansible/HEAD-0044091_1/libexec/lib/python3.9/site-packages/pip/_internal/req/req_install.py", line 530, in _generate_metadata
    return generate_metadata_legacy(
  File "/usr/local/Cellar/ansible/HEAD-0044091_1/libexec/lib/python3.9/site-packages/pip/_internal/operations/build/metadata_legacy.py", line 70, in generate_metadata
    call_subprocess(
  File "/usr/local/Cellar/ansible/HEAD-0044091_1/libexec/lib/python3.9/site-packages/pip/_internal/utils/subprocess.py", line 242, in call_subprocess
    raise InstallationError(exc_msg)
pip._internal.exceptions.InstallationError: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
WARNING: You are using pip version 20.2.4; however, version 20.3.1 is available.
You should consider upgrading via the '/usr/local/Cellar/ansible/HEAD-0044091_1/libexec/bin/python -m pip install --upgrade pip' command.
Removed file:///private/tmp/ansible--cffi-20201212-84958-1nyaxfy/cffi-1.14.3 from build tracker '/private/tmp/pip-req-tracker-nw82dq_f'
Removed build tracker: '/private/tmp/pip-req-tracker-nw82dq_f'

READ THIS: https://docs.brew.sh/Troubleshooting

These open issues may also help:
ansible 2.10.4 https://github.com/Homebrew/homebrew-core/pull/66823
Please create pull requests instead of asking for help on Homebrew's GitHub,
Twitter or any other official channels.
  </pre>
</details>

Inside of file /Users/hackeron/Library/Logs/Homebrew/ansible/29.pip - these are the relevant lines:

```
Created temporary directory: /private/tmp/pip-ephem-wheel-cache-ibn0yoyv
Created temporary directory: /private/tmp/pip-req-tracker-nw82dq_f
Initialized build tracking at /private/tmp/pip-req-tracker-nw82dq_f
Created build tracker: /private/tmp/pip-req-tracker-nw82dq_f
Entered build tracker: /private/tmp/pip-req-tracker-nw82dq_f
Created temporary directory: /private/tmp/pip-install-yh78y9lm
Processing /private/tmp/ansible--cffi-20201212-84958-1nyaxfy/cffi-1.14.3
  Created temporary directory: /private/tmp/pip-req-build-ah47eo5m
  Added file:///private/tmp/ansible--cffi-20201212-84958-1nyaxfy/cffi-1.14.3 to build tracker '/private/tmp/pip-req-tracker-nw82dq_f'
    Running setup.py (path:/private/tmp/pip-req-build-ah47eo5m/setup.py) egg_info for package from file:///private/tmp/ansible--cffi-20201212-84958-1nyaxfy/cffi-1.14.3
    Created temporary directory: /private/tmp/pip-pip-egg-info-h3pdnp84
    Running command python setup.py egg_info
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/tmp/pip-req-build-ah47eo5m/setup.py", line 152, in <module>
        if 'darwin' in sys.platform and macosx_deployment_target() >= (10, 15):
      File "/private/tmp/pip-req-build-ah47eo5m/setup.py", line 76, in macosx_deployment_target
        return tuple(map(int, get_config_var("MACOSX_DEPLOYMENT_TARGET").split('.')))
    AttributeError: 'int' object has no attribute 'split'
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
Exception information:
Traceback (most recent call last):
  File "/usr/local/Cellar/ansible/HEAD-0044091_1/libexec/lib/python3.9/site-packages/pip/_internal/cli/base_command.py", line 228, in _main
    status = self.run(options, args)
  File "/usr/local/Cellar/ansible/HEAD-0044091_1/libexec/lib/python3.9/site-packages/pip/_internal/cli/req_command.py", line 182, in wrapper
    return func(self, options, args)
  File "/usr/local/Cellar/ansible/HEAD-0044091_1/libexec/lib/python3.9/site-packages/pip/_internal/commands/install.py", line 323, in run
    requirement_set = resolver.resolve(
  File "/usr/local/Cellar/ansible/HEAD-0044091_1/libexec/lib/python3.9/site-packages/pip/_internal/resolution/legacy/resolver.py", line 183, in resolve
    discovered_reqs.extend(self._resolve_one(requirement_set, req))
  File "/usr/local/Cellar/ansible/HEAD-0044091_1/libexec/lib/python3.9/site-packages/pip/_internal/resolution/legacy/resolver.py", line 388, in _resolve_one
    abstract_dist = self._get_abstract_dist_for(req_to_install)
  File "/usr/local/Cellar/ansible/HEAD-0044091_1/libexec/lib/python3.9/site-packages/pip/_internal/resolution/legacy/resolver.py", line 340, in _get_abstract_dist_for
    abstract_dist = self.preparer.prepare_linked_requirement(req)
  File "/usr/local/Cellar/ansible/HEAD-0044091_1/libexec/lib/python3.9/site-packages/pip/_internal/operations/prepare.py", line 482, in prepare_linked_requirement
    abstract_dist = _get_prepared_distribution(
  File "/usr/local/Cellar/ansible/HEAD-0044091_1/libexec/lib/python3.9/site-packages/pip/_internal/operations/prepare.py", line 91, in _get_prepared_distribution
    abstract_dist.prepare_distribution_metadata(finder, build_isolation)
  File "/usr/local/Cellar/ansible/HEAD-0044091_1/libexec/lib/python3.9/site-packages/pip/_internal/distributions/sdist.py", line 40, in prepare_distribution_metadata
    self.req.prepare_metadata()
  File "/usr/local/Cellar/ansible/HEAD-0044091_1/libexec/lib/python3.9/site-packages/pip/_internal/req/req_install.py", line 555, in prepare_metadata
    self.metadata_directory = self._generate_metadata()
  File "/usr/local/Cellar/ansible/HEAD-0044091_1/libexec/lib/python3.9/site-packages/pip/_internal/req/req_install.py", line 530, in _generate_metadata
    return generate_metadata_legacy(
  File "/usr/local/Cellar/ansible/HEAD-0044091_1/libexec/lib/python3.9/site-packages/pip/_internal/operations/build/metadata_legacy.py", line 70, in generate_metadata
    call_subprocess(
  File "/usr/local/Cellar/ansible/HEAD-0044091_1/libexec/lib/python3.9/site-packages/pip/_internal/utils/subprocess.py", line 242, in call_subprocess
    raise InstallationError(exc_msg)
pip._internal.exceptions.InstallationError: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
WARNING: You are using pip version 20.2.4; however, version 20.3.1 is available.
You should consider upgrading via the '/usr/local/Cellar/ansible/HEAD-0044091_1/libexec/bin/python -m pip install --upgrade pip' command.
Removed file:///private/tmp/ansible--cffi-20201212-84958-1nyaxfy/cffi-1.14.3 from build tracker '/private/tmp/pip-req-tracker-nw82dq_f'
Removed build tracker: '/private/tmp/pip-req-tracker-nw82dq_f'
```

## What you expected to happen

I expected it to successfully compile.

## Step-by-step reproduction instructions (by running `brew install` commands)

Run this on Big Sur - reproduced both on x86 and arm:
```
brew install ansible --HEAD
```

**Comment by issyl0** [comment]
Sorry, but `HEAD` builds are unsupported:

> Please create pull requests instead of asking for help on Homebrew's GitHub, Twitter or any other official channels.

You'll have to figure this error out for yourself, or wait until the next released version for the feature you need from Ansible's main branch.

**Comment by rgaufman** [comment]
Thank you for the prompt response. I did figure out the error, it is ENV variable MACOSX_DEPLOYMENT_TARGET passing an integer of 11 instead of the expected string of '11.0'.

I'll see if I can figure out how to pass the correct ENV variable and create a pull request, I'm new to homebrew, thank you.

**Comment by eugene1g** [comment]
@rgaufman This just got resolved (in https://github.com/Homebrew/homebrew-core/pull/66823) - ansible now installs `2.10.3`. Thanks for making it google'able for the rest of us!
