### ISSUE TITLE
brew upgrade failed at all with Error: Calling Formula.sha1 is disabled!

### ISSUE THREAD

**Issue by Viktor45** [Homebrew/homebrew-core#6693]
why not just ignore invalid taps instead of break all upgrade process at all?

```

$ brew -v
Homebrew 1.1.0
Homebrew/homebrew-core (git revision 375a8; last commit 2016-11-07)

$ brew config
HOMEBREW_VERSION: 1.1.0
ORIGIN: https://github.com/Homebrew/brew.git
HEAD: b7abd33475b98598b414f9c4ee2e20249855437b
Last commit: 6 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 375a83c1af8c25290e5d41001e93e335c540e857
Core tap last commit: 5 hours ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_REPOSITORY: /usr/local/Homebrew
HOMEBREW_CELLAR: /usr/local/Cellar
HOMEBREW_BOTTLE_DOMAIN: https://homebrew.bintray.com
CPU: dual-core 64-bit penryn
Homebrew Ruby: 2.0.0-p648
Clang: 7.3 build 703
Git: 2.7.4 => /Library/Developer/CommandLineTools/usr/bin/git
Perl: /usr/bin/perl
Python: /usr/bin/python
Ruby: /usr/bin/ruby => /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin/ruby
Java: 1.6.0_65-b14-468
macOS: 10.11.6-x86_64
Xcode: N/A
CLT: 7.3.1.0.1.1461711523
X11: 2.7.9 => /opt/X11

$ brew upgrade
Updating Homebrew...
Error: Calling Formula.sha1 is disabled!
Use Formula.sha256 instead.
/usr/local/Homebrew/Library/Taps/jide/homebrew-clamp/clamp.rb:7:in `<class:Clamp>'
Please report this to the jide/clamp tap!
Please report this bug:
  https://git.io/brew-troubleshooting
/usr/local/Homebrew/Library/Homebrew/utils.rb:86:in `odeprecated'
/usr/local/Homebrew/Library/Homebrew/utils.rb:94:in `odisabled'
/usr/local/Homebrew/Library/Homebrew/compat/sha1.rb:3:in `sha1'
/usr/local/Homebrew/Library/Taps/jide/homebrew-clamp/clamp.rb:7:in `<class:Clamp>'
/usr/local/Homebrew/Library/Taps/jide/homebrew-clamp/clamp.rb:3:in `load_formula'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:25:in `module_eval'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:25:in `load_formula'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:42:in `load_formula_from_path'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:97:in `load_file'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:88:in `klass'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:84:in `get_formula'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:200:in `get_formula'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:240:in `factory'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:271:in `from_keg'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:254:in `from_rack'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1357:in `block in installed'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1355:in `map'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1355:in `installed'
/usr/local/Homebrew/Library/Homebrew/cmd/upgrade.rb:37:in `upgrade'
/usr/local/Homebrew/Library/Homebrew/brew.rb:94:in `<main>'

$ brew doctor
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry and just ignore them. Thanks!

Warning: "config" scripts exist outside your system or Homebrew directories.
`./configure` scripts often look for *-config scripts to determine if
software packages are installed, and what additional flags to use when
compiling and linking.

Having additional scripts in your path can confuse software installed via
Homebrew if the config script overrides a system or Homebrew provided
script of the same name. We found the following "config" scripts:
  /Library/Frameworks/Python.framework/Versions/3.4/bin/python3-config
  /Library/Frameworks/Python.framework/Versions/3.4/bin/python3.4-config
  /Library/Frameworks/Python.framework/Versions/3.4/bin/python3.4m-config

Warning: Python is installed at /Library/Frameworks/Python.framework

Homebrew only supports building against the System-provided Python or a
brewed Python. In particular, Pythons installed to /Library can interfere
with other software installs.

Warning: You have unlinked kegs in your Cellar
Leaving kegs unlinked can lead to build-trouble and cause brews that depend on
those kegs to fail to run properly once built. Run `brew link` on these:
  python
  unrar
Error: Calling Formula.sha1 is disabled!
Use Formula.sha256 instead.
/usr/local/Homebrew/Library/Taps/jide/homebrew-clamp/clamp.rb:7:in `<class:Clamp>'
Please report this to the jide/clamp tap!
Please report this bug:
  https://git.io/brew-troubleshooting
/usr/local/Homebrew/Library/Homebrew/utils.rb:86:in `odeprecated'
/usr/local/Homebrew/Library/Homebrew/utils.rb:94:in `odisabled'
/usr/local/Homebrew/Library/Homebrew/compat/sha1.rb:3:in `sha1'
/usr/local/Homebrew/Library/Taps/jide/homebrew-clamp/clamp.rb:7:in `<class:Clamp>'
/usr/local/Homebrew/Library/Taps/jide/homebrew-clamp/clamp.rb:3:in `load_formula'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:25:in `module_eval'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:25:in `load_formula'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:42:in `load_formula_from_path'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:97:in `load_file'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:88:in `klass'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:84:in `get_formula'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:200:in `get_formula'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:240:in `factory'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:271:in `from_keg'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:254:in `from_rack'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1357:in `block in installed'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1355:in `map'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1355:in `installed'
/usr/local/Homebrew/Library/Homebrew/diagnostic.rb:869:in `check_missing_deps'
/usr/local/Homebrew/Library/Homebrew/cmd/doctor.rb:43:in `block in doctor'
/usr/local/Homebrew/Library/Homebrew/cmd/doctor.rb:35:in `each'
/usr/local/Homebrew/Library/Homebrew/cmd/doctor.rb:35:in `doctor'
/usr/local/Homebrew/Library/Homebrew/brew.rb:94:in `<main>'

```

**Comment by bfontaine** [comment]
The use of `sha1` was deprecated almost two years ago.

1. In [February 2015](https://github.com/Homebrew/brew/commit/12861686b847f26f50af7d9a9024a0bc4d25b3bd) `brew audit --strict` started to show a warning and we updated all docs to advise not to use `sha1`.
2. In [June 2015](https://github.com/Homebrew/brew/commit/4f74e89) `brew audit` started to show the warning even without `--strict`.
3. In [March 2016](https://github.com/Homebrew/brew/commit/bd7e8543b3fba04a914f8f8c583652d6970d51db) `brew` started complaining about `sha1` in formulae.
4. We completely disabled it [yesterday](https://github.com/Homebrew/brew/commit/fcaa48d80b0c2989ca95528def6d0c8fbd65aa79).

You should submit a pull-request to the tap repository instead.

**Comment by rnelson0** [comment]
This has nothing to do with announcement timelines and everything to do with expectations surrounding the use of semver in 2016. You've caused backwards incompatibility not just in brew but in the ecosystem surrounding it. Your response to people telling you this has a decidedly "you're holding it wrong" tone it - which is certainly your prerogative, but it's our prerogative to be equally annoyed by it, too.
