### ISSUE TITLE
Disabled SHA1-Support is blocking the remove of unmaintained packages

### ISSUE THREAD

**Issue by Tilogorn** [Homebrew/homebrew-core#6999]
The disabled use for `Formula.sha1` is not only blocking the *installation* of a formula but *all* formula-related actions, even `brew remove` or `brew gist-logs`.

As I want to remove an old, unmaintained formula, `brew` is denying this action with the `Calling Formula.sha1 is disabled!` error.

See console outputs:

```
$ brew gist-logs cairo-quartz
Error: Calling Formula.sha1 is disabled!
Use Formula.sha256 instead.
/usr/local/Homebrew/Library/Taps/acornejo/homebrew-quartz/cairo-quartz.rb:6:in `<class:CairoQuartz>'
Please report this to the acornejo/quartz tap!
Please report this bug:
  https://git.io/brew-troubleshooting
/usr/local/Homebrew/Library/Homebrew/utils.rb:86:in `odeprecated'
/usr/local/Homebrew/Library/Homebrew/utils.rb:94:in `odisabled'
/usr/local/Homebrew/Library/Homebrew/compat/sha1.rb:3:in `sha1'
/usr/local/Homebrew/Library/Taps/acornejo/homebrew-quartz/cairo-quartz.rb:6:in `<class:CairoQuartz>'
/usr/local/Homebrew/Library/Taps/acornejo/homebrew-quartz/cairo-quartz.rb:3:in `load_formula'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:25:in `module_eval'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:25:in `load_formula'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:42:in `load_formula_from_path'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:97:in `load_file'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:88:in `klass'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:84:in `get_formula'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:241:in `factory'
/usr/local/Homebrew/Library/Homebrew/extend/ARGV.rb:67:in `block in resolved_formulae'
/usr/local/Homebrew/Library/Homebrew/extend/ARGV.rb:52:in `map'
/usr/local/Homebrew/Library/Homebrew/extend/ARGV.rb:52:in `resolved_formulae'
/usr/local/Homebrew/Library/Homebrew/cmd/gist-logs.rb:125:in `gist_logs'
/usr/local/Homebrew/Library/Homebrew/brew.rb:94:in `<main>'
```

Same output for `brew remove` and `brew remove --force`. I want to get rid of this old formula, but I can't. Since the maintainer of the formula is not reacting (I openend [this issue](https://github.com/acornejo/homebrew-quartz/issues/9?_pjax=%23js-repo-pjax-container) in august) I think only the core team can make removing such formulas possible.

```
brew config
HOMEBREW_VERSION: 1.1.1
ORIGIN: https://github.com/Homebrew/brew.git
HEAD: edf042ee97f80955b077724119e717a51eb25e29
Last commit: 22 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 0940307b539a30b9d5f169440448ab7d745ddc6b
Core tap last commit: 3 hours ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_REPOSITORY: /usr/local/Homebrew
HOMEBREW_CELLAR: /usr/local/Cellar
HOMEBREW_BOTTLE_DOMAIN: https://homebrew.bintray.com
CPU: quad-core 64-bit ivybridge
Homebrew Ruby: 2.0.0-p648
Clang: 8.0 build 800
Git: 2.9.3 => /Applications/Xcode.app/Contents/Developer/usr/bin/git
Perl: /usr/bin/perl
Python: /usr/local/bin/python => /usr/local/Cellar/python/2.7.12_2/Frameworks/Python.framework/Versions/2.7/bin/python2.7
Ruby: /usr/bin/ruby => /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin/ruby
Java: 1.8.0_40, 1.6.0_65-b14-468
macOS: 10.11.6-x86_64
Xcode: 8.1
CLT: 7.3.1.0.1.1461711523
X11: 2.7.9 => /opt/X11
```

**Comment by ilovezfs** [comment]
If you `brew untap acornejo/quartz` can you then remove it?

**Comment by MikeMcQuaid** [comment]
Or use `brew uninstall --force`?

**Comment by ilovezfs** [comment]
Unfortunately that doesn't work.

**Comment by MikeMcQuaid** [comment]
Opened a PR for this in https://github.com/Homebrew/brew/issues/1529. It'll take until 1.1.2 before it'll end up with you, though @Tilogorn so don't be surprised if it's not working right after merge.

**Comment by MikeMcQuaid** [comment]
The PR was merged.

**Comment by ponkster** [comment]
any clue how to resolve this?

**Comment by MikeMcQuaid** [comment]
Homebrew 1.1.2 has been released so this is now fixed if you `brew update`.
