### ISSUE TITLE
`autoremove` removed `libyaml` and now system gem and brew no longer work

### ISSUE THREAD

**Issue by GeQi** [Homebrew/homebrew-core#70753]
**`brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output**

Every brew command now only prints out this error message:
```
Traceback (most recent call last):
	18: from /usr/local/Homebrew/Library/Homebrew/brew.rb:31:in `<main>'
	17: from /usr/local/Homebrew/Library/Homebrew/brew.rb:31:in `require_relative'
	16: from /usr/local/Homebrew/Library/Homebrew/global.rb:34:in `<top (required)>'
	15: from /usr/local/Homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/i18n-1.8.7/lib/i18n.rb:55:in `backend'
	14: from /usr/local/Homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/i18n-1.8.7/lib/i18n/config.rb:21:in `backend'
	13: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	12: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	11: from /usr/local/Homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/i18n-1.8.7/lib/i18n/backend/simple.rb:3:in `<top (required)>'
	10: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	9: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	8: from /usr/local/Homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/i18n-1.8.7/lib/i18n/backend/base.rb:3:in `<top (required)>'
	7: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	6: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	5: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/yaml.rb:4:in `<top (required)>'
	4: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	3: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	2: from /Library/Ruby/Gems/2.6.0/gems/psych-3.3.0/lib/psych.rb:13:in `<top (required)>'
	1: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require': dlopen(/Library/Ruby/Gems/2.6.0/gems/psych-3.3.0/lib/psych.bundle, 0x0009): dependent dylib '/usr/local/opt/libyaml/lib/libyaml-0.2.dylib' not found for '/Library/Ruby/Gems/2.6.0/gems/psych-3.3.0/lib/psych.bundle' - /Library/Ruby/Gems/2.6.0/gems/psych-3.3.0/lib/psych.bundle (LoadError)
```

And system gem (`/usr/bin/gem`) only returns
```
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/yaml.rb:3: warning: It seems your ruby installation is missing psych (for YAML output).
To eliminate this warning, please install libyaml and reinstall your ruby.
Traceback (most recent call last):
	14: from /usr/bin/gem:21:in `<main>'
	13: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/gem_runner.rb:44:in `run'
	12: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/gem_runner.rb:79:in `do_configuration'
	11: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/gem_runner.rb:79:in `new'
	10: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/config_file.rb:198:in `initialize'
	9: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/config_file.rb:346:in `load_file'
	8: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems.rb:701:in `load_yaml'
	7: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	6: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	5: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/yaml.rb:4:in `<top (required)>'
	4: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	3: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	2: from /Library/Ruby/Gems/2.6.0/gems/psych-3.3.0/lib/psych.rb:13:in `<top (required)>'
	1: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require': dlopen(/Library/Ruby/Gems/2.6.0/gems/psych-3.3.0/lib/psych.bundle, 0x0009): dependent dylib '/usr/local/opt/libyaml/lib/libyaml-0.2.dylib' not found for '/Library/Ruby/Gems/2.6.0/gems/psych-3.3.0/lib/psych.bundle' - /Library/Ruby/Gems/2.6.0/gems/psych-3.3.0/lib/psych.bundle (LoadError)
```

****

- [X] The `brew doctor` above contains no "Warning" lines.

**What were you trying to do (and why)?**

`brew autoremove`

**What happened (include all command output)?**

```
~ ❯ brew autoremove 
==> Uninstalling 12 unneeded formulae:
bison
cython
docutils
libspiro
libuninameslist
libyaml
meson
pango
re2c
sphinx-doc
texi2html
texinfo
Uninstalling /usr/local/Cellar/docutils/0.16_2... (810 files, 8.9MB)
Uninstalling /usr/local/Cellar/pango/1.48.1... (64 files, 3MB)
Uninstalling /usr/local/Cellar/texi2html/5.0... (279 files, 6.2MB)
Uninstalling /usr/local/Cellar/libyaml/0.2.5... (10 files, 323.5KB)
Uninstalling /usr/local/Cellar/cython/0.29.21_1... (322 files, 6.9MB)
Uninstalling /usr/local/Cellar/meson/0.56.2... (276 files, 4.2MB)
Uninstalling /usr/local/Cellar/re2c/2.0.3... (10 files, 1.4MB)
Uninstalling /usr/local/Cellar/libuninameslist/20200413... (15 files, 4.2MB)
Uninstalling /usr/local/Cellar/sphinx-doc/3.4.3... (3,853 files, 55.3MB)
Uninstalling /usr/local/Cellar/libspiro/20200505... (17 files, 118.2KB)
Uninstalling /usr/local/Cellar/texinfo/6.7... (404 files, 7.4MB)
Uninstalling /usr/local/Cellar/bison/3.7.5... (94 files, 3.3MB)
```

**What did you expect to happen?**

I'm not expecting to break the system gem and homebrew itself with it.

**Step-by-step reproduction instructions (by running `brew` commands)**

`brew autoremove`

**Comment by GeQi** [comment]
I just revived my gem and brew by compiling yaml manually and linked the dylib file.

Still I'm very confused how `autoremove` could have done this in the first place.

**Comment by SMillerDev** [comment]
I don't have this gem on a clean install so you must have installed it yourself.
