### ISSUE TITLE
old brew doesn't run on Big Sur

### ISSUE THREAD

**Issue by JonathanGoodman** [Homebrew/homebrew-core#71214]
**`brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output**

[JonathansMBP20:~] jg% brew doctor
Traceback (most recent call last):
	11: from /usr/local/Library/brew.rb:6:in `<main>'
	10: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	 9: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	 8: from /usr/local/Library/Homebrew/global.rb:7:in `<top (required)>'
	 7: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	 6: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	 5: from /usr/local/Library/Homebrew/os.rb:1:in `<top (required)>'
	 4: from /usr/local/Library/Homebrew/os.rb:16:in `<module:OS>'
	 3: from /usr/local/Library/Homebrew/os/mac.rb:18:in `version'
	 2: from /usr/local/Library/Homebrew/os/mac.rb:18:in `new'
	 1: from /usr/local/Library/Homebrew/os/mac/version.rb:25:in `initialize'
/usr/local/Library/Homebrew/version.rb:186:in `initialize': Version value must be a string (TypeError)
[JonathansMBP20:~] jg% brew config
Traceback (most recent call last):
	11: from /usr/local/Library/brew.rb:6:in `<main>'
	10: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	 9: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	 8: from /usr/local/Library/Homebrew/global.rb:7:in `<top (required)>'
	 7: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	 6: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	 5: from /usr/local/Library/Homebrew/os.rb:1:in `<top (required)>'
	 4: from /usr/local/Library/Homebrew/os.rb:16:in `<module:OS>'
	 3: from /usr/local/Library/Homebrew/os/mac.rb:18:in `version'
	 2: from /usr/local/Library/Homebrew/os/mac.rb:18:in `new'
	 1: from /usr/local/Library/Homebrew/os/mac/version.rb:25:in `initialize'

****

- [X] The `brew doctor` above contains no "Warning" lines.

**What were you trying to do (and why)?**

bring my cmake up to date

**What happened (include all command output)?**

Every command gives the same output.  For example
 brew --version
Traceback (most recent call last):
	11: from /usr/local/Library/brew.rb:6:in `<main>'
	10: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	 9: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	 8: from /usr/local/Library/Homebrew/global.rb:7:in `<top (required)>'
	 7: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	 6: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	 5: from /usr/local/Library/Homebrew/os.rb:1:in `<top (required)>'
	 4: from /usr/local/Library/Homebrew/os.rb:16:in `<module:OS>'
	 3: from /usr/local/Library/Homebrew/os/mac.rb:18:in `version'
	 2: from /usr/local/Library/Homebrew/os/mac.rb:18:in `new'
	 1: from /usr/local/Library/Homebrew/os/mac/version.rb:25:in `initialize'
/usr/local/Library/Homebrew/version.rb:186:in `initialize': Version value must be a string (TypeError)

I don't know if this helps, but the version.rb file in /usr/local/Library/Homebrew/os/mac starts with a list of mac operating systems that doesn't include Big Sur.  Here's the beginning of that file.

require "version"

module OS
  module Mac
    class Version < ::Version
      SYMBOLS = {
        :el_capitan    => "10.11",
        :yosemite      => "10.10",
        :mavericks     => "10.9",
        :mountain_lion => "10.8",
        :lion          => "10.7",
        :snow_leopard  => "10.6",
        :leopard       => "10.5",
        :tiger         => "10.4"
      }

**What did you expect to happen?**

I would be glad to delete my old brew and install the most recent one, but my old brew won't do that.

**Step-by-step reproduction instructions (by running `brew` commands)**

I hope this is clear from above

**Comment by carlocab** [comment]
Try `brew update-reset`. Note, however, the following:
```
❯ brew help update-reset
Usage: brew update-reset [repository ...]

Fetch and reset Homebrew and all tap repositories (or any specified
repository) using git(1) to their latest origin/HEAD.

Note: this will destroy all your uncommitted or committed changes.
```
