### ISSUE TITLE
log4cxx failed to build on 10.12.1

### ISSUE THREAD

**Issue by Joschka1** [Homebrew/homebrew-core#7149]
log4cxx failed to build on my macOS 10.12.1. If i try to run `brew upgrade`, i get this error message:

```
Error: /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/log4cxx.rb:62: syntax error, unexpected <<
<<<<<<< Updated upstream
  ^
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/log4cxx.rb:63: syntax error, unexpected ',', expecting keyword_end
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/log4cxx.rb:65: syntax error, unexpected ===, expecting keyword_end
=======
   ^
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/log4cxx.rb:66: syntax error, unexpected ',', expecting keyword_end
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/log4cxx.rb:68: syntax error, unexpected >>, expecting keyword_end
>>>>>>> Stashed changes
  ^
Please report this bug:
  https://git.io/brew-troubleshooting
/usr/local/Homebrew/Library/Homebrew/formulary.rb:25:in `module_eval'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:25:in `load_formula'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:42:in `load_formula_from_path'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:97:in `load_file'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:88:in `klass'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:84:in `get_formula'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:241:in `factory'
/usr/local/Homebrew/Library/Homebrew/extend/ARGV.rb:67:in `block in resolved_formulae'
/usr/local/Homebrew/Library/Homebrew/extend/ARGV.rb:52:in `map'
/usr/local/Homebrew/Library/Homebrew/extend/ARGV.rb:52:in `resolved_formulae'
/usr/local/Homebrew/Library/Homebrew/cmd/gist-logs.rb:125:in `gist_logs'
/usr/local/Homebrew/Library/Homebrew/brew.rb:94:in `<main>'
```

run `brew doctor`results in same message.

my `brew config` looks as follow: 

```
HOMEBREW_VERSION: 1.1.1-56-gc3f959d
ORIGIN: https://github.com/Homebrew/brew
HEAD: c3f959d6af36f075600aac63f208d59c30cd602c
Last commit: 15 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: d8e307747793a0f910efbecc7a56eb6204e60a22
Core tap last commit: 3 hours ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_REPOSITORY: /usr/local/Homebrew
HOMEBREW_CELLAR: /usr/local/Cellar
HOMEBREW_BOTTLE_DOMAIN: https://homebrew.bintray.com
CPU: octa-core 64-bit ivybridge
Homebrew Ruby: 2.0.0-p648
Clang: 8.0 build 800
Git: 2.10.2 => /usr/local/bin/git
Perl: /usr/bin/perl
Python: /usr/local/bin/python => usr/local/Cellar/python/2.7.12_2/Frameworks/Python.framework/Versions/2.7/bin/python2.7
Ruby: /usr/bin/ruby => /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin/ruby
Java: 1.8.0_92
macOS: 10.12.1-x86_64
Xcode: 8.1
CLT: 8.1.0.0.1.1476494586
X11: 2.7.9 => /opt/X11

```

**Comment by MikeMcQuaid** [comment]
`cd /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/ && git reset --hard origin/master` will fix this.
