### ISSUE TITLE
postinstall python@3.9 fails on conflict with pip user configuration

### ISSUE THREAD

**Issue by Raphx** [Homebrew/homebrew-core#74131]
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

```shell
HOMEBREW_VERSION: 3.0.10-23-g5e0b08d
ORIGIN: https://github.com/Homebrew/brew
HEAD: 5e0b08dd01bdce3523c7e095739641b6f33b902a
Last commit: 4 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 745ccd12bc069ddba70c13f0d07a4bca82aa20e0
Core tap last commit: 3 hours ago
Core tap branch: master
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CASK_OPTS: []
HOMEBREW_EDITOR: vim
HOMEBREW_MAKE_JOBS: 4
HOMEBREW_NO_AUTO_UPDATE: set
Homebrew Ruby: 2.6.3 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: quad-core 64-bit broadwell
Clang: 12.0 build 1200
Git: 2.31.1 => /usr/local/bin/git
Curl: 7.64.1 => /usr/bin/curl
macOS: 11.2.3-x86_64
CLT: 12.4.0.0.1.1610135815
Xcode: N/A
```

### 

- [X] The `brew doctor` above contains no "Warning" lines.

### What were you trying to do (and why)?

Installing / upgrading python 3.9 using Homebrew.

### What happened (include all command output)?

Post installation failed. This happened because I have my own pip configuration in `~/.config/pip/pip.conf`. The content of this file:

```
[install]
user = true
```

Removing the user option in this file would allow post-installation to succeed, which is the workaround for now.

Failure log:

```
==> Postinstalling python@3.9
==> /usr/local/Cellar/python@3.9/3.9.2_4/bin/python3 -m ensurepip
==> /usr/local/Cellar/python@3.9/3.9.2_4/bin/python3 -m pip install -v --no-deps --no-index --upgrade --target=/usr/local/lib/python3.9/site-packages /usr/local/Cellar/python@3.9/3.9.2_4/Framework
Last 15 lines from /Users/raphx/Library/Logs/Homebrew/python@3.9/post_install.02.python3:
/usr/local/Cellar/python@3.9/3.9.2_4/Frameworks/Python.framework/Versions/3.9/lib/python3.9/ensurepip/_bundled/setuptools-54.1.2-py3-none-any.whl
/usr/local/Cellar/python@3.9/3.9.2_4/Frameworks/Python.framework/Versions/3.9/lib/python3.9/ensurepip/_bundled/pip-21.0.1-py3-none-any.whl
/usr/local/Cellar/python@3.9/3.9.2_4/libexec/wheel-0.36.2-py2.py3-none-any.whl

WARNING: The directory '/Users/raphx/Library/Caches/pip' or its parent directory is not owned or is not writable by the current user. The cache has been disabled. Check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
ERROR: Can not combine '--user' and '--target'
Exception information:
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/pip/_internal/cli/base_command.py", line 189, in _main
    status = self.run(options, args)
  File "/usr/local/lib/python3.9/site-packages/pip/_internal/cli/req_command.py", line 178, in wrapper
    return func(self, options, args)
  File "/usr/local/lib/python3.9/site-packages/pip/_internal/commands/install.py", line 228, in run
    raise CommandError("Can not combine '--user' and '--target'")
pip._internal.exceptions.CommandError: Can not combine '--user' and '--target'
Warning: The post-install step did not complete successfully
You can try again using:
  brew postinstall python@3.9
```

### What did you expect to happen?

Post installation should succeed, even when a user has custom pip configuration.

### Step-by-step reproduction instructions (by running `brew` commands)

Ensure `~/.config/pip/pip.conf` has this content:

```shell
[install]
user = true
```

Then install / upgrade / re-install python@3.9.

**Comment by carlocab** [comment]
Can you check if adding an `--isolated` or `--no-user-cfg` flag here helps

https://github.com/Homebrew/homebrew-core/blob/146d4ea914531d2a5c458c335b5a44a76f46c78f/Formula/python%403.9.rb#L335-L342

?

**Comment by Raphx** [comment]
Works with `--isolated`, I could run post-installation successfully even while retaining `[install]\nuser = true` on my pip configuration.

`--no-user-cfg` errors out though:

```
==> Postinstalling python@3.9
==> /usr/local/Cellar/python@3.9/3.9.2_4/bin/python3 -m ensurepip
==> /usr/local/Cellar/python@3.9/3.9.2_4/bin/python3 -m pip install -v --no-deps --no-index --upg
Last 15 lines from /Users/raphx/Library/Logs/Homebrew/python@3.9/post_install.02.python3:
--no-user-cfg
--target=/usr/local/lib/python3.9/site-packages
/usr/local/Cellar/python@3.9/3.9.2_4/Frameworks/Python.framework/Versions/3.9/lib/python3.9/ensurepip/_bundled/setuptools-54.1.2-py3-none-any.whl
/usr/local/Cellar/python@3.9/3.9.2_4/Frameworks/Python.framework/Versions/3.9/lib/python3.9/ensurepip/_bundled/pip-21.0.1-py3-none-any.whl
/usr/local/Cellar/python@3.9/3.9.2_4/libexec/wheel-0.36.2-py2.py3-none-any.whl


Usage:
  /usr/local/opt/python@3.9/bin/python3.9 -m pip install [options] <requirement specifier> [package-index-options] ...
  /usr/local/opt/python@3.9/bin/python3.9 -m pip install [options] -r <requirements file> [package-index-options] ...
  /usr/local/opt/python@3.9/bin/python3.9 -m pip install [options] [-e] <vcs project url> ...
  /usr/local/opt/python@3.9/bin/python3.9 -m pip install [options] [-e] <local project path> ...
  /usr/local/opt/python@3.9/bin/python3.9 -m pip install [options] <archive url/path> ...

no such option: --no-user-cfg
Warning: The post-install step did not complete successfully
You can try again using:
  brew postinstall python@3.9
```

**Comment by carlocab** [comment]
Great. Do you want to open a PR to fix it?

**Comment by Raphx** [comment]
Submitted a PR. Thanks for guiding along, @carlocab :)

**Comment by carlocab** [comment]
No problem, @Raphx. Thanks for the report.
