### ISSUE TITLE
Brew with OSX 10.12 have trouble uninstalling

### ISSUE THREAD

**Issue by qizhen816** [Homebrew/homebrew-core#7464]
If Homebrew was updated on Aug 10-11th 2016 and `brew update` always says `Already up-to-date.` you need to run: `cd "$(brew --repo)" && git fetch && git reset --hard origin/master && brew update`.
```
 QimatoMacBook-Pro:local qizhen816$ cd "$(brew --repo)" && git fetch && git reset --hard origin/master && brew update
HEAD is now at 8f82e89 README: update license name.
Already up-to-date.**
```

I Ran `brew doctor`, it gives me :
```
`QimatoMacBook-Pro:Homebrew qizhen816$ brew doctor
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry and just ignore them. Thanks!

Warning: Anaconda is known to frequently break Homebrew builds, including Vim and
MacVim, due to bundling many duplicates of system and Homebrew-available
tools.

If you encounter a build failure please temporarily remove Anaconda
from your $PATH and attempt the build again prior to reporting the
failure to us. Thanks!

Warning: python is symlinked to python3
This will confuse build scripts and in general lead to subtle breakage.

Warning: "config" scripts exist outside your system or Homebrew directories.
`./configure` scripts often look for *-config scripts to determine if
software packages are installed, and what additional flags to use when
compiling and linking.

Having additional scripts in your path can confuse software installed via
Homebrew if the config script overrides a system or Homebrew provided
script of the same name. We found the following "config" scripts:
  /Users/qizhen816/anaconda/bin/curl-config
  /Users/qizhen816/anaconda/bin/freetype-config
  /Users/qizhen816/anaconda/bin/icu-config
  /Users/qizhen816/anaconda/bin/libdynd-config
  /Users/qizhen816/anaconda/bin/libpng-config
  /Users/qizhen816/anaconda/bin/libpng16-config
  /Users/qizhen816/anaconda/bin/powerline-config
  /Users/qizhen816/anaconda/bin/python3-config
  /Users/qizhen816/anaconda/bin/python3.5-config
  /Users/qizhen816/anaconda/bin/python3.5m-config
  /Users/qizhen816/anaconda/bin/xml2-config
  /Users/qizhen816/anaconda/bin/xslt-config

Warning:

 Python is installed at /Library/Frameworks/Python.framework

Homebrew only supports building against the System-provided Python or a
brewed Python. In particular, Pythons installed to /Library can interfere
with other software installs.

Warning: You have leftover files from an older version of Xcode.
You should delete them using:
  /Developer/Library/uninstall-developer-folder

Warning: Unbrewed dylibs were found in /usr/local/lib.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected dylibs:
  /usr/local/lib/libaspell.15.1.4.dylib
  /usr/local/lib/libcudnn.5.dylib
  /usr/local/lib/libpspell.15.1.4.dylib

Warning: Unbrewed header files were found in /usr/local/include.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected header files:
  /usr/local/include/aspell.h
  /usr/local/include/cudnn.h
  /usr/local/include/pspell/pspell.h

Warning: Unbrewed .la files were found in /usr/local/lib.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected .la files:
  /usr/local/lib/libaspell.la
  /usr/local/lib/libpspell.la

Warning: Unbrewed static libraries were found in /usr/local/lib.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected static libraries:
  /usr/local/lib/libcaffe.a
  /usr/local/lib/libcudnn_static.a

Warning: Some directories in your path end in a slash.
Directories in your path should not end in a slash. This can break other
doctor checks. The following directories should be edited:
  /Developer/NVIDIA/CUDA-8.0/bin/
  /opt/local/sbin/
Error: /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/boost.rb:42: syntax error, unexpected <<
<<<<<<< Updated upstream
  ^
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/boost.rb:43: syntax error, unexpected ===, expecting keyword_end
=======
   ^
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/boost.rb:59: syntax error, unexpected >>, expecting keyword_end
>>>>>>> Stashed changes
  ^
Please report this bug:
  https://git.io/brew-troubleshooting
/usr/local/Homebrew/Library/Homebrew/formulary.rb:25:in `module_eval'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:25:in `load_formula'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:42:in `load_formula_from_path'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:97:in `load_file'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:88:in `klass'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:84:in `get_formula'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:201:in `get_formula'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:241:in `factory'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:272:in `from_keg'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:255:in `from_rack'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1368:in `block in installed'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1366:in `map'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1366:in `installed'
/usr/local/Homebrew/Library/Homebrew/diagnostic.rb:879:in `check_missing_deps'
/usr/local/Homebrew/Library/Homebrew/cmd/doctor.rb:43:in `block in doctor'
/usr/local/Homebrew/Library/Homebrew/cmd/doctor.rb:35:in `each'
/usr/local/Homebrew/Library/Homebrew/cmd/doctor.rb:35:in `doctor'
/usr/local/Homebrew/Library/Homebrew/brew.rb:94:in `<main>'`
```

**when I uninstall opencv, it gives me:**
```
QimatoMacBook-Pro:local qizhen816$ brew uninstall opencv
Error: /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/boost.rb:42: syntax error, unexpected <<
<<<<<<< Updated upstream
  ^
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/boost.rb:43: syntax error, unexpected ===, expecting keyword_end
=======
   ^
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/boost.rb:59: syntax error, unexpected >>, expecting keyword_end
>>>>>>> Stashed changes
  ^
Please report this bug:
  https://git.io/brew-troubleshooting
/usr/local/Homebrew/Library/Homebrew/formulary.rb:25:in `module_eval'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:25:in `load_formula'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:42:in `load_formula_from_path'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:97:in `load_file'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:88:in `klass'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:84:in `get_formula'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:201:in `get_formula'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:241:in `factory'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:272:in `from_keg'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:255:in `from_rack'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1368:in `block in installed'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1366:in `map'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1366:in `installed'
/usr/local/Homebrew/Library/Homebrew/keg.rb:342:in `installed_dependents'
/usr/local/Homebrew/Library/Homebrew/keg.rb:95:in `block in find_some_installed_dependents'
/usr/local/Homebrew/Library/Homebrew/keg.rb:94:in `each'
/usr/local/Homebrew/Library/Homebrew/keg.rb:94:in `find_some_installed_dependents'
/usr/local/Homebrew/Library/Homebrew/cmd/uninstall.rb:90:in `check_for_dependents'
/usr/local/Homebrew/Library/Homebrew/cmd/uninstall.rb:83:in `handle_unsatisfied_dependents'
/usr/local/Homebrew/Library/Homebrew/cmd/uninstall.rb:31:in `uninstall'
/usr/local/Homebrew/Library/Homebrew/brew.rb:94:in `<main>'
```

**Comment by MikeMcQuaid** [comment]
cd "$(brew --repo homebrew/core)" && git fetch && git reset --hard origin/master && brew update should fix this.

**Comment by ilovezfs** [comment]
@qizhen816 did that fix it for you?

**Comment by qizhen816** [comment]
sorry, I went out these days. Luckily after I tried 2 times,  it worked, guess it needs to reboot.:)
