### ISSUE TITLE
openssl@1.1 postinstall does not complete successfully

### ISSUE THREAD

**Issue by anandb-ripencc** [Homebrew/homebrew-core#75003]
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

```shell
% brew config
HOMEBREW_VERSION: 3.0.11
ORIGIN: https://github.com/Homebrew/brew
HEAD: 8e11f03fa93b148e26044a331654241a2c307039
Last commit: 7 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 9f0748072efdf331612040c7cea86f322c3119b2
Core tap last commit: 11 minutes ago
Core tap branch: master
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CASK_OPTS: []
HOMEBREW_EDITOR: vim
HOMEBREW_MAKE_JOBS: 8
Homebrew Ruby: 2.6.3 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: octa-core 64-bit icelake
Clang: 12.0 build 1200
Git: 2.24.3 => /Library/Developer/CommandLineTools/usr/bin/git
Curl: 7.64.1 => /usr/bin/curl
macOS: 11.2.3-x86_64
CLT: 12.4.0.0.1.1610135815
Xcode: N/A

% brew doctor
Your system is ready to brew.
```

### 

The `brew doctor` above contains no "Warning" lines.

### What were you trying to do (and why)?

I installed "python@3.9". This pulls in "openssl@1.1" as a dependency. But the openssl package's post-install does not complete.

### What happened (include all command output)?

```
brew install python@3.9
Updating Homebrew...
==> Auto-updated Homebrew!
Updated 1 tap (homebrew/core).
==> Updated Formulae
Updated 5 formulae.

==> Downloading https://homebrew.bintray.com/bottles/gdbm-1.19.big_sur.bottle.tar.gz
==> Downloading from https://d29vzk4ow07wi7.cloudfront.net/3581501b051db1c0d1acccc710fe04453b61777e4d67110485ceca69f30d6d1a?response-content-disposition=attachm
######################################################################## 100.0%
==> Downloading https://homebrew.bintray.com/bottles/mpdecimal-2.5.1.big_sur.bottle.tar.gz
==> Downloading from https://d29vzk4ow07wi7.cloudfront.net/255b6226cdcfaf0d40167012593e863e73dfed2884c10e7fc3eb4018e81712df?response-content-disposition=attachm
######################################################################## 100.0%
==> Downloading https://homebrew.bintray.com/bottles/openssl%401.1-1.1.1k.big_sur.bottle.tar.gz
==> Downloading from https://d29vzk4ow07wi7.cloudfront.net/17d94c51ddfa8364baed5f3a754063e1ca75f807194f68d0b976619cf4e69c1a?response-content-disposition=attachm
######################################################################## 100.0%
==> Downloading https://homebrew.bintray.com/bottles/readline-8.1.big_sur.bottle.tar.gz
==> Downloading from https://d29vzk4ow07wi7.cloudfront.net/2cc3a9582e3c7e21eb3c2c8964abd33e9720fb4a9588c626d8424ff8cc9b1aed?response-content-disposition=attachm
######################################################################## 100.0%
==> Downloading https://homebrew.bintray.com/bottles/sqlite-3.35.4.big_sur.bottle.tar.gz
==> Downloading from https://d29vzk4ow07wi7.cloudfront.net/861dc044ea531c39a2105010107feb95cf10977c3da94a4c4fce6aa1b3041c34?response-content-disposition=attachm
######################################################################## 100.0%
==> Downloading https://homebrew.bintray.com/bottles/xz-5.2.5.big_sur.bottle.tar.gz
==> Downloading from https://d29vzk4ow07wi7.cloudfront.net/4fbd4a9e3eb49c27e83bd125b0e76d386c0e12ae1139d4dc9e31841fb8880a35?response-content-disposition=attachm
######################################################################## 100.0%
==> Downloading https://homebrew.bintray.com/bottles/python%403.9-3.9.4.big_sur.bottle.tar.gz
==> Downloading from https://d29vzk4ow07wi7.cloudfront.net/77ba90d10acfc70e57781aae7b8f48799bc4d521422c74fe723cb2d6f5850c5c?response-content-disposition=attachm
######################################################################## 100.0%
==> Installing dependencies for python@3.9: gdbm, mpdecimal, openssl@1.1, readline, sqlite and xz
==> Installing python@3.9 dependency: gdbm
==> Pouring gdbm-1.19.big_sur.bottle.tar.gz
🍺  /usr/local/Cellar/gdbm/1.19: 24 files, 791.3KB
==> Installing python@3.9 dependency: mpdecimal
==> Pouring mpdecimal-2.5.1.big_sur.bottle.tar.gz
🍺  /usr/local/Cellar/mpdecimal/2.5.1: 71 files, 2.1MB
==> Installing python@3.9 dependency: openssl@1.1
==> Pouring openssl@1.1-1.1.1k.big_sur.bottle.tar.gz
==> Regenerating CA certificate bundle from keychain, this may take a while...
Warning: The post-install step did not complete successfully
You can try again using:
  brew postinstall openssl@1.1
==> Caveats
A CA file has been bootstrapped using certificates from the system
keychain. To add additional certificates, place .pem files in
  /usr/local/etc/openssl@1.1/certs

and run
  /usr/local/opt/openssl@1.1/bin/c_rehash

openssl@1.1 is keg-only, which means it was not symlinked into /usr/local,
because macOS provides LibreSSL.

If you need to have openssl@1.1 first in your PATH, run:
  echo 'export PATH="/usr/local/opt/openssl@1.1/bin:$PATH"' >> ~/.zshrc

For compilers to find openssl@1.1 you may need to set:
  export LDFLAGS="-L/usr/local/opt/openssl@1.1/lib"
  export CPPFLAGS="-I/usr/local/opt/openssl@1.1/include"

==> Summary
🍺  /usr/local/Cellar/openssl@1.1/1.1.1k: 8,071 files, 18.5MB
...
...
```

### What did you expect to happen?

The openssl@1.1 post-install step should have produced a file `/usr/local/etc/openssl@1.1/cert.pem`, but it did not. Without this file, python's `requests` module doesn't work properly.

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
brew rm openssl@1.1
rm -rf /usr/local/etc/openssl@1.1 # make sure the openssl config is completely gone
brew install openssl@1.1
```

**Comment by SMillerDev** [comment]
What happens if you run `brew postinstall openssl@1.1`?

**Comment by anandb-ripencc** [comment]
It fails again, @SMillerDev 
```
% brew postinstall openssl@1.1
==> Postinstalling openssl@1.1
==> Regenerating CA certificate bundle from keychain, this may take a while...
Warning: The post-install step did not complete successfully
You can try again using:
  brew postinstall openssl@1.1
```

**Comment by MikeMcQuaid** [comment]
@anandb-ripencc Try `brew postinstall --verbose --debug openssl@1.1`

**Comment by anandb-ripencc** [comment]
@MikeMcQuaid 
```
brew postinstall --verbose --debug openssl@1.1
/usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::FormulaLoader): loading /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/openssl@1.1.rb
==> Postinstalling openssl@1.1
/usr/bin/sandbox-exec -f /private/tmp/homebrew20210412-11212-1v30qtv.sb nice ruby -W1 -I $LOAD_PATH -- /usr/local/Homebrew/Library/Homebrew/postinstall.rb /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/openssl@1.1.rb
==> Regenerating CA certificate bundle from keychain, this may take a while...
Warning: The post-install step did not complete successfully
You can try again using:
  brew postinstall openssl@1.1
==> An exception occurred within a child process:
  Errno::EINTR: Interrupted system call @ rb_file_truncate - /private/tmp/20210412-11213-1w28wto

/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/delegate.rb:349:in `truncate'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/delegate.rb:349:in `block in delegating_block'
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/openssl@1.1.rb:149:in `block in macos_post_install'
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/openssl@1.1.rb:146:in `select'
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/openssl@1.1.rb:146:in `macos_post_install'
/usr/local/Homebrew/Library/Homebrew/extend/os/mac/on_os.rb:8:in `on_macos'
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/openssl@1.1.rb:115:in `post_install'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1076:in `block (2 levels) in run_post_install'
/usr/local/Homebrew/Library/Homebrew/formula.rb:918:in `with_logging'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1075:in `block in run_post_install'
/usr/local/Homebrew/Library/Homebrew/utils.rb:558:in `with_env'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1064:in `run_post_install'
/usr/local/Homebrew/Library/Homebrew/postinstall.rb:22:in `<main>'
```

**Comment by carlocab** [comment]
Can you try making this change, then do `brew postinstall --verbose --debug openssl@1.1` again:

```diff
diff --git a/Formula/openssl@1.1.rb b/Formula/openssl@1.1.rb
index 6c28462112c..986213c79f4 100644
--- a/Formula/openssl@1.1.rb
+++ b/Formula/openssl@1.1.rb
@@ -131,7 +131,7 @@ class OpensslAT11 < Formula
 
     # Check that the certificate has not expired
     valid_certs = certs.select do |cert|
-      IO.popen("#{bin}/openssl x509 -inform pem -checkend 0 -noout &>/dev/null", "w") do |openssl_io|
+      IO.popen("#{bin}/openssl x509 -inform pem -checkend 0 -noout", "w") do |openssl_io|
         openssl_io.write(cert)
         openssl_io.close_write
       end
@@ -148,7 +148,7 @@ class OpensslAT11 < Formula
         tmpfile.write cert
         tmpfile.truncate cert.size
         tmpfile.flush
-        IO.popen("/usr/bin/security verify-cert -l -L -R offline -c #{tmpfile.path} &>/dev/null")
+        IO.popen("/usr/bin/security verify-cert -l -L -R offline -c #{tmpfile.path}")
 
         $CHILD_STATUS.success?
       end
```

**Comment by anandb-ripencc** [comment]
@carlocab here:
```
brew postinstall --verbose --debug openssl@1.1
/usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::FormulaLoader): loading /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/openssl@1.1.rb
==> Postinstalling openssl@1.1
/usr/bin/sandbox-exec -f /private/tmp/homebrew20210412-13273-1rdynvd.sb nice ruby -W1 -I $LOAD_PATH -- /usr/local/Homebrew/Library/Homebrew/postinstall.rb /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/openssl@1.1.rb
==> Regenerating CA certificate bundle from keychain, this may take a while...
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will expire
Certificate will not expire
Certificate will expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
Certificate will not expire
readFile: short read
readFile: short read
SecCertificateCreateFromData: Unknown format in import.
Warning: The post-install step did not complete successfully
You can try again using:
  brew postinstall openssl@1.1
==> An exception occurred within a child process:
  Errno::EINTR: Interrupted system call @ rb_file_truncate - /private/tmp/20210412-13274-ebl5sx

/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/delegate.rb:349:in `truncate'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/delegate.rb:349:in `block in delegating_block'
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/openssl@1.1.rb:149:in `block in macos_post_install'
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/openssl@1.1.rb:146:in `select'
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/openssl@1.1.rb:146:in `macos_post_install'
/usr/local/Homebrew/Library/Homebrew/extend/os/mac/on_os.rb:8:in `on_macos'
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/openssl@1.1.rb:115:in `post_install'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1076:in `block (2 levels) in run_post_install'
/usr/local/Homebrew/Library/Homebrew/formula.rb:918:in `with_logging'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1075:in `block in run_post_install'
/usr/local/Homebrew/Library/Homebrew/utils.rb:558:in `with_env'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1064:in `run_post_install'
/usr/local/Homebrew/Library/Homebrew/postinstall.rb:22:in `<main>'
```

**Comment by Bo98** [comment]
> Interrupted system call @ rb_file_truncate

This sounds like something external to Homebrew. Do you have security software that might be interfering?

**Comment by anandb-ripencc** [comment]
This is a company-provided laptop, running a security application called SentinelOne. It *could* be interfering, but I'm not sure.

**Comment by carlocab** [comment]
It might be interfering. Try setting `HOMEBREW_TEMP` to an empty directory in your `HOME` directory.

**Comment by MikeMcQuaid** [comment]
> running a security application called SentinelOne. It _could_ be interfering, but I'm not sure.

This seems likely. Happy to reopen if it's demonstrated this isn't the case.
