### ISSUE TITLE
Cannot Run Any Brew Commands

### ISSUE THREAD

**Issue by scolby33** [Homebrew/homebrew-core#75071]
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

```shell
$ brew config
Traceback (most recent call last):
        3: from /usr/local/Homebrew/Library/Homebrew/brew.rb:31:in `<main>'
        2: from /usr/local/Homebrew/Library/Homebrew/brew.rb:31:in `require_relative'
        1: from /usr/local/Homebrew/Library/Homebrew/global.rb:22:in `<top (required)>'
/usr/local/Homebrew/Library/Homebrew/global.rb:22:in `require': cannot load such file -- active_support/core_ext/object/blank (LoadError)
```

```shell
$ brew doctor
Traceback (most recent call last):
        3: from /usr/local/Homebrew/Library/Homebrew/brew.rb:31:in `<main>'
        2: from /usr/local/Homebrew/Library/Homebrew/brew.rb:31:in `require_relative'
        1: from /usr/local/Homebrew/Library/Homebrew/global.rb:22:in `<top (required)>'
/usr/local/Homebrew/Library/Homebrew/global.rb:22:in `require': cannot load such file -- active_support/core_ext/object/blank (LoadError)
```

The `brew doctor` above contains no "Warning" lines.

### What were you trying to do (and why)?

Trying to run `brew update`, in order to update brew.

### What happened (include all command output)?

```shell
$ brew update
Traceback (most recent call last):
        3: from /usr/local/Homebrew/Library/Homebrew/brew.rb:31:in `<main>'
        2: from /usr/local/Homebrew/Library/Homebrew/brew.rb:31:in `require_relative'
        1: from /usr/local/Homebrew/Library/Homebrew/global.rb:22:in `<top (required)>'
/usr/local/Homebrew/Library/Homebrew/global.rb:22:in `require': cannot load such file -- active_support/core_ext/object/blank (LoadError)
```

### What did you expect to happen?

That the command worked.

### Step-by-step reproduction instructions (by running `brew` commands)

This happens every time I run any brew command, but I do not know how it got in to this state.

**Comment by SMillerDev** [comment]
Try brew update-reset.

**Comment by scolby33** [comment]
That did it; thank you!
