### ISSUE TITLE
`brew upgrade` fails ; followed with `brew install node` fails

### ISSUE THREAD

**Issue by krstp** [Homebrew/homebrew-core#75983]
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

```shell
`brew config` output:


HOMEBREW_VERSION: 3.1.3-107-g1157a97
ORIGIN: https://github.com/Homebrew/brew
HEAD: 1157a97d8be039db16e1c0bff5a48d372696c5a9
Last commit: 2 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 1da7ce26f5cfa33eec131571755152680a5321b7
Core tap last commit: 40 minutes ago
Core tap branch: master
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CASK_OPTS: []
HOMEBREW_DISPLAY: /private/tmp/com.apple.launchd.Fh9Ku4KM3H/org.macosforge.xquartz:0
HOMEBREW_MAKE_JOBS: 12
Homebrew Ruby: 2.6.3 => /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3_2/bin/ruby
CPU: dodeca-core 64-bit kabylake
Clang: 12.0 build 1200
Git: 2.26.0 => /usr/local/bin/git
Curl: 7.64.1 => /usr/bin/curl
macOS: 10.15.7-x86_64
CLT: 12.0.0.32.29
Xcode: 12.4
XQuartz: 2.7.11 => /opt/X11
```

`brew doctor` output:

```
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: "config" scripts exist outside your system or Homebrew directories.
`./configure` scripts often look for *-config scripts to determine if
software packages are installed, and which additional flags to use when
compiling and linking.

Having additional scripts in your path can confuse software installed via
Homebrew if the config script overrides a system or Homebrew-provided
script of the same name. We found the following "config" scripts:
  /Users/<user>/.pyenv/shims/python3.9-config
  /Users/<user>/.pyenv/shims/python-config
  /Users/<user>/.pyenv/shims/python3-config
  /Users/<user>/.pyenv/shims/python3.8-config

Warning: Some installed formulae are missing dependencies.
You should `brew install` the missing dependencies:
  brew install node

Run `brew missing` for more details.
```

`brew install node` output:

```
==> Downloading https://ghcr.io/v2/homebrew/core/icu4c/manifests/69.1
Already downloaded: /Users/<user>/Library/Caches/Homebrew/downloads/319330d53dab436f7e6bbe478539f29d41abb6be79788b06615f28006a82b30c--icu4c-69.1.bottle_manifest.json
==> Downloading https://ghcr.io/v2/homebrew/core/icu4c/blobs/sha256:3f75c907dadc6e7e647920506e740a312e56279369f3c9708cac54b018410120
Already downloaded: /Users/<user>/Library/Caches/Homebrew/downloads/ae98a35ec0a62dc76f69a11ae87dd39d0c2bf6fef79f3b1a4ad8ebcebfddd341--icu4c--69.1.catalina.bottle.tar.gz
==> Downloading https://ghcr.io/v2/homebrew/core/libuv/manifests/1.41.0
Already downloaded: /Users/<user>/Library/Caches/Homebrew/downloads/399b39fa778414eed23b02399bf6230322d2e035cbbfab23a14c5ed5c1f8350d--libuv-1.41.0.bottle_manifest.json
==> Downloading https://ghcr.io/v2/homebrew/core/libuv/blobs/sha256:fec3670ca2dcbe641c1351c806fa3f66f7e7054dc4d42c683d80c0dcfddf0131
Already downloaded: /Users/<user>/Library/Caches/Homebrew/downloads/dc8879e164d9e17fdbc6c82c67aeed4a7d1acbd13407b3b8bdc98e08ede998f7--libuv--1.41.0.catalina.bottle.tar.gz
==> Downloading https://ghcr.io/v2/homebrew/core/node/manifests/16.0.0_1
Already downloaded: /Users/<user>/Library/Caches/Homebrew/downloads/5bfe6a6d2a865eb4f6d9450c869aecc4596d61d83cb2456d8f76b2b80ea7a4ed--node-16.0.0_1.bottle_manifest.json
==> Downloading https://ghcr.io/v2/homebrew/core/node/blobs/sha256:f2529dfd77086b031a469b4c910ca70feba5e3d6947ca387dedd8fc69cb30da2
Already downloaded: /Users/<user>/Library/Caches/Homebrew/downloads/f43764a60c9a3ba55074c0b57c5816cd86b040b8b55518581768932bb3e37ab2--node--16.0.0_1.catalina.bottle.tar.gz
==> Installing dependencies for node: icu4c and libuv
==> Installing node dependency: icu4c
==> Pouring icu4c--69.1.catalina.bottle.tar.gz
Error: Couldn't parse manifest JSON.
Please report this issue:
  https://docs.brew.sh/Troubleshooting
/usr/local/Homebrew/Library/Homebrew/software_spec.rb:367:in `rescue in tab_attributes'
/usr/local/Homebrew/Library/Homebrew/software_spec.rb:364:in `tab_attributes'
/usr/local/Homebrew/Library/Homebrew/formula.rb:2251:in `bottle_tab_attributes'
/usr/local/Homebrew/Library/Homebrew/formula_installer.rb:1142:in `pour'
/usr/local/Homebrew/Library/Homebrew/formula_installer.rb:418:in `install'
/usr/local/Homebrew/Library/Homebrew/formula_installer.rb:741:in `install_dependency'
/usr/local/Homebrew/Library/Homebrew/formula_installer.rb:661:in `block in install_dependencies'
/usr/local/Homebrew/Library/Homebrew/formula_installer.rb:661:in `each'
/usr/local/Homebrew/Library/Homebrew/formula_installer.rb:661:in `install_dependencies'
/usr/local/Homebrew/Library/Homebrew/formula_installer.rb:389:in `install'
/usr/local/Homebrew/Library/Homebrew/cmd/install.rb:422:in `install_formula'
/usr/local/Homebrew/Library/Homebrew/cmd/install.rb:324:in `block in install'
/usr/local/Homebrew/Library/Homebrew/cmd/install.rb:322:in `each'
/usr/local/Homebrew/Library/Homebrew/cmd/install.rb:322:in `install'
/usr/local/Homebrew/Library/Homebrew/brew.rb:122:in `<main>'
```

root core issue `brew upgrade` output:

```
==> Upgrading 52 outdated packages:
libtiff 4.2.0 -> 4.3.0
jansson 2.12 -> 2.13.1
libhandy 1.2.0 -> 1.2.1
adwaita-icon-theme 3.38.0 -> 40.0
libksba 1.5.0 -> 1.5.1
logcli 2.1.0 -> 2.2.1
go 1.15.7_1 -> 1.16.3
azure-cli 2.21.0 -> 2.22.1
gh 0.12.0 -> 1.9.2
ghostscript 9.51 -> 9.53.3_1
gtk+3 3.24.28 -> 3.24.29
grpc 1.36.4_1 -> 1.36.4_2
nifi 1.13.0 -> 1.13.2
highlight 3.56 -> 4.0
boost 1.75.0_2 -> 1.75.0_3
gdk-pixbuf 2.42.4 -> 2.42.6
icu4c 68.2 -> 69.1
harfbuzz 2.8.0 -> 2.8.0_1
zsh-completions 0.30.0 -> 0.32.0
just 0.8.3 -> 0.9.1
llvm 10.0.1_1 -> 12.0.0
qt 5.15.2 -> 6.0.3_2
afl-fuzz 2.56 -> 2.57b_1
nvm 0.37.2 -> 0.38.0
lua 5.4.2 -> 5.4.3
libgcrypt 1.9.2 -> 1.9.3
htop 2.2.0_1 -> 3.0.5
radare2 5.0.0 -> 5.2.0
golangci-lint 1.36.0 -> 1.39.0
bpytop 1.0.63 -> 1.0.64
kafka 2.7.0 -> 2.8.0
librsvg 2.50.3 -> 2.50.4
zstd 1.4.9 -> 1.4.9_1
libopenmpt 0.5.7 -> 0.5.8
sbt 1.4.9 -> 1.5.1
derailed/k9s/k9s 0.21.2 -> 0.24.7
gd 2.3.1 -> 2.3.2
pcre2 10.34 -> 10.36
romkatv/powerlevel10k/powerlevel10k 1.13.0 -> 1.14.6
bat 0.15.0 -> 0.18.0
x264 r3048 -> r3049
kubernetes-cli 1.20.2 -> 1.21.0
libomp 10.0.0 -> 12.0.0
zsh 5.8 -> 5.8_1
gnupg 2.2.27 -> 2.3.1
openjdk@8 1.8.0+265 -> 1.8.0+282
bison 3.5.4 -> 3.7.6
hashcat 5.1.0 -> 6.1.1
protobuf 3.15.7 -> 3.15.8
automake 1.16.2 -> 1.16.3_1
abseil 20210324.0 -> 20210324.1
git 2.26.0 -> 2.31.1
==> Upgrading llvm 10.0.1_1 -> 12.0.0
==> Downloading https://ghcr.io/v2/homebrew/core/llvm/manifests/12.0.0
Already downloaded: /Users/<user>/Library/Caches/Homebrew/downloads/0a65e7869ebad0f70e7065d3196809e44835f612905b829b42ce781bb1298e4f--llvm-12.0.0.bottle_manifest.json
==> Downloading https://ghcr.io/v2/homebrew/core/llvm/blobs/sha256:330381b5d4be23e5ec878ed13ba8f96f311078a8be8130fcc6f49e7ef31dc8d5
Already downloaded: /Users/<user>/Library/Caches/Homebrew/downloads/c678947c1a5d6628bfaa35815b3dbd4dd241ab5a85f4fb2e18beaf713afc7a28--llvm--12.0.0.catalina.bottle.tar.gz
==> Pouring llvm--12.0.0.catalina.bottle.tar.gz
Error: Couldn't parse manifest JSON.
Please report this issue:
  https://docs.brew.sh/Troubleshooting
/usr/local/Homebrew/Library/Homebrew/software_spec.rb:367:in `rescue in tab_attributes'
/usr/local/Homebrew/Library/Homebrew/software_spec.rb:364:in `tab_attributes'
/usr/local/Homebrew/Library/Homebrew/formula.rb:2251:in `bottle_tab_attributes'
/usr/local/Homebrew/Library/Homebrew/formula_installer.rb:1142:in `pour'
/usr/local/Homebrew/Library/Homebrew/formula_installer.rb:418:in `install'
/usr/local/Homebrew/Library/Homebrew/upgrade.rb:137:in `upgrade_formula'
/usr/local/Homebrew/Library/Homebrew/upgrade.rb:47:in `block in upgrade_formulae'
/usr/local/Homebrew/Library/Homebrew/upgrade.rb:44:in `each'
/usr/local/Homebrew/Library/Homebrew/upgrade.rb:44:in `upgrade_formulae'
/usr/local/Homebrew/Library/Homebrew/cmd/upgrade.rb:178:in `upgrade_outdated_formulae'
/usr/local/Homebrew/Library/Homebrew/cmd/upgrade.rb:106:in `upgrade'
/usr/local/Homebrew/Library/Homebrew/brew.rb:122:in `<main>'
```
```


### 

- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.

### What were you trying to do (and why)?

initially I tried to run `brew upgrade`

### What happened (include all command output)?

```
==> Upgrading 52 outdated packages:
libtiff 4.2.0 -> 4.3.0
jansson 2.12 -> 2.13.1
libhandy 1.2.0 -> 1.2.1
adwaita-icon-theme 3.38.0 -> 40.0
libksba 1.5.0 -> 1.5.1
logcli 2.1.0 -> 2.2.1
go 1.15.7_1 -> 1.16.3
azure-cli 2.21.0 -> 2.22.1
gh 0.12.0 -> 1.9.2
ghostscript 9.51 -> 9.53.3_1
gtk+3 3.24.28 -> 3.24.29
grpc 1.36.4_1 -> 1.36.4_2
nifi 1.13.0 -> 1.13.2
highlight 3.56 -> 4.0
boost 1.75.0_2 -> 1.75.0_3
gdk-pixbuf 2.42.4 -> 2.42.6
icu4c 68.2 -> 69.1
harfbuzz 2.8.0 -> 2.8.0_1
zsh-completions 0.30.0 -> 0.32.0
just 0.8.3 -> 0.9.1
llvm 10.0.1_1 -> 12.0.0
qt 5.15.2 -> 6.0.3_2
afl-fuzz 2.56 -> 2.57b_1
nvm 0.37.2 -> 0.38.0
lua 5.4.2 -> 5.4.3
libgcrypt 1.9.2 -> 1.9.3
htop 2.2.0_1 -> 3.0.5
radare2 5.0.0 -> 5.2.0
golangci-lint 1.36.0 -> 1.39.0
bpytop 1.0.63 -> 1.0.64
kafka 2.7.0 -> 2.8.0
librsvg 2.50.3 -> 2.50.4
zstd 1.4.9 -> 1.4.9_1
libopenmpt 0.5.7 -> 0.5.8
sbt 1.4.9 -> 1.5.1
derailed/k9s/k9s 0.21.2 -> 0.24.7
gd 2.3.1 -> 2.3.2
pcre2 10.34 -> 10.36
romkatv/powerlevel10k/powerlevel10k 1.13.0 -> 1.14.6
bat 0.15.0 -> 0.18.0
x264 r3048 -> r3049
kubernetes-cli 1.20.2 -> 1.21.0
libomp 10.0.0 -> 12.0.0
zsh 5.8 -> 5.8_1
gnupg 2.2.27 -> 2.3.1
openjdk@8 1.8.0+265 -> 1.8.0+282
bison 3.5.4 -> 3.7.6
hashcat 5.1.0 -> 6.1.1
protobuf 3.15.7 -> 3.15.8
automake 1.16.2 -> 1.16.3_1
abseil 20210324.0 -> 20210324.1
git 2.26.0 -> 2.31.1
==> Upgrading llvm 10.0.1_1 -> 12.0.0
==> Downloading https://ghcr.io/v2/homebrew/core/llvm/manifests/12.0.0
Already downloaded: /Users/<user>/Library/Caches/Homebrew/downloads/0a65e7869ebad0f70e7065d3196809e44835f612905b829b42ce781bb1298e4f--llvm-12.0.0.bottle_manifest.json
==> Downloading https://ghcr.io/v2/homebrew/core/llvm/blobs/sha256:330381b5d4be23e5ec878ed13ba8f96f311078a8be8130fcc6f49e7ef31dc8d5
Already downloaded: /Users/<user>/Library/Caches/Homebrew/downloads/c678947c1a5d6628bfaa35815b3dbd4dd241ab5a85f4fb2e18beaf713afc7a28--llvm--12.0.0.catalina.bottle.tar.gz
==> Pouring llvm--12.0.0.catalina.bottle.tar.gz
Error: Couldn't parse manifest JSON.
Please report this issue:
  https://docs.brew.sh/Troubleshooting
/usr/local/Homebrew/Library/Homebrew/software_spec.rb:367:in `rescue in tab_attributes'
/usr/local/Homebrew/Library/Homebrew/software_spec.rb:364:in `tab_attributes'
/usr/local/Homebrew/Library/Homebrew/formula.rb:2251:in `bottle_tab_attributes'
/usr/local/Homebrew/Library/Homebrew/formula_installer.rb:1142:in `pour'
/usr/local/Homebrew/Library/Homebrew/formula_installer.rb:418:in `install'
/usr/local/Homebrew/Library/Homebrew/upgrade.rb:137:in `upgrade_formula'
/usr/local/Homebrew/Library/Homebrew/upgrade.rb:47:in `block in upgrade_formulae'
/usr/local/Homebrew/Library/Homebrew/upgrade.rb:44:in `each'
/usr/local/Homebrew/Library/Homebrew/upgrade.rb:44:in `upgrade_formulae'
/usr/local/Homebrew/Library/Homebrew/cmd/upgrade.rb:178:in `upgrade_outdated_formulae'
/usr/local/Homebrew/Library/Homebrew/cmd/upgrade.rb:106:in `upgrade'
/usr/local/Homebrew/Library/Homebrew/brew.rb:122:in `<main>'
```

### What did you expect to happen?

brew to upgrade

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
listed above; first fix and resolve any of the `brew doctor` issues, however, `node` reinstall will result in the same error; also I do not want to modify my `pyenv` configs, which will most likely affect and destroy existing configs that used to work for however-long-period-of-time.
```

**Comment by Bo98** [comment]
What's the contents of `~/Library/Caches/Homebrew/downloads/0a65e7869ebad0f70e7065d3196809e44835f612905b829b42ce781bb1298e4f--llvm-12.0.0.bottle_manifest.json`? Sounds like it might have corrupted while downloading?

**Comment by carlocab** [comment]
Your manifest download was likely intercepted (probably my a firewall or similar). See https://github.com/Homebrew/homebrew-core/issues/75997#issuecomment-827289299.
