### ISSUE TITLE
sqlite 3.35.4 fails to install on MacOS 10.15.7

### ISSUE THREAD

**Issue by ethnhll** [Homebrew/homebrew-core#75997]
`brew config` AND `brew doctor` output

```shell
➜  ~ brew config
HOMEBREW_VERSION: 3.1.3
ORIGIN: https://github.com/Homebrew/brew
HEAD: d89eda09abbeae907eb88bd6d01dc9cde7ff0e19
Last commit: 7 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: e4789405e71db54991439dfac0f3988acb4c65dc
Core tap last commit: 33 minutes ago
Core tap branch: master
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CASK_OPTS: []
HOMEBREW_EDITOR: vim
HOMEBREW_MAKE_JOBS: 12
Homebrew Ruby: 2.6.3 => /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3_2/bin/ruby
CPU: dodeca-core 64-bit kabylake
Clang: 12.0 build 1200
Git: 2.24.3 => /Library/Developer/CommandLineTools/usr/bin/git
Curl: 7.64.1 => /usr/bin/curl
macOS: 10.15.7-x86_64
CLT: 12.0.0.32.29
Xcode: N/A
➜  ~ brew doctor
Your system is ready to brew.
```

### 

- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.

### What were you trying to do (and why)?

`brew install sqlite`

sqlite is required for several other formulae, `vim` or `awscli`

### What happened (include all command output)?

```zsh
➜  ~ brew install sqlite
==> Downloading https://ghcr.io/v2/homebrew/core/sqlite/manifests/3.35.4
Already downloaded: /Users/e0x3q3x/Library/Caches/Homebrew/downloads/7a6e666475f4a2738f8ddb6d3f9f6617c45a4c3e77cbb8c229649dbb9e104240--sqlite-3.35.4.bottle_manifest.json
==> Downloading https://ghcr.io/v2/homebrew/core/sqlite/blobs/sha256:a1aee82c8dec9baf0073f52d89ecc2ec3003a49afaa4180315ebf533e08a152b
Already downloaded: /Users/e0x3q3x/Library/Caches/Homebrew/downloads/dbca105cdc48c760bf2ae64dc3abecc5a1486abd9fa77671ddf663ae7ea8aecc--sqlite--3.35.4.catalina.bottle.tar.gz
==> Pouring sqlite--3.35.4.catalina.bottle.tar.gz
Error: Couldn't parse manifest JSON.
Please report this issue:
  https://docs.brew.sh/Troubleshooting
/usr/local/Homebrew/Library/Homebrew/software_spec.rb:367:in `rescue in tab_attributes'
/usr/local/Homebrew/Library/Homebrew/software_spec.rb:364:in `tab_attributes'
/usr/local/Homebrew/Library/Homebrew/formula.rb:2251:in `bottle_tab_attributes'
/usr/local/Homebrew/Library/Homebrew/formula_installer.rb:1142:in `pour'
/usr/local/Homebrew/Library/Homebrew/formula_installer.rb:418:in `install'
/usr/local/Homebrew/Library/Homebrew/cmd/install.rb:422:in `install_formula'
/usr/local/Homebrew/Library/Homebrew/cmd/install.rb:324:in `block in install'
/usr/local/Homebrew/Library/Homebrew/cmd/install.rb:322:in `each'
/usr/local/Homebrew/Library/Homebrew/cmd/install.rb:322:in `install'
/usr/local/Homebrew/Library/Homebrew/brew.rb:122:in `<main>'
```

### What did you expect to happen?

sqlite install should succeed

### Step-by-step reproduction instructions (by running `brew` commands)

```zsh
brew install sqlite
```

**Comment by carlocab** [comment]
Looks like a duplicate of #75983. What's the output of
```
file /Users/e0x3q3x/Library/Caches/Homebrew/downloads/7a6e666475f4a2738f8ddb6d3f9f6617c45a4c3e77cbb8c229649dbb9e104240--sqlite-3.35.4.bottle_manifest.json
```
?

**Comment by ethnhll** [comment]
```zsh
➜  ~ file /Users/e0x3q3x/Library/Caches/Homebrew/downloads/7a6e666475f4a2738f8ddb6d3f9f6617c45a4c3e77cbb8c229649dbb9e104240--sqlite-3.35.4.bottle_manifest.json
/Users/e0x3q3x/Library/Caches/Homebrew/downloads/7a6e666475f4a2738f8ddb6d3f9f6617c45a4c3e77cbb8c229649dbb9e104240--sqlite-3.35.4.bottle_manifest.json: data
```

**Comment by carlocab** [comment]
Do you have `jq` installed? If you do, what's the output of
```
jq '.' </Users/e0x3q3x/Library/Caches/Homebrew/downloads/7a6e666475f4a2738f8ddb6d3f9f6617c45a4c3e77cbb8c229649dbb9e104240--sqlite-3.35.4.bottle_manifest.json
```
?

If you don't have `jq`, try
```
cat /Users/e0x3q3x/Library/Caches/Homebrew/downloads/7a6e666475f4a2738f8ddb6d3f9f6617c45a4c3e77cbb8c229649dbb9e104240--sqlite-3.35.4.bottle_manifest.json
```

**Comment by ethnhll** [comment]
Using `jq`...

```zsh
➜  ~ jq '.' </Users/e0x3q3x/Library/Caches/Homebrew/downloads/7a6e666475f4a2738f8ddb6d3f9f6617c45a4c3e77cbb8c229649dbb9e104240--sqlite-3.35.4.bottle_manifest.json
parse error: Invalid numeric literal at line 1, column 10
```

Looking at the file contents, I am actually seeing that the file is not JSON at all and is in fact some security flagged HTML page from my company's firewall.... 💯 Seems that I made the mistake of trying to update my software while on a company VPN connection.

clearing the cache with `brew cleanup --prune=all` and then `brew install sqlite` did the trick (I just pruned everything because I don't know which downloaded files have been "corrupted").

Install proceeds like normal after that... 
```zsh
➜  ~ brew install sqlite                                                                                                                                          
Updating Homebrew...
==> Downloading https://ghcr.io/v2/homebrew/core/sqlite/manifests/3.35.4
######################################################################## 100.0%
==> Downloading https://ghcr.io/v2/homebrew/core/sqlite/blobs/sha256:a1aee82c8dec9baf0073f52d89ecc2ec3003a49afaa4180315ebf533e08a152b
==> Downloading from https://pkg-containers-az.githubusercontent.com/ghcr1/blobs/sha256:a1aee82c8dec9baf0073f52d89ecc2ec3003a49afaa4180315ebf533e08a152b?se=2021-04-27T03%3A40%3A00Z&sig=kk7iHLe5MAWy1HdK%
######################################################################## 100.0%
==> Pouring sqlite--3.35.4.catalina.bottle.tar.gz
==> Caveats
sqlite is keg-only, which means it was not symlinked into /usr/local,
because macOS already provides this software and installing another version in
parallel can cause all kinds of trouble.

If you need to have sqlite first in your PATH, run:
  echo 'export PATH="/usr/local/opt/sqlite/bin:$PATH"' >> ~/.zshrc

For compilers to find sqlite you may need to set:
  export LDFLAGS="-L/usr/local/opt/sqlite/lib"
  export CPPFLAGS="-I/usr/local/opt/sqlite/include"

==> Summary
🍺  /usr/local/Cellar/sqlite/3.35.4: 11 files, 4.2MB
```

My apologies for the time sink and thanks for checking in so quickly, I'll close this issue.

**Comment by carlocab** [comment]
Great; glad that's resolved.
