### ISSUE TITLE
jupyter lab exits with "'ExtensionManager' object has no attribute '_extensions'" error after upgrading to jupyterlab 3.0.15

### ISSUE THREAD

**Issue by densmorejeff** [Homebrew/homebrew-core#77067]
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

```shell
brew gist-logs jupyterlab:
Error: No logs.

brew config:
HOMEBREW_VERSION: 3.1.6
ORIGIN: https://github.com/Homebrew/brew
HEAD: 734defb1a956487f82f28b6ac107727746ee3635
Last commit: 35 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 8752fa5a61b70bb0babee66da918bacb6c8c3c55
Core tap last commit: 80 minutes ago
Core tap branch: master
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CASK_OPTS: []
HOMEBREW_DISPLAY: /private/tmp/com.apple.launchd.7jkMV17Wbm/org.xquartz:0
HOMEBREW_MAKE_JOBS: 4
Homebrew Ruby: 2.6.3 => /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3_2/bin/ruby
CPU: quad-core 64-bit kabylake
Clang: 12.0.0 build 1200
Git: 2.24.3 => /Applications/Xcode.app/Contents/Developer/usr/bin/git
Curl: 7.64.1 => /usr/bin/curl
macOS: 10.15.7-x86_64
CLT: 12.4.0.0.1.1610135815
Xcode: 12.4

brew doctor:
Your system is ready to brew.
```

### 

- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.

### What were you trying to do (and why)?

Run jupyter lab after jupterlab forumla was upgraded to 3.0.15

### What happened (include all command output)?

jupyter lab:
[I 2021-05-11 20:31:48.890 ServerApp] jupyterlab | extension was successfully linked.
[W 2021-05-11 20:31:49.079 ServerApp] 'ExtensionManager' object has no attribute '_extensions'
Traceback (most recent call last):
  File "/usr/local/Cellar/jupyterlab/3.0.15/libexec/bin/jupyter-lab", line 8, in <module>
    sys.exit(main())
  File "/usr/local/Cellar/jupyterlab/3.0.15/libexec/lib/python3.9/site-packages/jupyter_server/extension/application.py", line 518, in launch_instance
    serverapp = cls.initialize_server(argv=args)
  File "/usr/local/Cellar/jupyterlab/3.0.15/libexec/lib/python3.9/site-packages/jupyter_server/extension/application.py", line 488, in initialize_server
    serverapp.initialize(
  File "/usr/local/Cellar/jupyterlab/3.0.15/libexec/lib/python3.9/site-packages/traitlets/config/application.py", line 87, in inner
    return method(app, *args, **kwargs)
  File "/usr/local/Cellar/jupyterlab/3.0.15/libexec/lib/python3.9/site-packages/jupyter_server/serverapp.py", line 1855, in initialize
    point = self.extension_manager.extension_points[starter_extension]
  File "/usr/local/Cellar/jupyterlab/3.0.15/libexec/lib/python3.9/site-packages/jupyter_server/extension/manager.py", line 290, in extension_points
    extensions = self.extensions
  File "/usr/local/Cellar/jupyterlab/3.0.15/libexec/lib/python3.9/site-packages/nbclassic/nbserver.py", line 80, in extensions
    nb = self._extensions.get("nbclassic")
AttributeError: 'ExtensionManager' object has no attribute '_extensions'

### What did you expect to happen?

Jupyter lab to open in browser.

Note jupyter notebook works fine.

I realize this may be a problem upstream, but I thought I would start here first.

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
brew update
brew upgrade
jupyter lab
```

**Comment by bayandin** [comment]
It looks like an upstream issue and could be fixed by updating resources (in particular `nbclassic` to 0.2.8 which has https://github.com/jupyterlab/nbclassic/pull/49).
I'll have a look

**Comment by bayandin** [comment]
Should be fixed: `brew update && brew upgrade jupyterlab`

**Comment by densmorejeff** [comment]
Yes, it's fixed locally for me.  Thanks!
