### ISSUE TITLE
Exiftool fails uninstall

### ISSUE THREAD

**Issue by JetForMe** [Homebrew/homebrew-core#7838]
- [ ] Ran `brew update` and retried your prior step?
```
me@machine: ~/ 17:55$ brew update
Updated 1 tap (caskroom/cask).
```
- [ ] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?
```
me@machine: ~/ 17:56$ brew doctor
Error: undefined local variable or method `formula' for #<Formulary::TapLoader:0x007ff1bb9ff4e8>
Please report this bug:
  https://git.io/brew-troubleshooting
/usr/local/Homebrew/Library/Homebrew/formulary.rb:214:in `rescue in load_file'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:212:in `load_file'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:88:in `klass'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:84:in `get_formula'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:206:in `get_formula'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:253:in `factory'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:284:in `from_keg'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:267:in `from_rack'
/usr/local/Homebrew/Library/Homebrew/diagnostic.rb:1010:in `block in check_for_unlinked_but_not_keg_only'
/usr/local/Homebrew/Library/Homebrew/diagnostic.rb:1007:in `reject'
/usr/local/Homebrew/Library/Homebrew/diagnostic.rb:1007:in `check_for_unlinked_but_not_keg_only'
/usr/local/Homebrew/Library/Homebrew/cmd/doctor.rb:43:in `block in doctor'
/usr/local/Homebrew/Library/Homebrew/cmd/doctor.rb:35:in `each'
/usr/local/Homebrew/Library/Homebrew/cmd/doctor.rb:35:in `doctor'
/usr/local/Homebrew/Library/Homebrew/brew.rb:94:in `<main>'
rmann@EclipseSSD: ~/ 17:56$ 
---------------------------------
```

- [ ] Confirmed this is problem with specific formulae and not Homebrew/brew? If it's a general 
Homebrew/brew problem please file this issue at https://github.com/Homebrew/brew/issues/new

Not sure.

### Bug reports:

```
me@machine: ~/ 17:56$ brew config
HOMEBREW_VERSION: 1.1.4
ORIGIN: https://github.com/Homebrew/brew.git
HEAD: 99f42146c06333f820f45ed1940c5487990e2b31
Last commit: 7 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 16c4d6bbdbde636adc836c4826d7b52df894447d
Core tap last commit: 4 hours ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_REPOSITORY: /usr/local/Homebrew
HOMEBREW_CELLAR: /usr/local/Cellar
HOMEBREW_BOTTLE_DOMAIN: https://homebrew.bintray.com
CPU: octa-core 64-bit ivybridge
Homebrew Ruby: 2.0.0-p648
Clang: 8.0 build 800
Git: 2.5.3 => /usr/local/bin/git
Perl: /usr/bin/perl
Python: /usr/local/bin/python => /usr/local/Cellar/python/2.7.10_2/Frameworks/Python.framework/Versions/2.7/bin/python2.7
Ruby: /usr/bin/ruby => /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin/ruby
Java: 1.8.0_45, 1.7.0_17, 1.7.0_09, 1.6.0_65-b14-468
macOS: 10.12.1-x86_64
Xcode: 8.1
CLT: N/A
X11: 2.7.9 => /opt/X11
```

```
me@machine: ~/ 17:57$ brew gist-logs exiftool
Error: No logs.
```

**Comment by jfromaniello** [comment]
I am having the same problem.

**Comment by bfontaine** [comment]
Please run `cd $(brew --repo) && git fetch && git reset --hard origin/master` and try again.

**Comment by JetForMe** [comment]
That fixed it for me, thank you.
