### ISSUE TITLE
Postinstall fails for openssl@1.1 and gnutls formula on Apple Silicon Mac

### ISSUE THREAD

**Issue by brentward** [Homebrew/homebrew-core#79932]
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

```shell
HOMEBREW_VERSION: 3.2.0-43-g47d5150
ORIGIN: https://github.com/Homebrew/brew
HEAD: 47d5150c333784c956db25c3d8ff8ffdd616bb68
Last commit: 21 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: f726665062954d90454a550b7acb808e4cea2184
Core tap last commit: 19 hours ago
Core tap branch: master
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_MAKE_JOBS: 8
Homebrew Ruby: 2.6.3 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: octa-core 64-bit arm_firestorm_icestorm
Clang: 12.0.5 build 1205
Git: 2.30.1 => /Applications/Xcode.app/Contents/Developer/usr/bin/git
Curl: 7.64.1 => /usr/bin/curl
macOS: 11.4-arm64
CLT: 12.5.0.22.9
Xcode: 12.5.1
Rosetta 2: false

Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: Some installed formulae are deprecated or disabled.
You should find replacements for the following formulae:
  ilmbase

Warning: You have uncommitted modifications to Homebrew/homebrew-core.
If this is a surprise to you, then you should stash these modifications.
Stashing returns Homebrew to a pristine state but can be undone
should you later need to do so for some reason.
  cd /opt/homebrew/Library/Taps/homebrew/homebrew-core && git stash && git clean -d -f

Uncommitted files:
   M Formula/gnutls.rb
   M Formula/openssl@1.1.rb
  ?? Formula/.openssl@1.1.rb.swp

Warning: Homebrew's "bin" was not found in your PATH.
Consider setting your PATH for example like so:
  echo 'export PATH="/opt/homebrew/bin:$PATH"' >> ~/.zshrc

Warning: Homebrew's "sbin" was not found in your PATH but you have installed
formulae that put executables in /opt/homebrew/sbin.
Consider setting your PATH for example like so:
  echo 'export PATH="/opt/homebrew/sbin:$PATH"' >> ~/.zshrc
```

### 

- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.

### What were you trying to do (and why)?

When I try to install openssl or gnutls I get postinstall errors. I previously opened a ticket on this and it was closed because they could not reproduce it.

However I have now determined what is happening and how to fix it. My path isn't getting passed into the sandbox session so the security cli tool needs the full path specified. I have a pull request to address this forthcoming.

https://github.com/Homebrew/brew/issues/10181

On Apple Silicon Mac when brew installed openssl@1.1 and gnutls as dependencies for pyenv and gpg respectively I got warnings:

==> Installing pyenv dependency: openssl@1.1
==> Pouring openssl@1.1-1.1.1i.arm64_big_sur.bottle.tar.gz
Warning: The post-install step did not complete successfully
You can try again using `brew postinstall openssl@1.1`
and

==> Installing gnupg dependency: gnutls
==> Pouring gnutls-3.6.15.arm64_big_sur.bottle.tar.gz
Warning: The post-install step did not complete successfully
You can try again using `brew postinstall gnutls`
respectively. So I attempted the postinstall commands as instructed

### What happened (include all command output)?

Command output of: brew postinstall openssl@1.1
```
❯ brew postinstall openssl@1.1 -dv
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::FormulaLoader): loading /opt/homebrew/Library/Taps/homebrew/homebrew-core/Formula/openssl@1.1.rb
==> Postinstalling openssl@1.1
/usr/bin/sandbox-exec -f /private/tmp/homebrew20201229-26088-ca0bns.sb nice ruby -W0 -I $LOAD_PATH -- /opt/homebrew/Library/Homebrew/postinstall.rb /opt/homebrew/Library/Taps/homebrew/homebrew-core/Formula/openssl@1.1.rb
Warning: The post-install step did not complete successfully
You can try again using `brew postinstall openssl@1.1`
==> An exception occurred within a child process:
 Errno::ENOENT: No such file or directory - security

/opt/homebrew/Library/Taps/homebrew/homebrew-core/Formula/openssl@1.1.rb:124:in ``'
/opt/homebrew/Library/Taps/homebrew/homebrew-core/Formula/openssl@1.1.rb:124:in `macos_post_install'
/opt/homebrew/Library/Homebrew/extend/os/mac/on_os.rb:8:in `on_macos'
/opt/homebrew/Library/Taps/homebrew/homebrew-core/Formula/openssl@1.1.rb:115:in `post_install'
/opt/homebrew/Library/Homebrew/formula.rb:1062:in `block (2 levels) in run_post_install'
/opt/homebrew/Library/Homebrew/formula.rb:904:in `with_logging'
/opt/homebrew/Library/Homebrew/formula.rb:1061:in `block in run_post_install'
/opt/homebrew/Library/Homebrew/utils.rb:530:in `with_env'
/opt/homebrew/Library/Homebrew/formula.rb:1050:in `run_post_install'
/opt/homebrew/Library/Homebrew/postinstall.rb:22:in `<main>'

```
 
Command output of: brew postinstall gnutls
```
❯ brew postinstall gnutls -dv     
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::FormulaLoader): loading /opt/homebrew/Library/Taps/homebrew/homebrew-core/Formula/gnutls.rb
==> Postinstalling gnutls
/usr/bin/sandbox-exec -f /private/tmp/homebrew20201229-26242-1g3cec.sb nice ruby -W0 -I $LOAD_PATH -- /opt/homebrew/Library/Homebrew/postinstall.rb /opt/homebrew/Library/Taps/homebrew/homebrew-core/Formula/gnutls.rb
Warning: The post-install step did not complete successfully
You can try again using `brew postinstall gnutls`
==> An exception occurred within a child process:
  Errno::ENOENT: No such file or directory - security

/opt/homebrew/Library/Taps/homebrew/homebrew-core/Formula/gnutls.rb:73:in ``'
/opt/homebrew/Library/Taps/homebrew/homebrew-core/Formula/gnutls.rb:73:in `post_install'
/opt/homebrew/Library/Homebrew/formula.rb:1062:in `block (2 levels) in run_post_install'
/opt/homebrew/Library/Homebrew/formula.rb:904:in `with_logging'
/opt/homebrew/Library/Homebrew/formula.rb:1061:in `block in run_post_install'
/opt/homebrew/Library/Homebrew/utils.rb:530:in `with_env'
/opt/homebrew/Library/Homebrew/formula.rb:1050:in `run_post_install'
/opt/homebrew/Library/Homebrew/postinstall.rb:22:in `<main>'
```

### What did you expect to happen?

Postintall scripts should have ran without failing due to an exception. Both of them seem to be failing doing the same thing which is it can't find the security command when run in backticks like this: certs_list = `security find-certificate -a -p #{keychains.join(" ")}` 
here: https://github.com/Homebrew/homebrew-core/blob/239ebee1f006dd5dcd658e5603936decc1aea4dc/Formula/openssl%401.1.rb#L124
and here: https://github.com/Homebrew/homebrew-core/blob/239ebee1f006dd5dcd658e5603936decc1aea4dc/Formula/gnutls.rb#L73

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
Reproducable on my machine:
This can be reproduced by executing:

brew install pyenv
brew postinstall openssl@1.1
```
and
```
brew install gpg
brew postinstall gnutls
```
```

**Comment by brentward** [comment]
I have submitted https://github.com/Homebrew/homebrew-core/pull/79933 to address this

**Comment by carlocab** [comment]
I am curious about what is happening to your `PATH` in `post_install`. Can you determine what your `PATH` variable looks like in those post-install blocks?

**Comment by brentward** [comment]
my `PATH` only contains `/opt/homebrew` at that point.
I determined this by adding `puts ENV['PATH']` right before the part where it tries to run `security` and it prints `/opt/homebrew`.

I discovered it does the same thing on my work computer which is configured in a similar way to my home computer but it is Intel instead of Apple Silicon so I'm pretty sure it has something to do with my environment configuration. I moved my configuration files into ~/.config/zsh instead of ~/ so that could be causing it.  My configuration does conform to the specs provided by the ZSH documentation so if brew is expecting to pick up the user's PATH then it must be missing something.

I can go back into my configuration files and figure out exactly how it sets the PATH if that would be helpful.

**Comment by brentward** [comment]
My path is set through the following process:
I have a `~/.zshenv` symlinked to `~/.config/zsh/.zshenv` and contains `export ZDOTDIR=$HOME/.config/zsh`
`~/.config/zsh/.zprofile` contains:
```
typeset -U PATH path
path=(/opt/qemu/bin $path)
path=(
    $HOME/.local/bin
    $HOME/.pyenv/shims
    $HOMEBREW_BIN
    $HOME/.cargo/bin
    $PYENV_BIN
    $HOMEBREW_PATH/sbin
    $path
)
export PATH
```

**Comment by carlocab** [comment]
Your environment shouldn't be affecting what's in your `PATH` in post-install, because of [this snippet](https://github.com/Homebrew/brew/blob/dc2c0ec8cf742b9499b7a765d3a4b44a2e5c3367/bin/brew#L102-L104):
```bash
if [[ -z "${HOMEBREW_NO_ENV_FILTERING}" ]]
then
  PATH="/usr/bin:/bin:/usr/sbin:/sbin"
```
Or do you have `HOMEBREW_NO_ENV_FILTERING` set?

**Comment by brentward** [comment]
I do not have `HOMEBREW_NO_ENV_FILTERING` set.

Do you have any further ideas to troubleshoot my path in the post-install?

**Comment by carlocab** [comment]
What does `echo $path` say for you currently?

**Comment by brentward** [comment]
it says:
```
❯ echo $path        
/Users/brent/.rbenv/shims /opt/homebrew/Cellar/pyenv-virtualenv/1.1.5/shims /opt/homebrew/Caskroom/miniforge/base/bin /opt/homebrew/Caskroom/miniforge/base/condabin /Users/brent/.local/bin /Users/brent/.pyenv/shims /opt/homebrew/bin /Users/brent/.cargo/bin /Users/brent/.pyenv/bin /opt/homebrew/sbin /opt/qemu/bin /usr/local/bin /usr/bin /bin /usr/sbin /sbin /Library/Apple/usr/bin
```

**Comment by brentward** [comment]
I'm trying to track down where the path changes currently. I put echos and puts of the PATH in a bunch of places. It is good through brew.rb and into postinstall.rb and still good at the top of gnutls.rb  where it is `/opt/homebrew/Library/Homebrew/shims/scm:/usr/bin:/bin:/usr/sbin:/sbi` but the puts at the beginning of the post_install function it changes to `/opt/homebrew`.

**Comment by cho-m** [comment]
Does sound like something is off about your environment.

On M1 mac here with a similar XDG-style `~/.zshenv` + `~/.config/zsh/` setup (though I personally run `eval $(/opt/homebrew/bin/brew shellenv)`), I have my path upon entering post_install and don't see any issue.

Maybe there is something wrong with `HOMEBREW_PATH` variable when setting up a new environment for post-install:
https://github.com/Homebrew/brew/blob/master/Library/Homebrew/formula.rb#L1081-L1103
```rb
      new_env = {
        TMPDIR:        HOMEBREW_TEMP,
        TEMP:          HOMEBREW_TEMP,
        TMP:           HOMEBREW_TEMP,
        _JAVA_OPTIONS: "-Djava.io.tmpdir=#{HOMEBREW_TEMP}",
        HOMEBREW_PATH: nil,
        PATH:          ENV["HOMEBREW_PATH"],
      }

      with_env(new_env) do
```

**Comment by cho-m** [comment]
Also, I would recommend avoiding touching/setting `HOMEBREW_PATH` unless you are sure you need to.

I am only able to reproduce your failure if I accidentally set `HOMEBREW_PATH` to an incomplete `PATH` missing some essential defaults paths.

**Comment by carlocab** [comment]
> Also, I would recommend avoiding touching/setting `HOMEBREW_PATH` unless you are sure you need to.

This is probably it. It sounds like `HOMEBREW_PATH` is being set to `/opt/homebrew`, and that breaks the `post_install`.

**Comment by carlocab** [comment]
Actually, in general, I recommend against setting `HOMEBREW_*` environment variables unless they're exposed publicly (see `man brew`) and you know what they do, as `brew` makes a lot of use of those variables internally.

**Comment by cho-m** [comment]
@carlocab maybe Homebrew's `brew doctor/config` output should make this issue a bit more clear.

From the original comment logs, I see the way we would have noticed this is from the warnings:
```
Warning: Homebrew's "bin" was not found in your PATH.
Consider setting your PATH for example like so:
  echo 'export PATH="/opt/homebrew/bin:$PATH"' >> ~/.zshrc

Warning: Homebrew's "sbin" was not found in your PATH but you have installed
formulae that put executables in /opt/homebrew/sbin.
Consider setting your PATH for example like so:
  echo 'export PATH="/opt/homebrew/sbin:$PATH"' >> ~/.zshrc
```

I reproduced this by exporting a bad `HOMEBREW_PATH` value, but maybe the doctor output can identify this better.

**Comment by carlocab** [comment]
Yes, having this diagnosed in `brew doctor` would be good. We might perhaps consider an allowlist of `HOMEBREW_*` variables, and warn about usage of anything else.

I don't think we document avoiding the use of `HOMEBREW_*` variables. We could probably try renaming internal variables to something like `_HOMEBREW_*`, but tracking all of the uses down would be a lot of work.

**Comment by carlocab** [comment]
CC @Homebrew/brew for opinions.
