### ISSUE TITLE
mitmproxy: cannot run

### ISSUE THREAD

**Issue by alexreg** [Homebrew/homebrew-core#8050]
If I try to run `mitmproxy` after a clean install, I get.

```
Traceback (most recent call last):
  File "/usr/local/bin/mitmproxy", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/usr/local/Cellar/mitmproxy/0.18.2_1/libexec/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3017, in <module>
    @_call_aside
  File "/usr/local/Cellar/mitmproxy/0.18.2_1/libexec/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3003, in _call_aside
    f(*args, **kwargs)
  File "/usr/local/Cellar/mitmproxy/0.18.2_1/libexec/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3030, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/local/Cellar/mitmproxy/0.18.2_1/libexec/lib/python2.7/site-packages/pkg_resources/__init__.py", line 650, in _build_master
    ws = cls()
  File "/usr/local/Cellar/mitmproxy/0.18.2_1/libexec/lib/python2.7/site-packages/pkg_resources/__init__.py", line 643, in __init__
    self.add_entry(entry)
  File "/usr/local/Cellar/mitmproxy/0.18.2_1/libexec/lib/python2.7/site-packages/pkg_resources/__init__.py", line 699, in add_entry
    for dist in find_distributions(entry, True):
  File "/usr/local/Cellar/mitmproxy/0.18.2_1/libexec/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2023, in find_on_path
    path_item, entry, metadata, precedence=DEVELOP_DIST
  File "/usr/local/Cellar/mitmproxy/0.18.2_1/libexec/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2432, in from_location
    py_version=py_version, platform=platform, **kw
  File "/usr/local/Cellar/mitmproxy/0.18.2_1/libexec/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2772, in _reload_version
    md_version = _version_from_file(self._get_metadata(self.PKG_INFO))
  File "/usr/local/Cellar/mitmproxy/0.18.2_1/libexec/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2397, in _version_from_file
    line = next(iter(version_lines), '')
  File "/usr/local/Cellar/mitmproxy/0.18.2_1/libexec/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2565, in _get_metadata
    for line in self.get_metadata_lines(name):
  File "/usr/local/Cellar/mitmproxy/0.18.2_1/libexec/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1471, in get_metadata_lines
    return yield_lines(self.get_metadata(name))
  File "/usr/local/Cellar/mitmproxy/0.18.2_1/libexec/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1467, in get_metadata
    value = self._get(self._fn(self.egg_info, name))
  File "/usr/local/Cellar/mitmproxy/0.18.2_1/libexec/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1576, in _get
    with open(path, 'rb') as stream:
IOError: [Errno 13] Permission denied: '/usr/local/Cellar/mitmproxy/0.18.2_1/libexec/lib/python2.7/site-packages/pycparser-2.16-py2.7.egg-info/PKG-INFO'
```

What's going on here?

**Comment by MikeMcQuaid** [comment]
Sorry but you have not followed the requested steps on [the Troubleshooting page](https://github.com/Homebrew/brew/blob/master/docs/Troubleshooting.md#troubleshooting) as requested by the issue template so I'm closing this issue out.

**Comment by alexreg** [comment]
`brew config`: https://gist.github.com/f267df359126cafcf309b400cca5408b
`brew doctor`: https://gist.github.com/65f31a7251b469bdc9c4e758f2bc6c31

No gist-logs output (it installs fine anyway, just running it is a problem)

Note: I'm using *brewdo*.

**Comment by MikeMcQuaid** [comment]
Does it reproduce without using `brewdo`?

**Comment by alexreg** [comment]
I can’t test that, I’m afraid. All I can say is that if I *run* mitmproxy with brewdo too, it seems to work. I just tested that. Obviously, it’s far from ideal though.

**Comment by MikeMcQuaid** [comment]
Sounds like a `brewdo` issue. Please avoid reporting stuff to us that relates to permissions while you're using it.
