### ISSUE TITLE
CI ubuntu-latest `which` failed Error: not found: python

### ISSUE THREAD

**Issue by chmac** [Homebrew/homebrew-core#83391]
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

```shell
n/a
```

### 

- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.

### What were you trying to do (and why)?

Creating a new formula #83099

### What happened (include all command output)?

```
npm ERR! code 1
npm ERR! path /home/linuxbrew/.linuxbrew/Cellar/joplin-cli/2.2.2/libexec/lib/node_modules/joplin/node_modules/keytar
npm ERR! command failed
npm ERR! command sh -c prebuild-install || npm run build
npm ERR! > keytar@7.7.0 build
npm ERR! > node-gyp rebuild
npm ERR! prebuild-install info begin Prebuild-install version 6.1.4
npm ERR! prebuild-install info install --build-from-source specified, not attempting download.
npm ERR! npm verb cli [
npm ERR! npm verb cli   '/home/linuxbrew/.linuxbrew/Cellar/node/16.6.2/bin/node',
npm ERR! npm verb cli   '/home/linuxbrew/.linuxbrew/opt/node/libexec/bin/npm',
npm ERR! npm verb cli   'run',
npm ERR! npm verb cli   'build'
npm ERR! npm verb cli ]
npm ERR! npm info using npm@7.20.3
npm ERR! npm info using node@v16.6.2
npm ERR! npm timing npm:load:whichnode Completed in 0ms
npm ERR! npm timing config:load:defaults Completed in 2ms
npm ERR! npm timing config:load:file:/home/linuxbrew/.linuxbrew/Cellar/node/16.6.2/libexec/lib/node_modules/npm/npmrc Completed in 4ms
npm ERR! npm timing config:load:builtin Completed in 4ms
npm ERR! gyp verb `which` failed }
npm ERR! gyp verb check python checking for Python executable "python" in the PATH
npm ERR! gyp verb `which` failed Error: not found: python
npm ERR! gyp verb `which` failed     at getNotFoundError (/home/linuxbrew/.linuxbrew/Cellar/joplin-cli/2.2.2/libexec/lib/node_modules/joplin/node_modules/node-gyp/node_modules/which/which.js:13:12)
npm ERR! gyp verb `which` failed     at F (/home/linuxbrew/.linuxbrew/Cellar/joplin-cli/2.2.2/libexec/lib/node_modules/joplin/node_modules/node-gyp/node_modules/which/which.js:68:19)
npm ERR! gyp verb `which` failed     at E (/home/linuxbrew/.linuxbrew/Cellar/joplin-cli/2.2.2/libexec/lib/node_modules/joplin/node_modules/node-gyp/node_modules/which/which.js:80:29)
npm ERR! gyp verb `which` failed     at /home/linuxbrew/.linuxbrew/Cellar/joplin-cli/2.2.2/libexec/lib/node_modules/joplin/node_modules/node-gyp/node_modules/which/which.js:89:16
npm ERR! gyp verb `which` failed     at /home/linuxbrew/.linuxbrew/Cellar/joplin-cli/2.2.2/libexec/lib/node_modules/joplin/node_modules/isexe/index.js:42:5
npm ERR! gyp verb `which` failed     at /home/linuxbrew/.linuxbrew/Cellar/joplin-cli/2.2.2/libexec/lib/node_modules/joplin/node_modules/isexe/mode.js:8:5
npm ERR! gyp verb `which` failed     at FSReqCallback.oncomplete (node:fs:195:21)
npm ERR! gyp verb `which` failed  python Error: not found: python
npm ERR! gyp verb `which` failed     at getNotFoundError (/home/linuxbrew/.linuxbrew/Cellar/joplin-cli/2.2.2/libexec/lib/node_modules/joplin/node_modules/node-gyp/node_modules/which/which.js:13:12)
npm ERR! gyp verb `which` failed     at F (/home/linuxbrew/.linuxbrew/Cellar/joplin-cli/2.2.2/libexec/lib/node_modules/joplin/node_modules/node-gyp/node_modules/which/which.js:68:19)
npm ERR! gyp verb `which` failed     at E (/home/linuxbrew/.linuxbrew/Cellar/joplin-cli/2.2.2/libexec/lib/node_modules/joplin/node_modules/node-gyp/node_modules/which/which.js:80:29)
npm ERR! gyp verb `which` failed     at /home/linuxbrew/.linuxbrew/Cellar/joplin-cli/2.2.2/libexec/lib/node_modules/joplin/node_modules/node-gyp/node_modules/which/which.js:89:16
npm ERR! gyp verb `which` failed     at /home/linuxbrew/.linuxbrew/Cellar/joplin-cli/2.2.2/libexec/lib/node_modules/joplin/node_modules/isexe/index.js:42:5
npm ERR! gyp verb `which` failed     at /home/linuxbrew/.linuxbrew/Cellar/joplin-cli/2.2.2/libexec/lib/node_modules/joplin/node_modules/isexe/mode.js:8:5
npm ERR! gyp verb `which` failed     at FSReqCallback.oncomplete (node:fs:195:21) {
npm ERR! gyp verb `which` failed   code: 'ENOENT'
npm ERR! gyp verb `which` failed }
npm ERR! gyp ERR! configure error 
npm ERR! gyp ERR! stack Error: Can't find Python executable "python", you can set the PYTHON env variable.
npm ERR! gyp ERR! stack     at PythonFinder.failNoPython (/home/linuxbrew/.linuxbrew/Cellar/joplin-cli/2.2.2/libexec/lib/node_modules/joplin/node_modules/node-gyp/lib/configure.js:484:19)
npm ERR! gyp ERR! stack     at PythonFinder.<anonymous> (/home/linuxbrew/.linuxbrew/Cellar/joplin-cli/2.2.2/libexec/lib/node_modules/joplin/node_modules/node-gyp/lib/configure.js:406:16)
npm ERR! gyp ERR! stack     at F (/home/linuxbrew/.linuxbrew/Cellar/joplin-cli/2.2.2/libexec/lib/node_modules/joplin/node_modules/node-gyp/node_modules/which/which.js:68:16)
npm ERR! gyp ERR! stack     at E (/home/linuxbrew/.linuxbrew/Cellar/joplin-cli/2.2.2/libexec/lib/node_modules/joplin/node_modules/node-gyp/node_modules/which/which.js:80:29)
npm ERR! gyp ERR! stack     at /home/linuxbrew/.linuxbrew/Cellar/joplin-cli/2.2.2/libexec/lib/node_modules/joplin/node_modules/node-gyp/node_modules/which/which.js:89:16
npm ERR! gyp ERR! stack     at /home/linuxbrew/.linuxbrew/Cellar/joplin-cli/2.2.2/libexec/lib/node_modules/joplin/node_modules/isexe/index.js:42:5
npm ERR! gyp ERR! stack     at /home/linuxbrew/.linuxbrew/Cellar/joplin-cli/2.2.2/libexec/lib/node_modules/joplin/node_modules/isexe/mode.js:8:5
npm ERR! gyp ERR! stack     at FSReqCallback.oncomplete (node:fs:195:21)
npm ERR! gyp ERR! System Linux 5.8.0-1039-azure
npm ERR! gyp ERR! command "/home/linuxbrew/.linuxbrew/Cellar/node/16.6.2/bin/node" "/home/linuxbrew/.linuxbrew/Cellar/joplin-cli/2.2.2/libexec/lib/node_modules/joplin/node_modules/.bin/node-gyp" "rebuild"
npm ERR! gyp ERR! cwd /home/linuxbrew/.linuxbrew/Cellar/joplin-cli/2.2.2/libexec/lib/node_modules/joplin/node_modules/keytar
npm ERR! gyp ERR! node -v v16.6.2
npm ERR! gyp ERR! node-gyp -v v3.8.0
npm ERR! gyp ERR! not ok 
npm ERR! npm timing command:run-script Completed in 153ms
npm ERR! npm verb exit 1
npm ERR! npm timing npm Completed in 348ms
npm ERR! npm verb code 1
```

### What did you expect to happen?

I assumed that if `python` is in the `PATH` on the macOS CI environment then it would also be available on the ubuntu CI environment.

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
Check PR #83099, this is a CI issue so I can't create commands here.
```

**Comment by carlocab** [comment]
Python needs to be invoked as `python3`. If that doesn't work, see the output of `brew info python`:
```
Unversioned symlinks `python`, `python-config`, `pip` etc. pointing to
`python3`, `python3-config`, `pip3` etc., respectively, have been installed into
  /usr/local/opt/python@3.9/libexec/bin
```
The `/usr/local` prefix will change depending on where Homebrew has been installed.

**Comment by chmac** [comment]
@carlocab Thanks for the quick response! This is on the ubuntu-latest CI build that runs as part of a PR against this repo. I don't run any commands, so I have no control over where python is run, etc.

Here's an example from the logs:

https://github.com/Homebrew/homebrew-core/pull/83099/checks?check_run_id=3341812711

I guess I'm getting something wrong, but I've no idea how to get python to be in the PATH on this ubuntu machine. It runs fine on the macOS machines. My naive assumption was that if my formula builds on macOS it should also build on ubuntu, but that doesn't seem to be the case.

**Comment by carlocab** [comment]
You should check if the build system lets you configure how to call Python. For example, you could pass additional flags or set environment variables. There are many examples of these in other formulae.

Failing that, maybe you could modify the source with an `inreplace`. Otherwise, you can also try to modify your `PATH` with `ENV.prepend_path`. See other formulae for examples.

**Comment by chmac** [comment]
@carlocab The build tool in this case is node-gyp, which expects python2 to be installed. But it seems the ubuntu CI system doesn't have python2 while it's automatically included as part of macOS. Is there anything in the docs about what to expect on a linux system compared to a macOS one? I'm lost here.

**Comment by chmac** [comment]
I'm giving up on adding joplin at this point, maybe somebody else can figure it out. I've personally invested an unreasonable amount of time already to try and swap `npm install joplin` for `brew install joplin`. I assumed that wrapping an npm package in a brew formula would be easier than this. Thanks for all the help along the way @carlocab, maybe somebody else will have more luck than me.

**Comment by carlocab** [comment]
So they only support Python2? We don't have Python2 on Linux CI. We can figure out Linux support later on. Thanks for the work you put into this!

**Comment by chmac** [comment]
Once I eventually got python@3.9 both installed and also added to the build path, I got a syntax error. Unfortunately there's so many dependencies in the npm chain that it's hard to know exactly what's going on. It seems like that version of node-gyp relies on python2, which is installed on macOS but not on the linux machine.
