### ISSUE TITLE
Error upgrading qt

### ISSUE THREAD

**Issue by dduugg** [Homebrew/homebrew-core#8340]
attempting to upgrade qt5 resulted in the following error:
```
Error: /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Aliases/qt:1: syntax error, unexpected ..
../Formula/qt5.rb
  ^
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Aliases/qt:1: unknown regexp options - qt
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Aliases/qt:1: syntax error, unexpected tINTEGER, expecting end-of-input
../Formula/qt5.rb
              ^
Please report this bug:
  https://git.io/brew-troubleshooting
/usr/local/Homebrew/Library/Homebrew/formulary.rb:25:in `module_eval'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:25:in `load_formula'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:42:in `load_formula_from_path'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:97:in `load_file'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:212:in `load_file'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:88:in `klass'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:84:in `get_formula'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:206:in `get_formula'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:253:in `factory'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:284:in `from_keg'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:267:in `from_rack'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1406:in `block in installed'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1404:in `map'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1404:in `installed'
/usr/local/Homebrew/Library/Homebrew/cmd/upgrade.rb:37:in `upgrade'
/usr/local/Homebrew/Library/Homebrew/brew.rb:94:in `<main>'
```

`brew doctor` initially warned about an unlinked keg (along with repeating the above error message after the warning):
```
$ brew doctor
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry and just ignore them. Thanks!

Warning: You have unlinked kegs in your Cellar
Leaving kegs unlinked can lead to build-trouble and cause brews that depend on
those kegs to fail to run properly once built. Run `brew link` on these:
  qt5
```

However, I'm still seeing errors after linking:
```
$ brew config
HOMEBREW_VERSION: 1.1.5
ORIGIN: https://github.com/Homebrew/brew.git
HEAD: 9cd5a21b473f0271b162bbe7f77f7d1468c0cfa1
Last commit: 2 weeks ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: af7ffaddab5edea4ed2fd3011fbcfb310a8d80c8
Core tap last commit: 44 minutes ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_REPOSITORY: /usr/local/Homebrew
HOMEBREW_CELLAR: /usr/local/Cellar
HOMEBREW_BOTTLE_DOMAIN: https://homebrew.bintray.com
CPU: quad-core 64-bit haswell
Homebrew Ruby: 2.0.0-p648
Clang: 8.0 build 800
Git: 2.11.0 => /usr/local/bin/git
Perl: /usr/bin/perl
Python: /usr/local/bin/python => /usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/bin/python2.7
Ruby: /Users/duggiestyle/.rvm/rubies/ruby-2.2.0/bin/ruby
Java: 1.8.0_40
macOS: 10.12.2-x86_64
Xcode: 8.2.1
CLT: N/A
X11: N/A
$ brew doctor
Error: /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Aliases/qt:1: syntax error, unexpected ..
../Formula/qt5.rb
  ^
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Aliases/qt:1: unknown regexp options - qt
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Aliases/qt:1: syntax error, unexpected tINTEGER, expecting end-of-input
../Formula/qt5.rb
              ^
Please report this bug:
  https://git.io/brew-troubleshooting
/usr/local/Homebrew/Library/Homebrew/formulary.rb:25:in `module_eval'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:25:in `load_formula'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:42:in `load_formula_from_path'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:97:in `load_file'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:212:in `load_file'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:88:in `klass'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:84:in `get_formula'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:206:in `get_formula'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:253:in `factory'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:284:in `from_keg'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:267:in `from_rack'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1406:in `block in installed'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1404:in `map'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1404:in `installed'
/usr/local/Homebrew/Library/Homebrew/diagnostic.rb:879:in `check_missing_deps'
/usr/local/Homebrew/Library/Homebrew/cmd/doctor.rb:43:in `block in doctor'
/usr/local/Homebrew/Library/Homebrew/cmd/doctor.rb:35:in `each'
/usr/local/Homebrew/Library/Homebrew/cmd/doctor.rb:35:in `doctor'
/usr/local/Homebrew/Library/Homebrew/brew.rb:94:in `<main>'
```

cc @MikeMcQuaid as i notice there were recent changes to the qt formulae (https://github.com/Homebrew/homebrew-core/commit/05eaba4cd570b000aa85d91a01e2b4d503894f00)

**Comment by MikeMcQuaid** [comment]
> Error: /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Aliases/qt:1: syntax error, unexpected ..

Can you check the syntax of this file with `cat /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Aliases/qt`? I can't reproduce that locally which makes me think there's something up with your repository.

> brew doctor initially warned about an unlinked keg (along with repeating the above error message after the warning):

This is known until you upgrade Qt5 as it's gone from being `keg_only` to not being any more.

> However, I'm still seeing errors after linking:

Are you seeing errors outside of `brew doctor` itself?

**Comment by dduugg** [comment]
thanks for the reply!

```
$  cat /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Aliases/qt
../Formula/qt5.rb
```

I'm getting this error with `brew upgrade`, `brew doctor` , and `brew uninstall qt`. Let me know if there are other commands you'd like me to try. (I'm happy to completely uninstall qt if you can recommend the incantations to do so).

**Comment by MikeMcQuaid** [comment]
@dduugg Your Git repository has some issues. Please try to `git checkout /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Aliases/qt` and try again.

**Comment by dduugg** [comment]
no luck 😿 
```
duggiestyle at Mac-mini in /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core on master*
$ git checkout /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Aliases/qt
duggiestyle at Mac-mini in /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core on master*
$ brew doctor
Error: /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Aliases/qt:1: syntax error, unexpected ..
../Formula/qt5.rb
  ^
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Aliases/qt:1: unknown regexp options - qt
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Aliases/qt:1: syntax error, unexpected tINTEGER, expecting end-of-input
../Formula/qt5.rb
              ^
Please report this bug:
  https://git.io/brew-troubleshooting
/usr/local/Homebrew/Library/Homebrew/formulary.rb:25:in `module_eval'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:25:in `load_formula'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:42:in `load_formula_from_path'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:97:in `load_file'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:212:in `load_file'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:88:in `klass'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:84:in `get_formula'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:206:in `get_formula'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:253:in `factory'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:284:in `from_keg'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:267:in `from_rack'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1406:in `block in installed'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1404:in `map'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1404:in `installed'
/usr/local/Homebrew/Library/Homebrew/diagnostic.rb:879:in `check_missing_deps'
/usr/local/Homebrew/Library/Homebrew/cmd/doctor.rb:43:in `block in doctor'
/usr/local/Homebrew/Library/Homebrew/cmd/doctor.rb:35:in `each'
/usr/local/Homebrew/Library/Homebrew/cmd/doctor.rb:35:in `doctor'
/usr/local/Homebrew/Library/Homebrew/brew.rb:94:in `<main>'
```

**Comment by MikeMcQuaid** [comment]
Probably worth a `rm -rf /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core` and `brew tap homebrew/core`. What's in your `~/.gitconfig`?

**Comment by dduugg** [comment]
here's my gitconfig: https://gist.github.com/dduugg/b9310701cd4ae9e14438ab1242a90a4f

**Comment by MikeMcQuaid** [comment]
`symlinks = false` is the cause of this issue. That's going to break all Homebrew aliases and anything relying on them.

**Comment by dduugg** [comment]
ah tyty!
