### ISSUE TITLE
talisman 1.11.0 installation fails

### ISSUE THREAD

**Issue by dexterous** [Homebrew/homebrew-core#83936]
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

```shell
$ brew config
HOMEBREW_VERSION: 3.2.9-37-g7d3f073
ORIGIN: https://github.com/Homebrew/brew
HEAD: 7d3f073e9d21ad6170d5cb433df1bdd1bb008e02
Last commit: 11 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: ad96d4024e26e7c43b3e369338cdb029ad7c0c52
Core tap last commit: 44 minutes ago
Core tap branch: master
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CASK_OPTS: []
HOMEBREW_MAKE_JOBS: 12
Homebrew Ruby: 2.6.3 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: dodeca-core 64-bit kabylake
Clang: 12.0.5 build 1205
Git: 2.33.0 => /usr/local/bin/git
Curl: 7.64.1 => /usr/bin/curl
macOS: 11.5.2-x86_64
CLT: 12.5.1.0.1.1623191612
Xcode: N/A
```

```shell
$ brew doctor
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: Some installed formulae are deprecated or disabled.
You should find replacements for the following formulae:
  multitail

Warning: Putting non-prefixed coreutils in your path can cause GMP builds to fail.

Warning: Some installed formulae are missing dependencies.
You should `brew install` the missing dependencies:
  brew install bash-completion

Run `brew missing` for more details.
```

### 

- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.

### What were you trying to do (and why)?

```shell
brew install talisman
```

### What happened (include all command output)?

```shell
==> Downloading https://ghcr.io/v2/homebrew/core/talisman/manifests/1.11.0
Already downloaded: /Users/ysxm180/Library/Caches/Homebrew/downloads/28dd2baf2aff902ebe9fce6d0949fa659b64969c64bae8501e7fb77a183c6ba8--talisman-1.11.0.bottle_manifest.json
==> Downloading https://ghcr.io/v2/homebrew/core/talisman/blobs/sha256:379a9307c825d9dc843e6e5df4a83786a462d48ba10022706810eeb720c91969
Already downloaded: /Users/ysxm180/Library/Caches/Homebrew/downloads/629f486b3a72b1c6b7d3f2f15728e99179863fd25f68d6e8b8fbdf9f224ac8ac--talisman--1.11.0.big_sur.bottle.tar.gz
==> Pouring talisman--1.11.0.big_sur.bottle.tar.gz
Error: Couldn't find manifest matching bottle checksum.
Please report this issue:
  https://docs.brew.sh/Troubleshooting
/usr/local/Homebrew/Library/Homebrew/software_spec.rb:400:in `tab_attributes'
/usr/local/Homebrew/Library/Homebrew/formula.rb:2379:in `bottle_tab_attributes'
/usr/local/Homebrew/Library/Homebrew/utils/bottles.rb:100:in `load_tab'
/usr/local/Homebrew/Library/Homebrew/formula_installer.rb:1154:in `pour'
/usr/local/Homebrew/Library/Homebrew/formula_installer.rb:394:in `install'
/usr/local/Homebrew/Library/Homebrew/install.rb:303:in `install_formula'
/usr/local/Homebrew/Library/Homebrew/cmd/install.rb:207:in `block in install'
/usr/local/Homebrew/Library/Homebrew/cmd/install.rb:205:in `each'
/usr/local/Homebrew/Library/Homebrew/cmd/install.rb:205:in `install'
/usr/local/Homebrew/Library/Homebrew/brew.rb:129:in `<main>'
```

### What did you expect to happen?

The latest version of the talisman formula was installed.

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
brew install talisman
```

**Comment by SMillerDev** [comment]
> Already downloaded: /Users/ysxm180/Library/Caches/Homebrew/downloads/28dd2baf2aff902ebe9fce6d0949fa659b64969c64bae8501e7fb77a183c6ba8--talisman-1.11.0.bottle_manifest.json

Try removing this (and the other) cached file and try again.

**Comment by dexterous** [comment]
That did it, thank.
