### ISSUE TITLE
GO: fix install for Linux

### ISSUE THREAD

**Issue by kksudo** [Homebrew/homebrew-core#84479]
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

```shell
brew config

HOMEBREW_VERSION: 3.2.10-46-gfb8d679
ORIGIN: https://github.com/Homebrew/brew
HEAD: fb8d679a62bafb8d9bed753c4a98037329119f5b
Last commit: 13 hours ago
Core tap ORIGIN: https://github.com/Homebrew/linuxbrew-core
Core tap HEAD: 5be537bbb3df36a076e9367fa9c01bb22834281c
Core tap last commit: 3 hours ago
Core tap branch: master
HOMEBREW_PREFIX: /home/linuxbrew/.linuxbrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_DISPLAY: :0
HOMEBREW_EDITOR: vi
HOMEBREW_MAKE_JOBS: 8
Homebrew Ruby: 2.6.3 => /home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3_2/bin/ruby
CPU: octa-core 64-bit nehalem
Clang: N/A
Git: 2.25.1 => /bin/git
Curl: 7.68.0 => /usr/bin/curl
Kernel: Linux 5.11.0-27-generic x86_64 GNU/Linux
OS: Linux Mint 20.2 (uma)
Host glibc: 2.31
/usr/bin/gcc: 9.3.0
/usr/bin/ruby: N/A
glibc: N/A
gcc@5: 5.5.0_7
xorg: N/A
```

brew test --verbose go
```
==> Testing go
==> /home/linuxbrew/.linuxbrew/Cellar/go/1.17/bin/go fmt hello.go
*** stack smashing detected ***: terminated
Error: go: failed
An exception occurred within a child process:
  BuildError: Failed executing: /home/linuxbrew/.linuxbrew/Cellar/go/1.17/bin/go fmt hello.go
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/formula.rb:2289:in `block in system'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/formula.rb:2225:in `open'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/formula.rb:2225:in `system'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/go.rb:79:in `block in <class:Go>'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/formula.rb:2089:in `block (3 levels) in run_test'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/utils.rb:550:in `with_env'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/formula.rb:2088:in `block (2 levels) in run_test'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/formula.rb:940:in `with_logging'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/formula.rb:2087:in `block in run_test'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/mktemp.rb:63:in `block in run'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/mktemp.rb:63:in `chdir'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/mktemp.rb:63:in `run'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/formula.rb:2340:in `mktemp'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/formula.rb:2081:in `run_test'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/test.rb:43:in `block in <main>'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3_2/lib/ruby/2.6.0/timeout.rb:93:in `block in timeout'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3_2/lib/ruby/2.6.0/timeout.rb:33:in `block in catch'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3_2/lib/ruby/2.6.0/timeout.rb:33:in `catch'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3_2/lib/ruby/2.6.0/timeout.rb:33:in `catch'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3_2/lib/ruby/2.6.0/timeout.rb:108:in `timeout'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/test.rb:48:in `<main>
```
```
brew doctor
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: Some installed formulae are deprecated or disabled.
You should find replacements for the following formulae:
  isl@0.18

Warning: "config" scripts exist outside your system or Homebrew directories.
`./configure` scripts often look for *-config scripts to determine if
software packages are installed, and which additional flags to use when
compiling and linking.

Having additional scripts in your path can confuse software installed via
Homebrew if the config script overrides a system or Homebrew-provided
script of the same name. We found the following "config" scripts:
  /usr/local/bin/ansible-config
```

### 

- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.

### What were you trying to do (and why)?

Try to  install anything with the go builder or go

### What happened (include all command output)?

```console
*** stack smashing detected ***: terminated
[1]    63841 abort (core dumped)  go
```

When I try to install from sources
```console
brew install --build-from-source go
==> Downloading https://storage.googleapis.com/golang/go1.16.linux-amd64.tar.gz
######################################################################## 100.0%
==> Downloading https://golang.org/dl/go1.17.src.tar.gz
==> Downloading from https://dl.google.com/go/go1.17.src.tar.gz
######################################################################## 100.0%
==> ./make.bash --no-clean
Last 15 lines from /home/kk_dev/.cache/Homebrew/Logs/go/01.make.bash:
--no-clean

./make.bash: line 140: 42377 Done                    echo "int main() { return 0; }"
     42378 Segmentation fault      (core dumped) | ${CC:-cc} -o ./test-musl-ldso -x c - > /dev/null 2>&1
Building Go cmd/dist using /tmp/go-20210902-42323-1e8i7eg/go/gobootstrap. (go1.16 linux/amd64)
warning: --no-clean is deprecated and has no effect; use 'go install std cmd' instead
Building Go toolchain1 using /tmp/go-20210902-42323-1e8i7eg/go/gobootstrap.
Building Go bootstrap cmd/go (go_bootstrap) using Go toolchain1.
Building Go toolchain2 using go_bootstrap and Go toolchain1.
Building Go toolchain3 using go_bootstrap and Go toolchain2.
Building packages and commands for linux/amd64.
# runtime/cgo
cc1: internal compiler error: Segmentation fault
/home/linuxbrew/.linuxbrew/Cellar/gcc@5/5.5.0_7/libexec/gcc/x86_64-unknown-linux-gnu/5.5.0/cc1: error while loading shared libraries: shared object not open
go tool dist: FAILED: /tmp/go-20210902-42323-1e8i7eg/go/pkg/tool/linux_amd64/go_bootstrap install -gcflags=all= -ldflags=all= std cmd: exit status 2

READ THIS: https://docs.brew.sh/Troubleshooting
```
### What did you expect to happen?

The command go version worked well.

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
brew uninstall go && \
brew cleanup --prune=all && \
brew install go
```

**Comment by dawidd6** [comment]
Build and test freshly passed in this run on Linux:
https://github.com/Homebrew/homebrew-core/runs/3494319845?check_suite_focus=true

The issue must be somewhere on your side.

**Comment by carlocab** [comment]
Why are you building Go from source?

**Comment by kksudo** [comment]
@carlocab 
I tried different options, and of course simple `brew install go`.
Yep, look like the error on my side, but can you tell me where to dig to solve this issue ?

**Comment by MikeMcQuaid** [comment]
@kksudo We do not support building Go from source.

**Comment by dawidd6** [comment]
@MikeMcQuaid user has problems running `go` binary from our bottle in the first place. Building from source was some form of debugging on their side I presume.

**Comment by azilber** [comment]
go1.17.1 (released 2021-09-09)
