### ISSUE TITLE
python@3.9 permission for configuration.py

### ISSUE THREAD

**Issue by 2young-2simple-sometimes-naive** [Homebrew/homebrew-core#84734]
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

```shell
`brew config`

HOMEBREW_VERSION: 3.2.10
ORIGIN: https://github.com/Homebrew/brew
HEAD: ab2118a402a44451b1d7559167b6956dc47cc19a
Last commit: 6 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 9b8e937d0c77b9465214cfdeceb6f44e9af3f6c8
Core tap last commit: 6 minutes ago
Core tap branch: master
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CASK_OPTS: []
HOMEBREW_DISPLAY: /private/tmp/com.apple.launchd.VJwkntD4oQ/org.xquartz:0
HOMEBREW_MAKE_JOBS: 12
Homebrew Ruby: 2.6.3 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: dodeca-core 64-bit kabylake
Clang: 12.0.5 build 1205
Git: 2.33.0 => /usr/local/bin/git
Curl: 7.64.1 => /usr/bin/curl
macOS: 11.5.2-x86_64
CLT: 12.5.0.22.9
Xcode: N/A


`brew doctor`

Your system is ready to brew.
```

### 

- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.

### What were you trying to do (and why)?

`brew install python@3.9`

### What happened (include all command output)?

==> Reinstalling python@3.9
==> Pouring python@3.9--3.9.7.big_sur.bottle.tar.gz
==> /usr/local/Cellar/python@3.9/3.9.7/bin/python3 -m ensurepip
==> /usr/local/Cellar/python@3.9/3.9.7/bin/python3 -m pip install -v --no-deps --no-index --upgrade --iso
Last 15 lines from /Users/xxxxxxxx/Library/Logs/Homebrew/python@3.9/post_install.02.python3:
  File "/usr/local/lib/python3.9/site-packages/pip/_internal/cli/req_command.py", line 203, in wrapper
    return func(self, options, args)
  File "/usr/local/lib/python3.9/site-packages/pip/_internal/commands/install.py", line 446, in run
    self._handle_target_dir(
  File "/usr/local/lib/python3.9/site-packages/pip/_internal/commands/install.py", line 501, in _handle_target_dir
    shutil.rmtree(target_item_dir)
  File "/usr/local/Cellar/python@3.9/3.9.7/Frameworks/Python.framework/Versions/3.9/lib/python3.9/shutil.py", line 726, in rmtree
    _rmtree_safe_fd(fd, path, onerror)
  File "/usr/local/Cellar/python@3.9/3.9.7/Frameworks/Python.framework/Versions/3.9/lib/python3.9/shutil.py", line 663, in _rmtree_safe_fd
    _rmtree_safe_fd(dirfd, fullname, onerror)
  File "/usr/local/Cellar/python@3.9/3.9.7/Frameworks/Python.framework/Versions/3.9/lib/python3.9/shutil.py", line 683, in _rmtree_safe_fd
    onerror(os.unlink, fullname, sys.exc_info())
  File "/usr/local/Cellar/python@3.9/3.9.7/Frameworks/Python.framework/Versions/3.9/lib/python3.9/shutil.py", line 681, in _rmtree_safe_fd
    os.unlink(entry.name, dir_fd=topfd)
PermissionError: [Errno 13] Permission denied: 'configuration.py'
Warning: The post-install step did not complete successfully
You can try again using:
  brew postinstall python@3.9

### What did you expect to happen?

successful install python@3.9 without bugs

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
`brew install python@3.9`

or

`brew reinstall python@3.9`
```

**Comment by daviduzumeri** [comment]
I'm also seeing this.

```HOMEBREW_VERSION: 3.2.10
ORIGIN: https://github.com/Homebrew/brew
HEAD: ab2118a402a44451b1d7559167b6956dc47cc19a
Last commit: 7 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: c4dda6ad15378d7c607e1037d985038d65fa1c47
Core tap last commit: 36 minutes ago
Core tap branch: master
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_MAKE_JOBS: 8
Homebrew Ruby: 2.6.3 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: octa-core 64-bit arm_firestorm_icestorm
Clang: 12.0.5 build 1205
Git: 2.30.1 => /Applications/Xcode.app/Contents/Developer/usr/bin/git
Curl: 7.64.1 => /usr/bin/curl
macOS: 11.5.2-arm64
CLT: 12.0.0.32.29
Xcode: 12.5.1
Rosetta 2: false
```

```Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: Your Command Line Tools are too outdated.
Update them from Software Update in System Preferences or run:
  softwareupdate --all --install --force

If that doesn't show you any updates, run:
  sudo rm -rf /Library/Developer/CommandLineTools
  sudo xcode-select --install

Alternatively, manually download them from:
  https://developer.apple.com/download/more/.
You should download the Command Line Tools for Xcode 12.5.


Warning: A newer Command Line Tools release is available.
Update them from Software Update in System Preferences or run:
  softwareupdate --all --install --force

If that doesn't show you any updates, run:
  sudo rm -rf /Library/Developer/CommandLineTools
  sudo xcode-select --install

Alternatively, manually download them from:
  https://developer.apple.com/download/more/.
You should download the Command Line Tools for Xcode 12.5.


Warning: Unbrewed dylibs were found in /usr/local/lib.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected dylibs:
  /usr/local/lib/libtcl8.6.dylib
  /usr/local/lib/libtk8.6.dylib

Warning: Unbrewed header files were found in /usr/local/include.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected header files:
  /usr/local/include/fakemysql.h
  /usr/local/include/fakepq.h
  /usr/local/include/fakesql.h
  /usr/local/include/itcl.h
  /usr/local/include/itcl2TclOO.h
  /usr/local/include/itclDecls.h
  /usr/local/include/itclInt.h
  /usr/local/include/itclIntDecls.h
  /usr/local/include/itclMigrate2TclCore.h
  /usr/local/include/itclTclIntStubsFcn.h
  /usr/local/include/mysqlStubs.h
  /usr/local/include/odbcStubs.h
  /usr/local/include/pqStubs.h
  /usr/local/include/tcl.h
  /usr/local/include/tclDecls.h
  /usr/local/include/tclOO.h
  /usr/local/include/tclOODecls.h
  /usr/local/include/tclPlatDecls.h
  /usr/local/include/tclThread.h
  /usr/local/include/tclTomMath.h
  /usr/local/include/tclTomMathDecls.h
  /usr/local/include/tdbc.h
  /usr/local/include/tdbcDecls.h
  /usr/local/include/tdbcInt.h
  /usr/local/include/tk.h
  /usr/local/include/tkDecls.h
  /usr/local/include/tkPlatDecls.h```

**Comment by jieniuu8** [comment]
Same. Running Catalina

```
jieniu@Jies-MacBook-Pro ~ % brew postinstall -d python@3.9 
/usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::FormulaLoader): loading /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/python@3.9.rb
==> Postinstalling python@3.9
/usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::FromPathLoader): loading /usr/local/opt/python@3.9/.brew/python@3.9.rb
==> /usr/local/Cellar/python@3.9/3.9.7/bin/python3 -m ensurepip
==> /usr/local/Cellar/python@3.9/3.9.7/bin/python3 -m pip install -v --no-deps --no-index --upgrade --isolated --target=/usr/local/lib/python3.9/site-packages /usr/local/Cellar/python@3.9/3.9.7/Frameworks/Python.framework/Versions/3.9/lib/python3.9/ensurepip/_bundled/setup
Last 15 lines from /Users/jieniu/Library/Logs/Homebrew/python@3.9/post_install.02.python3:
  File "/usr/local/lib/python3.9/site-packages/pip/_internal/cli/req_command.py", line 203, in wrapper
    return func(self, options, args)
  File "/usr/local/lib/python3.9/site-packages/pip/_internal/commands/install.py", line 446, in run
    self._handle_target_dir(
  File "/usr/local/lib/python3.9/site-packages/pip/_internal/commands/install.py", line 501, in _handle_target_dir
    shutil.rmtree(target_item_dir)
  File "/usr/local/Cellar/python@3.9/3.9.7/Frameworks/Python.framework/Versions/3.9/lib/python3.9/shutil.py", line 726, in rmtree
    _rmtree_safe_fd(fd, path, onerror)
  File "/usr/local/Cellar/python@3.9/3.9.7/Frameworks/Python.framework/Versions/3.9/lib/python3.9/shutil.py", line 663, in _rmtree_safe_fd
    _rmtree_safe_fd(dirfd, fullname, onerror)
  File "/usr/local/Cellar/python@3.9/3.9.7/Frameworks/Python.framework/Versions/3.9/lib/python3.9/shutil.py", line 683, in _rmtree_safe_fd
    onerror(os.unlink, fullname, sys.exc_info())
  File "/usr/local/Cellar/python@3.9/3.9.7/Frameworks/Python.framework/Versions/3.9/lib/python3.9/shutil.py", line 681, in _rmtree_safe_fd
    os.unlink(entry.name, dir_fd=topfd)
PermissionError: [Errno 13] Permission denied: 'configuration.py'
Warning: The post-install step did not complete successfully
You can try again using:
  brew postinstall python@3.9
==> An exception occurred within a child process:
  BuildError: Failed executing: /usr/local/Cellar/python@3.9/3.9.7/bin/python3 -m pip install -v --no-deps --no-index --upgrade --isolated --target=/usr/local/lib/python3.9/site-packages /usr/local/Cellar/python@3.9/3.9.7/Frameworks/Python.framework/Versions/3.9/lib/python3.9/ensurepip/_bundled/setuptools-57.4.0-py3-none-any.whl /usr/local/Cellar/python@3.9/3.9.7/Frameworks/Python.framework/Versions/3.9/lib/python3.9/ensurepip/_bundled/pip-21.2.4-py3-none-any.whl /usr/local/Cellar/python@3.9/3.9.7/libexec/wheel-0.37.0-py2.py3-none-any.whl

/usr/local/Homebrew/Library/Homebrew/formula.rb:2297:in `block in system'
/usr/local/Homebrew/Library/Homebrew/formula.rb:2233:in `open'
/usr/local/Homebrew/Library/Homebrew/formula.rb:2233:in `system'
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/python@3.9.rb:331:in `post_install'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1126:in `block (2 levels) in run_post_install'
/usr/local/Homebrew/Library/Homebrew/formula.rb:949:in `with_logging'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1125:in `block in run_post_install'
/usr/local/Homebrew/Library/Homebrew/utils.rb:550:in `with_env'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1114:in `run_post_install'
/usr/local/Homebrew/Library/Homebrew/postinstall.rb:22:in `<main>'
```

**Comment by jieniuu8** [comment]
Related: [74140](https://github.com/Homebrew/homebrew-core/pull/74140)

I removed `/usr/local/lib/python3.x` folders and no more errors.

**Comment by carlocab** [comment]
> I removed `/usr/local/lib/python3.x` folders and no more errors.

This will break Homebrew `python@3.9` if you have it installed. It will also unlink some Python formulae (e.g. `numpy`, `six`, etc).

**Comment by jieniuu8** [comment]
> > I removed `/usr/local/lib/python3.x` folders and no more errors.
> 
> This will break Homebrew `python@3.9` if you have it installed. It will also unlink some Python formulae (e.g. `numpy`, `six`, etc).

The issue was that Homebrew wasn't able to complete postinstall for python3. So I removed '/usr/local/lib/python3.9' after uninstalling `python@3.9`

**Comment by compuguy** [comment]
Out of curiosity has any progress been made on this?

**Comment by Jayanth-kumar5566** [comment]
Still facing this issue with "monterey"

**Comment by gromgit** [comment]
What's the output of `find $(brew --prefix)/ -name configuration.py -ls`?

**Comment by Jayanth-kumar5566** [comment]
Yes you are right! Its owned by root

`2979070       32 -rw-r--r--    1 jhome            admin               16335 Oct 11 11:37 /opt/homebrew//lib/python3.9/site-packages/igraph/configuration.py
4744577       32 -rw-r--r--    1 root             admin               13153 Oct 27 23:58 /opt/homebrew//lib/python3.9/site-packages/pip/_internal/configuration.py
4744601       24 -rw-r--r--    1 root             admin                8944 Oct 27 23:58 /opt/homebrew//lib/python3.9/site-packages/pip/_internal/commands/configuration.py`

I have now tried to changing the ownership of the `site-packages/pip/*` directory to my username.

`sudo chown -R 'jhome' /opt/homebrew/lib/python3.9/site-packages/pip/`

However, when I now run 

` brew postinstall python@3.9`

I still get an error that ` /opt/homebrew/opt/python@3.9/bin/python3.9: No module named pip
Warning: The post-install step did not complete successfully`

**Comment by gromgit** [comment]
> `sudo chown -R 'jhome' /opt/homebrew/lib/python3.9/site-packages/pip/`

Since you have root-owned files in other Python packages as well, best to do:
```
sudo chown -R jhome /opt/homebrew/lib/python3.9/*
```
instead, then `brew reinstall python@3.9` and see if you're still getting errors.

**Comment by Jayanth-kumar5566** [comment]
That worked like a charm! Thanks!

**Comment by swilshire** [comment]
sudo chown -R $(whoami) /usr/local/lib/python3.9/*

...worked for me for what it is worth.
