### ISSUE TITLE
missing command to get formula path: `brew which`

### ISSUE THREAD

**Issue by timotheecour** [Homebrew/homebrew-core#8935]
IMO `brew edit X` and `brew cat X` are kind of useless, what's missing is something like `brew which X` which would return the filename where the formula is defined, eg:

```
brew which mongodb
/home/timothee/.linuxbrew/Library/Taps/homebrew/homebrew-core/Formula/mongodb.rb
```

with this:
```
#brew edit X
$EDITOR `brew which X`

#brew cat X
cat `brew which X`
```

however, parsing the output of `brew edit` to get `brew which` is not great at all:
* it could be slow (has to open an editor)
* could be non-trivial to parse output to get the corresponding path, eg in some system i got the following which would have to be parsed robustly to get the path i want:

```
brew edit mongodb
Editing /home/timothee/.linuxbrew/Library/Taps/homebrew/homebrew-core/Formula/mongodb.rb
Warning: Using edit because no editor was set in the environment.
This may change in the future, so we recommend setting EDITOR, VISUAL,
or HOMEBREW_EDITOR to your pref
```

Conclusion: could we add a `brew which` ?

**Comment by ilovezfs** [comment]
>IMO brew edit X and brew cat X are kind of useless, what's missing is something like brew which X which would return the filename where the formula is defined

I use these constantly.

```
alias bfp='brew ruby -e "puts ARGV[0].f.path"'
```
That works.

**Comment by timotheecour** [comment]
Could you elaborate please?

```
alias bfp='brew ruby -e "puts ARGV[0].f.path"'
bfp mongodb
Error: Unknown command: ruby
which ruby
/usr/bin/ruby
```

**Comment by ilovezfs** [comment]
Oh I forget everyone doesn't have it tapped.

```
brew tap homebrew/dev-tools 
```

**Comment by timotheecour** [comment]
```
bfp mongodb
/usr/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in `require': /home/timothee/.linuxbrew/Library/Homebrew/utils.rb:48: syntax error, unexpected tLABEL (SyntaxError)
...od, replacement = nil, disable: false, disable_on: nil, call...
...                               ^
/home/timothee/.linuxbrew/Library/Homebrew/utils.rb:48: Can't assign to false
...lacement = nil, disable: false, disable_on: nil, caller: sen...
...                               ^
/home/timothee/.linuxbrew/Library/Homebrew/utils.rb:48: Can't assign to nil
...isable: false, disable_on: nil, caller: send(:caller))
...                               ^
/home/timothee/.linuxbrew/Library/Homebrew/utils.rb:48: syntax error, unexpected ')', expecting $end
        from /usr/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
        from /home/timothee/.linuxbrew/Library/Homebrew/extend/pathname.rb:4:in `<top (required)>'
        from /usr/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
        from /usr/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
        from /home/timothee/.linuxbrew/Library/Homebrew/global.rb:3:in `<top (required)>'
        from /usr/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
        from /usr/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
```

**Comment by ilovezfs** [comment]
That's Linuxbrew, so I will plead ignorance ;)

**Comment by ilovezfs** [comment]
We'd consider a PR for such a command but no one is actively working on it.
