### ISSUE TITLE
Error: private method `installed_on_request' called for #<FormulaInstaller:0x007fcf84b65188>

### ISSUE THREAD

**Issue by mlevin2** [Homebrew/homebrew-core#9034]
Hi,

As of this morning I'm getting an error `Error: private method `installed_on_request' called for #<FormulaInstaller:0x007fcf84b65188>` when I try to do a `brew upgrade`.

Details are below:

```
$ brew doctor
Your system is ready to brew.
$ brew update
Already up-to-date.
$ brew upgrade
==> Upgrading 7 outdated packages, with result:
aria2 1.31.0, certbot 0.10.1_1, gtk+3 3.22.7, httrack 3.48.22, libtasn1 4.10, homebrew/python/numpy 1.12.0, poppler 0.51.0
Error: private method `installed_on_request' called for #<FormulaInstaller:0x007fcf84b65188>
Please report this bug:
  http://docs.brew.sh/Troubleshooting.html
/usr/local/Homebrew/Library/Homebrew/cmd/upgrade.rb:113:in `upgrade_formula'
/usr/local/Homebrew/Library/Homebrew/cmd/upgrade.rb:79:in `block in upgrade'
/usr/local/Homebrew/Library/Homebrew/cmd/upgrade.rb:78:in `each'
/usr/local/Homebrew/Library/Homebrew/cmd/upgrade.rb:78:in `upgrade'
/usr/local/Homebrew/Library/Homebrew/brew.rb:94:in `<main>'
$ brew config
HOMEBREW_VERSION: 1.1.7-68-gaa926a1bd
ORIGIN: https://github.com/Homebrew/brew.git
HEAD: aa926a1bdf722e628455713d1450604988ac2928
Last commit: 12 minutes ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 1835d06629923925107ca3fbcd3d174e2070a032
Core tap last commit: 3 hours ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_REPOSITORY: /usr/local/Homebrew
HOMEBREW_CELLAR: /usr/local/Cellar
HOMEBREW_BOTTLE_DOMAIN: https://homebrew.bintray.com
CPU: octa-core 64-bit haswell
Homebrew Ruby: 2.0.0-p648
GCC-4.2: build 5666
Clang: 8.0 build 800
Git: 2.11.0 => /usr/local/bin/git
Perl: /usr/bin/perl
Python: /usr/local/bin/python => /usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/bin/python2.7
Ruby: /usr/local/bin/ruby => /usr/local/Cellar/ruby/2.4.0/bin/ruby
Java: 1.8.0_102, 1.8.0_92, 1.8.0_76, 1.8.0_74, 1.8.0_60, 1.7.0_76
macOS: 10.11.6-x86_64
Xcode: 8.2
CLT: 8.2.0.0.1.1480973914
X11: 2.7.11 => /opt/X11
```

**Comment by Saklad5** [comment]
I was actually in the middle of reporting this. It just started?

**Comment by MikeMcQuaid** [comment]
Yes. I'm looking at it.

**Comment by Saklad5** [comment]
I just realized that we are putting this in the wrong repository: this should go in [Homebrew/brew](https://github.com/Homebrew/brew). Oh well.

Anyway, I think I found the cause: [this commit](https://github.com/Homebrew/brew/commit/aa926a1bdf722e628455713d1450604988ac2928).

**Comment by ddgenome** [comment]
I'm seeing this too.

**Comment by MikeMcQuaid** [comment]
Temporary  fix https://github.com/Homebrew/brew/commit/5424db12637917c159aca231d7e18ecfdcc8315b

**Comment by ddgenome** [comment]
Working again, thanks.

**Comment by MikeMcQuaid** [comment]
I've pushed a new commit in f0249643d that should fix this properly.

**Comment by ddgenome** [comment]
That also works for me, thanks.
