### ISSUE TITLE
Bottled Python unable to import shared libraries on macOS Big Sur

### ISSUE THREAD

**Issue by robd003** [Homebrew/homebrew-core#91821]
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

```shell
brew config:
HOMEBREW_VERSION: 3.3.9
ORIGIN: https://github.com/Homebrew/brew
HEAD: 96137bc19e68398ebbb7033379df288cd8b9a3f9
Last commit: 4 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: e4cb2eac5c504056fa8dfa5411408d22ea4993fd
Core tap last commit: 4 hours ago
Core tap branch: master
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_CORE_GIT_REMOTE: https://github.com/Homebrew/homebrew-core
HOMEBREW_EDITOR: vi
HOMEBREW_GITHUB_API_TOKEN: set
HOMEBREW_MAKE_JOBS: 10
Homebrew Ruby: 2.6.8 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: 10-core 64-bit arm_firestorm_icestorm
Clang: 13.0.0 build 1300
Git: 2.32.0 => /Applications/Xcode.app/Contents/Developer/usr/bin/git
Curl: 7.77.0 => /usr/bin/curl
macOS: 12.2-arm64
CLT: 13.2.0.0.1.1638488800
Xcode: 13.2.1
Rosetta 2: false

brew doctor:
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: Some installed formulae are deprecated or disabled.
You should find replacements for the following formulae:
  libelf

Warning: Unbrewed dylibs were found in /usr/local/lib.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected dylibs:
  /usr/local/lib/libvigraimpex.11.1.11.1.dylib

Warning: Unbrewed header files were found in /usr/local/include.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected header files:
  /usr/local/include/vigra/windows.h
```

### Verification

- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.

### What were you trying to do (and why)?

Load libraries with Python CFFI

### What happened (include all command output)?

It seems like there's some kind of linking error with the Bottled version of Python on macOS Big Sur. It's unable to read C / C++ libraries that were built as python modules.

Example:
$ python3.9
```
Python 3.9.9 (main, Nov 21 2021, 03:16:13) 
[Clang 13.0.0 (clang-1300.0.29.3)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import coincurve
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/robd/code/lbry-sdk/env/lib/python3.9/site-packages/coincurve-16.0.0-py3.9-macosx-12-arm64.egg/coincurve/__init__.py", line 1, in <module>
    from coincurve.context import GLOBAL_CONTEXT, Context
  File "/Users/robd/code/lbry-sdk/env/lib/python3.9/site-packages/coincurve-16.0.0-py3.9-macosx-12-arm64.egg/coincurve/context.py", line 4, in <module>
    from coincurve.flags import CONTEXT_ALL, CONTEXT_FLAGS
  File "/Users/robd/code/lbry-sdk/env/lib/python3.9/site-packages/coincurve-16.0.0-py3.9-macosx-12-arm64.egg/coincurve/flags.py", line 1, in <module>
    from ._libsecp256k1 import lib
ImportError: dlopen(/Users/robd/code/lbry-sdk/env/lib/python3.9/site-packages/coincurve-16.0.0-py3.9-macosx-12-arm64.egg/coincurve/_libsecp256k1.cpython-39-darwin.so, 0x0002): symbol not found in flat namespace '_secp256k1_nonce_function_default'
```

However if you look at the symbols for the library the function '_secp256k1_nonce_function_default' exists.

$ nm -g env/lib/python3.9/site-packages/coincurve-16.0.0-py3.9-macosx-12-arm64.egg/coincurve/_libsecp256k1.cpython-39-darwin.so
```
                 U _PyArg_UnpackTuple
                 U _PyErr_Occurred
                 U _PyEval_RestoreThread
                 U _PyEval_SaveThread
                 U _PyImport_ImportModule
0000000000001998 T _PyInit__libsecp256k1
                 U _PyLong_FromLong
                 U _PyLong_FromVoidPtr
                 U _PyObject_CallMethod
                 U _PyObject_Free
                 U _PyObject_Malloc
                 U __Py_Dealloc
                 U __Py_NoneStruct
                 U ___chkstk_darwin
                 U ___stack_chk_fail
                 U ___stack_chk_guard
                 U _bzero
                 U _secp256k1_context_clone
                 U _secp256k1_context_create
                 U _secp256k1_context_destroy
                 U _secp256k1_context_randomize
                 U _secp256k1_context_set_error_callback
                 U _secp256k1_context_set_illegal_callback
                 U _secp256k1_ec_privkey_tweak_add
                 U _secp256k1_ec_privkey_tweak_mul
                 U _secp256k1_ec_pubkey_combine
                 U _secp256k1_ec_pubkey_create
                 U _secp256k1_ec_pubkey_parse
                 U _secp256k1_ec_pubkey_serialize
                 U _secp256k1_ec_pubkey_tweak_add
                 U _secp256k1_ec_pubkey_tweak_mul
                 U _secp256k1_ec_seckey_verify
                 U _secp256k1_ecdh
                 U _secp256k1_ecdsa_recover
                 U _secp256k1_ecdsa_recoverable_signature_convert
                 U _secp256k1_ecdsa_recoverable_signature_parse_compact
                 U _secp256k1_ecdsa_recoverable_signature_serialize_compact
                 U _secp256k1_ecdsa_sign
                 U _secp256k1_ecdsa_sign_recoverable
                 U _secp256k1_ecdsa_signature_normalize
                 U _secp256k1_ecdsa_signature_parse_compact
                 U _secp256k1_ecdsa_signature_parse_der
                 U _secp256k1_ecdsa_signature_serialize_compact
                 U _secp256k1_ecdsa_signature_serialize_der
                 U _secp256k1_ecdsa_verify
                 U _secp256k1_nonce_function_default
                 U _secp256k1_nonce_function_rfc6979
                 U dyld_stub_binder
```

### What did you expect to happen?

The library to load.

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
brew install python@3.9

pip3.9 install coincurve

python3.9

>>> import coincurve
```

This happens with just about any C / C++ library built by the bottled Python
```

**Comment by SMillerDev** [comment]
Is that library also compiled for ARM? 
Because it's not coming from Homebrew I can't really check it locally.

But if it's an x86 library that you're reading using an ARM python that will explain your misterious errors.

**Comment by carlocab** [comment]
```
                 U _secp256k1_nonce_function_default
```
The `U` means that `_libsecp256k1.cpython-39-darwin.so` uses `_secp256k1_nonce_function_default` but doesn't define it. (See `man nm`.) Are you sure you have the library that defines this symbol available?

**Comment by robd003** [comment]
> Is that library also compiled for ARM? Because it's not coming from Homebrew I can't really check it locally.
> 
> But if it's an x86 library that you're reading using an ARM python that will explain your misterious errors.

@SMillerDev It's compiled as arm64:

```
file _libsecp256k1.cpython-310-darwin.so 
_libsecp256k1.cpython-310-darwin.so: Mach-O 64-bit bundle arm64
```

**Comment by robd003** [comment]
> Is that library also compiled for ARM? Because it's not coming from Homebrew I can't really check it locally.
> 
> But if it's an x86 library that you're reading using an ARM python that will explain your misterious errors.

@SMillerDev It's compiled as arm64:

```
file _libsecp256k1.cpython-39-darwin.so 
_libsecp256k1.cpython-39-darwin.so: Mach-O 64-bit bundle arm64
```

**Comment by robd003** [comment]
@SMillerDev you can try doing `pip install coincurve` and then try loading that module in Python.
