### ISSUE TITLE
Groovy: launching groovysh throws UnsatisfiedLinkError: Could not load library

### ISSUE THREAD

**Issue by VonUniGE** [Homebrew/homebrew-core#92441]
```shell
$ brew config

HOMEBREW_VERSION: 3.3.9-103-ga0ae4a7
ORIGIN: https://github.com/Homebrew/brew
HEAD: a0ae4a7a02d9b6d886fb99a23ddbe07af7979fb6
Last commit: 14 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 7844861bc8428f5659fc0c04f476b9f925856736
Core tap last commit: 25 minutes ago
Core tap branch: master
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_CORE_GIT_REMOTE: https://github.com/Homebrew/homebrew-core
HOMEBREW_EDITOR: /usr/bin/vim
HOMEBREW_MAKE_JOBS: 8
Homebrew Ruby: 2.6.8 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: octa-core 64-bit arm_firestorm_icestorm
Clang: 13.0.0 build 1300
Git: 2.32.0 => /Library/Developer/CommandLineTools/usr/bin/git
Curl: 7.77.0 => /usr/bin/curl
macOS: 12.1-arm64
CLT: 13.2.0.0.1.1638488800
Xcode: N/A
Rosetta 2: false
````

````
$ brew doctor

Your system is ready to brew.
````

### Verification

- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.

### What were you trying to do (and why)?

Launch groovysh

### What happened (include all command output)?

````
$ groovysh

java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.codehaus.groovy.tools.GroovyStarter.rootLoader(GroovyStarter.java:111)
	at org.codehaus.groovy.tools.GroovyStarter.main(GroovyStarter.java:129)
Caused by: java.lang.UnsatisfiedLinkError: Could not load library. Reasons: [no jansi in java.library.path: [/Users/von/Library/Java/Extensions, /Library/Java/Extensions, /Network/Library/Java/Extensions, /System/Library/Java/Extensions, /usr/lib/java, .], /private/var/folders/5y/24qs1_mj41555qsdgs94h6s00000gn/T/libjansi-64-17060936816107880730.jnilib: dlopen(/private/var/folders/5y/24qs1_mj41555qsdgs94h6s00000gn/T/libjansi-64-17060936816107880730.jnilib, 0x0001): tried: '/private/var/folders/5y/24qs1_mj41555qsdgs94h6s00000gn/T/libjansi-64-17060936816107880730.jnilib' (fat file, but missing compatible architecture (have 'x86_64,i386', need 'arm64e')), '/usr/local/lib/libjansi-64-17060936816107880730.jnilib' (no such file), '/usr/lib/libjansi-64-17060936816107880730.jnilib' (no such file)]
	at org.fusesource.hawtjni.runtime.Library.doLoad(Library.java:182)
	at org.fusesource.hawtjni.runtime.Library.load(Library.java:140)
	at org.fusesource.jansi.internal.CLibrary.<clinit>(CLibrary.java:42)
	at org.fusesource.jansi.AnsiConsole.wrapOutputStream(AnsiConsole.java:48)
	at org.fusesource.jansi.AnsiConsole.<clinit>(AnsiConsole.java:38)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:398)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.lambda$createCallStaticSite$2(CallSiteArray.java:65)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.createCallStaticSite(CallSiteArray.java:63)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.createCallSite(CallSiteArray.java:156)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:125)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:130)
	at org.apache.groovy.groovysh.Main.installAnsi(Main.groovy:249)
	at org.apache.groovy.groovysh.Main.setTerminalType(Main.groovy:235)
	at org.apache.groovy.groovysh.Main.main(Main.groovy:120)
	... 6 more
````

### What did you expect to happen?

Obtain a groovy shell

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
$ brew install groovy

$ groovysh
```

**Comment by alebcay** [comment]
I made an attempt at building the missing JNI library for Apple Silicon in #92477 but it leads to a segfault when trying to run `groovysh` (this segfault also seems to happen on x86_64 when using a manually built JNI library, so maybe there's a configuration issue somewhere).

**Comment by VonUniGE** [comment]
This is an upstream issue: https://issues.apache.org/jira/browse/GROOVY-9869

**Comment by alebcay** [comment]
The issue linked is not actually what we're running into. Jansi appears in the Groovy dependency tree at least twice - once as a direct dependency and once as a nested dependency of JLine.

The direct dependency has been updated and that issue closed (what you linked above). However, it seems that the version of JLine used is still too old, as the version of JLine still bundles a copy of Jansi 1.x, which does not support Apple Silicon.

**Comment by rgbworld** [comment]
I have this same issue. I cannot run `groovysh`.

`Could not load library. Reasons: [no jansi in java.library.path: [/Users/von/Library/Java/Extensions, /Library/Java/Extensions, /Network/Library/Java/Extensions, ...`

M1 mac

**Comment by gallyamb** [comment]
Same for me
```
➜  ~ groovysh
java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.codehaus.groovy.tools.GroovyStarter.rootLoader(GroovyStarter.java:111)
	at org.codehaus.groovy.tools.GroovyStarter.main(GroovyStarter.java:129)
Caused by: java.lang.UnsatisfiedLinkError: Could not load library. Reasons: [no jansi in java.library.path: /Users/gallyamb/Library/Java/Extensions:/Library/Java/Extensions:/Network/Library/Java/Extensions:/System/Library/Java/Extensions:/usr/lib/java:., Can't load library: /var/folders/h4/fl4548j93qj10xqylq3rdwl40jtchm/T/libjansi-64-12562976176184592142.jnilib]
	at org.fusesource.hawtjni.runtime.Library.doLoad(Library.java:182)
	at org.fusesource.hawtjni.runtime.Library.load(Library.java:140)
	at org.fusesource.jansi.internal.CLibrary.<clinit>(CLibrary.java:42)
	at org.fusesource.jansi.AnsiConsole.wrapOutputStream(AnsiConsole.java:48)
	at org.fusesource.jansi.AnsiConsole.<clinit>(AnsiConsole.java:38)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:467)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.lambda$createCallStaticSite$2(CallSiteArray.java:65)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:318)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.createCallStaticSite(CallSiteArray.java:63)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.createCallSite(CallSiteArray.java:156)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:125)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:130)
	at org.apache.groovy.groovysh.Main.installAnsi(Main.groovy:249)
	at org.apache.groovy.groovysh.Main.setTerminalType(Main.groovy:235)
	at org.apache.groovy.groovysh.Main.main(Main.groovy:120)
	... 6 more
```

**Comment by hnjylwb** [comment]
Same here for M1 mac

**Comment by rgbworld** [comment]
Reopening this because it closed by a bot and the problem still exists.

**Comment by mbarretta** [comment]
+ same issue:

```
  % brew config                                                                                                                                                                       !158
HOMEBREW_VERSION: 3.4.5
ORIGIN: https://github.com/Homebrew/brew
HEAD: 33709297cf9cb37605cf4efcb7151905baf8ccf5
Last commit: 4 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 2d9167c7b8dd639a6de96087a834c171d14afeea
Core tap last commit: 14 hours ago
Core tap branch: master
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_CORE_GIT_REMOTE: https://github.com/Homebrew/homebrew-core
HOMEBREW_MAKE_JOBS: 10
Homebrew Ruby: 2.6.8 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: 10-core 64-bit arm_firestorm_icestorm
Clang: 13.1.6 build 1316
Git: 2.35.1 => /opt/homebrew/bin/git
Curl: 7.79.1 => /usr/bin/curl
macOS: 12.3-arm64
CLT: 13.3.0.0.1.1645755326
Xcode: N/A
Rosetta 2: false
```
