### ISSUE TITLE
Some files installed by "sshuttle" only readable by user that made the install

### ISSUE THREAD

**Issue by Feuermurmel** [Homebrew/homebrew-core#92551]
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

```shell
admin ~ % /opt/homebrew/bin/brew gist-logs sshuttle
Error: No logs.
```

```
admin ~ % /opt/homebrew/bin/brew config            
HOMEBREW_VERSION: 3.3.9
ORIGIN: https://github.com/Homebrew/brew
HEAD: 96137bc19e68398ebbb7033379df288cd8b9a3f9
Last commit: 3 weeks ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 8a007f7a85cbe6d225e7e271ff9d2b793bba5608
Core tap last commit: 37 minutes ago
Core tap branch: master
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_CORE_GIT_REMOTE: https://github.com/Homebrew/homebrew-core
HOMEBREW_MAKE_JOBS: 8
Homebrew Ruby: 2.6.8 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: octa-core 64-bit arm_firestorm_icestorm
Clang: 13.0.0 build 1300
Git: 2.32.0 => /Applications/Xcode.app/Contents/Developer/usr/bin/git
Curl: 7.77.0 => /usr/bin/curl
macOS: 12.1-arm64
CLT: 13.2.0.0.1.1638488800
Xcode: 13.2.1
Rosetta 2: false
```

```
admin ~ % /opt/homebrew/bin/brew doctor
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: Homebrew's "bin" was not found in your PATH.
Consider setting your PATH for example like so:
  echo 'export PATH="/opt/homebrew/bin:$PATH"' >> ~/.zshrc
```

### Verification

- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.

### What were you trying to do (and why)?

I'd like to install and run sshuttle. I have multiple user accounts (separating work/non-work) and all should be able to run software installed via Homebrew. In the test below I used a third user `admin` to install Homebrew and `sshuttle` and try to run it as another users, which fails.

To try to reproduce the problem as simply as possible, I used an account without any `.bashrc`/`.zshrc`/etc. files. Putting `/opt/homebrew/bin` on `$PATH` does not remove the issue though.

### What happened (include all command output)?

Installing Homebrew from scratch:

```
admin ~ % sudo rm -rf /opt/homebrew
Password:
admin ~ % /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
==> Checking for `sudo` access (which may request your password)...
==> This script will install:
/opt/homebrew/bin/brew
/opt/homebrew/share/doc/homebrew
/opt/homebrew/share/man/man1/brew.1
/opt/homebrew/share/zsh/site-functions/_brew
/opt/homebrew/etc/bash_completion.d/brew
/opt/homebrew
==> The following new directories will be created:
/opt/homebrew/bin
/opt/homebrew/etc
/opt/homebrew/include
/opt/homebrew/lib
/opt/homebrew/sbin
/opt/homebrew/share
/opt/homebrew/var
/opt/homebrew/opt
/opt/homebrew/share/zsh
/opt/homebrew/share/zsh/site-functions
/opt/homebrew/var/homebrew
/opt/homebrew/var/homebrew/linked
/opt/homebrew/Cellar
/opt/homebrew/Caskroom
/opt/homebrew/Frameworks

Press RETURN to continue or any other key to abort:
==> /usr/bin/sudo /bin/mkdir -p /opt/homebrew
==> /usr/bin/sudo /usr/sbin/chown root:wheel /opt/homebrew
==> /usr/bin/sudo /bin/mkdir -p /opt/homebrew/bin /opt/homebrew/etc /opt/homebrew/include /opt/homebrew/lib /opt/homebrew/sbin /opt/homebrew/share /opt/homebrew/var /opt/homebrew/opt /opt/homebrew/share/zsh /opt/homebrew/share/zsh/site-functions /opt/homebrew/var/homebrew /opt/homebrew/var/homebrew/linked /opt/homebrew/Cellar /opt/homebrew/Caskroom /opt/homebrew/Frameworks
==> /usr/bin/sudo /bin/chmod ug=rwx /opt/homebrew/bin /opt/homebrew/etc /opt/homebrew/include /opt/homebrew/lib /opt/homebrew/sbin /opt/homebrew/share /opt/homebrew/var /opt/homebrew/opt /opt/homebrew/share/zsh /opt/homebrew/share/zsh/site-functions /opt/homebrew/var/homebrew /opt/homebrew/var/homebrew/linked /opt/homebrew/Cellar /opt/homebrew/Caskroom /opt/homebrew/Frameworks
==> /usr/bin/sudo /bin/chmod go-w /opt/homebrew/share/zsh /opt/homebrew/share/zsh/site-functions
==> /usr/bin/sudo /usr/sbin/chown admin /opt/homebrew/bin /opt/homebrew/etc /opt/homebrew/include /opt/homebrew/lib /opt/homebrew/sbin /opt/homebrew/share /opt/homebrew/var /opt/homebrew/opt /opt/homebrew/share/zsh /opt/homebrew/share/zsh/site-functions /opt/homebrew/var/homebrew /opt/homebrew/var/homebrew/linked /opt/homebrew/Cellar /opt/homebrew/Caskroom /opt/homebrew/Frameworks
==> /usr/bin/sudo /usr/bin/chgrp admin /opt/homebrew/bin /opt/homebrew/etc /opt/homebrew/include /opt/homebrew/lib /opt/homebrew/sbin /opt/homebrew/share /opt/homebrew/var /opt/homebrew/opt /opt/homebrew/share/zsh /opt/homebrew/share/zsh/site-functions /opt/homebrew/var/homebrew /opt/homebrew/var/homebrew/linked /opt/homebrew/Cellar /opt/homebrew/Caskroom /opt/homebrew/Frameworks
==> /usr/bin/sudo /usr/sbin/chown -R admin:admin /opt/homebrew
==> Downloading and installing Homebrew...
remote: Enumerating objects: 200076, done.
remote: Counting objects: 100% (934/934), done.
remote: Compressing objects: 100% (502/502), done.
remote: Total 200076 (delta 476), reused 807 (delta 375), pack-reused 199142
Receiving objects: 100% (200076/200076), 55.06 MiB | 10.54 MiB/s, done.
Resolving deltas: 100% (147704/147704), done.
From https://github.com/Homebrew/brew
 * [new branch]          fxcoudert-patch-1 -> origin/fxcoudert-patch-1
 * [new branch]          master            -> origin/master
 * [new tag]             0.1               -> 0.1
 * [new tag]             0.2               -> 0.2
 * [new tag]             0.3               -> 0.3
 * [new tag]             0.4               -> 0.4
 * [new tag]             0.5               -> 0.5
 * [new tag]             0.6               -> 0.6
 * [new tag]             0.7               -> 0.7
 * [new tag]             0.7.1             -> 0.7.1
 * [new tag]             0.8               -> 0.8
 * [new tag]             0.8.1             -> 0.8.1
 * [new tag]             0.9               -> 0.9
 * [new tag]             0.9.1             -> 0.9.1
 * [new tag]             0.9.2             -> 0.9.2
 * [new tag]             0.9.3             -> 0.9.3
 * [new tag]             0.9.4             -> 0.9.4
 * [new tag]             0.9.5             -> 0.9.5
 * [new tag]             0.9.8             -> 0.9.8
 * [new tag]             0.9.9             -> 0.9.9
 * [new tag]             1.0.0             -> 1.0.0
 * [new tag]             1.0.1             -> 1.0.1
 * [new tag]             1.0.2             -> 1.0.2
 * [new tag]             1.0.3             -> 1.0.3
 * [new tag]             1.0.4             -> 1.0.4
 * [new tag]             1.0.5             -> 1.0.5
 * [new tag]             1.0.6             -> 1.0.6
 * [new tag]             1.0.7             -> 1.0.7
 * [new tag]             1.0.8             -> 1.0.8
 * [new tag]             1.0.9             -> 1.0.9
 * [new tag]             1.1.0             -> 1.1.0
 * [new tag]             1.1.1             -> 1.1.1
 * [new tag]             1.1.10            -> 1.1.10
 * [new tag]             1.1.11            -> 1.1.11
 * [new tag]             1.1.12            -> 1.1.12
 * [new tag]             1.1.13            -> 1.1.13
 * [new tag]             1.1.2             -> 1.1.2
 * [new tag]             1.1.3             -> 1.1.3
 * [new tag]             1.1.4             -> 1.1.4
 * [new tag]             1.1.5             -> 1.1.5
 * [new tag]             1.1.6             -> 1.1.6
 * [new tag]             1.1.7             -> 1.1.7
 * [new tag]             1.1.8             -> 1.1.8
 * [new tag]             1.1.9             -> 1.1.9
 * [new tag]             1.2.0             -> 1.2.0
 * [new tag]             1.2.1             -> 1.2.1
 * [new tag]             1.2.2             -> 1.2.2
 * [new tag]             1.2.3             -> 1.2.3
 * [new tag]             1.2.4             -> 1.2.4
 * [new tag]             1.2.5             -> 1.2.5
 * [new tag]             1.2.6             -> 1.2.6
 * [new tag]             1.3.0             -> 1.3.0
 * [new tag]             1.3.1             -> 1.3.1
 * [new tag]             1.3.2             -> 1.3.2
 * [new tag]             1.3.3             -> 1.3.3
 * [new tag]             1.3.4             -> 1.3.4
 * [new tag]             1.3.5             -> 1.3.5
 * [new tag]             1.3.6             -> 1.3.6
 * [new tag]             1.3.7             -> 1.3.7
 * [new tag]             1.3.8             -> 1.3.8
 * [new tag]             1.3.9             -> 1.3.9
 * [new tag]             1.4.0             -> 1.4.0
 * [new tag]             1.4.1             -> 1.4.1
 * [new tag]             1.4.2             -> 1.4.2
 * [new tag]             1.4.3             -> 1.4.3
 * [new tag]             1.5.0             -> 1.5.0
 * [new tag]             1.5.1             -> 1.5.1
 * [new tag]             1.5.10            -> 1.5.10
 * [new tag]             1.5.11            -> 1.5.11
 * [new tag]             1.5.12            -> 1.5.12
 * [new tag]             1.5.13            -> 1.5.13
 * [new tag]             1.5.14            -> 1.5.14
 * [new tag]             1.5.2             -> 1.5.2
 * [new tag]             1.5.3             -> 1.5.3
 * [new tag]             1.5.4             -> 1.5.4
 * [new tag]             1.5.5             -> 1.5.5
 * [new tag]             1.5.6             -> 1.5.6
 * [new tag]             1.5.7             -> 1.5.7
 * [new tag]             1.5.8             -> 1.5.8
 * [new tag]             1.5.9             -> 1.5.9
 * [new tag]             1.6.0             -> 1.6.0
 * [new tag]             1.6.1             -> 1.6.1
 * [new tag]             1.6.10            -> 1.6.10
 * [new tag]             1.6.11            -> 1.6.11
 * [new tag]             1.6.12            -> 1.6.12
 * [new tag]             1.6.13            -> 1.6.13
 * [new tag]             1.6.14            -> 1.6.14
 * [new tag]             1.6.15            -> 1.6.15
 * [new tag]             1.6.16            -> 1.6.16
 * [new tag]             1.6.17            -> 1.6.17
 * [new tag]             1.6.2             -> 1.6.2
 * [new tag]             1.6.3             -> 1.6.3
 * [new tag]             1.6.4             -> 1.6.4
 * [new tag]             1.6.5             -> 1.6.5
 * [new tag]             1.6.6             -> 1.6.6
 * [new tag]             1.6.7             -> 1.6.7
 * [new tag]             1.6.8             -> 1.6.8
 * [new tag]             1.6.9             -> 1.6.9
 * [new tag]             1.7.0             -> 1.7.0
 * [new tag]             1.7.1             -> 1.7.1
 * [new tag]             1.7.2             -> 1.7.2
 * [new tag]             1.7.3             -> 1.7.3
 * [new tag]             1.7.4             -> 1.7.4
 * [new tag]             1.7.5             -> 1.7.5
 * [new tag]             1.7.6             -> 1.7.6
 * [new tag]             1.7.7             -> 1.7.7
 * [new tag]             1.8.0             -> 1.8.0
 * [new tag]             1.8.1             -> 1.8.1
 * [new tag]             1.8.2             -> 1.8.2
 * [new tag]             1.8.3             -> 1.8.3
 * [new tag]             1.8.4             -> 1.8.4
 * [new tag]             1.8.5             -> 1.8.5
 * [new tag]             1.8.6             -> 1.8.6
 * [new tag]             1.9.0             -> 1.9.0
 * [new tag]             1.9.1             -> 1.9.1
 * [new tag]             1.9.2             -> 1.9.2
 * [new tag]             1.9.3             -> 1.9.3
 * [new tag]             2.0.0             -> 2.0.0
 * [new tag]             2.0.1             -> 2.0.1
 * [new tag]             2.0.2             -> 2.0.2
 * [new tag]             2.0.3             -> 2.0.3
 * [new tag]             2.0.4             -> 2.0.4
 * [new tag]             2.0.5             -> 2.0.5
 * [new tag]             2.0.6             -> 2.0.6
 * [new tag]             2.1.0             -> 2.1.0
 * [new tag]             2.1.1             -> 2.1.1
 * [new tag]             2.1.10            -> 2.1.10
 * [new tag]             2.1.11            -> 2.1.11
 * [new tag]             2.1.12            -> 2.1.12
 * [new tag]             2.1.13            -> 2.1.13
 * [new tag]             2.1.14            -> 2.1.14
 * [new tag]             2.1.15            -> 2.1.15
 * [new tag]             2.1.16            -> 2.1.16
 * [new tag]             2.1.2             -> 2.1.2
 * [new tag]             2.1.3             -> 2.1.3
 * [new tag]             2.1.4             -> 2.1.4
 * [new tag]             2.1.5             -> 2.1.5
 * [new tag]             2.1.6             -> 2.1.6
 * [new tag]             2.1.7             -> 2.1.7
 * [new tag]             2.1.8             -> 2.1.8
 * [new tag]             2.1.9             -> 2.1.9
 * [new tag]             2.2.0             -> 2.2.0
 * [new tag]             2.2.1             -> 2.2.1
 * [new tag]             2.2.10            -> 2.2.10
 * [new tag]             2.2.11            -> 2.2.11
 * [new tag]             2.2.12            -> 2.2.12
 * [new tag]             2.2.13            -> 2.2.13
 * [new tag]             2.2.14            -> 2.2.14
 * [new tag]             2.2.15            -> 2.2.15
 * [new tag]             2.2.16            -> 2.2.16
 * [new tag]             2.2.17            -> 2.2.17
 * [new tag]             2.2.2             -> 2.2.2
 * [new tag]             2.2.3             -> 2.2.3
 * [new tag]             2.2.4             -> 2.2.4
 * [new tag]             2.2.5             -> 2.2.5
 * [new tag]             2.2.6             -> 2.2.6
 * [new tag]             2.2.7             -> 2.2.7
 * [new tag]             2.2.8             -> 2.2.8
 * [new tag]             2.2.9             -> 2.2.9
 * [new tag]             2.3.0             -> 2.3.0
 * [new tag]             2.4.0             -> 2.4.0
 * [new tag]             2.4.1             -> 2.4.1
 * [new tag]             2.4.10            -> 2.4.10
 * [new tag]             2.4.11            -> 2.4.11
 * [new tag]             2.4.12            -> 2.4.12
 * [new tag]             2.4.13            -> 2.4.13
 * [new tag]             2.4.14            -> 2.4.14
 * [new tag]             2.4.15            -> 2.4.15
 * [new tag]             2.4.16            -> 2.4.16
 * [new tag]             2.4.2             -> 2.4.2
 * [new tag]             2.4.3             -> 2.4.3
 * [new tag]             2.4.4             -> 2.4.4
 * [new tag]             2.4.5             -> 2.4.5
 * [new tag]             2.4.6             -> 2.4.6
 * [new tag]             2.4.7             -> 2.4.7
 * [new tag]             2.4.8             -> 2.4.8
 * [new tag]             2.4.9             -> 2.4.9
 * [new tag]             2.5.0             -> 2.5.0
 * [new tag]             2.5.1             -> 2.5.1
 * [new tag]             2.5.10            -> 2.5.10
 * [new tag]             2.5.11            -> 2.5.11
 * [new tag]             2.5.12            -> 2.5.12
 * [new tag]             2.5.2             -> 2.5.2
 * [new tag]             2.5.3             -> 2.5.3
 * [new tag]             2.5.4             -> 2.5.4
 * [new tag]             2.5.5             -> 2.5.5
 * [new tag]             2.5.6             -> 2.5.6
 * [new tag]             2.5.7             -> 2.5.7
 * [new tag]             2.5.8             -> 2.5.8
 * [new tag]             2.5.9             -> 2.5.9
 * [new tag]             2.6.0             -> 2.6.0
 * [new tag]             2.6.1             -> 2.6.1
 * [new tag]             2.6.2             -> 2.6.2
 * [new tag]             2.7.0             -> 2.7.0
 * [new tag]             2.7.1             -> 2.7.1
 * [new tag]             2.7.2             -> 2.7.2
 * [new tag]             2.7.3             -> 2.7.3
 * [new tag]             2.7.4             -> 2.7.4
 * [new tag]             2.7.5             -> 2.7.5
 * [new tag]             2.7.6             -> 2.7.6
 * [new tag]             2.7.7             -> 2.7.7
 * [new tag]             3.0.0             -> 3.0.0
 * [new tag]             3.0.1             -> 3.0.1
 * [new tag]             3.0.10            -> 3.0.10
 * [new tag]             3.0.11            -> 3.0.11
 * [new tag]             3.0.2             -> 3.0.2
 * [new tag]             3.0.3             -> 3.0.3
 * [new tag]             3.0.4             -> 3.0.4
 * [new tag]             3.0.5             -> 3.0.5
 * [new tag]             3.0.6             -> 3.0.6
 * [new tag]             3.0.7             -> 3.0.7
 * [new tag]             3.0.8             -> 3.0.8
 * [new tag]             3.0.9             -> 3.0.9
 * [new tag]             3.1.0             -> 3.1.0
 * [new tag]             3.1.1             -> 3.1.1
 * [new tag]             3.1.10            -> 3.1.10
 * [new tag]             3.1.11            -> 3.1.11
 * [new tag]             3.1.12            -> 3.1.12
 * [new tag]             3.1.2             -> 3.1.2
 * [new tag]             3.1.3             -> 3.1.3
 * [new tag]             3.1.4             -> 3.1.4
 * [new tag]             3.1.5             -> 3.1.5
 * [new tag]             3.1.6             -> 3.1.6
 * [new tag]             3.1.7             -> 3.1.7
 * [new tag]             3.1.8             -> 3.1.8
 * [new tag]             3.1.9             -> 3.1.9
 * [new tag]             3.2.0             -> 3.2.0
 * [new tag]             3.2.1             -> 3.2.1
 * [new tag]             3.2.10            -> 3.2.10
 * [new tag]             3.2.11            -> 3.2.11
 * [new tag]             3.2.12            -> 3.2.12
 * [new tag]             3.2.13            -> 3.2.13
 * [new tag]             3.2.14            -> 3.2.14
 * [new tag]             3.2.15            -> 3.2.15
 * [new tag]             3.2.16            -> 3.2.16
 * [new tag]             3.2.17            -> 3.2.17
 * [new tag]             3.2.2             -> 3.2.2
 * [new tag]             3.2.3             -> 3.2.3
 * [new tag]             3.2.4             -> 3.2.4
 * [new tag]             3.2.5             -> 3.2.5
 * [new tag]             3.2.6             -> 3.2.6
 * [new tag]             3.2.7             -> 3.2.7
 * [new tag]             3.2.8             -> 3.2.8
 * [new tag]             3.2.9             -> 3.2.9
 * [new tag]             3.3.0             -> 3.3.0
 * [new tag]             3.3.1             -> 3.3.1
 * [new tag]             3.3.2             -> 3.3.2
 * [new tag]             3.3.3             -> 3.3.3
 * [new tag]             3.3.4             -> 3.3.4
 * [new tag]             3.3.5             -> 3.3.5
 * [new tag]             3.3.6             -> 3.3.6
 * [new tag]             3.3.7             -> 3.3.7
 * [new tag]             3.3.8             -> 3.3.8
 * [new tag]             3.3.9             -> 3.3.9
HEAD is now at 1105859c8 Merge pull request #12669 from Homebrew/dependabot/bundler/Library/Homebrew/rspec_junit_formatter-0.5.0
==> Tapping homebrew/core
remote: Enumerating objects: 1122422, done.
remote: Counting objects: 100% (100/100), done.
remote: Compressing objects: 100% (54/54), done.
remote: Total 1122422 (delta 58), reused 86 (delta 46), pack-reused 1122322
Receiving objects: 100% (1122422/1122422), 437.16 MiB | 10.76 MiB/s, done.
Resolving deltas: 100% (775149/775149), done.
From https://github.com/Homebrew/homebrew-core
 * [new branch]              master     -> origin/master
HEAD is now at 8a007f7a85c cdktf: update 0.8.4 bottle.
Warning: /opt/homebrew/bin is not in your PATH.
  Instructions on how to configure your shell for Homebrew
  can be found in the 'Next steps' section below.
==> Installation successful!

==> Homebrew has enabled anonymous aggregate formulae and cask analytics.
Read the analytics documentation (and how to opt-out) here:
  https://docs.brew.sh/Analytics
No analytics data has been sent yet (nor will any be during this install run).

==> Homebrew is run entirely by unpaid volunteers. Please consider donating:
  https://github.com/Homebrew/brew#donations

==> Next steps:
- Run these two commands in your terminal to add Homebrew to your PATH:
    echo 'eval "$(/opt/homebrew/bin/brew shellenv)"' >> /Users/admin/.zprofile
    eval "$(/opt/homebrew/bin/brew shellenv)"
- Run brew help to get started
- Further documentation:
    https://docs.brew.sh

```

Installing `sshuttle`:

```
admin ~ % /opt/homebrew/bin/brew install sshuttle
==> Downloading https://ghcr.io/v2/homebrew/core/gdbm/manifests/1.22
Already downloaded: /Users/admin/Library/Caches/Homebrew/downloads/e8b58066428135b278689a186abeaae951e5816cd8204e57b85c80b41adb13cc--gdbm-1.22.bottle_manifest.json
==> Downloading https://ghcr.io/v2/homebrew/core/gdbm/blobs/sha256:25cfaedb0fd8f
Already downloaded: /Users/admin/Library/Caches/Homebrew/downloads/79cddbc71979a3749644a793e742326f5ae03b943ba6137c38540d4199c1409a--gdbm--1.22.arm64_monterey.bottle.tar.gz
==> Downloading https://ghcr.io/v2/homebrew/core/mpdecimal/manifests/2.5.1
Already downloaded: /Users/admin/Library/Caches/Homebrew/downloads/f367c2ee08c56b88be0662703a8e4275f8657608a268c8c44e845154b0cea543--mpdecimal-2.5.1.bottle_manifest.json
==> Downloading https://ghcr.io/v2/homebrew/core/mpdecimal/blobs/sha256:726e8ec0
Already downloaded: /Users/admin/Library/Caches/Homebrew/downloads/ffb0c2f865ae1dafbb01e2e7d9772cf80bfaa1d725ec77730d2c3523eef8c6d0--mpdecimal--2.5.1.arm64_monterey.bottle.tar.gz
==> Downloading https://ghcr.io/v2/homebrew/core/ca-certificates/manifests/2021-
Already downloaded: /Users/admin/Library/Caches/Homebrew/downloads/b5cacbc629fba9719e906bfb01b11310bad8b389906e36cf04f3b415b2c61cf3--ca-certificates-2021-10-26.bottle_manifest.json
==> Downloading https://ghcr.io/v2/homebrew/core/ca-certificates/blobs/sha256:1b
Already downloaded: /Users/admin/Library/Caches/Homebrew/downloads/79ec4ac986e054c3e4138cc32553ebfc2eaf0a502bf9914308a075c02561ea13--ca-certificates--2021-10-26.all.bottle.tar.gz
==> Downloading https://ghcr.io/v2/homebrew/core/openssl/1.1/manifests/1.1.1m
Already downloaded: /Users/admin/Library/Caches/Homebrew/downloads/2bd04ba59408cbad6dce70fa2442a6c8997084cc474815d3a08863f9518dd9c9--openssl@1.1-1.1.1m.bottle_manifest.json
==> Downloading https://ghcr.io/v2/homebrew/core/openssl/1.1/blobs/sha256:b3a020
Already downloaded: /Users/admin/Library/Caches/Homebrew/downloads/e53e86306079d2bd4b0dbf613dd265ea043342303f242c8bd348e85c107db6e1--openssl@1.1--1.1.1m.arm64_monterey.bottle.tar.gz
==> Downloading https://ghcr.io/v2/homebrew/core/readline/manifests/8.1.1
Already downloaded: /Users/admin/Library/Caches/Homebrew/downloads/11817fbc41986210e339d9491c3e8026783c4b58c01d37c8f297bb06898f0ecf--readline-8.1.1.bottle_manifest.json
==> Downloading https://ghcr.io/v2/homebrew/core/readline/blobs/sha256:3b5aa5bdf
Already downloaded: /Users/admin/Library/Caches/Homebrew/downloads/71b34c1ac8e79770bbe5d300fb4bc1a5c220d210badf9d646f7d2b665b2d194c--readline--8.1.1.arm64_monterey.bottle.tar.gz
==> Downloading https://ghcr.io/v2/homebrew/core/sqlite/manifests/3.37.1
Already downloaded: /Users/admin/Library/Caches/Homebrew/downloads/7a48657aab70e097ec132c45ae20ac11cce0843906514fddb64d0f08862b56f8--sqlite-3.37.1.bottle_manifest.json
==> Downloading https://ghcr.io/v2/homebrew/core/sqlite/blobs/sha256:2e9774179ea
Already downloaded: /Users/admin/Library/Caches/Homebrew/downloads/bf91466c58e39642eb2b31d201bc393ead8dee7a14be56a78c60385e579e6024--sqlite--3.37.1.arm64_monterey.bottle.tar.gz
==> Downloading https://ghcr.io/v2/homebrew/core/xz/manifests/5.2.5
Already downloaded: /Users/admin/Library/Caches/Homebrew/downloads/9447dbb900ef03dd46277002d89d92c65920edee6c60ea22c33be6cf99d01dc6--xz-5.2.5.bottle_manifest.json
==> Downloading https://ghcr.io/v2/homebrew/core/xz/blobs/sha256:fcda3e81efe284f
Already downloaded: /Users/admin/Library/Caches/Homebrew/downloads/64dbe71f9204854898c794b9e289f4f607c483ef4d18e627b2b910c60fbb32fe--xz--5.2.5.arm64_monterey.bottle.tar.gz
==> Downloading https://ghcr.io/v2/homebrew/core/python/3.10/manifests/3.10.1
Already downloaded: /Users/admin/Library/Caches/Homebrew/downloads/ba44b4cfaec4b0996a8fc2b2def6f21371f8c859781b668a30ceb2e6f4bbf3be--python@3.10-3.10.1.bottle_manifest.json
==> Downloading https://ghcr.io/v2/homebrew/core/python/3.10/blobs/sha256:610ffb
Already downloaded: /Users/admin/Library/Caches/Homebrew/downloads/9f33296799fb0f3d8dc0e02e5a3f0248cc3f930fecbe9d5484feebad2976e337--python@3.10--3.10.1.arm64_monterey.bottle.tar.gz
==> Downloading https://ghcr.io/v2/homebrew/core/sshuttle/manifests/1.0.5_1
Already downloaded: /Users/admin/Library/Caches/Homebrew/downloads/c55592ce45364b6f69fda5f5f6f5aa1d8ef201b2664d28ad8c0fddcdae6a6691--sshuttle-1.0.5_1.bottle_manifest.json
==> Downloading https://ghcr.io/v2/homebrew/core/sshuttle/blobs/sha256:31fad7e2b
Already downloaded: /Users/admin/Library/Caches/Homebrew/downloads/bb8029fd724136dd3f7540fd0a6e93e2ffe50cc16036a0a19242dbb2209ea38b--sshuttle--1.0.5_1.arm64_monterey.bottle.tar.gz
==> Installing dependencies for sshuttle: gdbm, mpdecimal, ca-certificates, openssl@1.1, readline, sqlite, xz and python@3.10
==> Installing sshuttle dependency: gdbm
==> Pouring gdbm--1.22.arm64_monterey.bottle.tar.gz
🍺  /opt/homebrew/Cellar/gdbm/1.22: 24 files, 1MB
==> Installing sshuttle dependency: mpdecimal
==> Pouring mpdecimal--2.5.1.arm64_monterey.bottle.tar.gz
🍺  /opt/homebrew/Cellar/mpdecimal/2.5.1: 71 files, 2.2MB
==> Installing sshuttle dependency: ca-certificates
==> Pouring ca-certificates--2021-10-26.all.bottle.tar.gz
==> Regenerating CA certificate bundle from keychain, this may take a while...
🍺  /opt/homebrew/Cellar/ca-certificates/2021-10-26: 3 files, 208.5KB
==> Installing sshuttle dependency: openssl@1.1
==> Pouring openssl@1.1--1.1.1m.arm64_monterey.bottle.tar.gz
🍺  /opt/homebrew/Cellar/openssl@1.1/1.1.1m: 8,081 files, 18MB
==> Installing sshuttle dependency: readline
==> Pouring readline--8.1.1.arm64_monterey.bottle.tar.gz
🍺  /opt/homebrew/Cellar/readline/8.1.1: 48 files, 1.7MB
==> Installing sshuttle dependency: sqlite
==> Pouring sqlite--3.37.1.arm64_monterey.bottle.tar.gz
🍺  /opt/homebrew/Cellar/sqlite/3.37.1: 11 files, 4.3MB
==> Installing sshuttle dependency: xz
==> Pouring xz--5.2.5.arm64_monterey.bottle.tar.gz
🍺  /opt/homebrew/Cellar/xz/5.2.5: 95 files, 1.4MB
==> Installing sshuttle dependency: python@3.10
==> Pouring python@3.10--3.10.1.arm64_monterey.bottle.tar.gz
==> /opt/homebrew/Cellar/python@3.10/3.10.1/bin/python3 -m ensurepip
==> /opt/homebrew/Cellar/python@3.10/3.10.1/bin/python3 -m pip install -v --no-d
🍺  /opt/homebrew/Cellar/python@3.10/3.10.1: 3,134 files, 57.9MB
==> Installing sshuttle
==> Pouring sshuttle--1.0.5_1.arm64_monterey.bottle.tar.gz
🍺  /opt/homebrew/Cellar/sshuttle/1.0.5_1: 651 files, 9MB
==> Running `brew cleanup sshuttle`...
Disable this behaviour by setting HOMEBREW_NO_INSTALL_CLEANUP.
Hide these hints with HOMEBREW_NO_ENV_HINTS (see `man brew`).
```

Running `sshuttle` as `admin` works:

```
admin ~ % /opt/homebrew/bin/sshuttle 
usage: sshuttle [-l [ip:]port] [-r [user@]sshserver[:port]] <subnets...>
sshuttle: error: at least one subnet, subnet file, or -N expected
```

Running as another user fails:

```
other-user ~ % /opt/homebrew/bin/sshuttle
Traceback (most recent call last):
  File "/opt/homebrew/bin/sshuttle", line 33, in <module>
    sys.exit(load_entry_point('sshuttle==1.0.5', 'console_scripts', 'sshuttle')())
  File "/opt/homebrew/bin/sshuttle", line 25, in importlib_load_entry_point
    return next(matches).load()
StopIteration
```

It seems that the cause is that some files installed by the `sshuttle` formula are not world-readable:

```
other-user ~ % ls -l /opt/homebrew/Cellar/sshuttle/1.0.5_1/libexec/lib/python3.10/site-packages/sshuttle-1.0.5-py3.10.egg-info
total 56
-rw-------  1 admin  admin  3373 29 Dec  2020 PKG-INFO
-rw-------  1 admin  admin  1498 29 Dec  2020 SOURCES.txt
-rw-------  1 admin  admin     1 29 Dec  2020 dependency_links.txt
-rw-------  1 admin  admin    52 29 Dec  2020 entry_points.txt
-rw-r--r--  1 admin  admin  1909 29 Dec  2020 installed-files.txt
-rw-------  1 admin  admin     7 29 Dec  2020 requires.txt
-rw-------  1 admin  admin     9 29 Dec  2020 top_level.txt
```

### What did you expect to happen?

I'd expect all data installed by Homebrew to be world-readable and all installed software to be runnable by any user.

### Step-by-step reproduction instructions (by running `brew` commands)

See **What happened** above.

**Comment by SMillerDev** [comment]
> I'd expect all data installed by Homebrew to be world-readable and all installed software to be runnable by any user.

That's not how homebrew works. Homebrew is only designed for single user usage.

**Comment by Feuermurmel** [comment]
Would it still be possible to fix the root cause of this issue, which is not related to multiple user account being used?

**Comment by carlocab** [comment]
This looks related: https://github.com/pypa/setuptools/issues/1328

We could probably fix up permissions somewhere here: https://github.com/Homebrew/brew/blob/3ba6afb1d3b3272bc17bf8ff978e071cd35502b1/Library/Homebrew/language/python.rb#L288-L293

I'm open to reviewing a pull request that implements a fix like this.

**Comment by Feuermurmel** [comment]
@carlocab Thanks for the pointer! 

@SMillerDev I'd like to provide a piece of frank feedback to you. Your answer threw me off and I've contemplated it for a while. I take your answer as unsympathetic and dismissive, as if I've made a mistake in reporting this issue I had and asking for help.

**Comment by SMillerDev** [comment]
> I take your answer as unsympathetic and dismissive, 

That's fine, I'm not here to make friends. I'm here to help homebrew thrive.

> as if I've made a mistake in reporting this issue I had and asking for help.

You were asking for help with an unsupported use case. So I'd say my answer was exactly how I meant it then. You don't have to like it, but at least you had a quick answer giving you a clear indication how likely this was to be fixed based on the issue.
