### ISSUE TITLE
`brew doctor` crashes

### ISSUE THREAD

**Issue by ritmas** [Homebrew/homebrew-core#9296]
It seems command `brew doctor` crashes after I restarted laptop once Java & last OSx security updates were installed.

```
Error: /usr/local/Homebrew/Library/Taps/homebrew/homebrew-science/opencv.rb:97: syntax error, unexpected <<, expecting keyword_end
<<<<<<< Updated upstream
  ^
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-science/opencv.rb:100: syntax error, unexpected ===, expecting keyword_end
=======
   ^
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-science/opencv.rb:105: syntax error, unexpected >>, expecting keyword_end
>>>>>>> Stashed changes
  ^
Please report this bug:
  http://docs.brew.sh/Troubleshooting.html
/usr/local/Homebrew/Library/Homebrew/formulary.rb:25:in `module_eval'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:25:in `load_formula'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:42:in `load_formula_from_path'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:97:in `load_file'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:214:in `load_file'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:88:in `klass'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:84:in `get_formula'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:208:in `get_formula'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:255:in `factory'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:286:in `from_keg'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:269:in `from_rack'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1425:in `block in installed'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1423:in `map'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1423:in `installed'
/usr/local/Homebrew/Library/Homebrew/diagnostic.rb:891:in `check_missing_deps'
/usr/local/Homebrew/Library/Homebrew/cmd/doctor.rb:43:in `block in doctor'
/usr/local/Homebrew/Library/Homebrew/cmd/doctor.rb:35:in `each'
/usr/local/Homebrew/Library/Homebrew/cmd/doctor.rb:35:in `doctor'
/usr/local/Homebrew/Library/Homebrew/brew.rb:94:in `<main>'
```

My brew config:
```
HOMEBREW_VERSION: 1.1.8-42-g1f97e31
ORIGIN: https://github.com/Homebrew/brew.git
HEAD: 1f97e3186a117541f127f6e52ce77238a2791147
Last commit: 25 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: f753aaec2a2e7cf1cbbbe10b263532965fb0e2f6
Core tap last commit: 2 hours ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_REPOSITORY: /usr/local/Homebrew
HOMEBREW_CELLAR: /usr/local/Cellar
HOMEBREW_BOTTLE_DOMAIN: https://homebrew.bintray.com
CPU: quad-core 64-bit broadwell
Homebrew Ruby: 2.0.0-p648
Clang: 8.0 build 800
Git: 2.8.2 => /usr/local/bin/git
Perl: /usr/bin/perl
Python: /usr/local/bin/python => /usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/bin/python2.7
Ruby: /usr/bin/ruby => /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin/ruby
Java: 1.7.0_25
macOS: 10.11.6-x86_64
Xcode: 8.2.1
CLT: 8.2.0.0.1.1480973914
X11: 2.7.11 => /opt/X11
```

**Comment by MikeMcQuaid** [comment]
> Error: /usr/local/Homebrew/Library/Taps/homebrew/homebrew-science/opencv.rb:97: syntax error, unexpected <<, expecting keyword_end
> <<<<<<< Updated upstream
>   ^
> /usr/local/Homebrew/Library/Taps/homebrew/homebrew-science/opencv.rb:100: syntax error, unexpected ===, expecting keyword_end
> =======
>    ^
> /usr/local/Homebrew/Library/Taps/homebrew/homebrew-science/opencv.rb:105: syntax error, unexpected >>, expecting keyword_end
> >>>>>>> Stashed changes
>   ^

This is a merge conflict you need to resolve. Alternatively, run `brew update-reset`.

**Comment by ritmas** [comment]
Issue is still present.
The output of `brew update-reset` was:

```
==> Fetching /usr/local/Homebrew...

==> Resetting /usr/local/Homebrew...
Branch master set up to track remote branch master from origin.
Reset branch 'master'

==> Fetching /usr/local/Homebrew/Library/Taps/caskroom/homebrew-cask...

==> Resetting /usr/local/Homebrew/Library/Taps/caskroom/homebrew-cask...
Branch master set up to track remote branch master from origin.
Reset branch 'master'
Your branch is up-to-date with 'origin/master'.

==> Fetching /usr/local/Homebrew/Library/Taps/glevine/homebrew-phpunit...

==> Resetting /usr/local/Homebrew/Library/Taps/glevine/homebrew-phpunit...
Branch master set up to track remote branch master from origin.
Reset branch 'master'
Your branch is up-to-date with 'origin/master'.

==> Fetching /usr/local/Homebrew/Library/Taps/homebrew/homebrew-apache...
remote: Counting objects: 2, done.
remote: Total 2 (delta 1), reused 1 (delta 1), pack-reused 1
Unpacking objects: 100% (2/2), done.
From https://github.com/Homebrew/homebrew-apache
 * [new branch]      javian-patch-1 -> origin/javian-patch-1

==> Resetting /usr/local/Homebrew/Library/Taps/homebrew/homebrew-apache...
Branch master set up to track remote branch master from origin.
Reset branch 'master'
Your branch is up-to-date with 'origin/master'.

==> Fetching /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core...

==> Resetting /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core...
Branch master set up to track remote branch master from origin.
Reset branch 'master'
Your branch is up-to-date with 'origin/master'.

==> Fetching /usr/local/Homebrew/Library/Taps/homebrew/homebrew-dupes...

==> Resetting /usr/local/Homebrew/Library/Taps/homebrew/homebrew-dupes...
Branch master set up to track remote branch master from origin.
Reset branch 'master'
Your branch is up-to-date with 'origin/master'.

==> Fetching /usr/local/Homebrew/Library/Taps/homebrew/homebrew-php...
remote: Counting objects: 24, done.
remote: Compressing objects: 100% (9/9), done.
remote: Total 24 (delta 19), reused 20 (delta 15), pack-reused 0
Unpacking objects: 100% (24/24), done.
From https://github.com/Homebrew/homebrew-php
 * [new branch]      70opcacherev3 -> origin/70opcacherev3
 * [new branch]      apxsdetectionfix -> origin/apxsdetectionfix
 * [new branch]      javian-patch-2 -> origin/javian-patch-2
 * [new branch]      javian-patch-3 -> origin/javian-patch-3
 * [new branch]      javian-patch-4 -> origin/javian-patch-4
 * [new branch]      javian-patch-5 -> origin/javian-patch-5

==> Resetting /usr/local/Homebrew/Library/Taps/homebrew/homebrew-php...
Branch master set up to track remote branch master from origin.
Reset branch 'master'
Your branch is up-to-date with 'origin/master'.

==> Fetching /usr/local/Homebrew/Library/Taps/homebrew/homebrew-python...

==> Resetting /usr/local/Homebrew/Library/Taps/homebrew/homebrew-python...
Branch master set up to track remote branch master from origin.
Reset branch 'master'
Your branch is up-to-date with 'origin/master'.

==> Fetching /usr/local/Homebrew/Library/Taps/homebrew/homebrew-science...

==> Resetting /usr/local/Homebrew/Library/Taps/homebrew/homebrew-science...
opencv.rb: needs merge
error: you need to resolve your current index first

==> Fetching /usr/local/Homebrew/Library/Taps/homebrew/homebrew-services...

==> Resetting /usr/local/Homebrew/Library/Taps/homebrew/homebrew-services...
Branch master set up to track remote branch master from origin.
Reset branch 'master'
Your branch is up-to-date with 'origin/master'.

==> Fetching /usr/local/Homebrew/Library/Taps/homebrew/homebrew-versions...

==> Resetting /usr/local/Homebrew/Library/Taps/homebrew/homebrew-versions...
Branch master set up to track remote branch master from origin.
Reset branch 'master'
Your branch is up-to-date with 'origin/master'.
```

**Comment by MikeMcQuaid** [comment]
What's the `brew doctor` and `brew config` output now?

**Comment by ritmas** [comment]
Actually, the same.

`brew doctor`:
```
Error: /usr/local/Homebrew/Library/Taps/homebrew/homebrew-science/opencv.rb:97: syntax error, unexpected <<, expecting keyword_end
<<<<<<< Updated upstream
  ^
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-science/opencv.rb:100: syntax error, unexpected ===, expecting keyword_end
=======
   ^
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-science/opencv.rb:105: syntax error, unexpected >>, expecting keyword_end
>>>>>>> Stashed changes
  ^
Please report this bug:
  http://docs.brew.sh/Troubleshooting.html
/usr/local/Homebrew/Library/Homebrew/formulary.rb:25:in `module_eval'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:25:in `load_formula'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:42:in `load_formula_from_path'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:97:in `load_file'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:214:in `load_file'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:88:in `klass'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:84:in `get_formula'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:208:in `get_formula'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:255:in `factory'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:286:in `from_keg'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:269:in `from_rack'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1425:in `block in installed'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1423:in `map'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1423:in `installed'
/usr/local/Homebrew/Library/Homebrew/diagnostic.rb:891:in `check_missing_deps'
/usr/local/Homebrew/Library/Homebrew/cmd/doctor.rb:43:in `block in doctor'
/usr/local/Homebrew/Library/Homebrew/cmd/doctor.rb:35:in `each'
/usr/local/Homebrew/Library/Homebrew/cmd/doctor.rb:35:in `doctor'
/usr/local/Homebrew/Library/Homebrew/brew.rb:94:in `<main>'
```

`brew config`:
```
HOMEBREW_VERSION: 1.1.8-42-g1f97e31
ORIGIN: https://github.com/Homebrew/brew.git
HEAD: 1f97e3186a117541f127f6e52ce77238a2791147
Last commit: 26 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: f753aaec2a2e7cf1cbbbe10b263532965fb0e2f6
Core tap last commit: 2 hours ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_REPOSITORY: /usr/local/Homebrew
HOMEBREW_CELLAR: /usr/local/Cellar
HOMEBREW_BOTTLE_DOMAIN: https://homebrew.bintray.com
CPU: quad-core 64-bit broadwell
Homebrew Ruby: 2.0.0-p648
Clang: 8.0 build 800
Git: 2.8.2 => /usr/local/bin/git
Perl: /usr/bin/perl
Python: /usr/local/bin/python => /usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/bin/python2.7
Ruby: /usr/bin/ruby => /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin/ruby
Java: 1.7.0_25
macOS: 10.11.6-x86_64
Xcode: 8.2.1
CLT: 8.2.0.0.1.1480973914
X11: 2.7.11 => /opt/X11
```

**Comment by MikeMcQuaid** [comment]
Please try to `cd /usr/local/Homebrew/Library/Taps/homebrew/homebrew-science/ && git checkout --force -B master origin/master`.

**Comment by MikeMcQuaid** [comment]
Also for your own future reference I recommend reading https://help.github.com/articles/resolving-a-merge-conflict-using-the-command-line/

**Comment by ritmas** [comment]
Yes, `checkout`'ing to master in this manner solved the issue - `brew doctor` works as expected. Thanks!

**Comment by MikeMcQuaid** [comment]
For my own reference: was it the command I supplied that fixed it? Checking the `--force` handles this case.
