### ISSUE TITLE
Installing nginx with Phusion Passenger and RTMP module fails

### ISSUE THREAD

**Issue by SolcheSachen** [Homebrew/homebrew-core#9405]
Hello,

I am unable to install nginx with the Phusion Passenger and RTMP modules. I am running Ubuntu 16.04.

Here is the full output of running "brew install nginx-full --with-passenger --with-rtmp-module" (please note that I've run this command several times now, so some parts that succeeded during the first installation attempt might be missing)
```
==> Installing nginx-full from homebrew/nginx
==> Installing dependencies for homebrew/nginx/nginx-full: openssl, xz, passenger, rtmp-nginx-module
==> Installing homebrew/nginx/nginx-full dependency: openssl
==> Downloading https://www.openssl.org/source/openssl-1.0.2k.tar.gz
######################################################################## 100,0%
==> Downloading https://github.com/openssl/openssl/pull/1524.patch
Already downloaded: /home/main/.cache/Homebrew/openssl--patch-853a15755d3bc2b561d64c4f5d58a7ff4885e5cdbacbf429ce93b477e0d3d68e.patch
==> Patching
==> Applying 1524.patch
patching file Configure
Hunk #1 succeeded at 1723 (offset 2 lines).
==> perl ./Configure --prefix=/home/main/.linuxbrew/Cellar/openssl/1.0.2k --openssldir=/home/main/.linuxbrew/etc/openssl no-ssl2 zlib-dynamic shared enable-cms -isystem/home/main/
==> make depend
==> make
==> make test
==> make install MANDIR=/home/main/.linuxbrew/Cellar/openssl/1.0.2k/share/man MANSUFFIX=ssl
==> Downloading https://curl.haxx.se/ca/cacert-2016-04-20.pem
Already downloaded: /home/main/.cache/Homebrew/openssl--cacert-2016-04.pem
==> Caveats
A CA file has been bootstrapped using certificates from the SystemRoots
keychain. To add additional certificates (e.g. the certificates added in
the System keychain), place .pem files in
  /home/main/.linuxbrew/etc/openssl/certs

and run
  /home/main/.linuxbrew/opt/openssl/bin/c_rehash

==> Summary
🍺  /home/main/.linuxbrew/Cellar/openssl/1.0.2k: 1,703 files, 14.6M, built in 4 minutes 46 seconds
==> Installing homebrew/nginx/nginx-full dependency: xz
==> Downloading https://fossies.org/linux/misc/xz-5.2.3.tar.gz
######################################################################## 100,0%
==> ./configure --disable-silent-rules --prefix=/home/main/.linuxbrew/Cellar/xz/5.2.3
==> make check
==> make install
🍺  /home/main/.linuxbrew/Cellar/xz/5.2.3: 99 files, 1.8M, built in 25 seconds
==> Installing homebrew/nginx/nginx-full dependency: passenger
==> Downloading https://s3.amazonaws.com/phusion-passenger/releases/passenger-5.1.2.tar.gz
######################################################################## 100,0%
==> /usr/bin/rake apache2
Last 15 lines from /home/main/.cache/Homebrew/Logs/passenger/01.rake:
/usr/bin/g++-5 -o buildout/apache2/module_libboost_oxt/oxt/system_calls.o  -Isrc/cxx_supportlib -Isrc/cxx_supportlib/vendor-copy -Isrc/cxx_supportlib/vendor-modified -fPIC -DLINUX -D_REENTRANT -D_GNU_SOURCE -I/home/main/.linuxbrew/opt/apr/libexec/include/apr-1 -I/home/main/.linuxbrew/opt/apr-util/libexec/include/apr-1 -I/home/main/.linuxbrew/opt/openssl/include -D_REENTRANT -I/usr/local/include -Wall -Wextra -Wno-unused-parameter -Wno-parentheses -Wpointer-arith -Wwrite-strings -Wno-long-long -Wno-missing-field-initializers -feliminate-unused-debug-symbols -feliminate-unused-debug-types -fvisibility=hidden -DVISIBILITY_ATTRIBUTE_SUPPORTED -Wno-attributes -ggdb -DHAS_ALLOCA_H -DHAVE_ACCEPT4 -DHAS_SFENCE -DHAS_LFENCE -DPASSENGER_DEBUG -DBOOST_DISABLE_ASSERTS -std=gnu++11 -Wno-unused-local-typedefs -DHASH_NAMESPACE="__gnu_cxx" -DHASH_MAP_HEADER="<hash_map>" -DHASH_MAP_CLASS="hash_map" -DHASH_FUN_H="<hash_fun.h>" -c src/cxx_supportlib/oxt/system_calls.cpp
rm -rf buildout/apache2/module_libboost_oxt.a
ar cru buildout/apache2/module_libboost_oxt.a buildout/apache2/module_libboost_oxt/boost/error_code.o buildout/apache2/module_libboost_oxt/boost/once_atomic.o buildout/apache2/module_libboost_oxt/boost/thread.o buildout/apache2/module_libboost_oxt/boost/once.o buildout/apache2/module_libboost_oxt/boost/future.o buildout/apache2/module_libboost_oxt/boost/tss_null.o buildout/apache2/module_libboost_oxt/boost/posix_api.o buildout/apache2/module_libboost_oxt/boost/wc_regex_traits.o buildout/apache2/module_libboost_oxt/boost/cregex.o buildout/apache2/module_libboost_oxt/boost/regex_raw_buffer.o buildout/apache2/module_libboost_oxt/boost/cpp_regex_traits.o buildout/apache2/module_libboost_oxt/boost/c_regex_traits.o buildout/apache2/module_libboost_oxt/boost/static_mutex.o buildout/apache2/module_libboost_oxt/boost/instances.o buildout/apache2/module_libboost_oxt/boost/winstances.o buildout/apache2/module_libboost_oxt/boost/regex_traits_defaults.o buildout/apache2/module_libboost_oxt/boost/regex.o buildout/apache2/module_libboost_oxt/boost/regex_debug.o buildout/apache2/module_libboost_oxt/boost/wide_posix_api.o buildout/apache2/module_libboost_oxt/oxt/implementation.o buildout/apache2/module_libboost_oxt/oxt/system_calls.o
ar: `u' modifier ignored since `D' is the default (see `U')
ranlib buildout/apache2/module_libboost_oxt.a
/usr/bin/gcc-5 -o buildout/apache2/mod_passenger.o  -Isrc/agent -Isrc/cxx_supportlib -Isrc/cxx_supportlib/vendor-copy -Isrc/cxx_supportlib/vendor-modified -fPIC -DLINUX -D_REENTRANT -D_GNU_SOURCE -I/home/main/.linuxbrew/opt/apr/libexec/include/apr-1 -I/home/main/.linuxbrew/opt/apr-util/libexec/include/apr-1 -I/home/main/.linuxbrew/opt/openssl/include -D_REENTRANT -I/usr/local/include -Wall -Wextra -Wno-unused-parameter -Wno-parentheses -Wpointer-arith -Wwrite-strings -Wno-long-long -Wno-missing-field-initializers -feliminate-unused-debug-symbols -feliminate-unused-debug-types -fvisibility=hidden -DVISIBILITY_ATTRIBUTE_SUPPORTED -Wno-attributes -ggdb -DHAS_ALLOCA_H -DHAVE_ACCEPT4 -DHAS_SFENCE -DHAS_LFENCE -DPASSENGER_DEBUG -DBOOST_DISABLE_ASSERTS -c src/apache2_module/mod_passenger.c
src/apache2_module/mod_passenger.c:26:19: fatal error: httpd.h: file or directory not found
compilation terminated.
rake aborted!
Command failed with status (1): [/usr/bin/gcc-5 -o buildout/apache2/mod_passenger.o  -Isrc/agent -Isrc/cxx_supportlib -Isrc/cxx_supportlib/vendor-copy -Isrc/cxx_supportlib/vendor-modified -fPIC -DLINUX -D_REENTRANT -D_GNU_SOURCE -I/home/main/.linuxbrew/opt/apr/libexec/include/apr-1 -I/home/main/.linuxbrew/opt/apr-util/libexec/include/apr-1 -I/home/main/.linuxbrew/opt/openssl/include -D_REENTRANT -I/usr/local/include -Wall -Wextra -Wno-unused-parameter -Wno-parentheses -Wpointer-arith -Wwrite-strings -Wno-long-long -Wno-missing-field-initializers -feliminate-unused-debug-symbols -feliminate-unused-debug-types -fvisibility=hidden -DVISIBILITY_ATTRIBUTE_SUPPORTED -Wno-attributes -ggdb -DHAS_ALLOCA_H -DHAVE_ACCEPT4 -DHAS_SFENCE -DHAS_LFENCE -DPASSENGER_DEBUG -DBOOST_DISABLE_ASSERTS -c src/apache2_module/mod_passenger.c]
/tmp/passenger-20170129-13326-1yq019p/passenger-5.1.2/build/support/cplusplus.rb:52:in `run_compiler'
/tmp/passenger-20170129-13326-1yq019p/passenger-5.1.2/build/support/cplusplus.rb:96:in `compile_c'
/tmp/passenger-20170129-13326-1yq019p/passenger-5.1.2/build/support/cplusplus.rb:153:in `block in define_c_object_compilation_task'
Tasks: TOP => apache2 => buildout/apache2/mod_passenger.so => buildout/apache2/mod_passenger.o
(See full trace by running task with --trace)

READ THIS: https://github.com/Linuxbrew/brew/blob/master/docs/Troubleshooting.md#troubleshooting
```

As requested, here are the outputs of

brew config
```
HOMEBREW_VERSION: 1.1.6
ORIGIN: https://github.com/Linuxbrew/brew
HEAD: 98e06da6124e92192c14b02ae383fcd8010b19a3
Last commit: 3 weeks ago
Core tap ORIGIN: https://github.com/Linuxbrew/homebrew-core
Core tap HEAD: 1c0be3d3419c479e41b3f5b526313ce6d658c765
Core tap last commit: vor 13 Stunden
HOMEBREW_PREFIX: /home/main/.linuxbrew
HOMEBREW_REPOSITORY: /home/main/.linuxbrew
HOMEBREW_CELLAR: /home/main/.linuxbrew/Cellar
HOMEBREW_BOTTLE_DOMAIN: https://linuxbrew.bintray.com
CPU: octa-core 64-bit broadwell
Homebrew Ruby: 2.3.1 => /usr/bin/ruby2.3
Clang: N/A
Git: 2.7.4 => /usr/bin/git
Perl: /usr/bin/perl
Python: /usr/bin/python => /usr/bin/python2.7
Ruby: /usr/bin/ruby => /usr/bin/ruby2.3
Java: openjdk version "1.8.0_121"
Kernel: Linux 4.4.0-59-generic x86_64 GNU/Linux
OS: Ubuntu 16.04.1 LTS
Codename: xenial
OS glibc: 2.23
OS gcc: 5.4.0
Linuxbrew glibc: N/A
Linuxbrew gcc: N/A
Linuxbrew xorg: N/A
```

brew doctor
```
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry and just ignore them. Thanks!

Warning: Homebrew's sbin was not found in your PATH but you have installed
formulae that put executables in /home/main/.linuxbrew/sbin.
Consider setting the PATH for example like so
  echo 'export PATH="/home/main/.linuxbrew/sbin:$PATH"' >> ~/.bash_profile
```

brew gist-logs nginx
`Error: No logs.`

Thanks in advance for looking at my issue. If you need any further information, just let me know.

Kind regards
Benjamin

**Comment by MikeMcQuaid** [comment]
> I am running Ubuntu 16.04.

Report this to Linuxbrew.
