### ISSUE TITLE
Upgrade youtube-dl dependency for mpsyt

### ISSUE THREAD

**Issue by ed1d1a8d** [Homebrew/homebrew-core#9461]
# Please follow the general troubleshooting steps first:

- [X] Ran `brew update` and retried your prior step?
- [X] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?
- [X] Confirmed this is problem with specific formulae and not Homebrew/brew? If it's a general Homebrew/brew problem please file this issue at https://github.com/Homebrew/brew/issues/new

### Bug reports:

It seems that mpsyt needs to have its youtube-dl dependency updated. I got the following error after searching for a video:

> ERROR: Signature extraction failed: Traceback (most recent call last):
  File "/usr/local/Cellar/mps-youtube/0.2.7.1/libexec/lib/python3.6/site-packages/youtube_dl/extractor/youtube.py", line 1005, in _decrypt_signature
    video_id, player_url, s
  File "/usr/local/Cellar/mps-youtube/0.2.7.1/libexec/lib/python3.6/site-packages/youtube_dl/extractor/youtube.py", line 919, in _extract_signature_function
    errnote='Download of %s failed' % player_url)
  File "/usr/local/Cellar/mps-youtube/0.2.7.1/libexec/lib/python3.6/site-packages/youtube_dl/extractor/common.py", line 519, in _download_webpage
    res = self._download_webpage_handle(url_or_request, video_id, note, errnote, fatal, encoding=encoding, data=data, headers=headers, query=query)
  File "/usr/local/Cellar/mps-youtube/0.2.7.1/libexec/lib/python3.6/site-packages/youtube_dl/extractor/common.py", line 426, in _download_webpage_handle
    urlh = self._request_webpage(url_or_request, video_id, note, errnote, fatal, data=data, headers=headers, query=query)
  File "/usr/local/Cellar/mps-youtube/0.2.7.1/libexec/lib/python3.6/site-packages/youtube_dl/extractor/common.py", line 406, in _request_webpage
    return self._downloader.urlopen(url_or_request)
  File "/usr/local/Cellar/mps-youtube/0.2.7.1/libexec/lib/python3.6/site-packages/youtube_dl/YoutubeDL.py", line 2000, in urlopen
    req = sanitized_Request(req)
  File "/usr/local/Cellar/mps-youtube/0.2.7.1/libexec/lib/python3.6/site-packages/youtube_dl/utils.py", line 518, in sanitized_Request
    return compat_urllib_request.Request(sanitize_url(url), *args, **kwargs)
  File "/usr/local/opt/python3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 329, in __init__
    self.full_url = url
  File "/usr/local/opt/python3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 355, in full_url
    self._parse()
  File "/usr/local/opt/python3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 384, in _parse
    raise ValueError("unknown url type: %r" % self.full_url)
ValueError: unknown url type: '/yts/jsbin/player-en_US-vflV3n15C/base.js'
 (caused by ValueError("unknown url type: '/yts/jsbin/player-en_US-vflV3n15C/base.js'",)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

**Comment by MikeMcQuaid** [comment]
Fixed by https://github.com/Homebrew/homebrew-core/pull/9512, thanks for submitting the PR.
