### ISSUE TITLE
Can't install `dotnet` on Apple Silicon Macs

### ISSUE THREAD

**Issue by li-bei** [Homebrew/homebrew-core#96664]
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

```shell
libei@Beis-MacBook-Pro-2021 ~ % brew config
HOMEBREW_VERSION: 3.4.1
ORIGIN: https://github.com/Homebrew/brew
HEAD: ea0ddc3297739b7380887d4a7e6b6590c314dca9
Last commit: 4 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 9513ca077227920810d8687f2f7d73df50dd81b1
Core tap last commit: 6 hours ago
Core tap branch: master
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_CORE_GIT_REMOTE: https://github.com/Homebrew/homebrew-core
HOMEBREW_MAKE_JOBS: 10
Homebrew Ruby: 2.6.8 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: 10-core 64-bit arm_firestorm_icestorm
Clang: 13.0.0 build 1300
Git: 2.35.1 => /opt/homebrew/bin/git
Curl: 7.77.0 => /usr/bin/curl
macOS: 12.2.1-arm64
CLT: 13.2.0.0.1.1638488800
Xcode: 13.2.1
Rosetta 2: false
libei@Beis-MacBook-Pro-2021 ~ % brew doctor
Your system is ready to brew.
```

### Verification

- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.

### What were you trying to do (and why)?

Install `dotnet`.

### What happened (include all command output)?

```shell
libei@Beis-MacBook-Pro-2021 ~ % brew install dotnet --verbose --debug
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::FormulaLoader): loading /opt/homebrew/Library/Taps/homebrew/homebrew-core/Formula/dotnet.rb
Warning: Treating dotnet as a formula. For the cask, use homebrew/cask/dotnet
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::FormulaLoader): loading /opt/homebrew/Library/Taps/homebrew/homebrew-core/Formula/cmake.rb
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::FormulaLoader): loading /opt/homebrew/Library/Taps/homebrew/homebrew-core/Formula/pkg-config.rb
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::FormulaLoader): loading /opt/homebrew/Library/Taps/homebrew/homebrew-core/Formula/python@3.10.rb
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::FormulaLoader): loading /opt/homebrew/Library/Taps/homebrew/homebrew-core/Formula/gdbm.rb
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::FormulaLoader): loading /opt/homebrew/Library/Taps/homebrew/homebrew-core/Formula/mpdecimal.rb
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::FormulaLoader): loading /opt/homebrew/Library/Taps/homebrew/homebrew-core/Formula/openssl@1.1.rb
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::FormulaLoader): loading /opt/homebrew/Library/Taps/homebrew/homebrew-core/Formula/ca-certificates.rb
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::FormulaLoader): loading /opt/homebrew/Library/Taps/homebrew/homebrew-core/Formula/readline.rb
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::FormulaLoader): loading /opt/homebrew/Library/Taps/homebrew/homebrew-core/Formula/sqlite.rb
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::FormulaLoader): loading /opt/homebrew/Library/Taps/homebrew/homebrew-core/Formula/xz.rb
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::FormulaLoader): loading /opt/homebrew/Library/Taps/homebrew/homebrew-core/Formula/icu4c.rb
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::FormulaLoader): loading /opt/homebrew/Library/Taps/homebrew/homebrew-core/Formula/gnu-sed.rb
==> Downloading https://ghcr.io/v2/homebrew/core/dotnet/manifests/6.0.103
/opt/homebrew/Library/Homebrew/shims/shared/curl --disable --cookie /dev/null --globoff --show-error --user-agent Homebrew/3.4.1\ \(Macintosh\;\ arm64\ Mac\ OS\ X\ 12.2.1\)\ curl/7.77.0 --header Accept-Language:\ en --retry 3 --header Accept:\ application/vnd.oci.image.index.v1\+json --header Authorization:\ Bearer\ QQ== --location --silent --head --request GET https://ghcr.io/v2/homebrew/core/dotnet/manifests/6.0.103
Already downloaded: /Users/libei/Library/Caches/Homebrew/downloads/f4e23ecc109e1d91e0d2f9991c6ac423fa926e81fa71a27ad4c342dfe0bb8998--dotnet-6.0.103.bottle_manifest.json
==> Downloading https://ghcr.io/v2/homebrew/core/dotnet/blobs/sha256:2ff313f22047d96e30f1f8731ce1134ba7768c5dd74aab97f16dbcf68ea2fd10
/opt/homebrew/Library/Homebrew/shims/shared/curl --disable --cookie /dev/null --globoff --show-error --user-agent Homebrew/3.4.1\ \(Macintosh\;\ arm64\ Mac\ OS\ X\ 12.2.1\)\ curl/7.77.0 --header Accept-Language:\ en --retry 3 --header Authorization:\ Bearer\ QQ== --location --silent --head --request GET https://ghcr.io/v2/homebrew/core/dotnet/blobs/sha256:2ff313f22047d96e30f1f8731ce1134ba7768c5dd74aab97f16dbcf68ea2fd10
Already downloaded: /Users/libei/Library/Caches/Homebrew/downloads/868ff93adce04e218d7c83dd2c7cb45bdb536398c0a9eac860a9cd1e4c5986bf--dotnet--6.0.103.arm64_monterey.bottle.tar.gz
==> Verifying checksum for '868ff93adce04e218d7c83dd2c7cb45bdb536398c0a9eac860a9cd1e4c5986bf--dotnet--6.0.103.arm64_monterey.bottle.tar.gz'
/opt/homebrew/Library/Homebrew/shims/shared/git --version
==> Pouring dotnet--6.0.103.arm64_monterey.bottle.tar.gz
tar --extract --no-same-owner --file /Users/libei/Library/Caches/Homebrew/downloads/868ff93adce04e218d7c83dd2c7cb45bdb536398c0a9eac860a9cd1e4c5986bf--dotnet--6.0.103.arm64_monterey.bottle.tar.gz --directory /private/tmp/d20220311-4481-7yfw6e
cp -pR /private/tmp/d20220311-4481-7yfw6e/dotnet/. /opt/homebrew/Cellar/dotnet
cp: /private/tmp/d20220311-4481-7yfw6e/dotnet/./6.0.103/libexec/sdk/6.0.103/Sdks/Microsoft.NET.Sdk/codestyle/cs/Microsoft.CodeAnalysis.CSharp.CodeStyle.dll: Operation not permitted
cp: /private/tmp/d20220311-4481-7yfw6e/dotnet/./6.0.103/libexec/sdk/6.0.103/DotnetTools/dotnet-format/Microsoft.CodeAnalysis.CSharp.Workspaces.dll: Operation not permitted
cp: /private/tmp/d20220311-4481-7yfw6e/dotnet/./6.0.103/libexec/sdk/6.0.103/DotnetTools/dotnet-watch/6.0.103-servicing.22124.18/tools/net6.0/any/Microsoft.CodeAnalysis.CSharp.Workspaces.dll: Operation not permitted
Error: Failure while executing; `cp -pR /private/tmp/d20220311-4481-7yfw6e/dotnet/. /opt/homebrew/Cellar/dotnet` exited with 1. Here's the output:
cp: /private/tmp/d20220311-4481-7yfw6e/dotnet/./6.0.103/libexec/sdk/6.0.103/Sdks/Microsoft.NET.Sdk/codestyle/cs/Microsoft.CodeAnalysis.CSharp.CodeStyle.dll: Operation not permitted
cp: /private/tmp/d20220311-4481-7yfw6e/dotnet/./6.0.103/libexec/sdk/6.0.103/DotnetTools/dotnet-format/Microsoft.CodeAnalysis.CSharp.Workspaces.dll: Operation not permitted
cp: /private/tmp/d20220311-4481-7yfw6e/dotnet/./6.0.103/libexec/sdk/6.0.103/DotnetTools/dotnet-watch/6.0.103-servicing.22124.18/tools/net6.0/any/Microsoft.CodeAnalysis.CSharp.Workspaces.dll: Operation not permitted

/opt/homebrew/Library/Homebrew/system_command.rb:302:in `assert_success!'
/opt/homebrew/Library/Homebrew/system_command.rb:65:in `run!'
/opt/homebrew/Library/Homebrew/system_command.rb:40:in `run'
/opt/homebrew/Library/Homebrew/system_command.rb:44:in `run!'
/opt/homebrew/Library/Homebrew/system_command.rb:32:in `system_command!'
/opt/homebrew/Library/Homebrew/unpack_strategy/directory.rb:27:in `block in extract_to_dir'
/opt/homebrew/Library/Homebrew/unpack_strategy/directory.rb:26:in `each'
/opt/homebrew/Library/Homebrew/unpack_strategy/directory.rb:26:in `extract_to_dir'
/opt/homebrew/Library/Homebrew/unpack_strategy.rb:142:in `extract'
/opt/homebrew/Library/Homebrew/unpack_strategy.rb:162:in `block in extract_nestedly'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/tmpdir.rb:93:in `mktmpdir'
/opt/homebrew/Library/Homebrew/unpack_strategy.rb:146:in `extract_nestedly'
/opt/homebrew/Library/Homebrew/download_strategy.rb:99:in `stage'
/opt/homebrew/Library/Homebrew/download_strategy.rb:37:in `stage'
/opt/homebrew/Library/Homebrew/software_spec.rb:356:in `stage'
/opt/homebrew/Library/Homebrew/formula_installer.rb:1206:in `block in pour'
/opt/homebrew/Library/Homebrew/extend/pathname.rb:303:in `block in cd'
/opt/homebrew/Library/Homebrew/extend/pathname.rb:303:in `chdir'
/opt/homebrew/Library/Homebrew/extend/pathname.rb:303:in `cd'
/opt/homebrew/Library/Homebrew/formula_installer.rb:1205:in `pour'
/opt/homebrew/Library/Homebrew/formula_installer.rb:430:in `install'
/opt/homebrew/Library/Homebrew/upgrade.rb:208:in `install_formula'
/opt/homebrew/Library/Homebrew/install.rb:327:in `install_formula'
/opt/homebrew/Library/Homebrew/install.rb:317:in `block in install_formulae'
/opt/homebrew/Library/Homebrew/install.rb:316:in `each'
/opt/homebrew/Library/Homebrew/install.rb:316:in `install_formulae'
/opt/homebrew/Library/Homebrew/cmd/install.rb:218:in `install'
/opt/homebrew/Library/Homebrew/brew.rb:110:in `<main>'
```

### What did you expect to happen?

Install successfully.

### Step-by-step reproduction instructions (by running `brew` commands)

On a M1* Mac:

```shell
brew install dotnet
```

**Comment by carlocab** [comment]
Please provide the requested information instead of modifying the template. We can reopen this when you do so.

I'd also like to remind you of this notice in the bug report form:

> Please note we will close your issue without comment if you do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.

**Comment by li-bei** [comment]
@carlocab Sorry for missed the `brew config` and `brew doctor` part. Description updated.

**Comment by gromgit** [comment]
> ```shell
> cp -pR /private/tmp/d20220311-4481-7yfw6e/dotnet/. /opt/homebrew/Cellar/dotnet
> cp: /private/tmp/d20220311-4481-7yfw6e/dotnet/./6.0.103/libexec/sdk/6.0.103/Sdks/Microsoft.NET.Sdk/codestyle/cs/Microsoft.CodeAnalysis.CSharp.CodeStyle.dll: Operation not permitted
> cp: /private/tmp/d20220311-4481-7yfw6e/dotnet/./6.0.103/libexec/sdk/6.0.103/DotnetTools/dotnet-format/Microsoft.CodeAnalysis.CSharp.Workspaces.dll: Operation not permitted
> cp: /private/tmp/d20220311-4481-7yfw6e/dotnet/./6.0.103/libexec/sdk/6.0.103/DotnetTools/dotnet-watch/6.0.103-servicing.22124.18/tools/net6.0/any/Microsoft.CodeAnalysis.CSharp.Workspaces.dll: Operation not permitted
> ```

Are you running an antivirus program or other security software on your Mac? If so, try disabling it and running the `brew install` again.

**Comment by li-bei** [comment]
@gromgit Ah yes! I turned off the security software and installed successfully. Really thanks!
