### ISSUE TITLE
Terminator dies with rocessLookupError: [Errno 3] assume no such process (originated from sysctl(KERN_PROCARGS2) -> EINVAL)

### ISSUE THREAD

**Issue by Montanadude** [Homebrew/homebrew-core#98187]
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

```shell
brew config
HOMEBREW_VERSION: 3.4.4
ORIGIN: https://github.com/Homebrew/brew
HEAD: 5f5af43244eaece1f09d695603e1a261676713a0
Last commit: 4 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 7d396b9710ab94de1a983eb0178d28c217b4866c
Core tap last commit: 2 hours ago
Core tap branch: master
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CASK_OPTS: []
HOMEBREW_CORE_GIT_REMOTE: https://github.com/Homebrew/homebrew-core
HOMEBREW_DISPLAY: /private/tmp/com.apple.launchd.h2nGb4Pg43/org.xquartz:0
HOMEBREW_MAKE_JOBS: 8
Homebrew Ruby: 2.6.8 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: octa-core 64-bit westmere
Clang: 13.1.6 build 1316
Git: 2.35.1 => /usr/local/bin/git
Curl: 7.77.0 => /usr/bin/curl
macOS: 12.2.1-x86_64
CLT: 13.3.0.0.1.1645755326
Xcode: N/A
Rosetta 2: true

brew doctor
Your system is ready to brew.
```

### Verification

- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.

### What were you trying to do (and why)?

I recently received a new MacBook Pro, and i
installed homebrew and then 
ran brew install terminator and when I tried to run it, I just get

### What happened (include all command output)?

```
terminator                                                                                                          ok  17:54:20
Traceback (most recent call last):
  File "/usr/local/Cellar/terminator/2.1.1/libexec/lib/python3.9/site-packages/psutil/_psosx.py", line 365, in catch_zombie
    yield
  File "/usr/local/Cellar/terminator/2.1.1/libexec/lib/python3.9/site-packages/psutil/_psosx.py", line 431, in cmdline
    return cext.proc_cmdline(self.pid)
ProcessLookupError: [Errno 3] assume no such process (originated from sysctl(KERN_PROCARGS2) -> EINVAL)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/terminator", line 61, in <module>
    ibus_running = [p for p in psutil.process_iter() if p.name() == 'ibus-daemon' and p.username() == username]
  File "/usr/local/bin/terminator", line 61, in <listcomp>
    ibus_running = [p for p in psutil.process_iter() if p.name() == 'ibus-daemon' and p.username() == username]
  File "/usr/local/Cellar/terminator/2.1.1/libexec/lib/python3.9/site-packages/psutil/__init__.py", line 624, in name
    cmdline = self.cmdline()
  File "/usr/local/Cellar/terminator/2.1.1/libexec/lib/python3.9/site-packages/psutil/__init__.py", line 677, in cmdline
    return self._proc.cmdline()
  File "/usr/local/Cellar/terminator/2.1.1/libexec/lib/python3.9/site-packages/psutil/_psosx.py", line 344, in wrapper
    return fun(self, *args, **kwargs)
  File "/usr/local/Cellar/terminator/2.1.1/libexec/lib/python3.9/site-packages/psutil/_psosx.py", line 431, in cmdline
    return cext.proc_cmdline(self.pid)
  File "/usr/local/Cellar/python@3.9/3.9.12/Frameworks/Python.framework/Versions/3.9/lib/python3.9/contextlib.py", line 137, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/usr/local/Cellar/terminator/2.1.1/libexec/lib/python3.9/site-packages/psutil/_psosx.py", line 376, in catch_zombie
    raise ZombieProcess(proc.pid, proc._name, proc._ppid)
psutil.ZombieProcess: psutil.ZombieProcess process still exists but it's a zombie (pid=69475)
```

### What did you expect to happen?

For the program to run a terminator window and not crash

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
brew install terminator
terminator
```

**Comment by gromgit** [comment]
Just tried installing `terminator` myself on M1 Monterey under Rosetta:
![image](https://user-images.githubusercontent.com/215702/161006050-29b56ce4-0f6f-411e-b83a-62cb9b9b71fb.png)
It's got some warnings, and `arch` returns `i386` in the Rosetta'd Terminator shell for some reason, but no crashes, so it's probably something local to your machine.

Try reinstalling `terminator` and all its dependencies:
```
brew reinstall $(brew deps terminator) terminator
```
