### ISSUE TITLE
No available formula with the name "postgresql93"

### ISSUE THREAD

**Issue by Empact** [Homebrew/homebrew-core#9990]
Output of `brew uninstall --debug some-other-keg` is:

```
/usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::FormulaLoader): loading /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/xz.rb
Error: No available formula with the name "postgresql93" 
/usr/local/Homebrew/Library/Homebrew/formulary.rb:227:in `get_formula'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:255:in `factory'
/usr/local/Homebrew/Library/Homebrew/dependency.rb:32:in `to_formula'
/usr/local/Homebrew/Library/Homebrew/dependency.rb:97:in `block in expand'
/usr/local/Homebrew/Library/Homebrew/dependencies.rb:9:in `each'
/usr/local/Homebrew/Library/Homebrew/dependencies.rb:9:in `each'
/usr/local/Homebrew/Library/Homebrew/dependency.rb:84:in `expand'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1515:in `recursive_dependencies'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1542:in `missing_dependencies'
/usr/local/Homebrew/Library/Homebrew/keg.rb:143:in `block in find_some_installed_dependents'
/usr/local/Homebrew/Library/Homebrew/keg.rb:142:in `each'
/usr/local/Homebrew/Library/Homebrew/keg.rb:142:in `find_some_installed_dependents'
/usr/local/Homebrew/Library/Homebrew/cmd/uninstall.rb:90:in `check_for_dependents'
/usr/local/Homebrew/Library/Homebrew/cmd/uninstall.rb:83:in `handle_unsatisfied_dependents'
/usr/local/Homebrew/Library/Homebrew/cmd/uninstall.rb:31:in `uninstall'
/usr/local/Homebrew/Library/Homebrew/brew.rb:94:in `<main>'
```

Adding some debug output to `Dependency.expand` reveals:

```
#<Formula postgis (stable) /usr/local/Homebrew/Library/Taps/johnschultz/homebrew-postgis-for-93/postgis.rb>
#<Dependencies: [#<Dependency: "pkg-config" [:build]>, #<Dependency: "gpp" [:build]>, #<Dependency: "postgresql93" []>, #<Dependency: "proj" []>, #<Dependency: "geos" []>, #<Dependency: "json-c" []>, #<Dependency: "gdal" [:recommended]>, #<Dependency: "sfcgal" [:recommended]>]>
#<Dependency: "postgresql93" []>
```

Skipping the dependencies that raise in `#to_formula` works for me:

```ruby
    def expand(dependent, deps = dependent.deps, &block)
      # Keep track dependencies to avoid infinite cyclic dependency recursion.
      @expand_stack ||= []
      @expand_stack.push dependent.name

      expanded_deps = []

      deps.each do |dep|
        next if dependent.name == dep.name

        case action(dependent, dep, &block)
        when :prune
          next
        when :skip
          next if @expand_stack.include? dep.name
          expanded_deps.concat(expand(dep.to_formula, &block))
        when :keep_but_prune_recursive_deps
          expanded_deps << dep
        else
          next if @expand_stack.include? dep.name
          formula = dep.to_formula rescue next
          expanded_deps.concat(expand(formula, &block))
          expanded_deps << dep
        end
      end

      merge_repeats(expanded_deps)
    ensure
      @expand_stack.pop
    end
```

**Comment by MikeMcQuaid** [comment]
Please fill in the issue template so we have the information we need and refile this at Homebrew/brew (which it'll tell you to do, too). Thanks!
